### ISSUE TITLE
"Punkt Apteczny" is not a brand

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#100]
It is a legal term for a small rural drugstore - see https://pl.wikipedia.org/wiki/Punkt_apteczny

**Comment by matkoniecz** [comment]
Sorry, only now I spotted

> I'm not quite ready to have people help yet

in https://github.com/osmlab/name-suggestion-index/issues/38#issuecomment-421463860

Let me know once PRs and further review will be useful

**Comment by bhousel** [comment]
Thanks @matkoniecz !   You already follow the project, so if you want to submit a PR to update the filters that would be great 👍 

By "not quite ready to have people help yet" I meant more like - I want to wait to remove all the duplicates before I ask for more help from the twitter/mailing list crowd..
