### ISSUE TITLE
Research needed for: shop/bakery|Hinnerbäcker

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1001]
#### :thinking: We need help deciding what to do with "shop/bakery|Hinnerbäcker"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/bakery|Hinnerbäcker` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/bakery|Hinnerbäcker`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/bakery|Hinnerbäcker`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
Looks like a popular name without an uniting brand based on search results and https://forum.openstreetmap.org/viewtopic.php?pid=747375#p747375

**Comment by Adamant36** [comment]
Not these guys? http://hinnerbaecker.com/
![l](https://user-images.githubusercontent.com/30259065/57133857-041c6f00-6d59-11e9-9b97-24899b3e7251.jpg)
