### ISSUE TITLE
Removed tags resurfacing on release

### ISSUE THREAD

**Issue by gy-mate** [osmlab/name-suggestion-index#10010]
_See the issue description here: https://github.com/osmlab/name-suggestion-index/pull/9322#issuecomment-2380864073_

**Comment by kjonosm** [comment]
Should be resolved, see my additional comments in #9322

**Comment by gy-mate** [comment]
@kjonosm Thank you for the quick reply! I didn't know about this. I read the _Contributing_ page on the wiki before opening the PR but I think it didn't have any references to https://github.com/osmlab/name-suggestion-index/wiki/Technical-Details#nsi-and-the-nsi-collector-project. I've added it now: https://github.com/osmlab/name-suggestion-index/wiki/Contributing/_compare/9b72a182a1bb15c1ec0236eab8bac37f23852107...586472a493c17838e00bb88c66415954b585161e
