### ISSUE TITLE
Puuilo seems to be rather Do-It-Yourself Shop, not shop=hardware

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#10036]
from review of what is in OSM right now

https://nsi.guide/index.html?t=brands&k=shop&v=hardware&tt=puuilo

On the other hand, on looking through https://www.puuilo.fi/ I am not so sure what is the difference between `shop=hardware` and `shop=do-it-yourself`

**Comment by Oivo35** [comment]
I agree with change the Puuilo store from shop=hardware to DIY store.
Puuilo stores look exactly like DIY stores in Germany like Bauhaus, Obi or Hornbach.
A DIY store looks like a hypermarket and has separate departments for some type of product, while a shop=hardware may only have one or two smaller shelves for some type of product, f. e. shop=hardware only offers 1 or 2 brands of power tools, while DIY store 5 and more.

**Comment by UKChris-osm** [comment]
I agree, all done.
