### ISSUE TITLE
Fairfax & Favor

### ISSUE THREAD

**Issue by TheUKHighStreet** [osmlab/name-suggestion-index#10039]
Please can you add Fairfax & Favor as a brand?
Wikidata page: https://www.wikidata.org/wiki/Q125924395
Website: https://www.fairfaxandfavor.com/
Country: UK 
OSMTag: clothes
Thanks.

**Comment by Snowysauce** [comment]
As far as I can tell, this chain has only seven locations. The [minimum number needed for inclusion in the NSI](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case#notability) is generally 10-30.
