### ISSUE TITLE
Research needed for: shop/bakery|K&U

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1004]
#### :thinking: We need help deciding what to do with "shop/bakery|K&U"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/bakery|K&U` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/bakery|K&U`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/bakery|K&U`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
K & U Bäckerei - Q1719433

**Comment by ENT8R** [comment]
Information is alaready present:
https://github.com/osmlab/name-suggestion-index/blob/a16386c334f48bfa40774872058cfa7828d3b941/brands/shop/bakery.json#L297-L308

**Comment by Adamant36** [comment]
Thanks.
