### ISSUE TITLE
[CH] Add Enterprise GO

### ISSUE THREAD

**Issue by habi** [osmlab/name-suggestion-index#10066]
https://enterprise-go.ch is an 'office-less' car rental in Switzerland.
See https://community.openstreetmap.org/t/trying-to-bulk-import-locations/119788/ for details on an initial import of +100 stations.

**Comment by habi** [comment]
The website link is not 'finalized' yet.
The one added is a redirect, but redirects to a language-specific URL: https://community.openstreetmap.org/t/trying-to-bulk-import-locations/119788/29

**Comment by Snowysauce** [comment]
The Wikidata page for Enterprise GO [was deleted](https://www.wikidata.org/wiki/Special:Log?page=Q130467239) two days ago.

**Comment by Cj-Malone** [comment]
There is a couple options.

1.
```
brand=Enterprise
brand:wikidata=Q17085454
name=Enterprise GO
```
It is after all Enterprise, same logo, same social media, same brand.

2.
Get the Wikidata entry restored. It has more than 100 locations, it is notable. There is a structural need for this with OSM/NSI, while not Wikimedia projects, we share the same goles. https://github.com/osmlab/name-suggestion-index/pull/8475#issuecomment-1665543134

I think I'd actually prefer 1. But both should be possible.

**Comment by Snowysauce** [comment]
I agree that Enterprise GO belongs in the NSI, so I changed the values of its entry to match option 1 to fix the immediate issue. I have no objections to option 2 being the answer long-term.

**Comment by habi** [comment]
> brand=Enterprise
> brand:wikidata=Q17085454
> name=Enterprise GO

I would very much *not* prefer to `name` the stations.

**Comment by habi** [comment]
> brand=Enterprise
> brand:wikidata=Q17085454
> name=Enterprise GO

I would very much _not_ prefer to `name` the stations, so. would prefer option 2.
I've asked about the deletion on https://www.wikidata.org/wiki/User_talk:Ameisenigel#Deletion_of_Q130467239

**Comment by habi** [comment]
After a minor discussion on the user-page that deleted the item, https://www.wikidata.org/wiki/Q130467239 is undeleted.

**Comment by Snowysauce** [comment]
The original tag values have been restored.
