### ISSUE TITLE
Co-operative companies

### ISSUE THREAD

**Issue by road-runner-osm** [osmlab/name-suggestion-index#10060]
In Germany, Austria, Italy and Switzerland, co-operatives are quite common. They share the same advertising platform, the same brand and the same website, but they are different companies and sometimes even have different shop signs. For example, "Sparkasse" is the common name and brand, but the actual company is called "Steiermärkische Sparkasse" (responsible for Styria) and they also sign their bank shop this way.

How should we deal with these companies? Well, NGI suggests in some cases to just remove the old name, put it in the branch tag and use the cooperative name as the new name. I don't think that's optimal, because it's not a branch, it's a separate company. 
Should we take an single entry for the co-operative and leave the name blank, or one entry for each member of the co-operative (but often the members are quite small and have only a few branches)? I would say first option would be the best solution.

**Comment by Snowysauce** [comment]
> How should we deal with these companies? Well, NGI suggests in some cases to just remove the old name, put it in the branch tag and use the cooperative name as the new name. I don't think that's optimal, because it's not a branch, it's a separate company.

@bhousel would know about this much more than myself, but my guess is that the suggestion is actually prompted on iD's end based on an interpretation of the available NSI data. As you noted, this interpretation is probably incorrect in these cases.

> Should we take an single entry for the co-operative and leave the name blank, or one entry for each member of the co-operative (but often the members are quite small and have only a few branches)? I would say first option would be the best solution.

I agree; having one entry in the NSI that has a `brand` tag while omitting any name tags seems like the way to go. (There's also the option of specifying a "default" name in `name` while using [the preserveTags feature](https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#preserveTags) to allow OSM users to override the default name.)

**Comment by road-runner-osm** [comment]
Okay I have altered the entries of the effected companies and added a preserveTag (#10069). I will leave this issue open and see if it works in practical use or if it's better to also remove the name entry.

**Comment by road-runner-osm** [comment]
Thanks, this question is solved with the solution `"preserveTags": ["^name"]`.
