### ISSUE TITLE
Omar Effendi stores missing

### ISSUE THREAD

**Issue by RayBB** [osmlab/name-suggestion-index#10098]
https://en.wikipedia.org/wiki/Omar_Effendi
https://www.wikidata.org/wiki/Q6818793

**Comment by Snowysauce** [comment]
Could you provide an example of a location mapped in OSM? I was unable to determine which OSM category this store belongs in from either their website or from an overpass-turbo query.

**Comment by RayBB** [comment]
It does seem a bit ambiguous but I think, as wikipedia says department store seems like the type of store.
That being said, it seems like this chain of stores isn't well mapped in OSM.

Here's an example in OSM: https://www.openstreetmap.org/node/6810153710

**Comment by Snowysauce** [comment]
Thanks for the additional info. I've added the brand to `brands/shop/department_store.json` with a basic set of tags. If additional tags are needed/desired, feel free to add a comment.
