### ISSUE TITLE
"Okręgowa Stacja Kontroli Pojazdów"

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#101]
It makes sense to keep it in suggestion, it is a typical name for place where car may be inspected in a regular mandatory control of its state.

But it is not car_repair, it is either tagging for rendering or people confused how it should be tagged.

I am not sure how and where it should be specified and what is the preferred tagging.

amenity=vehicle_inspection appears to be a correct tag based on https://forum.openstreetmap.org/viewtopic.php?id=63584

**Comment by matkoniecz** [comment]
The same for "Stacja Kontroli Pojazdów"

**Comment by bhousel** [comment]
For now I've removed these, they seem kind of generic.  But we can add them back in if they really are branded.
