### ISSUE TITLE
Merge Philippe Védiaud Publicité and Védiaud

### ISSUE THREAD

**Issue by Kalepom** [osmlab/name-suggestion-index#10139]
Both Philippe Védiaud Publicité (philippevediaudpublicite-b12dbd) and Védiaud (vediaud-b12dbd) refers to the same poster_box operator Q130547976. Could you, please, merge both into one "Védiaud" only? As today, iD suggest you to update to Védiaud then again to Philippe Védiaud Publicité. 
Thanks

**Comment by UKChris-osm** [comment]
Thanks @Kalepom 👍
