### ISSUE TITLE
Aldi Suisse should use Q111030009

### ISSUE THREAD

**Issue by brawer** [osmlab/name-suggestion-index#10154]
NSI currently assigns [Q41171672 (Aldi Süd)](https://www.wikidata.org/wiki/Q41171672) to Aldi stores in Switzerland. However, Aldi Switzerland is a separate company with its own Wikidata ID, [Q111030009](https://www.wikidata.org/wiki/Q111030009). Proposal: Change NSI to assign the Wikidata ID  Q111030009 to Aldi stores in Switzerland.

**Comment by UKChris-osm** [comment]
Personally I feel we should stick to the basics within the NSI and focus on just the `brand` and not the underlying operator.

McDs, for example, is operated as a franchise model, with many different operators around the world, and even multiple operators within the same regions, but by focusing on just the `brand`, we can tag it as simply being "_a McDs_", and I think we should do the same with most big brands, unless there is a language specific version, or if the branding looks differently across different areas.

But I've just noticed McDs is split into multiple countries as well for France and Norway, but are using the same tagging, which seems unnecessary.

**Comment by brawer** [comment]
For what it’s worth, Aldi Süd and Aldi Suisse have different logos. So it’s a more user-visible difference than McDonald’s operators.

**Comment by bhousel** [comment]
> But I've just noticed McDs is split into multiple countries as well for France and Norway, but are using the same tagging, which seems unnecessary.

Yeah that does seem redundant - I remember Norway wanted more `"preserveTags": ["^name"]` so it's probably related to that.  And it's ok for different parts of the world to use different spelling or local tags.

But at least they are all still using `"brand:wikidata": "Q38076"` - What we're talking about here would be losing that also, which is the thing I would be sad about.

>For what it’s worth, Aldi Süd and Aldi Suisse have different logos. So it’s a more user-visible difference than McDonald’s operators.

Ah that is good to know - yes if they really have different names or logos, then I could see a case for splitting it into a new brand.   The logo looks the same to me, but with the word "Suisse" below it.  I don't really consider that _different_, but I dunno, maybe Swiss people do 😆

**Comment by brawer** [comment]
So what’s the verdict on Aldi Suisse?

Generally, I’d assume it makes sense for NSI to use different IDs if and when there’s difference in branding (different names or logos). For Wikidata, however, I think it makes sense to use a more granular model: different legal entitites typically have different properties such as headquarter location, company ID, establishment dates, CEOs, etc. Therefore, it seems inevitable to accept some mismatch in modeling granularity between Wikidata and OSM/NSI.

Personally I don’t have strong opinions on this, I’m just trying to resolve a thread in the Swiss OSM forum. People noticed that the Swiss Aldi stores currently don’t have the Wikidata tag of Aldi Suisse in OSM, but that of the German brand. The tag comes from NSI presets, hence this bug report. If NSI wants to keep Aldi Switzerland as-is, that’s of course fine too. But thanks for making a decision :-)

**Comment by Snowysauce** [comment]
If I'm understanding this request correctly, the sole difference between the proposed Swiss Aldi entry and the global Aldi Sud entry would be the Wikidata ID suggested by NSI. I feel that making this change would be a slippery slope of maintenance that would eventually lead to eight separate, nearly identical entries for every country Aldi Sud operates in. We already have difficulty making sure that changes to an entry in one category file are carried over to that entry's listing in other categories (#10137, #10145), and splitting international brands by country without a specific need to do so would invite the very real possibility of unintentional unsynchronized tagging within a brand, defeating the entire purpose of the NSI.
