### ISSUE TITLE
add Interrapidisimo

### ISSUE THREAD

**Issue by RayBB** [osmlab/name-suggestion-index#10157]
https://www.crunchbase.com/organization/inter-rapidisimo
No wikidata yet but tons of locations all over Bogotá, Colombia. Sometimes with a space and sometimes without. So we should probably add without a space as a synonym or something in case people see the sign with one word.

I won't be at my computer for a while so if someone else makes the Wikidata first that would be appreciated.

PS: I recently wrote a little blog post about the NSI. Hopefully making it easier for people to find this project 
https://blog.rayberger.org/how-to-add-a-brand-preset-to-openstreetmap

**Comment by bhousel** [comment]
> Sometimes with a space and sometimes without. So we should probably add without a space as a synonym or something in case people see the sign with one word.

In fact NSI ignores whitespace when it does the matching, so it will catch either variant. 👍

**Comment by RayBB** [comment]
Thanks for letting me know.

Btw I made the wikidata entity
https://www.wikidata.org/wiki/Q131291014
