### ISSUE TITLE
New Domain Name: nsi.openstreetmap.org

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#10210]
I think we've had the domain name [nsi.guide](https://nsi.guide) since the inception of the the Name Suggestion Index, but I'm guessing this is being paid for by @bhousel out of his own pocket (although I could be wrong about that) which seems like quite a burden / cost for Brian, as well as requiring him to maintain the domain and where it points to, which I think is a little unfair considering he shouldn't have to pay privately for something many of us use.

I've enquired with the operations team within the OSM Foundation, and asked if they'd be willing to set up a sub-domain for the NSI, possibly under `nsi.openstreetmap.org` or `nsi.osm.org`, and @Firefishy (Grant) replied very quickly to say it would be possible, but that he'd also happily take over the nsi.guide domain if Brian wished to Transfer it.

I don't have any private correspondence with @bhousel so this post will also be the first he's heard of the idea, but just wanted to get other people's views on the NSI project having an OSM sub-domain going forward?

How do you feel about it Brian, if you see this that is?

**Comment by bhousel** [comment]
>I've enquired with the operations team within the OSM Foundation, and asked if they'd be willing to set up a sub-domain for the NSI, possibly under nsi.openstreetmap.org or nsi.osm.org, and @Firefishy (Grant) replied very quickly to say it would be possible, but that he'd also happily take over the nsi.guide domain if Brian wished to Transfer it
> How do you feel about it Brian, if you see this that is?

Absolutely not.  And that's all we need to say about it.

**Comment by UKChris-osm** [comment]
Sorry if I've offended you Bryan

**Comment by Firefishy** [comment]
I don't know the context, but I'm still happy to point nsi.openstreetmap.org and nsi.osm.org to GitHub pages if desired by @bhousel .

**Comment by bhousel** [comment]
> Sorry if I've offended you Bryan

I'm not offended - but I have a list of grievances against the OSMF like a mile long, and if we want to get into that, that's what private messages are for.  They will not be taking over anything of mine ever again.
