### ISSUE TITLE
Should brands/office/estate_agent preserve name tags?

### ISSUE THREAD

**Issue by Snowysauce** [osmlab/name-suggestion-index#10239]
#10238 made me realize that `brands/office/estate_agent` doesn't have `"preserveTags": ["^name"]` set for the entire category, even though the individual agencies tend to have unique names like those of insurance agencies (`brands/office/insurance`, which does have `"preserveTags": ["^name"]` atop the category). Is this discrepancy intentional or an oversight?

**Comment by bhousel** [comment]
Yes, I agree this category probably should leave the name tags alone 👍 
I just added the rule in 7d1cbc9a4
