### ISSUE TITLE
Kmart is no longer notable

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#10271]

**Comment by UKChris-osm** [comment]
Can you expand on this?

Have they reduced their store count, closed them down, gone bust?

**Comment by grrla** [comment]
Only 5 stores left
________________________________

**Comment by Snowysauce** [comment]
This doesn't seem like a pressing issue since the NSI has entries for brands/operators with similar OSM instance counts. (We probably _shouldn't_ have them, but unless someone goes through the 40,000+ entries one by one to find them, they're there and that's just the reality of things.)

**Comment by Snowysauce** [comment]
Closing per the acceptance of #10030, which has less locations than Kmart.
