### ISSUE TITLE
comparable matchNames for aldi nord and süd

### ISSUE THREAD

**Issue by tiptoptom** [osmlab/name-suggestion-index#10287]
I think Aldi Nord and Aldi Süd should have comparable matchnames. At the moment [Aldi Süd](https://github.com/tiptoptom/name-suggestion-index/blob/93d39eb93eaa123a21d16d81bd100d25e90fdeef/data/brands/shop/supermarket.json#L329) has “aldi” as a matchname and [Aldi Nord](https://github.com/tiptoptom/name-suggestion-index/blob/93d39eb93eaa123a21d16d81bd100d25e90fdeef/data/brands/shop/supermarket.json#L314) has no matchnames. 

I see three possibilities:
1. both have no matchnames
2. both have “aldi” as matchnames
3. both have “aldi nord” or “aldi süd” as matchnames

see #10284

**Comment by Snowysauce** [comment]
Aldi Nord has "Aldi" as a matchName via https://github.com/osmlab/name-suggestion-index/pull/10284/files#diff-478a5b2128693e6e200c127873c89cd5231498ceca1ba5df34691011fb656d4eR325.
