### ISSUE TITLE
Research needed for: shop/books|Cultura

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1069]
#### :thinking: We need help deciding what to do with "shop/books|Cultura"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/books|Cultura` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/books|Cultura`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/books|Cultura`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bmillemathias** [comment]
From my experience Cultura is not only books, but also have consoles and games, music goods like CD but also instruments. They also have in my local shop a part dedicated to manual art, like paint or crafting paper, carton... They selling press and concert tickets.

Cultura are I know is french only based shops, seems to be confirmed by https://www.cultura.com/les-magasins.html/

**Comment by Adamant36** [comment]
@matkoniecz, you mind if this is closed since you added it?
