### ISSUE TITLE
Research needed for: shop/books|Дом книги

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1075]
#### :thinking: We need help deciding what to do with "shop/books|Дом книги"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/books|Дом книги` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/books|Дом книги`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/books|Дом книги`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
This will most likely be generic, a name dating back to soviet times and so will be shared by shops in pots-soviet countries

**Comment by bhousel** [comment]
This one is linked to https://www.wikidata.org/wiki/Q48950742
It seems ok, but let me know if it needs a change.

**Comment by tohaklim** [comment]
> This one is linked to https://www.wikidata.org/wiki/Q48950742

oh wow, I missed that wikidata entry. It actually is about one specific shop (in Moscow, judging by the name), but then the website and twitter handle are for an eponymous shop in St Petersburg. They are not related from what I can see
