### ISSUE TITLE
Research needed for: shop/car_parts|Армтек

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1099]
#### :thinking: We need help deciding what to do with "shop/car_parts|Армтек"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/car_parts|Армтек` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/car_parts|Армтек`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/car_parts|Армтек`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
tried adding a wikidata entry but it got wiped - it's a network of car parts stores, that was recently imported

**Comment by matkoniecz** [comment]
I recently added explanation how one may reference Wikidata entries to protect them from deletion - see https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#adding-references-to-wikidata (if anything is unclear there - let me know, it was just added)
