### ISSUE TITLE
Localization of name suggestion

### ISSUE THREAD

**Issue by hlaw** [osmlab/name-suggestion-index#11]
Currently the name suggestion index compiles global frequency counts of POIs for use in iD for suggestions / presets.   

In reality the different brand names / chain stores etc are not evenly distributed and differ across countries.  Many stores (and not least the usage of their localised names) are very confined.  

To enhance the relevancy of the suggestions, it might be useful to partition the counts into countries and provide suggestions based on the occurence of the pois in the country being edited. 

As a first step on the backend, I have attempted a new branch for the project at my repo - 
    https://github.com/hlaw/name-suggestion-index/tree/countrycode
## Format changes

The branch revise the project to add a new country code level at the top hierarchy of name-suggestions.json.  The JSON format under each country is the same as the current global file.   The threshold for generating topNames.json is lowered form 50 to 5 such that names from smaller / less well mapped countries would show up. 
## Changes made

In my setup the original `getRaw.js` could not finish processing the Asia extract and got killed after eating up several Gs of memory, and I could not got it to work under node.  I have therefore rewritten it in C++ and call libosmium directly (the same backend as osmium-node).   Besides counts, coordinates for each POI are saved for further processing.

In `build.js`, the process now checks the country code from the coordinates using https://github.com/hlaw/codegrid-js.  It then counts the POIs by country.
## Sample data

The branch contains demo data based on a recent pbf extract of asia (with 315M nodes / 10M ways).  I have not download the planet to test but I would guess that the files would be 8-10 times the current size when run on planet.

To use data from the branch, iD would need to be able to load presets / suggestions dynamically when a user moves to a different country.  This would probably require a set of country specific preset files to be built before deployment.  For most users this should result in smaller download size and more relevant results in suggestions.   I will try to explore how this could be done in iD.

Meanwhile as the change would break iD now this is just posted for review. Thank you.

**Comment by matkoniecz** [comment]
For example `shop/variety_store|Bazar` should not be proposed in Poland or for Polish editors as in Polish "bazar" means "bazaar" or "marketplace" and this brand is not present in Poland.

**Comment by bhousel** [comment]
I've added a `countryCodes` array property for entries that should only be shown when editing in certain countries.


```js
  "amenity/cafe|スターバックス": {
    "count": 608,
    "countryCodes": ["jp"],
    "tags": {
      "amenity": "cafe",
      "brand": "スターバックス",
      "brand:en": "Starbucks",
      "brand:wikidata": "Q37158",
      "brand:wikipedia": "ja:スターバックス",
      "cuisine": "coffee_shop",
      "name": "スターバックス",
      "name:en": "Starbucks"
    }
  },
  "amenity/cafe|星巴克": {
    "count": 258,
    "countryCodes": ["cn", "tw"],
    "tags": {
      "amenity": "cafe",
      "brand": "星巴克",
      "brand:en": "Starbucks",
      "brand:wikidata": "Q37158",
      "brand:wikipedia": "zh:星巴克",
      "cuisine": "coffee_shop",
      "name": "星巴克",
      "name:en" "Starbucks"
    }
  },
```
