### ISSUE TITLE
Research needed for: shop/clothes|Plato's Closet

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1200]
#### :thinking: We need help deciding what to do with "shop/clothes|Plato's Closet"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/clothes|Plato's Closet` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/clothes|Plato's Closet`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/clothes|Plato's Closet`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by skorasaurus** [comment]
I took a quick look at this and it only sells used clothing (I think I was in one of these years ago); It doesn't have its own wikipedia article; but has a section https://en.wikipedia.org/wiki/Winmark#Plato's_Closet 

In that case, do you still want the wikipedia linked? 

tag to add:
second_hand=only

**Comment by bhousel** [comment]
Thanks for the research @skorasaurus - I added the needs wikidata tag.  Someone can add it for us!
I agree with the `second_hand=only` tag too, we can include that in the entry.

**Comment by Adamant36** [comment]
Reopening as Winmark was only the operator and this could still use its own Wikidata entry.

**Comment by bhousel** [comment]
this was done
