### ISSUE TITLE
Research needed for: shop/convenience|Bonjour

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1250]
#### :thinking: We need help deciding what to do with "shop/convenience|Bonjour"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Bonjour` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Bonjour`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Bonjour`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by hfs** [comment]
"Bonjour" is the brand of convenience stores integrated with "Total" fuel stations especially in France and probably also in Europe. I couldn’t find separate Wikipedia/-data entries for "Bonjour". I’m not sure if putting the "Total" IDs on them would be correct or if the brand as such would deserve an own Wikidata ID.

Also, "bonjour" being the general salutation in French, if it’s used as name for a convenience store in other Francophone countries, it has probably nothing to do with Total.

**Comment by Adamant36** [comment]
Thanks for the information. I'll add the needs wikidata label to it.
