### ISSUE TITLE
Research needed for: shop/convenience|Cheers

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1253]
#### :thinking: We need help deciding what to do with "shop/convenience|Cheers"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Cheers` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Cheers`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Cheers`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by jeisenbe** [comment]
This is a convenience store brand in Singapore; I've bought a SIM card and snacks there:
http://www.cheers.com.sg/web/

Apparently they are expanding to Vietnam as well: 
https://insideretail.asia/2018/05/28/singapores-cheers-convenience-store-chain-expands-in-vietnam/

Hopefully someone else is interested in making a PR?

**Comment by SilentSpike** [comment]
I'll add it, thanks for the information!

**Comment by SilentSpike** [comment]
Done in 9d534a1df87f87811b7e725a5a5f9a34e021c976

Unfortunately can't see any obvious social media presence, but please flesh out the wikidata item as desired
