### ISSUE TITLE
Research needed for: shop/convenience|Martin's

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1273]
#### :thinking: We need help deciding what to do with "shop/convenience|Martin's"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Martin's` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Martin's`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Martin's`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Johnnybar** [comment]
Hi, I'd like to take this one but based on this page, the brand is a trading name for the Mccoll's brand and actually is not a convenience store, but belongs to the 'newsagents' category:
https://en.wikipedia.org/wiki/McColl%27s
Are such entries (trading names and such) still considered to be brands and can I as a contributor move entries to more accurate categories?

**Comment by matkoniecz** [comment]
> can I as a contributor move entries to more accurate categories?

Yes, see https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#card_file_box--about-the-brand-files for description of `match` property.

Note that wit such overriding of what is mapped it is useful to double check it, but sometimes there are some shops that are widely mistagged.
