### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/name-suggestion-index#13]
Just tried to run an update. Totally died, likely because of newer ubuntu and me missing something.

I should just rebuild this. This was my first node project, I know better now. Might be something for a slow night.

**Comment by math1985** [comment]
> Just tried to run an update. Totally died, likely because of newer ubuntu and me missing something.

Currently I'm getting this:

  $ node ./getRaw.js netherlands-latest.osm.pbf 
  Killed

Is that the same problem you were facing? I have the impression this might be a memory issue. On a smaller extract (Luxembourg), it works fine.

**Comment by math1985** [comment]
Confirmed that it still works (on the Netherlands extract) on Ubuntu 16.04 inside a Virtual Box with 20GB swap memory. Not sure which of these is the deciding factor though.

**Comment by math1985** [comment]
I just ran getNames on Ubuntu 16.04, and pushed the new topNames.json to the repository.

A rebuild might still be necessary, but the statement "Doesn't work anymore" seems to be false, so I'll close this issue.

**Comment by aaronlidman** [comment]
Thank you @math1985
