### ISSUE TITLE
Research needed for: shop/convenience|Stores

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1300]
#### :thinking: We need help deciding what to do with "shop/convenience|Stores"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Stores` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Stores`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Stores`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by SilentSpike** [comment]
Believe this might be a generic name. Overpass turbo results aren't clumped in any particular region and there aren't enough to make me believe it's a global chain of some sort (the lack of search results also suggests this).

**Comment by SilentSpike** [comment]
I overlooked quite a lot of nodes all clumped in Benin City, Nigeria.

However, I imagine this must be some kind of mistake as so many convenience stores with the same name all so close together (they're almost all on one street) seems like a stretch.

**Comment by bhousel** [comment]
Yeah - this one seems generic..
