### ISSUE TITLE
amenity/pharmacy|Ljekarna looks like a descriptive name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#131]

**Comment by matthijsmelissen** [comment]
Thanks for all your suggestions @matkoniecz ! If you like, you can also bundle multiple points (for example all descriptive names) in a single issue.

**Comment by matkoniecz** [comment]
I thought that it would be preferable to keep each topic separate - especially as in some cases like this one it is possible that my guess is wrong.

**Comment by matthijsmelissen** [comment]
@bhousel What is your preference?

**Comment by bhousel** [comment]
I don't plan to have extensive discussions on any of these, so separate issues are kind of unnecessary... 

My preference would be for people to open PRs to just filter out the names.
