### ISSUE TITLE
Research needed for: shop/convenience|Ветеран

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1319]
#### :thinking: We need help deciding what to do with "shop/convenience|Ветеран"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Ветеран` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Ветеран`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Ветеран`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
generic

**Comment by matkoniecz** [comment]
It translates as "Veteran", right? It seems to me that it is rather case of multiple shops using this name, without an uniting brand but without making it descriptive.

So this name should be not included in list of brands, but also it should not be proposed to be removed where it is present.

**Comment by tohaklim** [comment]
Ah, right, I think I might've misunderstood "generic" in the context of this index

**Comment by matkoniecz** [comment]
"generic" is a bit tricky, it may refer to both descriptive names (`amenity=restaurant name=Restaurant`) and popular names without uniting brand. I was unsure and that is why I asked but fortunately @bhousel intrpreted your comments correctly.

BTW, thanks for helping with processing so many entries!

If you would be interested - there are still some candidates waiting for a review, see https://github.com/osmlab/name-suggestion-index/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-asc
