### ISSUE TITLE
Research needed for: shop/convenience|Продукты 24 (objects in Russia)

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1357]
#### :thinking: We need help deciding what to do with "shop/convenience|Продукты 24"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/convenience|Продукты 24` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/convenience|Продукты 24`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/convenience|Продукты 24`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
Why do you think that this is a generic name?
Google returns this website: https://produkty24.com.ua/ ([Google Translate](https://translate.google.de/translate?sl=auto&tl=en&u=https%3A%2F%2Fprodukty24.com.ua%2F))

**Comment by Adamant36** [comment]
It could be that store. I assumed it was saying something like "24 hour product store" or some such. Nothing came up when I researched it either. That happens once in a while. A lot of the Russian related stuff is pretty obscure. We should get confirmation from a person that knows Russian.

**Comment by matkoniecz** [comment]
ping local expert: @DmitriiKh

**Comment by DmitriiKh** [comment]
It's a generic name for a convenience store. I saw so many of them :)
That website (https://produkty24.com.ua/) is for an online store.
