### ISSUE TITLE
Research needed for: shop/cosmetics|Rituals

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1397]
#### :thinking: We need help deciding what to do with "shop/cosmetics|Rituals"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/cosmetics|Rituals` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/cosmetics|Rituals`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/cosmetics|Rituals`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
Q62874140

**Comment by snowyleopard98** [comment]
Hello. I'd like this to be my first contribution to an open source, ever. I know JavaScript, but not used to working with node.js & json. Is this still a good first contribution for me?

I looked up Rituals, and yes they are a cosmetics company. But they do Not have a Wikipedia page/Wikidata. How can I best approach this, if this is still a good first contribution for me. Thanks!

**Comment by Adamant36** [comment]
Hi there. Feel free to give it a try. I created a Wikidata entry for it a while ago. Its Q62874140. Its fairly straight forward to add it to the index. There's a guide on how to do here https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md

Feel free to ask any questions if you have an issue with anything also.
