### ISSUE TITLE
Research needed for: shop/doityourself|Point P

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1413]
#### :thinking: We need help deciding what to do with "shop/doityourself|Point P"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/doityourself|Point P` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/doityourself|Point P`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/doityourself|Point P`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by SilentSpike** [comment]
Looks like a french DIY store which as far as I can tell doesn't have it's own wikipedia page, believe [this is the operator's page](https://fr.wikipedia.org/wiki/Saint-Gobain_Distribution_B%C3%A2timent_France). However, it links to a wikidata with label "Point P" so little unclear whether that is applicable 🤔 

Also looks like it's more correct to named `Point.P`
