### ISSUE TITLE
Research needed for: shop/doityourself|Строитель

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1420]
#### :thinking: We need help deciding what to do with "shop/doityourself|Строитель"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/doityourself|Строитель` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/doityourself|Строитель`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/doityourself|Строитель`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
Probably http://stroitel-spb.com/ru/ which doesn't have a Wikidata entry from I can find, but I'm 100% sure. So I'm adding the needs research label to it just in case.

**Comment by tohaklim** [comment]
It's a generic name (lit "Builder") for diy shops. [This page](https://www.facebook.com/stroitelorgua/) mentions a whopping 4 stores, and one can find shops named the same in other regions, yet not being the same brand.
Might be difficult to unify
