### ISSUE TITLE
"DHL Packstation" vs "InPost"

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#143]
Either DHL pack station should be named "DHL" and InPost pack station should be named "InPost" or  DHL pack station should be named "DHL Packstation" and InPost pack station should be named "Paczkomat InPost"

**Comment by matkoniecz** [comment]
As bonus there is also `amenity/vending_machine|Packstation`.

**Comment by bhousel** [comment]
> DHL pack station should be named "DHL Packstation" and InPost pack station should be named "Paczkomat InPost"

☝️  I did this and added InPost wikidata and wikipedia tags.

> As bonus there is also `amenity/vending_machine|Packstation`.

I set this string to match the DHL Packstation.
