### ISSUE TITLE
leisure/sports_centre|Curves, leisure/fitness_centre|Curves - is it the same thing? Is one version correct or both, like with Lewiatan?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#144]

**Comment by bhousel** [comment]
should be a fitness centre

**Comment by bhousel** [comment]
Actually I'd even go so far as to say all the "sports centres" in this list are probably wrong.. I think I might just exclude them.

**Comment by matkoniecz** [comment]
> Actually I'd even go so far as to say all the "sports centres" in this list are probably wrong..

Real sports centres have rather unique names, so as result only mistaggings ended on list of popular names.
