### ISSUE TITLE
Research needed for: shop/hairdresser|Franck Provost

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1492]
#### :thinking: We need help deciding what to do with "shop/hairdresser|Franck Provost"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/hairdresser|Franck Provost` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/hairdresser|Franck Provost`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/hairdresser|Franck Provost`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by guilhermemalfatti** [comment]
Hi, what is the process to submit a pull request? creating a new branch e push it? or there is another way to do so?

**Comment by bhousel** [comment]
I think this GitHub guide is a pretty good overview of the process:
https://guides.github.com/activities/forking/

You fork the repo, make changes on your local copy, and send a "pull request" back to this repo for me to review.

**Comment by bhousel** [comment]
> Hi, what is the process to submit a pull request? creating a new branch e push it? or there is another way to do so?

I'm really sorry to have to reject your pull request - you did everything right!

**Comment by bmillemathias** [comment]
Can be closed now.
