### ISSUE TITLE
Research needed for: shop/hairdresser|Стиль

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1509]
#### :thinking: We need help deciding what to do with "shop/hairdresser|Стиль"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/hairdresser|Стиль` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/hairdresser|Стиль`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/hairdresser|Стиль`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
Translates directly as "Style", this is a very generic (and not very creative) name for a beauty salon/hairdressers. Could get multiple in one city, so not really a brand in my understanding- maybe it is somewhere?

**Comment by Adamant36** [comment]
Probably not. There's a bunch of issues for Russian names that are probably generic like this one.

**Comment by bhousel** [comment]
Yeah I try not to assume though, so it's nice to get confirmation from local mappers.

(After all we do have a coffee house branded ["Coffee House"](http://osmlab.github.io/name-suggestion-index/brands/amenity/cafe.html#amenitycafecoffee-house) in the index 😬)
