### ISSUE TITLE
Research needed for: shop/hairdresser|Шарм

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1510]
#### :thinking: We need help deciding what to do with "shop/hairdresser|Шарм"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/hairdresser|Шарм` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/hairdresser|Шарм`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/hairdresser|Шарм`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by alvinalmodal** [comment]
Hello I am unable to find the file config/canonical.json. I have run npm run build but i am not seeing the file.

**Comment by Adamant36** [comment]
Hi there. The canonical.json file has been split into different files since the original post created. All the .json files needed for adding or updating things are now in the Brands/whatever_tag_type folders.

**Comment by alvinalmodal** [comment]
@Adamant36 hello I have tried editing the Brands/hairdresser.json (removed Шарм) but when I run the npm run build as per instruction the json values are just reverting back. Am i doing it wrong?

**Comment by Adamant36** [comment]
Hhmmm, I don't know what that's about. @bhousel have to help you with that one.

**Comment by matkoniecz** [comment]
@alvinalmodal Ypu want to remove Шарм as it is incorrect, right?

In that case https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#hocho--remove-generic-names should help

**Comment by tevez07b9** [comment]
@matkoniecz I tried the above way you mentioned to remove  Шарм, since it's not a brand, a i got this issue in npm run build. here is the SC
![Screenshot from 2019-05-31 01-45-14](https://user-images.githubusercontent.com/35212025/58661561-cace2380-8345-11e9-9268-c2f8d0a11a53.png)

**Comment by bhousel** [comment]
@tevez07b9 you need to do `npm install` first, then it should work.
