### ISSUE TITLE
Research needed for: shop/hardware|1000 мелочей

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1511]
#### :thinking: We need help deciding what to do with "shop/hardware|1000 мелочей"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/hardware|1000 мелочей` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/hardware|1000 мелочей`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/hardware|1000 мелочей`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
Looks like brand, not generic name - http://www.1000kem.ru/

**Comment by ENT8R** [comment]
I'm not 100% whether this is really a brand. The first link you posted leads to a page that lists shops mainly located in the city of Kemerowo ([Google Translate](https://translate.google.de/translate?sl=auto&tl=en&u=http%3A%2F%2F1000kem.ru%2F)) And none of them seems to be mapped in OSM...
The second link leads to a page of a Russian television show with the same name as this store...
During my reasearch I also found some other websites also having the same name, so this might also be a generic name.

**Comment by matkoniecz** [comment]
Second link is clearly a fail, but https://translate.google.de/translate?sl=auto&tl=en&u=http%3A%2F%2F1000kem.ru%2F looks to me like listing of their shops.

Probably asking local community on their mailing list would be the best idea.

In meantime I will ping @tohaklim

**Comment by tohaklim** [comment]
It's a tough one, since some regional retailers are using it as a brand, but it's generally not one. It can vary between 100/1000 "small things" in the name, probably the closest thing is a variety store

**Comment by DmitriiKh** [comment]
'1000 мелочей' is a popular name for stores in Russia. I think the closest thing is 'a dollar store'.

**Comment by matkoniecz** [comment]
In that case the best solution is to discard it from possible brand names, but at the same time it is a valid name for a shop, right?

**Comment by DmitriiKh** [comment]
Yes, it is a valid name for a shop.
