### ISSUE TITLE
Research needed for: shop/jewelry|Histoire d'Or

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1528]
#### :thinking: We need help deciding what to do with "shop/jewelry|Histoire d'Or"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/jewelry|Histoire d'Or` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/jewelry|Histoire d'Or`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/jewelry|Histoire d'Or`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Johnnybar** [comment]
Hi,
I'd like to take this one as my first open-source contribution, but after cloning the repo and running the build, I still can't find any file under 'config' called 'canonical.json'. I do find the entry for this shop under 'brands/shop'. Is that the expected folder or did I get something wrong?
Thanks,
Jonathan

**Comment by bhousel** [comment]
> I'd like to take this one as my first open-source contribution, but after cloning the repo and running the build, I still can't find any file under 'config' called 'canonical.json'. I do find the entry for this shop under 'brands/shop'. Is that the expected folder or did I get something wrong?

You did it right - `brands/shop.json` is the new file to edit...

`config/canonical.json` is old from when we had them all in one file.  Unfortunately old issues like this one still show the old instructions.

**Comment by Johnnybar** [comment]
Perfect, thanks. Another quick question - there are 106 other errors regarding other entries (missing tags, duplicates, etc.). I'd like to fix this one, move to the next one and so on, but can a pull request only be submitted after all these other errors have been resolved? :)

**Comment by Adamant36** [comment]
Hi there. The warnings regarding other entries can be completely ignored if you feel like. You don't have to fix them to submit a PR.

**Comment by matkoniecz** [comment]
No, it is not feasible to fix all issues at once.

**Comment by Johnnybar** [comment]
Thanks for your answers. After adding a country code and not finding any wikidata or wikipedia tags, I ran git pull, opened a new branch for my changes ('entry-Histoire-dOr'),  git add and git commit to commit my changes. However, I'm getting this error when trying to push with 'git push origin entry-Histoire-dOr' :
remote: Permission to osmlab/name-suggestion-index.git denied to Johnnybar.
fatal: unable to access 'https://github.com/osmlab/name-suggestion-index.git/': The requested URL returned error:
403

Any idea what could be causing this?
Thanks

**Comment by Adamant36** [comment]
It sounds like the error is because you have the main repo set as origin instead of your branch. Which you don't have direct access rights to. Instead, you need to add a remote by using "git add origin" to make your branch where you push to and then do a PR from there. 

https://help.github.com/en/articles/adding-a-remote

**Comment by Johnnybar** [comment]
To make it simpler, I forked and cloned the repo, made changes and pushed to it, then created a PR.
This is the PR URL - https://github.com/osmlab/name-suggestion-index/pull/2522
