### ISSUE TITLE
handling of sub brands

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#155]
I am still not 100% sure how subbrands should be handled.

For example "BPI Family Savings Bank" bank appears to be sub-brand of "BPI" bank. Should these two entries be merged into one, left alone or judged by a local mapper?

There are also cases where subsidiary has a completely different name. In one of extreme cases Nestle own thousands of brands.

* Valvoline Instant Oil Change / Valvoline
* Bliska fuel station with brand owned by Orlen ( https://dlakierowcow.orlen.pl/en/home-page ) (I feel that `brand:wikidata` would be incorrect here)
* Max Spielmann owned by https://en.wikipedia.org/wiki/Timpson_(retailer)

**Comment by matkoniecz** [comment]
Nex case - Bliska fuel station with brand owned by Orlen ( https://dlakierowcow.orlen.pl/en/home-page )

**Comment by bmillemathias** [comment]
this relates also to #1676 as Leclerc has a lot of sub-brands

**Comment by Adamant36** [comment]
For me it depends on how many stores there are and if they are unique store formats or have some other self defining features (like McCafe having its own entry seperate from McDonalds). I haven't looked into the banks, but the case of Leclerc the sub brands are unique enough and there's enough stores in the brands to warrant their own entries. In other instances, it should probably be on a case by case basis. There's no reason we can't decide for each one on its own if need be.

As a side, I think it would helpful if we created unique entries for subrands when it comes to Wikidata also. As it allows for a more complete brand database on their end. Which is good for everyone in my opinion.

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/Timpson_(retailer) owning Max Spielmann brand

**Comment by bhousel** [comment]
moved to #2787
