### ISSUE TITLE
Research needed for: shop/newsagent|Витебскоблсоюзпечать

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1565]
#### :thinking: We need help deciding what to do with "shop/newsagent|Витебскоблсоюзпечать"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/newsagent|Витебскоблсоюзпечать` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/newsagent|Витебскоблсоюзпечать`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/newsagent|Витебскоблсоюзпечать`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
Not entirely sure where this falls, so just commenting for now.
This is essentially a regional subsidiary of a countrywide newsagents/print state-run enterprise (Belsoyuzpechat, http://bspechat.by/), where the Vitebsk prefix denotes it being in the Vitebsk region.
Based on this https://gorodvitebsk.by/news/04-09-2017/dadizain, they are branded, so a separate brand entry might be justified. The issue with the current match though is that it's in Russian, while actual signage appears to be in Belarusian based on the above website
