### ISSUE TITLE
Research needed for: shop/newsagent|Первая полоса (Russia, around Moscow and Saint Petersburg)

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1566]
#### :thinking: We need help deciding what to do with "shop/newsagent|Первая полоса"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/newsagent|Первая полоса` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/newsagent|Первая полоса`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/newsagent|Первая полоса`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by DmitriiKh** [comment]
Hi,
I did some research and what I've found is:
- there is a news website called 'Первая полоса' (http://1polosa.net)
- there are no articles about this website in Wikipedia or Wikidata
- it looks like most of the topics published on this website are related to Ukraine

I'm not sure if the name 'Первая полоса' is a registered brand name or not. Probably there are some regulations (in Ukraine?) for registering brand names but I don't know how to find them.

**Comment by matkoniecz** [comment]
Curiously this name appears only in Russia - see http://overpass-turbo.eu/s/HEC

Almost entirely around Moscow and Saint Petersburg.

**Comment by Adamant36** [comment]
I can't post pictures right now, but going by Google Image search it looks like there are a bunch of them that share the same signs. So my guess is that its a brand.

**Comment by DmitriiKh** [comment]
Yes, you are right there are stores that share the same logo in Saint Petersburg. 
![image](https://user-images.githubusercontent.com/31587652/55514806-6ccfd900-563f-11e9-84e4-23a8a271ff89.png)
Therefore it can be a brand.
https://spb-gid.com/organizacii-spb/magazin-pervaya-polosa.html

**Comment by Adamant36** [comment]
Yeah that's it.

**Comment by DmitriiKh** [comment]
I have a question because I'm not sure how it works. You need wikidata because it's a copyright issue?

**Comment by Adamant36** [comment]
its nothing to do with the copyright. A Wikidata entry just allows it to be used as a preset in iD Editor and the name index farms the Wikidata page for certain information like brand icon links.

**Comment by DmitriiKh** [comment]
I see. What if a local brand has no info about it in any Wiki but we know it's a brand because we can see a lot of it's photos? Like [this](https://yandex.com/images/search?text=%D0%BF%D0%B5%D1%80%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%BE%D0%BB%D0%BE%D1%81%D0%B0%20%D0%BA%D0%B8%D0%BE%D1%81%D0%BA)

**Comment by Adamant36** [comment]
In that case we add the "needs wikidata" label to it and wait for someone to create one. Its not that complicated, but does a take a little effort. https://m.wikidata.org/wiki/Wikidata:Contribute

If you want to do it feel free. Then you can paste the wikidata Q number here and wait for someone to do a PR for it. You can also do that if you know how though. There's a guide in the contributing file. https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md

If you have any questions, feel free to ask.

**Comment by DmitriiKh** [comment]
I've created an item (Q62736412) with a label and a description in Russian but I stuck with the logo. As I understand I must to add it to Wiki Commons? Would it be useful at all in this project?

**Comment by matkoniecz** [comment]
Uploading logos to Commons is a bit tricky because only out of copyright files (or ones where copyright owner released them under a permissive license) may go there.

See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata

> Add social media accounts under the "Identifiers" section. If a brand has a Facebook, Instagram, or Twitter account, we can fetch its logo automatically.

(in linked section there is also animated gif showing how it can be done).

**Comment by matkoniecz** [comment]
Are you interested in making PR adding link to Q62736412? On one hand I may do it of you prefer to not have one more thing to figure out, on the other I prefer to not do it if you want to add your research results with your own pull request.

**Comment by DmitriiKh** [comment]
I added their vk.com (it's kind of Russian Facebook) account to Wikidata. It's the only thing I could find. I hope it will work. 
If you can do PR I'd appreciate it :)

**Comment by matkoniecz** [comment]
PR done, thanks for your research! If you would be interested there is plenty of names withing Russia waiting for similar check

For example:

```
shop=clothes name=Московская ярмарка without brand:wikidata 
shop=clothes name=Смешные цены without brand:wikidata 
shop=clothes name=Трикотаж without brand:wikidata 
shop=florist name=Мосцветторг without brand:wikidata 
shop=convenience name=24 часа without brand:wikidata 
shop=convenience name=АВ Daily without brand:wikidata 
shop=convenience name=Августина without brand:wikidata 
shop=convenience name=Агрокомплекс without brand:wikidata 
shop=convenience name=Белорусские продукты without brand:wikidata 
shop=convenience name=Добрый without brand:wikidata
```

(some of entries listed here may have their own issues opened, some may not - all require similar research)

**Comment by ArloJamesBarnes** [comment]
So the 'needs Wikidata' label is outdated?

**Comment by matkoniecz** [comment]
> So the 'needs Wikidata' label is outdated?

This is a closed issue, that was opened because it needed Wikidata. 

https://github.com/osmlab/name-suggestion-index/labels/needs%20wikidata - 8 open issues that still need wikidata

https://github.com/osmlab/name-suggestion-index/issues?q=label%3A%22needs+wikidata%22+is%3Aclosed - 254 closed issues that needed wikidata but are inactive (fixed, rejected, replaced by another issue or for other reason activity is no longer needed)
