### ISSUE TITLE
Research needed for: shop/pawnbroker|Ломбард

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1592]
#### :thinking: We need help deciding what to do with "shop/pawnbroker|Ломбард"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/pawnbroker|Ломбард` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/pawnbroker|Ломбард`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/pawnbroker|Ломбард`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by RoyJia** [comment]
pick up this

**Comment by RoyJia** [comment]
looks like "Ломбард" is just the translation with language Ukrainian
I found this - https://www.wikidata.org/wiki/Q176637, there are many language versions

so I'm not able to make sure "Ломбард" is a brand

**Comment by RoyJia** [comment]
ok, let me finish it

**Comment by RoyJia** [comment]
@bhousel Please help to review - https://github.com/osmlab/name-suggestion-index/pull/1875

**Comment by matkoniecz** [comment]
closed by #1875, thanks!
