### ISSUE TITLE
Research needed for: shop/shoes|Journeys

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1609]
#### :thinking: We need help deciding what to do with "shop/shoes|Journeys"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/shoes|Journeys` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/shoes|Journeys`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/shoes|Journeys`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bonbon12** [comment]
Hello, im looking at this issue and just wanted to confirm a few things.
1. What is the "count value" indicating in clothes.json
2. is the "needs wikidata" tag implying that we need to create wikidata for the store?
3. i also noticed that in clothes.json that adidas is missing. can i add this?

**Comment by bhousel** [comment]
Hello!

> 1. What is the "count value" indicating in clothes.json

This is generated automatically based on the last time we processed data from OpenStreetMap. You don't need to change it.

> 2. is the "needs wikidata" tag implying that we need to create wikidata for the store?

It means that someone needs to add the brand to wikidata. The [operating company](https://en.wikipedia.org/wiki/Genesco) has a page and wikidata id, but the brand does not.  So, somebody with experience in editing Wikipedia/Wikidata should do this part.

> 3. i also noticed that in clothes.json that adidas is missing. can i add this?

It looks like Adidas already exists under `shop/sports.json`, so it's not necessary to add it to `shop/shoes.json`
