### ISSUE TITLE
Research needed for: shop/shoes|Office

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1614]
#### :thinking: We need help deciding what to do with "shop/shoes|Office"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/shoes|Office` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/shoes|Office`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/shoes|Office`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by SilentSpike** [comment]
Likely this: https://en.wikipedia.org/wiki/Office_Holdings
Their website: https://www.office.co.uk/view/content/about-us-page

I guess this wikipedia page doesn't apply to the brand as it's not specific to the chain, but to the company which operates them? 🤔

**Comment by lakedistrictOSM** [comment]
The infobox on that wiki page literally says that it's a shoe shop, so I'd say that it's good enough to use. It can go in the operator wiki tags at the very least...

**Comment by Adamant36** [comment]
Looks perfectly fine for brand wikipedia tag. The name is "Office" and the article says how many stores they have. It specifically says the products is shoes also. So I don't see why not. 

The operator Wikipedia tag could be Truworths. It says in the article that its their parent company.

**Comment by Adamant36** [comment]
Closed in #2384
