### ISSUE TITLE
Vulcanizare looks like generic name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#162]

**Comment by matkoniecz** [comment]
"invalid" label is rather for issues that are invalid (say, reporting things like "I dislike red color of motorways on the OSM website")

**Comment by bhousel** [comment]
> "invalid" label is rather for issues that are invalid (say, reporting things like "I dislike red color of motorways on the OSM website")

Yes I agree.. I didn't add these - but it is very helpful to have all the "generic names" flagged!

**Comment by Adamant36** [comment]
My bad. I'll remove all the "invalid" labels from the generic name issues that I added them to when I get the time. Just having the "generic" label is enough on its own anyway.

**Comment by bhousel** [comment]
No worries.. I removed them already
