### ISSUE TITLE
Research needed for: shop/stationery|Office Max

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1640]
#### :thinking: We need help deciding what to do with "shop/stationery|Office Max"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/stationery|Office Max` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/stationery|Office Max`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/stationery|Office Max`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
> My understanding is that this issue has been generated for the single item in the `match` property

The match property does only contain other names a user might use for this brand. In this case it should probably be not removed...
But this issue has already been fixed with https://github.com/osmlab/name-suggestion-index/commit/bef2100ccc09218d7eb75f7950763c385bbdc06a and https://github.com/osmlab/name-suggestion-index/pull/1883

**Comment by bhousel** [comment]
Yes, @ENT8R is right.. "match" is for alternative less-preferred names.

That property really does have a confusing name - I think I should make a `FAQ.md` document for things like this.   Or consider renaming it.. 🤔
