### ISSUE TITLE
Research needed for: shop/supermarket|AD Delhaize

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1644]
#### :thinking: We need help deciding what to do with "shop/supermarket|AD Delhaize"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|AD Delhaize` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|AD Delhaize`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|AD Delhaize`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by maxerickson** [comment]
These probably belong with "Delhaize". There's several name variations in use:

http://overpass-turbo.eu/s/DmQ

https://en.wikipedia.org/wiki/Ahold_Delhaize#Belgium

**Comment by ENT8R** [comment]
From reading https://www.delhaize.be/nl-be/about-delhaize/our-brands/ad I would say that this is the same case as #1675: AD Delhaize is the same as Delhaize, just a little bit smaller.
So is it safe to add
```json
"brand:wikidata": "Q1184173",
"brand:wikipedia": "fr:Delhaize",
```
for the entry of AD Delhaize too?

**Comment by bhousel** [comment]
Yes, ok to have 2 entries if someone looking at a map and thinking about going there might care whether it’s the large store or not.

**Comment by ENT8R** [comment]
But then there should also be two separate Wikidata entries, shouldn't it?

**Comment by bhousel** [comment]
> But then there should also be two separate Wikidata entries, shouldn't it?

I think so, if it really is different enough.

**Comment by ENT8R** [comment]
I decided to use the same Wikipedia and Wikidata entries for AD Delhaize now too, because even the French Wikipedia article mentions AD Delhaize in the same list as Delhaize.
