### ISSUE TITLE
Hotel panorama is not always a brand

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#165]
Not doing PR for now as it would be a good idea to check whatever all names with "hotel" in name should be dropped

**Comment by bhousel** [comment]
Yeah - my gut says that most of them should not be in the index.

The script I wrote for #151 will hopefully prune down this list a lot.  If a lookup returns something like "hotel chain" than I'll can keep it, but otherwise I'm going to filter them into the discard list.

**Comment by matkoniecz** [comment]
At the very least Hotel Ibis is correct. I guess that it will be necessary to consider each one.

**Comment by bhousel** [comment]
This is old - looks like this hotel is in `filters.json` now..
