### ISSUE TITLE
Research needed for: shop/supermarket|Bulk Barn

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1656]
#### :thinking: We need help deciding what to do with "shop/supermarket|Bulk Barn"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Bulk Barn` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Bulk Barn`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Bulk Barn`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by jyntran** [comment]
I found Bulk Barn's [Wikidata value](https://www.wikidata.org/wiki/Q4996466) but no Wikipedia article ([Bulk foods](https://en.wikipedia.org/wiki/Bulk_foods) has a link to a [non-existing article](https://en.wikipedia.org/wiki/Bulk_Barn) though). Would it be okay to add only `brand:wikidata` in this case?

**Comment by bhousel** [comment]
> Would it be okay to add only `brand:wikidata` in this case?

yes!  We are starting to find a few entries like this.. That's ok..
