### ISSUE TITLE
Продукти is likely to be a generic name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#166]
Google translate suggests that it may be a generic name - https://www.google.com/search?hl=en&biw=1366&bih=578&sclient=psy-ab&q=translate+%D0%9F%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B8&btnG=&oq=&gs_l=&pbx=1

https://www.openstreetmap.org/way/620619264 and https://www.openstreetmap.org/node/5863413077 suggests that it was used as a generic name (it is unlikely that there are shops with Bulgarian name in a Polish village)

For now I opened https://www.openstreetmap.org/note/1543698 and https://www.openstreetmap.org/note/1543696 but maybe I should just delete names and make PR deleting this entry and it is undue concern to check

**Comment by bhousel** [comment]
This was done
