### ISSUE TITLE
Research needed for: shop/supermarket|E-Center

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1675]
#### :thinking: We need help deciding what to do with "shop/supermarket|E-Center"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|E-Center` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|E-Center`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|E-Center`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
This should probably belong to the entry of `Edeka`. E-Center is just an Edeka with a larger area. See also [this article](https://translate.google.de/translate?sl=auto&tl=en&u=https%3A%2F%2Fverbund.edeka%2Funternehmen%2Fwas-ist-der-edeka-verbund%2Fm%25c3%25a4rkte-vertrieb%2Fedeka%2F) on the official website of the supermarket chain.
Or is it also an option to leave it as it is (two separate entries) and just add the Wikidata and Wikipedia entry of the `Edeka` entry?

**Comment by bhousel** [comment]
> Or is it also an option to leave it as it is (two separate entries) and just add the Wikidata and Wikipedia entry of the `Edeka` entry?

It's ok to leave as two separate entries and have them share wiki tags.
