### ISSUE TITLE
Research needed for: shop/supermarket|E. Leclerc Drive

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1676]
#### :thinking: We need help deciding what to do with "shop/supermarket|E. Leclerc Drive"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|E. Leclerc Drive` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|E. Leclerc Drive`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|E. Leclerc Drive`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by johanricher** [comment]
[Already added][https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/supermarket.json#L1136).

**Comment by Adamant36** [comment]
From what I remember when I researched E.Leclerc Drive is a sub brand of E.Leclerc and a different store type. So it could still its own Wikidata information instead of using E.Leclerc. Which is really just the operator. I could be remembering wrong though.

**Comment by Lulucmy** [comment]
> From what I remember when I researched E.Leclerc Drive is a sub brand of E.Leclerc and a different store type. So it could still its own Wikidata information instead of using E.Leclerc. Which is really just the operator. I could be remembering wrong though.

E.Leclerc Drive is a sub brand of Leclerc indeed. It's a [Drive-through](https://en.wikipedia.org/wiki/Drive-through), you place orders on internet and you pick them up at these places. These "Drives" are often at the back of a E.Leclerc supermarket.

**Comment by Adamant36** [comment]
> E.Leclerc Drive is a sub brand of Leclerc indeed. It's a Drive-through, you place orders on internet and you pick them up at these places. These "Drives" are often at the back of a E.Leclerc supermarket.

Thanks for information. That's what I thought. So it sounds like it needs its own unique entry.

**Comment by johanricher** [comment]
Let's create a Wikidata item first, then.

**Comment by Lulucmy** [comment]
> Let's create a Wikidata item first, then. @Adamant36 you go ahead? And then another for E.Leclerc station service (fuel station). And then...
> ![image](https://user-images.githubusercontent.com/10212787/54518574-e475e680-4964-11e9-8a7e-46569dd57f77.png)

The problem is some of these brands are just a sheft in an E.Leclerc store. for e.g. the "Jardin"  : 
![image](https://user-images.githubusercontent.com/20552095/54518763-5bab7a80-4965-11e9-8ced-125aa577c58e.png) you may find it between ther shefts, not as a different store.

**Comment by johanricher** [comment]
They can be separate stores.

![](https://www.lescar-soleil.com/thumbs/1920x600r/adherents/jardi-e-leclerc/lescar-soleil-jardinerie-e.leclerc-devanture.jpg)

This king of sub-brands tend to change very frequently. It's just marketing. Most of the time, the corresponding POIs are closed to a superpermarket under the main brand. Adding all the sub-brands on WIkidata (and maintaining them) seems like an unnecessary effort. I would still use the E.Leclerc Wikidata item to tag all relevant POIs on OSM.

**Comment by Lulucmy** [comment]
> They can be separate stores.
> 
> ![](https://camo.githubusercontent.com/86050dd1e2b4a13af98d8956dc51b6510bf12569/68747470733a2f2f7777772e6c65736361722d736f6c65696c2e636f6d2f7468756d62732f3139323078363030722f6164686572656e74732f6a617264692d652d6c65636c6572632f6c65736361722d736f6c65696c2d6a617264696e657269652d652e6c65636c6572632d646576616e747572652e6a7067)
> 
> This kind of sub-brands tend to change very frequently. It's just marketing. Most of the time, the corresponding POIs are close to a superpermarket under the main brand. Adding all the sub-brands on WIkidata (and maintaining them) seems like an unnecessary effort. I would still use the E.Leclerc Wikidata item to tag all relevant POIs on OSM.

Ok, I've never seen some as seperate stores...
![image](https://user-images.githubusercontent.com/20552095/54519357-a11c7780-4966-11e9-9aac-b81a0d03caf4.png)
Here are the sub-brands that are often without E.Leclerc stores you should add. These are pretty common in France.

**Comment by Adamant36** [comment]
> Adding all the sub-brands of E.Leclerc on WIkidata (and maintaining them) seems like an unnecessary effort. I would still use the E.Leclerc Wikidata item to tag all relevant POIs on OSM.

For me it depends on if they have usage in OSM or not and how much. I'm not going to create individual Wikidata items for all of them, because I doubt most of them are even tagged in OSM at all, but E.Leclerc Drive specifically had its own entry and a bunch of usage already. So I have know problem creating a Wikidata entry for that one. It doesn't have to be all or nothing.

**Comment by johanricher** [comment]
> Ok, I've never seen some as seperate stores...

Me neither. :) Same for "L'auto or "La Borne"...

**Comment by Lulucmy** [comment]
> > Ok, I've never seen some as seperate stores...
> 
> Me neither. :) Same for "L'auto or "La Borne"...

You'll find "La borne" near E.Leclerc or near some shopping centers : 
![image](https://user-images.githubusercontent.com/20552095/54520022-02911600-4968-11e9-926c-c2b31d403e1d.png)
And "Lauto" in many towns : 
![image](https://user-images.githubusercontent.com/20552095/54520096-2e140080-4968-11e9-85a2-4fe3b06ad334.png)
But I agree with @Adamant36 I doubt most of them are tagged in OSM...

**Comment by Adamant36** [comment]
Just giving it a quick check over, name=La borne (66 uses), Brico (172 uses), Espace Culturel (50ish uses), Optique (33 uses), Parapharmacie (50ish), Voyages (11ish). So it might be worth creating Wikidata entries for some of them. Brico in particular.

**Comment by johanricher** [comment]
The string "Brico" might be used to tag other stores. Existing brands are "Brico Dépôt", "Bricomarché", "Brico Cash", or even "Brico" (in Belgium), to name just a few.

**Comment by Adamant36** [comment]
Maybe. It can always be added with a country code filter if need be. Just not adding it works also though. I still might create a Wikidata entry for it anyway. Otherwise, it can't be add to E. Leclerc's page as a subsidiary.
