### ISSUE TITLE
Research needed for: shop/supermarket|Famiglia Cooperativa

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1681]
#### :thinking: We need help deciding what to do with "shop/supermarket|Famiglia Cooperativa"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Famiglia Cooperativa` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Famiglia Cooperativa`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Famiglia Cooperativa`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by pgmpofu** [comment]
@bhousel may I work on this?

**Comment by Adamant36** [comment]
@pgmpofu, go ahead. You don't need premission to work on things. There's a guide in the CONTRIBUTING.md file on how to do things if you need it.

**Comment by pgmpofu** [comment]
I am no longer working on this issue. Anyone may take over. Thanks

**Comment by cmacswan07** [comment]
I went ahead and submitted a PR for this.

**Comment by ENT8R** [comment]
This has already been fixed with https://github.com/osmlab/name-suggestion-index/pull/2432
