### ISSUE TITLE
Research needed for: shop/supermarket|Foodland

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1684]
#### :thinking: We need help deciding what to do with "shop/supermarket|Foodland"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Foodland` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Foodland`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Foodland`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by anselb** [comment]
There appears to be 5 different Foodland supermaket chains in different countries and in different regions of the US according to [Wikipedia](https://en.wikipedia.org/wiki/Foodland).

**Comment by co16353sidak** [comment]
Would love to work on this @bhousel @Adamant36. Please give me the go-ahead.

**Comment by bhousel** [comment]
@co16353sidak if there are several different Foodland brands, it might be better to hold off on adding them right now.. Definitely feel free to work on one that is a bit more straightforward!
