### ISSUE TITLE
Research needed for: shop/supermarket|K+K

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1700]
#### :thinking: We need help deciding what to do with "shop/supermarket|K+K"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|K+K` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|K+K`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|K+K`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by OthankQ** [comment]
Beginner here! Is this free to take?

**Comment by Adamant36** [comment]
Hi there. Sure, go for it. You usually don't need permission to work on things here. It looks like it needs a Wikidata entry for it. So if you don't know how to work with Wikidata it might be an obstacle. Otherwise, there's a guide in the contributing file that use as a reference and also feel free to ask any questions you might have, here or in a new issue.

**Comment by OthankQ** [comment]
@Adamant36 Hello there! So I did some research on 'K + K' and it looks like it's not a supermarket brand at all. It's also not in any of the wikipedia entry.  So my next step should be 

1. Edit config/filters.json to add an expression that discards it
2. Edit config/canonical.json to remove the entry for shop/supermarket|K+K

I had some questions about those steps. when editing filters.json, I'm assuming I have to edit 

"^shop/(convenience|kiosk)\\|(bp|esso|exxon|mobil|shell)$"
 this line to
"^shop/(convenience|kiosk|supermarket)\\|(bp|esso|exxon|mobil|shell|K+K)$" 

But I'm kind of curious as to how to edit 'discardNames' object.
Also, config/canonical.json file seem to be nonexistant in my folder.

**Comment by bhousel** [comment]
From [this Overpass query](https://overpass-turbo.eu/s/GMC), it looks like it is a somewhat local brand around northern Germany

<img width="200" alt="Screenshot 2019-03-08 14 17 33" src="https://user-images.githubusercontent.com/38784/54050374-0032fd00-41ad-11e9-8864-5d7f9487f0e1.png">


This is probably either their site, or something related:
https://www.marktjagd.de/dortmund/filialen-k-k-klaas-kock:a28854

**Comment by OthankQ** [comment]
@bhousel Wow this is very interesting! I was able to find their wikipedia entry and retrieve both wikipedia and wikidata values! I will make a pull request! I am kind of confused because in the url of the wikipedia page, it showed something like %26 instead of +. I'm guessing it has to do something with ASCII.

**Comment by Adamant36** [comment]
I guess there's also a K+K hotel chain in Europe. Along with KK supermarket chain in Asian somewhere. There isn't any information about them anywhere that I could find, but they might be worth adding to at some point or at having a no match,  just to help with possible miss tagging if nothing else.

**Comment by OthankQ** [comment]
I made a pull request! But seeing how @Adamant36 mentioned there is also a hotel chain in Europe and supermarket chain in Asia, what's the next thing I can do to resolve that? What does it mean by 'having a no match'?
