### ISSUE TITLE
Research needed for: shop/supermarket|Maxi

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1711]
#### :thinking: We need help deciding what to do with "shop/supermarket|Maxi"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Maxi` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Maxi`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Maxi`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by rye761** [comment]
There are two different Maxi supermarkets, both called "Maxi". A serbian one and a Canadian one (Quebec only). How would we resolve this conflict? Two entries with different country codes?

**Comment by matkoniecz** [comment]
> Two entries with different country codes?

Exactly! (that is purpose of country codes).

**Comment by bhousel** [comment]
#1880 tracks this - but I'm not 100% sure it works 🤔

**Comment by magol** [comment]
It is also a Supermarket called Maxi in Sweden

**Comment by bhousel** [comment]
Thanks @magol  - I can definitely add these if they are a brand
https://en.wikipedia.org/wiki/ICA_Gruppen

**Comment by bhousel** [comment]
Reading that page, it lists:  ICA Maxi (closed 2012)
Are they still a brand that exists in the wild?  If they've been rebranded we should leave it off, otherwise users may create more of them.

**Comment by magol** [comment]
ICA Maxi is existing all over Sweden.
The correct name is ICA Maxi, but many is naming it Maxi.

**Comment by bhousel** [comment]
thanks @magol - i just added ICA Maxi in e3f04d6
