### ISSUE TITLE
Research needed for: shop/supermarket|Prix

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1735]
#### :thinking: We need help deciding what to do with "shop/supermarket|Prix"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Prix` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Prix`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Prix`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by maxerickson** [comment]
Supermarket in Italy: http://www.prixquality.com/

Needs wikidata.

There's also a fair number of ["name=Prix" in Norway](http://overpass-turbo.eu/s/CVb), which are probably https://en.wikipedia.org/wiki/Coop_Prix.

**Comment by maxerickson** [comment]
Supermarket in Italy: http://www.prixquality.com/

There's also a fair number of ["name=Prix" in Norway](http://overpass-turbo.eu/s/CVb), which are probably https://en.wikipedia.org/wiki/Coop_Prix.

**Comment by Adamant36** [comment]
I created Wikidata entry Q61994819 for the Italian one

**Comment by ENT8R** [comment]
> There's also a fair number of "name=Prix" in Norway, which are probably https://en.wikipedia.org/wiki/Coop_Prix.

Using Overpass Turbo, I could not see any supermarkets with name=Prix in Norway which is why I closed the issue by adding the italian supermarket chain.
