### ISSUE TITLE
Research needed for: shop/supermarket|Светофор

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1785]
#### :thinking: We need help deciding what to do with "shop/supermarket|Светофор"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Светофор` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Светофор`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Светофор`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by maxerickson** [comment]
Someone can create a new Wikidata entry for it and we can add that, there doesn't need to be a Wikipedia entry.

**Comment by mukulkhanna** [comment]
Hi @maxerickson , I was making a Wikidata entry for the above. There was an option to choose the language. Should I choose English or Russian (because its a supermarket in Russia)?

**Comment by mukulkhanna** [comment]
@maxerickson I have created the wikidata for the above.

https://www.wikidata.org/wiki/Q61875920
