### ISSUE TITLE
filter out completely mismatching wikidata entries and warn if some are present

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#181]
For start, anything that is instance of Q5 (human), directly or indirectly should not be shown in wiki matcher

**Comment by matkoniecz** [comment]
#2464 is exactly the same and explaining it better. Also, is this scripted still used?

**Comment by bhousel** [comment]
> Also, is this scripted still used?

I haven't been using it.. We might be past the point where we can just deal with all new entries that enter the list by manually reviewing and matching them - this is better anyway!

Also we might want to consider increasing the threshold above 50?  At least for some very generic kinds of POIs like convenience stores and restaurants, we are catching a lot of generic names  (see 457f2220)

**Comment by matkoniecz** [comment]
I hoped that we may lower minimal count in the future to catch more without people adding them manually :)

I wonder how many new nonbrand shared names will be now appearing once that initial wave is gone.
