### ISSUE TITLE
allow to store false matches of wikidata/wikipedia - for example in canonical 

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#182]
This way, especially for close matches, risk of (re)introducing wrong match is lowered and rerunning through list to process new wikipedia article/wikidata entries will be easier

**Comment by bhousel** [comment]
Can you give an example?

We can put "almost" matches into the `match` property currently.
`match` just means "If I see this, I really mean..."

For example:
```
  "amenity/fast_food|McDonald's": {
    "count": 19040,
    "match": [
      "amenity/fast_food|Mc Donald's",
      "amenity/fast_food|McDonalds",
      "amenity/fast_food|McDonald’s",
      "amenity/restaurant|Mc Donald's",
      "amenity/restaurant|Mc Donalds",
      "amenity/restaurant|McDonald's",
      "amenity/restaurant|McDonalds",
      "amenity/restaurant|McDonald’s"
    ],
```

**Comment by matkoniecz** [comment]
AFAIK, match_wikiTags.js script is no longer used anyway
