### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1913]
Because CI is nice

_Originally posted by @bhousel in https://github.com/osmlab/name-suggestion-index/pull/1910/comment#issuecomment-430729658_

**Comment by matkoniecz** [comment]
What is necessary? I have no big experience with travis but I may play around with it.

 - merging  #1917 
 - activate it at https://travis-ci.org/osmlab/name-suggestion-index  (I am not sure whatever I have sufficient permissions to do that)
 - look through jobs to see whatever something fails without a good reason

Something else?

**Comment by good-praxis** [comment]
Additionally:
- set up protection for master, that demands Travis CI passing in order to allow merge 

(admins can merge anyhow, but this is best practice)

**Comment by matkoniecz** [comment]
branch protection may be set up at https://github.com/osmlab/name-suggestion-index/settings/branches
