### ISSUE TITLE
What's missing?

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1934]
I'm really excited by the response to this repository!  We're building a really useful link between OpenStreetMap and Wikidata.  Today we've merged over 70 pull requests, which has got to be a record for me.  Thank you for all your help!  🙇 

This issue is just a placeholder for **anything else that you notice is missing from the index**.  

The index was seeded by names which exist more than 50x in OpenStreetMap.  I know from hanging out in malls, shopping centers, and airport terminals that we are missing a lot of brands.  

No Auntie Anne's 🥨 ?
No Nathan's 🌭?
No Blue Bottle ☕️ ?
No Chop't 🥗 ?
No problem!

Just add it anyway, following the [contributor guidelines](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md).  Copy an existing similar entry in the index, add the wiki tags, and make sure to include `"nocount": true` to suppress the warning that it's a new thing.

When submit your pull request, tag (but don't close!) this issue.
You can add "re: #1934" in the commit message or pull request.

**Comment by matkoniecz** [comment]
Also, I would encourage to look at location you know at OSM ( https://www.openstreetmap.org/ ) and add missing shops! (there is an "Edit" button on top left leading to built-in editor with tutorial for new users).

**Comment by 1ec5** [comment]
* [PetScan query of articles about chains of all sorts at the English Wikipedia](https://petscan.wmflabs.org/?psid=6157573)
* [Rough diff of English Wikipedia articles listed in the name suggestion index versus English Wikipedia articles in the PetScan query above](https://gist.github.com/1ec5/77ab9bfbaed39aa4524bda049511b1c9)

**Comment by 1ec5** [comment]
[This spreadsheet](https://docs.google.com/spreadsheets/d/14yhHtAtKjqUL5fo5m1CqkBTlE4whzXBH91J3HRweEL0/edit?usp=sharing) lists hidden chains (of the non-Markov variety). Those in the first tab are included in the name-suggestion-index but not explicitly identified as chains via English Wikipedia categories. Those in the second tab are the other way around: explicitly identified as chains via Wikipedia categories but omitted from the name-suggestion-index.

Steps to reproduce:

1. Install [`jq`](https://stedolan.github.io/jq/).
1. Clone the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index/) repository.
1. [Search the English Wikipedia for categories about chains](http://en.wikipedia.org/wiki/Special:Search/Special:Search/category:intitle:chains).
1. Run Petscan on the English Wikipedia looking for [articles about chains](https://petscan.wmflabs.org/?psid=6158970), changing the format to CatScan JSON.
1. Get English Wikipedia articles in the name suggestion index:
   ```bash
   cat config/canonical.json | jq -r '.[].tags["brand:wikidata"] | strings' | sort -u > nsi.txt
   ```
1. Get English Wikipedia articles in the PetScan results:
   ```bash
   cat petscan.json | jq -r '.["*"][0].a["*"][].q | strings' | sort -u > petscan.txt
   ```
1. Diff the results:
   ```bash
   diff nsi.txt petscan.txt | grep '<' | sed 's/^< //' | sort -u
   diff nsi.txt petscan.txt | grep '>' | sed 's/^> //' | sort -u
   ```
1. Install the [Wikipedia and Wikidata tools](https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/) add-on for Google Sheets.
1. Invoke the `WIKIDATALABELS` function on each QID to get its English label.

The next step would be to join on one of the SPARQL queries in https://github.com/osmlab/name-suggestion-index/issues/151#issuecomment-424097840 to determine which chains need additional claims in Wikidata.

**Comment by bhousel** [comment]
This is happening, so we can close this 😄
