### ISSUE TITLE
Add back "RCBC Savings Bank"?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#1948]
It was removed in #1938 and it is owned by similarly named bank and share brand - but I think that bank named "RCBC Savings Bank" probably still should be tagged with `name=RCBC Savings Bank`, not `name=RCBC`

**Comment by bhousel** [comment]
Isn't it all the same bank? 
https://en.wikipedia.org/wiki/Rizal_Commercial_Banking_Corporation

it seems similar to this - where some people use "CIBC" and others spell out "CIBC Banking Centre", so we just prefer the short version:
```
  "amenity/bank|CIBC": {
    "count": 558,
    "countryCodes": ["ca"],
    "match": ["amenity/bank|CIBC Banking Centre"],
    "tags": {
      "amenity": "bank",
      "brand": "CIBC",
      "brand:wikidata": "Q666694",
      "brand:wikipedia": "en:Canadian Imperial Bank of Commerce",
      "name": "CIBC"
    }
  },
```

**Comment by matkoniecz** [comment]
#1938 had

> I removed RCBC Savings Bank entry since it's a subsidiary of RCBC: https://en.wikipedia.org/wiki/Rizal_Commercial_Banking_Corporation#RCBC_Savings_Bank

So it is single bank with sub-brands like Carefour (for large supermarkets) and Carefour Express (for bigger convenience shops/small supermarkets).

**Comment by bhousel** [comment]
yeah it's definitely fuzzy (like all things in OSM!)

There is probably enough of a difference to justify 2 entries for:
* Carefour (supermarket) and Carefour Express (convenience)
* Pizza Hut (restaurant) and Pizza Hut Express (fast food)

But we don't really have different tags for different kinds of banks...  They might not even be different kinds of banks.  I think when in doubt we should just discard the less popular name variant, and only keep a duplicate if the branding is really very different or implies a different osm tagging.

**Comment by matkoniecz** [comment]
> But we don't really have different tags for different kinds of banks... They might not even be different kinds of banks. 

I agree, but based on information that I have seems that encouraging to map "RCBC Savings Bank" as "RCBC" is not necessary and may be harmful (not something really bad, but difference is big enough that mappers care). Especially that with brand tag one may find all sub-brands.

**Comment by bhousel** [comment]
Closing here.. I think our handling of "RCBC" is consistent with other banks in the index.
If people want to add `official_name` tags for the longer version of the name, that's cool.
