### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#1980]
Now that things are going smoothly with getting this repo cleaned up, I'd like to release a version 1 so that some of the work we've done can make it quickly into [iD](https://github.com/openstreetmap/iD) and the other downstream OSM editors.

My plan is to rebuild the `dist/name-suggestions*` files but keep them backward-compatible with the current files.  

The only difference will be that going forward, _we'll only include entries that have been matched to a `wikidata` tag_.  

This will eliminate all of the crappy names that are currently suggested by iD - and it will mean that as users add more branded stuff to OpenStreetMap, it will include the wiki tags that let people do more interesting analysis of the data.

Side note:  `npm run build` will now print a "completeness score" so that we can track how well we are doing at this.

<img width="409" alt="screenshot 2018-10-19 10 35 00" src="https://user-images.githubusercontent.com/38784/47224915-bdea5a00-d38a-11e8-809c-549a98fa9fd0.png">

**Comment by matkoniecz** [comment]
Maybe it would be also a good idea to remove all duplicates listed by `npm run build` before releasing 1.0?

Some of Hactoberfest mentioned that it is scary, also many of duplicates are indicating invalid entries.

**Comment by bhousel** [comment]
> Maybe it would be also a good idea to remove all duplicates listed by `npm run build` before releasing 1.0?

Maybe not all of them but at least the most common ones?   I'd like to get a new iD released in the next week or so.

I think when I created the Hacktoberfest issues, I skipped the keys that were potential duplicates - thinking that resolving those might require more OSM knowledge..

**Comment by bhousel** [comment]
> And maybe many similar cases; so in the worst case - **we are injecting bad brands/wikidata/wikipedia tags to the openstreetmap;** and the new OSM contributors not detect this.

I definitely don't want to inject bad brands into OSM - I'm very much in favor of holding off the tricky cases like "ABC". 

I believe that all of the cases that we've matched up so far have been matched correctly.  I have been reviewing the PRs and we've even rejected a few which have been wrong or misleading.  (I do actually open wikidata and look up the Q code before clicking the green merge button)


In the very worst case - we inject a misleading brand as new users are adding things to OSM, but can identify them all pretty easily with overpass and update/remove them.

**Comment by ImreSamu** [comment]
>I believe that all of the cases that we've matched up so far have been matched correctly. 

for me - it is extremely hard to research every brand in the database: http://www.wipo.int/branddb/en/

Another `local brand` type - candidate : 
* https://github.com/osmlab/name-suggestion-index/issues/2101

**Comment by ImreSamu** [comment]
`countryCodes` is important - and not so easy to find them.

Quick test - 
* https://github.com/osmlab/name-suggestion-index/issues/2101
* https://github.com/osmlab/name-suggestion-index/issues/2102
* https://github.com/osmlab/name-suggestion-index/issues/2106
* https://github.com/osmlab/name-suggestion-index/issues/2107
* https://github.com/osmlab/name-suggestion-index/issues/2108

>In the very worst case - we inject a misleading brand as new users are adding things to OSM, 
>but can identify them all pretty easily with overpass and update/remove them.

I would like to minimalize the worst case issues.

**Comment by bhousel** [comment]
@ImreSamu Thank you for adding the countryCodes - I agree that it's important and, if we can scope these presets to just countries where they should used, we should do that.

I also want to add that - probably anything we do at this point is better than what iD currently does.  The existing index in iD doesn't have any concept of country codes at all, and is full of a _lot_ of generic / outdated / duplicate entries.  It's really pretty bad, which was why I made this project a priority the past few months 😄 

It will be nice to see all these kinds of results go away! 

abc | school
--- | ---
<img width="250" alt="screenshot 2018-10-22 09 19 49" src="https://user-images.githubusercontent.com/38784/47294629-a9e96700-d5db-11e8-97aa-8c45545431e2.png"> | <img width="250" alt="screenshot 2018-10-22 09 22 17" src="https://user-images.githubusercontent.com/38784/47294772-0187d280-d5dc-11e8-8d96-82384ca1ab1d.png">

**Comment by bhousel** [comment]
Hey, I released v1.0.0 just now!  🎊 
Thanks again for everyone for helping out with this project..  ❤️
