### ISSUE TITLE
Should state-run 'brands' be considered brands?

### ISSUE THREAD

**Issue by good-praxis** [osmlab/name-suggestion-index#2028]
In particular this is about #2009 
These shops are _all_ government run because of the specific regulation [[source](https://en.wikipedia.org/wiki/Doh%C3%A1nybolt)]. They are close enough to be considered generic, but since they're all ran by the same actor, should they be considered generic? There is no tangible difference between this and a company running a franchise.

**Comment by ImreSamu** [comment]
As a Hungarian - my personal  opinion

Remove
*   "shop/tobacco|Dohánybolt"
*   "shop/kiosk|Nemzeti Dohánybolt"

Keep: 
*  "shop/tobacco|Nemzeti Dohánybolt" - without a "brand"

**Comment by good-praxis** [comment]
"brand" in these cases mostly don't actually mean real life brands, it's just kind if _this_ specific kind of shop (or this "brand" of shop)

**Comment by ImreSamu** [comment]
@good-praxis : 

No "hungarian" (local language) version;
so I would not  add this 2 tags - to the `shop/tobacco|Nemzeti Dohánybolt`
* "brand:wikidata": "Q20639040",
*  "brand:wikipedia": "en:Dohánybolt",
imho:  the https://www.wikidata.org/wiki/Q20639040  is low quality wikidata info

the `brand=Nemzeti Dohánybolt` - maybe usefull;    
but  We (=hungarian community) need to discuss in the hungarian mail list,  
( But it takes a lot of time -  but If we have a fdifferent consensus - I  can change later )

it is ok for you ?

**Comment by bhousel** [comment]
Yeah this is in some US states for state run alcohol shops too.
Virginia ABC #969  is one of these

https://www.abc.virginia.gov/
https://en.wikipedia.org/wiki/Virginia_Alcoholic_Beverage_Control_Authority
https://www.wikidata.org/wiki/Q7934236

I'm ok with it.  They often operate like a brand and have a logo and common identity.

**Comment by matkoniecz** [comment]
> but We (=hungarian community) need to discuss in the Hungarian osm mail list,
> ( But it takes a lot of time

I think that it may give good results. Ask here in case of any doubts (I am unable to contribute at Hungarian mailing list due to language issues).

**Comment by good-praxis** [comment]
So I guess we will put this on freeze for now? Until @ImreSamu returns with a consensus of the hu osm mail list?

**Comment by ImreSamu** [comment]
@good-praxis : 
* I have sent an [e-mail to the hungarian osm mail list](https://groups.google.com/forum/#!topic/openstreetmap-hungary/CrF9pt2R_OI).
* I have fixed the wikidataid:  https://www.wikidata.org/w/index.php?title=Q20639040&action=history

need 1-2 days - for the first consensus ..

my proposal was:

keep:
```
"countryCodes": ["hu"],   
      shop=tobacco
      name=Nemzeti Dohánybolt
      brand=Nemzeti Dohánybolt	     
      brand:wikidata=Q20639040
      brand:wikipedia=en:Dohánybolt
```


remove:
```
  "shop/kiosk|Nemzeti Dohánybolt": 56,   
  "shop/tobacco|Dohánybolt": 107,             
  "shop/tobacco|Nemzeti dohánybolt": 157,
```

**Comment by matkoniecz** [comment]
Thanks for doing it! Hopefully there will be a consensus on mailing list.

**Comment by bhousel** [comment]
Thanks @ImreSamu !   We'll wait to hear back.. There is no rush 😄

**Comment by bhousel** [comment]
Closing here .. yes state-run stores can be considered brands, and we have a bunch of them in the index now  👍
