### ISSUE TITLE
Don't allow `countryCodes` in the `tags` section

### ISSUE THREAD

**Issue by good-praxis** [osmlab/name-suggestion-index#2029]
Problem arose in #2009, specifically efee5fd9f8169d00bdd11cf5d29c286aa085330c
Maybe we can make the build script look out for that, too?

**Comment by bhousel** [comment]
ohhh this is just: "countryCodes" should not be in the `tags:` object

**Comment by bhousel** [comment]
ah looks like @ENT8R commented already 👍

**Comment by good-praxis** [comment]
@bhousel the idea of this issue was an improvement to the build script, that it should also validate the position of additional keys like countryCodes

**Comment by bhousel** [comment]
Thanks @good-praxis, I understand now

**Comment by bhousel** [comment]
I added the schema validation rule in 5277f94 and it right away caught several cases where the `countryCodes` were added as OpenStreetMap tags 😬
