### ISSUE TITLE
Project News

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2034]
Hey!  A few other housekeeping issues that I might as well mention here...

### Admins
I **really** want to thank everyone who has stepped up and contributed so much to this repo in the past week.  When I maintain an open source project, I believe in just granting admin rights to anyone who has contributed a dozen or so pull requests - so I've invited @eigenbrot, @sinclarius, @ENT8R, @maxerickson, and @good-praxis to be administrators on this project.  Thanks all 👏  

We can absolutely grow this list.  One interesting thing about this project is how much we benefit from having people contribute their local knowledge.  I'd love to see more contributors with experience in languages like Chinese, Arabic, Korean, Russian, Spanish, etc.  _The world is big._  So if you know anyone, please reach out to them!

### Slack
IF you are into Slack, OpenStreetMap US runs one that anybody can join at https://slack.openstreetmap.us/   
I created a channel on there called #poi specifically to talk about mapping businesses and brands.  Stop in and say hello!

### Hacktoberfest
I think most people know about this already from all the Hacktoberfest labels, but just in case you don't -- sign up on https://hacktoberfest.digitalocean.com/ with your github login, and submit 5 pull requests before the end of October to receive a free shirt!  Please share the news with anyone you know, especially if they are new to open source and want to learn.  

The [GitHub Guides](https://guides.github.com/) are a really great resource to get started, especially this one about how to fork a project and submit a pull request:  https://guides.github.com/activities/forking/

**Comment by good-praxis** [comment]
Whoops! I actually still don't have rights @bhousel !

**Comment by bhousel** [comment]
> Whoops! I actually still don't have rights @bhousel !

It's supposed to go to your email, but if it didn't you can accept at https://github.com/osmlab/name-suggestion-index/invitations

**Comment by bhousel** [comment]
Adding @xeluna to the admin list too - thank you for all the work you've done over the weekend 🙇
