### ISSUE TITLE
[limiting local brand]   amenity/cafe|Havanna

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2101]
I have found some  - "Havanna Cafe" in Hungary 
* https://www.facebook.com/havannacafe/
* https://www.facebook.com/balatonlellehavannacaffe

but probably none of the 2 example  member of argentine ["Café Havanna"](https://en.wikipedia.org/wiki/Havanna_(Argentine_company) )  chain    ( different logo )

Example - of  ( Argentine) Havanna Café :
* https://www.facebook.com/HavannaCafeParaguay/

![image](https://user-images.githubusercontent.com/2217320/47273272-19d2ff80-d592-11e8-9c68-7b18c94e2fbe.png)

So somebody can research -   (  and limit )   this brand fort he actual countries? 
```json
  "amenity/cafe|Havanna": {
    "count": 87,
    "tags": {
      "amenity": "cafe",
      "brand": "Havanna",
      "brand:wikidata": "Q2900869",
      "brand:wikipedia": "es:Havanna",
      "name": "Havanna"
    }
  },
```

**Comment by bhousel** [comment]
Closing here - logos will make it easier for mappers to be really sure that they are adding the thing that they think they are adding.
