### ISSUE TITLE
[limiting local brand] amenity/cafe|Espresso House

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2102]
Common amenity/cafe name -  need some countryCodes 

Now:
```
  "amenity/cafe|Espresso House": {
    "count": 155,
    "tags": {
      "amenity": "cafe",
      "brand": "Espresso House",
      "brand:wikidata": "Q10489162",
      "brand:wikipedia": "en:Espresso House",
      "name": "Espresso House"
    }
  },
```
![image](https://user-images.githubusercontent.com/2217320/47273391-26585780-d594-11e8-9c9e-83d644402e03.png)

My Test :  

Search in Facebook - and check the different  logos  
https://www.facebook.com/search/str/Espresso+House/keywords_pages

![image](https://user-images.githubusercontent.com/2217320/47273479-ff4e5580-d594-11e8-94eb-18e941ecd5c8.png)

**Comment by ENT8R** [comment]
According to Overpass (https://overpass-turbo.eu/s/CYS) the chain does only exist in Scandinavia and all the other results are just some smaller cafes. I think adding `"countryCodes": ["dk, "fi", "no", "se"]` should be sufficient for the current element.

**Comment by bhousel** [comment]
>  I think adding "countryCodes": ["dk, "fi", "no", "se"] should be sufficient for the current element.

☝️ I did this
