### ISSUE TITLE
[limiting local brand]  amenity/cafe|Espresso House

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2103]
Common amenity/cafe name -  need  add some countryCodes 

Now:
```
  "amenity/cafe|Espresso House": {
    "count": 155,
    "tags": {
      "amenity": "cafe",
      "brand": "Espresso House",
      "brand:wikidata": "Q10489162",
      "brand:wikipedia": "en:Espresso House",
      "name": "Espresso House"
    }
  },
```
![image](https://user-images.githubusercontent.com/2217320/47273391-26585780-d594-11e8-9c9e-83d644402e03.png)

My Test :  

Search in Facebook - and check the different  logos  
https://www.facebook.com/search/str/Espresso+House/keywords_pages

![image](https://user-images.githubusercontent.com/2217320/47273479-ff4e5580-d594-11e8-94eb-18e941ecd5c8.png)

**Comment by ENT8R** [comment]
Already covered by https://github.com/osmlab/name-suggestion-index/issues/2102

**Comment by ENT8R** [comment]
Already covered with https://github.com/osmlab/name-suggestion-index/issues/2102
