### ISSUE TITLE
[limiting local brand] - amenity/cafe|Cafe Coffee Day

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2107]
no `countryCodes` AND probably Local Brand ("amenity/cafe|Cafe Coffee Day")

```json
  "amenity/cafe|Cafe Coffee Day": {
    "count": 270,
    "tags": {
      "amenity": "cafe",
      "brand": "Cafe Coffee Day",
      "brand:wikidata": "Q5017235",
      "brand:wikipedia": "en:Café Coffee Day",
      "name": "Cafe Coffee Day"
    }
  },
```

**Comment by ENT8R** [comment]
Should be definetely `"countryCodes": ["in"]`
See https://overpass-turbo.eu/s/D04 and the wikipedia article the item links to for more information...

**Comment by good-praxis** [comment]
This one is probably not a local brand, the wikipedia article doesn't state which 6 countries CCD operates in, though. I also find the missing `é` suspicious

**Comment by good-praxis** [comment]
@ENT8R No, not just india, the wikipedia article states it operates in 6, albeit it unnamed, countries

**Comment by good-praxis** [comment]
[Nepal](https://www.sharesansar.com/newsdetail/coffee-giant-cafe-coffee-day-to-open-third-outlet-in-nepal-at-durbar-marg) is definitely one of those countries

**Comment by Adamant36** [comment]
Looks like they are all over India. there's also a few in other places, including Asian countries, north and south America, and Europe. That's hardly local. So I suggest this issue be closed. If anyone wants its easy to do a overpass turbo query [here](https://overpass-turbo.eu/?w=%22name%22%3D%22Cafe+Coffee+Day%22+global&R) to confirm where exactly they are.

**Comment by ImreSamu** [comment]
# "Cafe Coffee Day Global limited Company "

http://www.cafecoffeeday.com/  
https://www.wikidata.org/wiki/Q5017235
![image](https://user-images.githubusercontent.com/2217320/50569908-c17b6380-0d73-11e9-8cd6-2a7042abc532.png)


"countryCodes": ["in","at","cz","my","eg"]

based on
"CCD now has the largest footprint of multi-format cafés in India with more than 1600 cafés across 240+ cities. Now, CCD is going global, setting up cafés in Austria, Egypt, the Czech Republic and Malaysia."   http://www.cafecoffeeday.at/about_us.html

# Other

##   Russian -  "Coffee Day"

![image](https://user-images.githubusercontent.com/2217320/50569760-917d9180-0d6e-11e9-8375-e1968b5e3d6c.png)
https://www.openstreetmap.org/node/5203997345    ( now -  tagged as a shop=tea  )   
https://www.instagram.com/coffeeday63/   
https://vk.com/coffeeday63   

## Italian 
![image](https://user-images.githubusercontent.com/2217320/50569785-5465cf00-0d6f-11e9-8d1d-94a90304570c.png)
https://www.wipo.int/branddb/en/showData.jsp?ID=ITTM.2009901711597

## indonesian 
![image](https://user-images.githubusercontent.com/2217320/50569828-cbe82e00-0d70-11e9-8523-b19e049f2e95.png)
https://www.wipo.int/branddb/en/showData.jsp?ID=IDTM.D002015056055

## indonesian
![image](https://user-images.githubusercontent.com/2217320/50569842-647eae00-0d71-11e9-8945-ec4c8293133b.png)
https://www.wipo.int/branddb/en/showData.jsp?ID=IDTM.D002015005442

**Comment by bhousel** [comment]
Closing here - logos will make it easier for mappers to be really sure that they are adding the thing that they think they are adding.
