### ISSUE TITLE
[limiting local brand] - amenity/cafe|Caffè Nero

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2108]
no `countryCodes` AND probably a Local Brand ("amenity/cafe|Caffè Nero")

```json
  "amenity/cafe|Caffè Nero": {
    "count": 229,
    "match": [
      "amenity/cafe|Cafe Nero",
      "amenity/cafe|Caffe Nero"
    ],
    "tags": {
      "amenity": "cafe",
      "brand": "Caffè Nero",
      "brand:wikidata": "Q675808",
      "brand:wikipedia": "en:Caffè Nero",
      "name": "Caffè Nero"
    }
  },
```

**Comment by ENT8R** [comment]
I would not consider this as a local brand: https://en.wikipedia.org/wiki/Caff%C3%A8_Nero

> Currently, the company runs more than 825 coffee houses in nine countries: the UK, Ireland, Poland, Cyprus, Croatia, Turkey, the UAE, Oman, and the United States.

Do you read the wikipedia article or make a quick search with Overpass or why do you claim that this (and other) brands are local?

**Comment by ImreSamu** [comment]
Sorry, probably the 'local brand' term is not perfect, 

in my view - there are a lot of "Caffé Nero" café - different brand than [Caffé Nero(Q675808)](https://en.wikipedia.org/wiki/Caff%C3%A8_Nero)
* https://www.facebook.com/pg/Caff%C3%A8-Nero-161842344519308/about/?ref=page_internal

or reverse name order:
* https://www.facebook.com/Nero-Caff%C3%A8-1471950509746060/
* https://www.facebook.com/Nero-Caff%C3%A8-1636709259742574/

As I see - this is a ["Figurative"  trademark](https://euipo.europa.eu/ohimportal/en/trade-mark-definition)
* https://euipo.europa.eu/eSearch/#details/trademarks/002133908

Probably we need to make a difference between "Word mark" vs . "Figurative mark"
* https://euipo.europa.eu/ohimportal/en/trade-marks-examples#Figurative_mark

The "Figurative mark" (names ) is not always a same brand.
* https://www.facebook.com/pg/Caff%C3%A8-Nero-161842344519308/about/?ref=page_internal

**Comment by bhousel** [comment]
Closing here - logos will make it easier for mappers to be really sure that they are adding the thing that they think they are adding.
