### ISSUE TITLE
Logos - also distinguishing "true" brands from similarly-named independent businesses

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2116]
https://euipo.europa.eu/ohimportal/en/trade-mark-definition

Different Trademarks exists -
* "Caffé Nero" -  **"Figurative"**:  https://euipo.europa.eu/eSearch/#details/trademarks/002133908
* "Deutsche Bank" - **"Word"** :  https://euipo.europa.eu/eSearch/#details/trademarks/009616988

So same name("Caffé Nero") + Different Logo  - probably legal , or at least exists.
* https://www.facebook.com/pg/Caff%C3%A8-Nero-161842344519308/about/?ref=page_internal

in ideal case - we can show the logos for the user :

![image](https://user-images.githubusercontent.com/2217320/47304615-66b4e580-d627-11e8-81b4-511680383838.png)

( related to "Caffé Nero"  -  https://github.com/osmlab/name-suggestion-index/issues/2108 )

**Comment by bhousel** [comment]
@ImreSamu can you say more about what the issue is?  It's not really clear to me.  We know there will always be other uses of the brand names.

I'd love to be able to show logos in the openstreetmap editor.. Once the entries have been linked to wikidata, we can fetch logos from there, if available.  All the logos would first need to be in wiki commons, or we could possibly fetch logos from their social media accounts.

It would be useful to try to link the wikidata ids to logos and see how successfully we can do that.

**Comment by matkoniecz** [comment]
> @ImreSamu can you say more about what the issue is? It's not really clear to me

Also for me, I have no idea what the trademark problem is supposed to be.

**Comment by ImreSamu** [comment]
> can you say more about what the issue is? It's not really clear to me

sorry,

My problem is the same: **preventing injecting a "false" `brand=` tags  to the database.**

* When    "brand type" == "Word Trademarks"   - probably this is not a problem.
* When    "brand type" == "Figurative Trademark" ( with a  logo ) - then it **can be** a problem, 
    * the  "name=*"   NOT ALWAYS   has the same  "brand=*"   ;     Only the logo protected.  ; So if the OSM contributor doesn't know the differences ( `name`!=`brand` ) -   then maybe choosing a name with "bad" brands. The English Wikipedia sometimes not useful if the local user is known only Hungarian language, he/she will accept the default similar values.   The average user will not detect the small differences.


### my real problem :)

I do have [skin in the game](https://en.wikipedia.org/wiki/Skin_in_the_game_(phrase)) 
- because I need to clean/validate the Hungarian POI data ;
If the "brand type" == ("Figurative Trademark" )  then it is very hard to verify - no thumb of rule. 
I need to individually check the website, facebook page - and compare the logos.

And the same name no guarantee - like this ["Caffé Nero"]( 
https://www.facebook.com/pg/Caff%C3%A8-Nero-161842344519308/about/?ref=page_internal) is not member the  ["Caffé Nero"](https://en.wikipedia.org/wiki/Caff%C3%A8_Nero)  Company ( different logo )


So My real problem,   How Can I validate "Figurative Trademark" brands?

**Comment by matkoniecz** [comment]
> When "brand type" == "Figurative Trademark" ( with a logo ) - then it can be a problem,    the "name=" NOT ALWAYS has the same "brand=" ; Only the logo protected.

Can you give examples of a "Figurative Trademark" brands? I am still unsure what is the problem.

**Comment by ImreSamu** [comment]
As I see - this help to understand:

_"**FIGURATIVE trademark protects the word (words) in the scope of graphic design.** The emphasis is put on the visual part of a trademark."_  http://www.trademarks-blog.eu/word-or-figurative-trademark/

> Can you give examples of a "Figurative Trademark" brands?

*  "Quick"   
     *  https://euipo.europa.eu/eSearch/#details/trademarks/000350918
*  "Pollo Campero"  : 
     *  https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Pollo%20Campero


| OSM preset                      | Brand         | Trademark type    | Wikidata | Wikipedia                  |  Trademark search in EU
| -------------------------       | ------------- | ----------------- | -------- | -------------------------  | ------------------------
|"amenity/fast_food/Potbelly"     | Potbelly      | Word + Figurative | Q7234777 | en:Potbelly Sandwich Works |  https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Potbelly
|"amenity/fast_food/Pollo Campero"| Pollo Campero | Figurative | Q942741  | en:Pollo Campero           |  https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Pollo%20Campero
|"amenity/fast_food/Qdoba"        | Qdoba         | Word              | Q1363885 | en:Qdoba                   |  https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Qdoba
|"amenity/fast_food/Quick"        | Quick         | [Figurative](https://euipo.europa.eu/eSearch/#details/trademarks/000350918)        | Q286494  | en:Quick (restaurant)      |  https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Quick
|"amenity/fast_food/Quiznos"      | Quiznos       | [Word](https://euipo.europa.eu/eSearch/#details/trademarks/007285109)  | Q1936229 | en:Quiznos  | https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Quiznos
 |"amenity/fast_food/Rally's"     | Rally's       | ??(Not protected in the EU?) | Q3419341 | en:Checkers and Rally's | https://euipo.europa.eu/eSearch/#basic/1+1+1+1/100+100+100+100/Rally's

**Comment by matkoniecz** [comment]
Why trademark type and its legal status is important? We are not tagging that information.

**Comment by matkoniecz** [comment]
And from what I see in table name and brand matches.

**Comment by ImreSamu** [comment]
sorry my draft english.

> Why trademark type and its legal status is important?

imho:
* IF  "FIGURATIVE trademark "**   -  THEN Logo/visual is important!  

in this case the "brand="  name is not unique!

## example  - amenity/cafe  + Nero

The brand: **"Caffé Nero"  - with  "FIGURATIVE trademark "**     - can be detected only with LOGO/Visual because "NERO" is a frequent name , and "Nero Caffé" with different Visual can be exist

Now : 

"amenity/cafe|Caffè Nero" Linked to -> https://en.wikipedia.org/wiki/Caff%C3%A8_Nero
![image](https://user-images.githubusercontent.com/2217320/47356820-6cf99f00-d6c5-11e8-94cf-212f28ad8dfe.png)

Vs.

see:  https://www.nero-caffe.hu/   ( Hungarian example )
![image](https://user-images.githubusercontent.com/2217320/47355863-d330f280-d6c2-11e8-9e24-a7721099fcf1.png)


## use case 

A NEW hungarian contributor  want to add "www.nero-caffe.hu" - POI  to the OSM
* And "no visual" information in the iD Editor
* No english knowledge ( speak only hungarian )
   * and [hungarian word order is flexible](https://en.wikipedia.org/wiki/Personal_name#Eastern_name_order)  "Nero Caffé" vs. "Caffé Nero" is same meanings.
   * No hungarian wikipedia page: https://en.wikipedia.org/wiki/Caff%C3%A8_Nero   
* He/She - has not any information - that the other   "Caffé Nero" ( chain)  exists - and this is not a member of ( `brand:wikidata=Q675808` )

Start typing "Nero"
![image](https://user-images.githubusercontent.com/2217320/47359011-d381bb80-d6cb-11e8-9b43-877f8e0602c9.png)



And select  ...

```json
  "amenity/cafe|Caffè Nero": {
    "count": 229,
    "match": [
      "amenity/cafe|Cafe Nero",
      "amenity/cafe|Caffe Nero"
    ],
    "tags": {
      "amenity": "cafe",
      "brand": "Caffè Nero",
      "brand:wikidata": "Q675808",
      "brand:wikipedia": "en:Caffè Nero",
      "name": "Caffè Nero"
    }
  },
```

And injecting bad tags
* "brand": "Caffè Nero",
* "brand:wikidata": "Q675808",
* "brand:wikipedia": "en:Caffè Nero",

imho:  this is ~ [Unintended consequences]( https://en.wikipedia.org/wiki/Unintended_consequences)


## extra comments

"Caffé Nero"  -has a "Green Caffé Nero"  brand -> https://greencaffenero.pl/en

amenity=cafe   ->  `Nice classes` = 43 _"Services for providing food and drink; restaurant and catering services; self-service restaurant services; snack bar services; café services; take-away services; coffee bar and coffee house services; carry out restaurant and take out restaurant services; coffee supply services for offices; office coffee supply services; contract food and drink services; food preparation; preparation of carry out foods and beverages; information, advisory and consultancy services in relation to all the aforesaid."_

**Comment by ImreSamu** [comment]
>It sounds like you are worried that users will pick "Caffé Nero" (Q675808)
> from the list in iD when they >really mean "Caffé Nero"
> (a random place that just happens to be called that).
>Is that a fair restatement of the issue?

yes, this is correct.

**Comment by bhousel** [comment]
> > It sounds like you are worried that users will pick "Caffé Nero" (Q675808)
> > from the list in iD when they >really mean "Caffé Nero"
> > (a random place that just happens to be called that).
> > Is that a fair restatement of the issue?
> 
> yes, this is correct.

Great!  Do you agree that the solution to this issue is dependent on downstream projects like iD giving the user enough clues in the UI to make this decision?

I'd really like to show logos if this is possible.  Or at least a UI hint that there is some wikidata and maybe the user can hover to view some of the information about the brand?  Again, showing logos for every brand is a great stretch goal, but depends on completeness in Wikidata (and maybe this is a thing where OSMers can help).

@ImreSamu - are you ok if I move this issue to the iD repo?   It seems more like something to address there.

**Comment by ImreSamu** [comment]
@bhousel 

>I'd really like to show logos if this is possible. 
>Or at least a UI hint that there is some wikidata 
>and maybe the user can hover to view some of the information about the brand? 

imho:  Picture/Logo  is important  for choosing the correct brand. 

(imho) as a long term vision:
* maybe we can extend this repo with image links
* and/or we can import links via Wikidata properties.

```
    "tags": {
      "amenity": "fast_food",
      "brand": "McDonald's",
      "brand:wikidata": "Q38076",
      "brand:wikipedia": "en:McDonald's",
      "cuisine": "burger",
      "name": "McDonald's"
    }
    "icon": ""
    "image:logos": [
      "https://commons.wikimedia.org/wiki/File:McDonald%E2%80%99s_gr%C3%BCn_logo.svg",
      "https://commons.wikimedia.org/wiki/File:McDonald%27s_Golden_Arches.svg",
      "https://commons.wikimedia.org/wiki/File:McDonald%27s_logo.svg"
    ], 
    "image:outside": {
      "https://commons.wikimedia.org/wiki/File:McDonald%27s_in_Exeter.jpg",
      "https://commons.wikimedia.org/wiki/File:McDonald%27s_Liberdade_in_Sao_Paulo_002.JPG",
      "https://commons.wikimedia.org/wiki/File:McDonalds_HongKong.jpg",
      "https://commons.wikimedia.org/wiki/File:McDonald%27s_in_Brno_(Masaryk_Street).JPG"
    },
    "image:inside": [
      "https://commons.wikimedia.org/wiki/File:2011-10-25_McDonald%27s_in_Raleigh.jpg"
    ]
```    

Maybe we can reuse wikimedia commons  images: https://commons.wikimedia.org/wiki/McDonald%27s
or import image/logo links via Wikidata SPARQL 
* example: fast food restaurant chains ( image, logo ) :  http://tinyurl.com/y8mxc4fu

> are you ok if I move this issue to the iD repo? It seems more like something to address there.

I understand, that probably I make too much noise with my fears, sorry.
But if possible - please keep this issue open.

I prefer defensive solution ( and solving problems at the roots )

* IF has VISUAL(Wikidata.Logo?)  
    * THEN   import   Wikidata.Logo Links.
    * ELSE    not export `brand=` information - to the release file - because no VISUAL clue.
 
On the other hand 
* other projects using this database.( http://vespucci.io/tutorials/name_suggestions/ )
* and easier for me validate the metadata here.  ( Generate an OSM Brand Catalog - with logo/image )

**Comment by matkoniecz** [comment]
> ELSE not export brand= information - to the release file - because no VISUAL clue.

I would leave such filtering for users of the data.

> move this issue to the iD repo? It seems more like something to address there.

Cafe
Cafe - Nero Cafe brand

should make problems less likely

> and/or we can import links via Wikidata properties.

Note that there is an interesting project that allows quick adding images to Wikidata entries, would be useful in adding missing properties before an import to this project - here is my query for objects around Kraków but it should be possible to create one for brands within our index https://tools.wmflabs.org/fist/wdfist/?depth=3&language=en&project=wikipedia&sparql=SELECT%20?item%20WHERE%20{%20SERVICE%20wikibase:around%20{%20?item%20wdt:P625%20?itemlocation%20.%20bd:serviceParam%20wikibase:center%20%22Point(20%2050)%22^^geo:wktLiteral%20.%20bd:serviceParam%20wikibase:radius%20%2215%22%20.%20}}&no_images_only=1&prefilled=1), [Masuria](https://tools.wmflabs.org/fist/wdfist/?depth=3&language=en&project=wikipedia&sparql=SELECT%20?item%20WHERE%20{%20SERVICE%20wikibase:around%20{%20?item%20wdt:P625%20?itemlocation%20.%20bd:serviceParam%20wikibase:center%20%22Point(21.7666%2054.0430)%22^^geo:wktLiteral%20.%20bd:serviceParam%20wikibase:radius%20%2215%22%20.%20}}&no_images_only=1&prefilled=1

**Comment by bhousel** [comment]
> * and/or we can import links via Wikidata properties.

^ This is what I was thinking.  Once the wikidata links are established, we can get all kinds of stuff through SPARQL queries.  We don't need to mirror the urls or the logos over to this project.

> example: fast food restaurant chains ( image, logo ) : http://tinyurl.com/y8mxc4fu

Nice!  yeah this is a good start.  I clicked through several of these, and I have to admit, Wikidata has pretty poor logo coverage.  Another important detail is - for displaying a list of business brand presets in iD, we really want a smallish, squarish, thumbnail image.  Many of the wiki commons "logos" are photos of the storefronts or of the signage, or the dimensions are all wrong.

 _My gut_ says that we would be better to do: 
Wikidata SPARQL -> Twitter (or other) ID -> profile photo URL
(This is maybe a problem to be solved on the iD side)

> I understand, that probably I make too much noise with my fears, sorry.
> But if possible - please keep this issue open.

No problem, I'm happy to keep it open here..  This is a good discussion 👍

**Comment by ImreSamu** [comment]
@matkoniecz 
>Cafe
>Cafe - Nero Cafe brand
>should make problems less likely

We need carefully designed UI. 
 ["brand"](https://en.wikipedia.org/wiki/Brand) - has a multiple meaning and context, and an average people don't know the differences.

searching http://www.wipo.int/branddb/en I have found 8 different Caffé Nero ( registered ) brand/logo
![image](https://user-images.githubusercontent.com/2217320/47498088-7b2df380-d85c-11e8-90eb-1bbd084bebbd.png)


for an average  hungarian people this is a brand ( lokal, unregistered)  :
![image](https://user-images.githubusercontent.com/2217320/47500001-d7474680-d861-11e8-9de8-bcbbd74dabb1.png)
 https://www.nero-caffe.hu/  
*  same domain name  - and the name inside ✔️
*  has a logo - and a name inside  ✔️
*  legal company ✔️
*  everybody knows  -  in the city  ( local knowledge)  ✔️

But not a "global brand" : https://en.wikipedia.org/wiki/Brand#Global_brand_variables

**Comment by bhousel** [comment]
Logos were added in #2422  🎉
