### ISSUE TITLE
Add Swedish video/candy chain Hemmakväll

### ISSUE THREAD

**Issue by Vesihiisi** [osmlab/name-suggestion-index#2119]
wiki: https://sv.wikipedia.org/wiki/Hemmakv%C3%A4ll

Overpass: https://overpass-turbo.eu/s/D22

I guess technically it's `shop=video` but the current tagging on OSM is all over the place…

**Comment by bhousel** [comment]
It's ok for this index to contain both

"shop/confectionery|Hemmakväll"    (for the candy-only stores)
and
"shop/video|Hemmakväll"    (for the video-only stores)

And users in the OpenStreetMap editors will just have to choose one.  From their website it looks like the video business is on its way out.

**Comment by good-praxis** [comment]
# How to resolve this issue:
Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for info, and feel free to ask questions on this issue!

Open a PR that adds and entry for this brand by copying another entry.
Update the `"brand:wikipedia"` and `"brand:wikidata"` values accordingly
Be sure you add the `"nocount"` key to the index, and set it to `true`!

**Comment by amey-kudari** [comment]
how do i solve the issue? i still didnt understand it

**Comment by amey-kudari** [comment]
what is brand:wikidata?

**Comment by bhousel** [comment]
@amey-kudari :  https://wiki.openstreetmap.org/wiki/Key:brand:wikidata

Also see [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) for more info.

**Comment by amey-kudari** [comment]
And what about count? what do I put for "count"= ?

**Comment by bhousel** [comment]
> And what about count? what do I put for "count"= ?

You should add `"nocount": true` because this entry does not have a count yet.

**Comment by amey-kudari** [comment]
Sorry, i didnt read the .md file completely, im so sorry, And yeah thanks a lot, i created a pull request.
And right now i only know javascript, should i continue contributing or learn node/anything else before i continue?
And yeah, Thank you so much :)

**Comment by bhousel** [comment]
done in #2293, thanks @amey-kudari 👍
