### ISSUE TITLE
Add Swedish shoe chain Din Sko

### ISSUE THREAD

**Issue by Vesihiisi** [osmlab/name-suggestion-index#2120]
Wiki: https://sv.wikipedia.org/wiki/Din_sko

**Comment by good-praxis** [comment]
# How to resolve this issue:
Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for info, and feel free to ask questions on this issue!

Open a PR that adds and entry for this brand by copying another entry.
Update the `"brand:wikipedia"` and `"brand:wikidata"` values accordingly
Be sure you add the `"nocount"` key to the index, and set it to `true`!
