### ISSUE TITLE
SuperAmerica is becoming Speedway

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#2135]
So the brand is discontinued:

http://m.startribune.com/superamerica-is-becoming-speedway-end-of-a-name-that-originated-at-a-st-paul-gas-station/497195131/

(It also needs to be merged with "Super America")

Should the index continue to suggest SuperAmerica until there aren't any stores that physically have the branding?

I'm inclined to no, so in that case the issue is whether to add them as matches for Speedway or to add a filter for them.

**Comment by bhousel** [comment]
> Should the index continue to suggest SuperAmerica until there aren't any stores that physically have the branding?
> 
> I'm inclined to no, so in that case the issue is whether to add them as matches for Speedway or to add a filter for them.

Ah yeah we've discarded deprecated brands in the past - see #221 / f3c53eb
(leaving them in would only cause mappers to add more of them)

I'm not sure whether discarding completely or adding them as matches to the new branding is better.

I have this dream that we will eventually be able to use this index to produce a task list, e.g. for Maproulette.  If we want to try this..
* _discarding_ might generate a task for mappers "Should the generic name SuperAmerica be removed Y/N?"  
* _matching_ might generate a task for mappers "Should the less preferred name SuperAmerica be upgraded to Speedway Y/N?"

**Comment by bhousel** [comment]
done in #2145
