### ISSUE TITLE
Research needed for: amenity/bank|Columbia Bank

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2167]
#### :thinking: We need help deciding what to do with "amenity/bank|Columbia Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Columbia Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Columbia Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Columbia Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bhousel** [comment]
I found this one while removing the potential duplicate with "shop/clothes|Columbia".

There are 2 separate Columbia Banks, one in Washington and one in New Jersey:

WA: https://www.columbiabank.com/
NJ:  https://www.columbiabankonline.com/

Overpass:  https://overpass-turbo.eu/s/Da6
<img width="300" alt="screenshot 2018-10-27 18 18 21" src="https://user-images.githubusercontent.com/38784/47609838-be32c700-da14-11e8-85ce-d62b2ebf985c.png">


I don't think either of them have wikidata.

**Comment by bhousel** [comment]
> I think it's fair if we remove these tags.

Thanks @good-praxis - I agree....

**Comment by ENT8R** [comment]
I created two new Wikidata entries ([`Q62084089`](https://www.wikidata.org/wiki/Q62084089) for the bank operating in the northwestern states and [`Q62084096`](https://www.wikidata.org/wiki/Q62084096) for the bank operating mainly in New Jersey) with all the information I could gather for those two banks and added them as two separate entries with https://github.com/osmlab/name-suggestion-index/commit/c7f231fe2b34c75fbe58f71604acb032a283b150

**Comment by bhousel** [comment]
Thank you @ENT8R 👍
