### ISSUE TITLE
Carpet Right or Carpetright

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2194]
```
  "shop/carpet|Carpet Right": {
    "count": 120,
    "tags": {
      "brand": "Carpet Right",
      "name": "Carpet Right",
      "shop": "carpet"
    }
  },
  "shop/carpet|Carpetright": {
    "count": 68,
    "tags": {
      "brand": "Carpetright",
      "name": "Carpetright",
      "shop": "carpet"
    }
  },
```

Wikipedia has https://en.wikipedia.org/wiki/Carpetright but their logo, OSM usage and my aversion to mutilating language pushes me toward using `Carpet Right` as canonical.

But I am not 100% sure is it a good solution so I will open this issue.

**Comment by maxerickson** [comment]
https://www.carpetright.co.uk/ gleefully mutilates language, so I would probably go with Carpetright.

It looks like newer storefronts also have the words more run together:

https://www.google.com/search?tbm=isch&q=carpetright

**Comment by bhousel** [comment]
Yep, looks like the stores do have the name running together:
https://www.glassdoor.com/Photos/Carpetright-Office-Photos-IMG924841.htm

My vote is for keeping "Carpetright" and adding "Carpet Right" as a match.

**Comment by matkoniecz** [comment]
I guess that it goes on "We map reality as it is, not as we want it to be" pile.
