### ISSUE TITLE
Phone House or The Phone House

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2195]
The biggest WTF branding in our index is probably  "Phone House" vs "The Phone House".  It's actually one company that just can't decide what to call their stores. 

The index currently has both versions.  But given how confusing this is likely to be to users, maybe we should pick a winner?

https://www.google.com/search?biw=1416&bih=758&tbm=isch&sa=1&ei=FofdW_ehJMHl_Qa3haHQDw&q=phone+house+store&oq=phone+house+store&gs_l=img.3..0i24.10740.11125..11607...0.0..0.62.227.4......1....1..gws-wiz-img.nwTqG68moDI

**Comment by matkoniecz** [comment]
It gets better, restricting photos to last month or last year is not changing anything.

If it is the same group of shops, maybe just selects whatever is more popular in OSM database at this moment?

**Comment by todrobbins** [comment]
Their [global website](http://www.phonehouse.com/) uses "Phone House" and links to multiple national websites that also use "Phone House".

See also: http://www.dominion-global.com/en/-/dominion-compra-phone-house

**Comment by bhousel** [comment]
Thanks for checking @todrobbins!  I think we can just call it "Phone House", if that's how their website is branded.
