### ISSUE TITLE
Remove "Lowes" from index, "Lowe's" is the proper name

### ISSUE THREAD

**Issue by sanecito** [osmlab/name-suggestion-index#2197]
Per title remove "Lowes" as "Lowe's" is what is seen across all branding and buildings. Stumbled across this issue when searching in ID and came across two entries in the index:
![image](https://user-images.githubusercontent.com/3056597/47980495-2755b280-e085-11e8-9b46-99cdf5fa2cbc.png)

**Comment by maxerickson** [comment]
This is already done in the index, the latest version just hasn't been pulled into iD.
