### ISSUE TITLE
add automatically generated country restrictions

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2201]
I thought a bit what may be improved as I was using name-suggestion-index in Vespucci.

The most noticeable problem is that most of names proposed as I was typing are never, ever appearing in my country and should not be proposed.

For example proposing `shop/kiosk|Kolporter` in Indonesia is pointless. Similarly proposing `shop/kiosk|Pressbyrån` in Poland.

We are already using region restrictions for the most obvious cases but I think that it would be highly useful to automatically generate such restrictions for all entries.

My ideas is that

- for each entry without `countryCodes` field:
  - check OSM data and list countries where this object is appearing (just one time is enough)
  - list all of them in a new field, say `automatedCountryCodes`
  - on release for entries with `automatedCountryCodes` without `countryCodes`:
   - promote `automatedCountryCodes` to `countryCodes`

- for each entry with `countryCodes` field:
  - check OSM data and list countries where this object is appearing
  - list cases where this object is appearing (say, more than five times)
  - complain about overly restrictive filters 

My main question is what are preferences for code that would generate such list. Is it necessary that it is written in a JavaScript?

**Comment by stefanb** [comment]
> check OSM data and list countries where this object is appearing (just one time is enough)

l think this should be performed periodically, eg on a yearly basis or few times a year.
Reasoning is that global chains are often expanding into new countries and sometimes also pull out of some.

**Comment by matkoniecz** [comment]
Yes, it should be regenerated from time to time as brands may appear/disappear/reappear in a given territory.

**Comment by bhousel** [comment]
I was thinking about this.. It would be hard to do because I strip out the geometry before processing the list.  So we'd need to process a full planet file with geometry and then reverse geocode which countries the names are used.  It would be slow!

A faster alternative might be to run thru each entry and run queries against @nyurik's wikibase or elasticsearch?, which has the full planet with geometry.

**Comment by matkoniecz** [comment]
What you think about language of this tool? Should it be also built with js node or is it unimportant?

**Comment by bhousel** [comment]
> What you think about language of this tool? Should it be also built with js node or is it unimportant?

If it's in this repo, please use Node/JavaScript.

**Comment by nyurik** [comment]
I asked my Elasticsearch colleagues if it would be possible to do a on-the-fly searching based on the user typing some string, e.g. if it would be possible to quickly suggest some results based on both what the user typed as well as the user's location - and sort the result on how likely it fits with the object's locale.  Thanks to @polyfractal for explaining how this might be possible (text adapted from Zachary's reply). Posting it here for the future reference.

- use a `term` or `completion` suggester to drive the autocomplete
- then a `term` query + `geo_distance` filter to find eligible documents (where the geo distance puts a max bounding box on the area to improve performance, so you aren't searching the whole world). _(bounding box might be unnecessary because we don't actually have that many data points)_
- finally, the query is sorted by `_geo_distance` based on the user's position (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#geo-sorting)
if you need scoring to be some combination of proximity and text scoring, then instead of sorting by `_geo_distance` you can use a `function_score` to incorporate the geo into the rest of the query scoring, or something like a `rescore` based on distance, etc

Another idea is to have a boolean clause for "matching brands" (which have a `match`/`term`/whatever query for the autocompleted brand name) boosted to `n`, and a second boolean clause for "everything else" with a lower boost. Basically boils down to different combinations of regular queries + geo distance sorting, or function_score to incorporate geo score into regular score.

**Comment by bhousel** [comment]
Going to close here as I think doing this _automatically_ would be a lot more work, and we are doing a pretty good job just manually curating this index with the volunteers that we have.

**Comment by matkoniecz** [comment]
> doing this automatically would be a lot more work

I think that it would not be so hard. I hacked together small script - output for banks is at https://gist.github.com/matkoniecz/3348f4e3f7c7eea108c5336f8d33a79b

It found large number of entries that seem to be present in just single country.

**Comment by Adamant36** [comment]
Do you have a link to the script for it? I was just doing research on how to mine Wikipedia for parent company information. It would be cool if I could see how you did it for country codes.

**Comment by matkoniecz** [comment]
Not using Wikipedia, just OSM data (for copyright and practical reasons). I am suing external geocoder with unchecked legal status, I may need to switch to ODBL compatible one.

Note that this us useful as pseudocode as it uses some of my unreleased libraries, but code is really simple.

Loaded `name-suggestions.json` is one after #2403

```
require 'json'
require_relative '../watchlist_infrastructure'
require 'overhelper.rb'
require_relative '../require.rb'
require "offline_geocoder" #https://github.com/sildur/offline_geocoder

$geocoder = OfflineGeocoder.new

def process_entry(key, value, name, entry_data)
    type_segment = CartoCSSHelper::OverpassQueryGenerator.turn_tag_into_overpass_filter([key, value]).strip
    name_segment = CartoCSSHelper::OverpassQueryGenerator.turn_tag_into_overpass_filter(['name', name]).strip
    query = "[out:json][timeout:2500]; (nwr#{type_segment}#{name_segment};);out body;>;out skel qt;"
    json_string = get_data_from_overpass(query, "query")
    obj = JSON.parse(json_string)
    elements = obj["elements"]
    latitudes = []
    longitudes = []
    countries = []
    country_codes = []
    elements.each do |entry|
      if entry["type"] == "node"
        latitudes << entry["lat"]
        longitudes << entry["lon"]
        countries << $geocoder.search(entry["lat"], entry["lon"])[:country]
        country_codes << $geocoder.search(entry["lat"], entry["lon"])[:cc].downcase
      end
    end
    if latitudes.length == 0
      puts "#{key}=#{value} #{name}"
      puts entry_data
    end
    span_lat = (latitudes.max - latitudes.min).abs
    span_lon = (longitudes.max - longitudes.min).abs
    if entry_data.include?("countryCodes")
      return
      if Set.new(entry_data["countryCodes"].to_a) == Set.new(country_codes.uniq)
        return
      end
      puts entry_data
      puts "'#{key}'='#{value}' and name='#{name}' global"
      puts entry_data["countryCodes"]
      puts "======="
      puts country_codes.uniq
      puts
    elsif countries.uniq.length == 1 #[span_lon, span_lat].max < 10
      puts entry_data
      puts "'#{key}'='#{value}' and name='#{name}' global"
      puts countries.uniq
      puts country_codes.uniq
      puts
    end
end

CartoCSSHelper::Configuration.set_path_to_folder_for_cache('/media/mateusz/5bfa9dfc-ed86-4d19-ac36-78df1060707c/OSM-cache')
name_suggestion_data = JSON.parse(File.read("name-suggestions.json"))
name_suggestion_data.keys.each do |key|
  name_suggestion_data[key].keys.each do |value|
    name_suggestion_data[key][value].keys.each do |name|
      entry_data = name_suggestion_data[key][value][name]
      osm_name = entry_data["tags"]["name"]
      process_entry(key, value, osm_name, entry_data)
    end
  end
end
```

**Comment by Adamant36** [comment]
Hhhmm, interesting. Thanks for providing it. It doesn't seem that complicated. It would cool if the country codes could be automatically inserted into the index after they are retrieved. Although its probably better if they are reviewed first.

**Comment by matkoniecz** [comment]
I made some changes (my program detected that Iran was mistaken for Ireland etc) and opened test issues - I may open more if someone is also interested in adding this missing data.

**Comment by Adamant36** [comment]
Sweet. I was wondering if the issues were from it. I'll add the country codes for the banks after my current PR is merged. I was actually going to ask if you could run it for the bank file. Since I'm currently going through it.

**Comment by matkoniecz** [comment]
OK, I will also open three with longer list if you are going through it :)

**Comment by Adamant36** [comment]
Awesome. If you want to go over my PR and merge it for me also I'd appreciate it.

**Comment by bhousel** [comment]
This is great @matkoniecz  🎉 
Whatever your script finds, just go ahead and change in the index.  I dont really want issues opened for each thing.

**Comment by bripmccann** [comment]
Hi, related thought: Could it be useful to narrow things down by writing system (Latin, Cyrillic, Hanzi, Kana, etc.)?

**Comment by bhousel** [comment]
> Hi, related thought: Could it be useful to narrow things down by writing system (Latin, Cyrillic, Hanzi, Kana, etc.)?

Yes, the build script does this already:

https://github.com/osmlab/name-suggestion-index/blob/8611e0ed8154ca34950c73571c69f516e62d07d8/build_brands.js#L161-L201

**Comment by bripmccann** [comment]
@bhousel Ah, I didn't realize. What about cases where you can't infer the country from a given writing system?

Really I was thinking of tags to categorize all those "Research needed" issues. Someone from, say, Russia could check out all the issues for brand names written in Cyrillic, and people who can't read Cyrillic could choose to exclude them.

**Comment by bhousel** [comment]
> @bhousel Ah, I didn't realize. What about cases where you can't infer the country from a given writing system?
> 
> Really I was thinking of tags to categorize all those "Research needed" issues. Someone from, say, Russia could check out all the issues for brand names written in Cyrillic, and people who can't read Cyrillic could choose to exclude them.

Mostly we rely on volunteers to go through each one.  I know it does take a while 😅
