### ISSUE TITLE
Magazin Mixt looks like a generic name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2202]
Based on https://www.facebook.com/Magazin-Mixt-1001781153217131/ https://commons.wikimedia.org/wiki/File:Magazin_Mixt_-_panoramio.jpg and lack of any web presence of this supposed brand.

**Comment by bhousel** [comment]
As far as I can tell, all the "Magazin" entries in the index are generic, so I'll remove them..
