### ISSUE TITLE
shop/bakery|Müller may be a generic name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2203]
Müller is a popular surname in Germany, and I found so far no indicators that it is a single company

**Comment by matkoniecz** [comment]
@ENT8R And you are from Germany, right?

**Comment by ENT8R** [comment]
Yes, I am 😄 
Do you want to add it to the list of generic names or should I do that?

**Comment by matkoniecz** [comment]
Feel free to do that! I may do that, but probably during 2019.
