### ISSUE TITLE
Research needed for: amenity/bank|Bank Zachodni WBK

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#221]
#### :thinking: We need help deciding what to do with "amenity/bank|Bank Zachodni WBK"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Bank Zachodni WBK` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Bank Zachodni WBK`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Bank Zachodni WBK`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
This brand is deprecated. All existing OSM data is outdated or will become outdated soon.

Brand is being replaced by Santander Bank Polska.

See https://en.wikipedia.org/w/index.php?title=Bank_Zachodni_WBK for details.

I would put it on hold and wait until OSM data is updated or discard it in processing.

**Comment by bhousel** [comment]
> or discard it in processing.

Yeah sounds like something to discard.. If we include it, users will just create more of them. 😆
