### ISSUE TITLE
Fix osmium dependency

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2211]
It looks like the build is currently failing on the most recent version of Node because Travis can't install osmium.  

We don't actually use osmium to build the project.  It's only used for the "once in a while" processing of the OSM planet file.  So it would be great to either fix osmium or skip its installation on Travis.

h/t @sinclarius

**Comment by maxerickson** [comment]
Is Mapbox likely to publish binaries for more recent versions of node?

node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.5.7/node-v67-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for osmium@0.5.7 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp)

If not the options seem to be to build osmium, abuse optionalDependencies a little bit in package.json, or remove it entirely.

**Comment by bhousel** [comment]
> If not the options seem to be to build osmium, abuse optionalDependencies a little bit in package.json, or remove it entirely.

Ah yeah [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) sounds exactly like what where we should put it.  👍

**Comment by bhousel** [comment]
update per fa6f62b
Because we are still having trouble with installing iD downstream because of this dependency that is not really used, I'm just dropping it from the dependencies list and updated the README to suggest a global install instead.
