### ISSUE TITLE
Create Christmas presets

### ISSUE THREAD

**Issue by HubMiner** [osmlab/name-suggestion-index#2240]
Please create presets for Christmas related features.
Documentation seems to be lumped on one page: https://wiki.openstreetmap.org/wiki/Key:xmas:feature

Sample visualization: https://be2art.de/xmasmap/?lat=50.766&lon=6.994&zoom=10

Based on that, I propose initial support for following features.  Below is aggregation from documentation and actual examples.

1. Market
xmas:feature=market
xmas:name=* (name of the Christmas market)
xmas:day_date=* (period for the event)
xmas:opening_hours=*
xmas:url=* (website for the market)
xmas:note=* (note - for example, holidays)
xmas:location=* (brief description of the place)
check_date=yyyy-mm-dd (last checked)
operator=*

2. Pyramid
    "xmas:day_date": "2018-11-26/2018-12-23",
    "xmas:feature": "pyramid",
    "xmas:lastcheck": "2018-09-24",
    "xmas:pyramid:height": "12.5 m",
    "xmas:pyramid:level": "5",
    "xmas:url": "https://www.kieler-weihnachtsmaerkte.de/standorte/asmus-bremer-platz.html"
    "xmas:location": "Place Saint-Louis",
    "xmas:name": "Pyramide de Noël",
    "xmas:operator": "Ville de Metz",
    "description": "Mainzer Weihnachtspyramide",
    "opening_hours": "24/7",
    "tourism": "attraction",
    check_date=yyyy-mm-dd (last checked)

3. Tree Shop
xmas:feature=shop
xmas:feature:shop=christmas_tree
xmas:website: http://www.weihnachtsbaumhof-tacke.de/
xmas:feature: shop
xmas:feature:shop: christmas_tree
xmas:name: Weihnachtsbaumhof Tacke
check_date=yyyy-mm-dd (last checked)

4. xmas:feature=event
    "xmas:day_date": "03.12.2016-23.12.2016",
    "xmas:feature": "event",
    "xmas:name": "Forst Bliestorf",
    "xmas:note": "2./3./4. Advent großes Rahmenprogramm",
    "xmas:opening_hours": "Mo-Su 09:00-16:00",
    "xmas:url": "http://www.forstbliestorf.de/"
    "xmas:fee": "1,50€ - 13,50€",

5. xmas:feature=tree
xmas:feature: tree
xmas:location: hinter dem Rathaus
xmas:name: Printe
xmas:open_date: 20.11.2015-23.12.2015
xmas:opening_hours: Mo-Su,PH 11:00-21:00
xmas:tree:height: 3-4 m (grob geschätzt)
xmas:url: http://www.bv-gbh.de/index.php/8-buergerverein/41-treffen-am-kriegerdenkmal

**Comment by bhousel** [comment]
Oh sorry to close this but generic presets is really not what this project is for.  Except for Christmas Tree Shop, which is a brand. 

Sorry!

**Comment by HubMiner** [comment]
NP, is there anything place/project where I could submit this to?

**Comment by bhousel** [comment]
> NP, is there anything place/project where I could submit this to?

It sounds like the sort of thing some people might create a [JOSM preset file](https://josm.openstreetmap.de/wiki/Presets) for.
