### ISSUE TITLE
Template "Harley-Davidson" motorcycle shop in ID editor

### ISSUE THREAD

**Issue by coffeepotprotocol** [osmlab/name-suggestion-index#2249]
Hi all,
there's a typo in the brand= value (missing hyphen), compare with the wikipedia and wikidata value.
See https://i.postimg.cc/zGXFz8gR/harley2.png

Here's a wiki page about the brand
https://wiki.openstreetmap.org/wiki/Tag:brand%3DHarley-Davidson
Will add a hint to use the template when completed.
(Currently the Overpass link in the "see also" section won't find all dealers as of the missing hyphen)

**Comment by bhousel** [comment]
Thanks @coffeepotprotocol , I just made the change.
