### ISSUE TITLE
Warnings for cuisine, vending

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2257]
Should the build script issue these warnings?
* `amenity=vending_machine` without `vending=*` tag
* `amenity=restaurant` without `cuisine=*` tag
* `amenity=fast_food` without `cuisine=*` tag

others?

**Comment by matthijsmelissen** [comment]
> Should the build script issue these warnings?

I think these are all sensible warnings.

**Comment by bhousel** [comment]
> @bhousel, can you add a warning for `shop=clothes` without `clothes=*`?

Is there a tag for if the shop just sells all kinds of clothes, and doesn't fit neatly into [any of the values listed here](https://wiki.openstreetmap.org/wiki/Key:clothes) ?

**Comment by Adamant36** [comment]
Hhhmmm, good question. I guess it would just be not adding the `clothes=*` tag in the first place? There's 475 uses of clothes=yes, but that seems wrong. Maybe we could create one, like clothes=general or something.

**Comment by Adamant36** [comment]
That works to. I wasn't sure if it was a requirement for the check to have a general key or something for whatever its checking.
