### ISSUE TITLE
Społem - shop=supermarket, shop=convenience, or both?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2269]
I opened thread asking local community at https://forum.openstreetmap.org/viewtopic.php?pid=735742#p735742

This issue is created to avoid forgetting about it.

next one after #1991

**Comment by bhousel** [comment]
Looks like from the forum that it can be both, and the brand operates both larger supermarkets and smaller convenience stores,  so I've added it both ways to the index.
