### ISSUE TITLE
Nando's cuisine, should it be "chicken" or "portuguese"?

### ISSUE THREAD

**Issue by SilentSpike** [osmlab/name-suggestion-index#2272]
Here's the current tagging in the index

https://github.com/osmlab/name-suggestion-index/blob/05c4bdeeafe084518f416e626f4d45d9603fa25f/config/canonical.json#L14986

It's been a while since I've eaten here, but I think chicken is the whole menu. From a brief search it sounds like the dishes are just inspired by Portuguese cuisine, not the real deal. Perhaps that's enough to warrant the tag though.

**Comment by bhousel** [comment]
It can be both!.. I set it to 
```
 "cuisine": "chicken;portuguese"
```
