### ISSUE TITLE
countryCodes lost in distribution

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2274]
Compare ABANCA (the first entry) in https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/dist/name-suggestions.json (dist) and https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/config/canonical.json (config)

countryCodes value is lost despite that it would be useful to, for example, limit useless name suggestions

Related to #2201 (without fixing this benefit of #2201 would be lost)

**Comment by bhousel** [comment]
Yes, we don't have the ability to limit the presets by `countryCode` in iD yet and I wanted to keep the `name-suggestions.json` format backward compatible for now.  (I don't think anyone else is using these files anyway). 


It probably makes more sense for iD to directly consume `canonical.json` now and just deprecate `name-suggestions.json`.

**Comment by simonpoole** [comment]
@bhousel Vespucci has been using the json format since day one essentially, afaik the change wouldn't break anything. Wrt cannonical.json can you give us an idea how that stacks up against the distributed file?

**Comment by bhousel** [comment]
> @bhousel Vespucci has been using the json format since day one essentially, afaik the change wouldn't break anything. Wrt cannonical.json can you give us an idea how that stacks up against the distributed file?

It wouldn't break anything to add `countryCodes` to the distributed json file, but if we add those and also the alternate `match` names (which some people suggested using as preset search terms) then we basically just have `canonical.json`.  (I'm happy to keep `name-suggestions.*` around indefinitely)

**Comment by matkoniecz** [comment]
> Wrt cannonical.json can you give us an idea how that stacks up against the distributed file?

Main differences is that entries umatched with wikidata/wikipedia (and therefore possibly false) are dropped. Also `countryCodes`, `match`, `nomatch` properties are dropped.

> It wouldn't break anything to add countryCodes to the distributed json file, but if we add those and also the alternate match names (which some people suggested using as preset search terms) then we basically just have canonical.json

Dropping unmatched entries would be remaining difference.

**Comment by simonpoole** [comment]
What confuses me is that it seems that cannonical.json has 3699 entries, but dist/name-suggestions.json only 2841. Shouldn't things be the other way around?

**Comment by bhousel** [comment]
> What confuses me is that it seems that cannonical.json has 3699 entries, but dist/name-suggestions.json only 2841. Shouldn't things be the other way around?

Only entries matched to a `brand:wikidata` tag get put in `dist/name_suggestions.json` and we’re only about 75% of the way done with this.
