### ISSUE TITLE
French Vival store: Supermarket or Convencience Store?

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#2313]
It would be great if someone in France could chime in on Vival. We have it in the file as both a supermarket and a convenience store. Which one should it be tagged as?

**Comment by Adamant36** [comment]
According to Wikipedia its "a brand of local grocery shops run by Groupe Casino. Vival can also sometimes be found at petrol stations." Which might be why its categorized as both a supermarket for the grocery stores and a convenience store for the ones in petrol stations. Looking at images on Google they mostly look like supermarkets, but I don't want to go just off of that. 

Id say look at usage for the ones tagged as convenience stores to see if they are next to or within petrol stations. Then do the same for the supermarkets to see if they aren't (the ones mapped next to petrol stations are the more important ones to research in my opinion). If it turns they are both though, it might be worth keeping them as separate entries.

**Comment by matkoniecz** [comment]
> Which one should it be tagged as?

Are there cases where it is supermarket and where it is a convenience shop?

> A supermarket is a large store for groceries and other goods. It's a full service grocery store that often sells a variety of non-food products as well. Almost always part of a chain, e.g. Tesco, Safeway. Stores that do not provide full service grocery departments are generally not considered supermarkets for historical reasons. 

> shop=convenience - Typically much smaller than a supermarket, and typically carries a more limited selection of food items. One suggestion for distinguishing between a supermarket and a convenience shop, is that a supermarket is large enough to use trolleys.

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dsupermarket


> A convenience store. A small local shop carrying a variety of everyday products, mostly including single-serving food items such as milk, bread, snacks, groceries to over-the-counter medications, household items, stationery, and small auto supplies such as fuses. 

> shop=supermarket - shops which sell a whole range of products, but which are large. Suggested distinction: Large enough to have push trolleys. Please note that many small shops will call themselves supermarkets in their name. Please choose based on the size of the shop, not its name.

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dconvenience

**Comment by Lulucmy** [comment]
Hey,
I am French and I there are two Vival near my home. I've been around France for years and I can tell you that Vival are convenience stores. You'll find them in petrol station (highway stops), high mountain and countryside. These are small shops, you'll find 50-100 products, so I wouldn't say that these are supermarkets.

**Comment by matkoniecz** [comment]
I looked at tagged ones and `shop=supermarket` ones looks mistagged http://overpass-turbo.eu/s/H6f

**Comment by Adamant36** [comment]
You should start a MapRoulette thing for it. I would, but I don't know how :(

**Comment by Lulucmy** [comment]
These shop are mistagged, for e.g. this one (near my house) : 
![image](https://user-images.githubusercontent.com/20552095/54518473-a2e53b80-4964-11e9-8fc5-f134e9cc00f7.png) ![image](https://user-images.githubusercontent.com/20552095/54518460-9d87f100-4964-11e9-8e7b-3408034bc95b.png)
It's clearly not a supermarket, you don't have trolleys, just a few items for the beach and sandwiches...

**Comment by Adamant36** [comment]
@tas50, you want to do a MapRoulette for it since you know how?

**Comment by matkoniecz** [comment]
Note that I opened OSM notes for some suspicious stores.

**Comment by Adamant36** [comment]
> Note that I opened OSM notes for some suspicious stores.

Thanks. That works also. I wasn't sure how many there were or if notes would be sufficient because OverPassTurbo froze up on me before I could check.

**Comment by bhousel** [comment]
> I am French and I there are two Vival near my home. I've been around France for years and I can tell you that Vival are convenience stores. You'll find them in petrol station (highway stops), high mountain and countryside. These are small shops, you'll find 50-100 products, so I wouldn't say that these are supermarkets.

Thank you, that is good information! It sounds like it should be in the index as 2 records - one for supermarket and one for convenience.

**Comment by matkoniecz** [comment]
Hmm, for me it sounds like all of the are convenience shops.

And I edited this way, so if it is wrong then it would be necessary to revert it.

**Comment by bhousel** [comment]
> Hmm, for me it sounds like all of the are convenience shops.
> 
> And I edited this way, so if it is wrong then it would be necessary to revert it.

Oh ok, sorry! I misread the above comment.  I'll set them as `shop=convenience` only for now..

**Comment by bhousel** [comment]
> Oh ok, sorry! I misread the above comment. I'll set them as `shop=convenience` only for now..

aaaand.. that's how they already are.. so there is nothing to do!
