### ISSUE TITLE
Fix wiki tagging for Co-op in the UK

### ISSUE THREAD

**Issue by lakedistrictOSM** [osmlab/name-suggestion-index#2315]
Presets affected:
- Co-op (supermarket)
- Co-op (convenience)

Currently these are tagged `brand:wikidata=Q5440676` and `brand:wikipedia=en:Federated Co-operatives` which is a Canadian brand. In the UK they should be tagged `brand:wikidata=Q3277439` and `brand:wikipedia=en:Co-op Food` 

And yes, there is overlap with The Co-operative Food which is the old name. Not sure if it's been completely phased out yet though, so it makes sense to keep both names in the suggestion index.

**Comment by Zilula** [comment]
Hi. Would love to work on this issue.

**Comment by tas50** [comment]
@Zilula It's yours

**Comment by Zilula** [comment]
@tas50 Awesome, thank you.

**Comment by Zilula** [comment]
@tas50 I read the Contributing documentation but didn`t see if it was necessary to open a new branch. I opened one anyway, should I push the branch up and open a PR?

**Comment by maingockien01** [comment]
Hi, was the bug fixed ?

**Comment by Adamant36** [comment]
Seems it wasn't since the PR that was suppose to fix it got closed instead of being merged because its a complicated issue. Feel free to try and fix it if you want though.

**Comment by maingockien01** [comment]
Awesome, I will give it a shot.

**Comment by maingockien01** [comment]
hmm I have searched Google about Co-op and I see the name "Co-op" is quite wide and not specific. If you want to mean "Co-op" is supermarkets/conveniences in UK, "Co-op Food" name seems better.
 Should I change the name of the brand?

**Comment by bhousel** [comment]
> Should I change the name of the brand?

No, there are several "co-op" brands used all around the world.  Ideally this project would capture as many of them as possible, and with links to appropriate wikidata pages for each one.  If needed, we can filter the entries by the country code, and also add disambiguation test to the names like "Co-op~(UK)" if that is what's needed.

(like @Adamant36 said, this one is a bit more complicated than the typical issue in this repository)

**Comment by maingockien01** [comment]
Well, I got your idea. As I added country code, now I just need to update more Co-op brand in different countries.

**Comment by bhousel** [comment]
This was done (not sure when)
