### ISSUE TITLE
Add entry for: Marathon Sports

### ISSUE THREAD

**Issue by sguinetti** [osmlab/name-suggestion-index#2355]
[Marathon Sports Website](https://www.marathon.store/)
[Wikipedia](https://es.wikipedia.org/wiki/Marathon_Sports)
`brand=Marathon Sports`
`shop=sports`

**Comment by ImreSamu** [comment]
in Hungary - a similar company name:  https://www.marathonsport.hu/en/main-page/    ( at least the domain name of the company )

**Comment by ImreSamu** [comment]
in the U.S 
* "Marathon Sports, Inc. is an American chain of sporting goods retailers."
  * https://en.wikipedia.org/wiki/Marathon_Sports_(retailer)
  * https://www.marathonsports.com/

**Comment by sguinetti** [comment]
This is interesting. However, this Ecuadorian company has no relationship with the American or Hungary company. This another website with "Marathon Sports" commercial brand http://www.marathoncorporativo.com/ (similar to first website).

**Comment by Adamant36** [comment]
Going by Taginfo and OverPassTurbo there's only 11 of them mapped. Two are in America and the rest are in south america.

**Comment by sguinetti** [comment]
Yes. On the web there are other stores. So it remains to include more POIs to OSM. https://www.marathon.store/store-finder

**Comment by Adamant36** [comment]
The issue is how to separate the ones in America from the ones in South America I guess.

**Comment by ImreSamu** [comment]
yes, my issue - is the separating.

so  `countryCodes` is important in this case 
```
"countryCodes": ["ec","pe"],                 // Optional `countryCodes` - array of countries where this entry is used   ; in this case  [  'ec'=Ecuador ; 'pe'=Peru ]
```

see [Contributing](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#identical-names-multiple-brands)
