### ISSUE TITLE
Research needed for: amenity/bank|Cajero Automatico Bancared

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#237]
#### :thinking: We need help deciding what to do with "amenity/bank|Cajero Automatico Bancared"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Cajero Automatico Bancared` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Cajero Automatico Bancared`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Cajero Automatico Bancared`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
My thought is that this might be only an ATM of a bank, because it has "Automatico" in it... Maybe somebody can confirm this?

**Comment by Adamant36** [comment]
That's my guess also. I added the "check local" label.

**Comment by matkoniecz** [comment]
Google translate gives

> Bancared ATM

so what is this? Mass misstagged ATMs?

**Comment by Adamant36** [comment]
That's my guess. Probably a term for a generic ATM machine. Cajero means ATM and the rest is pretty obvious. Its not a brand name.

**Comment by ENT8R** [comment]
I did another research and I found out that the majority of "banks" with this name are existing in the capital of Guatemala: 114 of 125 are only in one city (Ciudad de Guatemala). And all of them were added only by a single user...
The other 9 occurences are then misstaggings in other places of the world (probably set via the iD preset for this entry)
This is why I added the entry to the list of generic names.

**Comment by Adamant36** [comment]
Thanks. Sounds like the correct thing to do.
