### ISSUE TITLE
Braum's tagging

### ISSUE THREAD

**Issue by SilentSpike** [osmlab/name-suggestion-index#2382]
An American brand which already has an entry, `shop/dairy|Braum's`, and the wikidata page is `Q4958263`.

However, I can't tell if shop=dairy is the right tagging. It looks like they serve fast food and specialise in ice cream. Perhaps someone more familiar with the brand can weigh in on the tagging for these.

**Comment by bhousel** [comment]
oh yeah, it really looks like we should change it to `amenity=ice_cream`

**Comment by bhousel** [comment]
Actually reading more here https://en.wikipedia.org/wiki/Braum%27s  I'm not so sure.

Not crazy about having both `amenity=ice_cream` and `shop=dairy` but it seems like this place really does do both things.

**Comment by bhousel** [comment]
I ended up moving it from `shop/dairy.json` to `amenity/fast_food.json`, (per Slack it is "basically a Dairy Queen") with a `shop=dairy` tag.

```js
  "amenity/fast_food|Braum's": {
    "count": 118,
    "countryCodes": ["us"],
    "match": ["shop/dairy|Braum's"],
    "tags": {
      "amenity": "fast_food",
      "brand": "Braum's",
      "brand:wikidata": "Q4958263",
      "brand:wikipedia": "en:Braum's",
      "cuisine": "ice_cream",
      "name": "Braum's",
      "shop": "dairy"
    }
  },
```
