### ISSUE TITLE
German clothes recycling containers

### ISSUE THREAD

**Issue by johnjohndoe** [osmlab/name-suggestion-index#24]
Can you please add `operator` names of [German clothes recycling containers](http://wiki.openstreetmap.org/wiki/Deutsche_Altkleider-Container_Betreiber)?

**Comment by johnjohndoe** [comment]
Ping.

**Comment by johnjohndoe** [comment]
Ping.

**Comment by Firefishy** [comment]
Pull Requests are where all the love is.

**Comment by bhousel** [comment]
closing as stale
