### ISSUE TITLE
Research needed for: amenity/bank|Chase

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#240]
#### :thinking: We need help deciding what to do with "amenity/bank|Chase"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Chase` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Chase`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Chase`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
I suspect that it is https://en.wikipedia.org/wiki/Chase_Bank but there are some locations in Adrica and Sri Lanka that are suspect - https://overpass-turbo.eu/s/COp

https://www.openstreetmap.org/node/5986953664
https://www.openstreetmap.org/node/5986976759
https://www.openstreetmap.org/node/1460894592
https://www.openstreetmap.org/node/5552467820
https://www.openstreetmap.org/node/4075655670

**Comment by bhousel** [comment]
I'd assign it to Chase Bank.
https://en.wikipedia.org/wiki/Chase_Bank

There will always be outliers in Overpass, but that's ok.  We aren't mass retagging stuff, we're just trying to build an index that can help people add common brands in the editors.
