### ISSUE TITLE
likely Canada only companies not marked as Canada-only

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2406]
'amenity'='bank' and name='Banque Laurentienne' is unique in OSM tagging to Canada. Consider adding `"countryCodes": ["ca"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Caisse Desjardins' is unique in OSM tagging to Canada. Consider adding `"countryCodes": ["ca"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Desjardins' is unique in OSM tagging to Canada. Consider adding `"countryCodes": ["ca"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

**Comment by bhousel** [comment]
If you are pretty sure about these, just change them.. You don't need to open issues for each thing your script finds..

**Comment by matkoniecz** [comment]
I think that manual verification is needed, I checked some (see commits) but I am unable to go through all of them.

Or is automated editing based on location within OSM database good enough?

**Comment by bhousel** [comment]
I’m just saying, this issue has 3 Frenchy-sounding names only found in Canada.  It’s probably fine. We don’t need an actual Canadian person to show up and check it. 

If you opened a PR that said “my script found that these banks are single country so I added the countries”, I’d just take a quick look and accept it.  Even if you wanted to just push that change directly to master, that’s fine too.  I trust you!

**Comment by matkoniecz** [comment]
I will keep this one open to not forget about this script.

**Comment by Adamant36** [comment]
You still want me to add them and I'll just keep the issue open after or no?
