### ISSUE TITLE
contry code for ireland - ie or ir?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2407]
From what I see at https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 it is ie.
Currently at least AIB bank use "ir" what is a code for Iran.

**Comment by Adamant36** [comment]
Here's the link @bhousel gave me to go off of if you want it. I guess Wikipedia isn't 100% accurate or something https://www.nationsonline.org/oneworld/country_code_list.htm
