### ISSUE TITLE
likely Spain only companies not marked as Spain-only

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2410]
'amenity'='bank' and name='Banco Sabadell' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Bankia' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Caixabank' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Caja España' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Caja Rural de Jaén' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='CajaSur' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='Cajamar' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

'amenity'='bank' and name='CatalunyaCaixa' is unique in OSM tagging to Spain. Consider adding `"countryCodes": ["es"],` to its entry if this company is really present in this country. It will allow editors to not offer this as a suggestion in other countries and to detect mistakenly tagged objects. If that is false positive and is present also in other countries - comment below or just close this issue.

**Comment by matkoniecz** [comment]
closing in preference to an automatic processing

**Comment by Adamant36** [comment]
So you don't need them done now then?

**Comment by matkoniecz** [comment]
I think that I will switch for automatic adding. There is a second part that will certainly require a manual review but it is not ready at this moment.

**Comment by matkoniecz** [comment]
But thanks that you wanted to help with this!

**Comment by Adamant36** [comment]
OK that works. No problem. Feel free to ping me if you want help with anything else.

**Comment by matkoniecz** [comment]
@Adamant36 Can you look at https://gist.githubusercontent.com/matkoniecz/443ea2f716eee9c113579ad6dd5b0a65/raw/719720a91b831775c3c11bf95bd310e16748a301/gistfile1.txt ?

It is initial dump of mismatches between declared country limits and actual OSM usage.

In cases where there is a huge use outside specified countries investigations would be useful. Obviously, just because name appears once in other country is not a good reason to add that country but using it I found cases like

- limitations set to wrong country https://github.com/osmlab/name-suggestion-index/commit/1c897cf47438ab3e38fd5f49af8d6eda04af71e1
- missing different company across world with the same name https://github.com/osmlab/name-suggestion-index/commit/f494657cb25f98088b7c57e0e9dd116626ba8f6e
- typo in country code https://github.com/osmlab/name-suggestion-index/commit/e785f9f9592d64ffe3d00c10b23931f357ddd6c8

Let me know if it is confusing/not usable - it probably is and I plan on making it more readable. But let me know what is confusing/unclear.
