### ISSUE TITLE
Include no-longer existing brand, especially ones popular in OSM

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2415]
Obviously it should be distributed separately, not as source for suggestion but rather for validator complaints.

It would also help with maintaining index - there are some unclear case like

```
  "amenity/bank|Banco Popular": {
    "count": 704,
    "countryCodes": ["pr", "us", "vi"],
    "match": ["amenity/bank|Popular"],
    "tags": {
      "amenity": "bank",
      "brand": "Banco Popular",
      "brand:wikidata": "Q537259",
      "brand:wikipedia": "es:Banco Popular Español",
      "name": "Banco Popular",
      "name:en": "Popular Bank",
      "official_name": "Banco Popular Español",
      "official_name:en": "Spanish Popular Bank",
      "operator": "Banco Santander",
      "operator:wikidata": "Q806215",
      "operator:wikipedia": "en:Banco Santander"
    }
  },
```

that is mapped 400+ in Spain, 200+ in Dominicana, company is described as gone on Wikipedia. It would be nice to know whatever someone checked is this brand is still used in Spain or not.

Other examples: Banca Intesa - is this brand still in use or is OSM outdated?

```
{
  "tags": {
    "amenity": "bank",
    "brand": "Allied Bank",
    "brand:wikidata": "Q4732555",
    "brand:wikipedia": "en:Allied Banking Corporation",
    "name": "Allied Bank"
  },
  "countryCodes": [
    "pk",
    "ph"
  ]
}
```
is also described as defunct

**Comment by Adamant36** [comment]
That would be really helpful. There's been a couple of banks I've ran across that were either closed or consolidated with other brands and I just left them in the database because I wasn't sure what to do with them (I think that was actually one of them), but it would be worth saving the entries somewhere for re-tagging efforts later. I don't think just adding them the exclude file is a good option.

**Comment by bhousel** [comment]
Good idea!
Maybe we could add something like a `"deprecated": true` property to these entries.
Maybe also `"upgradeTo" : "amenity/bank|whatever"` so that iD can do the upgrades.

**Comment by matkoniecz** [comment]
And maybe also `notSimpleUpgrade` (or something better) where not all were transformed into a new brand?

**Comment by tas50** [comment]
There's a lot of these in the US as well. Toys R Us and Payless shoes are EVERYWHERE and they're both gone.

**Comment by matkoniecz** [comment]
> Toys R Us

This is an interesting case and reminder that brand may be only partially gone - it is certainly still present in Poland.

Maybe something similar to `countryCodes`? Though `countryCodesWhereNoLongerPresent` is probably too long.

**Comment by Adamant36** [comment]
There's still Payless Shoe stores in malls in a few places also. I was just in one the other day.

**Comment by tas50** [comment]
Toys R Us is pretty weird since they licenses their brand globally and the folks that licensed the brand are continuing to run them. At some point I want to get a MR challenge to clean those up, but I need to research exactly where they shutdown and where they stayed open. Payless is in the middle of a global shutdown. They're not even trying to restructure like Toys R Us. They're just calling it quits and closing all the stores.

**Comment by Adamant36** [comment]
"Payless is in the middle of a global shutdown. They're not even trying to restructure like Toys R Us. They're just calling it quits and closing all the stores."

According to a CNN article a few weeks ago, "A spokeperson said its international franchises and Latin American stores will not be affected." 

I guess Toys R Us is going to try and make a comeback with a new name. It should be interesting to see how that goes. In the meantime, I doubt they will inhabit the old stores. So its probably worth cleaning the ones up that can be. How does it work on
Map Roulette for those types of things? Like, is there a way to keep people from deleting the legitimate ones while they are in the process of getting rid of the bad ones or is it "all or nothing"?

**Comment by matkoniecz** [comment]
See https://osm.mathmos.net/ghosts/ for a project collecting brands gone from UK.

**Comment by matkoniecz** [comment]
Comercial Mexicana is one more case of a defunct brand.

**Comment by matkoniecz** [comment]
My current idea is to have `"defunct": yes` field.

It would cause entry to be removed from default distribution file, become added to a new distribution file specially for defunct entries.

Cases where brand is gone in some countries and continue to exist in other would have two entries, one with `"defunct": yes` field, one without. Both would have country codes restriction specified.

**Comment by Adamant36** [comment]
That might work. Although I think "desolved" might be a better word. Its how closed down companies are usually refered to. Although, I guess it doesn't really matter. Either word works.

**Comment by matkoniecz** [comment]
Maybe `gone` of `not_existing` as key name would be even better?

**Comment by Adamant36** [comment]
Is this something that will be added to OSM database or stay in the name index?

**Comment by matkoniecz** [comment]
That would be entry in the name index. It could be used by validators to flag entries that are likely to be outdated.

**Comment by Adamant36** [comment]
Then I guess it doesn't matter and your suggestions are as good as mine. So whichever you prefer.

**Comment by matkoniecz** [comment]
PR opened.
