### ISSUE TITLE
Same shop, two entries, which of the two names to put in a match array?

### ISSUE THREAD

**Issue by coderbeetle** [osmlab/name-suggestion-index#2419]
These two appear to be the same shop, yet there are two different entries for them. I thought about including one of them into the other with a `"match": []` array, but I'm not sure which variation to keep and which to put in the array.

![image](https://user-images.githubusercontent.com/48364789/54087638-68284580-435d-11e9-9a46-03d3b998d33e.png)

**Comment by bhousel** [comment]
I'd keep the `"shop/beverages|Fristo"` entry, add `"match": ["shop/beverages|Fristo Getränkemarkt"]`, and delete the other one.

1. It's used more frequently (99 vs 53)
2. It's a shorter name which is better for displaying on maps.

**Comment by coderbeetle** [comment]
That's what I thought as well, I just wasn't sure :) Thanks, I'll do that!

**Comment by bhousel** [comment]
done in #2420
