### ISSUE TITLE
Browsable name suggestion index ideas

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2438]
I generated some summary pages for all the categories here:
 http://osmlab.github.io/name-suggestion-index/brands/index.html 

Try it out - anyone who is interested in improving the logo coverage on Wikidata will find this very useful!

This shows you:
- which brands are missing a `brand:wikidata` tag and 
- which brands with a `brand:wikidata` tag have no logo, or unsuitable logo.

`npm run docs` will regenerate these pages.

I'm opening this issue to get some feedback on what other things we can add to the generated pages to make this even more useful.

**Comment by bhousel** [comment]
- [ ] Add a link to overpass-turbo for each row, so you can see where it is
- [ ] Add anchors so people can link to any row

**Comment by todrobbins** [comment]
One quick thought: ability to filter the tags on the main page:
<img width="791" alt="Screen Shot 2019-03-13 at 10 08 07 PM" src="https://user-images.githubusercontent.com/158590/54330737-8485e580-45dc-11e9-820c-396998e5d9ae.png">

**Comment by matkoniecz** [comment]
404 page at http://osmlab.github.io/name-suggestion-index/ is a bit ugly

**Comment by matkoniecz** [comment]
There are some problems with handling country-limited entries, though impact is not big.

See Agribank at http://osmlab.github.io/name-suggestion-index/brands/amenity/bank.html

Overpass turbo links are misleading (should be country limited).

"< 50" is result of `nocount` that was necessary due to name collisions, but it is not implying "< 50" usage. Maybe "no data" would be better?

**Comment by matkoniecz** [comment]
What is the point of Facebook and Twitter columns? As far as I know it is not something that should be added to OSM or is useful in OSM editors.

**Comment by Adamant36** [comment]
"What is the point of Facebook and Twitter columns"

They are just another source for an icon in case Wikimedia doesn't have it. Also, the icon links are obtained through the Wikimedia entries. So if a Twitter or Facebook entry isn't in the Wikidata page the index won't use those sources. From what I've seen so far they can have better quality icons then Wikimedia in some cases also. Especially Twitter. Twitter icons might be more up to date also. 

Twitter and Facebook isn't used other then that though (that I know of).

**Comment by bhousel** [comment]
> What is the point of Facebook and Twitter columns? As far as I know it is not something that should be added to OSM or is useful in OSM editors.

Yes, we aren't adding the info to OSM, but I'm going to use those links to fetch their logo images to display in iD.  

Logos are one thing that often isn't (or can't be) added to Wikidata because of copyright concerns, but using them "for information purposes" (i.e. to identify a branded business on a map) is ok.

**Comment by bhousel** [comment]
> There are some problems with handling country-limited entries, though impact is not big.
> See Agribank at http://osmlab.github.io/name-suggestion-index/brands/amenity/bank.html
> Overpass turbo links are misleading (should be country limited).

Ohh yeah that makes sense, since the overpass search is just by `name`.  I *think* anyone who gets dropped into Overpass should be able to figure this out.  Overpass is really for finding where the name is used and if it spills out into other countries, that is an important thing to know.

**Comment by Adamant36** [comment]
I noticed that some Wikidata entries for restaurant's have a "cuisine" value. For instance Baja Fresh (Q2880019). Would it be possible to query it to add to the Wikidata Description table? Then we could use it to add cuisine tags to restaurant in OSM where we don't have them, and we could also use our values to improve Wikidata where we can. My guess is that there would be more cuisines missing from Wikidata entries and Wikidata's system seems a little more restrictive on what can be added to it, but it still might be worth doing.

**Comment by matkoniecz** [comment]
One would anyway need to read at least Wikipedia article to check is it correct (see "plate of fries photo added as a logo").

And fully automated import would be a poor idea, we would risk be importing into OSM some database that is CC0 only in USA.

**Comment by Adamant36** [comment]
> One would anyway need to read at least Wikipedia article to check is it correct (see "plate of fries photo added as a logo").

Cuisine information is different then a messed up icon. People are already getting the information from Wikipedia articles in some cases, but it would just streamline things slightly to do it this way, allow for more of a two way transaction, and would provide an extra data set to double check with that people might not think of normally. 

> And fully automated import would be a poor idea anyway, we would risk importing into OSM some database that is CC0 only in USA.

I'm not suggesting the information be automatically imported into OSM. I'm asking to have it in the table for people to check against what's already there and add from in cases where its needed. Its no more an import or automatic then what people are already doing, except it just negates the need to open an extra page in some cases. Listing the information in the table isn't in anyway equal to it being in OSM, whatever people do or don't do with it. It's not insinuating people start mass "automatically importing" it just because its in there either. Anymore then it is with company URL's by having them in the table. Which people can add to OSM if they feel like. So I'm not sure what the difference would be.

**Comment by bmillemathias** [comment]
That would be great to have that page generated each time a merge is done

**Comment by SilentSpike** [comment]
Something that's been bugging me for a while:

Maybe just me that experiences this, but the fact that the categories are sorted alphabetically in rows and not columns makes it harder to navigate.

**Comment by bhousel** [comment]
> Something that's been bugging me for a while:
> 
> Maybe just me that experiences this, but the fact that the categories are sorted alphabetically in rows and not columns makes it harder to navigate.

Ah yeah this bugs me too... I will try to change it.

**Comment by yotamN** [comment]
Is it possible to use Instgram pictures as well?

**Comment by bhousel** [comment]
> Is it possible to use Instgram pictures as well?

Not currently

**Comment by 1ec5** [comment]
> In practice, I haven't run into many brands without some kind of presence on Facebook (either official or a fan page).

I haven’t been looking for fan pages on Facebook, but I figure those aren’t what Wikidata’s Facebook ID property is supposed to be used for anyways.

So far, every time I’ve encountered a brand without an official Facebook account, it’s been either a bank (which in the U.S. means it’s subject to more regulation over its social media usage) or a chain that’s limited to more rural communities where Facebook has less of a presence.

**Comment by bhousel** [comment]
> I haven’t been looking for fan pages on Facebook, but I figure those aren’t what Wikidata’s Facebook ID property is supposed to be used for anyways.

Usually not, but I've noticed a handful of Japanese brands with no official social media, where fans have set up pages that are maintained in a lot of detail.  (These might be run unofficially by employees - I don't know).

**Comment by bhousel** [comment]
I added a tag filter today!  Try it out
https://osmlab.github.io/name-suggestion-index/index.html

Looks like this:
![filtering](https://user-images.githubusercontent.com/38784/60547034-ae2e5e00-9cec-11e9-9ca5-bac906c8d163.gif)
