### ISSUE TITLE
Hofer only as a supermarket, not as fuel

### ISSUE THREAD

**Issue by tordans** [osmlab/name-suggestion-index#2443]
Right now, Hofer is in the index twice:
- fuel https://github.com/osmlab/name-suggestion-index/blob/b2e768bb4847fc45cf3a4bc9e3208395fd2dee15/brands/amenity/fuel.json#L1105-L1119
- supermarket https://github.com/osmlab/name-suggestion-index/blob/d0c923dd8e66361f3feec95ca242ba882cf7e5b1/brands/shop/supermarket.json#L1741-L1755

Both link to the wiki data https://www.wikidata.org/wiki/Q15815751 which states that it is a supermarket.

I could not find a reference why it should also be a fuel provider. Especially since logo and wikidata all link to the same shop.

I suggest removing the fuel-name-suggestion from the index.

**Comment by matkoniecz** [comment]
See http://overpass-turbo.eu/s/H0M

Looks like case of supermarket-brand fuel stations. If you are convinced that tagging is wrong - can you open osm notes at some of this places with request to locals to check this?

Have you checked whatever https://de.wikipedia.org/wiki/Hofer_KG mentions fuel stations?

**Comment by Adamant36** [comment]
![Hofer 1](https://user-images.githubusercontent.com/30259065/54419746-74960080-46c5-11e9-87c6-ab1729c94cda.jpg)
![Hofer 3](https://user-images.githubusercontent.com/30259065/54419809-92636580-46c5-11e9-9391-8e3729a45e58.jpg)

**Comment by matkoniecz** [comment]
So it looks like a typical supermarket fuel station. Closing.

**Comment by tordans** [comment]
Thanks!

**Comment by Adamant36** [comment]
Yep. At least we know now.
