### ISSUE TITLE
Show counts in duplicate warnings

### ISSUE THREAD

**Issue by waldyrious** [osmlab/name-suggestion-index#2461]
[CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#thinking--resolve-warnings) currently recommends the following to pick which of the duplicates to eliminate:

> Usually the entry used more frequently (indicated by "count" property) is the one to keep. If you are not sure, you can also search on the OpenStreetMap Wiki for tag best practices.

But the warnings output does not show this count, so one has to manually open both files to check the counts, which is unnecessarily cumbersome.

This count should be visible directly in the output, e.g.:

    "tourism/motel|Motel 6" (count: 123) -> duplicates? -> "tourism/hotel|Motel 6" (count: 456)

**Comment by matkoniecz** [comment]
I am not sure is it really useful. It is necessary to check more than just raw count.

I would rather update CONTRIBUTING.md.

**Comment by waldyrious** [comment]
Yeah, I just made the mistake of relying on the count alone in #2465. I'd be happy to submit a change to CONTRIBUTING.md, but I'm not sure what would be appropriate. Perhaps listing 2 or 3 checks that can be performed, including the count?

**Comment by matkoniecz** [comment]
> Perhaps listing 2 or 3 checks that can be performed, including the count?

I think that would be a good idea.

**Comment by matkoniecz** [comment]
I opened #2473 - review is welcomed.

**Comment by waldyrious** [comment]
Do you guys know if it's possible to limit / filter the warnings to a given country or region (so that local knowledge can indeed be applied)?

**Comment by matkoniecz** [comment]
> Do you guys know if it's possible to limit / filter the warnings to a given country or region (so that local knowledge can indeed be applied)?

Currently not really well. I made script that will add all missing `countryCodes`, including entries waiting for processing but it will take time - for now it processed only small part of bank entries. It bottlenecks on reverse geocoding, it could be working thousands of times faster if I would have a working offline reverse geocoder (location to country code). Currently I am calling Nominatim API, 1 call every 1.3 s (to be within usage limits).

**Comment by matkoniecz** [comment]
I think that it can be closed and considered fixed by https://github.com/osmlab/name-suggestion-index/pull/2473/files

Showing raw taginfo count may mislead people (like old documentation version) into treating count as sole measurement.

@waldyrious What is your local area? Portugal? I can ping you once entries for review are ready.

**Comment by bhousel** [comment]
> If someone can recommend working reverse geocoder (country code is sufficient but accuracy should be high - wrong results near borders are not OK), deployable on an old laptop ("import planet" as one of steps is nonstarter) - let me know! I tried two geocoders, both were not working properly (first project is dead, in second I reported minimal example).

I have a feeling @nyurik could throw together a SPARQL query against Sophox that would do this.  It has an up-to-daily extract of OSM features with geometry.

**Comment by waldyrious** [comment]
> I think that it can be closed and considered fixed by https://github.com/osmlab/name-suggestion-index/pull/2473/files
>
> Showing raw taginfo count may mislead people (like old documentation version) into treating count as sole measurement.

Agreed, closing now.

> @waldyrious What is your local area? Portugal? I can ping you once entries for review are ready.

Yes, Portugal :) I'd like to prioritize the Braga region in particular, if a finer level of detail is possible, but that's just a nice extra.
