### ISSUE TITLE
Use alphanumeric shortcuts in wikimatch script

### ISSUE THREAD

**Issue by waldyrious** [osmlab/name-suggestion-index#2462]
Currently if I execute `npm run wikimatch`, I get a prompt like this:

```
']':  Next name
'[':  Previous name
'}':  Skip to next tag
'{':  Skip to previous tag
'/':  Search for a key
'e':  Toggle 'en:' tags (currently OFF)
'q':  Quit

Choose:
```

This may be convenient for en-US keyboards, but for many others some of the keys (especially the brackets) are only accessible in combination with `Shift`, `AltGr`, or other modifier keys.

It would be much easier if the menu accepted alphanumeric shortcuts instead, e.g. mnemonic ones like those used by `git add --patch`:

```
'nn':  Next name
'pn':  Previous name
'nt':  Skip to next tag
'pt':  Skip to previous tag
's':  Search for a key
'e':  Toggle 'en:' tags (currently OFF)
'q':  Quit
```

or

```
'n':  Next name
'p':  Previous name
'N':  Skip to next tag
'P':  Skip to previous tag
's':  Search for a key
'e':  Toggle 'en:' tags (currently OFF)
'q':  Quit
```

or

```
'n':  Next name
'N':  Previous name
't':  Skip to next tag
'T':  Skip to previous tag
's':  Search for a key
'e':  Toggle 'en:' tags (currently OFF)
'q':  Quit
```

Thoughts?

**Comment by bhousel** [comment]
I don't really plan to spend much time on improving the wikimatch script, as it's a thing we only run occasionally.   

The main requirement is for the keyboard shortcuts to be able to skip through records very quickly - this is why it uses left handed <kbd>1</kbd>,<kbd>2</kbd>,<kbd>3</kbd>... numbers for the choices, and right handed <kbd>[</kbd>,<kbd>]</kbd>... symbols for navigation.  But I'd definitely be willing to switch to something more universal that doesn't require modifiers for non-en-us keyboards.

**Comment by waldyrious** [comment]
@bhousel it seems to me that the wikimatch script is actually a very nice way to make contributions of wikidata and wikipedia tags in a more streamlined manner than what is currently suggested in [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#female_detective--add-wiki-tags), so if anything I would recommend making it _more_ prominent. That's how I made the changes submitted at #2466. Or did I misunderstand its purpose?

**Comment by bhousel** [comment]
I decided to remove the wikimatch script in dba2045e1.

This script was very useful in performing the initial bunch of name <-> qid matching quickly, but now we have a dedicated community of volunteers to match the entries.  So I think we are at the point now where the script is more likely to introduce erroneous matches than helpful ones, and we can get rid of it.

Also, there are some upstream changes going on in the `wikidata-sdk` -> `wikibase-sdk` dependency, so I need to make some changes in all the places we use this dependency to query wikidata.  It didn't make sense for me to spend time upgrading that old wikimatch script.
