### ISSUE TITLE
Add blacklist of instances for Wikidata items in the wikimatch script

### ISSUE THREAD

**Issue by waldyrious** [osmlab/name-suggestion-index#2464]
The wikimatch script currently includes candidates that are clearly not eligible, such as instances of human, of given name, etc.

To give one specific example (note the values in the `instance of` fields):

```
[85/749]: amenity/fuel|Alpet

'1':  Matched: Alpette (Q8993)
      "Italian comune"
      instance of: [comune of Italy]
      article: https://en.wikipedia.org/wiki/Alpette
      brand:wikidata = Q8993
      brand:wikipedia = en:Alpette

'2':  Matched: Alpetragius (Q2119334)
      instance of: [impact crater]
      article: https://en.wikipedia.org/wiki/Alpetragius_(crater)
      brand:wikidata = Q2119334
      brand:wikipedia = en:Alpetragius (crater)

'3':  Matched: alpine skiing (Q186222)
      "skiing variation"
      instance of: [type of sport]
      article: https://en.wikipedia.org/wiki/Alpine_skiing
      brand:wikidata = Q186222
      brand:wikipedia = en:Alpine skiing
```

Ideally, there would be a blacklist of instances which would automatically disqualify items as potential candidates for amenities, and the script would check any candidates against this, to avoid proposing them to the user.

**Comment by waldyrious** [comment]
Alternatively, instead of a blacklist approach, a whitelist could be used, by mapping each amenity type with one (or several) "instance of" value which candidates would have to match.

**Comment by bhousel** [comment]
Oh yeah!  this is kind of #181 .. I'm admittedly not super skilled at querying Wikidata - this is my first project where I've tried it!

**Comment by waldyrious** [comment]
I'd be happy to contribute a list of entities to start filling up such a blacklist (or whitelist), if that'd help.

**Comment by waldyrious** [comment]
Also I can help with composing queries / locating entities at the right abstraction level of the semantic graph.

**Comment by bhousel** [comment]
Closing here, since I got rid of the old wikimatch script.  🔪 
see https://github.com/osmlab/name-suggestion-index/issues/2462#issuecomment-588353843 for context.
