### ISSUE TITLE
Generic poi type associated to a brand/wikidate entry

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#2479]
АЗС associated with Q12122687 is a generic term for a fuel pump in ex-Soviet countries. Should probably be discouraged as a preset

**Comment by matkoniecz** [comment]
Thanks for spotting and reporting this mistake!

**Comment by matkoniecz** [comment]
https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%B7%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F confirms

**Comment by matkoniecz** [comment]
Again, thanks for reporting this mistake!

**Comment by matkoniecz** [comment]
@bhousel Is it maybe a good reason to release a new version to stop iD users from unintentionally adding wrong data?

**Comment by bhousel** [comment]
> @bhousel Is it maybe a good reason to release a new version to stop iD users from unintentionally adding wrong data?

A good thing about wrong data added with `brand:wikidata` is that it is trivially easy to fix with overpass/level0 😄 
But yes I do want to get the updates to nsi into the users soonish.

**Comment by matkoniecz** [comment]
> A good thing about wrong data added with brand:wikidata is that it is trivially easy to fix with overpass/level0 smile

I did it, that is why there are no mistakes currently present :)

**Comment by matkoniecz** [comment]
In addition to iD using name-suggestion-index to complain about bad entries I opened https://josm.openstreetmap.de/ticket/17471
