### ISSUE TITLE
Midas - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2486]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 600,
  "countryCodes": [
    "ca",
    "us"
  ],
  "logos": {
    "facebook": "https://graph.facebook.com/Midas/picture?type=square",
    "twitter": "https://pbs.twimg.com/profile_images/801083117842866176/tVPtEHUe_bigger.jpg"
  },
  "tags": {
    "brand": "Midas",
    "brand:wikidata": "Q3312613",
    "brand:wikipedia": "en:Midas (automotive service)",
    "name": "Midas",
    "shop": "car_repair"
  }
}
````

Country codes declared in name-suggestion-index:
* ca - approximately 1740 mapped entries
* us - approximately 9500 mapped entries

Additional countries with object of matching name and type mapped in OSM
you can use following query in the Overpas Turbo Wizard to look at this data:
'shop'='car_repair' and name='Midas' global
be - approximately 360 mapped entries
za - approximately 90 mapped entries
fr - approximately 5100 mapped entries
es - approximately 610 mapped entries
au - approximately 410 mapped entries
pt - approximately 240 mapped entries
at - approximately 30 mapped entries
ma - approximately 10 mapped entries
nz - approximately 50 mapped entries
it - approximately 50 mapped entries
ls - approximately 10 mapped entries
mx - approximately 140 mapped entries
sv - approximately 190 mapped entries
pl - approximately 40 mapped entries

examples are listed below:
this is in country with code 'be', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1223643537

this is in country with code 'pt', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1314688604

this is in country with code 'be', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1739091864

this is in country with code 'be', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1759618316

this is in country with code 'fr', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1831947739

this is in country with code 'au', according to name index present nearly not present outside ["ca", "us"]
https://www.openstreetmap.org/node/1918035670

**Comment by bhousel** [comment]
Wikipedia says it operates in 17 countries.. 
https://en.wikipedia.org/wiki/Midas_(automotive_service)

So whoever put that `countryCodes` property on there should not have done it, and it should be removed.

**Comment by matkoniecz** [comment]
Or maybe extend it to this 17 countries? Or is it to much to maintain and showing it also in remaining 178 countries is a good idea?

**Comment by bhousel** [comment]
> Or maybe extend it to this 17 countries? Or is it to much to maintain and showing it also in remaining 179 countries is a good idea?

We should not be maintaining the international reach of a brand in this project.  

_If it's more than a few countries, we should just leave it as a global brand and trust mappers to do the right thing._  This will be easier for them soon when iD starts showing them the logo next to the brand name.

My original reason for including `countryCodes` was to filter out brands which are in a different language and can't even be read by the people using the editor.  It had nothing to do with where the brand actually operates, and everything to do with whether a novice user would find it jarring to see that brand pop up in their preset list.

**Comment by matkoniecz** [comment]
For me it is also very useful to show more relevant ones - I am editing with Vespucci and typing on mobile is more frustrating than on a PC.

**Comment by bhousel** [comment]
> For me it is also very useful to show more relevant ones - I am editing with Vespucci and typing on mobile is more frustrating than on a PC.

Yeah I agree - I think it's worth specifying the `countryCodes` where it can be done perfectly.  I worry about adding it where there are exceptions.

Another thing I was worried about are situations like where a national bank operates in one country, but also has a few special branches in London / New York / Hong Kong.  I guess in that situation we could still limit it to the country, and leave it for mappers who know what they are doing to add `brand:wikidata` on the exceptions.
