### ISSUE TITLE
suspiciously generic name - Минимаркет and Мини-маркет

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2490]
@tohaklim Is it maybe something that you can confirm to be a generic name of `shop=convenience`? Or is it maybe a brand?

**Comment by tohaklim** [comment]
Inclined to say these are both generic, but wouldn’t be surprised if some shrewd retailer somewhere trademarked this. Still, not a brand/chain I am aware of

**Comment by matkoniecz** [comment]
Thank you! I may ping you in future on encountering issues that require local Belarus knowledge or ability to understand Belarusian or Russian.

Let me know if that would not be OK.
