### ISSUE TITLE
Семейный is it shop=convenience, shop=supermarket, may be both or is it a generic name rather than a brand?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2492]
https://ru.wiktionary.org/wiki/%D1%81%D0%B5%D0%BC%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9 suggests that it is not a a generic name but brand

overpass turbo link: http://overpass-turbo.eu/s/H94

OSM data suggests that it is rather `shop=convenience` (assuming that this exists as a brand), but `shop=supermarket` is not ruled out.

@tohaklim (seems to be present in Russia, but there is also some Belarusian presence)

**Comment by tohaklim** [comment]
I was able to find this in terms of Russian usage https://russretail.ru/uchastniki/13080-semeynyy.html which appears to show a chain with this name exists in Saratov region, classed as “универсам», which feels closer to a supermarket but would depend on the local usage of that tag/size. 
Guess that might qualify as a local brand?

Certainly no such brand in Belarus, just a generic name. Not sure what on the wikitionary shows it as a brand

**Comment by DmitriiKh** [comment]
Yes, indeed, there is a chain with this name in Saratov. Also, there are many shops in Russia that have the same name but they are not in the chain. You can see them on the pictures [here](https://yandex.ru/images/search?text=%D1%81%D0%B5%D0%BC%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD). I would go with generic.

**Comment by matkoniecz** [comment]
Given generic use it seems safer to not propose this name.

> Or, maybe, it's possible to target only Saratov city?

Currently it would be possible to limit it to Russia.

**Comment by matkoniecz** [comment]
It can be still tagged manually in Saratov where it is actually a brand.
