### ISSUE TITLE
Interspar - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2494]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 127,
  "countryCodes": [
    "at"
  ],
  "tags": {
    "brand": "Interspar",
    "brand:wikidata": "Q15820339",
    "brand:wikipedia": "de:Interspar (Österreich)",
    "name": "Interspar",
    "shop": "supermarket"
  }
}
````

Country codes declared in name-suggestion-index:
* at - 230 mapped entries

Additional countries with object of matching name and type mapped in OSM
si - 18 mapped entries
it - 147 mapped entries
hr - 71 mapped entries
ru - 1 mapped entries
hu - 119 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
'shop'='supermarket' and name='Interspar' global

examples are listed below:
this is in country with code 'it', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/334146727

this is in country with code 'hr', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/628231346

this is in country with code 'hr', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/1982784303

this is in country with code 'it', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/2092088318

this is in country with code 'it', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/2160933842

this is in country with code 'hr', according to name index present nearly not present outside ["at"]
https://www.openstreetmap.org/node/2162550658

**Comment by ImreSamu** [comment]
imho this info is correct in the metadata level 
* https://de.wikipedia.org/wiki/Interspar_(%C3%96sterreich)  ->  Spar Austria  ->  `countryCodes=at`


some local(.hu) comment for this info:

>Additional countries with object of matching name and type mapped in OSM
>hu - 119 mapped entries

in Hungary -  the Interspar is under the ["SPAR" brand umbrella](https://www.spar.hu/hu_HU/spar_csoport/uzlettipusok/interspar.html )

We(= OSM-HU)  have a planned  SPAR  importing/"data cleaning"  process 
* the latest (hu)interspar data proposal is here [osm-hu-interspar.osm]( https://github.com/KAMI911/osm-import-request/blob/master/hu_spar/poi_address_merge_husparint.osm)  ( but this is not final )

According to our plan we will use/overwrite -  at least these brand tags: 
```
    <tag k="brand:wikidata" v="Q610492"/>
    <tag k="brand:wikipedia" v="hu:Spar"/>
    <tag k="name" v="Interspar"/>
```

Summary:  pleaase not add the "hu" countryCodes info!

**Comment by matkoniecz** [comment]
So we should probably go with

> it may be caused by:
> by different brand using the same name, not present in the index (fixable by adding it to the index)

And add `Interspar~(Hungary)`

    <tag k="brand:wikidata" v="Q610492"/>
    <tag k="brand:wikipedia" v="hu:Spar"/>
    <tag k="name" v="Interspar"/>

And there are still two countries left:

```
it - 147 mapped entries
hr - 71 mapped entries
```

**Comment by ImreSamu** [comment]
>So we should probably go with
>it may be caused by:  by different brand using the same name, not present in the index (fixable by adding it to the index)

yes  

in Hungary - we have 3 shop types under the "SPAR" brand. ( we have received the data from spar.hu )

according the import plan:

name                  |  brand:wikidata |  brand:wikipedia |
---------------------- |  ------  |  -------
Interspar  | Q610492  | hu:Spar
Spar Expressz | Q610492  | hu:Spar
Spar | Q610492 | hu:Spar

the data import is  now on the  ( prepare / data cleaning / review / testing )   -  phase 


> it - 147 mapped entries

http://www.interspar.it/    ---(forward) -> https://www.desparitalia.it/
imho:  under the SPAR brand.


>hr - 71 mapped entries

http://www.interspar.hr    This site can’t be reached
according to https://www.spar.hr/hr_HR/spar-hrvatska0/adrese-interspar-spar.html

multiple shop types:
* SPAR Supermarket
* Interpsar Hipermarket 
* Interpsar Restoran

imho:  under the SPAR brand.

**Comment by Adamant36** [comment]
Should probably split it into three different entries if they are different types of markets. I don't know what a Hipermarket is, but there's no reason we can't create unique Wikidata entries for them if need be.

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/Hypermarket

**Comment by Adamant36** [comment]
Thanks. If I remember right there was a proposal for a hypermarket tag awhile back that never went anywhere. To bad. It would have been helpful to the index. Maybe someone can revive it..

**Comment by matkoniecz** [comment]
@ImreSamu

> in Hungary - we have 3 shop types under the "SPAR" brand

What is their shop type? Interspar seems to be `shop=supermarket` though there is `shop=convenience` Interspar ( http://overpass-turbo.eu/s/Hd8 https://www.openstreetmap.org/node/4310753094 )

Spar Expressz is clearly `shop=convenience`.

Spar seems to be either `shop=convenience` or `shop=supermarket`, depending on location.

**Comment by Adamant36** [comment]
There's also SuperSPAR  in South Africa. Along with Spar Gourmet in Austria.  Both are mid-sized supermarkets.

**Comment by Adamant36** [comment]
They all seem to have good usage according to TagInfo. If its agreed that thry should have different entries in the index, id be willing to create Wikidata pages for them. Im sure a good number of the 5000 or so instances of Spar are probably sub brands that just aren't tagged correct. So I think it would be worth creating entries for each one.

**Comment by bhousel** [comment]
stale
