### ISSUE TITLE
Set `takeaway=yes` for some types?

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2496]
It can probably be safely set on all
- `amenity=fast_food`
- `amenity=cafe`
- others?

**Comment by matkoniecz** [comment]
I worry that it is not universally true that all cafes and fast_foods offer that.

**Comment by Adamant36** [comment]
I was thinking about suggesting a similar thing for drive-throughs. There's always exceptions though. Maybe we could just start adding the tags into the brands we are sure about at least and open issues for ones we aren't. Its better then creating some false positives. Even if they might rare. Especially considering how different fast food places are country to country and whatnot. Maybe drive-throughs or takeout are more of a "western" thing? Who knows.

**Comment by bhousel** [comment]
I think I'm just going to do this.  

If anyone knows of an `amenity=cafe` or a `amenity=fast_food` that somehow specifically does not allow takeaway, we can later set `takeaway=no` for that.  I'm willing to bet there is no such thing, at least for branded businesses.

**Comment by matkoniecz** [comment]
I still worry that it will turn out that in some cases it will be a wrong data.
