### ISSUE TITLE
name=Vinmonopolet is never used

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2500]
There is Vinmonopolet entry but this name is never actually used.

See for example https://www.openstreetmap.org/node/1384216370 `name=Vinmonopolet Sletten`

I propose to remove Vinmonopolet entry as clearly against local tagging scheme - it is never used, not even once ( http://overpass-turbo.eu/s/Hel )

**Comment by ENT8R** [comment]
It seems as if all of them have only a `brand=Vinmonopolet` (https://overpass-turbo.eu/s/Hf4)
And the additional name after that is likely the name of the branch.

**Comment by matkoniecz** [comment]
In this situation (no standard name) I am planning to remove this entry.
