### ISSUE TITLE
Магнит у дома - add match?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2501]
`"shop/convenience|Магнит":` has match to `shop/supermarket|Магнит у дома`.

Maybe it also should have match for `shop/convenience|Магнит у дома`?

With planet update in https://github.com/osmlab/name-suggestion-index/commit/5e6f2a4e6441f3fc74d2174d91e2239e491e8dfc.patch `shop/convenience|Магнит у дома` dropped below 50 so its count was removed.

I am now removing its entry, but adding match still may be a good idea.

**Comment by DmitriiKh** [comment]
I'm not sure I completely understand what match is. Does it mean "interchangeable"?

According to the company's website there are different types of stores:
- 13,427 stores "Магнит у дома". The closest thing is a convenience store but some people in Russia could say "supermarket" (not for size but for large assortment). Also people can omit "у дома" and use just "Магнит" 
- 213 stores "Магнит Семейный" which are always supermarkets
- 244 stores "Магнит-Опт" which are hypermarkets 
- 4,505 stores "Магнит Косметик" which sell cosmetics
- unknown (probably small) number of "Магнит Аптека" which are drug stores

I think `shop/convenience|Магнит` , `shop/supermarket|Магнит у дома` and `shop/convenience|Магнит у дома` should be interchangeable.

**Comment by matkoniecz** [comment]
> Does it mean "interchangeable"?

Yes. For example in https://github.com/osmlab/name-suggestion-index/commit/29b5e08ae96c677835c0a866fdb94dfa585288ec I declared `amenity/pharmacy|Ziko` to be a duplicate of `amenity/pharmacy|Ziko Apteka`.


> some people in Russia could say "supermarket"

Is `shop=convenience` tagging always preferred or are there some large enough to make tagging them as `shop=supermarket` preferable?

**Comment by DmitriiKh** [comment]
> Is shop=convenience tagging always preferred or are there some large enough to make tagging them as shop=supermarket preferable?
Some of them are big and they has to be tagged as `shop=supermarket`.

**Comment by DmitriiKh** [comment]
I'm saying that people in Russia can use `shop=supermarket` tag for quite small stores.
For example: https://www.openstreetmap.org/node/4581538290 is not a big store. You can see it on [Google](https://www.google.ca/maps/place/Magnit/@55.7830123,37.7378524,3a,75y,347.76h,81.77t/data=!3m6!1e1!3m4!1shwQAsXyY8FERQt_JzJRR3A!2e0!7i13312!8i6656!4m13!1m7!3m6!1s0x46b5353e207a01e9:0x3641f56996d84b28!2sUlitsa+Shcherbakovskaya,+53,+Moskva,+Russia,+105318!3b1!8m2!3d55.783019!4d37.7341471!3m4!1s0x46b5353e0b4bf859:0xa694e0ebecb41ccb!8m2!3d55.7831515!4d37.7374168) . It's the red one.
It can make a mess but it's historical.

**Comment by Adamant36** [comment]
Im still not clear why your removing entries with under 50 uses. I don't see it mentioned it mentioned anywhere in the contributing file or anything that we should do that, it would still be helpful to keep the entries for multiple reasons, and I'm pretty sure we've added entries with before and @bhousel said he was fine with it. 

My main thoughts for keeping entries under 50 uses is 1. We don't know why they went under or when they will go back to fifty. Its reduent to add the information back again if they do when we already had it. 2. 50 is kind of an arbitrary number 3. If the point in the name index is to improve accuracy of store mapping or whatever, its just as bad to have   a bunch of badly tagged stores with only thirty entries each then it is to have one store with a few hundred uses wrongly tagged. 

I don't think it means the index should have every mom and pop store out there, but fifty uses is way to high a bar. There's plenty perfectly notable, legitimate businesses out there with way less then that. Personally, II think the important thing should be if they are notable enough for a Wikidata entry or not. A lot of brands under 50 uses are.

**Comment by matkoniecz** [comment]
> Im still not clear why your removing entries with under 50 uses.

??? I am confused, is this comment supposed to be here?

**Comment by Adamant36** [comment]
Yeah, you said "shop/convenience|Магнит у дома dropped below 50 so its count was removed. I am now removing its entry." It was in response to that. Unless I miss understood you.

**Comment by matkoniecz** [comment]
Sorry. In this case I removed it because I was pretty certain that it is a duplicate, like `shop/supermarket|Магнит у дома.`. I was not 100% sure so I created this issue.

**Comment by matkoniecz** [comment]
We have in the index `shop/cosmetics|Магнит Косметик`, `shop/convenience|Магнит`, `shop/convenience|Магнит`.

It sounds like it is OK. If something is still wrong it would be probably best to open a new issue.

**Comment by Adamant36** [comment]
That was my bad. I must have miss understood you. No point in keeping it if its a dupe.

**Comment by bhousel** [comment]
Oh yeah it’s ok to have brands with fewer than 50 entries.  That number was just chosen to balance the initial seeding script so that it doesn’t find too many generics. People adding things manually can use their judgement whether a brand is notable enough to belong in this index 👍
