### ISSUE TITLE
Ampersands not escaped in overpass links in docs

### ISSUE THREAD

**Issue by ldw606** [osmlab/name-suggestion-index#2503]
Brands with an & in their name cause incorrect overpass links to be generated in the docs.
This can be seen on the B&M Bargains entry in the [variety_store](https://osmlab.github.io/name-suggestion-index/brands/shop/variety_store.html) section where the link generated is
https://overpass-turbo.eu/?Q=%5Bout:json%5D%5Btimeout:25%5D;%0A(nwr%5B%22shop%22=%22variety_store%22%5D%5B%22name%22=%22B&M%20Bargains%22%5D;);%0Aout%20body;%0A%3E;%0Aout%20skel%20qt;&R
but should be
https://overpass-turbo.eu/?Q=%5Bout:json%5D%5Btimeout:25%5D;%0A(nwr%5B%22shop%22=%22variety_store%22%5D%5B%22name%22=%22B%26M%20Bargains%22%5D;);%0Aout%20body;%0A%3E;%0Aout%20skel%20qt;&R
with a %26 instead of the &

**Comment by ENT8R** [comment]
Fixed with https://github.com/osmlab/name-suggestion-index/commit/b076a33e55626dffd25a3079c093e3efa09fd564
