### ISSUE TITLE
Cosmo - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2519]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 84,
  "countryCodes": [
    "jp"
  ],
  "tags": {
    "amenity": "fuel",
    "brand": "Cosmo",
    "brand:wikidata": "Q2498318",
    "brand:wikipedia": "en:Cosmo Oil Company",
    "name": "Cosmo"
  }
}
````

Country codes declared in name-suggestion-index:
* jp - 68 mapped entries

Additional countries with object of matching name and type mapped in OSM
th - 107 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
'amenity'='fuel' and name='Cosmo' global

examples are listed below:
this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/256551504

this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/2081340999

this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/2089745996

this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/2128238197

this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/2423510173

this is in country with code 'th', according to name index present nearly not present outside ["jp"]
https://www.openstreetmap.org/node/2546437175

**Comment by matkoniecz** [comment]
There are many companies named Cosmo, so far I failed to track down any that would be involved in petrol stations.

**Comment by Adamant36** [comment]
Cosmo Oil Company. They have petrol stations in Japan. Although its not clear from the Wikipedia page if they are located anywhere else. They probably are though. 

https://en.wikipedia.org/wiki/Cosmo_Oil_Company

![Cosmo_Oil](https://user-images.githubusercontent.com/30259065/55045059-c6118a00-4ff9-11e9-9baa-95aa1c08b042.jpg)

**Comment by bhousel** [comment]
I'm closing this as stale too, but I did look into it a bit..

As far as I can tell, the "Cosmo" fuel brand in Japan is still good and NSI is correct.

The 35 or so "Cosmo" stations in Thailand might now be [branded as "PT"](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#pt-56d9b3), but I can't find a press release or any supporting documentation about this, so I'm not comfortable adding a matchName or just mass renaming them.  Eventually someone will resurvey and update them..
