### ISSUE TITLE
BR - mismatch between data in name-suggestion-index and data mapped in OSM (Brazil, Paraguay local knowledge needed)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2520]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 193,
  "countryCodes": [
    "br"
  ],
  "match": [
    "amenity/fuel|BR Postobras",
    "amenity/fuel|Petrobras",
    "amenity/fuel|Posto BR"
  ],
  "tags": {
    "amenity": "fuel",
    "brand": "BR",
    "brand:wikidata": "Q4836468",
    "brand:wikipedia": "pt:Petrobras Distribuidora",
    "name": "BR"
  }
}
````

Country codes declared in name-suggestion-index:
* br - 349 mapped entries

Additional countries with object of matching name and type mapped in OSM
py - 173 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
'amenity'='fuel' and name='BR' global

examples are listed below:
this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/1784482070

this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/2669622293

this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/4144133886

this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/4654861891

this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/4846648527

this is in country with code 'py', according to name index present nearly not present outside ["br"]
https://www.openstreetmap.org/node/4860763717

**Comment by matkoniecz** [comment]
Added in d625352e - @ENT8R can you take a look?

**Comment by ENT8R** [comment]
I didn't add the country code of Paraguay with any intention in my mind (if I would have looked a little bit longer at the results of Overpass Turbo, I probably would also have added 'py' to the country codes)
I did some more reasearch now, and it seems as if the situation is a little bit difficult:
- BR Petrobras does also operate fuel stations in Paraguay. On their website is a map (https://www.petrobrasdistribucion.com.py/estaciones-de-servicios) which shows all of them and a lot of them actually match entries in OSM.
- But there is also another independant fuel station chain only in Paraguay called "[Barcos & Rodados](http://www.barcosyrodados.com.py/)". The abbreviation of that chain is of course "BR" 😞

A possible solution would probably be to rename the entry from `amenity/fuel|BR` to `amenity/fuel|Petrobras`. The second name is a lot more common than the first: 193 vs. 586 according to [Overpass Turbo](https://overpass-turbo.eu/s/HqG). And it is also not only used in Paraguay and Brazil, but actually in all countries of South America, so this seems to be the right one to use.
Then we can create another new entry for Barcos & Rodados with `"countryCodes": ["py"]`.
What do you think?

**Comment by matkoniecz** [comment]
It is likely that "Petrobras" is preferable over "BR Petrobras" and "BR" for "Petrobras Distribuidora" fuel stations but it is complicated enough that Overpass Turbo + easily googleable sources are not giving a confident answer.

**Comment by bhousel** [comment]
stale
