### ISSUE TITLE
remove count field from human editable files

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2523]
It is useful solely during research how many uses are out there and it is always necessary to use Overpass anyway, so it is not too useful.

And people may think that it deserves being edited by humans.

See https://github.com/osmlab/name-suggestion-index/pull/2515/files where someone modified it manually and https://github.com/osmlab/name-suggestion-index/pull/2522#issuecomment-477107834 where new contributor was unsure about its purpose.

Similar to #2472 that proposed to move logos cache away from human editable file.

**Comment by bhousel** [comment]
I'm ok with getting rid of these.. 

What about the `nocount: true` property and the "Warning - Uncommon brand not found in `names_keep.json`" warning (when that property is not set)?  
I do kind of think those are useful just to force people to make sure they really do mean to add a less common entry.  But I'm also ok with getting rid of them, if `count` also goes.

**Comment by matkoniecz** [comment]
I thing that both deleting and keeping it would be OK.

**Comment by Adamant36** [comment]
My votes on delete.
