### ISSUE TITLE
handling of Tesco brands

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2530]
See also #155 for more general issue

Text below copied from https://github.com/osmlab/name-suggestion-index/pull/2521#issuecomment-477389576 - @ldw606 is the author

For images see https://github.com/osmlab/name-suggestion-index/pull/2521#issuecomment-477369268

I wasn't aware that there were Tesco extra branded convenience stores attached to petrol stations or Tesco express branded petrol stations, that confuses the issue even more.

After some more searching I have found _17_ possibly valid Tesco tagging combinations:
`shop/convenience|Tesco Express`
https://www.hamessharley.com.au/files/images/CS1.tesco_pic_.jpg
`shop/convenience|Tesco`
http://redding-fal.place-advisor.co.uk/img/companies/6/64/645/6451/64513.jpg
`shop/convenience|Tesco Extra`
https://i2-prod.getreading.co.uk/incoming/article4106654.ece/ALTERNATES/s615/C_67_article_2090002_body_articleblock_0_bodyimage.jpg

`shop/supermarket|Tesco Express`
http://invezz.com/uploads/story/12027/thumbs/Tesco_Express_Clane_story_full.jpg
`shop/supermarket|Tesco Metro`
https://cdn.images.express.co.uk/img/dynamic/1/590x/secondary/Tesco-Ferment-Fruit-Alcohol-New-Policy-Tesco-Fruit-ID-Challenge-25-Fermentation-250297.jpg
`shop/supermarket|Tesco`
http://img01.thedrum.com/s3fs-public/news/tmp/56002/tesco_9.jpg
`shop/supermarket|Tesco Extra`
https://bmcontent.affino.com/AcuCustom/Sitename/DAM/014/Tescoshopfronttescosupermarket.jpg
`shop/supermarket|Tesco Superstore` – I can only find one of these
https://www.liverpool-one.com/wp-content/uploads/2016/10/Tesco.jpg

`amenity/fuel|Tesco Express`
https://user-images.githubusercontent.com/30259065/55116203-ccf4d700-50a3-11e9-9fa3-f115b8b80c0f.jpg
`amenity/fuel|Tesco`
https://i.dailymail.co.uk/i/pix/2013/11/04/article-2486895-032DB4A20000044D-572_634x421.jpg
`amenity/fuel|Tesco Extra`
https://upload.wikimedia.org/wikipedia/commons/6/60/Tesco_petrol_station%2C_Bidston_Moss.jpg

`amenity/bank|Tesco Bank` – There are only 3 of these according to Tesco’s website
https://corporate.tescobank.com/assets/images/cms/TESCO_BANK_Newcastle175.JPG?crop=(18,0,563,350)&cropxunits=571&cropyunits=381&height=350&width=545

International brands, I’m not familiar with these:
Thailand:

`shop/convenience|Tesco Lotus Express`
http://www.chiangmailocator.com/design/photosbiz/chiang-mai-tesco-lotus-express-moon-muang-rd-7014.jpg
`shop/supermarket|Tesco Lotus Express` ?
https://s3-eu-central-1.amazonaws.com/cp-website-images/wp-content/uploads/2017/08/Tesco-Lotus-Express.jpg
`shop/supermarket|Tesco Lotus`
http://photos.wikimapia.org/p/00/01/70/58/34_big.jpg
`shop/supermarket|Tesco Lotus Extra`
http://photos.wikimapia.org/p/00/03/83/71/98_big.jpg

Slovakia:
`shop/supermarket|Tesco Supermarket`
http://www.prozahori.sk/wp-content/uploads/2015/11/tesco-1024x683.jpg

Of the UK options, I think it would make sense to use these 10:
`shop/convenience|Tesco Express`
`shop/convenience|Tesco`
`shop/convenience|Tesco Extra`
`shop/supermarket|Tesco Express`
`shop/supermarket|Tesco Metro`
`shop/supermarket|Tesco`
`shop/supermarket|Tesco Extra`
`amenity/fuel|Tesco Express`
`amenity/fuel|Tesco`
`amenity/fuel|Tesco Extra`

**Comment by SilentSpike** [comment]
These all look good to me 👍 

I can see people very easily mixiing up the supermarket/convenience presets in practise though. Almost sounds like tesco requires it's own OSM wikipedia page to explain the correct tagging 😆

**Comment by tohaklim** [comment]
This is the case for quite a lot of supermarket brands in the index, most would have sub-brand for smaller convenience places, some would have larger store brands as well - how to handle them?

**Comment by Adamant36** [comment]
> This is the case for quite a lot of supermarket brands in the index, most would have sub-brand for smaller convenience places, some would have larger store brands as well - how to handle them?

My personal opinion is to split sub brands into their own entries whenever it adds something unique and helpful to the map/Wikidata to do so. Outside of that, there probably shouldn't be a hard and fast rule. Myself, Id totally get into the weeds creating Wikidata entries for obscure sub brands that might not have that many stores, because it adds up eventually. 

Plus, I like the idea of expanding access/knowledge to under served/niche areas and once the index gets big enough its possible filtering could happen on the state/province  level. So it could be useful to start collecting entries for smaller sub-brands now before it does. Even if it doesn't though, it's still improves the map in the meantime to do so.

**Comment by tohaklim** [comment]
now somebody (apart from you) needs to start doing that as well

**Comment by bhousel** [comment]
Calling it done in #2740, but let me know if you find more changes needed, or if Tesco changes their store names again.
