### ISSUE TITLE
76

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#2533]
The gas station chain [76](https://www.wikidata.org/wiki/Q1658320) is missing. In fact, iD complains that existing features tagged `amenity=fuel` `name=76` are “generically named”, probably because there’s no entry for this brand in the index. Convenience stores and car repair shops can also carry the 76 brand, though car repair shops often have their own independent branding.

**Comment by Adamant36** [comment]
I noticed that the other day and was pretty surprised by it. I was planning on adding it, but I totally forgot. So thanks for opening an issue about it.

**Comment by tas50** [comment]
This is a super common one I’ve been running into lately that’ll be great to have in the list
