### ISSUE TITLE
Coviran vs Covirán (Portugal, Spain)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2543]
From overpass turbo check:

Coviran appears in both Spain and Portugal - http://overpass-turbo.eu/s/HBJ

Covirán appears in Spain with single shop in Portugal - http://overpass-turbo.eu/s/HBI

Coviran is listed in https://en.wikipedia.org/wiki/List_of_supermarket_chains_in_Portugal 

Coviran seems to have also major presence in Spain - https://www.coviran.es/

----

So initial questions are

- is Coviran in Portugal and Coviran in Spain the same company?
- is Covirán in Spain and Coviran in Spain the same company?

ping @waldyrious

**Comment by DavidMoraisFerreira** [comment]
Hi, 

According to [this page](http://www.coviran.pt/Paginas/aviso.aspx) there are two distinct legal entities. In Portugal, the shops are referred to as “Coviran”, while in Spain they are referred to as “Covirán” (note the accent). 

Therefore it is safe to assume that [this node](https://www.openstreetmap.org/node/5731713144/history) in Portugal was just mistagged.

Should these be described as two distinct brands in the name-suggestion-index?

**Comment by 1ec5** [comment]
Yes, if there is a legitimate reason for distinct name tags, NSI should have a separate entry for each spelling.

**Comment by DavidMoraisFerreira** [comment]
I doubt there is, seems to me like a mechanical edit (obviously with the support of the local community) should get rid of this issue.

**Comment by ArenaL5** [comment]
They're all the same brand, in both countries. (I'm from Spain.)

We Spaniards are just sloppy with capitals; in Spain it's supposed to be "Covirán", acute accent over the A. Skimming over the Portuguese webpage, it seems like in Portugal its "Coviran", no diacritical mark. They probably decided to respell the name.

The same official name and fiscal ID number is noted in both legal notices ([Portuguese](http://www.coviran.pt/Paginas/aviso.aspx) and [Spanish](https://www.coviran.es/aviso-legal)): `Covirán, Sociedad Cooperativa Andaluza`, number `ES-F18004937` (`ES` is for España/Spain; in the Spanish legal notice it's just listed as `F-18004937`).
