### ISSUE TITLE
Планета Суши (Sushi Planet) - popular name or a brand? (Russia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2544]
Is it popular name for unrelated restaurants or is it name of a brand of restaurants?

ping @DmitriiKh (let me know if you prefer to not be spammed about Russia-related issues)

**Comment by DmitriiKh** [comment]
It looks like it's a brand name. It's a restaurants chain. 
http://planetsushi.ru/

**Comment by matkoniecz** [comment]
Thanks!

**Comment by DmitriiKh** [comment]
No problem.

**Comment by DmitriiKh** [comment]
Q62739250
I'd appreciate if someone added wikidata. I promise I'll do it on my own next time.

**Comment by matkoniecz** [comment]
Added, thanks!

**Comment by matkoniecz** [comment]
One more thing - is it a good idea to add `cuisine=sushi` tag to all this restaurants? (I added this based on name and website images, let me know if that would be a mistake).

**Comment by DmitriiKh** [comment]
Yes, it was a good idea to add that tag.
