### ISSUE TITLE
Add instruction how Wikidata entry may be created and that if missing it is a good idea to create it

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2558]
Now we have just https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata

**Comment by Adamant36** [comment]
I've been sort of working on a guide with what data can be entered with each tag. It needs more work, but I had planned on finishing it in the next few weeks and seeing if it would be useful after that. Maybe something from it can be integrated into the contributing file. I think it would be good to have a list of default values for the tags at least. 

https://gist.github.com/Adamant36/68204c6668f892dcaa154ee11c520325

**Comment by 1ec5** [comment]
Some time ago, I created [a similar guide](https://gist.github.com/1ec5/8d44e94db9ac23c0b859c2718d7f82c3) but didn’t add it to this repository because it still needed more work. There’s some overlap, but feel free to copy over anything that isn’t already in the guide you started.

**Comment by Adamant36** [comment]
As you noticed mines a fork. I was going to mention it when I wrote the message about it but I was on mobile and couldn't remember what your screen name was. So sorry for not giving you credit. I'll have to checkout the changes you made since I forked it.

**Comment by matkoniecz** [comment]
According to undeletion discussion on Wikidata external references are mandatory, entries without them can be deleted.

**Comment by 1ec5** [comment]
Would you mind linking to the undeletion discussion, for more context?

**Comment by matkoniecz** [comment]
https://www.wikidata.org/w/index.php?title=Wikidata:Administrators%27_noticeboard&oldid=930147980#Please_undelete_this_entries_about_brands
