### ISSUE TITLE
AXA is more an insurance company than a bank

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#2573]
I've added an AXA insurance Poi in ID and the editor set it automatically with a bank tag but to my knowledge (in France at least) Axa is more an insurance company than a bank. This is confirmed by the wikipedia page.

> AXA is a French multinational insurance firm headquartered in the 8th arrondissement of Paris that engages in global insurance, investment management, and other financial services. 

I don't know what is the source of the decision but amha I should be reviewed.

map with office=insurance (red) and amenity=bank (grey)
https://overpass-turbo.eu/s/HXW
it shows majority of amenity=bank were used in Belgium, I don't knoz if there is a specific status there.

Best

**Comment by Adamant36** [comment]
According to [this](https://de.wikipedia.org/wiki/Axa_Bank) German article, AXA insurance is owned by AXA Bank or something. It's not really clear. There are banks though, as can be told by the company logo. Seems like it needs to be split into both an insurance company and a bank, but I'm not sure how.

**Comment by Prince-Kassad** [comment]
In Germany AXA is an online-only bank, so it doesn't make sense to add amenity=bank since they don't actually have any facilities where you could deposit/withdraw money or print your current balance. They operate solely by their insurance agents.

Still no idea about Belgium.

**Comment by Adamant36** [comment]
> since they don't actually have any facilities where you could deposit/withdraw money or print your current balance.

Banks do more than provide money deposits/withdraws. In my opinion "insurance" is a very specific thing and it looks like this bank/whatever handles more than simply providing "insurance." Cash deposits/withdraws or not. For instance, it says on their website that they also handle investment packages. Like brokerage accounts, 401Ks, mutual funds, and educational savings accounts. None of those are related to insurance. 

So, in my opinion this would best be kept tagged as a bank and maybe create something like an insurance=yes tag to designate that it also provides those services. It's clearly not it's main thing though.

**Comment by Adamant36** [comment]
Btw, there's also a office=financial tag. Although, I don't know if it would be appropriate in this situation.

**Comment by bhousel** [comment]
Now that we support `office` (see #2634), we are matching AXA as an `office=insurance` too.  This is probably the most correct tagging.

I also left it in `amenity=bank` since the situation is unclear, then mappers can still call it a bank if the want to.  And I removed the countryCodes, since it appears to operate [nearly worldwide](https://en.wikipedia.org/wiki/AXA#/media/File:AXA_Group_Global_Locations.svg).
