### ISSUE TITLE
Юлия - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2579]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused for example by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
````
{
  "count": 68,
  "countryCodes": [
    "bg"
  ],
  "tags": {
    "brand": "Юлия",
    "name": "Юлия",
    "shop": "convenience"
  },
}
````

Country codes declared in name-suggestion-index:
* bg - 0 mapped entries

Additional countries with object of matching name and type mapped in OSM
ru - 140 mapped entries
ua - 17 mapped entries
kz - 5 mapped entries
by - 4 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
'shop'='convenience' and name='Юлия' global

examples are listed below:
this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/403905201

this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/861919986

this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/920485175

this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/947046966

this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/1125026375

this is in country with code 'ru', according to name index present nearly not present outside ["bg"]
https://www.openstreetmap.org/node/1157336589

**Comment by matkoniecz** [comment]
Calling @DmitriiKh as Russia expert and @StheffanyHadlich as it was added in https://github.com/osmlab/name-suggestion-index/commit/ace2445086e6547d57e70471f7839ab7b610e2fa

**Comment by DmitriiKh** [comment]
It looks like 'Юлия' is not a registered brand name in Russia. All pictures of shops with this name have no common style. I'm not so sure about 'bg' (is it for Bulgaria?)
I'm suggesting removing the entry.
