### ISSUE TITLE
Кировский - is it shop=convenience or shop=supermarket? (Russia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2584]
* is shop=convenience sometimes preferable tagging for Кировский?
* is shop=supermarket sometimes preferable tagging for Кировский?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like shop=bakery name=Bakery) rather than a brand?

ping local expert: @DmitriiKh

**Comment by DmitriiKh** [comment]
It looks like the preferable tagging should be shop=supermarket.
There are 172 stores in this chain located at Sverdlovsk area.
Q63301903 - Wikidata
https://ru.wikipedia.org/wiki/Кировский_(группа_компаний)

**Comment by matkoniecz** [comment]
Thanks!

**Comment by DmitriiKh** [comment]
No problem
