### ISSUE TITLE
Add entry for: SECU

### ISSUE THREAD

**Issue by rivermont** [osmlab/name-suggestion-index#2585]
`amenity=bank`  
`building=yes`  
Name could be "SECU" or "State Employees Credit Union".  
[website](https://www.ncsecu.org)  
[Wikipedia](https://en.wikipedia.org/wiki/State_Employees_Credit_Union)

**Comment by Adamant36** [comment]
Hi there. "building=yes" isn't necessary. It's not used in the index and sometimes businesses are mapped as nodes anyway. Neither is the businesses website. as the index really doesn't do websites. Thanks.

**Comment by patrick-salvatore** [comment]
Hello, I'd like to contribute to this. May I?

**Comment by Adamant36** [comment]
Sure. Go for it. If you need any help, feel free to ask. There's also a guide in the contributing file https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md

**Comment by Adamant36** [comment]
Closed in #2790
