### ISSUE TITLE
Мария-Ра - is it shop=convenience or shop=supermarket? (Russia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2589]
* is shop=convenience sometimes preferable tagging for Мария-Ра?
* is shop=supermarket sometimes preferable tagging for Мария-Ра?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

This brand may be described at https://ru.wikipedia.org/wiki/Мария-Ра

summoning Russia expert: @DmitriiKh

**Comment by DmitriiKh** [comment]
From what I see on Yandex pictures it should be supermarkets. Also it's a
chain not a generic name.
I am gonna check wikidata later today.

**Comment by DmitriiKh** [comment]
(Q4281631) looks okay to me

**Comment by matkoniecz** [comment]
Google translate on Wikipedia article gives

> In the future, “Maria-Ra” opens only self-service stores, the main format of which is “convenience store”.

so probably both may be correct depending on a shop. Thanks for identifying the match! At this moment I am planning to mark that both versions may be correct depending on a location.

**Comment by DmitriiKh** [comment]
The chain website gives number of merchandises for each store. It's 4000 per a store at least. The convenience stores I saw were a little bit smaller.
Nevertheless, the both tags together would work okay I think.
