### ISSUE TITLE
Research needed for: amenity/bank|Fidelity Bank

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#259]
#### :thinking: We need help deciding what to do with "amenity/bank|Fidelity Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Fidelity Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Fidelity Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Fidelity Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by mds08011** [comment]
Needs to be clarified.  There is [Fidelity Investments](https://en.wikipedia.org/wiki/Fidelity_Investments) with multiple subsidiaries in the USA, but also the unrelated [Fidelity Bank Ghana](https://en.wikipedia.org/wiki/Fidelity_Bank_Ghana), and [Fidelity Bank Nigeria](https://en.wikipedia.org/wiki/Fidelity_Bank_Nigeria).  All separate businesses.
