### ISSUE TITLE
Гроздь - is it shop=convenience or shop=supermarket? (Russia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2590]
* is shop=convenience sometimes preferable tagging for Гроздь?
* is shop=supermarket sometimes preferable tagging for Гроздь?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

summoning Russia expert: @DmitriiKh

**Comment by DmitriiKh** [comment]
It's a shop=convenience. Also it's a retail chain at Saratov area in Russia.
Q21638412
https://ru.wikipedia.org/wiki/Гроздь_(сеть_магазинов)

>

**Comment by matkoniecz** [comment]
Google translates its wikipedia entry as

> As of March 6, 2015, the Grazd network consisted of about 240 stores in the “convenience store” format, as well as in the supermarket format (20 stores) and a supermarket (2 stores) located in 25 cities of the Saratov region and the Volga region.

What would indicate that both `shop=convenience` and `shop=supermarket` may be valid, depending on location.

Are you sure that `shop=convenience` is always preferable?

**Comment by DmitriiKh** [comment]
I agree. The both tag would be preferable if it's possible.
I made my opinion looking at Yandex pictures. All of the stores were quite small there.
