### ISSUE TITLE
Верный - is it shop=convenience or shop=supermarket? (Russia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2591]
* is shop=convenience sometimes preferable tagging for Верный?
* is shop=supermarket sometimes preferable tagging for Верный?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

summoning Russia experts: @DmitriiKh @tohaklim

**Comment by matkoniecz** [comment]
summoning @tohaklim

**Comment by tohaklim** [comment]
I haven’t seen these in the wild, so might defer to locals. 
Based on their website and photos, you can’t say for sure whether it would be a supermarket or convenience. 
It certainly is a brand though

**Comment by bhousel** [comment]
Closing, since this has no wikidata anyway..
