### ISSUE TITLE
major mismatches

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2593]
`npm run wikicheck` reports

Warning - Wrong Wikipedia article which is not linked to the Wikidata entity:
To resolve these, check whether the Wikidata or the Wikipedia value is wrong and correct one of them

<s>amenity/bank|Ibercaja: Q5907815 (brand:wikidata) is not linked to es:Ibercaja Banco but to es:Ibercaja</s> - fixed!

shop/shoes|André: Q2847114 (brand:wikidata) is not linked to fr:André (chaussure) but to fr:Exand Holding (ex Chaussures André)

**Comment by bhousel** [comment]
> shop/shoes|André: Q2847114 (brand:wikidata) is not linked to fr:André (chaussure) but to fr:Exand Holding (ex Chaussures André)

This has been fixed as of May 14..
