### ISSUE TITLE
ケーズデンキ - is it shop=appliance or shop=electronics? (Japan)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2594]
* is shop=appliance sometimes preferable tagging for ケーズデンキ?
* is shop=electronics sometimes preferable tagging for ケーズデンキ?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

This brand may be described at https://ja.wikipedia.org/wiki/ケーズホールディングス

ping local expert @johachi

**Comment by johachi** [comment]
ケーズデンキ if translated literary would be "K's electronics", and is a store chain. 

They do sell appliances (refrigerators, washing machines, rice cookers, AC, vacuum cleaners etc.) **BUT** they do also sell electronics such as computers, routers, TV's, Audio equipments, HDD, keyboards, etc. All the stores (that I know of) are of equal size and offering, and should have the same tag.

The absolute best would be if it is possible to have both tags. Is that an option?

**Comment by matkoniecz** [comment]
> The absolute best would be if it is possible to have both tags. Is that an option?

Proposed by name-suggestion-index, with user selecting one? Yes.

On the same object - no, as both `shop=appliance` and `shop=electronics` is using the same key (and multiple values in a shop type like `shop=electronics;appliance` is rather a poor idea)

**Comment by bhousel** [comment]
Looking at the pics, and from @johachi's description I think this one can just be `shop=electronics`

**Comment by johachi** [comment]
Yes, if only one key is to prefer / is possible, the `shop=electronics` is the better option.
