### ISSUE TITLE
Белсоюзпечать - is it shop=kiosk or shop=newsagent? (Belarus)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2595]
* is shop=kiosk sometimes preferable tagging for Белсоюзпечать?
* is shop=newsagent sometimes preferable tagging for Белсоюзпечать?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is a generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

pinging @tohaklim

Based on results in https://duckduckgo.com/?q=%D0%91%D0%B5%D0%BB%D1%81%D0%BE%D1%8E%D0%B7%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D1%8C&t=canonical&ia=webI would guess `shop=newsagent` but it is not a strong hint.

**Comment by tohaklim** [comment]
shop=kiosk is quite catch all. Can't tell you a hard and fast rule, but newsagent is probably a better fit for most locations I've seen. 
It's a country-wide name, that sometimes comes up in regional flavours (substitute Бел for %regionname%-"obl (short for oblast', lit. region). I think one of them was already in the index.

**Comment by tohaklim** [comment]
see also index/issues/1565[https://github.com/osmlab/name-suggestion-index/issues/1565](url)

**Comment by matkoniecz** [comment]
I consulted with someone from Belarus with conclusion that `shop=newsagent` is preferable and that Russian name is incorrectly used here.

**Comment by tohaklim** [comment]
Um, both Белсоюзпечать and Витебскоблсоюзпечать seem to be incorrectly matched to Q4430611, which is about the now defunct Soviet parent and predecessor of these entities. 
How about replacing it with Q63986228?

**Comment by tohaklim** [comment]
They also seem to be (slowly) trying to rebrand using a shortened be version of the name - БелДрук http://beldruk.by/
