### ISSUE TITLE
Include some discarded brands

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2598]
Sometimes I look through `dist/names_discard.json` to see if we are missing anything important.

Looks like we can include some branded dental clinics:
```
  "amenity/dentist|Aspen Dental": 124,
  "amenity/dentist|Cabinet Dentaire": 53,
  "amenity/dentist|Cabinet dentaire": 63,
  "amenity/dentist|Consultorio Dental": 214,
  "amenity/dentist|Consultorio Odontologico": 58,
  "amenity/dentist|Dentix": 77,
  "amenity/dentist|Family Dentistry": 96,
  "amenity/dentist|Gentle Dental": 59,
  "amenity/dentist|Vitaldent": 64,
  "amenity/dentist|Zahnarzt": 75,
```

Also this money transfer brand:
```
  "shop/money_transfer|Orange Money": 325,
```

**Comment by matkoniecz** [comment]
>   "amenity/dentist|Zahnarzt": 75,

Looks like generic German word for a dentist to me, https://de.wikipedia.org/wiki/Zahnarzt confirms

>  "amenity/dentist|Cabinet Dentaire": 53,
>  "amenity/dentist|Cabinet dentaire": 63,

The same in French - see https://www.wordhippo.com/what-is/the-meaning-of/french-word-cabinet_dentaire.html

**Comment by matkoniecz** [comment]
>   "shop/money_transfer|Orange Money": 325,

Covered by match in amenity/money_transfer|Orange Money

**Comment by bmillemathias** [comment]
> > "amenity/dentist|Cabinet Dentaire": 53,
> > "amenity/dentist|Cabinet dentaire": 63,
> 
> The same in French - see https://www.wordhippo.com/what-is/the-meaning-of/french-word-cabinet_dentaire.html

I confirm this is a generic term for dentist.
