### ISSUE TITLE
日高屋 - is it amenity=fast_food or amenity=restaurant? (Japan)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2599]
* is amenity=fast_food sometimes preferable tagging for 日高屋?
* is amenity=restaurant sometimes preferable tagging for 日高屋?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

This brand may be described at https://ja.wikipedia.org/wiki/ハイデイ日高 (google translate confirms that it is a brand and suggest `amenity=fast_food` though maybe it can be considered as a cheap restaurant? it mentions that opening of restaurants is also planned - maybe it already happened?)

summoning @johachi to get info a about Japan

**Comment by johachi** [comment]
It's a "fast food restaurant", so please tag it as `fast_food`.

**Comment by matkoniecz** [comment]
Thanks! I moved suggested tag for 日高屋 `amenity=restaurant` to `amenity=fast_food`.

**Comment by Adamant36** [comment]
Could be `cuisine=ramen` since it's a ramen place.
