### ISSUE TITLE
Research needed for: amenity/bank|First Bank

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#260]
#### :thinking: We need help deciding what to do with "amenity/bank|First Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|First Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|First Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|First Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bonbon12** [comment]
Researching this issue I found this Wiki: [https://en.wikipedia.org/wiki/FirstBank_Holding_Co](url), which directly links the website: [https://www.efirstbank.com/](url). On the wiki and website it seems that it's also known as 1stbank, possibly a nickname, should that also be added in?

Also another question, cloning the repo i cannot see cannonical.json in my config folder, assuming its auto generated, so i just want to change the bank.json folder and submit a PR from there?

**Comment by SilentSpike** [comment]
You're right about just editing the `bank.json` file, `cannonical.json` was recently split into the `brands/` directory structure you see now as it was getting very long.


I can't speak too much on the First Bank information, would be tempted to add `1STBank` as `short_name`. Also looks to me like perhaps the `name` should be `FirstBank` and not `First Bank`.

**Comment by bonbon12** [comment]
>Also looks to me like perhaps the name should be FirstBank and not First Bank.
In regards to this, the website and wiki directly has this as the name, so i thought i'd leave it like that.
>would be tempted to add 1STBank as short_name
Can do that!

**Comment by SilentSpike** [comment]
I can't decide if `short_name` is appropriate though, `alt_name` might be a better fit

**Comment by Adamant36** [comment]
I think the way it was decided in another issue was that the long name would be "official_name" and the shortened version of the name is the brand/name tags. There's also "operator." That's how we are doing it now. One of those three should be sufficient. @bhousel understandably doesn't want to introduce a bunch of alternative name tags into the index. 

In my personal opinion both short_name and alt_name are bad tags compared to official_name + name anyway.  Like alt_name is to colloquial for my taste. Short name to a lesser degree, but it has its own problems (like the risk of arbitrarily using it to shorten long names by random people that don't like them. Which I have seen happen).
