### ISSUE TITLE
reviewing popular restaurant names in Japan

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2601]
`amenity=restaurant name=木曽路`
`amenity=restaurant name=ステーキガスト`
`amenity=restaurant name=和食さと`
`amenity=restaurant name=夢庵`

For each one it would be useful to know:
Is it an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

-----

Following is based on googling and automatic translation:

It seems that all four are real brands.

For the first one (`amenity=restaurant name=木曽路`) https://ja.wikipedia.org/wiki/%E6%9C%A8%E6%9B%BD%E8%B7%AF_(%E4%BC%81%E6%A5%AD) looks correct based on a Google translate.

For the second (`amenity=restaurant name=ステーキガスト`) https://ja.wikipedia.org/wiki/%E3%81%99%E3%81%8B%E3%81%84%E3%82%89%E3%83%BC%E3%81%8F#%E5%BA%97%E8%88%97%E6%A5%AD%E6%85%8B seems to be a good fit.

For the third (`amenity=restaurant name=和食さと`) it seems that there is no entry about brand itself but to mark it as a real one linking https://ja.wikipedia.org/wiki/SRS%E3%83%9B%E3%83%BC%E3%83%AB%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B9 - its owner - may be a good solution.

The same for the fourth one (`amenity=restaurant name=夢庵`) - https://ja.wikipedia.org/wiki/%E3%81%99%E3%81%8B%E3%81%84%E3%82%89%E3%83%BC%E3%81%8F#%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E3%81%99%E3%81%8B%E3%81%84%E3%82%89%E3%83%BC%E3%81%8F%E3%81%AE%E9%81%8B%E5%96%B6%E3%81%99%E3%82%8B%E3%83%81%E3%82%A7%E3%83%BC%E3%83%B3%E5%BA%97 seems to be the closest one and good enough to mark it as a valid brand.

summoning @johachi to get info a about Japan and to review potential mistakes

**Comment by johachi** [comment]
All four are valid brands. 

Unless cuisine is already entered for the restaurants, 夢庵 and 木曽路 and 和食さと should be Japanese. ステーキガスト should be Steak.

The Wikipedia links are good. A lot of Japanese restaurants do not have their own Wikipedia page. But instead share / are mentioned on their parent companies page.

**Comment by matkoniecz** [comment]
> Steak

Currently it has `japanese;western`. Do you think that `steak` would be better?

**Comment by johachi** [comment]
> Currently it has `japanese;western`. Do you think that `steak` would be better?

It's a steak house with western and japanese steak. I think I added the `japanese;western`. But since we wanted to avoid the `western` cuisine when there are better cuisine, maybe changing it would be good.
