### ISSUE TITLE
detect links to Wikidata items at risk of being deleted due to missing P31 property and not linked to any Wikipedia article

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2603]
Potential continuation of https://github.com/osmlab/name-suggestion-index/pull/2538 by @ENT8R 

It would be useful to add check listing Wikidata entries used in the index that are at risk of being deleted.

Items without link to Wikipedia article and without [P31 property](https://www.wikidata.org/wiki/Property:P31) may be deleted, see https://www.wikidata.org/w/index.php?title=Wikidata:Administrators%27_noticeboard&diff=prev&oldid=935716550 (Identification part)

There are also some minimal requirements for third-party sources, especially for companies and I trying to establish what is the minimum necessary to deletproof entries. Once I will get that info I will make a new issue to cover that.

**Comment by Adamant36** [comment]
@matkoniecz, here's an example of a foreign company with a Library of Congress authority ID. It also has a bunch of other identifiers besides that. It might be worth keeping a running list. As the more the better in my opinion.

**Comment by SilentSpike** [comment]
In the UK there is also companies house https://beta.companieshouse.gov.uk

**Comment by matkoniecz** [comment]
> @matkoniecz, here's an example of a foreign company with a Library of Congress authority ID. It also has a bunch of other identifiers besides that. It might be worth keeping a running list. As the more the better in my opinion.

? It seems that link is missing, it also seems to be posted in a wrong issue

**Comment by ENT8R** [comment]
> Items without link to Wikipedia article

That would be quite a lot of Wikidata entries which don't fit this requirement. According to my own experience, I would say that the `P31` claim is probably the most important claim and if an entry has this claim, the risk of it being deleted is very low.

> without P31 property

That's a very good way to find potential deletion candidates. I'm currently working on improving the wikicheck script to add another check for missing claims like P31

**Comment by matkoniecz** [comment]
@ENT8R I though about listing entries without P31 and without Wikipedia link as "linked to Wikipedia article" makes it ineligible for a deletion, even if items is completely empty.

**Comment by ENT8R** [comment]
Ah okay, so both conditions should be true...

**Comment by matkoniecz** [comment]
> I'm currently working on improving the wikicheck script to add another check for missing claims like P31

Great! Are you potentially interested in adding also #2604 check?

**Comment by ENT8R** [comment]
Yes, I will do both!

**Comment by Adamant36** [comment]
> ? It seems that link is missing, it also seems to be posted in a wrong issue

My bad. I added it to the original comment. Also, I figured the issues were related enough for it not being a problem posting it here.
