### ISSUE TITLE
Wikidata items at risk of being deleted due to missing third-party references (shop=clothes entry only)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2608]
Part of `npm run wikicheck` output waiting for fixes.

```shop/clothes|Armani Exchange: Q56045740 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Catherines: Q64026208 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|DXL Men's Apparel: Q61981830 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Loft: Q62075137 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Madewell: Q64026213 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Only: Q61799370 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Plato's Closet: Q61779112 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Sela: Q62075111 (brand:wikidata) is missing a sitelink and a reference
shop/clothes|Street One: Q61997265 (brand:wikidata) is missing a sitelink and a reference
```

See https://www.wikidata.org/wiki/Q60097339 for an example of item with external reference (for fact that it has 158 restaurants).

See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#adding-references-to-wikidata for explanation how one may add such references.

EDIT: removed two fixed, thanks to @bmillemathias

**Comment by tas50** [comment]
A good chunk of those are mine. I'll go expand them

**Comment by matkoniecz** [comment]
> I'll go expand them

Please comment here once part (or all of them) are fixed, I will close this issue and create a new one.

**Comment by matkoniecz** [comment]
After processing this group of entries we should request undeletion of `shop/supermarket|Виталюр: Q55663075 (brand:wikidata) does not exist` ( https://www.wikidata.org/w/index.php?title=Special:Log&page=Q55663075 )

**Comment by bmillemathias** [comment]
as I created some of them, could you explain what is to fix?

**Comment by matkoniecz** [comment]
Should be covered by https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#adding-references-to-wikidata (if anything is unlear or missing, let me know - I added this section recently).

**Comment by bmillemathias** [comment]
Added ref for Cache-Cache and Caroll

**Comment by matkoniecz** [comment]
I updated the list, thanks!

**Comment by bhousel** [comment]
Wikidata items getting deleted is still a real problem for us.  We've added the external NSI identifiers to Wikidata, but admins there still occasionally remove our items.  Discussion has moved to #4648 lately.
