### ISSUE TITLE
Research needed for: amenity/bank|First National Bank

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#261]
#### :thinking: We need help deciding what to do with "amenity/bank|First National Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|First National Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|First National Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|First National Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bonbon12** [comment]
Hello! May I attempt to resolve this?

**Comment by Adamant36** [comment]
Go for it. You don't need permission ;) The contributing file says how to do things. In case you don't know.

**Comment by tas50** [comment]
Closed by #2332
