### ISSUE TITLE
Ignore historical logos in Wikidata

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#2614]
[The Wikidata item for Popeyes](https://www.wikidata.org/wiki/Q1330910#P154) has a logo statement, but that statement has an [end time](https://www.wikidata.org/wiki/Property:P582) qualifier saying that the brand stopped using that logo in 2008. The index should omit historical logos in favor of other, more current statements in the Wikidata item.

I just added the current logo to the Wikidata item. A Wikidata constraint detected that there were multiple logo statements and forced me to mark the current logo as having “preferred” rank. So that’s another way to ensure that we’re pulling in the current logo.

**Comment by 1ec5** [comment]
[Wendy’s](https://www.wikidata.org/wiki/Q550258) is another example. In this case, no Commons image is available to serve as a current logo, so the constraint doesn’t apply and the rank doesn’t identify the statement as being outdated. The qualifier is the only way to determine that the logo should be omitted.

**Comment by bhousel** [comment]
> A Wikidata constraint detected that there were multiple logo statements and forced me to mark the current logo as having “preferred” rank. So that’s another way to ensure that we’re pulling in the current logo.

Yes, when choosing a claim value, we are already skipping "deprecated" and prioritizing "preferred" ranked..  I was hoping that might be sufficient enough for our purposes?

https://github.com/osmlab/name-suggestion-index/blob/2b70a7241cd92bf469ead75698145dc5d17a0ba4/build_wikidata.js#L179-L187

**Comment by 1ec5** [comment]
That’s good enough for items that have multiple logo statements, because the constraint requires one of them to be preferred. However, in the case of Wendy’s (and previously Popeyes), there’s only a single statement with historical qualifiers, so the rank is normal.

**Comment by bhousel** [comment]
> However, in the case of Wendy’s (and previously Popeyes), there’s only a single statement with historical qualifiers, so the rank is normal.

Ok, I did the thing in  5821c3e
