### ISSUE TITLE
branch tag

### ISSUE THREAD

**Issue by HubMiner** [osmlab/name-suggestion-index#2618]
Common brand names presets should show field for "branch" tag, to encourage editors to identify and record location of that instance.

Goal is that end users searching for a common place will see branch identifiers next to names (perhaps a future request to OsmAnd, etc).

https://wiki.openstreetmap.org/wiki/Key%3Abranch
https://taginfo.openstreetmap.org/keys/branch#overview

(Please move this issue to correct ID related project, if this is not it)

**Comment by matkoniecz** [comment]
In this project we may add tags that apply to all locations - tags as in "key with value", rather than "all useful tags that would be nice to have filled" what is job for preset editors

> to encourage editors to identify and record location of that instance.

Location is already added by mapping point/area at a specific location.

**Comment by matkoniecz** [comment]
I closed as it is impossible to add here. If you think that `branch` tag makes sense I would advise you to add some example at https://wiki.openstreetmap.org/wiki/Key%3Abranch

At taginfo I see tagging that should be done using `brand` tag.

And in cases where individual shops/amenities have individual names - it should be probably put into `name` tag. See also #2475 and #2610 for what seems related.

**Comment by Adamant36** [comment]
From looking at TagInfo the vast majority of it's use is on Russian named places. I'm not sure exactly what to make of it, but it does make me specious of the tag that it has 102,210 uses at the same time as having no apparent wider appeal then Russian. It just seems a little to niche or something. I'm not sure why though.
