### ISSUE TITLE
create wikidata item for name-suggestion-index itself and add it to items used by us

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2620]
Based on [Wikidata discussion](https://www.wikidata.org/w/index.php?title=Wikidata:Administrators%27_noticeboard&diff=941582891&oldid=941573611#Please_undelete_this_entries_about_brands) - it appears that it may help making wikidata entries used by us less likely to be suddenly deleted and distinguish them from spam

As first step it would be necessary to create Wikidata entry about NSI itself and mention it in the linked discussion. I plan to do this, but I am unsure when I will do that - if someone creates proper Wikidata entry, please link it here and I will push that discussion forward.

> I don't really understand what this "OSM lab name suggestion index" really is. Would it be appropriate to consider it a work by its own which deserves an item? It could then perhaps be used with stated in (P248) in references, or as main value with described by source (P1343). I am not yet sure about that, however.

> In my opinion, the "name suggestion index" should have a separate item. Can you please create one and link it from here? We could then use it in references with the [[Help:Sources#Web page|web page]] source model (carefully, e.g. only on P31 claims). —[[User:MisterSynergy|MisterSynergy]]

https://www.wikidata.org/w/index.php?title=Wikidata:Administrators%27_noticeboard&diff=941582891&oldid=941573611

**Comment by Adamant36** [comment]
This would be a cool idea. Although, we would have to be sure to remove the wiki reference if the brand it's attached to is deleted from the index.

**Comment by 1ec5** [comment]
@ArloJamesBarnes created [Q62108705](https://www.wikidata.org/wiki/Q62108705) for NSI a while back. There’s even a bot that automatically updates it whenever we publish a new release.

**Comment by SilentSpike** [comment]
I personally don't think it's a good idea to try and use NSI as a source, but can't eloquently explain why currently (it feels like bootstrapping notability). If you're able to find information on a brand/company, then why not just add the sources you used directly?

However, there are potentially other ways the NSI item could be linked to brand items via a property.

**Comment by 1ec5** [comment]
I think it would be more natural to use NSI as a source of external identifiers. For example, [Q38076](https://www.wikidata.org/wiki/Q38076) could claim a “name-suggestion-index ID” of `amenity/fast_food=McDonald's`, which could automatically link to [its entry in the name-suggestion-index](http://osmlab.github.io/name-suggestion-index/brands/amenity/fast_food.html#amenityfast_foodmcdonalds). There’s some precedent for ad-hoc identifiers like this, such as [Flags of the World ID](https://www.wikidata.org/wiki/Property:P3089). I’m pretty sure FOTW never thought of its URL slugs as being database identifiers in their own right.

**Comment by matkoniecz** [comment]
> @ArloJamesBarnes created Q62108705 for NSI a while back.

Thanks! Creating this issue instead of making entry turned out smarter than expected :)

> However, there are potentially other ways the NSI item could be linked to brand items via a property.

Yes, I initially though about something like "this property is used externally in XYZ" but I am unsure is it something that is done in Wikidata.

**Comment by SilentSpike** [comment]
An external identifier property is the closest thing to that, however I don't know whether the NSI warrants one. It's not really an authoritative source of information, just a collection of data from other sources.

**Comment by ArloJamesBarnes** [comment]
It's an authority within the context of iD/OSM. There are plenty of secondary/tertiary source identifiers already on WD; since they act in concert and are not sources but rather indicators that "these people are interested in this thing enough to give it an identifier", there is no pressure to select the One True Authority Record (the Qnumber is that for Wikidata).

**Comment by bhousel** [comment]
I never really intended the NSI keys to be stable.  

The keys themselves are made up like:
`k/v|n~d`
`key/value|Name~Disambiguator`

And all of those things can change for whatever reason.  Either because OSM decides they want to change the best practice tagging of a thing, or because the brand decides to change their name, or because a same-name brand is established somewhere and we need to disambiguate them.  

So I am kind of wary of using these things as an identifier elsewhere.

**Comment by ArloJamesBarnes** [comment]
If NSI updates, it seems like it would be straightforward to change the Wikidata pointer at the same time. Or is there something I am not considering?

**Comment by bhousel** [comment]
> If NSI updates, it seems like it would be straightforward to change the Wikidata pointer at the same time. Or is there something I am not considering?

This doesn't seem straightforward to me.  The mappings aren't even 1:1   (see #2787 - we have multiple NSI keys that point to a single Wikidata QID, e.g. Walmart Market / Walmert Supercenter / plain Walmart).

I don't really want to work on it, but if somebody else wants to do the work, I'm ok with it.  Going to close for now.

**Comment by 1ec5** [comment]
A Wikidata administrator [brought up the idea of an external identifier property](https://www.wikidata.org/wiki/Wikidata:Administrators'_noticeboard#Undelete_items_used_by_name-suggestion-index), in the context of another item that got deleted, so I [started a proposal](https://www.wikidata.org/wiki/Wikidata:Property_proposal/name-suggestion-index_identifier) for an NSI ID property to add to these items. I’d appreciate it if folks familiar with Wikidata could review my proposal for mistakes.
