### ISSUE TITLE
Add Bruegger's Bagels, bagel restaurant

### ISSUE THREAD

**Issue by BjornRasmussen** [osmlab/name-suggestion-index#2622]
https://en.wikipedia.org/wiki/Bruegger's 
https://www.wikidata.org/wiki/Q4978656

**Comment by matkoniecz** [comment]
What is the preferred tagging? `amenity=cafe` or `amenity=restaurant` or maybe `amenity=fast_food`? (I know that `restaurant` is in the title, but OSM tags are sometimes a bit tricky)

http://overpass-turbo.eu/s/J7p

**Comment by BjornRasmussen** [comment]
Well, it has more of a feel of a restaurant based on what I can see from the outside (I've never been in one).  `amenity=restaurant` seems accurate, because of the style of the stores. 
There isn't a perfect match here unfortunately.

**Comment by bhousel** [comment]
If people wait on you it's `amenity=restaurant`... If they don't it's `amenity=fast_food`
`amenity=cafe` is really for coffee houses.

HTH

**Comment by bhousel** [comment]
Also, Wikipedia calls it a "fast casual" which in OSM means `amenity=fast_food`. 
These are places where you order from a counter and seat yourself (Panera Bread is a similar example).

**Comment by iandees** [comment]
Yep, definitely fast food. Some branches are small enough that they might be called a cafe (i.e. they're primarily coffee and the bagels part is less important), but in general it's more fast food than restaurant.

**Comment by BjornRasmussen** [comment]
Sounds good!

**Comment by 1ec5** [comment]
Oops, I added Bruegger’s in 46a822c7e46670234e4e67be3fb6589cc6ee0cd5 without noticing this issue. It’s definitely `fast_food`, not even fast-casual.

**Comment by matkoniecz** [comment]
Is it maybe `name=Bruegger’s official_name=Bruegger's Bagels`?

**Comment by 1ec5** [comment]
The company’s name is Bruegger’s, but the restaurants I’ve been to are always signposted as Bruegger’s Bagels, with the “Bagels” set in the same type as the “Bruegger’s”.
