### ISSUE TITLE
Add Roses, department store

### ISSUE THREAD

**Issue by BjornRasmussen** [osmlab/name-suggestion-index#2623]
https://en.wikipedia.org/wiki/Roses_(store)
https://www.wikidata.org/wiki/Q7368644

**Comment by matkoniecz** [comment]
`shop=variety_store` is also quite popular - is `shop=department_store` always preferable? 

http://overpass-turbo.eu/s/J7q

**Comment by BjornRasmussen** [comment]
`variety_store` actually seems much more accurate.
