### ISSUE TITLE
shop|hairdresser|Haarwerk : remove brand

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/name-suggestion-index#2625]
NSI suggests to tag some hairdressers called "Haarwerk" under the brand umbrella "Haarwerk". This is not correct, there's no such brand as "Haarwerk". All hairdressers are privately owned and don't belong to any brand. I'd suggest to simply remove the "brand" tag.

http://osmlab.github.io/name-suggestion-index/brands/shop/hairdresser.html#shophairdresserhaarwerk

https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/hairdresser.json#L72-L77

**Comment by matkoniecz** [comment]
Haarwerk - is it a popular name without uniting brand or is it an unwanted descriptive name like `name=hairdresser`?

> NSI suggests to tag some hairdressers called "Haarwerk" under the brand umbrella "Haarwerk"

Note that this is fortunately not true - as `brand:wikidata` is missing it is not appearing in list of  suggestion in iD/Vespucci/other users. Still, it is a very useful and welcomed issue as nobody will waste time on hunting down nonexisting brand!

**Comment by mmd-osm** [comment]
I haven’t really checked how popular this name is compared to other hairdressers‘ names. Haarwerk translates to something like a hair factory, so this isn’t strictly a descriptive name. I would be ok removing it altogether, too.
