### ISSUE TITLE
Support `office` toplevel key

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2634]
@1ec5 started adding some reasonable `office/*` entries to the index in #2627 and #2629 - Thanks!

We should add support for the `office` key to the scripts that process the planet and filter the names.

codepoints here:

https://github.com/osmlab/name-suggestion-index/blob/94f1fab6d04ca4c4f3f23fd66896b9c8d41813d6/build_all_names.js#L26

https://github.com/osmlab/name-suggestion-index/blob/94f1fab6d04ca4c4f3f23fd66896b9c8d41813d6/config/filters.json#L2-L27

Also need to update CONTRIBUTING.md and README.md (including the section with the `osmium` command).

**Comment by 1ec5** [comment]
Not sure if it matters, but `office=company` and some other `office` tags are used for the headquarters and field offices of companies that own brands. For example, a bank’s headquarters or regional headquarters would be tagged `office=financial`; it would only be tagged `amenity=bank` if there also happens to be a bank branch there.

**Comment by bhousel** [comment]
> Not sure if it matters, but `office=company` and some other `office` tags are used for the headquarters and field offices of companies that own brands. For example, a bank’s headquarters or regional headquarters would be tagged `office=financial`; it would only be tagged `amenity=bank` if there also happens to be a bank branch there.

We'd probably only notice this if a company had >50 `office=company` in OSM.  Some maybe do, and I guess that's ok.

**Comment by tas50** [comment]
Perhaps it's just me, but in the past when I've added office things have just spun forever when generating the names file.

**Comment by matkoniecz** [comment]
@bhousel Is it now fixed? #2685 was merged

**Comment by bhousel** [comment]
> @bhousel Is it now fixed? #2685 was merged

From what @tas50 said above, I don't think anyone has successfully processed a planet file with offices yet.

**Comment by bhousel** [comment]
This was done today!
