### ISSUE TITLE
Vue has multiple brands and brand Vue is present in less areas than index claims

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2637]
For example  brand "Vue" is not present in Poland at all (this one was fixed in https://github.com/osmlab/name-suggestion-index/commit/0a74f49f61846ef5aa0da332929082156c1d0d19 )

But the same is true also for other markets - see for example http://vue-international.com/index.php/our-markets/taiwan

Note to self: after this is fixed remove `Vue` from manual_name_skip in my validator script.

**Comment by SilentSpike** [comment]
Ah thank you, I didn't come across that section of their website in my searching. I just got the countries from wikipedia.

**Comment by SilentSpike** [comment]
Should be fixed by 96a2156757139acb092200d371d2ec0faf5a3a59, 0356665edf1d4d52e10641e1c0c9b55d2afdf772, fd7ab18b4e08bcdf08e63f1b20beb19d0c764e46 and d614a7e4fb2879cdc4e64ecdd9a47a6721202a28

I didn't add the Taiwanese brand SBC because it looks like it's only a single cinema

**Comment by matkoniecz** [comment]
In that case: closing and thanks for fixing!
