### ISSUE TITLE
Research needed for: amenity/bank|HSBC

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#264]
#### :thinking: We need help deciding what to do with "amenity/bank|HSBC"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|HSBC` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|HSBC`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|HSBC`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by SK53** [comment]
HSBC retail (consumer) banks: in the UK have been re-named as "HSBC UK". I suspect HSBC as the brand is still entirely valid. This name change signals a clear separation of consumer customer liabilities from those of the holding company. I'm not sure if HSBC operations in other countries have similar identities yet on the high street. (Note, do we have any view of organisations with entirely different names, but sharing an obvious brand identify, e.g., the former Midland Bank traded under that name using the HSBC logo for a while).
