### ISSUE TITLE
Indicate whether Wikimedia Commons image is usable and preferred

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#2641]
iD needs to know whether the Wikimedia Commons image in a Wikidata item’s logo claim is usable as a preset icon. iD would then prefer that image over any social media icon for the brand. openstreetmap/iD#6361 proposes two factors for determining whether the image is usable: it must be in SVG format and it must be a reasonable aspect ratio, not necessarily square but squarish.

The Wikidata item only indicates the image’s file name, but the dimensions can change any time someone uploads a new version of the file to Commons. So instead of storing the dimensions, the index should store a Boolean indicating whether the Commons image is usable (and thus preferred). This would ensure that, even if iD is working off an outdated image between releases, the logo would be nonsquare but undistorted.

Currently, the index gets the Wikidata statement’s file name and fashions a Special:Redirect URL from it. Special:Redirect is handy if all you need is the URL, but we need metadata in addition to the URL.

https://github.com/osmlab/name-suggestion-index/blob/e87db9f2de44cc882dded1b08518c2a85d6d4765/build_wikidata.js#L134-L138

[This Wikimedia Commons API request](https://www.wikidata.org/wiki/Special:ApiSandbox#action=query&format=json&prop=imageinfo&titles=File%3AAbercrombie%20%26%20Fitch%20logo.svg|File%3AMonsoon%20accessorize%20logo.svg|File%3AAckermans-Logo.jpg|File%3AAeropostale%20logo.svg|File%3AAmerican%20Eagle%20Outfitters%20text%20logo.svg|File%3AAnthropologieLogo.png|File%3AArdene%20logo.png|File%3ABanana%20Republic%20logo.png|File%3ABershka%20logo.svg|File%3ABig%20Star%20logo.svg|File%3ABonobos%20LogoGrey%20April13.jpg|File%3ALOGO%20BRICE%20Noir.png|File%3ABrooks%20Brothers%20logo.svg|File%3ABurberry%20Logo.svg|File%3ABurlington%20Coat%20Factory%20Logo.svg|File%3AC-und-A-Logo-2011.svg|File%3ACalvin%20klein%20logo.svg|File%3ACalzedonia%20logo.svg|File%3ALogo%20celio%20RVB.jpg|File%3ACharles%20Voegele%20Logo.svg|File%3ACharlotte%20russe.png|File%3AChico's%20FAS%20logo.svg|File%3AChristopher%20%26%20Banks%20logo.png|File%3AClub-monaco-logo.jpg&iiprop=dimensions|url|mime) returns the full URL, MIME type, and dimensions of `shop/clothes` logos from A through C. Up to 50 images can be combined in a single request, but we could create a bot account to request up to 500 images at a time.

Ideally the index would store a permalink to the latest revision, but MediaWiki only generates a permalink for archived (superseded) revisions.

**Comment by 1ec5** [comment]
[This API request](https://www.wikidata.org/wiki/Special:ApiSandbox#action=query&format=json&prop=imageinfo&titles=File%3AAbercrombie%20%26%20Fitch%20logo.svg|File%3AMonsoon%20accessorize%20logo.svg|File%3AAckermans-Logo.jpg|File%3AAeropostale%20logo.svg|File%3AAmerican%20Eagle%20Outfitters%20text%20logo.svg|File%3AAnthropologieLogo.png|File%3AArdene%20logo.png|File%3ABanana%20Republic%20logo.png|File%3ABershka%20logo.svg|File%3ABig%20Star%20logo.svg|File%3ABonobos%20LogoGrey%20April13.jpg|File%3ALOGO%20BRICE%20Noir.png|File%3ABrooks%20Brothers%20logo.svg|File%3ABurberry%20Logo.svg|File%3ABurlington%20Coat%20Factory%20Logo.svg|File%3AC-und-A-Logo-2011.svg|File%3ACalvin%20klein%20logo.svg|File%3ACalzedonia%20logo.svg|File%3ALogo%20celio%20RVB.jpg|File%3ACharles%20Voegele%20Logo.svg|File%3ACharlotte%20russe.png|File%3AChico's%20FAS%20logo.svg|File%3AChristopher%20%26%20Banks%20logo.png|File%3AClub-monaco-logo.jpg&iiprop=dimensions|url|mime&iiurlwidth=100) returns 100-pixel-wide thumbnails of all those images. Only 50 thumbnails can be returned in a single API call, even with a bot account.

**Comment by Adamant36** [comment]
> openstreetmap/iD#6361 proposes two factors for determining whether the image is usable: it must be in SVG format and it must be a reasonable aspect ratio, not necessarily square but squarish.

Some of the logo's on Wikiata are trash, like pictures of buildings or just bad logo designs compared to the ones on social media, and the two factors won't help with that. 

I'm wondering if this would be something better set by the user instead of a script somehow or if a better solution would be to have a setting to not farm icons anymore for certain brands that we have already collected "good" logos for. It's completely inefficient to continually quarry social media platforms  and Wikidata for entries that already have a good logo and I imagine it could cause problems down the line when we have a couple million entries. It would be much better to just get a good logo once and call it good on that brand. Especially for long standing companies who never change their logos except for promotional reasons like McDonald's or Burger King.

**Comment by 1ec5** [comment]
> I'm wondering if this would be something better set by the user instead of a script somehow or if a better solution would be to have a setting to not farm icons anymore for certain brands that we have already collected "good" logos for. It's completely inefficient to continually quarry social media platforms and Wikidata for entries that already have a good logo and I imagine it could cause problems down the line when we have a couple million entries.

I think we should continue to rely on APIs to gather logo images (and logo metadata) on the fly. If this project stores the actual logo images, it risks infringing on scores of copyrights. If this project hand-maintains metadata about Commons images, a different image could be uploaded under the same name, and this project would have stale metadata about it. At least metadata gathered from API responses would be easier to maintain.

We already make one Wikidata API call per 50 entries. An additional API call per 50 entries doesn’t seem so bad to me. We’re probably very, very far from running into any sort of rate limiting on that API. I’m not sure about the social media platforms.

> Some of the logo's on Wikiata are trash, like pictures of buildings or just bad logo designs compared to the ones on social media, and the two factors won't help with that.

Pictures of buildings are easily fixable by editing Wikidata. I’ve been keeping an eye on the generated documentation and moving such pictures from logo statements to image statements, and I recommend that others do as well. Once a Wikidata logo claim is fixed, it’s unlikely to be unfixed unless the brand undergoes a rebranding.

Apart from the image format or aspect ratio, are there other objective criteria that would render a logo “bad” in your opinion? I think a _subjectively_ “bad” logo design on Wikidata will most likely be just as bad in the brand’s social media accounts anyways.

A blacklist of Commons images is feasible but has the above caveat that it could get outdated. A blacklist of social media images won’t solve the problem unless we monitor all the social media accounts. Unlike at Commons, a good social media picture today could easily become a not-so-good picture tomorrow.

**Comment by bhousel** [comment]
I'm going to close this, sorry.. It just sounds like a lot of extra work to fetch extra metadata for logos that I don't really intend to use anyway except in special cases.  The social media profile pics are overwhelmingly better for identifying the brands in iD..   

Some numbers:
```
Index completeness:
  4141 entries total.
  3619 (87.4%) with a 'brand:wikidata' tag.
  3312 (80.0%) with a logo.
```
Of those 3312, there are only a handful where using a social picture is arguably the wrong choice because the brand put a funny picture there.  There are many many (a third?) where using the Wiki commons image is the wrong choice because it either looks bad or is just not a current logo.  

I'm going to just add a few lines of code to iD's build script and move on...
