### ISSUE TITLE
Verify country restrictions for Maxima XX

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2642]
It has no locations mapped in the OSM in following countries where this brand is supposedly present.

Maybe the company is operating there but is using a local brand?
* Bulgaria (bg)
* <s>Poland (pl)</s>

In that case it should not be listed as existing there.

https://en.wikipedia.org/wiki/Maxima_Group

```
{
  "countryCodes": [
    "bg",
    "ee",
    "lt",
    "lv",
    "pl"
  ],
  "nomatch": [
    "shop/supermarket|Maxima X",
    "shop/supermarket|Maxima XXX"
  ],
  "tags": {
    "brand": "Maxima XX",
    "brand:wikidata": "Q1881222",
    "brand:wikipedia": "en:Maxima Group",
    "name": "Maxima XX",
    "shop": "supermarket"
  }
}
```

**Comment by tohaklim** [comment]
I think they use a different brand there https://zw.lt/gospodarka/maxima-otworzy-w-polsce-563-sklepy/

**Comment by matkoniecz** [comment]
Good catch, amended in https://github.com/osmlab/name-suggestion-index/commit/2f374c5cda4b9a1af9bcd177a5a6761d49b39d76

Bulgaria remains for checking.

**Comment by Adamant36** [comment]
> Bulgaria remains for checking.

Everything official seems to point to them only having T Market stores in Bulgaria. I couldn't find any references to Maxima XX stores there on the internet. Although that might not mean anything. Id recommend removing it as a country code and adding a Bulgaria specific T Market entry with them as the operator. Wikipedia/Wikidata could be clearer about what they operate and where. It seems that T Market isn't even mentioned on their Wikipedia page. 

https://www.linkedin.com/company/maxima-bulgaria-eood

http://www.maximagrupe.eu/news/176/81/Maxima-Grupe-took-over-12-stores-of-a-German-chain-in-Bulgaria

(From their website)

![160728_Maxima Bulgarija_new stores_ENG-1](https://user-images.githubusercontent.com/30259065/58386762-63b51580-7fb9-11e9-951a-fe736d5310b5.jpg)

**Comment by Adamant36** [comment]
I created [Q64033983](https://www.wikidata.org/wiki/Q64033983) for T Market. Maybe @matkoniecz can double check it to make sure it's cited good enough.

**Comment by matkoniecz** [comment]
It was not, but thanks to your research I fixed it quickly:

![adding references](https://user-images.githubusercontent.com/899988/58399128-6cf4bf80-8057-11e9-825f-d39a629cad2f.gif)

**Comment by Adamant36** [comment]
Hhhmm, I'm not a big fan of the has part reference. It seems pointlessly convoluted and I have yet to see it on other Wikidata entries that haven't been deleted. Maybe at some point we can come up with an easier one to input.

**Comment by matkoniecz** [comment]
> and I have yet to see it on other Wikidata entries that haven't been deleted

See https://www.wikidata.org/wiki/Q60097339 that was undeleted thanks to it

**Comment by Adamant36** [comment]
I didn't say it wouldn't work for the intended purpose, just that there's probably one that would work with less steps that we could probably use instead at some point. There's also a difference between a reference that will lead to un-deletion versus one that will keep something from being deleted in the first place IMHO.

**Comment by matkoniecz** [comment]
Do you have an idea for easier attaching external sources that will typically work? Official website is not enough according to Wikidata admins.

**Comment by bhousel** [comment]
Looks like this was done?
