### ISSUE TITLE
Garbadrome and Garba potentially generic words

### ISSUE THREAD

**Issue by SilentSpike** [osmlab/name-suggestion-index#2643]
Was looking through amenity/restaurant entries and noticed these two. Both are mapped exclusively in Ivory Coast ([see here](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A(nwr%5B%22amenity%22%3D%22restaurant%22%5D%5B%22name%22%3D%22Garbadrome%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&R)) and there's an excessive clumping in the city of Abidjan.

I couldn't determine what language this is so can't confirm if these are generic words, but it seems likely to me.

**Comment by matkoniecz** [comment]
Found https://commons.wikimedia.org/wiki/Category:Garba_(food) and via that 

> Popular Ivorian meal, the Garba (otherwise named Attiéké and fish) is generally sold by men in small street stalls, called Garbadromes.

via `Garbadrome Garba ivory coast` search. Not sure that is the preferred way of fixing that tagging. Just removing name seems to be a poor idea - at least it should be a some sort of cuisine tag, but at the same time it seems to be a descriptive name.
