### ISSUE TITLE
Franprix - is it shop=convenience or shop=supermarket? (France)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2645]
* is shop=convenience sometimes preferable tagging for Franprix?
* is shop=supermarket sometimes preferable tagging for Franprix?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

This brand may be described at https://fr.wikipedia.org/wiki/Franprix or https://fr.wikipedia.org/wiki/Franprix

@Lulucmy - can I bother you with [France-related](https://github.com/osmlab/name-suggestion-index/issues/2313#issuecomment-473824195) questions? If not simply don;t answer I will not ping you like that.

**Comment by Lulucmy** [comment]
Hey,
Don’t worry you don’t bother me, I’m always happy to help OSM !
Franprix are always convenience shops, they’re small and some are even opened 24/24.
I would not say these are supermarkets, but Franprix used to get called “Marché Franprix”. The “Marché” should be removed now.

Have a nice day - Lulucmy

**Comment by bmillemathias** [comment]
> Franprix are always convenience shops, they’re small and some are even opened 24/24.

**Comment by bmillemathias** [comment]
> Franprix are always convenience shops

I concur, they are located in cities in Paris and around.

**Comment by Lulucmy** [comment]
Yes, and you will also find some in France major cities

**Comment by matkoniecz** [comment]
Thanks, I marked `name=Franprix shop=supermarket` as incorrect.
