### ISSUE TITLE
Update for rebranding of JLP shops (Waitrose, John Lewis)?

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#2647]
Not sure what the guidelines on this are among the maintainers, but the index has both Waitrose supermarkets and John Lewis department stores named as such, as expected since OSM data is mostly some years old.
Should it be updated to add "& Partners" to the names of both entities?

**Comment by SilentSpike** [comment]
We should probably write some guidelines on this for future reference, I tend to follow the sentiment here: https://github.com/osmlab/name-suggestion-index/issues/2236#issuecomment-451346930

Which would suggest to me they should probably be left as is, but we could add `official_name` with the "& Partners"

**Comment by matkoniecz** [comment]
>  Should it be updated to add "& Partners" to the names of both entities?

`official_name` tag? Yes, assuming that it is their official name.

To `name` tag? Likely no, as `name` tag is not for the official name but name that is actually used.

**Comment by tohaklim** [comment]
The comment linked by @SilentSpike actually seems to contradict the points you are making, namely:

> We almost always want to use the name that the brand prefers. So, if "Dunkin' Donuts" is now calling themselves "Dunkin'" then that's the name we should suggest to people, even if they are overwhelmingly already mapped as and signed as "Dunkin' Donuts". 

Which is exactly what is happening here: JLP want to underscore that they are a partnership, all of the signage was changed (in a staggerignly short span of time) to match the new branding, and internal docs use new brand names. This is slightly more than just a styling change.
FWIW, Wikipedia has the new names

**Comment by SilentSpike** [comment]
I refer to just below your quote
> We also need to pick a name that renders reasonably on a map. So nothing too long or weird.

We want to adhere to the companies own naming convention unless it's not going to be nice for a typical data consumer to read on the map. Which is where `official_name` comes in for data consumers who're interested in that.

**Comment by tohaklim** [comment]
I guess it's up to whether a typical data consumer would consider an additional 9 char string too long or weird. Official name might be more suitable indeed

**Comment by bhousel** [comment]
I'm closing as this has kind of gone stale and it looks like the Waitrose entries are ok.. 
But if you want to add an `official_name` tag with the longer name on it, feel free.. 👍
