### ISSUE TITLE
Petit Casino - is it shop=convenience or shop=supermarket? (France)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2648]
* is shop=convenience sometimes preferable tagging for Petit Casino?
* is shop=supermarket sometimes preferable tagging for Petit Casino?
Is it maybe describing objects using the same name, but operating under different brands.
Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

Pinging @Lulucmy and @bmillemathias as local France knowledge is useful here.

**Comment by bmillemathias** [comment]
Petit Casino are convenience shops version of Casino supermarkets.
They are located from my experience in center cities or in streets as small shops.

**Comment by matkoniecz** [comment]
Petit Casino supermarkets are now considered as a mistake

In case that it is wrong - please comment or eve better, create a new issue!

**Comment by Lulucmy** [comment]
I agree with @bmillemathias
