### ISSUE TITLE
Verify country restrictions for Planet Fitness

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2649]
It has no locations mapped in the OSM in following countries where this brand is supposedly present.

Note that it includes some very well mapped areas - Poland and Germany

* United Arab Emirates (ae)
* Chile (cl)
* China (cn)
* Colombia (co)
* Costa Rica (cr)
* Germany (de)
* Spain (es)
* United Kingdom (gb)
* Guatemala (gt)
* Israel (il)
* Japan (jp)
* Kuwait (kw)
* Mexico (mx)
* New Zealand (nz)
* Panama (pa)
* Peru (pe)
* Poland (pl)
* Puerto Rico (pr)
* Saudi Arabia (sa)
* Singapore (sg)

Maybe the company is operating there but is using a local brand?
In that case it should not be listed as existing there.

Link: https://en.wikipedia.org/wiki/Planet_Fitness

Entry data:
````
{
  "countryCodes": [
    "ae",
    "au",
    "ca",
    "cl",
    "cn",
    "co",
    "cr",
    "de",
    "do",
    "es",
    "gb",
    "gt",
    "il",
    "jp",
    "kw",
    "mx",
    "nz",
    "pa",
    "pe",
    "pl",
    "pr",
    "sa",
    "sg",
    "us"
  ],
  "tags": {
    "brand": "Planet Fitness",
    "brand:wikidata": "Q7201095",
    "brand:wikipedia": "en:Planet Fitness",
    "leisure": "fitness_centre",
    "name": "Planet Fitness"
  }
}
````

**Comment by SilentSpike** [comment]
As far as I know Planet Fitness is not present in the UK

**Comment by Adamant36** [comment]
I think who ever created entry just added a bunch of random country codes. There's no Planet Fitness is Isreal. There's a Planet Fitness Club in Poland, but they don't seem to be connected. There's a Fitness Planet in Dubai, but its not connected to Planet Fitness Either and its closed down anyway. That's all I could find.

**Comment by matthewlw** [comment]
Hi, creator here. I imported a list of country codes from their website, not thinking that they might be operating under different brands elsewhere. I think it's probably fair to remove those areas where it's not mapped.

**Comment by matthewlw** [comment]
Upon closer investigation, it seems that I made a different error entirely. I meant to paste those in under Orangetheory Fitness instead. It's a very expansive list -- some of those countries have only a handful of locations -- so it's probably better to cut down on false positives and leave the country codes setting for Orangetheory as it is. For actual Planet Fitness, [their website](https://www.planetfitness.com/gyms/) shows only locations in US+Canada with a smattering elsewhere in the Americas.

**Comment by Adamant36** [comment]
Thanks @matthewlw. I merged the fix.

**Comment by matkoniecz** [comment]
@matthewlw Thanks for a fix!
