### ISSUE TITLE
handle  Tuffy Auto Service Center (USA)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2650]
`'name'='Tuffy Tire & Auto Service'` is not used even once - see http://overpass-turbo.eu/s/JeX

"Tuffy Auto Service Center" name seems to be typically used. It either should replace current name or be added in matchNames if it is wrong for some reason.

entry data:

```{
  "countryCodes": [
    "us"
  ],
  "matchNames": [
    "tuffy tire and auto service"
  ],
  "tags": {
    "brand": "Tuffy Tire & Auto Service",
    "brand:wikidata": "Q17125314",
    "brand:wikipedia": "en:Tuffy Auto Service Centers",
    "name": "Tuffy Tire & Auto Service",
    "shop": "car_repair"
  }
}
```

**Comment by 1ec5** [comment]
It’s inconsistent: some locations say “Tuffy Auto Service Center” while others say “Tuffy Tire & Auto Service”, both with the same yellow logo. I _think_ they offer the same services either way, but I’m not 100% certain. We could split the difference and call both of them “Tuffy” or split it into two separate entries.

**Comment by bhousel** [comment]
<img width="480" alt="Screenshot 2019-06-12 17 26 26" src="https://user-images.githubusercontent.com/38784/59387512-55942280-8d37-11e9-9978-4b2ff9279002.png">

Can we just call it "Tuffy" and matchname all the alternate versions of it?
