### ISSUE TITLE
shop/clothes|Bonita needs fixing

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/name-suggestion-index#2652]
"shop/clothes|Bonita": {
    "tags": {
      "brand": "Bonita",
      "brand:wikidata": "Q945463",
      "brand:wikipedia": "en:Bonia (fashion)",
      "name": "Bonita",
      "shop": "clothes"
}

Bonita is a German fashiion retailer, with  wikidata = Q892598

Both brand:wikidata and brand:wikipedia point to another fashion retailer in Kuala Lumpur with even a different name (note the missing "t" in the name).

Suggested fix:
* brand:wikidata = Q892598
* Remove brand:wikipedia

**Comment by matkoniecz** [comment]
Fixed, thanks! https://github.com/osmlab/name-suggestion-index/issues/2655 covers necessary OSM edit that should (re)done after iD and Vespucci update used presets.
