### ISSUE TITLE
On generated pages prefer official website from Wikidata without specified constraints

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/name-suggestion-index#2654]
http://osmlab.github.io/name-suggestion-index/brands/shop/clothes.html#shopclothestom-tailor

-> mentions tom-tailor-online.kz as website, probably because it's the last entry on https://www.wikidata.org/wiki/Q571206. This is a bit confusing. It would be better to show the official website www.tom-tailor.com as per wikidata.

**Comment by matkoniecz** [comment]
https://www.wikidata.org/wiki/Property:P856

**Comment by bhousel** [comment]
Yes, you can update this in Wikidata itself if it is wrong there.  Set a "preferred" rank on the main website, and the script will pull that one.

**Comment by matkoniecz** [comment]
> Set a "preferred" rank on the main website, and the script will pull that one.

Is it even correct with geographic qualifiers? For Russia .ru page is a preferred one.

**Comment by bhousel** [comment]
> Is it even correct with geographic qualifiers? For Russia .ru page is a preferred one.

I'm not sure what you are asking.. The script which gathers claim data from wikidata is just picking a single result to show on our docs page.  

https://github.com/osmlab/name-suggestion-index/blob/d38ebe6d455f7a258ef791d30a5966c0374b674d/build_wikidata.js#L124

The claim picking logic works like this:

https://github.com/osmlab/name-suggestion-index/blob/d38ebe6d455f7a258ef791d30a5966c0374b674d/build_wikidata.js#L170-L175

So it might pull a less preferred value if there are several to choose from, but whenever I notice it doing that, I just update Wikidata and set the preferred rank on the real "official" website.
