### ISSUE TITLE
Fix data damage in OSM for Bonita brand

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2655]
Not doing this now as we new ones may appear until iD and Vespucci updates

see http://overpass-turbo.eu/s/Jft - data damage still needs to be fixed

see #2652 for reason

see https://github.com/osmlab/name-suggestion-index/commit/d38ebe6d455f7a258ef791d30a5966c0374b674d for required fix

**Comment by bhousel** [comment]
I'd prefer for this issue tracker to just be about the index itself and not track data updates here.

**Comment by matkoniecz** [comment]
I think that nsi should take responsibility for data damage that was caused by mistakes in it. It is obvious that mistakes may happen but we should fix it, as part of fixing the bug.

For example see how StreetComplete is doing this https://github.com/westnordost/StreetComplete/issues/1222 , I think that we should follow that.

**Comment by matkoniecz** [comment]
Autofix is now running.
