### ISSUE TITLE
VinMart / VinMart+ is it OK or a real conflict?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2656]
`npm run build` reports

> "shop/supermarket|VinMart" -> duplicates? -> "shop/convenience|VinMart+"

VinMart+ is mentioned at https://vi.wikipedia.org/wiki/VinMart and according to Google Translate

> along with more than 1,400 convenience stores VinMart +. [1]

and

> VinMart is a supermarket system belonging to VinGroup, Vietnam. 

so it seems that tagging is OK, but it would be nice to have confirmation from someone who actually understands language, so summoning @1ec5 as Vietnamese speaker for confirmation

**Comment by 1ec5** [comment]
Previous discussion in #1306 #1403 #2231. VinMart should be `shop=supermarket`, while VinMart+ should be `shop=convenience_store`.
