### ISSUE TITLE
MTS subsidiaries outside Russia

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#2657]
MTS, a Russian telecom, operates multiple subs in the CIS.
This is more of a reminder to add specific country codes to the main brand, already in the index, as well as subs such as https://www.wikidata.org/wiki/Q3920355

**Comment by matkoniecz** [comment]
Is it about

```
  "shop/mobile_phone|МТС": {
    "countryCodes": ["by", "ru", "ua"],
    "tags": {
      "brand": "МТС",
      "brand:en": "MTS",
      "brand:wikidata": "Q1368919",
      "brand:wikipedia": "en:MTS (network provider)",
      "name": "МТС",
      "name:en": "MTS",
      "shop": "mobile_phone"
    }
  },
```
?

In that case - which countries are missing? Current one match OSM data - see http://overpass-turbo.eu/s/Jgw

Under MTS name there is just a bit of entries, not sure is it even correct to map them in this way - see http://overpass-turbo.eu/s/Jgx

**Comment by tohaklim** [comment]
Yep, that's the one.
I guess my issue is more about the wikidata entry associated - it points to the Russian parent company, however this preset is coded as applicable to ru/by/ua (they also have subs in central Asia).
Should such cases be split to point to different wikidata entries (as linked in the OP for by)

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/MTS_(network_provider) is about company operating in multiple countries, in some cases through entities that may be legally distinct but are de facto one entity - especially for purposes of brand recognition

> The MTS mobile network operates using the GSM standard. It currently holds licences to provide mobile services in 81 out of 83 regions in Russia and the entire territories of Armenia (VivaCell MTS), Ukraine, Belarus, Uzbekistan, Turkmenistan.[3][4][5] MTS is currently the biggest mobile operator in Central and Eastern Europe.[6] 

> my issue is more about the wikidata entry associated

In that case it would be a Wikidata issue, not a name-suggestion-index issue so I will close this ticket
