### ISSUE TITLE
no data found at all for 'Peavey Mart shop=country_store'

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2658]
`'shop'='country_store' and 'name'='Peavey Mart' global` query finds no elements

entry data:

```
{
  "countryCodes": [
    "ca"
  ],
  "tags": {
    "brand": "Peavey Mart",
    "brand:wikidata": "Q7158483",
    "brand:wikipedia": "en:Peavey Mart",
    "name": "Peavey Mart",
    "shop": "country_store"
  },
  "internal_index_name": "shop/country_store|Peavey Mart",
  "key": "shop",
  "value": "country_store"
}
```

Is this brand actually existing? Maybe there is a typo in the name or official name was added to `name` tag rather than `official_name` tag?

https://www.openstreetmap.org/search?query=Peavey%20Mart#map=19/50.44621/-104.52706 finds some cases - is it the same brand? Is entry in name-suggestion-index actually tagged better than every single shop mapped in OSM?

**Comment by maxerickson** [comment]
Yeah, the NSI entry is likely better tagged than all of OSM: 

https://www.peaveymart.com/

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcountry_store

There's probably room to argue about how established the tag is, but it is clearly usefully different than shop=hardware.

**Comment by matkoniecz** [comment]
In that case lets close it.
