### ISSUE TITLE
add Bank of East Asia

### ISSUE THREAD

**Issue by hanchao** [osmlab/name-suggestion-index#2661]
https://www.wikidata.org/wiki/Q806679
https://zh.wikipedia.org/zh-hk/%E6%9D%B1%E4%BA%9E%E9%8A%80%E8%A1%8C

"amenity": "bank"
"brand": "東亞銀行"
"brand:en": "Bank of East Asia"
"brand:wikidata": "Q806679"
"brand:wikipedia": "zh:東亞銀行"
"name": "東亞銀行"
"name:en": "Bank of East Asia"

**Comment by matkoniecz** [comment]
>  "name": "東亞銀行"

Where this name is used? Mainland China? Honk Kong seems to prefer BEA - see http://overpass-turbo.eu/s/Jjj and http://overpass-turbo.eu/s/Jjg
 (seems to not be incorrect - see https://en.wikipedia.org/wiki/File:Response_of_malicious_rumours_of_BEA_on_24_Sept_2008.jpg )

There are also https://en.wikipedia.org/wiki/Bank_of_East_Asia#Overseas_operations

**Comment by hanchao** [comment]
yes. BEA is better

Honk Kong 
English: BEA(Bank of East Asia) 
Traditional Chinese:東亞銀行
![bea](https://www.hkbea.com/images/logo.gif)
see https://www.hkbea.com/html/en/index.html

Mainland China
Simplified Chinese:東亚銀行

**Comment by zbc** [comment]
I can work on this.

**Comment by matkoniecz** [comment]
PR are welcomed! If you need some help, please comment!

**Comment by zbc** [comment]
Done.
