### ISSUE TITLE
M&S Simply Food - is it shop=supermarket or shop=convenience? (United Kingdom)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2664]
* is shop=supermarket sometimes preferable tagging for M&S Simply Food? Or both?
* is shop=convenience sometimes preferable tagging for M&S Simply Food? Or both?
Is it maybe describing objects using the same name, but operating under different brands?

```
{
  "tags": {
    "brand": "M&S Simply Food",
    "name": "M&S Simply Food",
    "shop": "supermarket"
  }
}
```

```
{
  "tags": {
    "brand": "M&S Simply Food",
    "name": "M&S Simply Food",
    "shop": "convenience"
  }
}
```

@SilentSpike

**Comment by tohaklim** [comment]
I've seen some that are edging towards a supermarket (trolleys, etc), but generally feel like convenience fits better. Bit ambiguous

**Comment by matkoniecz** [comment]
So is allowing both, with mapper selecting one would be preferable?

**Comment by tohaklim** [comment]
I'd say so. These shops can be parts of larger M&S dept stores, and can really outgrow a typical osm convenience shop

**Comment by matkoniecz** [comment]
Thanks!

Below 20 minutes from reporting by validation script to fixing, nice speed :)

In case that different resolution is preferable - please create a new issue!
