### ISSUE TITLE
Verify country restrictions for Street One

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2677]
It has no locations mapped in the OSM in following countries where this brand is supposedly present

Note that it includes some very well mapped areas like Poland.

* Bulgaria (bg)
* Czechia (cz)
* Spain (es)
* Finland (fi)
* France (fr)
* Croatia (hr)
* Hungary (hu)
* Ireland (ie)
* Italy (it)
* Lithuania (lt)
* Luxembourg (lu)
* Latvia (lv)
* Poland (pl)
* Romania (ro)
* Sweden (se)
* Slovenia (si)
* Slovakia (sk)

Maybe the company is operating there but is using a local brand?
In that case it should not be listed as existing there.

entry data:
```
{
  "countryCodes": [
    "at",
    "be",
    "bg",
    "ch",
    "cz",
    "de",
    "dk",
    "es",
    "fi",
    "fr",
    "hr",
    "hu",
    "ie",
    "it",
    "lt",
    "lu",
    "lv",
    "nl",
    "no",
    "pl",
    "ro",
    "se",
    "si",
    "sk"
  ],
  "tags": {
    "brand": "Street One",
    "brand:wikidata": "Q61997265",
    "name": "Street One",
    "operator": "CBR Fashion Holding",
    "operator:wikidata": "Q1022989",
    "operator:wikipedia": "de:CBR Fashion Holding",
    "shop": "clothes"
  }
}
```
This brand may be described at https://www.wikidata.org/wiki/Q61997265
according to the OSM data it is in: `["at", "de", "ch", "nl", "us", "be", "dk", "no"]`

OSM data matches not listed currently: `["us"]`

**Comment by ENT8R** [comment]
According to my research, it must be `["at", "be", "ch", "de", "dk", "nl"]`. All stores with other country codes which are currently in the index are either ["stores-within-a-store"](https://en.wikipedia.org/wiki/Store-within-a-store) or only other retail stores which buy the products of "StreetOne" and sell them in their own store (e.g. Peek & Cloppenburg). The latter is what they prefer to do in countries where no "StreetOne" stores exist, according to the Wikipedia article of the [company which owns "StreetOne"](https://de.wikipedia.org/wiki/CBR_Fashion_Holding) and the [store locator of "StreetOne"](https://www.street-one.de/shopfinder).
So I am now going to replace the country codes which contains all countries where they sell at least one thing in some store (which mustn't be "StreetOne" itself) with the list of country codes where they really operate own stores called "StreetOne".

**Comment by bhousel** [comment]
Thanks @ENT8R for taking care of this! 👍
