### ISSUE TITLE
shop=variety_store name=Centrakor without assigned brand:wikidata (objects in France)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2681]
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

For real brands without Wikipedia article and existing Wikidata page creating new Wikidata entry may be helpful, but for start confirmation that it is a valid brand would be helpful. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata for hints about Wikidata editing.

@Lulucmy @bmillemathias 

entry data:
```
{
  "countryCodes": [
    "fr"
  ],
  "tags": {
    "brand": "Centrakor",
    "name": "Centrakor",
    "shop": "variety_store"
  }
}
```

**Comment by bmillemathias** [comment]
Centrakor is a real brand name, that sell various things for home.
I can create the wikidata entries this evening.
