### ISSUE TITLE
shop=hairdresser name=Saint Algue without assigned brand:wikidata (objects in France)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2689]
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

For real brands without Wikipedia article and existing Wikidata page creating new Wikidata entry may be helpful, but for start confirmation that it is a valid brand would be helpful. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata for hints about Wikidata editing.

entry data:
```
{
  "tags": {
    "brand": "Saint Algue",
    "name": "Saint Algue",
    "shop": "hairdresser"
  }
}
```

@Lulucmy @bmillemathias

**Comment by Adamant36** [comment]
Looks like its a chain of hair dressers. @bmillemathias already created a Wikidata entry for it a month ago Q62973210. Although, it could use better citation. Its also mentioned here https://fr.wikipedia.org/wiki/Franck_Provost 

![l](https://user-images.githubusercontent.com/30259065/58441776-9a625d00-8099-11e9-8401-a155c58be20d.jpg)
