### ISSUE TITLE
amenity=bank name=Банк Дабрабыт without assigned brand:wikidata (objects in Belarus)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2693]
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

For real brands without Wikipedia article and existing Wikidata page creating new Wikidata entry may be helpful, but for start confirmation that it is a valid brand would be helpful. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata for hints about Wikidata editing.
I am asking as I want to improve https://github.com/osmlab/name-suggestion-index/
and I lack local knowledge how it should be tagged. Data from this project are
used for example by iD and Vespucci.
Improving it may help mappers using this editors as they will be guided better during editing.

@tohaklim

entry data:
```
{
  "tags": {
    "amenity": "bank",
    "brand": "Банк Дабрабыт",
    "name": "Банк Дабрабыт"
  }
}
```

**Comment by tohaklim** [comment]
Oh yes, I've created a [wikidata page](https://www.wikidata.org/wiki/Q63981850) for it.
It was previously known as Банк Москва-Минск, but was recently imported by people known to you, rocketdata, with the new name as they rebranded

**Comment by matkoniecz** [comment]
Note that it is preferable to add also some referenced info (see https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#adding-references-to-wikidata for detail)
