### ISSUE TITLE
Indomaret - is it shop=supermarket or shop=convenience? (Indonesia)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2694]
* is shop=supermarket sometimes preferable tagging for Indomaret?
* is shop=convenience sometimes preferable tagging for Indomaret?
Is it maybe describing objects using the same name, but operating under different brands?
Or is it a popular name among independent shops, without shared brand?

https://en.wikipedia.org/wiki/Indomaret describes them as convenience shops, but I am not sure is it accurate 

entry data:
```
{
  "tags": {
    "brand": "Indomaret",
    "name": "Indomaret",
    "shop": "supermarket"
  }
}
```

and

```
{
  "tags": {
    "brand": "Indomaret",
    "name": "Indomaret",
    "shop": "convenience"
  }
}
```

**Comment by Adamant36** [comment]
You might want to ask @jeisenbe about that since he lives there. I don't think he'd mind. Even though I have yet to see him contribute over here.

**Comment by matkoniecz** [comment]
@jeisenbe In case that you would be OK with that - can I ping you in future in case of similar questions?

**Comment by jeisenbe** [comment]
Sure, no problem.

Indomaret is a shop=convenience, like It’s competitor “Alfamart” and
7-Eleven.

We don’t have many supermarkets: the brands of supermarket that I know are
Super Indo, Hypermart, and Carrefore.
