### ISSUE TITLE
shop=hairdresser name=Super Cut without assigned brand:wikidata (objects in Germany)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2695]
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

For real brands without Wikipedia article and existing Wikidata page creating new Wikidata entry may be helpful, but for start confirmation that it is a valid brand would be helpful. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata for hints about Wikidata editing.

entry data:
```
{
  "tags": {
    "brand": "Super Cut",
    "name": "Super Cut",
    "shop": "hairdresser"
  }
}
```

summoning @ENT8R

**Comment by ENT8R** [comment]
It's a real brand with about 120 stores in Germany.
I created a Wikidata item for it, containing all information I could find: https://www.wikidata.org/wiki/Q64139077

**Comment by matkoniecz** [comment]
Thanks, I added wikidata
