### ISSUE TITLE
How should JoS. A. Bank be spelled?

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#2701]
The company calls itself “JoS. A. Bank”. The index’s spelling (and the current most popular tagging) uses the abbreviation without the flourish: “Jos. A. Bank”. I think it should be spelled either “JoS. A. Bank” or in full as “Joseph A. Bank”.

“Jos.” (with a lowercase S) is the traditional abbreviation for “Joseph”. OSM avoids abbreviations in part to facilitate text-to-speech. Brands often seem to get a pass (“Carl’s Jr.”, not “Carl’s Junior”), but this abbreviation seems problematic. Less sophisticated text-to-speech engines are unlikely to know how to expand the relatively rare “Jos.” into “Joseph”, whereas a renderer could make use of “Jos.” in `short_name` if space is a problem.

On the other hand, if we think it’s better to match the trademark, then it should be “JoS. A. Bank”, not “Jos. A. Bank”, incorporating the stylistic flourish that the company uses even in plain text.

https://github.com/osmlab/name-suggestion-index/blob/de7f7319a0083e5d818b8ca2308e27e8d24fce1b/brands/shop/clothes.json#L1077-L1086

**Comment by matkoniecz** [comment]
> The index’s spelling (and the current most popular tagging)

What form is typically used by people?

> to facilitate text-to-speech

I am not convinced that is the main reason for doing this. AFAIK abbreviations in paper maps/encyclopedia were used to fit more data into limited physical space, and OSM/Wikipedia has no such restriction.

**Comment by 1ec5** [comment]
> What form is typically used by people?

“Jos. A. Bank” is more prevalent in news reports, but both are common. Serious published works like news reports and encyclopedias would prefer a non-stylized spelling, so the S would be lowercase. (Brands often incorporate typographical flourishes that are ignored by third parties, cf. #2691.)

As for ordinary folks on the street, it probably depends on the person’s familiarity with their logo. Otherwise, I see no reason why someone would hear their commercials saying “Joseph… A… Baaank” and think it would be abbreviated that way.

>> to facilitate text-to-speech
> 
> I am not convinced that is the main reason for doing this. AFAIK abbreviations in paper maps/encyclopedia were used to fit more data into limited physical space, and OSM/Wikipedia has no such restriction.

Well, it’s about removing ambiguity and avoiding data loss, but I guess my point is that ambiguity is more problematic in text-to-speech than normal rendering. Abbreviation isn’t specific to printed matter. After all, online maps routinely abbreviate street names to improve label density at a particular zoom level.

Incidentally, [Google Ngram Viewer](https://books.google.com/ngrams/graph?content=Joseph+A.+Bank%2CJos.+A.+Bank&year_start=1905&year_end=2019&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CJoseph%20A.%20Bank%3B%2Cc0%3B.t1%3B%2CJos.%20A.%20Bank%3B%2Cc0#t1%3B%2CJoseph%20A.%20Bank%3B%2Cc0%3B.t1%3B%2CJos.%20A.%20Bank%3B%2Cc0) also shows a clear preference for “Jo[Ss]. A. Bank”, but that may be influenced by business directories and magazine advertising where space is also at a premium.

**Comment by bhousel** [comment]
> The company calls itself “JoS. A. Bank”.

☝️ Let's call it that.
