### ISSUE TITLE
incorrect brand tagging for S-market

### ISSUE THREAD

**Issue by crimsondusk** [osmlab/name-suggestion-index#2704]
S-market is a chain of supermarkets in Finland and it is currently indexed as "S-Market". The "m" should not be capitalized.

**Comment by crimsondusk** [comment]
If you want, I can probably come up with indexes for the other Finnish shop chains.

**Comment by matkoniecz** [comment]
Issues about wrong/missing data is welcomed! Pull requests - even more!

If you want you may add yourself to https://github.com/osmlab/name-suggestion-index/issues/2588 to sign up for notifications about wrong/missing entries concerning Finland.

**Comment by matkoniecz** [comment]
> The "m" should not be capitalized.

http://overpass-turbo.eu/s/Jq8 http://overpass-turbo.eu/s/Jq6

So the more popular tagging is wrong, right? Wikipedia has https://fi.wikipedia.org/wiki/S-market

**Comment by crimsondusk** [comment]
The name style is also present in the [official website](https://www.s-kanava.fi/web/smarkethokelanto/etusivu). So I'm convinced that this is the correct style. I think the small caps is throwing people off.

Also, the store names generally come with qualifiers forming unique names, e.g. [this one](https://osm.org/node/269693256), so the overpass link is not covering all of the S-markets, which is why IMO it's good that brand tagging is becoming a thing.
