### ISSUE TITLE
Petron - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2705]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused for example by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)
* descriptive name in brand idex (things like `shop=bakery name=Bakery`)

Country codes declared in name-suggestion-index:
* ph - 1375 mapped entries

Additional countries with object of matching name and type mapped in OSM
my - 273 mapped entries
ma - 3 mapped entries
in - 6 mapped entries
ru - 1 mapped entries
am - 1 mapped entries
iq - 1 mapped entries
ss - 2 mapped entries
pe - 1 mapped entries
pk - 3 mapped entries
tz - 1 mapped entries
pl - 1 mapped entries
do - 1 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data: 'amenity'='fuel' and name='Petron' global

entry data:
```
{
  "countryCodes": [
    "ph"
  ],
  "tags": {
    "amenity": "fuel",
    "brand": "Petron",
    "brand:wikidata": "Q7179011",
    "brand:wikipedia": "en:Petron Corporation",
    "name": "Petron"
  }
}
```

ping @jeisenbe - is this brand actually present in Malaysia?

**Comment by mds08011** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Petron_Corporation):

>On March 30, 2012, Petron acquired ExxonMobil's downstream business in Malaysia in with XCEL Petroleum. In January 2013, Petron officially opened their Malaysian operations, rebranding all Esso and Mobil stations across Peninsular Malaysia.

It looks like a different subsidiary but same brand (name, logo, sign, etc): https://www.petron.com.my/web/

**Comment by bhousel** [comment]
ok I've added `my` to the list of countryCodes
