### ISSUE TITLE
remove generic entry "Volksbank"

### ISSUE THREAD

**Issue by Prince-Kassad** [osmlab/name-suggestion-index#2707]
Follow-up to PR #2610

Wikidata item Q695110 is extremely confusing as to what it should refer to, it contains both the Austrian banks called "Volksbank" and the German banks also called "Volksbank" with no relation to each other. The English Wikipedia entry the Wikidata item links to is more or less a disambiguation page that says there are multiple unrelated banks in different countries with that name. "Volksbank" is such a generic name that it will always require human interaction to clarify which Volksbank is meant, as such I suggest removing this entry entirely.

**Comment by Adamant36** [comment]
I suggest we create different entries for the Austrian and German ones with country codes and create sepreate Wikidata entries for each .

**Comment by SilentSpike** [comment]
@Adamant36 If I understand correctly, it's present in both countries, but it isn't actually one unified brand in either (clearer from reading #2610).

**Comment by bhousel** [comment]
This was done in 741d771
