### ISSUE TITLE
add EuroShop

### ISSUE THREAD

**Issue by Prince-Kassad** [osmlab/name-suggestion-index#2708]
EuroShop should be added as shop=variety_store and linked to Wikidata item Q15846763 and Wikipedia entry de:Schum EuroShop

This is currently reported as a "generic name" although it is a valid brand.

**Comment by matkoniecz** [comment]
Thank you for reporting this validator mistake!

> This is currently reported as a "generic name" although it is a valid brand.

This is now fixed in name-suggestion-index. After new version of name-suggestion-index and iD is released it will be fixed.

**Comment by matkoniecz** [comment]
Do you want be asked questions about local situation in Germany? If you want you may add yourself to https://github.com/osmlab/name-suggestion-index/issues/2588

Typical question is something like #2648
