### ISSUE TITLE
cuisine tag is missing for amenity=restaurant 永和豆漿 (Taiwan)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2710]
Is there one that apply to every single location for this poi?
What would be appropriate value for it?

This brand may be described at https://zh.wikipedia.org/wiki/永和豆漿

entry data:
```
{
  "countryCodes": [
    "tw"
  ],
  "tags": {
    "amenity": "restaurant",
    "brand": "永和豆漿",
    "brand:en": "Yonghe Soy Milk",
    "brand:wikidata": "Q11131335",
    "brand:wikipedia": "zh:永和豆漿",
    "name": "永和豆漿",
    "name:en": "Yonghe Soy Milk"
  }
}
```

**Comment by zbc** [comment]
It's a traditional Chinese breakfast. It could be `"cuisine": "chinese;breakfast"`

**Comment by bhousel** [comment]
thanks, go ahead and make the change @zbc  👍
