### ISSUE TITLE
H&R Block - mismatch between data in name-suggestion-index and data mapped in OSM.

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2711]
Countries declared in countryCodes field and where such objects are mapped in OSM is not matching.
it may be caused for example by:
* mistake in countryCodes field (fixable by changing it)
* by different brand using the same name, not present in the index (fixable by adding it to the index)
* mistake in OSM (fixable by editing OSM)
* suspicious data in OSM (fixable by opening an OSM note)

entry data:
```
{
  "countryCodes": [
    "pr",
    "us"
  ],
  "matchTags": [
    "office/accountant"
  ],
  "tags": {
    "brand": "H&R Block",
    "brand:wikidata": "Q5627799",
    "brand:wikipedia": "en:H&R Block",
    "name": "H&R Block",
    "office": "tax_advisor"
  }
}
```

entry in name-suggestion-index is currently:
tags assigned:
* office=tax_advisor
* name=H&R Block
* brand=H&R Block
* brand:wikidata=Q5627799
* brand:wikipedia=en:H&R Block
appearing in countries:
* Puerto Rico (pr)
* United States (us)

Country codes declared in name-suggestion-index:
* pr - 0 mapped entries
* us - 419 mapped entries

Additional countries with object of matching name and type mapped in OSM
ca - 80 mapped entries
au - 6 mapped entries

you can use following query in the Overpas Turbo Wizard to look at this data:
`'office'='tax_advisor' and name='H&R Block' global`

This brand may be described at https://en.wikipedia.org/wiki/H&R_Block
examples are listed below:
this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/3132997026

this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/3213567941

this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/3426852736

this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/4772212776

this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/4804787463

this is in country with code 'ca', according to name index present nearly not present outside ["pr", "us"]
https://www.openstreetmap.org/node/4890466560

**Comment by 1ec5** [comment]
bee2b8f8050e7a372b3a45ac6cfcf9b4a4811e01 added 🇨🇦 to Block Advisors, but I think the intention was to add it to H&R Block instead. [Block Advisors’ store locator](https://www.blockadvisors.com/find-a-tax-advisor/) requires you to enter a (U.S.-centric) ZIP code, while H&R Block’s Canadian site makes no mention of Block Advisors.

**Comment by 1ec5** [comment]
> pr - 0 mapped entries 

What about [this POI](https://www.openstreetmap.org/node/5978733983)?

**Comment by 1ec5** [comment]
#2713 moves 🇨🇦 from Block Advisors to H&R Block.

**Comment by 1ec5** [comment]
32dee31ad6ce17717c6a6c692ecfbd4008fe1981 adds 🇦🇺🇮🇳 to H&R Block.

**Comment by matkoniecz** [comment]
> What about this POI?

Because Nominatim shows USA as country (and therefore `us` as a country code) for Puerto Rico locations (unlike for example with Isle of Man) https://nominatim.openstreetmap.org/details.php?place_id=79844174

Thanks for noticing, I need to check whatever it is somewhere documented what approach should be taken for such subcountry codes or at least how filtering in iD and Vespucci works in say Puerto Rico and Isle of Man.

**Comment by matkoniecz** [comment]
@1ec5 I opened https://github.com/osmlab/name-suggestion-index/issues/2714 as it appears to not be clearly defined (I can easily add special case for my script but I am dubious whatever separate entry for Puerto Rico, Isle of Man etc is actually useful).
