### ISSUE TITLE
Country codes for entities like Isle of Man and Puerto Rico

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2714]
[Isle of Man](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#IM) and [Puerto Rico](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#PR) have assigned ISO 3166-1 alpha-2 codes.

Is it useful and desirable to use them in `countryCodes` field? Maybe it would be enough to specify `["us"]` rather than `["us", "pr"]` and `["gb"]` rather than `["gb", "im", "gg", "je"]`?

Pinging @bhousel and @simonpoole as representing main users of this data - what is preferable? Maintaining separate entries in `countryCodes` field for cases like this? Only some of them?

summoning @Adamant36, @1ec5, @maxerickson for US question - is it useful to maintain separate list of brands present in Puerto Rico? Is there some case where it would be useful to add `us` code without `pr` code or `pr` code without `us` code?

summoning @SilentSpike - the same for UK. Is there some case where Isle of Man, Guernsey or Jersey would benefit from separate brand list in `countryCodes` field?

**Comment by Adamant36** [comment]
Hhhmm, I think in the case of Puerto Rico it would be fine to just use US because its classified as part of America and a state in OSM. So it will still come up in searches. Whatever the exact legal details about it might be.

**Comment by SilentSpike** [comment]
For the Isle of Man, Jersey and Guernsey I'd probably leave them separate. I can't think of many cases where businesses would be specific to them. However, there are likely many instances of businesses that are present in the UK but not those locations.

Plus it's nice to have granularity where available.

**Comment by 1ec5** [comment]
I think our decision should be based on how clients like iD and Vespucci will behavior as a result. If both editors use Nominatim and the result always comes back with a `country_code` of `us`, then there’s no need to maintain `pr` in the index, since it would have no effect. But if `country_code` can be `pr`, then we need to be vigilant about missing `pr`s in `countryCodes`. Otherwise, mappers in Puerto Rico could miss out on useful entries. (Same with Isle of Man, Hong Kong, etc.)

Maybe someday in the future, this index will become so large that we’ll need to filter entries more granularly, down to the state/province/territory level. But it’ll be a lot of work to do that consistently, so we should wait until editor usability concerns require it.

**Comment by bhousel** [comment]
> I think our decision should be based on how clients like iD and Vespucci will behavior as a result. If both editors use Nominatim and the result always comes back with a `country_code` of `us`, then there’s no need to maintain `pr` in the index, since it would have no effect.

yes, iD uses nominatim.  I think we can avoid adding `pr` for now.

**Comment by matkoniecz** [comment]
I created explicit issue at Vespucci bugtracker, lets wait some time for a reply whatever they have some preference.

**Comment by simonpoole** [comment]
We use an on-device border based index for determining the country / state and don't really care (for Puerto Rico we get back PR, US for the Isle of Man IM, UK). As the NSI was originally about chains I would suspect that mini-territories (aka IM) shouldn't be a real concern in any case.

**Comment by matkoniecz** [comment]
> As the NSI was originally about chains I would suspect that mini-territories (aka IM) shouldn't be a real concern in any case.

IM is big enough to have town/cities and appears to have some chain stores - see for example https://www.openstreetmap.org/#map=19/54.15024/-4.47897

**Comment by simonpoole** [comment]
@matkoniecz "chain stores that are specific to the territory and that occur often enough that they should be reflected in the NSI". Manx Telecom might have been a candidate, but they have exactly one shop.

**Comment by matkoniecz** [comment]
@simonpoole There are also many cases where something appears in a limited set of places but not elsewhere.

See for example http://overpass-turbo.eu/s/JyI recorded at https://github.com/osmlab/name-suggestion-index/blob/de7f7319a0083e5d818b8ca2308e27e8d24fce1b/brands/shop/charity.json#L33

Or Specsavers that operates in a limited set of countries - see http://overpass-turbo.eu/s/JyJ

Or Thomas Cook travel agency - see http://overpass-turbo.eu/s/JyL

> chain stores that are specific to the territory and that occur often enough that they should be reflected in the NSI

What is quoted here?

**Comment by simonpoole** [comment]
> 
> 
> @simonpoole There are also many cases where something appears in a limited set of places but not elsewhere.

That is I think something that can be said of essentially everything :-).  The question here is if the next level up admin entity can be used conflict free to determine the characteristics of the chain in question.

So you don't need anything else than a global entry for McDonalds and for Specsavers UK would be narrow enough (assuming there is an unrelated Specsavers elsewhere in the world).
  

> > "chain stores that are specific to the territory and that occur often enough that they should be reflected in the NSI"
> 
> What is quoted here?
Myself trying to clarify what I meant.

**Comment by 1ec5** [comment]
> (for Puerto Rico we get back PR, US for the Isle of Man IM, UK)

If I’m reading correctly, that would be similar to the Nominatim behavior of including Puerto Rico in the U.S., right? If so, then we can safely remove any `pr`s from the index until we start collecting second-level administrative areas more comprehensively.

**Comment by matkoniecz** [comment]
> If I’m reading correctly, that would be similar to the Nominatim behavior of including Puerto Rico in the U.S., right? If so, then we can safely remove any prs from the index until we start collecting second-level administrative areas more comprehensively.

Yes, exactly. Both iD and Vespucci is fine with that, apparently it is not adding useful info and it seems better that adding Puerto Rico code to all entries that have USA code.

**Comment by 1ec5** [comment]
We’re running into this problem again with Hong Kong and Macau, which often require different tagging than mainland China for the same brands: https://github.com/osmlab/name-suggestion-index/pull/2797#discussion_r294061235.

**Comment by matkoniecz** [comment]
I also noticed China issue - but as in this case the re are actually significant differences, and our codes are correct. It probably should be requested for iD to support this regional country codes.

**Comment by ferdinand0101** [comment]
Would it be possible to have something like  `"countryCodes": ["cn-hk"],`
because that would fit with the I[SO](https://en.wikipedia.org/wiki/ISO_3166-2) for country subdivisons.

**Comment by bhousel** [comment]
Yes, we'll switch this library over to using https://github.com/ideditor/location-conflation soon and that will let us define much better geographical regions.
(This is also #3162

**Comment by bhousel** [comment]
This was done!  from the updates to the contributing guide:

---

Each entry requires a `locationSet` to define where the entry is available.  You can define the `locationSet` as an Object with `include` and `exclude` properties:

```js
"locationSet": {
  "include": [ Array of locations ],
  "exclude": [ Array of locations ]
}
```

The "locations" can be any of the following:
* Strings recognized by the [country-coder library](https://github.com/ideditor/country-coder#readme). These should be [ISO 3166-1 2 or 3 letter country codes](https://en.wikipedia.org/wiki/List_of_countries_by_United_Nations_geoscheme) or [UN M.49 numeric codes](https://en.wikipedia.org/wiki/UN_M49).<br/>_Example: `"de"`_<br/>Tip: The M49 code for the whole world is `"001"`.
* Filenames for custom `.geojson` features. If you want to use a custom feature, you'll need to add these under the `features/` folder (see ["Features"](#features) below for more details). Each `Feature` must have an `id` property that ends in `.geojson`.<br/>_Example: `"de-hamburg.geojson"`_<br/>Tip: You can use [geojson.io](http://geojson.io) or other tools to create these.

You can view examples and learn more about working with `locationSets` in the [@ideditor/location-conflation](https://github.com/ideditor/location-conflation/blob/master/README.md) project.

⚡️ You can test locationSets on this interactive map:  https://ideditor.github.io/location-conflation/

**Comment by bhousel** [comment]
Examples:
- [Isle of Man](https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%27im%27%5D%20%7D%0A)
- [Puerto Rico](https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%27pr%27%5D%20%7D%0A)
- [Macau](https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%27mo%27%5D%20%7D%0A)
- [Hong Kong](https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%27hk%27%5D%20%7D%0A)
- [China, excluding Hong Kong and Macau](https://ideditor.github.io/location-conflation/?locationSet=%7B%20include%3A%20%5B%27cn%27%5D%2C%20exclude%3A%20%5B%27hk%27%2C%27mo%27%5D%20%7D%0A)
