### ISSUE TITLE
car_repair: remove BestDrive countryCodes ?

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#2715]
Hello,

following a comment from @matkoniecz on OSM (https://www.openstreetmap.org/changeset/69043146) I've check again where BestDrive where implemented.

I found on some french PR the picture 
![image](https://user-images.githubusercontent.com/8579/58641994-a437ca80-82fc-11e9-9d8e-f8f6b6dec4ed.png) but I assume this covers only Europe as I read in other news that BestDrive is also present in South-Africa.

What should I do ? remove countryCodes or try to find every country where BestDrive are ?

Thanks

**Comment by bhousel** [comment]
> What should I do ? remove countryCodes or try to find every country where BestDrive are ?

Either is ok 👍
