### ISSUE TITLE
Research needed for: amenity/bank|Kasa Stefczyka

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#272]
#### :thinking: We need help deciding what to do with "amenity/bank|Kasa Stefczyka"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Kasa Stefczyka` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Kasa Stefczyka`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Kasa Stefczyka`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
> Add tags for brand:wikidata and brand:wikipedia

It has no own wikipedia entry. Brand is based on https://pl.wikipedia.org/wiki/Kasa_Stefczyka - but article is not about the current company.

**Comment by matkoniecz** [comment]
https://pl.wikipedia.org/wiki/Sp%C3%B3%C5%82dzielcza_kasa_oszcz%C4%99dno%C5%9Bciowo-kredytowa describes this type of company, not just this one brand.

**Comment by bhousel** [comment]
I don't know, @matkoniecz - use your best judgement.
If it's not really a brand, we can just discard it from the index.

**Comment by matkoniecz** [comment]
It is a brand but currently there is no wikidata or wikipedia page for it. Is it OK to just create nearly empty Wikidata entry for that brand?

**Comment by good-praxis** [comment]
Ah, sorry, the wikidata isn't accurate enough?

**Comment by matkoniecz** [comment]
Done!
