### ISSUE TITLE
Create preset for Kilwins

### ISSUE THREAD

**Issue by HubMiner** [osmlab/name-suggestion-index#2728]
brand=Kilwins
brand:wikidata=Q38250832
brand:wikipedia=en:Kilwins
name=Kilwins

# optional 
alt_name=Kilwin's
cuisine=chocolate;ice_cream;popcorn

**Comment by HubMiner** [comment]
Add:
 "shop": "confectionery" or "amenity": "ice_cream"

**Comment by zbc** [comment]
Can I work on this?

**Comment by bhousel** [comment]
> Can I work on this?

Yes, go ahead! 👍

**Comment by bhousel** [comment]
done in #2754
