### ISSUE TITLE
nsi docs - include ability to limit results to a specific country code

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2733]
To make data review easier it would be useful to add ability to show all entries with, for example, country code `au` and entries without `countryCodes` field.

Filtering can be either dynamic with some JS or static version of http://osmlab.github.io/name-suggestion-index/brands/ can be generated for every country

**Comment by matkoniecz** [comment]
I plan to do it after automatic country matcher will process most of the data to avoid wasting human time on adding country restrictions that can be done automatically.

**Comment by bhousel** [comment]
This doesn't really close the issue, but I did add `countryCodes` to the doc pages today:

<img width="719" alt="Screenshot 2019-06-05 12 08 12" src="https://user-images.githubusercontent.com/38784/58972029-9f569900-878a-11e9-8319-cc1806bcf657.png">

**Comment by matkoniecz** [comment]
Single page with all brands from each country unfortunately is too heavy for browsers that start lagging with 5MB of html, so there is a separate index for each country in my WIP.

I started thinking about keeping geenrate docs in a separate repository to reduce churn cause by regenerating it - and adding generated pages for each country is going to make it even worse.

**Comment by matkoniecz** [comment]
And separate browser for each country is also unreasonable - count of countries multiplied by count of supported tags is unreasonably large, it would generate thousands of .html pages.

**Comment by bhousel** [comment]
The current static doc pages is something I threw together in a day or two.. It would be better to write an app that loads the `dist/brands.json` and `dist/wikidata.json` files and builds the documentation in client-side Javascript (and could do filtering and searching and other useful stuff).

**Comment by matkoniecz** [comment]
I hoped that adding this will take hour or two and it worked but I forgot to check how many pages would be needed :)

**Comment by bhousel** [comment]
I added this today!  Try it out
https://osmlab.github.io/name-suggestion-index/index.html

**Comment by bhousel** [comment]
looks like this.. You can filter on tag text or country code.

![filtering](https://user-images.githubusercontent.com/38784/60546949-7c1cfc00-9cec-11e9-81be-fa7e7528722e.gif)
