### ISSUE TITLE
generate docs for individual entries, with full information presented

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2734]
It would make review of data easier for local communities. JSON is relatively readable, but not for all and multiple big JSON files are not improving situation.

It would make possible to include full data, with matches and country code list included, including default matches.

Individual entries would be linked from tag lists like http://osmlab.github.io/name-suggestion-index/brands/amenity/bank.html

**Comment by matkoniecz** [comment]
I see three ways how this goal can be achieved

- expand existing lists (undesirable, would break current usecases)
- add individual page for every single entry (thousands of new .html files may have negative effects)
- create list with entries by category (like the current list), each entry with full data, (may be hard to browse)

First seems to be a poor idea, I am not sure which of two remaining ones is better. Anyway, I want to implement it to make #2733 possible (#2733 would be confusing without making country code limitations visible)

**Comment by Adamant36** [comment]
Hhhhmmm, neither of the three options seem optimal. Maybe there's another way of doing it that just hasn't been thought of yet.

**Comment by matkoniecz** [comment]
This is not feasible with current documentation model based on static htmls.

**Comment by Adamant36** [comment]
Bummer. Closing then.
