### ISSUE TITLE
amenity=bank name=БПС-Сбербанк without assigned brand:wikidata (objects in Belarus)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2737]
In case that it is an existing brand - is it one that has its own Wikipedia page or a Wikidata entry?

Or maybe it is an unwanted generic name (like amenity=restaurant name=Restaurant) rather than a brand?
Or maybe it is a valid name (like amenity=restaurant name=Bamboo), without an uniting brand?

For real brands without Wikipedia article and existing Wikidata page creating new Wikidata entry may be helpful, but for start confirmation that it is a valid brand would be helpful. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#memo--edit-wikidata for hints about Wikidata editing.

entry data:
```
{
  "tags": {
    "amenity": "bank",
    "brand": "БПС-Сбербанк",
    "name": "БПС-Сбербанк"
  }
}
```

entry in name-suggestion-index is currently:
tags assigned:
* amenity=bank
* name=БПС-Сбербанк
* brand=БПС-Сбербанк

@tohaklim

**Comment by Adamant36** [comment]
@matkoniecz, looks like it's https://www.bps-sberbank.by/

**Comment by tohaklim** [comment]
yeah, I think this should do https://www.wikidata.org/wiki/Q2074915

**Comment by matkoniecz** [comment]
Thanks!

**Comment by Adamant36** [comment]
I added some details to the Wikidata entry. It always surprises how many entries don't even have basic details like a title 🙄
