### ISSUE TITLE
cuisine tag is missing for amenity=fast_food 맥도날드 (South Korea)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2742]
Is there one that apply to every single location for this poi?
What would be appropriate value for it?

entry data:
```
{
  "countryCodes": [
    "kr"
  ],
  "tags": {
    "amenity": "fast_food",
    "brand": "맥도날드",
    "brand:ko": "맥도날드",
    "name": "맥도날드",
    "name:ko": "맥도날드",
    "takeaway": "yes"
  }
}
```

**Comment by Adamant36** [comment]
Since it's McDonald's id assume burger. It doesn't look like they have anything else on their menu to warrant another tag.

**Comment by bhousel** [comment]
I added the wiki tags for McDonalds, along with a bunch of other multilingual name and brand tags in the fast_food file.
