### ISSUE TITLE
Westfield is still a mall

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#2743]
#2735 added a `shop=mall` entry for Westfield, which is still a mall brand, even though it’s owned by two different companies that are no longer called Westfield. See [this Wikipedia list](https://en.wikipedia.org/wiki/List_of_Westfield_shopping_centres) and its sublists. The current entry is tagged with a Wikidata item and Wikipedia article for a defunct company whose successor is also defunct.

A Wikidata item needs to be created for the Westfield brand, linked to the current parent companies, and the NSI entry needs to be switched over to the new item. Alternatively, separate Wikidata items can be created for the Scentre Group properties and Unibail-Rodamco-Westfield properties, limited to different sets of countries.

**Comment by bhousel** [comment]
In the mean time, I've removed the wiki tags in ea284122

**Comment by andrewharvey** [comment]
See also my comment at https://github.com/osmlab/name-suggestion-index/commit/ea284122267ef828070d0271cb9377ee22bc7ec8 regarding omitting the name tag.

**Comment by bhousel** [comment]
We can't omit the name tag.

**Comment by bhousel** [comment]
I removed the entry in 671b85f5
We are currently [filtering out](https://github.com/osmlab/name-suggestion-index/blob/671b85f564906f0eb3e79ff6b693dea84afc4a0c/config/filters.json#L32) `shop/mall` from the names we extract from the planet, and this single entry didn't have suitable wiki tags anyway.    

We can revisit this later, but I just want to remove it for right now.

**Comment by 1ec5** [comment]
For future reference, [this Wikipedia search](https://en.wikipedia.org/w/index.php?title=Special:Search&search=%22chain+of+malls%22) turns up several more chains of malls, though Westfield is the largest and most strongly branded of them.
