### ISSUE TITLE
O2 links to defunct company

### ISSUE THREAD

**Issue by Prince-Kassad** [osmlab/name-suggestion-index#2748]
The entry for O2 is linked to Q7072246, which is a defunct company that ceased business in 2015.

It probably should be linked to the parent company which is Q1759255. This also affects the corresponding Wikipedia link.

**Comment by Adamant36** [comment]
Probably it should be re-tagged/removed on the map through a MapRoulette task and the entry deleted from the index. @tas50?

**Comment by bhousel** [comment]
It's ok for the entries to link to defunct companies in Wikidata.   The correct thing to do is what @Adamant36 said, find them all and either remove them from OSM or update them.    

The `brand:wikidata=Q7072246` is the tag that helps people actually do the cleanup, so it should stay as it is..

**Comment by Prince-Kassad** [comment]
I'm a bit confused. O2 still exists, only the Irish subsidiary closed in 2015, The Wikidata entry links to the Irish subsidiary specifically. So why should all the other stores outside of Ireland also be removed even though they definitely exist in the real world?

**Comment by bhousel** [comment]
> So why should all the other stores outside of Ireland also be removed even though they definitely exist in the real world?

Sorry I was confused too.  You said in your initial comment that it was a defunct company that ceased business.
