### ISSUE TITLE
iD wants to use lithuanian shop details in latvia

### ISSUE THREAD

**Issue by richlv** [osmlab/name-suggestion-index#2759]
Continuation from https://github.com/openstreetmap/iD/issues/6495 .

Select this shop in iD: https://www.openstreetmap.org/way/67623510 .

Notice how it says "Aibe has outdated tags".
It suggests these changes:

    + brand=Aibė
    + brand:wikidata=Q1022952
    + brand:wikipedia=de:Aibė
    - name=Aibe
    + name=Aibė

This is incorrect, as it uses Lithuanian character, and the [wikidata entry](https://www.wikidata.org/wiki/Q1022952) points at the Lithuanian website as well.

**Comment by bhousel** [comment]
What do you want it to do instead?

**Comment by richlv** [comment]
The most reasonable and simple solution would be not to suggest these changes at all (in Latvia). Further improvements could be made, but that is likely out of scope for this issue.

**Comment by richlv** [comment]
Yay, thank you for the quick fix :)
