### ISSUE TITLE
Printemps seems to be a missing entry

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2765]
http://www.wikidata.org/entity/Q1535260 Printemps - "French department store chain"

Is it maybe a defunct brand? In that case please report it in comments, optionally you may also add this information to Wikidata.

Is this entry already in our index but without a link? In that case add `brand:wikidata` and `brand:wikipedia` tags. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#female_detective--add-wiki-tags for details.

Is this entry not present in index at all? Then maybe it should be added! See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#card_file_box--about-the-brand-files for more details.

Is this entry already present but with a different link? Maybe new one is more fitting. If not, please comment.

In case that it is not something that should be added to name-suggestion-index or something went wrong - please comment.

Note that name that should be used during tagging may differ from name used as Wikipedia article name or Wikidata label.

**Comment by mmd-osm** [comment]
This one is a bit complicated, Printemps Haussmann, the Printemps flagship store in Paris (https://www.openstreetmap.org/relation/2323870) has a different wikidata id: Q3403689. Besides Printemps has about 21 stores in France: https://www.printempsfrance.com/
