### ISSUE TITLE
Fix damage in OSM caused by a bogus match (Citizens Bank linked to entry about a specific building)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2769]
Mismatch fixed in https://github.com/osmlab/name-suggestion-index/commit/e8ad03a0cd7374a53b081da245352c9239231da5

Preferably to be done after release so iD is not adding new mismatches (I can do it, I have a bot used in a previous fix).

All `brand:wikidata` and `brand:wikipedia` in http://overpass-turbo.eu/s/JM5 probably should be removed

Added in https://github.com/osmlab/name-suggestion-index/commit/d1cb033e4 - looks like an unfortunate mistake

**Comment by bhousel** [comment]
We should really fix the index too, if there are several Citizen's Banks.
https://en.wikipedia.org/wiki/Citizens_Bank

We can just multiple entries with disambiguation text and then iD won't suggest upgrades in those cases.

**Comment by matkoniecz** [comment]
> We should really fix the index too

after https://github.com/osmlab/name-suggestion-index/commit/e8ad03a0cd7374a53b081da245352c9239231da5 it will no longer be in distributed version, though yes - it appears to be more than one institution using this name

**Comment by matkoniecz** [comment]
New version released ( https://github.com/osmlab/name-suggestion-index/releases ), iD is updated - https://github.com/openstreetmap/iD/pull/6543

I will now run fix edit.
