### ISSUE TITLE
Le Méridien seems to be a missing hotel chain brand entry

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#2775]
http://www.wikidata.org/entity/Q261077 Le Méridien - "hotel chain"

Is it maybe a no longer used brand? In that case please report it in comments, optionally you may also add this information to Wikidata.

Is this entry already in our index but without a link? In that case add `brand:wikidata` and `brand:wikipedia` tags. See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#female_detective--add-wiki-tags for details.

Is this entry not present in index at all? Then maybe it should be added! See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#card_file_box--about-the-brand-files for more details.

Is this entry already present but with a different link? Maybe new one is more fitting. If not, please comment.

In case that it is not something that should be added to name-suggestion-index or something went wrong - please comment.

Note that name that should be used during tagging may differ from name used as Wikipedia article name or Wikidata label.

**Comment by bhousel** [comment]
Can you just add them yourself rather than cluttering the GitHub issues with dozens of questions that could be answered in 5 minutes.  This is why I made you a maintainer.

**Comment by matkoniecz** [comment]
> dozens of questions that could be answered in 5 minutes

But note that even if each issue takes 5 minutes to process, there are thousands of them, it is unlikely that I will process even small part of it.

> cluttering the GitHub issues

If it is preferred I may stop creating issues completely. For now I will limit it to cases where local knowledge is necessary. So I will not create further issues like this one, about brands with Wiki page/Wikidata entry not listed in nsi. As discussed at Slack I would be happy to publish it also using other method - for example as spreadsheet.

I can also stop opening any issues at all about missing/wrong data, including cases where local knowledge is necessary.

> add them yourself

So far I opened issue only after closing other issue/PR to avoid just opening issues.

**Comment by bmillemathias** [comment]
> 
> Can you just add them yourself rather than cluttering the GitHub issues with dozens of questions that could be answered in 5 minutes. This is why I made you a maintainer.

(sorry for the side-discussion)

Hi @bhousel 

I take @matkoniecz behavior as a way to openly communicate to all current commiters and potential contributors problems he saw and involve them rather than commiting on its side, for me this is rather a good way of working.

my 2 cents.
