### ISSUE TITLE
Jackson's Stores pointing to wrong Wikidata

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2791]
https://osmlab.github.io/name-suggestion-index/brands/shop/convenience.html#shopconveniencejacksons

"Jacksons" in our index is scoped to countryCode `us` and looking on Overpass seems to be only located in the Pacific Northwest US.  But the `brand:wikidata` and `brand:wikipedia` links to a UK convenience store brand.

So I'm going to remove these tags, and we should clean up the data also after the next iD release.

**Comment by tas50** [comment]
Let me get a real wikidata entry for Jacksons. It's Shell's in house convenience store brand for the PNW.

**Comment by tas50** [comment]
I take back the shell bit. Apparently it's an independent brand. I've never seen it anywhere that isn't a Shell though.

**Comment by tas50** [comment]
Fixed in dc01d25a02de33f1758d97ec588d043bd84c096e
