### ISSUE TITLE
Russian Sberbank erroneously matched to Pridnestrovian Sberbank

### ISSUE THREAD

**Issue by tohaklim** [osmlab/name-suggestion-index#2792]
This one is quite weird.
Russian Sberbank (Q205012) with over 7k entries was somehow matched to a Pridnestrovian bank with a similar name (Q4378147). I am surprised the latter even has a wikidata page.
Pridnestrov'e is an unrecognised state/region in Eastern Europe

**Comment by bhousel** [comment]
I guess this happened because apparently these strings are not the same:
"Сбербанк" and "Cбербанк"

**Comment by bhousel** [comment]
I've tried to sort it out as follows in 380051c6b

* "Sberbank" Q205012 - for their extensive international presence
* "Cбербанк" Q205012 - as it is branded in Kazakhstan/Russia
* "Приднестровский Сбербанк" Q4378147 - for the sub-brand in Moldova
* `matchName` alternate versions that contain an ASCII `c` instead of a Cyrillic `D0A1`

```js

  "amenity/bank|Sberbank": {
    "tags": {
      "amenity": "bank",
      "brand": "Sberbank",
      "brand:wikidata": "Q205012",
      "brand:wikipedia": "en:Sberbank of Russia",
      "name": "Sberbank"
    }
  },

  "amenity/bank|Сбербанк": {
    "countryCodes": ["kz", "ru"],
    "matchNames": [
      "cбербанк",
      "cбербанк россии",
      "сбербанк россии"
    ],
    "tags": {
      "amenity": "bank",
      "brand": "Сбербанк",
      "brand:en": "Sberbank",
      "brand:ru": "Сбербанк",
      "brand:wikidata": "Q205012",
      "brand:wikipedia": "en:Sberbank of Russia",
      "name": "Сбербанк",
      "name:en": "Sberbank",
      "name:ru": "Сбербанк"
    }
  },

  "amenity/bank|Приднестровский Сбербанк": {
    "countryCodes": ["md"],
    "matchNames": ["приднестровский cбербанк"],
    "tags": {
      "amenity": "bank",
      "brand": "Приднестровский Сбербанк",
      "brand:en": "Pridnestrovian Savings Bank",
      "brand:ru": "Приднестровский Сбербанк",
      "brand:wikidata": "Q4378147",
      "brand:wikipedia": "ru:Приднестровский Сбербанк",
      "name": "Приднестровский Сбербанк",
      "name:en": "Pridnestrovian Savings Bank",
      "name:ru": "Приднестровский Сбербанк"
    }
  },

```

**Comment by tohaklim** [comment]
Thanks, I didn’t even notice it was different charsets. 
The Pridnestrovian bank is not really a sub brand, I think they are just using the old Soviet state bank name, which Sberbank of Russia replaced. 
It almost seems like rogue marketing

**Comment by matkoniecz** [comment]
So incorrect data problem is that Q4378147 http://overpass-turbo.eu/s/K7C should not appear outside Transnistria, right?

**Comment by tohaklim** [comment]
Yeah, I believe it is only present there (Transnistria, that's the english name for it!)

**Comment by tohaklim** [comment]
I think this now behaves as intended, and I've reverted the wrong matches found
