### ISSUE TITLE
Burger King has been changed the logo to  "Stranger King"  ( "upside down" marketing campaign )

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2798]
( via - OSM-Talk
"When I try to tag something as the fast-foot chain, Burger King in ID, the preset Burger King logo pops up as an upside down "Stranger King" symbol. "
https://lists.openstreetmap.org/pipermail/talk/2019-June/082725.html )

and it is true  -- the Burger King  logo changed. 
-  https://twitter.com/BurgerKing
-  https://www.facebook.com/burgerking
https://www.facebook.com/burgerking/photos/a.160996107247067/2765720566774595/?type=3&theater

## id Now:
![image](https://user-images.githubusercontent.com/2217320/59557087-c43fdd00-8fd0-11e9-9ac2-52acead9db63.png)

## Twitter - now:
![image](https://user-images.githubusercontent.com/2217320/59557011-da4c9e00-8fce-11e9-83d0-49f1dbcf9de1.png)

## Facebook now:
![image](https://user-images.githubusercontent.com/2217320/59557016-f9e3c680-8fce-11e9-827a-3bfe6670e0b4.png)

**Comment by bhousel** [comment]
Oh yeah, this isn't really wrong, it's just Burger King being playful with their social media accounts.  

This is really  https://github.com/openstreetmap/iD/issues/6361
(on the iD side, we should probably just whitelist the few brands that do this to use their commons logo instead)

**Comment by 1ec5** [comment]
> on the iD side, we should probably just whitelist the few brands that do this to use their commons logo instead

We’ll never be able to keep up with these companies’ brand marketing departments. #2641 should make it possible to avoid special-casing individual brands in iD.
