### ISSUE TITLE
[bank] key:operator vs. Parent_company

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#2816]
Some bank operator is strange for me. ( https://osmlab.github.io/name-suggestion-index/brands/amenity/bank.html )

Imho:  the [Parent company](https://en.wikipedia.org/wiki/Parent_company)  !=  [OSM  Operator](https://wiki.openstreetmap.org/wiki/Key:operator)
 
in my sense:  operator == operating the bank == Usually visible on bills/contracts  with customers;  And has a local tax number ....

So I don't think, that the "National Bank of Greece" is visible on the "Banca Românească" bills ; 

in this case : "National Bank of Greece"  is  _"A parent company is a company that owns enough voting stock in another firm to control management and operation by influencing or electing its board of directors."_
and not the operator.

```
"amenity": "bank"
"brand": "Banca Românească"
"brand:en": "Romanian Bank"
"brand:ro": "Banca Românească"
"brand:wikidata": "Q4854052"
"brand:wikipedia": "ro:Banca Românească"
"name": "Banca Românească"
"name:en": "Popular Bank of Vicena"
"name:ro": "Banca Românească"
"operator": "National Bank of Greece"
"operator:wikidata": "Q1816028"
"operator:wikipedia": "en:National Bank of Greece"
```

![image](https://user-images.githubusercontent.com/2217320/60089193-41d9ba80-9740-11e9-924e-ad943d01f84b.png)
https://en.wikipedia.org/wiki/Banca_Rom%C3%A2neasc%C4%83

**Comment by Adamant36** [comment]
If National Bank of Greece isn't the operator it can probably just be deleted. There isn't a parent_company tag though unfortunately. That said, sometimes the parent company can also be the operator in my opinion and  I still think National Bank of Greece is the operator in this case. It says on the National Bank of Greece's wiki page that it does banking services and that Banca Romaneasca is one of it's accusations. There's no mention of an intermediary firm. I don't know why there would be one either.

**Comment by ImreSamu** [comment]
> That said, sometimes the parent company can also be the operator in my opinion

sometimes  "brand" - "operator" has an
* 1:1 relationships   ( no extra information ; can be added to the wikidata )
* 1:N relationships   ( we can't add to his register - only the local users  )

So I think -  We should remove all `operator=*`  tags from this repo.

>  I still think National Bank of Greece is the operator in this case. It says on the National Bank of Greece's wiki page that it does banking services and that Banca Romaneasca is one of it's accusations. 

imho:
* this is a "Bank group"  ~ a "Bigger Brand".   ( upper in the hierarchy )
* operator is an opposite  ;  ~ subcontractor    ; so always a lower entity in the hierarchy than the "brand"

so "Brand hierarchy"  != "Operator"

**Comment by SilentSpike** [comment]
This is a good point to bring up and something I've also pondered in the past 👍

I' don't personally feel strongly about inclusion/removal of `operator` tags from NSI.

**Comment by ImreSamu** [comment]
> There isn't a parent_company tag though unfortunately. 

The wikidata has 2 Property:
* ["P749:parent organization"](https://www.wikidata.org/wiki/Property:P749) 
* ["P355:subsidiary of a company or organization, opposite of parent organization"](https://www.wikidata.org/wiki/Property:P355) 

example https://www.wikidata.org/wiki/Q1343118  Bank:"Intesa Sanpaolo" -> subsidiary ->  ....

**Comment by Adamant36** [comment]
> So I think - We should remove all operator=* tags from this repo.

I'm not really sure how both the bullet points above lead to removing all operator tags. Both can be true and there would still be legitimate uses of the operator tag. Even if there aren't any in relation to banks. Which I think there are. 

> operator is an opposite ; ~ subcontractor ; so always a lower entity in the hierarchy than the "brand"

To me, an operator is whoever operates the bank. If it's a lower entity then the brand, then it's a lower entity to the brand. If not though, it's not. According to the wiki "The operator tag is used to name a company, corporation, person or **any other entity** who is directly in charge of the current operation of a map object." That doesn't sound like it always applies to a lower entity then the brand to me. 

I've spent A LOT of time working on the bank file and adding banking information to Wikipedia/Wikidata. You can't really generalize like that. There's many different kinds of banks and a bunch of different ways they are ran or operated.

**Comment by Adamant36** [comment]
> The wikidata has 2 Property

Yes Wikidata does, but there isn't equivalent tags to them in OSM. Which is the more important issue.

**Comment by ImreSamu** [comment]
> To me, an operator is whoever operates the bank. 

The bank operator need a "Bank license"   ...   need a local registered number ;  local tax number ...   so the parent company in different country is not the same 
How can you verify - Who "operates" this or that  Bank office ?      

> Yes Wikidata does, but there isn't equivalent tags to them in OSM. Which is the more important issue.

We can invent similar tags  or we can use the wikidata - for storing this information ..

but -  my problem :
*   **we should not store the "parent organisation" info in the `operator=` key   ;    this is different semantic info**
*    in the armchair - nobody has a reliable information about the operator info of any  POI  
     *  except:  discussed in the local OSM mail list and has an agreemnent

**Comment by bhousel** [comment]
This issue with the `operator` tags keeps coming up, see #2471 and #2736

We know the tag is not supposed to be used for parent company, and people keep doing it anyway.  I have told people to stop.

We don't need a tag for parent company because anyone can get this information from wikidata itself.

I'm also inclined to just remove them from the index, since people can not figure out how to use the tag.

**Comment by Adamant36** [comment]
<I'm also inclined to just remove them from the index, since people can not figure out how to use the tag.

Might as well. It doesn't really matter anyway since the information is on Wikidata. Also, I agree with ImreSamu that its hard to get reliable information about the operator from arm chair mapping. So, its not worth keeping if people don't, or can't, use it correctly.

**Comment by 1ec5** [comment]
As a sidenote, some Wikidata entries need to be cleaned up and split because they conflate a bank holding company with another entity, either a parent company or a subsidiary.

(HSBC is a particularly gnarly example that came up recently. In that case, there are multiple levels of corporate hierarchy, another reason to avoid adding `operator` merely because a company “operates” the `brand`.)

**Comment by bhousel** [comment]
Ok, I've removed all the `operator` tags.  I think this is best going forward.
