### ISSUE TITLE
Research needed for: amenity/bank|Millennium Bank

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#282]
#### :thinking: We need help deciding what to do with "amenity/bank|Millennium Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Millennium Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Millennium Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Millennium Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
The information for this bank is already present: https://osmlab.github.io/name-suggestion-index/brands/amenity/bank.html#amenitybankmillennium-bank
Do you think this can be closed?

**Comment by Adamant36** [comment]
Id so go for it. The other Millennium Bank brands outside of Poland aren't really mapped anyway. We can just add new entries for them when they are.
