### ISSUE TITLE
office/insurance|AOK needs fixing

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/name-suggestion-index#2823]
Currently office/insurance|AOK is listed as:

  | "brand": "AOK" "brand:wikidata": "Q295933" "brand:wikipedia": "de:AOK Baden-Württemberg" "name": "AOK" "office": "insurance"
-- | --

AOK is in fact an insurance organization with a number of regional subdiaries, i.e. currently, the NSI entry refers to a single of those local orgs only, which is incorrect pretty much everywhere except for Baden-Württemberg:

- AOK Baden-Württemberg
- AOK Bayern
- AOK Bremen/Bremerhaven
- AOK Hessen
- AOK Niedersachsen
- AOK Nordost (Brandenburg, Berlin, Mecklenburg-Vorpommern)
- AOK NORDWEST (Schleswig-Holstein, Westfalen-Lippe)
- AOK PLUS (Sachsen, Thüringen)
- AOK Rheinland/Hamburg
- AOK Rheinland-Pfalz/Saarland
- AOK Sachsen-Anhalt

I think, https://www.wikidata.org/wiki/Q835141 would be the correct wikidata entry for the umbrella organization. I haven't really researched if there's a Wikidata entry for each of the 11 local subsidiaries.

For actual tagging purposes, it's not clear to me if someone would assign Q835141, or rather the (correct) local org entity, both of which would be valid.

It's complicated, after all.

**Comment by Adamant36** [comment]
From a quick look it seems as though some of them have both their own Wikidata and Wikipedia entries. Although on the Wikidata side the entries lack much information. At least they exist though. So, my recommendation would be to create individual entries for the ones that at least have their own Wikidata/Wikipedia pages and also adding the relevant information to Wikidata about them where need be.

**Comment by bhousel** [comment]
Thanks @mmd-osm - I switched the wiki tags to point to the umbrella organization in 230402af9

Hopefully we can just leave it this way.  If people want the more complicated version where each specific state has their own wikidata/wikipedia, we should probably just remove it from the index entirely (like we did with the sparkassen entries (https://github.com/osmlab/name-suggestion-index/pull/2475#issuecomment-492324960).
