### ISSUE TITLE
New category for shop=swimming_pool

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#2834]
I was looking into adding [Leslie's Swimming Pool Supplies](https://en.wikipedia.org/wiki/Leslie%27s_Poolmart) to the NSI and was planning on tagging it as `shop=swimming_pool` per the wiki: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dswimming_pool .  According to Wikipedia there are approximately 900 stores in the US.  Existing tagging of this brand seems to be all over the place.

Can we add a new NSI category for  `shop=swimming_pool`?

**Comment by SilentSpike** [comment]
You can actually just create a file following the same directory and filename convention to add a brand with tagging not already present in the index 😃

**Comment by tas50** [comment]
https://github.com/osmlab/name-suggestion-index/pull/2835

**Comment by mds08011** [comment]
Thank you both!
