### ISSUE TITLE
Research needed for: amenity/bank|NSB

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#285]
#### :thinking: We need help deciding what to do with "amenity/bank|NSB"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|NSB` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|NSB`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|NSB`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
@Adamant36 could you explain to me, why you think that these are multiple companies? [Overpass Turbo](https://overpass-turbo.eu/s/HfB) returns only banks in Sri Lanka.
Or do you mean this one: https://www.nesb.bank/ which doesn't seem to be mapped on OSM, at least not under this name.

**Comment by Adamant36** [comment]
Hhhmmm, I can't really remember now. Some of that stuff is pretty obscure. I probably could have documented things better with some of them. It might have been NESB and its not like we don't add entries for companies that have zero usage, but feel free to ignore it for now, as it might be to hyper local anyway, and just add the Indian bank. Then we can always add it later if anyone maps it.

**Comment by Adamant36** [comment]
I think it was https://en.wikipedia.org/wiki/Newtown_Savings_Bank. It has fifteen locations. Maybe someone can add it later if need be.
