### ISSUE TITLE
Add Back Yard Burgers

### ISSUE THREAD

**Issue by mapman-44** [osmlab/name-suggestion-index#2875]
https://www.backyardburgers.com/
Approximately 50 locations in the SE US. 
No wikidata entry.

**Comment by Adamant36** [comment]
It seems this already has Wikidata and Wikipedia entries https://www.wikidata.org/wiki/Q2878376

**Comment by Adamant36** [comment]
@mapman-44, you know if this is considered a fast food place? The Wikipedia article says it's "quick serve."

**Comment by mapman-44** [comment]
I ate at one when I was living in North Carolina. I would put in the same
category with other burger places. The home page on their website is filled
with pictures of burgers, and their menu has 8 different burgers. I'm
comfortable with "fast food."

**Comment by Adamant36** [comment]
Thanks @mapman-44. Closed in #2881.
