### ISSUE TITLE
Add Herfy

### ISSUE THREAD

**Issue by waso99** [osmlab/name-suggestion-index#2885]
wikidata (Q5738371)
Country code (SA) 
herfy.com
https://twitter.com/herfyfsc
https://www.instagram.com/herfyfsc/
https://www.facebook.com/herfyfscksa

**Comment by DavidHunterJS** [comment]
I get a permission denied error when I try to push changed that I've made.
I'm using my own github creds when prompted.

**Comment by mds08011** [comment]
#2888
