### ISSUE TITLE
Duplicate entries for Carrefour fuel.  

### ISSUE THREAD

**Issue by BjornRasmussen** [osmlab/name-suggestion-index#2892]
This entry should be deleted: http://osmlab.github.io/name-suggestion-index/index.html?k=amenity&v=fuel#carrefour

... and this one should be updated to include "Carrefour" (without "Market") as a synonym if this is possible: http://osmlab.github.io/name-suggestion-index/index.html?k=amenity&v=fuel#carrefour-market

**Comment by bhousel** [comment]
Thanks for reporting!
