### ISSUE TITLE
CVS branded vending machines

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#2894]
As [reported here](https://www.reddit.com/r/openstreetmap/comments/cdpfln/any_ideas_on_how_to_map_these_newish_cvs_vending/)

My recommendation:
```
amenity=vending machine
brand=CVS
brand:wikidata=Q2078880
brand:wikipedia=en:CVS Pharmacy
vending=chemist
```

**Comment by DavidHunterJS** [comment]
May I give this one a try?

**Comment by bhousel** [comment]
Yes, thank you!
