### ISSUE TITLE
Stop suggesting some amenity=fuel names

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#29]
It seems that the some `amenity=fuel` names shouldn't be suggested at all.
For example, right now we have in OSM 8615 objects with `brand=Shell` and 10228 objects with `name=Shell`

Most probably people are wrongly using `brand` as `name` since the default OSM style doesn't display the `brand` https://github.com/gravitystorm/openstreetmap-carto/issues/1874 (ie, users are tagging for the renderer).

Suggesting such names that clearly are `brand` will just keep feeding the wrong names.

**Comment by bhousel** [comment]
I think for these it's common to use the brand name as the common name that people refer to the place.

We should fill in `name` and `brand` and `brand:wikidata`, which is what #38 is about

**Comment by naoliv** [comment]
It's common because people don't understand `brand` + the editor also suggests to wrongly use `brand` in `name`.

**Comment by naoliv** [comment]
People also wrongly use `brand` in `name` because of this https://github.com/gravitystorm/openstreetmap-carto/issues/1874 for example
In some place we need to stop suggesting brand names in `name` (and this should be in the editors).

**Comment by AntMadeira** [comment]
This is issue is still ongoing and should be corrected. iD still pops a warning to fill the name of a gas station with the brand.
Please, correct this, because it's filling the database with wrong names.

**Comment by bhousel** [comment]
> This is issue is still ongoing and should be corrected. iD still pops a warning to fill the name of a gas station with the brand.
> Please, correct this, because it's filling the database with wrong names.

Can you link to a node where iD shows a warning?
AFAIK if the user picks the "Shell" preset when creating a new gas station, it will default it `brand=Shell` and `name=Shell` (which is definitely not wrong), and mappers are free to change the name to something else like `name=Shell - Morristown", and iD should preserve the name tag and not raise a warning about it.

**Comment by AntMadeira** [comment]
Here's one: https://www.openstreetmap.org/node/2849420428

The default behaviour is definitely wrong. `brand` is different from `name` and iD should not promote this.
Even if the name can coincide with the brand, many times, the fuel station has a brand and a specific name, and if iD fills the name automatically, it is populating the database with wrong and meaningless data. For example, in Brazil, almost all fuel stations have a name, different from the brand. New mappers are encouraged to apply these warnings without knowing this is not right.


> 
> 
> > This is issue is still ongoing and should be corrected. iD still pops a warning to fill the name of a gas station with the brand.
> > Please, correct this, because it's filling the database with wrong names.
> 
> Can you link to a node where iD shows a warning? AFAIK if the user picks the "Shell" preset when creating a new gas station, it will default it `brand=Shell` and `name=Shell` (which is definitely not wrong), and mappers are free to change the name to something else like `name=Shell - Morristown`, and iD should preserve the name tag and not raise a warning about it.

**Comment by bhousel** [comment]
This is the warning I see.. It's prompting me to update the brand tags, but I can set the `name` to whatever I want:

<img width="290" alt="Screen Shot 2021-10-31 at 12 08 30 PM" src="https://user-images.githubusercontent.com/38784/139592388-421491bb-93f3-4f91-b44d-dd4e2c640149.png">

If I choose to upgrade it, I get this - that's what you want yes?

<img width="290" alt="Screen Shot 2021-10-31 at 12 10 16 PM" src="https://user-images.githubusercontent.com/38784/139592456-ce2f1710-76fc-464b-a2c6-118000343cf2.png">

**Comment by 1ec5** [comment]
> Here's one: https://www.openstreetmap.org/node/2849420428

This node was originally [tagged](https://www.openstreetmap.org/changeset/22260517) `name=GALP` a long time ago, manually, before the NSI-based validator was ever implemented. Later, it was [tagged](https://www.openstreetmap.org/changeset/108058768) `brand=GALP` manually using OsmAnd. Were you expecting iD to automatically _remove_ the `name` from the node when you [recently used iD](https://www.openstreetmap.org/changeset/113199456) to add the `brand:wikidata` and `brand:wikipedia` tags?

**Comment by AntMadeira** [comment]
The problem is when you don't fill the name field. The warning still pops up.
If you don't know the name and the brand is correct, iD should not show the warning and should not fill the name field with the brand.

> 
> If I choose to upgrade it, I get this - that's what you want yes?
> 
> <img alt="Screen Shot 2021-10-31 at 12 10 16 PM" width="290" src="https://user-images.githubusercontent.com/38784/139592456-ce2f1710-76fc-464b-a2c6-118000343cf2.png">

**Comment by AntMadeira** [comment]
iD should not remove the name, but it also should not pop up a warning if the name field is empty and, worse, fill it with the brand.


> 
> 
> > Here's one: https://www.openstreetmap.org/node/2849420428
> 
> This node was originally [tagged](https://www.openstreetmap.org/changeset/22260517) `name=GALP` a long time ago, manually, before the NSI-based validator was ever implemented. Later, it was [tagged](https://www.openstreetmap.org/changeset/108058768) `brand=GALP` manually using OsmAnd. Were you expecting iD to automatically _remove_ the `name` from the node when you [recently used iD](https://www.openstreetmap.org/changeset/113199456) to add the `brand:wikidata` and `brand:wikipedia` tags?

**Comment by AntMadeira** [comment]
In short, this suggestion should not be made:
![firefox_b8hzXlHobo](https://user-images.githubusercontent.com/34066528/139592954-4af013ff-9cf0-4183-8e55-b5692e69e08c.png)

**Comment by bhousel** [comment]
@AntMadeira I hear what you're saying, but I'm having a hard time seeing how `name=GALP` is _worse_ than having no name at all.  I really feel like most people would feel oppositely. 

You can change the name to whatever you want, but the gas station should have _some name_ right?  People who use maps expect the markers to be labeled with something.

**Comment by tas50** [comment]
I have to agree with @bhousel on this one. OSM is full of gas stations with no names that don't display correctly and it's really problematic. If a gas station has a non brand name that should be set but the brand is better than no name at all.

**Comment by AntMadeira** [comment]
Not every element as name, for the most various reasons. Usually, a fuel station has a name, but you may not fill it because you didn't notice it, hadn't time to right it down, etc. If you're "forcing" people to apply a name, that's worse than having no name at all. Apps show fuel stations as POI, even if there's no name present. The brand will show, and the name will also show if it exists, not because iD decided it should exist.

I think the wiki is very helpful on this:
https://wiki.openstreetmap.org/wiki/Names
