### ISSUE TITLE
Add House of Hoops by Foot Locker

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#2901]
eg https://news.nike.com/news/nike-and-foot-locker-unwrap-dream-basketball-store
https://sneakernews.com/2015/01/14/foot-locker-house-hoops-open-largest-location-ever-nyc/
https://stores.footlocker.com/us/ny/new-york/11-west-34th-street.html

This is not exactly Foot Locker, so I think it needs a new entry.

**Comment by LuisMBarrera** [comment]
@yoasif Hey already added this to shop/shoes, waiting for reviews.

**Comment by LuisMBarrera** [comment]
Hey @doublah sorry for dragging you here but I would like to take on your offer of reviewing future PRs, the only problem is that I couldn't add or find how to add reviewers. I'm sorry for the hassle.
