### ISSUE TITLE
Add Bulmag Supermarkets brand

### ISSUE THREAD

**Issue by roshavagarga** [osmlab/name-suggestion-index#2911]
Item has no wikidata. Bulmag (locally also transliterated as Булмаг) is a Bulgarian supermarket chain. More info on its stores' location here: https://www.bulmag.org/bg/pages/locations-222.html

Brand Logo can be legally sourced from: https://www.facebook.com/BulMagSupermarkets

**Comment by ENT8R** [comment]
Is it more common to say "Булмаг" or "Bulmag" when you want to refer to this store?

**Comment by roshavagarga** [comment]
The company writes it out as 'BulMag' on their website and store fronts. You would use Булмаг when writing, as Cyrillic is the official alphabet. The LTD or whatever is 100% written using Cyrillic, as using Latin is against the law. Personally, if I was searching for it online, I'd use the Cyrillic version first and if that didn't work out - I'd try the Latin one. Which one to use is a bit ambiguous honestly :/

**Comment by ENT8R** [comment]
Thank you for your quick reply! 👍 
I added it now with "Булмаг" as the main name and "BulMag" as how you would refer to it when you are not using the cyrillic alphabet.

**Comment by roshavagarga** [comment]
No worries, thank you for going through the trouble and adding it :) The addition seems appropriate, thank you for the hard work!
