### ISSUE TITLE
Add La Colombe Coffee Roasters

### ISSUE THREAD

**Issue by quincylvania** [osmlab/name-suggestion-index#2912]
https://en.wikipedia.org/wiki/La_Colombe_Coffee_Roasters
https://www.lacolombe.com

**Comment by mds08011** [comment]
These appears to be a [`amenity=cafe`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe) that also sell coffee beans rather than a [`shop=coffee`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcoffee).  Does that seem correct?

**Comment by quincylvania** [comment]
@mds08011 Yep, these are Starbucks-equivalent in form.

**Comment by mds08011** [comment]
I used `name=La Colombe Coffee Roasters` and `short_name=La Colombe` based on what I saw on the website and street level imagery but let me know if you think otherwise.

https://github.com/osmlab/name-suggestion-index/commit/45d94dcde4997631cc5d1692bb4e0aefbecaedd5

**Comment by quincylvania** [comment]
> I used name=La Colombe Coffee Roasters and short_name=La Colombe based on what I saw on the website and street level imagery but let me know if you think otherwise.

That sounds good. Thanks for adding it!
