### ISSUE TITLE
#IL Патио

### ISSUE THREAD

**Issue by literannn** [osmlab/name-suggestion-index#2913]
Please fix amenity/restaurant|IL Патио cuisine - it's Italian, not american. Prooflink: https://ilpatio.ru/upload/iblock/052/ip_core_menu_msc.pdf

**Comment by mds08011** [comment]
Fixed: https://github.com/osmlab/name-suggestion-index/blob/master/brands/amenity/restaurant.json#L884

Thanks for catching that!
