### ISSUE TITLE
Some Canadian chains not connecting

### ISSUE THREAD

**Issue by bkissin** [osmlab/name-suggestion-index#2919]
Hello everyone! I just tried to connect brands to a St-Hubert and a Mike's location in Moncton, NB using iD and they didn't come up as options. Am I doing something wrong in iD, or is there a problem with the code in the index?

**Comment by mds08011** [comment]
The NSI gets packaged up and incorporated into iD at periodic intervals (typically monthly).  You can check the “releases” page to see when this last happened (26 days ago): https://github.com/osmlab/name-suggestion-index/releases

My guess is that St-Hubert and Mike's are in the NSI but have not been brought into iD yet.

**Comment by bkissin** [comment]
Oh! OK, cool! Thanks for letting me know!

**Comment by mds08011** [comment]
You have great timing!  In the past few hours:

1. An NSI was created: https://github.com/osmlab/name-suggestion-index/releases/tag/v3.1.0
2. NSI was included with iD version 2.15.4: https://github.com/openstreetmap/iD/releases/tag/v2.15.4
3. It went live on openstreetmap.org: ![image](https://user-images.githubusercontent.com/8010709/61970821-68368400-af92-11e9-9626-9ff4fb61828b.png)
4. And now you should be able to map those brands in iD:

![image](https://user-images.githubusercontent.com/8010709/61971199-5acdc980-af93-11e9-8468-09046363ff4a.png)
