### ISSUE TITLE
Research needed for: amenity/bank|PKO BP

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#294]
#### :thinking: We need help deciding what to do with "amenity/bank|PKO BP"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|PKO BP` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|PKO BP`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|PKO BP`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by maraf24** [comment]
The bank is now using slightly different spelling - "PKO Bank Polski".

**Comment by matkoniecz** [comment]
@maraf24 So iD should suggest `name=PKO Bank Polski` over `name=PKO BP`, rather than reverse as it is doing now?

**Comment by maraf24** [comment]
> Links: https://pl.wikipedia.org/wiki/Powszechna_Kasa_Oszcz%C4%99dno%C5%9Bci_Bank_Polski https://www.wikidata.org/wiki/Q578832
> 
> @maraf24 So iD should suggest `name=PKO Bank Polski` over `name=PKO BP`, rather than reverse as it is doing now?

Now I'm 100% sure only spelling "PKO Bank Polski" is in use.
