### ISSUE TITLE
Boys and Girls Club

### ISSUE THREAD

**Issue by bkissin** [osmlab/name-suggestion-index#2942]
Good morning all! 

I was going to add the Boys and Girls Club to the list, but I'm trying to determine where we would place them? 

Would we say it is amenity=community_centre or amenity=social_centre?

**Comment by 1ec5** [comment]
I’ve [tagged it](https://www.openstreetmap.org/way/114649255) as `amenity=social_facility` `social_facility=outreach` `social_facility:for=child` in the past, but I could see after-school programs alternatively being tagged as `amenity=community_centre`.

**Comment by Adamant36** [comment]
They give kids mentors and stuff like that right? If so, I'd assume they have case managers etc also. I see that more as a social facility doing outreach type thing then a community center.

**Comment by DavidMoraisFerreira** [comment]
Hi,
Shouldn't those be tagged as [club=scout](https://wiki.openstreetmap.org/wiki/Tag:club%3Dscout)?

**Comment by tas50** [comment]
Boys and Girls club isn't a Boy Scout type thing. They provide after school programs for kids: https://www.bgca.org/

**Comment by DavidMoraisFerreira** [comment]
> 
> 
> Boys and Girls club isn't a Boy Scout type thing. They provide after school programs for kids: https://www.bgca.org/

Oh, my bad! Sorry :)

**Comment by bhousel** [comment]
This showed up in 83047ee
