### ISSUE TITLE
Research needed for: amenity/bank|PNB

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#295]
#### :thinking: We need help deciding what to do with "amenity/bank|PNB"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|PNB` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|PNB`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|PNB`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bhousel** [comment]
You can use Overpass Turbo to see where the features exist in OSM:
https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#using-overpass-turbo

If it's not really clear what people mean by "PNB", we can just discard it from the index..

**Comment by aestevens** [comment]
Thanks, @bhousel. The "PNB" name actually does a better job of capturing Philippine National Bank locations based on the results from Overpass Turbo, BUT it also matches 1 location for Punjab National Bank in India. Should I just remove the entry for Philippine National Bank and add the Philippine National Bank as a `match` tag on PNB? That seems like the best course, but that 1 result for Punjab National Bank has me second-guessing. Thoughts?

**Comment by codehard-achal** [comment]
Hi @aestevens, Achal Singh here from India! I think you should keep the 'PNB' tag for Philippine National Bank and for Punjab National Bank you can have a tag 'PJNB', if this suggestion sounds good, give me a **_go-ahead_** and I'll do the needful. Cheers!
