### ISSUE TITLE
Add masymas retail store brand

### ISSUE THREAD

**Issue by carstenhag** [osmlab/name-suggestion-index#2959]
Hey, noticed today that this spanish supermarket chain is not available yet.

https://www.wikidata.org/wiki/Q6135987
https://es.wikipedia.org/wiki/Supermercados_Masymas

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/commit/8acdd52576075031e38e0ac1e9f8db1394055026
