### ISSUE TITLE
Add github issue templates for this repo

### ISSUE THREAD

**Issue by carstenhag** [osmlab/name-suggestion-index#2960]
Hey, to make it easier for users to request brand additions and to better have all needed information in the issues, issue templates could be added to this repo.

See https://help.github.com/en/articles/creating-issue-templates-for-your-repository for more information about this

**Comment by bhousel** [comment]
Thanks for the suggestion, I've added a template for submitting a brand request.

**Comment by carstenhag** [comment]
Lovely, thanks!
