### ISSUE TITLE
Add The Grocery Outlet (Canada)

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#2964]
**Brand Name**
The Grocery Outlet

**Brand Wikidata**
Q16062155

**Brand Wikipedia**
https://en.wikipedia.org/wiki/The_Grocery_Outlet_(Canadian_grocer)

**OSM Tags**
`shop=supermarket`

**Country Codes (if any)**
ca

**Anything else?**
Be sure to include the Canada country code to distinguish it from the US [Grocery Outlet](https://en.wikipedia.org/wiki/Grocery_Outlet)

**Comment by Adamant36** [comment]
Thanks @mds08011 I Added it in 2b5e007.
