### ISSUE TITLE
Add Éxito

### ISSUE THREAD

**Issue by quincylvania** [osmlab/name-suggestion-index#2965]
**Brand Name**
Éxito

**Brand Wikidata (if there is one)**
https://www.wikidata.org/wiki/Q861947

**Brand Wikipedia (if there is one)**
https://en.wikipedia.org/wiki/Grupo_%C3%89xito

The Wikidata and Wikipedia pages are for the parent company, Groupo Éxito, but this brand should just be for the "Éxito" brand department stores.

**OSM Tags**
`shop=department_store`

Similar to Walmart, they sell all kinds of things including clothes, electronics, groceries, etc.

**Country Codes (if any)**
Primarily Colombia, but possibly other South American countries too.

**Comment by shiraazAh** [comment]
Groupo Éxito has stores in Colombia, Brasil, Uruguay and Argentina. But just the "Éxito" brand department stores are only in Colombia and i couldn't find any brand wikidata or wikipedia for that.

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/commit/097759eccc6c03a2dd1c7b6a14cd3acbe17ffc50

**Comment by quincylvania** [comment]
@mds08011 Thanks! I forgot we could still add brands without wiki tags 😅
