### ISSUE TITLE
Taiwanese convenience stores mixed up with same name brands

### ISSUE THREAD

**Issue by tntchn** [osmlab/name-suggestion-index#2982]
I'd mentioned that there might has a duplicated tag in Chinese version "FamilyMart" (全家/全家便利商店)
https://github.com/osmlab/name-suggestion-index/blob/57850f1e14697b61ff3b1b4ca239a8473640c775/brands/shop/convenience.json#L2490-L2511
It was a mistake because the zhwiki article 全家便利商店 (Q10891564) point to the operator of FamilyMart in Taiwan but not the brand page.

But I support that keep the tag separated between mainland China and Taiwan because different operators and different names accustomed. This is my opinion of the edit:

```javascript
"shop/convenience|全家": { 
   "countryCodes": ["cn"], 
   "tags": { 
     "brand": "全家", 
     "brand:en": "FamilyMart", 
     "brand:wikidata": "Q1191685", 
     "brand:wikipedia": "zh:FamilyMart", 
     "name": "全家", 
     "name:en": "FamilyMart", 
     "shop": "convenience" 
   } 
 }, 
 "shop/convenience|全家便利商店": { 
   "countryCodes": ["tw"], 
   "tags": { 
     "brand": "全家便利商店", 
     "brand:en": "FamilyMart", 
     "brand:wikidata": "Q1191685", 
     "brand:wikipedia": "zh:FamilyMart", 
     "name": "全家便利商店", 
     "name:en": "FamilyMart", 
     "shop": "convenience" 
   } 
 }, 
```

### Furthermore, there is a same problem at the tag 'shop/convenience|OK便利商店'

https://github.com/osmlab/name-suggestion-index/blob/57850f1e14697b61ff3b1b4ca239a8473640c775/brands/shop/convenience.json#L1035-L1047

There are some facts shows that "OK便利店" (Hong Kong) and "OK超商" (Taiwan, aka OK便利商店 but the former name is more official) have no relationship now:
* **OK便利店** is Hong Kong-based and has the license of Circle K (US), using "Circle K" in English and the operating region is Hong Kong, Macau, and Guangzhou, China.
* **OK超商** is Taiwan-based, former Circle K of Taiwan but had stopped the partnership for a long time. Operates in Taiwan and using "OK超商" and "OK mart" as brand name.
It will be better to separate them into two brands to avoid editing mistakes:
```javascript
 "shop/convenience|OK便利店": { 
   "countryCodes": ["cn"],     // not sure if "hk" and "mo" are supported
   "matchNames": ["circle k"], 
   "tags": { 
     "brand": "OK便利店", 
     "brand:en": "Circle K", 
     "brand:wikidata": "Q3268010", 
     "brand:wikipedia": "zh:OK便利店", 
     "name": "OK便利店", 
     "name:en": "Circle K", 
     "shop": "convenience" 
   } 
 "shop/convenience|OK超商: { 
   "countryCodes": ["tw"], 
   "tags": { 
     "brand": "OK超商", 
     "brand:en": "OK mart", 
     "brand:wikidata": "Q10851968", 
     "brand:wikipedia": "zh:OK超商", 
     "name": "OK超商", 
     "name:en": "OK mart", 
     "shop": "convenience" 
   } 
```

And finally it will be better if the English name of another convenience store in Taiwan "萊爾富" could be fill in at the same time:
```
'shop/convenience|萊爾富'
+ "brand:en": "Hi-Life"
+ "name:en": "Hi-Life"
```
(ref: https://www.facebook.com/hihilife/ )

**Comment by mds08011** [comment]
Thank you for looking into these!
