### ISSUE TITLE
Doubt about if "永和豆漿" is a brand or not

### ISSUE THREAD

**Issue by tntchn** [osmlab/name-suggestion-index#2983]
I found that the brand name "永和豆漿" was added into the restaurant list in https://github.com/osmlab/name-suggestion-index/issues/943, and that makes confused because I think that "永和豆漿" is not a name of a brand but a operation type of restaurants like _bistro_ or _cafe_.

**永和豆漿** (Yonghe Soymilk) was a breakfast shop mainly selling soymilk originally, but now represent the shops which sell chinese breakfast and late night meal, some of them open from night to midnight to morning.

There are no brand called "永和豆漿", but are some brands have similar names: "永和豆漿大王", "世界豆漿大王" (the earliest 永和豆漿 shop), "四海豆漿大王", "台北永和豆漿", each of them all have more than 30 franchisee all around in Taiwan.

BTW there is a Taiwanese businessman opened a brand "永和豆浆" (simplified 永和豆漿) in mainland China and have more than 500 branches and franchisee mainland China, but no branch in Taiwan.
https://overpass-turbo.eu/s/LIl

**Comment by bhousel** [comment]
Thanks for letting us know!   I will remove "永和豆漿" from the index as a generic name..  

I'll also add a placeholder entry for "永和豆浆" the brand in mainland china with 500 branches.  This entry won't show up in editors yet until we match it to a `brand:wikidata` tag.
