### ISSUE TITLE
Name error in "Domino's Pizza" entry

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#2994]
The entry amenity/fast_food|Domino's Pizza has name and brand equal to "Domino's Pizza". But according to https://en.wikipedia.org/wiki/Domino%27s_Pizza the chain is now branded simply as "Domino's". Web images show stores and packaging using just this one word.

I don't know if this applies world-wide, but there certainly seems to be a number of countries in which "Domino's Pizza" is not the correct name or brand to use, so the Name Suggestion Index should not be suggesting this.

**Comment by Adamant36** [comment]
Seems valid. If it does get changed the current Maproulette challenge will have to rename Dominos Pizza to Domino's Pizza will have to be canceled. @tas50

**Comment by tas50** [comment]
Let me hide that challenge for now

**Comment by bhousel** [comment]
Sounds good - I will change the name 👍 
This is a great example of how the index can help identify and retag POIs that have older names when a business updates their branding.
