### ISSUE TITLE
bakery "Schäfer" gets matched to "Schäfer's"

### ISSUE THREAD

**Issue by Prince-Kassad** [osmlab/name-suggestion-index#2995]
A bakery called "Schäfer" will automatically get matched to a bakery chain called "Schäfer's".

"Schäfer" is such a common name in Germany there are hundreds of independent bakeries called "Schäfer", which now get incorrectly matched to the chain despite there being no relation. There have been a number of reverts in the past, ex. https://www.openstreetmap.org/changeset/74187565

The match should just be removed.

**Comment by bhousel** [comment]
Ok I removed the match.

For what it's worth, looks like there are a bunch of these in OSM currently:
https://overpass-turbo.eu/s/McS

Many of them seem to be operating as branches of this Schäfer brand:
https://www.schaefer-dein-baecker.de/
This brand does not have a wikipedia/wikidata entry that I can find, so I've filtered it out for now.  If someone ever adds a wikidata for it, we can support it in the index.  

(This Schäfer is different from the other Schäfer's brand we already support with [Q1464562](https://www.wikidata.org/wiki/Q1464562))
