### ISSUE TITLE
Chemist/pharmacy confusion

### ISSUE THREAD

**Issue by pmailkeey** [osmlab/name-suggestion-index#30]
I note iD is now showing chemist chains (e.g. Boots, Rowlands, Lloyds, Numark, Well*) as 'amenity pharmacy' when in fact they are building=retail' 'shop=chemist' and should have pharmacy=yes by default. Asda (wal*Mart) in uk often has a pharmacy and pharmacy=yes is more appropriate than a separate 'amenity=pharmacy' - I think. Some have opticians in store too.

That raises the question as to how a mailbox should be shown in Asda - as a node can be used to show the location where as mailbox=yes as a subtag on the building doesn't.

* note chain 'Well' is the name but the branding is displayed as '+Well' - which is how I first came across it - but is in fact incorrect.

**Comment by math1985** [comment]
Note that in the Netherlands, and possibly other countries as well, Boots actually run pharmacies rather than chemists.

**Comment by math1985** [comment]
Boots, Rowlands, Lloyds, Numark and Well are currently (much) more often tagged as amenity=pharmacy than shop=chemist. If you'd like to change this, I'd recommend discussing this with the UK community first. For Boots I can follow your reasoning, but for for example Lloyds, pharmacy seems right to me.

I'm closing this issue for now.

**Comment by bhousel** [comment]
Yeah I agree that we get this wrong in iD.  We do have a `shop=chemist` preset, but we display the word "Chemist" and we show an icon of a little chemistry beaker.   US speakers are not familiar with the UK usage of this word.

We should instead encourage `amenity=pharmacy` to be tagged as a point node within drug stores or whatever other business. This makes more sense because:
1. the pharmacy department is usually a separate entity with different phone number and operating hours
2. pharmacies frequently exist in other non-drug stores, supermarkets (Walmart, Costco, etc)

In my mind the ideal steps going forward would be to:

1. clarify position with tagging lists

2. update wiki

3. update iD to:
  - rename `shop=chemist` preset to say "Drug Store" and change icon.
  - make sure `amenity=pharmacy` says "Pharmacy" and appears only on nodes

4. update name-suggestion-index

5. maproulette challenge to clean up existing chemist/pharmacy mixups 


reopen if you agree?

**Comment by math1985** [comment]
> We should instead encourage amenity=pharmacy to be tagged as a point node within drug stores or whatever other business.

This makes sense in the US, and increasingly in the UK, but not in continental Europe. In continental Europe, pharmacies are usually dedicated businesses in their own buildings. Chemists might have a pharmacy section too

A pharmacy in the Netherlands:
![pharmacy](https://apotheekelderveld.leef.nl/media/auguria/sliders/resized/1122x559/Elderveld-2.jpg)

A chemist in the Netherlands:
![chemist](http://www.drogisterijperton.nl/img/winkel.jpg)

**Comment by math1985** [comment]
> We should instead encourage amenity=pharmacy to be tagged as a point node within drug stores or whatever other business.

This makes sense in the US, and increasingly in the UK, but not in continental Europe. In continental Europe, pharmacies are usually dedicated businesses in their own buildings. They normally sell only medicines, and no cosmetics/cleaning stuff. They might have a few self-service racks, but most of the products are hidden behind the counter. Chemists on the other hand have a wide range of products including cosmetics, cleaning stuff, candy, etc. Usually all products are self-service. All chemists sell over the-counter-medicine like paracetamol/tylenol, some (depending on the country legislation) might also have a pharmacy section with the full range of medicines.

A pharmacy in the Netherlands:
![pharmacy](https://apotheekelderveld.leef.nl/media/auguria/sliders/resized/1122x559/Elderveld-2.jpg)

A chemist in the Netherlands:
![chemist](http://www.drogisterijperton.nl/img/winkel.jpg)

**Comment by bhousel** [comment]
ok.. Aside from the "dedicated building" difference, it does sound like we're talking about the same thing.   We should probably fix this, right?

**Comment by math1985** [comment]
I disagree in particular with 'make sure amenity=pharmacy [..] appears only on nodes', the rest sounds fine to me.

**Comment by bhousel** [comment]
No problem, I amended my comment above.. We don't need to restrict `amenity=pharmacy` to nodes.

**Comment by math1985** [comment]
Within the scope of this project I still don't see anything we can do, by the way.

**Comment by pmailkeey** [comment]
Hi,

Does OSM language choice permit different labelling - so where UK sees
'Chemist' US sees 'Drug Store' ? Or is there a better globally acceptable
name ? (In the UK a 'drug store' isn't generally recognised and would
likely to be taken as a place to purchase recreational (or illegal) drugs.
Also in the past (not sure if still possible) but chemists used to be able
to supply chemicals for non-human use - for example, sulphuric acid for car
batteries. Boots, the most famous uk retailer in this field traded with the
tag-line "Boots the Chemist".

Another outlet in this area are 'health food shops' which may also sell
homeopathic 'remedies' - but unlike 'chemists' won't sell deodorants,
toothbrushes or sunglasses.

Liking the 'node idea' of pharmacy - but clearly should be possible to be a
building area (amenity) where the building is uniquely a pharmacy.

-- 
Mike.

Abuse of the vulnerable <https://abuseofaudreypaley.wordpress.com/the-abuse>
- please sign and spread the word about this petition
<https://www.change.org/p/protect-the-protectors-with-edna-s-law-need-one-law-for-all-whistleblowers>
from
Compassion in Care <http://www.compassionincare.com>.

Retire at 60 petition:
http://you.38degrees.org.uk/petitions/let-men-and-women-retire-at-60-with-a-state-pension


@millomweb <https://sites.google.com/site/millomweb/index/introduction> -
For all your info on Millom and South Copeland
via *the area's premier website - *

*currently unavailable due to the country's ongoing harassment of me, my
family, property & pets*

T&Cs <https://sites.google.com/site/pmailkeey/e-mail>

**Comment by bhousel** [comment]
> Does OSM language choice permit different labelling - so where UK sees
> 'Chemist' US sees 'Drug Store' ? Or is there a better globally acceptable
> name ?

We can have separate labeling in iD (and I'll set this up for Drug Store / Chemist), but not generally in OSM.

**Comment by pmailkeey** [comment]
On 28 June 2016 at 14:46, Bryan Housel <notifications@github.com> wrote:

> Does OSM language choice permit different labelling - so where UK sees
> 'Chemist' US sees 'Drug Store' ? Or is there a better globally acceptable
> name ?
>
> We can have separate labeling in iD (and I'll set this up for Drug Store /
> Chemist), but not generally in OSM.
>
>
That's surprising as I'd have expected OSM to be completely multilingual.

-- 
Mike.

Abuse of the vulnerable <https://abuseofaudreypaley.wordpress.com/the-abuse>
- please sign and spread the word about this petition
<https://www.change.org/p/protect-the-protectors-with-edna-s-law-need-one-law-for-all-whistleblowers>
from
Compassion in Care <http://www.compassionincare.com>.

Retire at 60 petition:
http://you.38degrees.org.uk/petitions/let-men-and-women-retire-at-60-with-a-state-pension


@millomweb <https://sites.google.com/site/millomweb/index/introduction> -
For all your info on Millom and South Copeland
via *the area's premier website - *

*currently unavailable due to the country's ongoing harassment of me, my
family, property & pets*

T&Cs <https://sites.google.com/site/pmailkeey/e-mail>

**Comment by 1ec5** [comment]
This change has the potential to cause a lot of confusion, and it should be discussed more widely before being implemented in iD: openstreetmap/iD#3213.

**Comment by math1985** [comment]
> it should be discussed more widely

+1. This is (obviously) not the place for tagging discussions, or discussions on how tags should be called in iD.

**Comment by 1ec5** [comment]
I started a discussion on the [talk-us](https://lists.openstreetmap.org/pipermail/talk-us/2016-July/016519.html) and [tagging](https://lists.openstreetmap.org/pipermail/tagging/2016-July/029569.html) lists.

**Comment by 1ec5** [comment]
Possibly of interest: openstreetmap/iD#4127.

**Comment by bhousel** [comment]
Happy 2019!
Now seems like as good a time as any to rename "Pharmacy" to "Pharmacy Counter" in iD, so I did that in https://github.com/openstreetmap/iD/commit/a1bc6b3e31a899179b98bb51d402db518192a68a

Since around 2015 some people ([see wiki talk page](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dpharmacy)) have suggested mapping 2 features:  the outer store as a `shop=chemist` (aka "Drug Store") and the inner pharmacy counter as an `amenity=pharmacy`.  This makes sense, as they often have separate `opening_hours` and contact information, and it's also the only way that works when a pharmacy operates a separate space inside a larger business like a Target or Costco.

Hope this change helps clear up the previous `chemist` vs `pharmacy` confusion!
