### ISSUE TITLE
Research needed for: amenity/bank|Postbank Finanzcenter

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#300]
#### :thinking: We need help deciding what to do with "amenity/bank|Postbank Finanzcenter"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Postbank Finanzcenter` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Postbank Finanzcenter`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Postbank Finanzcenter`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by moritzsternemann** [comment]
"Postbank Finanzcenter" is the german name for branch offices of the "Postbank". `config/canonical.json` list both, "Postbank" and "Postbank Finanzcenter". How should I proceed?

**Comment by bhousel** [comment]
If they are the same thing, add a `"match"` property to the better entry, and delete the worse entry.

```
"amenity/bank|Postbank": {
    "count": 588,
    "match": ["amenity/bank|Postbank Finanzcenter"],
    "tags": {
      "amenity": "bank",
      "brand": "Postbank",
      "name": "Postbank"
    }
  },
```
Also make sure to add `brand:wikidata` and `brand:wikipedia` tags - that's what we're really looking for.
