### ISSUE TITLE
Add Wetherspoons Pub

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3009]
Brand Name
Wetherspoons (also referred to as J D Wetherspoon, JD Wetherspoon, Wetherspoon in current tags)
amenity=pub

Country Codes:
gb, ie

https://www.jdwetherspoon.com/pubs/all-pubs
Pretty much all Wetherspoons are seperately named pubs with wetherspoon branding (going by their website, only 9 out of the almost 900 pubs have "Wetherspoon(s)" in the name).
This means most current tagging is very inconsistent with most currently using various operator= tags (see https://taginfo.openstreetmap.org/search?q=Wetherspoon#values and https://taginfo.openstreetmap.org/search?q=Wetherspoons#values )

Wiki:
https://en.wikipedia.org/wiki/Wetherspoons
https://www.wikidata.org/wiki/Q6109362

**Comment by tohaklim** [comment]
Wondering if this might work with an operator matchnames string.
This would also need to preserve the current name tag

**Comment by bhousel** [comment]
This was done in #3103 🍻

**Comment by doublah** [comment]
Would still be nice if we had a way to matchnames for operators, plus needs an ie country code.

**Comment by bhousel** [comment]
> Would still be nice if we had a way to matchnames for operators, plus needs an ie country code.

Good catch, I added the `ie` code in 21aec5792

We don't include operator tags in this index because they have historically been misused, but we will probably add something eventually.
(see #2816, but we are considering relaxing this rule per #2928)

**Comment by doublah** [comment]
Reopening as was undone in b9c20873f

Probably need to think about a better way to deal with brands with obvious branding like this but with unique location names.

**Comment by UKChris-osm** [comment]
I'm not sure how well linked the NSI is with the iD Editor, but for a brand like Wetherspoon, could the matching occur if someone were to add a node or way and search for the tag "JD Wetherspoon", and have the name element itself appear within iD (like a preset) yet remain empty, and hence invite the mapper to add the name?

 "amenity/pub|JD Wetherspoon": {
    "countryCodes": ["gb"],
    "matchNames": [ "JD Wetherspoons", "Wetherspoons", "Wetherspoon"],
    "tags": {
      "amenity": "pub",
      "brand": "JD Wetherspoon",
      "brand:wikidata": "Q6109362",
      "brand:wikipedia": "en:Wetherspoon",
      "name": **REQUIRED**
    }
  }

... or does the **name** within the tags section need to match that at the start of the "amenity/pub|**name**"??

**Comment by bhousel** [comment]
> ... or does the **name** within the tags section need to match that at the start of the "`amenity/pub|name`"??

☝️ yes, it's this.  All the code in this project is written to treat the identifier as `key/value|name`.  For many years, both the NSI project and iD treated the `name` tag as the only identifier.  `brand` tags and wikidata were not a thing until 2018.  ([see my talk](https://2019.stateofthemap.us/program/sat/mapping-brands-with-the-name-suggestion-index.html) for some history!)

Also, the index is only set up to work with `brand` keys (not `network` or `operator`), so this is another obvious limitation that we want to move beyond.  So we can map transit features, or other things where the operator is really the identifier.

I do want to relax these limitations eventually!  For now, just try to add things to the index that are consistently named.

**Comment by bhousel** [comment]
> I do want to relax these limitations eventually! For now, just try to add things to the index that are consistently named.

Update on the above - the `name` field is not strictly required anymore now that we have new identifiers (#3995) and more flexible code to work with them  🎊

**Comment by UKChris-osm** [comment]
Wetherspoon added back via [50059d4](https://github.com/osmlab/name-suggestion-index/commit/50059d45f93d04bcaaa4c72aa2fe1db1880a8254), minus the "_name_" tag.

**Comment by UKChris-osm** [comment]
I'm not really up on Wikimedia uploads, but as Wetherspoon doesn't have any social media links, and as such doesn't have any logo associated with the entry in the NSI at the moment, would the [app icon](https://www.jdwetherspoon.com/~/media/images/app/new-logo.png?h=400&w=400&la=en&hash=3F14D651883A431658C39F9D9B04095951A4CDF2) be suitable as a Wikimedia upload? Would it even be allowed?

**Comment by ArloJamesBarnes** [comment]
Yes, I think that would be well within the originality limits per PD-textlogo. I can make and upload an SVG version if you'd like.

**Comment by UKChris-osm** [comment]
@ArloJamesBarnes If you're able to do that it would be great 🥇

**Comment by kymckay** [comment]
@ArloJamesBarnes Are you sure? The level of originality required for copyright protection in the United Kingdom is very low in comparison to elsewhere, most UK origin logos don't qualify.

**Comment by ArloJamesBarnes** [comment]
Ah, it seems you are correct. Thanks for catching that. https://commons.wikimedia.org/wiki/Commons:Copyright_rules_by_territory/United_Kingdom#Typographical_copyright

**Comment by UKChris-osm** [comment]
Would it be usable if Wetherspoons granted permission? I could always email and ask?

**Comment by bhousel** [comment]
I'd like to close this issue here, as a lot of work has been done on the NSI side to allow branded pubs to exist with unique names.  

There will always be followup work to do on keeping the Weatherspoons wikidata page updated, but for things like making sure their logo image looks good I don't want an open issue in our tracker.
