### ISSUE TITLE
Filtering by country code on the nsi.guide website

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#3025]
The nsi.guide website provides a useful to quickly filter the NSI by brands and/or country codes.  Currently when one filters by a country code, they are shown brands that are restricted to that country code *and* brands that have no country code assigned.  It would be useful to add a feature that allows one to enter a country code and see only brands which are assigned that particular country code.

For example, filter by `lv` (Latvia) and only see brands exclusive to Latvia.

![image](https://user-images.githubusercontent.com/8010709/65360528-1d617300-dbb5-11e9-8f4c-ba0b87cce428.png)

**Comment by andrewharvey** [comment]
It would be a good option, but should be an option so you can still see international chains + your local country chains.

Fixing the entries which aren't international would also help alleviate this, eg https://en.wikipedia.org/wiki/76_(gas_station) is US only but currently doesn't set a countryCode.

**Comment by mds08011** [comment]
Agreed.  I envision this as an additional feature, not a replacement.

**Comment by pyrog** [comment]
Add a checkbox after:
* [app/src/Filters.jsx#L27](https://github.com/osmlab/name-suggestion-index/blob/master/app/src/Filters.jsx#L27)

Filter the brands:
* [app/src/Overview.jsx#L69](https://github.com/osmlab/name-suggestion-index/blob/master/app/src/Overview.jsx#L69)
* [app/src/Category.jsx#L87](https://github.com/osmlab/name-suggestion-index/blob/master/app/src/Category.jsx#L87)

**Comment by Adamant36** [comment]
Closing as it seems resolved.
