### ISSUE TITLE
Add Barceló Group

### ISSUE THREAD

**Issue by Crashillo** [osmlab/name-suggestion-index#3045]
Spanish global brand of hotel and resorts

tag: `tourism=hotel`
wikidata: https://www.wikidata.org/wiki/Q15148996

Thanks

**Comment by robinroscher** [comment]
I would like to try this if no one else is working on it!

**Comment by bhousel** [comment]
> I would like to try this if no one else is working on it!

Go for it 👍

**Comment by mds08011** [comment]
Added in https://github.com/osmlab/name-suggestion-index/pull/3064
