### ISSUE TITLE
Merge 'Volg' convenience store and supermarket

### ISSUE THREAD

**Issue by habi** [osmlab/name-suggestion-index#3046]
This is a Swiss brand of smaller supermarkets, mostly in rural regions.

The name-suggestion index has it listed as shop=supermarket (554 times, https://overpass-turbo.eu/s/MHB) and as shop=convenience (290 times, https://overpass-turbo.eu/s/MHC)
The shop=convenience entry is less 'good' and should be merged into shop=supermarket (even though some of the VOLG shops can be quite small...).

**Comment by habi** [comment]
I first wanted to 'add' Voll, but was on a subpage where I couldn't find it...

**Comment by mds08011** [comment]
Thank you @habi !

I created a PR to remove the Volg `shop=convenience` entry and match these with the correct `shop=supermarket`.  Note that the existing Volgs in OSM will not be automatically changed but iD editor will suggest/direct mappers to use `shop=supermarket` in the future.
