### ISSUE TITLE
Evereve

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#3052]
`shop=clothes` `clothes=women`

https://evereve.com/storelocator/index/

No Wikidata item yet (not to be confused with [this German band](https://www.wikidata.org/wiki/Q572839)). [This public domain logo](https://d78fj94i6kg8.cloudfront.net/media/logo/stores/1/EE-global-logo-275x50-x2.png) can be uploaded to Wikimedia Commons and used in a new Wikidata item.

**Comment by UKChris-osm** [comment]
Not sure if these help: 

"shop/clothes|Evereve": {
    "countryCodes": ["us"],
    "tags": {
      "brand": "Evereve",
      "brand:wikidata":"Q69891997",
      "clothes": "women",
      "name": "Evereve",
      "shop": "clothes"
    }
  }
