### ISSUE TITLE
Altar’d State

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#3054]
`shop=clothes`

https://www.altardstate.com/help/?page=store-locator

No Wikidata item yet. A public domain logo can be found in SVG format in the above webpage’s source code – search for `as-header-logo` – and uploaded to Wikimedia Commons for use in a new Wikidata item.

**Comment by aestevens** [comment]
Hi @1ec5, I just entered #3124 after creating the Wikidata Item and adding the tag to the index. I'm happy to add the logo to the Wikidata Item, but my only concern is the legality of uploading logos to Wikimedia Commons.

My understanding is that logos constitute copyrighted material, and as such are not eligible for upload to the Commons. However, I'm seeing numerous logos that were uploaded to Commons that are listed variously as public domain or with a form of CC license. Can you clarify on your understanding of uploading logos to Commons? Thanks in advance!
