### ISSUE TITLE
Add Four Points by Sheraton (Hotel)

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#3087]
**Brand Name**
Four Points by Sheraton

**Brand Wikidata**
Q1439966

**Brand Wikipedia**
https://en.wikipedia.org/wiki/Four_Points_by_Sheraton

**OSM Tags**
`name=Four Points by Sheraton`
`amenity=hotel`
`short_name=Four Points`

**Comment by mds08011** [comment]
I'm unsure if `name` and `brand` should include "by Sheraton".  Ongoing discussion: https://github.com/osmlab/name-suggestion-index/pull/3088

**Comment by cristianKumul** [comment]
Hello @mds08011, I'm following the discussion. and when we have an approach to solve the brand name problem, can I work on this issue?

**Comment by mds08011** [comment]
@cristianKumul yes, thank you!

**Comment by mds08011** [comment]
@cristianKumul I recently stayed in one of these hotels and am now convinced that the name and brand should be the full “Four Points by Sheraton”.  The “…by Sheraton” brand name was included everywhere: from the sign on the outside of the building to the branded floor mats.

**Comment by mds08011** [comment]
Added in: https://github.com/osmlab/name-suggestion-index/pull/3091
