### ISSUE TITLE
Devise way to handle nouns used as names

### ISSUE THREAD

**Issue by simonpoole** [osmlab/name-suggestion-index#31]
One of the larger issues with the index as is, is that is doesn't really work internationally. It is quite possible and happens (I believe "Apotheke" is such a case), that a noun in one language is used as the name of a chain in another currently there is no way to handle such a conflict or any regional differences in naming.

**Comment by math1985** [comment]
See also #11

**Comment by bhousel** [comment]
In iD we just sort the name suggestion matches below the noun matches (which are localized).  I think it makes sense to consider these name suggestions a fallback strategy to whatever other name searching exists in an osm app.

For example, "Railway" is a noun in osm, also happens to be the name of a Pub.  

<img width="280" alt="screenshot 2016-07-18 13 31 42" src="https://cloud.githubusercontent.com/assets/38784/16924180/04804538-4cec-11e6-8981-38057382889f.png">


iD sort the search results by 1. exact match on (localized) name, 2. exact match on (localized) terms, 3. exact match on (generally `en_UK`) osm tag value, 4. Name suggestions,  5. Other fuzzy matches. 

This works for iD, but might not work for Vespucci or other apps?  Is there specific improvement you need in the name suggestion index that would help disambiguate chain suggestions from local nouns?

**Comment by bhousel** [comment]
Yeah let's just leave #11 as the issue for dealing with local-only names.  I agree we should do it.
