### ISSUE TITLE
Make build_all_names gather names from `craft=*` too

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#3110]
The planet processing file isn't picking up anything under `craft=*` yet, so we might want to change the code to start doing this, so we can get accurate counts.

We're also starting to track some brands under `leisure=*`, `healthcare=*`, so may want to include them too.

_Originally posted by @bhousel in https://github.com/osmlab/name-suggestion-index/pull/3096#issuecomment-541380528_

**Comment by tas50** [comment]
I'm playing around with this right now and we probably want to avoid healthcare=* since we've moved those all over to the amenity tags in the index. We should keep all the amenity tags that are actually healthcare though. dentist, doctor, clinic, hospital, etc.

**Comment by bhousel** [comment]
Thanks for taking this up and processing the planet files @tas50  👏 

`healthcare` is an interesting one because we still keep the `amenity` tags around in the iD presets, and surely will for a while.  

OSM-carto actually declined to render `healthcare` (see https://github.com/gravitystorm/openstreetmap-carto/pull/3731)  so a lot of people just don't use it.

**Comment by tas50** [comment]
I filtered all this data and didn't really get anything back that was useful at this point. It just makes the whole planet processing take that much longer. I suspect not a lot of folks are using the craft tag and we'll have better luck driving its adoption through adding things to NSI vs. watching things hit 50+.
