### ISSUE TITLE
Bell Canada

### ISSUE THREAD

**Issue by Shermapper1** [osmlab/name-suggestion-index#3113]
Right now, Bell stores are treated as mobile phone stores, and sometimes they are. But Bell Canada also offers Satellite TV and Landline services, and as such, many Bell Canada stores offer all 3.

**Comment by tohaklim** [comment]
This is similar to A1, which offers TV and cable services. Unless office=telecom is a better fit, I'd say we map those based on what is (perceived) to be the primary function

**Comment by bhousel** [comment]
Yeah, a handful of these have ended up as `office=telecom`.  I'm kind of surprised people want that to be the tag.. `shop=something` seems more appropriate for a storefront business.

**Comment by Shermapper1** [comment]
I ended up making up shop=telecom, because I've gotten tired of store/business tags that fit poorly (or not at all).

**Comment by bhousel** [comment]
Oh yeah, see #2900 too - I think we're kind of moving towards `shop=telecommunication`.  I agree with @tas50 .  I think we should start retagging these.

**Comment by tohaklim** [comment]
Yeah, that would work well, and uses the same term as the office tag. Would be good to put it on the wiki as “in use”, if avoiding the proposal process
