### ISSUE TITLE
Add Carvel ice cream 

### ISSUE THREAD

**Issue by wireguy** [osmlab/name-suggestion-index#3138]
https://www.wikidata.org/wiki/Q5047520
https://en.wikipedia.org/wiki/Carvel_(franchise)

name=Carvel
amenity=ice_cream 🍦

**Comment by amous4822** [comment]
should this be added in shop=bakery ? 
because it also offers stuff like cake/Sundaes & Shakes. 

[](https://www.carvel.com)

**Comment by doublah** [comment]
Added in #3145
