### ISSUE TITLE
Figure out process of remapping an old QID to a new one

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#3154]
There are a handful of brands in `dissolved.json` where we believe that they should have a new Wikidata QID.  

For example, from discussion on OSM-US Slack, we think that:

* [Gulf Oil Q1296860](https://www.wikidata.org/wiki/Q1296860) maybe should be remapped to [Gulf Oil LP Q5617505](https://www.wikidata.org/wiki/Q5617505)
In this case Gulf company dissolved and their IP is now owned by a successor company that is using it. 

* [Conoco Q1126518](https://www.wikidata.org/wiki/Q1126518) maybe should be remapped to [ConocoPhillips Q214763](https://www.wikidata.org/wiki/Q214763)
This case is more complicated.  Conoco is no longer an active company, but [it is still an active brand](https://www.conoco.com/) being used by ConocoPhillips.  I'm not sure what to make of it - maybe it doesn't belong in `dissolved.json` ?

When we decide that a brand should switch QIDs, we should have a way of just remapping them all en masse and maybe recording this in the brand files so that other projects can know.

**Comment by 1ec5** [comment]
> Conoco is no longer an active company, but it is still an active brand being used by ConocoPhillips. I'm not sure what to make of it - maybe it doesn't belong in dissolved.json ?

dissolved.json should track brands just like our other files. A brand can change hands without going defunct, and that seems to have happened with the Conoco brand: ConocoPhillips spun off Conoco as part of [Phillips Petroleum Company](https://en.wikipedia.org/wiki/Phillips_Petroleum_Company).

Over time, we should ensure that gas station brands are linked to Wikidata items that are about the brands rather than the parent companies. Those brand items will be more stable, since gas station brands change hands quite frequently.

**Comment by SilentSpike** [comment]
I was going to say the way brands are modelled at wikidata could actually be improved - separating the brand entity from the company entity. 

For most businesses it hasn't really been needed (e.g. McDonald's the brand and McDonald's the company are so intertwined that using the company item is stable enough for our needs), but for brands that are changing hands it could be useful.

Would probably want to discuss how to approach creating brand entities at https://www.wikidata.org/wiki/Wikidata:WikiProject_Companies or how brands can be best modelled at https://www.wikidata.org/wiki/Wikidata:WikiProject_Ontology

**Comment by wireguy** [comment]
Chase Bank is another example.
The wikidata entry makes a recursive loop which points the dissolved brand to the new parent company back to the old (but now relaunched) brand.

**Comment by bhousel** [comment]
Bumping this issue as some things have changed in the past year.

Now that we have semi-stable identifiers, and the `build_wikidata.js` script is _updating_ wikidata to have P8253 claims, I am noticing some stuff.  Sometimes QIDs get merged/redirected.  There are a few in this situation where our index has the old one, we try to update, and we get an error in the script.  

* [Q56599145](https://www.wikidata.org/wiki/Q56599145) -> [Q3056765](https://www.wikidata.org/wiki/Q3056765) (Steers)
* [Q28729658](https://www.wikidata.org/wiki/Q28729658) -> [Q18015543](https://www.wikidata.org/wiki/Q18015543) (Colin's Jeans )

We should update NSI (and OSM) to use the new QID.  So my question is - how?   I'm more interested in what this would look like from the OSM side.

Old QIDs will sit around in OSM and continue to be set by apps like iD which don't update as quickly as I'd like.

I think as a first step I'm just going to
* produce list of QID remaps and store it with this project
* make an overpass query to find them all in OSM
* perform level0 edit to upgrade them
* just do this sometimes?

**Comment by bhousel** [comment]
related to #98 "producing lists for cleanup"

**Comment by bhousel** [comment]
I added a file [`config/replacements.json`](https://github.com/osmlab/name-suggestion-index/blob/main/config/replacements.json) to keep track of all the situations where QIDs have changed and we should remap them in OSM data.
