### ISSUE TITLE
Fix name for Ozon box vending_machines

### ISSUE THREAD

**Issue by literannn** [osmlab/name-suggestion-index#3158]
Please change name=Постамат Ozon Box to name=Постамат Ozon Box cause amenity=vending_machine + vending=parcel_pickup means Постамат.

wikidata=Q2365235

https://wiki.openstreetmap.org/wiki/Names : "The names should be restricted to the name of the item in question only and should not include additional information not contained in the official name such as **categories**, types, descriptions, addresses, refs, or notes."

**Comment by bhousel** [comment]
> Please change `name=Постамат Ozon Box` to `name=Постамат Ozon Box`

those are.. the same thing?

**Comment by bhousel** [comment]
Actually, I just checked and none of this is in our index..
Are you asking us to add it?
I'm very confused.

**Comment by literannn** [comment]
I'm sorry )) name=Постамат Ozon Box to name=Ozon Box
