### ISSUE TITLE
Add Aerie clothing store

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3167]
Over 100 locations according to https://en.wikipedia.org/wiki/Aerie_(clothing_retailer)

**Comment by oliversiket** [comment]
Hey! I added a pull request for this one - #3215 
Could you please have a look? :) thank you

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/commit/485eacc41ab049dd7ca6d63538d176e14856505b
