### ISSUE TITLE
Update Gulf outdated wikidata entry

### ISSUE THREAD

**Issue by wireguy** [osmlab/name-suggestion-index#3183]
amenity/fuel|Gulf

has:
https://www.wikidata.org/wiki/Q1296860
but that was dissolved in 1984
it should be changed to:
https://www.wikidata.org/wiki/Q5617505

  "amenity/fuel|Gulf": {
    "tags": {
      "amenity": "fuel",
      "brand": "Gulf",
      "brand:wikidata": "Q5617505",
      "brand:wikipedia": "en:Gulf Oil",
      "name": "Gulf"
    }
  },

Update all existing osm pois?

**Comment by bhousel** [comment]
Yeah this is #3154 - I'm not really sure what the best solution is.
I like @1ec5's suggestion that we maintain `dissolved.json` manually rather than using a script to look for dissolution dates in Wikidata.
