### ISSUE TITLE
Research Conoco

### ISSUE THREAD

**Issue by wireguy** [osmlab/name-suggestion-index#3184]
Conoco (amenity/fuel) is currently appearing in the dissolved.json file, getting kicked out because Conoco was marked dissolved in wikidata: https://www.wikidata.org/wiki/Q1126518

Conoco has become ConocoPhillips, which has a wikidata entry of:
https://www.wikidata.org/wiki/Q214763

should Q1126518 be changed to Q214763 in nsi?
should exisiting osm pois get updated?

**Comment by bhousel** [comment]
Yeah this is #3154 - I'm not really sure what the best solution is.
I like @1ec5's suggestion that we maintain `dissolved.json` manually rather than using a script to look for dissolution dates in Wikidata.
