### ISSUE TITLE
Add Stuart Weitzman shoe store

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3199]
There's a Wikipedia article already for the founder, which *shouldn't* be used.

**Comment by quetcodesfire** [comment]
Made PR #3226. I did not add the founder's Wikipedia and there is not added a Wikipedia for the store.

**Comment by Adamant36** [comment]
PR #3226 didn't solve the issue since it was just adding the entry to shop=clothes when it was already in shop=shoes and didn't have anything to do with creating a Wikidata entry. So if anyone besides @quetcodesfire still want's to create a Wikidata entry for it and do a new PR that would be great.

**Comment by Adamant36** [comment]
I created a Wikidata entry for it [Q75244763](https://www.wikidata.org/wiki/Q75244763)

**Comment by LuisMBarrera** [comment]
Added wikidata entry on this PR.
