### ISSUE TITLE
Add Edgars women's clothing store

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3200]
Women's clothing store: https://www.edgars.co.za

**Comment by m4tr1k** [comment]
@tas50 can I take this one?

**Comment by tas50** [comment]
@m4tr1k all yours

**Comment by m4tr1k** [comment]
@tas50 it is already on the json file, so I don't think this issue is necessary
![image](https://user-images.githubusercontent.com/12871065/67818654-f9455b80-faa9-11e9-9b8c-b580c4510e7d.png)
I will try another issue!

**Comment by Adamant36** [comment]
@m4tr1k you can still create a Wikidata entry for it and do a PR with that. If you need any help let us know.

**Comment by Adamant36** [comment]
@tas50, it says on their website that they have all kinds of stuff. Including men's clothing, beauty products, and housewares. Are you sure they wouldn't be better tagged as a department store like ROSS or TJ-Max?

**Comment by UKChris-osm** [comment]
I see that [Edgars](https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=edg#edgars-b23c0b) has Wiki* data added to it now, and almost all entries in OSM are tagged as a clothes shop, so can this be closed, or should it be updated to be tagged as a department store?

It does seem like it's more of a department store, but the very high number of clothes shop tags makes me wonder if local people are happier with that tag?

**Comment by bhousel** [comment]
> It does seem like it's more of a department store, but the very high number of clothes shop tags makes me wonder if local people are happier with that tag?

Oh interesting - yeah I agree it should be a department_store.  We should probably change it in the NSI.
