### ISSUE TITLE
Add Little Burgandy shoe store

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3201]
Shoe store in Canada: https://www.littleburgundyshoes.com

**Comment by bhousel** [comment]
This won't show up in iD until we add a Wikidata identifier, but it looks like there isn't one yet.

This page lists the sub-brands owned by Genesco, so would be a good place to start for anyone who wants to add the info to Wikipedia/Wikidata: https://en.wikipedia.org/wiki/Genesco#Brands

**Comment by Adamant36** [comment]
Wikidata added in https://github.com/osmlab/name-suggestion-index/commit/bd12e80efd5c97f4564e2113e2ebb04012f1b29a
