### ISSUE TITLE
Add Van Heusen men's clothing store

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3202]
Men's clothing store: https://vanheusen.partnerbrands.com/

**Comment by rashmiap** [comment]
I can do this 👍 @tas50

**Comment by quetcodesfire** [comment]
I have made a PR #3225

**Comment by Adamant36** [comment]
Added in #3210. @quetcodesfire, next time someone says they are going to do a PR for something, maybe don't do one yourself. Otherwise, it's redundant and takes time away from dealing with more important things. Thanks.
