### ISSUE TITLE
Add Ampol

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3233]
Australian fuel station brand

https://en.wikipedia.org/wiki/Ampol
https://www.wikidata.org/wiki/Q4748528

**Comment by theonlymikeever** [comment]
I can help with this!

**Comment by bhousel** [comment]
Thanks @theonlymikeever !
A cool GitHub tip for future PRs - you can include some text like "closes #3233" in your commit message or pull request, and GitHub will close the issue for us automatically 💪 

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
