### ISSUE TITLE
Add Din Tai Fung

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3280]
Global Chinese restaurant chain

https://en.wikipedia.org/wiki/Din_Tai_Fung
https://www.wikidata.org/wiki/Q699142

**Comment by Grimlock257** [comment]
I'll take this!

**Comment by trevorspecht** [comment]
working on this one

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/commit/f022136bb1da7888a4415cfb896d077fe7d7d428
