### ISSUE TITLE
Add Hog's Australia's Steakhouse

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3294]
https://en.wikipedia.org/wiki/Hog's_Australia's_Steakhouse
https://www.wikidata.org/wiki/Q5876920

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/pull/3306

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/pull/3306/commits/135490a99935f18b15cb631056ad207cbdf4b267
