### ISSUE TITLE
Add Mad Mex

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3297]
Fresh Mexican place with restaurants in Australia and New Zealand. 

https://en.wikipedia.org/wiki/Mad_Mex_Fresh_Mexican_Grill
https://www.wikidata.org/wiki/Q19589766

**Comment by mds08011** [comment]
https://github.com/osmlab/name-suggestion-index/commit/0cb555472a16119bc0c755053004d708aac7775c
