### ISSUE TITLE
Add Shingle Inn

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3310]
Australian cafe chain

**Comment by lyndic** [comment]
I'd like to work on this!

**Comment by Adamant36** [comment]
Sure. Go for it. Generally with this repo you can work on whatever issues you want as long as they don't already have an open PR for them. Also, if you have any questions feel free to ask.

**Comment by Adamant36** [comment]
Closed in #3310. Thanks @lyndic
