### ISSUE TITLE
Add Zambrero

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3314]
Australian fast food Mexican restaurant chain. Also has locations in other countries.  

https://en.wikipedia.org/wiki/Zambrero
https://www.wikidata.org/wiki/Q18636431

**Comment by HERBOD7** [comment]
@Adamant36 I can do it.

**Comment by Adamant36** [comment]
Alright. Thanks. Feel free to do PRs for whichever ones you want to do.

**Comment by Adamant36** [comment]
Closed in #3343
