### ISSUE TITLE
Add Zarraffa's Coffee

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3315]
National coffee house chain. 

https://en.wikipedia.org/wiki/Zarraffas_Coffee
https://www.wikidata.org/wiki/Q8066878

**Comment by HERBOD7** [comment]
@Adamant36 I can do it.

**Comment by Adamant36** [comment]
:-1:

**Comment by Adamant36** [comment]
Closed in #3343
