### ISSUE TITLE
Add Copeland's

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3316]
American restaurant chain

https://en.wikipedia.org/wiki/Copeland%27s
https://www.wikidata.org/wiki/Q5168346

**Comment by HERBOD7** [comment]
@Adamant36 I can do it.

**Comment by Adamant36** [comment]
Thanks, go for it. If you have any questions feel free to ask.

**Comment by Adamant36** [comment]
Closed in #3342
