### ISSUE TITLE
Add Harry Ramsden's

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3318]
Seafood fast food restaurant chain in the United Kingdom and Ireland

https://en.wikipedia.org/wiki/Harry_Ramsden%27s
https://www.wikidata.org/wiki/Q5671849

**Comment by lyndic** [comment]
Can I work on this?

**Comment by Adamant36** [comment]
Hi, @lyndic. Sure, go for it. If you have any questions about anything feel free to ask.

**Comment by Adamant36** [comment]
Closed in #3335
