### ISSUE TITLE
Add Kona Grill

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3321]
International restaurant chain

https://en.wikipedia.org/wiki/Kona_Grill
https://www.wikidata.org/wiki/Q6428706

**Comment by adzkar** [comment]
Can i take this ?

**Comment by bhousel** [comment]
> Can i take this ?

Sure @adzkar go for it 👍

**Comment by adzkar** [comment]
I have added kona grill to restaurant, please check my pr #3326

**Comment by mds08011** [comment]
Looks great, thank you @adzkar !

https://github.com/osmlab/name-suggestion-index/commit/3e6d3255042de6bb546d9477717f5699a8594426
