### ISSUE TITLE
Jessops - shop=camera or shop=photo

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3331]
AFAIK, Jessops focuses more on just cameras/lenses, with other photography services as an extra, but i'd like a second opinion.

https://en.wikipedia.org/wiki/Jessops
Q3191701

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcamera
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dphoto

**Comment by bhousel** [comment]
I agree that it's slightly more of a `shop=camera` than a `shop=photo`, but really either is fine.
Even `shop=electronics` would be ok, since it seems like they sell computer equipment, projectors, and drones now 🤷‍♂

**Comment by SK53** [comment]
They are definitely a camera shop above all else and always have been (when they were a single store specialist). They do photo processing, but much of this is now via an on-line offering & presence has been reduced considerably in store in recent years.
