### ISSUE TITLE
Hampton By Hilton

### ISSUE THREAD

**Issue by Djminisite06** [osmlab/name-suggestion-index#3344]
Hampton should have country tags removed as it is now a worldwide brand

**Comment by Adamant36** [comment]
Well, not technically world wide. According to Wikipedia it's in the United States, Canada, United Kingdom, Latin America and Europe. It really depends on how many European and Latin American countries its in as to if the country codes should be removed completely or not IMHO. We have a few brands in the index with like 20 country codes. There's no reason we couldn't do it here so it come up in searches done in Africa, Australia, or the middle east. Which is still a huge part of the world.

**Comment by bhousel** [comment]
I'd like to start using [country-coder](https://github.com/ideditor/country-coder) in more projects.  It some support for regions, so we wouldn't need to specify all the countries.  For now let's just remove the `us` countryCode, and we can improve on this later.

**Comment by Adamant36** [comment]
Alright. I wasn't aware of country-coder. Sounds like it will be awesome. Closed in  #3346.
