### ISSUE TITLE
exclude dissolved brands from /master/dist/brands.json

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#3357]
pinging @ENT8R 

Going by https://github.com/osmlab/name-suggestion-index/commit/4354c753098d85b9f14cae45969e4bc90fc19008#diff-c9fd8c420a55626cc18b25e9ed410434

`// brand does not exist anymore, so it should not be in the index`

it seems that dist file is not supposed to contain brands known to be dissolved.

But https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/dist/brands.json has entries from https://github.com/osmlab/name-suggestion-index/blob/master/dist/dissolved.json

For example `Allied Bank~(defunct bank in Philipines)` or `Banca Popolare di Verona`.

This is not a major problem as number of known dissolved brands is quite low.

**Comment by matkoniecz** [comment]
That is because this file includes all brands, for use are rather https://github.com/osmlab/name-suggestion-index/blob/master/dist/name-suggestions.json and https://github.com/osmlab/name-suggestion-index/blob/master/dist/name-suggestions.min.json

**Comment by Adamant36** [comment]
> This is not a major problem as number of known dissolved brands is quite low

There is currently 17 of them that I know of in the bank.json file. I haven't gone through any of the others, but I'm sure there are a lot more out there. One of the things I've been working on is going through Wikidata entries and adding "former" to the descriptions of all the brands no longer in existence. Along with making sure they have a "dissolved" entry with the date of dissolution. That way they will be a lot easier to find on nsi.guide's sub-pages or at least find them by doing a SPARQL query if nothing else. Hopefully at some point we can figure out a good way to deal with them in OSM itself to.
