### ISSUE TITLE
Add NASA Federal Credit Union bank

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3363]
https://en.wikipedia.org/wiki/NASA_Federal_Credit_Union

**Comment by gedfaj** [comment]
HI There! 

I have added NASA Federal Credit Union to brand/bank.json, along with wikidata that is associated.

This is my first contribution to an open-source project, so if there is anything that needs to be changed or if you have any feedback let me know!

#3379

**Comment by bhousel** [comment]
Looks great @gedfaj  welcome!

A cool GitHub tip for future PRs - you can include some text like "closes #3379" in your commit message or pull request, and GitHub will close the issue for us automatically 💪

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by gedfaj** [comment]
Thanks for the tip @bhousel !
