### ISSUE TITLE
Add Old Country Buffet restaurant

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3365]
Needs a wikidata page. It's owned by https://en.wikipedia.org/wiki/Ovation_Brands

**Comment by Adamant36** [comment]
Here you go [Q75243208](https://www.wikidata.org/wiki/Q75243208)

**Comment by swapnamanupati** [comment]
Hello, Is this issue open? I would like to help.

**Comment by bhousel** [comment]
Yes @swapnamanupati go for it!

**Comment by swapnamanupati** [comment]
Old Country buffet is restaurant located in USA. we need to add a key value pair in brands/amenity/restaurant.json.

**Comment by swapnamanupati** [comment]
I am getting below error.
PS C:\Users\gani\Swapna\name-suggestion-index> git push --set-upstream origin 3365-old-country-buffet
remote: Permission to osmlab/name-suggestion-index.git denied to swapnamanupati.
fatal: unable to access 'https://github.com/osmlab/name-suggestion-index.git/': The requested URL returned error: 403

Please give me permissions to push my branch.

**Comment by bhousel** [comment]
Hey @swapnamanupati , if you make a fork of the project, you’ll be able to make whatever branches you want in the fork, and still submit pull requests..

**Comment by swapnamanupati** [comment]
Thank you for your response.

I am doing it now.

Regards,
Swapna M

**Comment by bhousel** [comment]
done in #3401

**Comment by TheAdventurer64** [comment]
Should we add the `owner` tags as well?
