### ISSUE TITLE
Add Biscuitville

### ISSUE THREAD

**Issue by joecaruso** [osmlab/name-suggestion-index#3368]
https://www.wikidata.org/wiki/Q4917274
https://en.wikipedia.org/wiki/Biscuitville

I'm not sure exactly how it should be tagged.  `amenity=fast_food` and then `cuisine=southern` and/or some other way to denote breakfast?

**Comment by Brent017** [comment]
Hello, Is this issue open?  I would like to help if so.

**Comment by bhousel** [comment]
Yes, go for it @Brent017  👍

**Comment by Brent017** [comment]
Thanks Brian, this is my first contribution.  I'm just basically adding a key value for Biscuitville to the brands file correct?
________________________________

**Comment by bhousel** [comment]
> Thanks Brian, this is my first contribution. I'm just basically adding a key value for Biscuitville to the brands file correct?

Great!  We love first time contributors ❤️ 

The file to change is `brands/amenity/fast_food.json`.

If you open it you'll see a lot of entries for fast food places.  You can copy one of those to a new entry, and edit it to have the details for Biscuitville which are in this ticket.   

You'll need to set the key of the entry, and also `name`, `brand`, `brand:wikidata`, `brand:wikipedia` values, and make sure it has `"cuisine": "american;breakfast",`

If you are doing this on a local development environment with git and node, you can then run `npm run build` and it will check the syntax and make the file look pretty.  (If you are doing this in the GitHub file editor, it won't do that, but that's ok).  

Check the [README](https://github.com/osmlab/name-suggestion-index/blob/master/README.md) and [CONTRIBUTING](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) files for lots more details, and let me know if you have any questions.

**Comment by rajatmw1999** [comment]
I have added the Biscucitville brand to brands/amenity/fast_food.json. As per the information available on the and from Biscuitville's offical website, the company is primarily involved in selling biscuits made from their own recipe. It was involved in the pizza and bread business but biscuits is what they are known for. So, "cuisine" is given the value of "biscuit". Other better options can be "cuisine" : "snacks". I am a first time contributor, so, if there's anything that i missed, please inform about it!

https://github.com/osmlab/name-suggestion-index/pull/3373

**Comment by Brent017** [comment]
I have also submitted a pull request for this issue.  It looks like the contributor above forgot to change the name at top from A&W to Biscuitville.

**Comment by bhousel** [comment]
done in #3376
