### ISSUE TITLE
Mace needs splitting up.

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3371]
Mace is 3 brands, current wikidata info only refer to chain in GB and wikipedia page refers to all of them.

Mace (Ireland)
https://mace.ie/ - https://www.facebook.com/MACEIreland
ie
Site claims 160 stores.

Mace (Northern Ireland)
http://www.maceni.co.uk/ - https://www.facebook.com/MACENorthernIreland/
gb (no used country code for NI)
Facebook claims 88 stores.

Mace (Great Britain)
http://www.macestores.co.uk/ - https://www.facebook.com/maces.stores
gb
Site claims 764 stores.

**Comment by Adamant36** [comment]
Mace (Ireland) [Q75236910](https://www.wikidata.org/wiki/Q75236910)
Mace (Northern Ireland) [Q75238536](https://www.wikidata.org/wiki/Q75238536)
Mace (Great Britain) [Q75240338](https://www.wikidata.org/wiki/Q75240338) (I guess there was already a Wikidata entry for this one and I accidentally created a duplicate for it. Oh well 🤷‍♂) 

Now someone just needs to create the entries for them.

**Comment by doublah** [comment]
Fixed in #3371
