### ISSUE TITLE
Add Haart Estate Agents

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3372]
https://www.haart.co.uk/branch-finder/ shows 135
gb only
No wikidata, but parent company is https://en.wikipedia.org/wiki/Spicerhaart (Q17021921)

**Comment by rajatmw1999** [comment]
I have created a wikidata entry in the name of haart real estate. https://www.wikidata.org/wiki/Q75006731.
Basically, i contacted their team and told them about the work i am doing. They were really happy to help me out and give me some information about their company. Hope, i will receive a mail from them giving even more info about their founders and ceo. https://www.haart.co.uk/about-us/
Also added it under the estate_agent file. Hope this helps. If there anything that needs to be edited or improved, just let me know.
https://github.com/osmlab/name-suggestion-index/pull/3374

**Comment by bhousel** [comment]
done in #3374.. also thanks @rajatmw1999 and @doublah for adding the Wikidata page!
