### ISSUE TITLE
Adding Dark mode

### ISSUE THREAD

**Issue by rajatmw1999** [osmlab/name-suggestion-index#3375]
Adding a dark mode to the website will make it look even more cool and presentable. Currently it has a plain and boring interface. Adding some styles will make it more engaging.

**Comment by Adamant36** [comment]
> Currently it has a plain and boring interface. 

I'd call it utilitarian

**Comment by bhousel** [comment]
Sure, I'd welcome any improvements to the website.  It is something I threw together pretty quickly.

**Comment by rajatmw1999** [comment]
> > Currently it has a plain and boring interface.
> 
> I'd call it utilitarian

Yes, it is indeed, But the user doesn't care about all that. All the user cares about is a interactive and engaging interface..

**Comment by Adamant36** [comment]
> Yes, it is indeed, But the user doesn't care about all that. All the user cares about is a interactive and engaging interface.. 

I know. I meant to add a 😉 to the end of my last comment. I agree that the website could be spiced up some though.

**Comment by rajatmw1999** [comment]
> Sure, I'd welcome any improvements to the website. It is something I threw together pretty quickly.

I am having problems locating the file to which i should make changes. Please tell me the path of the rendered file on the browser. I will use bootstrap to add some professional styling and will also add an alternate dark mode.

**Comment by bhousel** [comment]
> I am having problems locating the file to which i should make changes. Please tell me the path of the rendered file on the browser.

It's a React app and the source is under here:
https://github.com/osmlab/name-suggestion-index/tree/master/app

When you change the source, you'll need to do `npm run docbuild` to regenerate the bundled app under `/docs`.

**Comment by azheng4119** [comment]
<img width="1440" alt="Screen Shot 2019-11-25 at 2 13 42 PM" src="https://user-images.githubusercontent.com/10579796/69570465-e2513680-0f8d-11ea-950a-fb7dfdd30a04.png">
<img width="1440" alt="Screen Shot 2019-11-25 at 2 13 31 PM" src="https://user-images.githubusercontent.com/10579796/69570473-e54c2700-0f8d-11ea-924e-a7c9097505ca.png">

How would these look for the dark mode?
I just did some simple css changes, but can make a slider for it on the main page.

**Comment by bhousel** [comment]
> How would these look for the dark mode?

Looks like it needs a bit more work, but a good start..

**Comment by rajatmw1999** [comment]
> > How would these look for the dark mode?
Consider changing the color of the links from blue to something else, like silver or white. That might give it a lovely look.  Also, justifying the content accordingly will help to make it look even more presentable.Although, You have done some great job here.

**Comment by rajatmw1999** [comment]
> > How would these look for the dark mode?
> 
Consider changing the color of the links from blue to something else, like silver or white. That might give it a lovely look. Also, justifying the content accordingly will help to make it look even more presentable.Although, You have done some great job here.

**Comment by bhousel** [comment]
This went stale so I just did it..
