### ISSUE TITLE
Add The Range

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3388]
https://en.wikipedia.org/wiki/The_Range_(retailer)
https://www.wikidata.org/wiki/Q7759409
gb and ie

Current shops are tagged as department_store, doityourself, furniture, variety_store, houseware, hardware and more, honestly not sure which is best.

**Comment by doublah** [comment]
Looks like it was done while i wasn't looking in https://github.com/osmlab/name-suggestion-index/commit/853ced7f194c70d9b8f192f45196c0fc889cc2e3

**Comment by trigpoint** [comment]
Just spotted that an armchair mapper has changed my local Range to homeware and began investigating. Appears to have simply clicked yes to all iD suggestions.

It does not really fit homeware, it is much more Wilko than Dunelm. It stocks garden supplies, pet food and supplies, food along with home stuff.

Can this be fixed?

**Comment by bhousel** [comment]
> Can this be fixed?

Sure, what you would like it changed to?

**Comment by trigpoint** [comment]
It should be a variety_store, that is more in fitting with what they sell.
