### ISSUE TITLE
Greggs

### ISSUE THREAD

**Issue by trigpoint** [osmlab/name-suggestion-index#3396]
The name suggestion index is retagging Greggs as shop=bakery, this feels wrong to me.

In my experience Greggs primarily sells Pasties and sandwiches and operates two type of outlet, takeaway only which are tagged as amenity=fast_food and larger cafe locations, which are tagged as amenity=cafe. 

Either should be accepted, the value of OSM is afterall local knowledge but in my experience of Greggs bakery feels wrong. This is not to say some outlets elsewhere are not bakeries.

**Comment by Adamant36** [comment]
Wikipedia calls them a bakery and they look like bakeries from Google image search. IMO if a place 99% pastries/bread and 1% sells sandwiches, as a side thing because they also make bread, it would still be a bakery. My suggestion is to consult the UK tagging mailing list though.

**Comment by Adamant36** [comment]
@SilentSpike do you happen to know anything about this brand?

**Comment by SilentSpike** [comment]
I would argue that a bakery is really just a subclass of fast food and a more appropriate tag for this brand (when I think of Greggs I think of baked goods first and foremost, it's true that they sell some other things - apparently fried chicken now too).

 These sources seem to back up the idea that Greggs is a bakery:
- https://www.greggsfoundation.org.uk/about/history
- https://www.thesun.co.uk/money/8590225/geordie-john-gregg-started-1billion-bakery-empire-greggs-by-delivering-bread-on-council-estates
- https://www.theguardian.com/global/2016/mar/05/greggs-conquered-britain-bakery-profit-sausage-rolls
- https://www.referenceforbusiness.com/history2/93/Greggs-PLC.html

Quote from the last in particular:
>We intend to be Europe's finest bakery-related retailer

I have heard something about cafe locations before (never seen one myself), so perhaps we could add an entry with that tagging.

**Comment by carlinmack** [comment]
I would say that Greggs is primarily fast food. They do sell baked goods however most people think of a bakery selling freshly baked bread which Greggs does not. Therefore any user searching for a bakery and going to Greggs will be disappointed.

Secondly it's not been mentioned that they equally sell cake slices and donuts besides their pastries. We don't classify Dunkin' Donuts as a bakery so I think that serves as valid precedence.

I think they try hard to be seen as a bakery for marketing reasons - fast food is a very dirty word in the UK as evidenced by McDonalds shift to natural based marketing in the past 5 years.

**Comment by bhousel** [comment]
Thanks all! 
From their website and menu it looks like they are more of a fast-casual place, similar to Panera Bread in the US.  (They call themselves a bakery too, but they are really a cafeteria serving all kinds of stuff).

I've switched the Greggs entry over to use the tags `amenity=fast_food` + `cuisine=sandwich;bakery`.
