### ISSUE TITLE
A.C Moore needs to be added to disolved list

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3404]
They're closing all stores as of today:

https://www.cnn.com/2019/11/26/business/ac-moore-closures-trnd/index.html

**Comment by hikemaniac** [comment]
I've added a statement to [Wikidata](https://www.wikidata.org/wiki/Q4647066) indicating that the store is dissolved. When _A. C Moore_ is added to the index and `npm run wikidata` and `npm run dist` are run, it should be added to dissolved.json.

**Comment by hikemaniac** [comment]
@bhousel This can be closed now, since `npm run wikidata` was run and A.C. Moore was therefore added to dissolved.json. Thanks! 👍

**Comment by bhousel** [comment]
Ok!
