### ISSUE TITLE
Add hhgreg to the dissolved list

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#3406]
These are still tagged all over:

https://en.wikipedia.org/wiki/H._H._Gregg

**Comment by hikemaniac** [comment]
I've added an attribute to [Wikidata](https://www.wikidata.org/wiki/Q5750102), indicating that it was dissolved. 👍 If I understand the process correctly, _H. H. Gregg_ now needs to be added to the index and running `npm run dist` should add it to dissolved.json.

**Comment by hikemaniac** [comment]
@tas50 I've been digging a bit deeper on this one now and it seems that all former stores have been closed but another company bought the intellectual property of hhgregg and has opened a [new store in New Jersey](http://franklinreporter.com/h-h-gregg-opens-new-retail-electronics-store-in-township/). It is also mentioned on their [homepage](https://www.hhgregg.com/hhgregg-grand-opening/). What should be done in this case?

**Comment by bhousel** [comment]
Closing - it's not in the index anymore..
