### ISSUE TITLE
Add Xercise4Less

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3413]
UK gym chain

https://www.xercise4less.co.uk/

**Comment by LuisMBarrera** [comment]
Hi! I'm new with contributing to open-source projects, can I help with this one? @doublah

**Comment by doublah** [comment]
Sure, go for it! Let me know if you need any help.

**Comment by LuisMBarrera** [comment]
ok, thank you, I'm also fixing some warnings about missing cuisine tags and duplicates

**Comment by bhousel** [comment]
> ok, thank you, I'm also fixing some warnings about missing cuisine tags and duplicates

Thanks -but I'd hold off on fixing warnings until you have a bit more experience.. Most of the brands we are getting warned about might not actually be brands - or they might be things that a local person should really make a decision on.

**Comment by LuisMBarrera** [comment]
ok, I'll take that in consideration and undo those

**Comment by trigpoint** [comment]
I created a wikidata item for this and started a pull request.

Had to run for a train, will finish later

**Comment by LuisMBarrera** [comment]
ok, so I don't know how @trigpoint pull request affects what I was doing, but I finished adding this gym, so should I make the PR?

**Comment by trigpoint** [comment]
@LuisMBarrera
I will abandon my PR.

The wikidata I added is https://m.wikidata.org/wiki/Q79244612

**Comment by LuisMBarrera** [comment]
ok, thank you

**Comment by LuisMBarrera** [comment]
PR is up "Added Xercise4Less #3438"

**Comment by doublah** [comment]
I'll check the PR now, you can add reviewers (i'm open to being added as one for future PRs), but usually someone eventually gets round to checking and merging them.
