### ISSUE TITLE
Upper Crust miscategorised as shop/bakery

### ISSUE THREAD

**Issue by rskedgell** [osmlab/name-suggestion-index#3414]
Although Upper Crust sells the products of a bakery, it's a sandwich outlet (mainly selling baguette-style sandwiches), frequently operating from small units in shopping centres, railway stations etc. I have never seen one which bakes in store. amenity=fast_food + cuisine=sandwich would seem more appropriate here.

**Comment by SK53** [comment]
Resolved by PR #3415

**Comment by rskedgell** [comment]
Thanks @SK53 !
