### ISSUE TITLE
Add Optical Express

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3419]
Optical Express is a chain of opticians in the UK, mapped 44 times in OSM. Not sure what the procedure is for contributing to the NSI but here's the code for a new brand. 

"shop/optician|Optical Express": {
"countryCodes": ["gb"],
    "tags": {
      "brand": "Optical Express"
      "brand:wikidata": "Q7098810"
      "brand:wikipedia": "en:Optical Express"
      "name": Optical Express",
      "shop": "optician"
    }
  },

**Comment by bhousel** [comment]
Thanks @boothym 👍 
I added this entry in 807e9f6e8
