### ISSUE TITLE
Currys and PC World

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3430]
These two shops were once separate but are now combined, I don't think there's many still separate - if at all. In OSM there's about 160 for the combined name, 60 for Currys and 30 for PC World.

There doesn't seem to be a combined wiki page or wikidata item though, so not sure what should be in the NSI brand - could probably just use the Currys brand?

**Comment by bhousel** [comment]
I'm not sure.  🤔 
It's ok to have multiple entries in the NSI if they are branded inconsistently on the actual stores.. 

https://en.wikipedia.org/wiki/Currys
https://en.wikipedia.org/wiki/PC_World_(retailer)

From that PC World Wikipedia, it sounds like they have phased out the PC World brand:  
> PC World closed their last remaining standalone shop in Ayr, in the week commencing 26 March 2018, and now exists solely online and as part of the Currys megastores.

**Comment by boothym** [comment]
The branding is consistent on the actual stores. I assume all of the stores have now changed over, though of course I can't be completely sure. The numbers were just to show what the situation was like in OSM.

As you point out the PC World brand is no longer in operation on its own. https://www.dixonscarphone.com/en/our-business/brands

Without the Currys PC World preset you get people adding stores to the map as just Currys: https://www.openstreetmap.org/node/6893756667

I'd propose the following:

 - remove PC World as a brand
 - remove the current Currys PC World brand (since it uses the PC World wikidata)
 - change the Currys brand name to Currys PC World, so that is the only one remaining

**Comment by bhousel** [comment]
> I'd propose the following:
> 
> * remove PC World as a brand
> * remove the current Currys PC World brand (since it uses the PC World wikidata)
> * change the Currys brand name to Currys PC World, so that is the only one remaining

Sounds good - I did this!
I also added `matchNames` properties for the old independent "Currys" and "PC World" names on the preferred "Currys PC World" entry, so mappers will get encouraged to upgrade the name.
