### ISSUE TITLE
Johnsons dry cleaners

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3431]
This is a UK dry cleaning chain: https://www.johnsoncleaners.com/ - 93 shops in the UK containing the word "Johnson", but most are just named Johnsons.

"shop/dry_cleaning|Johnsons": {
"countryCodes": ["gb"],
"tags": {
"brand": "Johnsons"
"brand:wikidata": "Q6268527"
"brand:wikipedia": "en:Johnsons Cleaners UK"
"name": Johnsons",
"shop": "dry_cleaning"
}
},

**Comment by bhousel** [comment]
Thanks, I added this 👍 
I also added a matchName for "Johnson" since it seems to be a frequent misspelling.
