### ISSUE TITLE
Add Dobbies and Wyevale Garden Centres

### ISSUE THREAD

**Issue by trigpoint** [osmlab/name-suggestion-index#3434]
Dobbie's and Wyevale are the two largest chains of Garden Centres in the UK.

"shop/garden_centre|Dobbies": {
"countryCodes": ["gb"],
"tags": {
"brand": "Dobbies"
"brand:wikidata": "Q5286529"
"brand:wikipedia": "en:Dobbies Garden Centres"
"name": Dobbies",
"shop": "garden_centre"
}
},

"shop/garden_centre|Wyevale": {
"countryCodes": ["gb"],
"tags": {
"brand": "Wyevale"
"brand:wikidata": "Q7735819"
"brand:wikipedia": "en:Wyevale Garden Centres"
"name": Wyevale",
"shop": "garden_centre"
}
},

**Comment by bhousel** [comment]
done! thank you 👍
