### ISSUE TITLE
Timpson

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3437]
https://en.wikipedia.org/wiki/Timpson_(retailer)
https://www.wikidata.org/wiki/Q7807658

[overpass-turbo](https://overpass-turbo.eu/?w=%22name%22%3D%22Timpson%22+global&R)

It's a generalistic craft shop, and existing tagging is very inconsistent with `craft=key_cutter`, `shop=shoe_repair`, `shop=locksmith`, `shop=shoes`, `craft=shoemaker`, `craft=watchmaker`, `shop=dry_cleaning` and more

Most of these tags aren't necessarily wrong, as most Timpson shops offer these services, it's just not descriptive of all they do, maybe just `craft=yes` would be best because it's so generalistic.

**Comment by bhousel** [comment]
> Most of these tags aren't necessarily wrong, as most Timpson shops offer these services, it's just not descriptive of all they do, maybe just `craft=yes` would be best because it's so generalistic.

Hmm, I'm really not comfortable giving it the tag `craft=yes`, but I'll ask for some suggestions on Slack.

**Comment by SK53** [comment]
Most are a shoe repair with a key cutting service. A combination of those two would be fine (shoe_repair;key_cutting). I don't think they are craft specialists either as locksmiths or as cobblers (I'd never trust my good shoes to them). All the other services (dry cleaning, watch batteries etc) are ancillary to the two main activities. They certainly don't sell shoes or make shoes so those items are just wrong.

**Comment by carlinmack** [comment]
they have now branched into phone repairs in the past five years

**Comment by jnicho02** [comment]
Timpson are primarily a 'cobblers', i.e. a shoe repair shop, that have added additional services, the biggest of which is key cutting. They really aren't a hardware store, or a craft store. I concur with SK53.

(opinion from the UK)

**Comment by doublah** [comment]
> A combination of those two would be fine (shoe_repair;key_cutting).

The problem is a tag like this wouldn't really be supported (see [wiki page](https://wiki.openstreetmap.org/wiki/Semi-colon_value_separator)).

**Comment by jnicho02** [comment]
So, maybe we need a secondary tag...shop=shoe_repair + services=key_cutting ?

**Comment by SK53** [comment]
Th

> A combination of those two would be fine (shoe_repair;key_cutting).
> 
> The problem is a tag like this wouldn't really be supported (see wiki page).

This doesn't need to be so. There are relatively few UK specific data consumers (SomeoneElse CartoCSS Style, cycle.travel and local sites such as OSM-Nottingham & Bexley), and all implement rules much more complex than recognising a string.

What is more complex is that currently there are about equal numbers of both combination of keys in use. For most data consumption purposes appropriate brand tags are probably more important for Timpson than the actual shop tag value. The advantage of having one combination of the two tags in NSI is that this combination is, over time, likely to become the commonest one which would simplify general data consumption patterns.

For specific shop types I just chopped the shop tag value at ";" when I analysed worldwide shops back in 2015 (I was fine with counting a shop twice in different categories). So using semicolons imposes a pretty small cost for more specific uses. 

As for adding a services tag, the same multiple value issue still arises for data consumers so it wont go away. Not doing something because it is currently unsupported just ensures that no-one attempts to grapple with real-world issues. There must be plenty of other shops in other countries with similar issues.

**Comment by bhousel** [comment]
I'm not really comfortable with using semicolon-delimited shop values in this project.. 

For example, [The Home Depot](https://nsi.guide/index.html?k=shop&v=doityourself#The%20Home%20Depot) also has a key-cutting kiosk, a tool rental, and a garden center, but that doesn't mean I would change all the Home Depots worldwide to `shop=doityourself;key_cutting;tool_hire;garden_centre`

Maybe for Timpson, can we just pick one thing?  It doesn't have to be perfect, but something that is accepted enough so they render on the map with a reasonable icon?  Nothing too clever..  

The issue of OSM tags for features-that-are-multiple-things is something that we're not going to solve on this thread (or probably ever).

**Comment by lakedistrictOSM** [comment]
I've been mapping Timpson branches as shop=locksmith (sometimes with craft=key_cutter) as I thought that was their primary focus. Signage is quite mixed as these recent Geograph images show:
https://s1.geograph.org.uk/geophotos/06/60/06/6600689_9189e3f6_original.jpg
https://www.geograph.org.uk/photo/6538259
https://www.geograph.org.uk/photo/6553193

**Comment by UKChris-osm** [comment]
@rjw62 as a seasoned mapper, do you have any input on how best to tag up Timpson?

**Comment by rjw62** [comment]
I don't know whether all Timpson's are the same in terms of their range of services. The size of store can vary a bit, from a small counter as a concession within by local Tesco, to a bigger shop like the one in https://s1.geograph.org.uk/geophotos/06/60/06/6600689_9189e3f6_original.jpg .

Certainly for a shop where I thought the business was shoe repairs and key cutting I would use "shop"="key_cutting;shoe_repair", and would probably add other values to the list as required. Unless there's a more specific shop value for their collective group of services, I think the best thing to do with Timpson would be to use the semi-colon list. (Although that might get somewhat unwieldy, if we need to add e.g. dry_cleaning, watch_repair and mobile_phone_repair). However, any data-consumers interested in these markets in the UK will be aware that businesses often overlap in their areas, and so would need to parse the semi-colons.

Whether that's any help for NSI I don't know. It's fine if we know that all Timpsons have the same range of services. If not, is the NSI (or more specfically iD's implementation) able to deal with multiple allowable shop values, without enticing editors to over-write existing (quite possibly correct) tagging?

**Comment by TurnrDev** [comment]
I didn't even know Timpson did shoe repairs
