### ISSUE TITLE
Thomas Cook no longer exists

### ISSUE THREAD

**Issue by trigpoint** [osmlab/name-suggestion-index#3440]
Thomas Cook travel agent went into administration on 23rd September, whilst the toour operator is no longer in existence the shops were bought by Hays Travel.

My local Thomas Cook travel agent continued with Thomas Cook branding, and Hays Travel on A4 paper on the doors and windows. It has now been fully rebranded.

As a side note, as well as taking over the local Thomas Cook, Hays have also opened a second shop in the local town centre so they are expanding fast outside of the Thomas Cook takeover.

I believe they bought all of the shops, but they will need confirmation.

However Thomas Cook should no longer exist on shops, they should probably be rebranded.

I am not sure how to raise a PR request for this.

**Comment by UKChris-osm** [comment]
Hays Travel already exists under **brands/shop/travel_agency.jsom**, so it's currently possible to add the brand to any Thomas Cook branches that they have taken over, but I expect it would be better for local surveys to be carried out first before any form of blanket re-branding.

I'm not sure what the NSI policy is for removing entries, whether it's done soon or if there is a waiting period until most (or all) existing uses of it on OSM are corrected.

**Comment by bmillemathias** [comment]
In France, the few Thomas Cook I saw were all replaced by Salaün Holidays.

**Comment by trigpoint** [comment]
Hays Travel does seem to have come from  nowhere very quickly. Local high street has two Hays Travel shops, one ex-Thomas Cook but the other was not previously a travel agent.

**Comment by UKChris-osm** [comment]
I think Hays Travel have seen an opportunity to get hold of the Thomas Cook branches on the cheap and have started an aggressive expansion to capitalise.

**Comment by doublah** [comment]
UK ones are probably good to upgrade to Hays Travel as all shops were bought by them in the UK.
Thomas Cook in India still operates under Thomas Cook name, and we should probably have an entry for Q23010921.
Germany is a ?
Thomas Cook China according to Wikipedia continue to operate by the other partial owner of the brand. Don't know if they even had stores though.

**Comment by bmillemathias** [comment]
I'm not sure this is a problem that can be fixed in this project for each ex-Thomas Cook travel agency in each country a different solution was found (for instance I came across an article about how TC agency in France were attributed, so they were at elast 3 differents new brands)

Perhaps something can be done in ID to suggest locally when selecting an Thomas Cook agency

**Comment by bhousel** [comment]
> Perhaps something can be done in ID to suggest locally when selecting an Thomas Cook agency

Yeah I agree - we should add something that at least flags the POI as dissolved so that someone can take attention and remove or rebrand it as needed.

**Comment by UKChris-osm** [comment]
> Yeah I agree - we should add a validator to iD that warns that the POI as dissolved so that someone can take attention and remove or rebrand it as needed.

Could the NSI be updated to include a fixme marker?

  "shop/travel_agency|Thomas Cook": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "Thomas Cook",
      "brand:wikidata": "Q2141800",
      "brand:wikipedia": "en:Thomas Cook Group",
      **"fixme":"brand no longer trading, possibly now a Hays Travel",**
      "name": "Thomas Cook",
      "shop": "travel_agency"
    }
  }

... or would this not work for already marked up nodes / ways?

**Comment by bhousel** [comment]
> Could the NSI be updated to include a fixme marker?

It would sort of work but not very well.. The user would need to choose to upgrade the brand first in order to see the `fixme` tag, then they would need to do the actual fix, and finally they would need to remember to delete the `fixme` tag.

I worry that people would find it kind of annoying if we use the `fixme` tag like this.

**Comment by bhousel** [comment]
Closing this - Thomas Cook appears in the dissolved file now that it is marked as such on Wikidata.
