### ISSUE TITLE
Add Yours clothing store

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3442]
https://www.yoursclothing.co.uk/
Clothing retailer in gb, ie, de, gg

**Comment by Adamant36** [comment]
@doublah, you have any opinion on adding a unique entry for BadRhino or not? It seems that they have different social media accounts and some seperate stores, but also a lot are just combined with Yours. It might be worth having different entries for them if its possible though.

**Comment by doublah** [comment]
If there's enough of them, it makes sense to add them as well, we have Monsoon and Accessorize, even though they're frequently combined

**Comment by UKChris-osm** [comment]
I've added "_Yours Clothing_" and "_BadRhino_" via a pull request. There are very few independent "_BadRhino_" outlets, but I added them as I can imagine mappers might add them as a node close to or within any "_Yours Clothing_" they are associated with.
