### ISSUE TITLE
"Figaro" (Philippine cafe chain) tagged as suspicious

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#3445]
I found that the name "Figaro" (a Philippine café chain) gets tagged as a suspicious. I don't know how it get tagged as such in the Names Suggestion Index.

The brand is question is a chain, with ~40 mapped in OSM per this [Overpass query](http://overpass-turbo.eu/s/PdS). The Wikipedia page is https://en.wikipedia.org/wiki/Figaro_Coffee_Company and the Wikidata item is at [Q17069806](https://www.wikidata.org/wiki/Q17069806)

**Comment by Adamant36** [comment]
Looks like its getting flagged as a generic name for some reason. That can happen. Luckily it can be fixed pretty easily though.
