### ISSUE TITLE
Add Hunt Brothers Pizza

### ISSUE THREAD

**Issue by MrSpoon** [osmlab/name-suggestion-index#3447]
Hunt Brothers Pizza is a pizza chain located inside a larger parent store. (gas stations, grocery stores, etc.) There is 7800+ locations but only 24 on the map.

name=Hunt Brothers Pizza
amenity=fast_food
cuisine=pizza
takeaway=yes
brand=Hunt Brothers Pizza
brand:wikipedia=en:Hunt Brothers Pizza
brand:wikidata=Q5943909
website=https://www.huntbrotherspizza.com/

**Comment by Adamant36** [comment]
Thanks, but this was already brought up and closed in #2586. I think the same reasons for it being closed still apply (not having a good way to tag them). Plus, this issue is a duplicate anyway. So I am going to close it also. Feel free to comment in #2586 though.
