### ISSUE TITLE
Adding "Buzz Bingo" to the list.

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3452]
Hello everyone,

I'm brand new to GitHub, so don't feel confident doing any form of editing, so could anybody more experienced check and possibly add "Buzz Bingo" to the Name Suggestion Index?

I'm not entirely sure if "adult_gaming_centre" is the right way to tag Buzz Bingo? Maybe a more generic "gambling=bingo" would be suitable?

Having read over some examples, I think the text that would need to be added to "adult_gaming_centre.jsom" would look like:

"leisure/adult_gaming_centre|Buzz Bingo": {
    "countryCodes": ["gb"],
    "tags": {
	"brand": “Buzz Bingo",
	"brand:wikidata": "Q60746117",
	"brand:wikipedia": "en:Buzz Bingo",
	"leisure": "adult_gaming_centre",
	"name": "Buzz Bingo",
    }
}

... but, I couldn't see such a file name under brands/leisure" so perhaps I'm also wrong on that as well?

**Comment by SilentSpike** [comment]
Hey, I can look at this in a little bit. Can't speak for the tagging just now, but you've got the syntax and file structure right 👍

The only reason there's no file by that name there currently is because there are no existing brands in the index with that tagging.

**Comment by UKChris-osm** [comment]
Thank you SilentSpike :)

**Comment by SilentSpike** [comment]
See what you mean about the tagging, don't understand why there was a proposal with a generic `amenity=gambling` tag that allows for granularity which also includes more specific restrictive tags 🤔

Do we know if all locations have slot machines? I'd be inclined to go with 
```
amenity=gambling
gambling=bingo;slot_machines
```

**Comment by UKChris-osm** [comment]
I've just checked with them, and they tell me all clubs have slot machines and a bingo hall.

**Comment by UKChris-osm** [comment]
Thanks for your help and quick addition SilentSpike :)

**Comment by UKChris-osm** [comment]
I just noticed [Add bingo hall preset](https://github.com/openstreetmap/iD/issues/7198) over on [iD](https://github.com/openstreetmap/iD), not sure if that has any relevance to this, but thought I would highlight it, just in case.

**Comment by quincylvania** [comment]
> I just noticed Add bingo hall preset over on iD, not sure if that has any relevance to this, but thought I would highlight it, just in case.

@UKChris-osm Thanks, @boothym raised this based off your diary post. Your link helped!
