### ISSUE TITLE
Add Hursts

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#3456]
Petrol station forecourt convenience store chain.

Not really much about this brand online, but MFG (the company that owns the brand) claims 299 sites [on their website](https://www.motorfuelgroup.com/partners/) so it should be significant.

UK only AFAIK.

**Comment by UKChris-osm** [comment]
It looks like a Hursts Wikidata has been created, although it's pretty bare and doesn't have any logo references.

 "shop/convenience|Hursts": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "Hursts",
      "brand:wikidata": "Q80975681",
      "name": "Hursts",
      "shop": "convenience"
    }
  }

**Comment by bhousel** [comment]
Thanks @UKChris-osm  I added it just now..
