### ISSUE TITLE
Centra Wikidata missing (Q747678)

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#3461]
Supermarket **Centra** actually has a wikidata entry (Q747678)

The corresponding row on https://nsi.guide/index.html?k=shop&v=supermarket is empty.

Please add :-)

**Comment by bhousel** [comment]
similar to #3469 
This is another brand that already exists in `shop/convenience`:
https://nsi.guide/index.html?k=shop&v=convenience#Centra

Would you say that:
* All Centras should be either a `shop/convenience` -or- a `shop/supermarket` and we should keep one correct entry?
-or-
* Centra can be either thing and so we need two entries.

**Comment by Adamant36** [comment]
According to their Wikipedia article and the article it cites they have three store formats. "The chain has three different formats available to franchisees — smaller Quick Stop outlets, mid-sized Foodmarkets, and larger Supermarkets." 

I would guess the Quick Stop outlets would be the convenience stores and could probably have a unique "Centra Quick Stop" entry. Then the other two formats could just be the Centra supermarket entry. Although it seems some convenience stores might just be named Centra. So, checking locally still might be a good idea, but it would be worth having a unique Centra Quick Stop entry anyway IMO. 

![Centra Quick Stop](https://user-images.githubusercontent.com/30259065/73345904-c726cf80-4239-11ea-816a-d74b9d573205.jpg)
![Centra Supermarket](https://user-images.githubusercontent.com/30259065/73345913-c9892980-4239-11ea-80dc-b5d8ddf5514f.jpg)

**Comment by bhousel** [comment]
> * Centra can be either thing and so we need two entries.

I did this ☝️
