### ISSUE TITLE
Revisiting the tagging schema for BDO (Philippines)

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/name-suggestion-index#3462]
Per research and the [FAQ document](https://www.bdo.com.ph/sites/default/files/pdf/BDO_FAQ_Website_FINAL.pdf) on its website, BDO/Banco de Oro doesn't use "Golden Bank" as its English name while "Banco de Oro" isn't used as its Spanish name but as one of the names and styles of the said bank. Based on what I've found, I'm suggesting that the naming schema for BDO be changed to the following:

"alt_name": "Banco de Oro"
"amenity": "bank"
"brand": "BDO"
"brand:wikidata": "Q4854129"
"brand:wikipedia": "en:Banco de Oro"
"name": "BDO"
"operator": "BDO Unibank"

**Comment by bhousel** [comment]
sounds good, thanks!
