### ISSUE TITLE
Add (German) Netto Markendiscount (Q879858)

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#3464]
So far there's only entry for Netto, which relates to Netto France (Les Mousquetaires)

There's a completly independent supermarket chain in Germany called Netto Markendiscount (Q879858)

Quote wikipedia:
"The chain is unrelated to the Danish Netto chain, which has operations in several German states, or the French-owned Netto discount store. However Edeka owns 25% of a joint venture with the Danish Netto."

Please include Netto Markendiscount as own brand for Germany.

**Comment by SilentSpike** [comment]
Is that not what this is?
https://github.com/osmlab/name-suggestion-index/blob/a9ce763679413adf17fe6038a64b202fd6a78931/brands/shop/supermarket.json#L2856-L2865

**Comment by Contrib1043** [comment]
Argh, must have mixed up something with the filters..
Sorry & nevermind..
