### ISSUE TITLE
Add (Danish) Netto (Q552652)

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#3465]
So far there's only entry for Netto, which relates to Netto France (Les Mousquetaires)

There's a completly independent supermarket chain in Denmark called Netto (Q552652)

Please include Netto as own brand for Denmark.

**Comment by SilentSpike** [comment]
Looks like this is already in:
https://github.com/osmlab/name-suggestion-index/blob/a9ce763679413adf17fe6038a64b202fd6a78931/brands/shop/supermarket.json#L2876-L2885

**Comment by Contrib1043** [comment]
Argh, must have mixed up something with my filters
Sorry & nevermind..
