### ISSUE TITLE
Londis Ireland vs Londis UK

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#3469]
While researching, I discovered that supermarkets Londis **Ireland** and **United Kingdom** are two independent companies under different ownership (see e.g. Wikipedia "Created Ireland-only page. The UK and Ireland Londis businesses are under completely separate ownership so therefore deserve their own pages.", quote from https://en.wikipedia.org/w/index.php?title=Londis_(Ireland)&action=history). 

Londis Ireland has a separate wikipedia page and wikidata item (Q21015800). 

To avoid confusion between Londis UK and Londis Ireland, I suggest including the following for Londis Ireland

"shop/supermarket|Londis": {
  "countryCodes": ["ie"],
    "tags": {
      "brand": "Londis",
      "brand:wikidata": "Q21015800",
      "brand:wikipedia": "en:Londis (Ireland)",
      "name": "Londis",
      "shop": "supermarket"
    }
  },

Any objections?

**Comment by doublah** [comment]
We actually already have both Londis brands in shop/convenience here: https://github.com/osmlab/name-suggestion-index/blob/9dd4a12d6e4cf71fbba02ea7f83ed7c9f8ca6072/brands/shop/convenience.json#L906-L925

I'm not sure if they're needed in shop/supermarket aswell.

**Comment by Contrib1043** [comment]
Good point!

Still I would suggest to add the same differentiation for shop=supermarket as well as we've got quite a couple of Londis shop=supermarkets in Ireland, see **https://overpass-turbo.eu/s/Pxw**

I would suggest to add "matchTags": ["shop/supermarket"] in the convenience file and remove the record in the supermarkets file. Any objections?

**Comment by bhousel** [comment]
> Still I would suggest to add the same differentiation for shop=supermarket as well as we've got quite a couple of Londis shop=supermarkets in Ireland,

If I understand correctly - you're saying both the UK Londis and the IE Londis can be tagged as either `shop/convenience` and `shop/supermarket`?  I just want to make sure I have it right before I make any change..

If this is the case, we don't want any `matchTags` property.  That property is used to list less-preferred tag combinations that we want to offer users to replace with the more-preferred tagging.

**Comment by mds08011** [comment]
Previous related issue for reference: https://github.com/osmlab/name-suggestion-index/issues/2966

**Comment by Contrib1043** [comment]
> If I understand correctly - you're saying both the UK Londis and the IE Londis can be tagged as either shop/convenience and shop/supermarket? 

I analysed the OSM data for Ireland - I would (roughly) estimate that 50% of Irish Londis stores are tagged as supermarkets, 50% as convenience. 

Maybe let's go back three days (see https://github.com/osmlab/name-suggestion-index/blob/eb978c15bf1dbed778e3df5c6aa79bd980c8b916/brands/shop/supermarket.json#L2303) to better explain the situation:

3 days ago we had the situation that convenience.json already had two records, one for UK, one for Ireland --> **everything perfectly fine** for convenience shops

**supermarket.json** in contrast had only one record with no distinction between UK and Ireland.

Ideally we have the **same structure** in convenience.json and supermarket.json, otherwise Londis convenience stores in Ireland will have wikidata links, whereas the supermarkets from exactly the same Irish company won't have wikidata links etc.

So if I understand your kind advice, the preferred way would be to add a second record for Ireland in the supermarket.json to achieve consistent tagging, right?

**Comment by bhousel** [comment]
> So if I understand your kind advice, the preferred way would be to add a second record for Ireland in the supermarket.json to achieve consistent tagging, right?

I really don't know.  We want to set this index up according to how these stores actually work in the real world.  Looking at the existing tagging could be useful, but it might be wrong.

For now in  8084d73 I just made it so both Londis UK and Londis Ireland can be either a supermarket or convenience store.
