### ISSUE TITLE
UK Supermarket Cafe's

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3473]
Would Supermarket Cafe's be suitable for the NSI?

All the major supermarkets within the UK have a Cafe brand, and many of the branches scattered around the Country have a branded cafe within the main Supermarket.

On OSM, many cafe's have their own node placed within the store area, named as you might expect, "Tesco Cafe", "Morrisons Cafe", etc, and so I think having an NSI brand available for each cafe would be useful.

My suggested code is below, and I'd welcome any for or against opinions for adding them to the index.

## brands/amenity/cafe.json

  "amenity/cafe|Asda Cafe": {
    "countryCodes": ["gb"],
    "tags": {
      "amenity": "cafe",
      "brand": "Asda Cafe",
      "brand:wikidata": "Q297410",
      "brand:wikipedia": "en:Asda",
      "cuisine": "coffee_shop",
      "name": "Asda Cafe",
      "takeaway": "yes"
    }
  },
  "amenity/cafe|M&S Cafe": {
    "countryCodes": ["gb","ie"],
    "matchNames": ["marks and spencer cafe"],
    "tags": {
      "amenity": "cafe",
      "brand": "M&S Cafe",
      "brand:wikidata": "Q714491",
      "brand:wikipedia": "en:Marks & Spencer",
      "cuisine": "coffee_shop",
      "name": "M&S Cafe",
      "takeaway": "yes"
    }
  },
  "amenity/cafe|Morrisons Cafe": {
    "countryCodes": ["gb"],
    "tags": {
      "amenity": "cafe",
      "brand": "Morrisons Cafe",
      "brand:wikidata": "Q922344",
      "brand:wikipedia": "en:Morrisons",
      "cuisine": "coffee_shop",
      "name": "Morrisons Cafe",
      "takeaway": "yes"
    }
  },
  "amenity/cafe|Sainsbury's Cafe": {
    "countryCodes": ["gb"],
    "tags": {
      "amenity": "cafe",
      "brand": "Sainsbury's Cafe",
      "brand:wikidata": "Q152096",
      "brand:wikipedia": "en:Sainsbury's",
      "cuisine": "coffee_shop",
      "name": "Sainsbury's Cafe",
      "takeaway": "yes"
    }
  },
  "amenity/cafe|Tesco Cafe": {
    "countryCodes": ["gb","ie"],
    "tags": {
      "amenity": "cafe",
      "brand": "Tesco Cafe",
      "brand:wikidata": "QQ487494",
      "brand:wikipedia": "en:Tesco",
      "cuisine": "coffee_shop",
      "name": "Tesco Cafe",
      "takeaway": "yes"
    }
  }

**Comment by bhousel** [comment]
Sure, if it makes sense to map these cafes-with-supermarkets as their own POI, and the UK community wants them mapped this way, I think it sounds good.  👍 

I'd like to hear from a few other contributors before we start doing it.

**Comment by SilentSpike** [comment]
It's something I've considered before, but never fully looked into. I see supermarket cafes mapped like this often, but I'm not so sure they should be named as such (e.g. "Asda Cafe") because it's a descriptive name really (in my experience they're not signed with the brand - there will just be something like "cafe" because you're already inside the store).

**Comment by UKChris-osm** [comment]
It's true that many in store cafe's tend to be marked as just "cafe" (although some Sainsbury's have started bearing the name "_Sainsbury's Cafe_" inside stores), and the name "cafe" would be technically correct, but if you attempt to use just "cafe" as a name within iD you're given an error message:

**Cafe has the suspicious name "_cafe_"**
"_Names should be the actual, on-the-ground names of features_"

... so that could cause quite a bit of confusion.

Whereas using the name "_Asda Cafe_" for an in store cafe would, I think, make everything simpler, unless something such as "_instore cafe_" was also a possibility?

**Comment by SilentSpike** [comment]
I think the name "cafe" would also wrong - my personal mapping preference would just be a cafe node with `brand=` inside the store. This wouldn't be possible to capture in the index though.

I think the best bet to see progress on this one is to consult the talk-gb mailing list on how such in-store cafe's should be mapped and whether a name tag is appropriate. That way there's a discussion that can be linked as evidence to support their inclusion in the index. If there's support for using such names then it'd be easy to do so.

I've done this before for some inclusions such as:
- https://github.com/osmlab/name-suggestion-index/commit/853ced7f194c70d9b8f192f45196c0fc889cc2e3
- https://github.com/osmlab/name-suggestion-index/commit/28beea77d73b0dd279e1e4ae934fba226a6bcbec

**Comment by UKChris-osm** [comment]
As I've never used talk-gb, I've started with a [diary post](https://www.openstreetmap.org/user/UKChris/diary/391862), if you'd like to you're welcome to copy / paste it into talk-gb to get to a wider audience.

**Comment by Adamant36** [comment]
@UKChris-osm, what's the benefit of having an entry for them in the name index aside from them then having names? If they are already mostly tagged as amenity=coffee_shop, I don't see what the point is Since none uniform tagging isn't an issue. Plus, in these cases I see it more like an operator thing. The cafe's aren't technically their own distinct brands. By adding the store title to the name its essentially just adding the operator name.

**Comment by Cj-Malone** [comment]
I would drop the names, I don't think they are universal eg some Morrisons have "Market Street" cafes and some just have "cafes". And then is "Asda Cafe" a description? in which case OSM doesn't want it.

User agents of OSM data should probably display the `name` and when that isn't available `brand` + " cafe", I think it's the same for fuel stations, `name` isn't necessary.

I would also drop cuisine, these instore cafe/restaurant menus vary quite a lot, even within a brand. eg [Asda Newport Isle of Wight](https://storelocator.asda.com/south-east/newport/st-georges-way) has a cafe, with a menu of ["Coffee Shop"](https://s7d2.scene7.com/is/content/asdagroceries/Asda.com/3.%20Landing%20pages/Cafe/191217%5Fadc%5Fcafe%5FMenu%5FCoffee%2DShops.pdf) and [Asda Pentwyn](https://storelocator.asda.com/wales/cardiff/8-dering-road-pontprennau) has a cafe with ["Express Diner"](https://s7d2.scene7.com/is/content/asdagroceries/Asda.com/3.%20Landing%20pages/Cafe/191217%5Fadc%5Fcafe%5FMenu%5FExpress%2DDiners.pdf) menu. And then the Asda near my grandparents house must have a different menu again as they go to eat there every Thursday.

I think the standard tags below are still useful to be on `amenity=cafe` in OSM, and assuming nsi presets can work without a `name` I would support them being in nsi.
```json
"brand": "Tesco"
"brand:wikidata": "Q487494"
"brand:wikipedia": "en:Tesco"
```

**Comment by Cj-Malone** [comment]
> Names are required for there to be an entry.

Is that an NSI or OSM requirement?

> Plenty of fuel stations have names that are completely valid.

But plenty don't really have names, just brands or operators, they are also completely valid.

> I'd be surprised if there wasn't at least some staples on the menus. Especially if the cuisine is something like "American." I highly doubt they frequently change from American cuisine to Chinese or similar. Same goes for in store deli's that serve sandwiches. Maybe they get rid of roast beef from the menu and add tuna now and then when there is a supply chain issue, but they just don't have the equipment, time, or a reason to switch the menus that drastically to often.

I'm not saying there shouldn't be a cuisine tag, this proposal said `cuisine=coffee_shop` for all supermarket cafes. I think that is inaccurate. I also don't believe there is a universal cuisine for all Asda cafes as the menus I linked shows. One is just drinks, the other is food, [another menu](https://s7d2.scene7.com/is/content/asdagroceries/Asda.com/3.%20Landing%20pages/Cafe/191217%5Fadc%5Fcafe%5FMenu%5FAsda%2DCafe.pdf) adds main meals after 1200. I think this varies too much to have one `cuisine` tag for all Asda cafes.

**Comment by bhousel** [comment]
> > Names are required for there to be an entry.
> Is that an NSI or OSM requirement?

It's a hard requirement in NSI currently.  It's strongly encouraged in OSM.

**Comment by Adamant36** [comment]
That seems to like more to do with different formats at different locations then a particular store changing its menu frequently. It looks like from the list most are  "Traditional Café." At least that's what they call them. We could also create a few different entries if need be. We need still need to pick an appropriate tag anyway and it seems like there might not be a one tag fits all option as it is anyway. Like I'm sure their coffee shop format is different from their Asda Kitchen format. We cant tag them the same. So, it looks like its either have different entries or none. 

https://corporate.asda.com/article/asda-cafe-store-lists

**Comment by bhousel** [comment]
> It's a hard requirement in NSI currently. It's strongly encouraged in OSM.

Update on this.. `name` isn't a hard requirement in NSI anymore.
I'm going to close here, but feel free to add the supermarket cafes as POIs with or without names, however you feel it is best. 

We've seen a few of these sneak into the NSI already , such as the Costco Food Court, and I think this is fine 👍
