### ISSUE TITLE
Consider ignoring order of semicolon-separated values when matching

### ISSUE THREAD

**Issue by quincylvania** [osmlab/name-suggestion-index#3475]
I'm not sure if the order matters when there are multiple values in a tag, but if not then I'd suggest ignoring it when matching brands. Warnings like this seem sort of trivial:

<img width="365" alt="Screen Shot 2020-01-09 at 2 19 52 PM" src="https://user-images.githubusercontent.com/2046746/72097844-484e0f00-32eb-11ea-9551-55816c6586a4.png">

**Comment by bhousel** [comment]
But it needs to be `donut;coffee_shop` to get the donut icon.  🍩

**Comment by bhousel** [comment]
Anyway this is an iD issue.

**Comment by quincylvania** [comment]
I'm pretty sure [matcher.js](https://github.com/osmlab/name-suggestion-index/blob/master/lib/matcher.js) would handle this, but I'm worried about it either way.

**Comment by bhousel** [comment]
> I'm pretty sure [matcher.js](https://github.com/osmlab/name-suggestion-index/blob/master/lib/matcher.js) would handle this, but I'm not worried about it either way.

No, `matcher.js` only considers the `key`, `value`, and `name`.. not tags like `cuisine`.
https://github.com/openstreetmap/iD/blob/2.x/modules/validations/outdated_tags.js#L95
