### ISSUE TITLE
nsi.guide counter comparison suggestion

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3479]
On the [nsi.guide](https://nsi.guide/) web site I've noticed each entry has a set of brackets at the end and seems to compare two values.

I believe this is a brand vs total comparison, in that it shows that for (as an example) **leisure/fitness_centre (30/33)**, that out of the total 33 entries in the list of **fitness_centre.json**, that only 30 of them have added brand tags.

If this is correct, is it possible to consider having a paragraph of text near the top of the page explaining what these comparisons are, just so others can easily see what they refer to, for example:

_If a record is missing a 'brand:wikidata' tag, you can do the research to add it to our project, or filter it out if it is not a brand. **Each entry below shows how many entries have brand:wikidata associated with them in brackets**. See CONTRIBUTING.md for more info._

Just an idea :)

**Comment by bhousel** [comment]
Yes it does say something like that already, but it could be made more clear: 

<img width="822" alt="Screenshot 2020-01-10 10 29 38" src="https://user-images.githubusercontent.com/38784/72164609-0200ba80-3394-11ea-8a0d-0dbdc9d4c44b.png">

**Comment by UKChris-osm** [comment]
I don't know how I missed that line, my apologies.

**Comment by bhousel** [comment]
> I don't know how I missed that line, my apologies.

no apology needed!  It's really not worded well.. I've wanted to change it for a while to be more clear, or maybe change the counts to be more useful or actionable.  I definitely welcome any feedback on how we can make the nsi.guide site more useful.

**Comment by UKChris-osm** [comment]
If I'm correct the [nsi.guide](https://nsi.guide) is hosted on GitHub, so does that mean you're limited with what you can do with it, such as little to no server side stuff?

I also noticed it seems to be entirely powered by JavaScript, via the [src.a2b27638.js](https://nsi.guide/src.a2b27638.js) file. Is that a requirement of hosting on GitHub or just how the site has been designed for this project?

**Comment by bhousel** [comment]
> If I'm correct the [nsi.guide](https://nsi.guide) is hosted on GitHub, so does that mean you're limited with what you can do with it, such as little to no server side stuff?

Yes, it's just a React app hosted on GitHub pages.  No server side stuff..

> I also noticed it seems to be entirely powered by JavaScript, via the [src.a2b27638.js](https://nsi.guide/src.a2b27638.js) file. Is that a requirement of hosting on GitHub or just how the site has been designed for this project?

I used [nano-react-app](https://github.com/adrianmcli/nano-react-app) to create the https://nsi.guide site.  nano-react-app uses a bundler called [parcel.js](https://parceljs.org/) to bundle all the React code and other dependencies into that single JavaScript file.  

Parcel also includes that random string of stuff in the filenames so that whenever a new version of the app gets built, all the files will get refreshed (you won't end up with an old javascript file from your cache - this is called [cache busting](https://www.keycdn.com/support/what-is-cache-busting)).

There isn't any requirement to do it this way, and we can serve any html, js, or other files from a GitHub page.  This is just how nano-react-app set it up.

**Comment by maxerickson** [comment]
Adding some space before the last line would make it stand out more. Could also make it longer:

Below is a list of categories that roughly match the categories used by OpenStreetMap. The numbers after each category show how many items in the category have Wikidata entries with logos / the total number of items in the category.

Another option would be to switch the number shown to the number of incomplete entries, and only show 2 numbers when the category is incomplete. It's a little harder to digest, but then the data is more actionable:

Below is a list of categories that roughly match the categories used by OpenStreetMap. A single number indicates the category has that many items, all of them complete. When there are 2 numbers, the first number indicates how many entries in the category are missing a Wikidata entry or do not have a logo in Wikidata, the second one is the total number of entries in the category.

**Comment by bhousel** [comment]
I reworded the instructions a bit and I also added an "Incomplete" checkbox to the filter, so people can focus just on brands that need something..
