### ISSUE TITLE
Add Moroccan Fuel Stations (Winxo, Ziz, Green Oil)

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#3480]
I recently traveled to Mococco and came across three brands of fuel/gas/petrol stations (`amenity=fuel`) which have many locations (and plenty more under construction) but are not in the NSI.  All three websites have french versions/translations.

~~Note that none of these brands have Wikidata entries yet.~~

### Winxo
- Website: http://winxo.com/
- Wikidata: https://www.wikidata.org/wiki/Q88389320

###  Ziz
- Website: http://www.ziz.ma/
- Wikidata: https://www.wikidata.org/wiki/Q88393228

###  Green Oil
- Website: https://www.greenoil.ma/
- Facebook: http://www.facebook.com/pages/Green-Oil/240145689415213
- Wikidata: https://www.wikidata.org/wiki/Q88393926

**Comment by ferdinand0101** [comment]
there currently are NO wikidata or wikipedia entries for those shops
