### ISSUE TITLE
tReds - shoe shop, but some branches also sell clothing.

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3482]
There is a brand called [tReds](http://treds.co.uk) in the South of England, which is mostly a shoe shop, but some stores also sell clothes as a secondary line. How would this best be included in the NSI, if at all?

As a shoe shop and left at that (with a matchtag for clothes maybe), or two separate entries, one for shoes and one for clothes, or as one entry just for clothes, or something else?

My initial code is:

  "shop/shoes|tReds": {
    "countryCodes": ["gb"],
    "matchTags": ["shop/clothes"],
    "tags": {
      "brand": "tReds",
      "brand:wikidata": "Q81647338",
      "name": "tReds",
      "shop": "shoes"
    }
  }

**Comment by bhousel** [comment]
Yeah the sportswear brands are all over the place.

- Adidas is `shop=sports`
https://nsi.guide/index.html?k=shop&v=sports#Adidas

- Nike is `shop=clothes`
https://nsi.guide/index.html?k=shop&v=clothes#Nike

- New Balance is `shop=shoes`
https://nsi.guide/index.html?k=shop&v=shoes#New%20Balance

We picked these categories based on how popular the tags were that people were using for the brands.  And I could see any of these being any of the tags - the business is mostly shoes, but you can also buy sportswear and maybe even some equipment or balls.

My suggestion is to not over-think it.  If it's _mostly_ a shoe store, just tag it as `shop=shoes` and it will have a shoe icon on the map.  

I don't think it's good to have multiple entries unless there is a really good reason.

**Comment by UKChris-osm** [comment]
I'd say it's mostly a shoe shop, so that's what I'll submit. You're right I'm probably trying to hard to have my entries exactly right, after all I'd feel very bad if I got anything wrong an interfered with an already existing and excellent project :)

Did the NSI start from automatic scans of the current OSM database? And whatever was the most used at the time is how each entry started out?

**Comment by UKChris-osm** [comment]
#3484 contained tReds in a Pull Request.
