### ISSUE TITLE
The Works - is "books" still accurate

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3483]
I just added a brand tag to "The Works" in my area, but noticed it's listed as a book shop, when it actually sells a lot more these days. Taken from the web site, they describe themselves as:

"_We stock books, toys, gifts, stationery and arts & crafts at discount prices, and sell over one million of our products every week to consumers looking for a bargain._"

... so I'm wondering if these needs reclassifying?

**Comment by bhousel** [comment]
I know these questions come up sometimes, but I'd just leave it classified as the main thing that the store sells.  

If I'm not sure, I mostly just consider what icon I want the marker to have on a map.  In the case of The Works, probably a book icon.  (The icons on https://nsi.guide are the same icons that iD editor uses.)

**Comment by UKChris-osm** [comment]
Thanks bhousel, I'll leave it as it is, overthinking to much, one of the problems of a newbie :)
