### ISSUE TITLE
countryCodes key explaination

### ISSUE THREAD

**Issue by QuentinS33** [osmlab/name-suggestion-index#3486]
Hi, 

What happened when "countryCodes" key is not an entry? In ID, what happened for OSM contributors? The name is already suggested wherever on the world? 
When "countryCodes" is written (for example "fr"), the brand name is suggested only in France or whenever on the world ?
Thanks in advance for clarification.

Quentin

**Comment by SilentSpike** [comment]
It sounds like you have the right understanding of how iD is using the country codes yes.

Keep in mind this index is it's own project, as far as the index is concerned a brand with `countryCodes` suggests that the brand is known to be present only in those countries. Conversely a brand without `countryCodes` just means that information isn't in the index (doesn't necessarily suggest the brand is global, but it is often used that way to avoid a massive list of country codes).

**Comment by bhousel** [comment]
Yes, currently if there is no `countryCodes` it's considered a global brand.
I'm working on something that will make this better soon though, so we will have the ability to include or exclude regions of the world.
