### ISSUE TITLE
Baguette bakery brand in Austria

### ISSUE THREAD

**Issue by MarkusGaugg** [osmlab/name-suggestion-index#3492]
For some time now, iD has been showing the following warning for cafes called baguette:
Café has the suspicious name "Baguette"

Baguette is the name of a tyrolean bakery company: 
https://www.baguette.at/

https://github.com/openstreetmap/iD/issues/7246

**Comment by bhousel** [comment]
Thanks for reporting @MarkusGaugg.  I've removed it from the generic name filter so it won't warn about the suspicious name anymore.

I couldn't find an entry on Wikidata or Wikipedia for this business, but we can keep it in the index until a Wikidata QID is available.

**Comment by MarkusGaugg** [comment]
Hello @bhousel. Thank you for your fast support. I've created a Wikidata Entry: https://www.wikidata.org/wiki/Q82512635 :-)

**Comment by bhousel** [comment]
Thanks @MarkusGaugg - I just added it to the index 👍

**Comment by Adamant36** [comment]
Wish there was a way with things like this to keep the generic warnings in countries where they are still generic. You think that's something that might be doable at some point?

**Comment by bhousel** [comment]
> Wish there was a way with things like this to keep the generic warnings in countries where they are still generic. You think that's something that might be doable at some point?

That's a good idea and it probably is something we can do... I'll split it off into a new issue..
