### ISSUE TITLE
Name Suggestions missing presets

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#35]
Since the name suggestion index was recently rebuilt, there are now a handful of name suggestions that don't correspond to presets in iD.

This isn't necessarily a bad thing, but I am just listing them here so that we can determine next steps to clean them up.

If a name suggestion doesn't have a preset, it either means that 
1. the thing is uncommon, or 
2. we should make a preset for those, or
3. the name suggestion might be assigned the wrong tag.

---

> WARN: no preset for suggestion = amenity,ice_cream,Grido
> WARN: no preset for suggestion = shop,ice_cream,Мороженое

^ Not sure what the best tagging is for ice cream shop these days.  There is disagreement here.

> WARN: no preset for suggestion = amenity,sauna,Баня
> WARN: no preset for suggestion = amenity,driving_school,Автошкола

^ Maybe we should add presets to iD for these?

> WARN: no preset for suggestion = shop,energy,Punto Enel

^ Not sure what is a `shop=energy`?

> WARN: no preset for suggestion = shop,charity,British Heart Foundation
> WARN: no preset for suggestion = shop,charity,Cancer Research UK
> WARN: no preset for suggestion = shop,charity,Oxfam
> WARN: no preset for suggestion = shop,charity,Scope
> WARN: no preset for suggestion = shop,charity,Age UK
> WARN: no preset for suggestion = shop,charity,Goodwill
> WARN: no preset for suggestion = shop,charity,Sue Ryder

^ Probably should add a `shop=charity` preset to iD.

> WARN: no preset for suggestion = man_made,windmill,De Hoop

^ I don't see why this is included in the name suggestion index?

**Comment by math1985** [comment]
Thanks for this analysis, very useful.

> ^ Not sure what the best tagging is for ice cream shop these days. There is disagreement here.

amenity=ice_cream is more popular than shop=ice_cream, so personally I'd say amenity=ice_cream should be added to iD. Ultimately that should be discussed in the iD repository of course.

> ^ Maybe we should add presets to iD for these?

Agree, also a thing for the iD repo of course.

> ^ Not sure what is a shop=energy?

Could it be a shop where you could conclude a contract with an electricity/gas provider in countries with a free energy market?

> ^ Probably should add a shop=charity preset to iD.

It's in common use, so seems sensible.

> > WARN: no preset for suggestion = man_made,windmill,De Hoop

> I don't see why this is included in the name suggestion index?

Many windmills in the Netherlands are called 'De Hoop' (literally 'The Hope'). It's not a chain of course, just a frequent name. I'm neutral to whether or not we should include it in name-suggestion-index.

**Comment by math1985** [comment]
I think I don't see cases where "the name suggestion might be assigned the wrong tag", but let me know if you feel differently.

**Comment by bhousel** [comment]
oh, since I opened this:
* we added a preset to iD for `amenity=ice_cream` 
* we added a preset to iD for `shop=charity` 

So I only see these ones now:
```
WARN: no preset for suggestion = amenity,sauna,Баня
WARN: no preset for suggestion = amenity,driving_school,Автошкола
WARN: no preset for suggestion = shop,energy,Punto Enel
WARN: no preset for suggestion = shop,ice_cream,Мороженое
WARN: no preset for suggestion = man_made,windmill,De Hoop
```


> I think I don't see cases where "the name suggestion might be assigned the wrong tag", but let me know if you feel differently.

Just the `shop=ice_cream` one should maybe be switched to `amenity=ice_cream`?  I am not sure. 

I'm not really familiar enough with these names to know if the tag suggestion is ok.  It's fine to leave them out of iD for now until we get feedback from someone with local knowledge.

**Comment by matkoniecz** [comment]
Is it fixed by merged #39?

**Comment by bhousel** [comment]
> Is it fixed by merged #39?

No, there is only one left:
```
WARN: no preset for suggestion = shop,ice_cream,Мороженое
```
and the thing is still listed as a `shop=ice_cream` here:
https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json#L9273

I guess that would make sense for a place that just sells packages of ice cream and you can not eat it there.   If it has seating it's more of an `amenity=ice_cream`.

**Comment by HubMiner** [comment]
Russian names in the list above are not proper nouns, and likely should not be used as place names.

WARN: no preset for suggestion = amenity,sauna,Баня
WARN: no preset for suggestion = amenity,driving_school,Автошкола
WARN: no preset for suggestion = shop,ice_cream,Мороженое

**Comment by bhousel** [comment]
Thanks @HubMiner, just added "Мороженое" which was the only one left on the list.
