### ISSUE TITLE
Duplicate entries E.Leclerc Drive

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#3512]
Currently there are two entries for E.Leclerc Drive
 
https://github.com/osmlab/name-suggestion-index/blob/9208270a60abb4d3239331e35e2b60fc6ea1fac4/brands/shop/supermarket.json#L1180

https://github.com/osmlab/name-suggestion-index/blob/9208270a60abb4d3239331e35e2b60fc6ea1fac4/brands/shop/supermarket.json#L2268

Shouldn't this be merged into one entry, preferrably **E.Leclerc Drive** as the official spelling according to their homepage? 

(Mind the missing E. in the second record..)

**Comment by bmillemathias-1a** [comment]
Yep, you're right, the second one has not even the tags.
Do you mind doing a PR for that ?

**Comment by Contrib1043** [comment]
Thanks guys :-)
