### ISSUE TITLE
Waves Car Wash, UK

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3518]
Would a car wash be something that's suitable for the NSI?

I can't see a _car_wash.json_ file under amenity, but **Waves** have a number of "by hand" car washes dotted about the UK, many within Supermarket car parks (Tesco, Asda, Morrisons, etc), but are branded as Waves, as opposed to the supermaket in question.

"amenity/car_wash|Waves": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "Waves",
      "brand:wikidata": "Q81802122",
      "name": "Waves",
      "amenity": "car_wash"
    }
  }

I thought I would post the query first, to get some other opinions, but also because if it is suitable, I don't know how to create a new file :)

**Comment by bhousel** [comment]
I think this is ok 👍

**Comment by mds08011** [comment]
>...but also because if it is suitable, I don't know how to create a new file

@UKChris-osm The easy/lazy method would be to copy an existing *.json* file, rename it to *car_wash.json*, and then replace the content with your car wash entry.  Just be careful to keep the appropriate syntax at the beginning and end of the json file.  Let me know if you need help with this.

**Comment by UKChris-osm** [comment]
Thanks @mds08011, I didn't realise it was just a case of creating the new _.json_ file, as I thought other code within the project might need to reference the existence of the file in some way.

I've created #3519 which hopefully I've done correctly.
