### ISSUE TITLE
Add Taziki's

### ISSUE THREAD

**Issue by joecaruso** [osmlab/name-suggestion-index#3545]
https://www.wikidata.org/wiki/Q19849840
https://en.wikipedia.org/wiki/Taziki%27s_Mediterranean_Caf%C3%A9

> amenity=restaurant
> cuisine=mediterranean

**Comment by UKChris-osm** [comment]
Are you able to add the social media entries to the Wikidata article for this entry? It would help the NSI grab the logo of the brand.

**Comment by joecaruso** [comment]
I don't have a wikidata account, but here are the links 

https://twitter.com/tazikis
https://www.facebook.com/TazikisMedCafe/
https://www.instagram.com/tazikis

**Comment by UKChris-osm** [comment]
Hi @joecaruso, an account isn't needed to edit a Wikidata article, you can edit it by clicking the "_+ add statement_" link roughly halfway down the page on the right.

Clicking this will bring up an entry box, which you can type in a "_property_" and in this box you can type "_Facebook_", "_Twitter_" etc and it will offer the correct property for each social media entry that is available, and in the box that appears to the right, you can add the correct username for each entry, such as:

**Facebook ID**: _TazikisMedCafe_
**Twitter Username**: _tazikis_
**Instagram Username**: _tazikis_

With each entry you add, if you also select "_+ add reference_", you can add details of where the information came from. For something like a social media entry, I tend to add "_retrieved_" which is the date I checked the data, and "_reference URL_" for the web site I found the social media link on, which is usually the home page of the brand in question.

Feel free to give it a go, as knowing how to improve Wikidata articles is a great way to help with the Name Suggestion Index (NSI) :)

**Comment by Adamant36** [comment]
Closed in #3546.
