### ISSUE TITLE
Disambiguate Eurotyre

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#3550]
We have an entry for Eurotyre now : 
https://nsi.guide/index.html?k=shop&v=tyres#Eurotyre

It looks like there are only a handful of these mapped in OSM:
https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A60%5D%3B%0A(nwr%5B%22shop%22%3D%22tyres%22%5D%5B%22name%22%3D%22Eurotyre%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B&R

I did a web search and it seems like there are several of these, so we should probably figure out which ones operate where and create separate entries with disambiguators:
https://www.eurotyre.fr/
https://www.euro-tyre.com/en/
https://www.eurotyre.pt/
http://www.eurotyre.de/

**Comment by Cerebrovinny** [comment]
Hi @bhousel I would like to help yours with this project, so to fix this all you need is to add another Eurotyre countries in Json file?

**Comment by bhousel** [comment]
done in #3758
