### ISSUE TITLE
Add brand AWG-Modecenter

### ISSUE THREAD

**Issue by Bingo67** [osmlab/name-suggestion-index#3552]
the name of the brand AWG is AWG-Modecenter
brand:wikipedia=de:AWG-Modecenter
brand:wikidata=Q300220

**Comment by bhousel** [comment]
done in #3553

**Comment by Bingo67** [comment]
Thanks for adding, but now I'm not sure if the Wikipedia name AWG-Modecenter is the right name.
On https://www.awg-mode.de/ the name of the stores is AWG Mode Center. On taginfo you find a few combinations of AWG and Mode and Center.  Maybe it is a good compromise that you added AWG as short_name, because AWG has the most hits on taginfo. Can you tell me, when the change will work in iD editor?

**Comment by bhousel** [comment]
> Can you tell me, when the change will work in iD editor?

I can make a name-suggestion-index release that will start working right away in the iD development mirror, but it will probably be a while before we make another official iD release so that it is available on osm.org

**Comment by Bingo67** [comment]
Ok, i can wait :-) until now it is not working (see attachment)
![2020-02-25 10_42_15-Window](https://user-images.githubusercontent.com/59020063/75235933-55e92680-57bd-11ea-9308-7c8c173784ca.jpg)
