### ISSUE TITLE
after school tutoring brands (de)

### ISSUE THREAD

**Issue by ferdinand0101** [osmlab/name-suggestion-index#3554]
There are Schülerhilfe (Schülerhilfe(Q2259702))
Studienkreis (Studienkreis(Q2358555))

I would like to add them but I'm unsure if I should use the unsupported but used amenity tutoring or amenity school which is documented but doesn't fit well

**Comment by bhousel** [comment]
These look like good additions and we have several entries like this in the index already.

I'd use the `amenity=prep_school` tag: 
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dprep_school

(Note that this tag `prep_school` has a meaning that is different from what most people consider a "prep school" in British or American language.)
