### ISSUE TITLE
Add FATZ

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3558]
American and Canadian restaurant chain that serves American cuisine. 

https://en.wikipedia.org/wiki/Fatz
https://www.wikidata.org/wiki/Q5424504
https://fatz.com/

**Comment by valoTN** [comment]
Hi, i added this brand just now

**Comment by bhousel** [comment]
done in #3562

@valoTN, A cool GitHub tip for future PRs - you can include some text like "closes #3562" in your commit message or pull request, and GitHub will close the issue for us automatically when it merges. 💪

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by valoTN** [comment]
@bhousel, Thanks for the advice, this was my first ever contribution on a public project.

**Comment by bhousel** [comment]
> @bhousel, Thanks for the advice, this was my first ever contribution on a public project.

That's great, welcome!   Looking forward to many more 🎉
