### ISSUE TITLE
Web Site idea & Version NSI query

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3563]
Just out of interest, which release version of the NSI is currently available via the iD Editor?

I see from the NSI GitHub page that release 29, version 4.0.0 was made available 22 days ago, but is this version currently available within iD? Or does the release version here then have to be made available via another iD update?

Leading on from that, I think on the [nsi.guide](https://nsi.guide/) web site, for each entry, it could be handy to have some form of marker that highlights if a current entry is live within iD, such as a small green dot / tick to mean it's available in iD now, and a yellow dot / question mark to indicate its not yet available but will be when the next update is released.

**Comment by SilentSpike** [comment]
Currently it's whichever version was released at the time which the latest iD version was released (with a few exceptions where this won't be the case). However, future versions of iD will pull the data in at runtime instead of bundling it.

**Comment by SilentSpike** [comment]
As for the website, it's probably not worth implementing that since it represents this project and not iD. There are other users of this data downstream too (Vespucci for example).

**Comment by UKChris-osm** [comment]
> However, future versions of iD will pull the data in at runtime instead of bundling it.

Ah, that'll be handy, thanks.
Is that something that will be happening soon, or is it a little way away yet?

**Comment by bhousel** [comment]
> Is that something that will be happening soon, or is it a little way away yet?

This works now on the 2.x branch, which is here: https://2-x--ideditor.netlify.com

For example I see this entry for IMO car wash that was just added in the latest release:
<img width="300" alt="Screenshot 2020-02-29 08 58 30" src="https://user-images.githubusercontent.com/38784/75608908-c780e780-5ad1-11ea-8b03-1900f2958d99.png">

On the iD side, I need to do a bit of work to make this better.  It still requires the NSI presets to be built into `presets.json`, and this requires a build step, so the projects aren't as independent yet as I'd like.

**Comment by UKChris-osm** [comment]
> This works now on the 2.x branch, which is here: https://2-x--ideditor.netlify.com

Ah, I see it there, thanks - I notice 2.x has a really good multi-select feature as well, definitely looking forward to that :)

> On the iD side, I need to do a bit of work to make this better.

That will be great when it's done :) I can't really offer any help in that regard, as it probably involves quite a bit of skill, so I'll just try and add a few more missing entries to the NSI :)
