### ISSUE TITLE
Add DriveTime

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3564]
American car dealer chain
https://en.wikipedia.org/wiki/DriveTime
https://www.wikidata.org/wiki/Q5307879

**Comment by prayagd** [comment]
Hello, 
I would like to work on this issue. Should i add this in brands/shop/second_hand or someplace else?

**Comment by Adamant36** [comment]
Hi there. Go for it. I'd put it under brands/shop/car.json and just add second_hand=only. That's what the Wiki recommends. It doesn't really fit the definition of a second hand shop anyway.
