### ISSUE TITLE
Add ENSA

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3565]
Angolan insurance company
[Wikipedia](https://en.wikipedia.org/wiki/ENSA_%E2%80%93_Seguros_de_Angola)
[Wikidata](https://www.wikidata.org/wiki/Q5323726)

**Comment by gabemanfroi** [comment]
Hey there!
I'm a begginer with open source, I think this task is a good first-issue to me, could I be assigned to it?
Thank you!

**Comment by bmillemathias-1a** [comment]
> I'm a begginer with open source, I think this task is a good first-issue to me, could I be assigned to it?

Ok, no problem. As far as I know we don't assign tasks.
Just provide the patch and that'll be good.

**Comment by gabemanfroi** [comment]
> > I'm a begginer with open source, I think this task is a good first-issue to me, could I be assigned to it?
> 
> Ok, no problem. As far as I know we don't assign tasks.
> Just provide the patch and that'll be good.

Thanks for the Attention!

**Comment by ferdinand0101** [comment]
It seems to be added now.
Please close it

**Comment by Adamant36** [comment]
Closed in #3574.
