### ISSUE TITLE
Split Eurobank entry

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3568]
The current entry for Eurobank seems to be three different banks.

Current entry (Poland)
[Q9256201](https://www.wikidata.org/wiki/Q9256201)

Eurobank Ergasias (Greece, Cyprus, Luxembourg, Serbia, Bulgaria and UK)
[Q951850](https://www.wikidata.org/wiki/Q951850)

Eurobank a.d. (Serbia)
[Q5411684](https://www.wikidata.org/wiki/Q5411684)

In OSM all three of them are just called Eurobank.

**Comment by ArenaL5** [comment]
Checking Wikipedia and their website tells me that Eurobank was absorbed by Bank Millenium ([Q4855947](https://www.wikidata.org/wiki/Q4855947)).

The other two entries should be easy to resolve by just adding countryCodes, right? The only conflict is in Serbia, but as far as I recall iD only raises an alert if there's one single match.

**Comment by bhousel** [comment]
From what I can tell, this was mostly done already..

The Polish item is gone, as the bank is defunct and absorbed by another, the other two items exist with decent `locationSets` - I will add the countries where Eurobank Ergasias operates:

https://github.com/osmlab/name-suggestion-index/blob/031b8ffc0a01e2a919d11a553b9890742adadd5c/data/brands/amenity/bank.json#L4405-L4428
