### ISSUE TITLE
Fix `npm run wikidata` script to run as GitHub action or uncredentialed

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3569]
Is there any reason why [nsi.guide](https://nsi.guide) seems to no longer show any Twitter logos?

**Comment by ferdinand0101** [comment]
the [twitter api](https://api.twitterstat.us/) does not show any issues so it's probably a bug somwhere on this side

**Comment by UKChris-osm** [comment]
It looks like "_wikidata.json_" hasn't had any Twitter Logo reference's added to the file during the latest build, and "_build_wikidata.js_" has some Twitter API code commended out.

Looking at [wikidata.json](https://github.com/osmlab/name-suggestion-index/commits/master/dist/wikidata.json), the latest edit by @ArenaL5 12 days ago seems to have removed a lot of data from the file, with 5,142 deletions - maybe those deletions were the Twitter logo references?

Was the Twitter API disabled?

**Comment by bhousel** [comment]
I just reran it a few seconds ago, and I think they are back.

**Comment by UKChris-osm** [comment]
Yes, all there, well done @bhousel :)

Was still a good excuse for me to look through some of the code and see what makes the NSI tick :)

**Comment by bhousel** [comment]
yes!  `npm run wikidata` should fetch the latest, but you need twitter application credentials to run it.  I'd like to eventually move this to a GitHub action or something.

**Comment by ArenaL5** [comment]
> but you need twitter application credentials to run it.

I'm sorry, I didn't know this - I did run `npm run wikidata` blindly.

**Comment by bhousel** [comment]
> I'm sorry, I didn't know this - I did run `npm run wikidata` blindly.

No worries.. I'll reopen this issue to fix the script.
