### ISSUE TITLE
nsi.guide html title is just "brands"

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#3573]
It deserves better title and certainly some metadata to have a better SEO.

**Comment by UKChris-osm** [comment]
If any edits to the web site are done, is it best to do it within the **/app/** folder or **/docs/** folder?

**Comment by bhousel** [comment]
> If any edits to the web site are done, is it best to do it within the **/app/** folder or **/docs/** folder?

Edit files under **/app**
Then `npm run docbuild` will generate the files under **/docs**
