### ISSUE TITLE
Add V-Markt supermarket brand

### ISSUE THREAD

**Issue by carstenhag** [osmlab/name-suggestion-index#3576]
Wikidata: Q2505135, could be more complete though
Wikipedia: https://de.wikipedia.org/wiki/Georg_Jos._Kaes

**Comment by abdo28** [comment]
Hey there!
I'm a beginner with open source, I think this task is a good first-issue to me, could I be assigned to it?
Thank you!

**Comment by carstenhag** [comment]
Hey abdo, sure, you can do this. I guess only contributors can assign someone, but this shouldn't be a problem. Link this issue when you are creating the Pull Request and you are going to be fine! :)

**Comment by jimohabdol** [comment]
I would like to be a contributor to this project

**Comment by Adamant36** [comment]
@jimohabdol, feel free to contribute. This issue already has a PR for it, but there other issues that are good for first time contributors. It's usually pretty straightforward, but there's a guide in the CONTRIBUTING.md file if you need it. Also, if you have any questions just ask.
