### ISSUE TITLE
Best way to add "NM Money" - UK

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3581]
In the UK, **NM Money** are taking over the Bureau de Change branches of EuroChange, and many of them are adding extra services, such a mortgage advice, insurance advice, etc.

Would NM Money then best be described as "_office/financial_advisor_"??

  "office/financial_advisor|NM Money": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "NM Money",
      "brand:wikidata": "Q86529747",
      "name": "NM Money",
      "office": "financial_advisor"
    }
  }

They would still have the standard Bureau de Change counter, but also desk space / rooms for mortgage advice, etc. Is there any additional tags I could add to the above to indicate travel money services as well?

**Comment by mds08011** [comment]
> many of them are adding extra services, such a mortgage advice, insurance advice, etc.

Do you know approximately how many?  Most or just some?

My initial though could be to have multiple NM Money entries: `office=financial_advisor` and `amenity=bureau_de_change` and start tagging the currency counters and back offices separately.

**Comment by UKChris-osm** [comment]
> Do you know approximately how many? Most or just some?

Unfortunately not yet, as it's an ongoing change throughout the UK, but I believe they will all retain Bureau de Change counters, so my initial theory was to keep them as amenity=bureau_de_change, as I remember seeing in other threads here that a dominant service is probably the best selection for the NSI.
 
> My initial though could be to have multiple NM Money entries: `office=financial_advisor` and `amenity=bureau_de_change` and start tagging the currency counters and back offices separately.

If that was the case, could they both be named "NM Money" as one is an 'office' and another an 'amenity', or would the names still need to be unique, such as "NM Money ~ Bureau de Change" / "NM Money ~ Financial Advice"?

**Comment by mds08011** [comment]
> If that was the case, could they both be named "NM Money" as one is an 'office' and another an 'amenity', or would the names still need to be unique, such as "NM Money ~ Bureau de Change" / "NM Money ~ Financial Advice"?

They could have the same name in different category (both just "NM Money").  A similar solution was used for the Londis [supermarkets](https://nsi.guide/index.html?k=shop&v=supermarket#Londis~(UK)) and [convenience stores](https://nsi.guide/index.html?k=shop&v=convenience#Londis~(UK)).

**Comment by UKChris-osm** [comment]
> They could have the same name in different category (both just "NM Money"). A similar solution was used for the Londis [supermarkets](https://nsi.guide/index.html?k=shop&v=supermarket#Londis~(UK)) and [convenience stores](https://nsi.guide/index.html?k=shop&v=convenience#Londis~(UK)).

Thanks @mds08011, I think I'll do it that way :)

**Comment by mds08011** [comment]
Resolved via: https://github.com/osmlab/name-suggestion-index/commit/9dc391a06928966a37de0a54be8723e87dced546 & https://github.com/osmlab/name-suggestion-index/commit/a54cc81011d92fd46f3f1c67758205fa0696840a
