### ISSUE TITLE
Add ABC Warehouse

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3586]
American appliance store chain
https://en.wikipedia.org/wiki/ABC_Warehouse
https://www.wikidata.org/wiki/Q4650261

**Comment by parmeet9891** [comment]
I have submitted a pull request for adding this brand. Test Once.

**Comment by Adamant36** [comment]
Hhhhmmm, I don't see one.

**Comment by parmeet9891** [comment]
I had created a pull request and it was accepted.
Check Here - [https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/electronics.json]

**Comment by Adamant36** [comment]
Oh. I didn't see it in the list of closed of PRs. I guess I'll close this issue then.
