### ISSUE TITLE
Add Spaces coworking company

### ISSUE THREAD

**Issue by mds08011** [osmlab/name-suggestion-index#3590]
Spaces is an `amenity=coworking` brand.  ~~It does not have a Wikidata page yet.~~  According to the website, they have "over 389 locations around the globe".

**Brand Name**: Spaces
**OSM Tags**: `amenity=coworking`
**Website**: https://www.spacesworks.com
**Example on OSM**: https://www.openstreetmap.org/node/7280862295

**Comment by Adamant36** [comment]
394 locations according to their website. I guess "over 389 locations around the globe" sounds better though 😄 

[Q87629680](https://www.wikidata.org/wiki/Q87629680)

**Comment by mds08011** [comment]
Actually, I think the 394 count includes a few "coming soon" locations. Negligible either way.

**Comment by Adamant36** [comment]
Oh, that makes sense. As far as Wikidata is concerned,  I'm just going to go with 394. 

Your welcome.
