### ISSUE TITLE
query generated by nsi.guide on overpass are broken

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#3592]
I don't know if something changed on overpass' side but the queries currently lead to error
```
[out:json][timeout:60];
(nwr["shop"="funeral_directors"]["name"="PFG"];);
out body;
>;
out skel qt;
```
```
Error: line 2: parse error: Unknown type "nwr"

Error: line 2: static error: For the attribute "type" of the element "query" the only allowed values are "node", "way", "relation" or "area"
```

**Comment by bhousel** [comment]
Weird!  It is working for me right now.  
Can you try again in a little while?  Maybe it is just a temporary issue on the Overpass Turbo side.

**Comment by bmillemathias** [comment]
> Weird! It is working for me right now.

hoooooo. I've configured it to use french instance //overpass.openstreetmap.fr/api/
Don't know why it does not work the same.

**Comment by bmillemathias** [comment]
French mate confirmed the version used is lagging behind thus not supporting `nwr`
