### ISSUE TITLE
Provide "Rich" JOSM presets.

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#3598]
The existing presets are all JOSM "one click" presets that don't do anything other than set the values associated with the NSI entry. It's likely possible to reuse existing JOSM presets to provide richer input, for example: https://josm.openstreetmap.de/browser/trunk/resources/data/defaultpresets.xml#L3021

It may be a better project to implement direct support in JOSM:

https://josm.openstreetmap.de/ticket/15217

**Comment by bhousel** [comment]
I'm going to close this , but I think it's a great idea for someone with more experience in JOSM presets to take on.  It might be good candidate for a new project?
