### ISSUE TITLE
Split First State Bank

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3599]
They are all located in the United States. 

Q87647395 - Florida
Q87647340 - Illinois
Q87647452 - Mississippi
Q87647479 - Michigan 
Q87647374 - Ohio
Q5453817 - Nebraska
Q87646525 - Nebraska
Q87647065 - Texas

I think that's all of them 🤣

**Comment by 1ec5** [comment]
Nothing from Delaware? 😮

**Comment by Adamant36** [comment]
Closed in #3675
