### ISSUE TITLE
Don't use name=Nails to designate a Nail Salon. 

### ISSUE THREAD

**Issue by skorasaurus** [osmlab/name-suggestion-index#36]
While searching for nail salons iD, I saw the results 'Nails' emerge as one of the first results and its tags were beauty=shop and name=Nails, as indicated below. 
![nails](https://cloud.githubusercontent.com/assets/955351/19627107/8134186c-990d-11e6-8a18-f08120364ffc.png)

This isn't the proper tagging for a nail salon (shop=beauty and beauty=nails) and I'm skeptical that 'Nails' is the name for many beauty salons and think it is an error and its usage is being reinforced by newer mappers who don't know that this is the incorrect tag for a nail salon.

**Comment by boothym** [comment]
This was brought up in the iD repo here - https://github.com/openstreetmap/iD/issues/3357 - apparently should be fixed in the next version of iD, which is taking a bit longer than normal to be released.

**Comment by bhousel** [comment]
this was done
