### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3639]
@bhousel, I think we broke something 😢

**Comment by UKChris-osm** [comment]
Apparently the following file isn't found by the web browser:
[https://raw.githubusercontent.com/openstreetmap/iD/master/data/taginfo.json](https://raw.githubusercontent.com/openstreetmap/iD/master/data/taginfo.json)

So is the issue [nsi.guide](https://nsi.guide), or iD Editor?

**Comment by UKChris-osm** [comment]
Has the master branch of the iD Editor vanished, or did it never exist under that name??

**Comment by UKChris-osm** [comment]
Are you able to edit the [nsi.guide](https://nsi.guide) JS file to change the reference from:
... raw.githubusercontent.com/openstreetmap/iD/ **master** /data/taginfo.json
... to ...
... raw.githubusercontent.com/openstreetmap/iD/ **develop** /data/taginfo.json
... and see if it starts working again??

**Comment by johanricher** [comment]
The iD repo README was updated 2 days ago: https://github.com/openstreetmap/iD/commit/32600f993fb9d394d69179de0a85b8851f5f09ce.

`v3-prototype` is their replacement branch for `master`. Weird workflow but ok.

**Comment by UKChris-osm** [comment]
That'll be the cause then :)

Perhaps chaining the URL reference from **master** to **release** would be the best thing to do for now?

**Comment by UKChris-osm** [comment]
Made the change via Pull Request: #3640

Others (@bhousel) may actually prefer to use a different branch, however (such as **develop**)

**Comment by quincylvania** [comment]
Hi friends 👋

Apologies for the breakage! iD's so-called `master` branch had turned into an experimental branch so we had to change the name. The `release` branch will continue to be the most stable so it's fine to reference that. Alternatively you could reference the `develop` branch to get changes as we make them. These branch names should be stable for the foreseeable future.

**Comment by UKChris-osm** [comment]
Thank you @quincylvania

**Comment by maxerickson** [comment]
Note, need to run 'npm run docbuild' to pick up changes to the website sources. Did that a minute ago.

**Comment by Adamant36** [comment]
Yes, thanks @quincylvania. It looks like a lot of the iD icons in the tag list aren't loading now though.

**Comment by UKChris-osm** [comment]
I think those icons are still referring to the master branch in the URLs.

**Comment by UKChris-osm** [comment]
I can see in the taginfo.json file that the master branch is referenced twice, so maybe this file is in need of an update:

{
  "data_format": 1,
  "data_url": "**#gitURL#**/openstreetmap/iD/**master**/data/taginfo.json",
  "project": {"name": "iD Editor", "description": "Online editor for OSM data.", "project_url": "**#gitURL#**/openstreetmap/iD", "doc_url": "**#gitURL#**/openstreetmap/iD/blob/**master**/data/presets/README.md", "icon_url": "**#jsdelivrURL#**/gh/openstreetmap/iD@release/dist/img/logo.png", "keywords": ["editor"]},

When looking at [nsi.guide](https://nsi.guide) I've noticed that the icons seem to be coming from multiple locations, some working and some not, such as:

https://cdn.jsdelivr.net/gh/ideditor/temaki/icons/car_wash.svg
https://cdn.jsdelivr.net/gh/mapbox/maki/icons/casino-15.svg
https://cdn.jsdelivr.net/gh/openstreetmap/iD@master/svg/fontawesome/fas-charging-station.svg

.. where the last one which references @master is now missing, but are these multiple URL's necessary? Is there not a single location where all the icons are stored for iD?

**Comment by UKChris-osm** [comment]
Asked about this on iD: https://github.com/openstreetmap/iD/issues/7453

**Comment by Adamant36** [comment]
> Asked about this on iD: openstreetmap/iD#7453

Thanks. It's kind of odd that the icons aren't located in a single place. 

> A lot of the icons in that file also refer to @master.

I bet that Oleg Smirnov guy gets pinged about a lot of none sense 😆

**Comment by UKChris-osm** [comment]
@quincylvania appears to have updated taginfo.json :)

**Comment by quincylvania** [comment]
> I think those icons are still referring to the master branch in the URLs.

Yep, this was the issue. Thanks for reporting. This is why we shouldn't change branch names very often 😅

> It's kind of odd that the icons aren't located in a single place.

@Adamant36 iD presets can use icons from five different projects so we reference the source projects as much as possible for this kind of thing.

**Comment by UKChris-osm** [comment]
Thank you @quincylvania

I've changed the web site reference from "**release**" to "**develop**" so we get quicker updates.
(https://github.com/osmlab/name-suggestion-index/commit/f053e7028f9f86415743b201eb86256181ff9a1e)

**Comment by johanricher** [comment]
> @quincylvania appears to have updated taginfo.json :)

Only on the `develop` branch: https://github.com/openstreetmap/iD/blob/develop/data/taginfo.json, the [other branches](https://github.com/openstreetmap/iD/branches) have not been updated.

**Comment by maxerickson** [comment]
@UKChris-osm I'm not sure I know how to run docbuild either.

All I did was 
    git fetch upstream
    git merge upstream/master
    npm install
    npm run docbuild

(I hadn't run npm install in a long time)

And then `git status` to see what changed and needed to be commited.

Anyway, I did it again and the icons are loading now.
