### ISSUE TITLE
add tea shop Palais des Thés

### ISSUE THREAD

**Issue by Kazing** [osmlab/name-suggestion-index#3663]
Hello, a tea shop brand to add, according to their website they have more than 50 shops in France, Belgium, Norway...

**OSM tags** `shop=tea`
**brand** Palais des Thés 
**brand:wikidata** Q3225161
**brand:wikipedia** en:Le Palais des Thés
**country** fr, be, no, lu, ru

**Comment by bmillemathias-1a** [comment]
Hi @Kazing 

Are you able to create a pull request ? 
* create a fork
* edit the file brands/shop/tea.json
* commit 
* submit the change

Best.

**Comment by bmillemathias-1a** [comment]
There are shops in Israel and Georgia as well according their website

**Comment by Kazing** [comment]
Ok I will try to do this

**Comment by bmillemathias-1a** [comment]
> Ok I will try to do this

In case of question, don't hesitate to ask for help.

**Comment by Kazing** [comment]
See the PR, I added Israel and Georgia to the country list
