### ISSUE TITLE
Add french Pizza Paï

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3679]
`name="Pizza Paï"`
`amenity=restaurant` or `amenity=fast_food`
`cuisine=pizza`

25 objects in OSM: https://overpass-turbo.eu/s/Ssa
website: https://www.pizzapai.fr
wikidata: [Q3389501](https://www.wikidata.org/wiki/Q3389501)

**Comment by bhousel** [comment]
This happened in #3681
