### ISSUE TITLE
Add french convenience shop Proxi

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3680]
`name="Proxi"`
`shop=convenience` or ?? `shop=supermarket`

707 objects in OSM: https://overpass-turbo.eu/s/Syv
wikidata: Q3408522

**Comment by bmillemathias-1a** [comment]
Both are possible reading their website https://www.franchise-proximite.carrefour.com/nos-enseignes-proxi-concept

🇫🇷 
> 2 formats Proxi :
> des magasins de petit format organisés autour d’un point fort attractif comme les produis frais, une station-service, de la presse…
> Proxi Super des commerces alimentaires plus grands organisés autour des pôles alimentaires traditionnels comme la zone marché, le point chaud, la boucherie-charcuterie…

🇬🇧 
> 2 Proxi formats:
> small format stores organized around an attractive point such as fresh produce, a service station, the press, etc.
> Proxi Super larger food businesses organized around traditional food hubs such as the market area, the hot spot, the butcher's shop

**Comment by johanricher** [comment]
It's _Proxi_ not "Proxy", and the brand is already added: https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/convenience.json#L1438

**Comment by pyrog** [comment]
[Proxy](https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/convenience.json#L2050) seem a duplication of [Proxi](https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/convenience.json#L2036).

And Proxy Super should be added in [brands/shop/superkarket.json](https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/supermarket.json) with the same wikidata item.
Right ?

```json
    {
      "displayName": "Proxi Super",
      "locationSet": {"include": ["ch", "fr"]},
      "tags": {
        "brand": "Proxi",
        "brand:wikidata": "Q3408522",
        "name": "Proxi Super",
        "shop": "supermarket"
      }
    },

```

**Comment by johanricher** [comment]
"Proxi" and "Proxi Super" are effectively sharing the same Wikidata item: https://www.wikidata.org/wiki/Q3408522. Then "Proxi Super" should be added as a separate entry `convenience.json` as you described and "Proxy" should be removed.

**Comment by nuxper** [comment]
Done:
- Added Proxi Super in supermarket
- Added Proxy as a matchname for Proxi in convenience in order to avoid automatic creation of the Proxy entry due to massive wrong naming of those convenience in France
- Deleted the Proxy entry

Note @pyrog : we actually have a high number of incorrectly named "Proxy" convenience store in France (>50). I'll edit some.
