### ISSUE TITLE
Add french clothes Phildar

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3691]
`name=Phildar`
`shop=clothes`

Less than 62 objects in France : https://overpass-turbo.eu/s/SLM
website: https://www.phildar.fr/storelocator/
wikidata: [Q3378886](https://www.wikidata.org/wiki/Q3378886)

**Comment by bmillemathias** [comment]
are you sure about `shop=clothes` ?
Back in the time in the 80's Phildar was a mainly a knit shop, did it changed since then ?
Their website sells clothes but have still their knit section with templates, yarn.

**Comment by pyrog** [comment]
My mother practiced knitting 😉

[One shop in Canada](https://www.openstreetmap.org/node/6797579886) seem a knit shop (tagged as `shop=whool`).
According to their website, it seem that it's[ clothes shop since 2017](https://www.phildar.fr/cms/notre-histoire.html)

Tags founded accross the world with the previous overpass query : 
tag | count
--|--
shop=clothes | 30
shop=confectionery | 1
shop=craft | 2
shop=fabric | 18
shop=fashion | 1
shop=haberdashery | 1
shop=sewing | 4
shop=variety_store | 3
shop=wool | 3
shop=yes | 2

**Comment by ankita2210** [comment]
Shall I add a entry for french clothes Phildar and submit a PR ?

**Comment by bhousel** [comment]
> Shall I add a entry for french clothes Phildar and submit a PR ?

Yes please 👍
