### ISSUE TITLE
Add belgian electronics shops Krëfel

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3702]
`name= Krëfel`
`shop=electronics`

Currently 24 / ? shops in Belgium : https://overpass-turbo.eu/s/SOn
website: https://www.krefel.be
wikidata: [Q3200093](https://www.wikidata.org/wiki/Q3200093)

**Comment by Eric-Sparks** [comment]
I'm already seeing this in `electronics.json` file.

```
  },
  "shop/electronics|Krëfel": {
    "countryCodes": ["fr", "nl"],
    "tags": {
      "brand": "Krëfel",
      "brand:wikidata": "Q3200093",
      "brand:wikipedia": "fr:Krëfel",
      "name": "Krëfel",
      "shop": "electronics"
    }
```

**Comment by bhousel** [comment]
Thanks @Eric-Sparks , looks like this was done
