### ISSUE TITLE
Add country codes to some fast food brands

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#3703]
Please add country codes to following fast food brands with rather general names as nsi wrongly suggests those to be present Germany:

- Telepizza
- Snack Bar
- Pizza King
- Panda Express
- Chipotle
- China Garden
- China Wok

Thanks!

**Comment by tas50** [comment]
I don’t know about the others but Chipotle has a single location now with Germany and I’d expect that to increase in the future.

**Comment by kjonosm** [comment]
> Chipotle has a single location now with Germany

thanks for the update! so "de" can be added to the country codes...

**Comment by bhousel** [comment]
Gonna just close this, it sounds like it wasn't very thoroughly researched..
