### ISSUE TITLE
Add country codes to some restaurant brands

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#3705]
Please add country codes to following restaurant brands with rather general names as nsi wrongly suggests those to be present in Germany:

- Chili's
- PizzaExpress
- Wasabi

Thanks!

**Comment by bhousel** [comment]
Apparently there is indeed a [Chili's in Germany](https://www.google.com/maps/place/Chili's/@49.4448165,7.599528,15z/data=!4m8!1m2!2m1!1sLawn+Avenue+Bldg+2140+435+SVS+%2F+SVBME,+Unit+3240+Box+535,+APO+AE,+66877+Ramstein-Miesenbach,+Rhineland-Palatinate+Germany!3m4!1s0x47960b322396b00b:0xa9c836e079dfaed7!8m2!3d49.4458179!4d7.6067796)  🌶️
