### ISSUE TITLE
Remove cafes with generic names

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#3710]
Please remove/discard following cafes as they tend to be in the index just because of their generic name:

- Aroma (apparently there is an Argentinian chain called Aroma Café)
- Café de Paris
- Café de la Mairie
- Café de la Poste
- Cappuccino
- Dolce Vita

Thanks!

**Comment by bhousel** [comment]
Aroma and Dolce Vita are definitely real brands.  @kjonosm are you getting these lists from somewhere?  Local knowledge?

**Comment by ferdinand0101** [comment]
at least in Germany Dolce vita is a common non brand name for (italian) cafes

**Comment by bhousel** [comment]
Aroma and Dolce Vita are definitely real brands.  @kjonosm are you getting these lists from somewhere, or is it just guesses?

**Comment by kjonosm** [comment]
Just local knowledge (and some wiki/google search). I checked the amenity=cafe list on the nsi for "de" and the above entries strike me as non existing brands at least in Germany. I did that check because I came across some wrong suggestions when using the id validator. maybe there should be a higher threshold for id to suggest (obviously international) brands that don't have a country code
