### ISSUE TITLE
Remove entries with generic names

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#3712]
Please remove/discard following entries as they tend to be in the index just because of their generic name:

- 'amenity/dentist|Zahnarztpraxis' (generic German name for dentist practice)
- 'amenity/pharmacy|Einhorn-Apotheke'
- 'amenity/vending_machine|Schlauchomat'
- 'shop/hairdresser|Hair Studio'
- 'tourism/hotel|Hotel Belvedere' (maybe someone from Italy can confirm?)
- 'tourism/hotel|Hôtel de la Gare' (maybe someone from France can confirm?)

Thanks!

**Comment by sandygudie** [comment]
I think all the generic names above have been removed

**Comment by matkoniecz** [comment]
No, for example https://github.com/osmlab/name-suggestion-index/search?q=Hair+Studio&unscoped_q=Hair+Studio

**Comment by sandygudie** [comment]
Hi there, how about the last two?

**Comment by matkoniecz** [comment]
Hotel Belvedere researched and removed as nonbrand name

**Comment by bhousel** [comment]
I've done "Hotel de la Gare" - that should take care of all of them 👍
