### ISSUE TITLE
How to handle regional brands operating besides independent stores with the same name in the same country?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#3713]
I stumbled across two regional German bakery chain entries in the index that operate besides lots of independent bakeries with the same name spread across the country:

- 'shop/bakery|Bäckerei Schmidt' (70 stores)
- 'shop/bakery|Bäckerei Schneider' (134 stores)

In each case they account for about half of the current total number of bakeries with that name. Should the brand suggestion be removed or is there another way to differentiate between branded and independent stores?

**Comment by SilentSpike** [comment]
You can manually tag independent stores using `not:brand:wikidata`. This tag will suppress the brand tagging suggestions in iD and the `not:` prefix is an established concept for cases where it's beneficial to explicitly mark a tag as intentionally not present.

**Comment by kjonosm** [comment]
While I thinks it's a fair approach to manually add the `not:` prefix for exceptions I wonder if there is a better way to handle cases (as the above mentioned) to allow for a more differentiated approach where the number of non-branded entries exceed or almost exceed the number of branches of a branded chain. maybe id can offer to add the `not:brand:wikidata` tag directly within the validator. Similar to how crossing ways are handled and the id validator is offering to either add a bridge or a tunnel.
