### ISSUE TITLE
Add french fast-food Coeur de Blé

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3741]
`name=Coeur de Blé` or `name=Cœur de Blé`
`amenity=fast_food`
`cuisine=sandwich`

Could be tagged as `shop=bakery` or `amenity=restaurant`

Currently 12 / ? in France https://overpass-turbo.eu/s/T1K
website: http://restaurants.casino-restauration.fr
wikidata:

**Comment by BARICISSE** [comment]
is this still open ? I am available to work on it.
