### ISSUE TITLE
FR: Add Vapostore (e-cigarette)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3750]
Hello,

country code: FR
shop=e-cigarette
name=Vapostore
brand=Vapostore
brand:wikidata=Q91257968
network=Vapostore

**Comment by pyrog** [comment]
Does `network` key is useful ?

**Comment by gendy54** [comment]
It's a franchised business. To see if it's useful.

**Comment by pyrog** [comment]
@bhousel in https://github.com/osmlab/name-suggestion-index/issues/3756#issuecomment-617181638
> We don't set network keys now for pharmacies (or anything else yet)

**Comment by pyrog** [comment]
Existing tags are `shop=tobacco`, `shop=chemist`, `shop=yes`
Currently 32 / [98](https://www.vapostore.com/magasins-cigarette-electronique) in France: https://overpass-turbo.eu/s/Td9

**Comment by UKChris-osm** [comment]
Merged via #3834
