### ISSUE TITLE
Add Sephora (perfumery)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3751]
Hello,

"brand": "Sephora"
"brand:wikidata": "Q2408041"
"brand:wikipedia": "fr:Sephora (entreprise)"
"name": "Sephora"
"shop": "perfumery"

**Comment by bmillemathias-1a** [comment]
Hi @gendy54 

Sephora is already listed but as `shop:cosmetics`, so do you suggest to change the tag?

**Comment by gendy54** [comment]
I don't see any inconvenience.

**Comment by bhousel** [comment]
No let's please leave Sephora as `shop=cosmetics` how it is.  "cosmetics" includes a bunch of products like perfume, makeup, hair care, lotion, etc.

**Comment by gendy54** [comment]
It's fixed ;)
