### ISSUE TITLE
FR: Add Bastide (medical_supply)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3752]
Hello,

shop=medical_supply
name=Bastide Le Confort Médical
brand=Bastide Le Confort Médical
brand:wikidata=Q2887693
brand:wikipedia=fr:Bastide Le Confort Médical

**Comment by bmillemathias** [comment]
Indeed, it should be added.
I did not know the name was "Bastide Le Confort Médical".

**Comment by bmillemathias** [comment]
https://overpass-turbo.eu/s/T7e

**Comment by gendy54** [comment]
I thought too the name was only "Bastide" and that "Le Confort Médical" was a slogan.

**Comment by bhousel** [comment]
> I thought too the name was only "Bastide" and that "Le Confort Médical" was a slogan.

We can do
```js
"brand": // whatever is best
"name": "Bastide",
"official_name": "Bastide Le Confort Médical",
```

But I'd treat the `name` tag as close as possible to how people familiarly think of the brand and how they'd expect to see it rendered on maps.  This will never be perfect, but see https://github.com/osmlab/name-suggestion-index/issues/2236#issuecomment-451346930 for some thoughts on how we approach naming.

**Comment by gendy54** [comment]
Okay, your analysis suits me perfectly.
I had mapped a shop with name=Bastide, because Le Confort Médical seemed superfluous to me.

**Comment by pyrog** [comment]
https://entreprise.data.gouv.fr/etablissement/30563503900608
