### ISSUE TITLE
FR: Add GO Sport (sports)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3753]
Hello,

Country code: FR (only)
"brand": "GO Sport"
"brand:wikidata": "Q48746237"
"brand:wikipedia": "fr:GO_Sport"
"name": "GO Sport"
"shop": "sports"

**Comment by HussainArif12** [comment]
I've added a fix to this issue. Kindly check

**Comment by gendy54** [comment]
Why name and brand GO SPORT in uppercase?

**Comment by HussainArif12** [comment]
> Why name and brand GO SPORT in uppercase?

My apologies, it was my mistake. I've fixed this in the latest commit

**Comment by alpe88** [comment]
@HussainArif12 why not assign this to yourself?

**Comment by Adamant36** [comment]
> @HussainArif12 why not assign this to yourself?

I might be wrong since I've been a calibrator for a while, but I don't think non-collaborators can assign things.

**Comment by HussainArif12** [comment]
Hi, this issue has been resolved.

**Comment by Adamant36** [comment]
> Hi, this issue has been resolved.

So it has. Thanks for the heads up. Closed in #3760
