### ISSUE TITLE
FR: Add Au vieux campeur (sports)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3754]
Hello,

Country code: FR (only)
"brand": "Au vieux campeur"
"brand:wikidata": "Q2409646"
"brand:wikipedia": "fr:Au vieux campeur"
"name": "Au vieux campeur"
"shop": "sports"

**Comment by bmillemathias** [comment]
Looking at the website, I'd say it seems to be more an outdoor shop (hiking and mountain related activity) than a sport shop (they do sell sport gears though). What do you think ?

Best.

**Comment by pyrog** [comment]
>  it seems to be more an outdoor shop

Oui, je confirme (matos de spéléologie, montagne, escalade…) 😃

**Comment by gendy54** [comment]
In Paris, as there is one shop by sports theme, you can differentiate, but for the other shops in France, I don't have an opinion.

**Comment by pyrog** [comment]
Have a look to https://www.auvieuxcampeur.fr/boutiques/Paris  😉 

PS:I checked all shop, they mainly sells outdoor equipments.

**Comment by UKChris-osm** [comment]
Merged via #3833
