### ISSUE TITLE
Add a template "add brand"

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3755]
Hi, I saw that on another project.
It's possible to set templates to create issue.

See a possible example : https://github.com/osmlab/name-suggestion-index/issues/3741

**Comment by gendy54** [comment]
I was thinking more along the lines of a template like the one:
https://github.com/PanierAvide/Covid_enseignes

**Comment by bhousel** [comment]
Hmm, we tried this in #2960 but almost immediately people started opening issues with the template info [not actually filled in](https://github.com/osmlab/name-suggestion-index/issues/2968).

This has also been my experience using issue templates on other projects, that:
-  people don't follow the instructions in the template and it ends up making more work for the maintainer, and 
- the template restricts the kind of things that people will open issues for, so you lose out on useful signal about other kinds of issues

I guess we can try it again, but I'm generally :-1: on templates.

**Comment by gendy54** [comment]
Ok Bryan. I thought the template would make it easier for you to integrate, but if you'd rather there wasn't, I have no objection.

**Comment by pyrog** [comment]
Agree too. I have no experience with templates, it's a "new" feature for me 😉 

PS: templates : [PanierAvide/Covid_enseignes/issues/new/choose](https://github.com/PanierAvide/Covid_enseignes/issues/new/choose)

**Comment by bhousel** [comment]
Thanks for understanding @gendy54  - I don't have a ton of time to dedicate to this project so I'd rather keep things relatively simple and avoid the templates, and let people open up whatever issues they want to.
