### ISSUE TITLE
Integrate Yesss electrical shops

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#3759]
Hello,
Yessss Group has shops (more than 300 to date) in few European countries and in each the name differs a little bit
- fr: Yesss Électrique
- uk: Yesss Electrical
- de: Yesss Elektro
- it: Yesss Electrical

I don't know what is the best way to do that ? Should I create one entry per country, or could nsi provide a way to provide the local name to the consumer (name:fr, name:it, …) ?

```
"shop/electrical|Yesss": {
  "countryCodes": [
    "fr",
    "it",
    "mc",
    "nl",
    "uk"
  ],
  "tags": {
    "brand": "Yesss",
    "brand:wikidata": "Q91307483",
    "name": "Yesss",
    "shop": "electrical"
  }
```

**Comment by bhousel** [comment]
> Should I create one entry per country,

Unfortunately for now, I think this is the best way.. Because the name is a little different, I'd do one for each spelling of the name, each with a `countryCode` that says where the name is like that.
