### ISSUE TITLE
Add french pharmacy Anton et Willem

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3761]
`brand=Anton et Willem`
`brand:wikidata=`[Q91330267](https://www.wikidata.org/wiki/Q91330267)
`amenity=pharmacy`
`healthcare=pharmacy`
`dispensing=yes`

Curently 4 / [~40](https://www.anton-et-willem.fr/pharmacies) in France : https://overpass-turbo.eu/s/T8l
website: https://www.anton-et-willem.fr

See #3756 for issue with names

**Comment by chankailong** [comment]
I want to help this issue.

It is my first time to contribute to the Github.

After reading the instruction, should I follow the "Adding missing brands"?

Also, I don't get the meaning of #3756. So what the conclusion is for the "name"?

Thank you!

**Comment by Adamant36** [comment]
> I don't get the meaning of #3756. So what the conclusion is for the "name"?

Hi there. Unfortunately, I didn't follow along with the conversation in #3756. So I don't know what it's about. @pyrog would though, or another option would be to do a PR for something else. It doesn't really matter. Whatever you feel like doing 👍

**Comment by UKChris-osm** [comment]
Merged via #3832
