### ISSUE TITLE
Add european  curtains shop Heytens

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3763]
`name=Heytens`
`shop=curtain`

Currently, **46** objects in OSM : https://overpass-turbo.eu/s/SQm
country | website
--|--
 world | https://www.heytens.com
be | https://www.heytens.be
fr | https://www.heytens.fr
lu | https://www.heytens.lu
ch | https://www.heytens.ch

wikidata: [Q90565231](https://www.wikidata.org/wiki/Q90565231)

PS: I don't know if we use the same wikidata items for this brand for all the countries?
Or we should/must create one for each country

**Comment by Adamant36** [comment]
> PS: I don't know if we use the same wikidata items for this brand for all the countries?
Or we should/must create one for each country

If it goes by the same name everywhere, then just one entry is fine. We don't use websites anyway.
