### ISSUE TITLE
Add french beauty shop Carlance

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3764]
`brand=Carlance`
`brand:wikidata=`[Q91601625](https://www.wikidata.org/wiki/Q91601625)
`shop=beauty`

Currently 23 / 70 in France https://overpass-turbo.eu/s/Td3
website: http://www.carlance.fr

**Comment by MohamedBechir** [comment]
@pyrog i am new to contributing and i want to start with solving this issue can you guide me through it ? Thank you

**Comment by mds08011** [comment]
@MohamedBechir please review [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#convenience_store--add-missing-brands) and let us know if you have specific questions.

**Comment by RishabhBajaj97** [comment]
hey ! 
I have added this on my local repository could you please tell me how to generate pull request and submit this code
Thank you

**Comment by UKChris-osm** [comment]
Hi @RishabhBajaj97,

Thanks for your PR #3810, unfortunately there is a spelling mistake in the "name" value, where "Carl**e**nce" with an "**e**" is used in the middle, compared to the rest of the entry, which uses "Carl**a**nce", were an "**a**" is used in the middle.

**Comment by UKChris-osm** [comment]
Closed with merging of #3810, thank you @RishabhBajaj97
