### ISSUE TITLE
Add Sunbelt Rentals

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3765]
American equipment rental chain. Doesn't have a Wikidata or Wikipedia entry. 
https://www.sunbeltrentals.com/

**Comment by modaserMoj** [comment]
Can I add the brand without the Wikipedia and Wikidata tags? Also, this would go in amenities?

**Comment by Adamant36** [comment]
> Can I add the brand without the Wikipedia and Wikidata tags? Also, this would go in amenities?

You can add it to the index without the Wikipedia and Wikidata tags. They will just need to be added later for it to show up in iD Editor. At least the Wikidata tag will. I don't think there are any entries with just the Wikipedia tag. Otherwise, someone will likely come along and create a Wikidata entry for it eventually (I probably will myself if know one else does). 

On how to tag it, I think [shop=rental](https://wiki.openstreetmap.org/wiki/Tag:shop%3Drental) is the correct tag.

**Comment by modaserMoj** [comment]
> > Can I add the brand without the Wikipedia and Wikidata tags? Also, this would go in amenities?

> You can add it to the index without the Wikipedia and Wikidata tags. They will just need to be added later for it to show up in iD Editor. At least the Wikidata tag will. I don't think there are any entries with just the Wikipedia tag. Otherwise, someone will likely come along and create a Wikidata entry for it eventually (I probably will myself if know one else does).
> On how to tag it, I think [shop=rental](https://wiki.openstreetmap.org/wiki/Tag:shop%3Drental) is the correct tag.

Firstly, thank you for the informative reply and sorry to ask again but I am not sure how to fix this error.
I added the following code to shop/rental and run npm run build and got the following error.

  {
		 "displayName": "Sunbelt Rentals",
		 "locationSet": {"include": ["ca", "us"]},
		  "tags": {
		  "name": "Sunbelt Rentals",
		  "shop": "rental"
	    }
	  },

Error - Schema validation:
  ./brands/shop/rental.json:
  instance.brands/shop/rental[3].tags is not exactly one from [subschema 0],[subschema 1],[subschema 2]

**Comment by Adamant36** [comment]
Build seems to not be working on my end either based on the latest commit. Although it's gives a different error about locationset not being a function in some file. 

@bhousel

**Comment by bhousel** [comment]
Ah yeah, json schema validation errors are not very understandable.. It is complaining that there is no `brand` tag.

**Comment by modaserMoj** [comment]
> 
> 
> Ah yeah, json schema validation errors are not very understandable.. It is complaining that there is no `brand` tag.

Yup, thank you that was it.

**Comment by UKChris-osm** [comment]
I've created a Wikidata for Sunbelt Rentals in [ecf248c](https://github.com/osmlab/name-suggestion-index/commit/ecf248ce645d7a323078b3bac85071df17a6c33e)!
