### ISSUE TITLE
МИБС is not a brand for medical supply

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#3774]
Seem to be center for diagnostic radiology (PET, MRI…).
See [translation of their website](https://translate.google.com/translate?hl=fr&sl=ru&tl=en&u=https%3A%2F%2Fldc.ru%2F).

Don't know which tag to use: `healthcare=*` + `healthcare:speciality=diagnostic_radiology` ?

**Comment by Adamant36** [comment]
I know facility:radiology_labs is the moat used "radiology" tag by a long shot.

**Comment by bhousel** [comment]
ok I moved it to `amenity/clinic.json`:
```js
  "amenity/clinic|МИБС": {
    "locationSet": {"include": ["ru"]},
    "matchTags": ["shop/medical_supply"],
    "tags": {
      "amenity": "clinic",
      "brand": "МИБС",
      "healthcare": "clinic",
      "healthcare:speciality": "diagnostic_radiology",
      "name": "МИБС"
    }
  }
```
