### ISSUE TITLE
Resolving the Warning Issue

### ISSUE THREAD

**Issue by chankailong** [osmlab/name-suggestion-index#3775]
"amenity/payment_terminal|ПриватБанк" -> duplicates? -> "amenity/bank|ПриватБанк"
"amenity/payment_terminal|Сбербанк" -> duplicates? -> "amenity/bank|Сбербанк"

After reading the wiki, I suggested to add ""matchTags": ["amenity/payment_terminal"]" to "amenity/bank".

https://www.wikidata.org/wiki/Q1515015
https://www.wikidata.org/wiki/Q205012

If it's fine, I can help to fix

**Comment by bhousel** [comment]
For this one, I think people are mapping banks separate from payment terminals, so adding matchTags is probably not what we want to do.. 

I think we could treat the payment terminals like ATMs, but we aren’t really sure what to do with ATMs yet either (#2883 and #3056)

**Comment by matkoniecz** [comment]
I will close this one as it is OK to map payment terminals. Thanks for being interested, but this specific idea would have unexpected consequences.
