### ISSUE TITLE
Add Pharmacies Bolivia

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3776]
Bolivian pharmacy chain
Q81970584
http://www.farmaciasbolivia.com.bo/

**Comment by ferreiro-axel** [comment]
Hi! I just fork it to make this my first contribution but it seems like it has already been added in #3490

**Comment by Adamant36** [comment]
Wierd. Thanks for mentioning it. I did a search for it before opening the issue and nothing came up for some reason.
