### ISSUE TITLE
Car Park Operators as Names (Q-Park)

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#3799]
I just noticed a new addition to the NSI ([ee271f6](https://github.com/osmlab/name-suggestion-index/commit/ee271f6fd65041beb08f31dc69a0002f0acf666c)) which is for the car park operator **Q-Park**, which places the car park operator as the name of the car park.

However, I think many car parks have their own name (e.g [Cedars Car Park](https://www.openstreetmap.org/way/119564846)), and so wouldn't this particular entry be better marked up as an operator addition? For example:

"amenity/parking|Q-Park": {
"countryCodes": ["be", "de", "dk", "fr", "gb", "ie", "nl"],
"tags": {
"amenity": "parking",
"brand": "Q-Park",
"brand:wikidata": "Q1127798",
"brand:wikipedia": "en:Q-Park",
_"fee": "yes",_
**"operator": "Q-Park"**
}
}

... I'm also not sure if _fee_ should automatically be assumed to be yes, unless it can be guaranteed that all Q-Park operated  car parks are charged for?

**Comment by Adamant36** [comment]
> However, I think many car parks have their own name (e.g Cedars Car Park), and so wouldn't this particular entry be better marked up as an operator addition?

All the other parking entries have name tags.  Although I'm not 100% sure, I think it would need one to work. People can change it manually if need be anyway. 

> I'm also not sure if fee should automatically be assumed to be yes, unless it can be guaranteed that all Q-Park operated car parks are charged for?

I semi agree with that. Although, again all the other parking entries have fee=yes. So 🤷

**Comment by peternewman** [comment]
We don't need names now, so this can be fixed can't it?

**Comment by bhousel** [comment]
I moved the `amenity/parking.json` file from the 'brands' tree to the 'operators' tree, and removed the `name` tag for Q-Park.  If there are others that shouldn't have names, we can remove it from them too.
