### ISSUE TITLE
add insurance=health for some "Krankenkasse"-presets in germany

### ISSUE THREAD

**Issue by Lukas458** [osmlab/name-suggestion-index#3854]
In Germany, there are presets for "AOK", "DAK Gesundheit" and "Techniker Krankenkasse" which are common health-insurance brands here. The tag insurance=health (https://wiki.openstreetmap.org/wiki/Tag:insurance%3Dhealth) is used not so often, but specifies those insurance offices which are specialized (only) on health insurances. On the tagging-mailing list, people said it would be a good purpose to use an under-tag for this. So I think this tag might be added to the presets.

**Comment by bhousel** [comment]
Thanks for raising this, it's a good suggestion..

We currently have 74 entries under `office/insurance` (57 of which are complete with wikidata and social links). I think it would be great to eventually have all of them tagged with the `insurance=*` tag, and raise a warning if the sub tag is missing (similar to what we do now with tags like `cuisine` and `vending` etc).
