### ISSUE TITLE
Add Barmer Ersatzkasse

### ISSUE THREAD

**Issue by Bingo67** [osmlab/name-suggestion-index#3861]
the name of the brand is Barmer Ersatzkasse
it is a health insurance in Germany
category office/insurance
brand:wikipedia=de:Barmer Ersatzkasse
brand:wikidata=Q808361

**Comment by UKChris-osm** [comment]
Hi @Bingo67,

I've added "Barmer" via [60f8bcf](https://github.com/osmlab/name-suggestion-index/commit/60f8bcf6a33c1c7706d4fc1dcba69d2609e0ca0e), as the single word "Barmer" seems to me mostly used as the brand.

If you disagree let me know with more info if you can.

As a heads up, the Wikidata you suggested had some out of date information on it (web site, email, social media links) so if you're able to double check any future suggestions, that would be very helpful :)

**Comment by Bingo67** [comment]
Hi UKChris-osm,

thank you for the quick response. Barmer instead of Barmer Ersatzkasse is ok.
Next time i will edit wikidata if i have the missing information.
