### ISSUE TITLE
Bulk edit: proposed to change bank to ATM if it has ATM in the name

### ISSUE THREAD

**Issue by HubMiner** [osmlab/name-suggestion-index#3879]
If a bank has "ATM" in the name, it is most likely an ATM (but not always!)

Overpass query:
amenity=bank and name~/\bATM\b/i
http://overpass-turbo.eu/s/Ubm

**Comment by bhousel** [comment]
Thanks @HubMiner  - This is a good suggestion and I agree with it, but this project isn't about doing bulk edits.  We're just building a list of brands, and it's up to other projects to decide what to do with this list.  If you want to do a bulk edit, you should read the [OpenStreetMap Automated Edits code of conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct) and try to follow whatever guidelines are set there.

We don't yet have ATMs in our index, but we will probably add them eventually - more info on #2883.
