### ISSUE TITLE
Monoprix in France and Monoprix in Tunisia appears to be a different Monoprix

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#3883]
https://en.wikipedia.org/wiki/Monoprix
https://en.wikipedia.org/wiki/Monoprix_(Tunisia)
http://overpass-turbo.eu/s/UeU
https://github.com/osmlab/name-suggestion-index/blob/e08d46024350e492001c38f47f4a336e544a963d/brands/shop/supermarket.json#L3024

**Comment by ArenaL5** [comment]
The French Wikipedia has a disambiguation page: https://fr.wikipedia.org/wiki/Monoprix

Someone who actually speaks French may confirm this: apparently Monoprix (Tunisia) has splintered off Monoprix (France), but it's legally distinct, and has different investors.

[Currently they share logo](https://fr.wikipedia.org/wiki/Monoprix_(Tunisie)#Identit%C3%A9_visuelle) and name. Also, the website in wikidata doesn't work (http://www.snmvt.com/) but https://www.monoprix.tn/ does, and it's written in French.
