### ISSUE TITLE
Move Poundworld to dissolved list, replace with OneBelow

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3885]
https://github.com/osmlab/name-suggestion-index/blob/e76b8c1b165f746d1cf5813f8d4a509f3f7a9d53/brands/shop/variety_store.json#L363

Closed in 2018 https://en.wikipedia.org/wiki/Poundworld

According to that, some were converted to OneBelow shops and there's a dozen of them in OSM just now. https://en.wikipedia.org/wiki/OneBelow

name=OneBelow
brand:wikidata=Q65079443
brand:wikipedia=en:OneBelow

**Comment by UKChris-osm** [comment]
Hi @boothym, just to let you know that I added OneBelow via [6176fed](https://github.com/osmlab/name-suggestion-index/commit/6176feded719c172118a8c9bf62743dc67d82413) back on the 16th May, although it may take a little time to filter into the iD Editor.

I think Poundworld should automatically appear in the dissolved list once a Wikidata script is run and the dissolved tagged (which I've just added) is picked up.
