### ISSUE TITLE
Add Wren Kitchens [GB]

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3886]
brand/name=Wren Kitchens
shop=kitchen
brand:wikidata=Q8037744
brand:wikipedia=en:Wren Kitchens

**Comment by UKChris-osm** [comment]
You know, I could have sworn I already added Wren a while back, but thanks for the suggestion @boothym, added via [4a6bbe8](https://github.com/osmlab/name-suggestion-index/commit/4a6bbe80e6edba46a7742386e92d84f43cde23f4)
