### ISSUE TITLE
Add internet tags to Premier Inn

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#3905]
[Premier Inn](https://nsi.guide/index.html?k=tourism&v=hotel#Premier%20Inn) hotels have free wifi, would it be best to add the following to the template?
```
internet_access=wlan
internet_access:fee=customers
```

**Comment by matkoniecz** [comment]
Is it true for every single one?

**Comment by Cj-Malone** [comment]
[Yes](https://www.premierinn.com/gb/en/why/wifi.html)

They even say they use the same SSID, so that could be added as well.

```
internet_access:ssid=Premier Inn Free Wi-Fi
```

**Comment by bhousel** [comment]
Seems fine, as long as we are sure that it's true for every one. 👍
