### ISSUE TITLE
New tag for "Poivre Rouge" restaurants

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#3906]
Hi,
I republish a request I made on https://github.com/osmlab/name-suggestion-index/issues/887 because I don't know how to reopen that issue.

The "Poivre Rouge" restaurant is already existing cf. https://nsi.guide/index.html?k=amenity&v=restaurant#Poivre%20Rouge

I completed the wikidata page https://www.wikidata.org/wiki/Q7316076 with extra information.
I suggest to add the following tag:
`operator=Les Mousquetaires`

That's it!

**Comment by bhousel** [comment]
Thanks for reporting @overflorian  - we've gone back and forth a few times about whether to add `operator` tags for the name-suggestion-index entries.  Following https://github.com/osmlab/name-suggestion-index/issues/2816#issuecomment-505434193 we found that enough people were misusing the tag that it was easiest to just remove them for now.  

I'm going to close this for now, but we might change it later if we start adding `operator` tags again.

**Comment by overflorian** [comment]
OK, I read the comment, I understand why you guys took this decision and it sounds legitimate to me.
Good job by the way for this project that I discovered recently and that I will spend more time on during the following weeks. Regards
