### ISSUE TITLE
Add Strutt & Parker

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3907]
UK estate agent with 47 tagged in OSM.

  "office/estate_agent|Strutt & Parker": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "Strutt & Parker",
      "brand:wikidata": "Q7625458",
      "name": "Strutt & Parker",
      "office": "estate_agent"
    }
  },

**Comment by bhousel** [comment]
> @bhousel Can I work on this issue too ?

Sure, thanks!  On this project it's ok to just jump in - you don't need to ask permission 🙇

**Comment by g4rry420** [comment]
@bhousel I have completed this issue. Please let me know if I have made any mistakes #3915

**Comment by boothym** [comment]
@g4rry420 thanks for doing this, I'm looking through popular shop tags in the UK to find missing brands so I'll add some more later.
