### ISSUE TITLE
Add Richer Sounds

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3908]
"shop/hifi|Richer Sounds": {
    "tags": {
    "countryCodes": ["gb"],
      "brand": "Richer Sounds",
      "brand:wikidata": "Q7330409",
      "brand:wikipedia": "en:Richer Sounds",
      "name": "Richer Sounds",
      "shop": "hifi"
    }
  },

**Comment by bhousel** [comment]
Thanks @g4rry420 , go for it!
Check out the [contributing guidelines](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) for more details on what files to edit.

**Comment by g4rry420** [comment]
@bhousel  I have solved the issue. Please let me know if I have made any mistake in it. #3911
