### ISSUE TITLE
Supermarkets Charter are guessed incorrectly as 'Eroski' brand

### ISSUE THREAD

**Issue by numeropi** [osmlab/name-suggestion-index#3918]
Hi, i was checking the http://osmose.openstreetmap.fr/es/map/#item=3130&class=31301&zoom=8&lat=40.707&lon=-2.896&level=1%2C2%2C3&tags=&fixable=

and realized that for many small town supermarkets named "Charter" here, it is suggested as the "Eroski" brand
"brand": "Eroski"
"brand:wikidata": "Q1361349"
"brand:wikipedia": "en:Eroski"

but "Charter" actually it is a franchise of the "Consum" brand.
"brand": "Consum"
"brand:wikidata": "Q8350308"

https://www.consum.es/franquiciados
https://www.consum.es/wp-content/uploads/revslider/charter1/charter5.jpg

Thanks for fixing if it needs to.

**Comment by UKChris-osm** [comment]
Hi @numeropi,

I can see both "Eroski" and "Consum" in the NSI, and under "Eroski" is ""**matchNames": ["charter", "eroski center"],**", which means the NSI thinks Charter is the same as Eroski.

So, just to confirm with you, are you saying that "**Charter**" is a supermarket brand in its own right, with its own shops, and is owned by "Consum", and that it does not have any association with "Eroski"?

Does **Charter** have its own Wikipedia / Wikidata entries?

**Comment by UKChris-osm** [comment]
I have removed the matchNames for "_Charter_" in the "_Eroski_" entry via [6fbaf03](https://github.com/osmlab/name-suggestion-index/commit/6fbaf036d4ef38a3332457a4fc2ee374c3a01c21) and added a basic entry for "_Charter_" (with no Wikidata) in its own right [40fee65](https://github.com/osmlab/name-suggestion-index/commit/40fee65661080c9e85681ce6d3a835f62e67a2b1)

**Comment by UKChris-osm** [comment]
Added Wikidata for "Charter" via [34381e8](https://github.com/osmlab/name-suggestion-index/commit/34381e845714e9933d3e185c1b3609c1600a6557).

**Comment by UKChris-osm** [comment]
Do let me know if you think further changes might be required @numeropi, but for know I'll close this :)

**Comment by numeropi** [comment]
Here you can see that Eroski owned Consum untill 2004: https://www.consum.es/en/history , but then Consum got out from Eroski, and Charter is now the franchise of Consum.

Charter does not have his own wikipedia article, but Consum does, in spanish, where you can the reference to Charter: https://es.wikipedia.org/wiki/Consum
