### ISSUE TITLE
Add National Tyres and Autocare

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#3925]
"shop/car_repair|National Tyres and Autocare": {
    "countryCodes": ["gb"],
    "tags": {
      "brand": "National Tyres and Autocare",
      "brand:wikidata": "Q6979055",
      "brand:wikipedia": "en:National Tyres and Autocare",
      "name": "National Tyres and Autocare",
      "shop": "car_repair"
    }
  },

Not sure if you can also create a match for the shorter name "National Tyres"?

**Comment by UKChris-osm** [comment]
Another one which I thought was already in the index, thanks again @boothym :)
