### ISSUE TITLE
StadtRAD Hamburg [potentially out of scope]

### ISSUE THREAD

**Issue by camelCaseNick** [osmlab/name-suggestion-index#3930]
StadtRad Hamburg stations (`amenity=bicycle_rental`) are tagged with

    brand=StadtRAD Hamburg
    brand:wikidata=Q2326366
    brand:wikipedia=de:StadtRAD Hamburg

among others (notably `network:*` and `operator:*`) after a brief discussion in the local community. [[1]](https://lists.openstreetmap.de/pipermail/hamburg/2019-November/001316.html)

As the individual stations have names and those are chosen to be used for `name`, the current name matching won't work.

I thought, I'd open it for future considerations. (If this is and will continue to be out of scope and/or is not wanted, I can stop issuing such brands.)

p.s. stations not tagged this way use an old four-digit reference, and haven't been checked thereafter.

**Comment by bhousel** [comment]
Thanks @camelCaseNick  - Its definitely a good issue to keep in mind for future development, even though we can't easily support features with variable names or `operator`/`network` tags yet.

**Comment by bhousel** [comment]
Since this was opened we added support for 'operators' and added a tree for them, and StadtRAD Hamburg [is there now](https://nsi.guide/index.html?t=operators&k=amenity&v=bicycle_rental#stadtradhamburg-012211)!  🎉
