### ISSUE TITLE
Fix amenity/fuel|Applegreen

### ISSUE THREAD

**Issue by luisluigi639** [osmlab/name-suggestion-index#3931]
There is a need to add the country codes of the UK, US, Ireland.

Also, the addition of the Wikidata ID which is: Q7178908

Lastly add the Wikipedia link of en:Applegreen

**Comment by ArenaL5** [comment]
Thank for you helping. I remember solving the first issue you posted here hours ago.

May I interest you in making a pull request? You'd be able to fix things yourself, and we'd only have to approve your fixes. It would be quicker for you and for us.

The first step is using the Fork button in the upper-right corner, to create a copy of the project. After that, you can click the pencil icon at https://github.com/osmlab/name-suggestion-index/blob/master/brands/amenity/fuel.json to add your edit. GitHub's GUI is pretty intuitive.

Please write if you need help. Learning how to use [Git](https://git-scm.com/downloads) is very helpful on the long run, but not mandatory.

**Comment by luisluigi639** [comment]
I think I did the pull request. So far I have no questions.

**Comment by tas50** [comment]
Closing this out. Feel free to open it back up @ArenaL5 if there's more to do here.

**Comment by bhousel** [comment]
Thanks @luisluigi639 👍

**Comment by bhousel** [comment]
A cool GitHub tip for future PRs - you can include some text like "closes #3931" in your commit message or pull request, and GitHub will close the issue for us automatically when it merges. 💪

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by ArenaL5** [comment]
> Closing this out. Feel free to open it back up @ArenaL5 if there's more to do here.

I can't think of anything, you already merged it for me.

@luisluigi639, we'll keep giving tips in the future so your future PRs will become perfect. :slightly_smiling_face: This was good.
