### ISSUE TITLE
Add King Soopers Fuel Station

### ISSUE THREAD

**Issue by luisluigi639** [osmlab/name-suggestion-index#3932]
"amenity/fuel|King Soopers"
"countryCodes": ["us"]
"amenity": "fuel"
"brand": "King Soopers"
"brand:wikidata": "Q6412065"
"brand:wikipedia": "en:King Soopers"
"name": "King Soopers"
"official_name": "King Soopers Fuel Station"

This addition is for the grocery store that have a fuel station.

**Comment by tas50** [comment]
@luisluigi639 Can you open a PR to add this one?

**Comment by luisluigi639** [comment]
@tas50 I have opened a pull request for this issue.

**Comment by tas50** [comment]
I missed that. Thanks for the PR
