### ISSUE TITLE
NPM Run Build location-conflation error

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#3940]
After I pulled the few updates that added support for the location-conflation thing I'm now getting an error that the module can't be found. Can someone check and see they are getting the same error on their side when running the build script so I know it's not something with my setup? 
@bhousel 

![Annotation 2020-06-07 214937](https://user-images.githubusercontent.com/30259065/83993758-3cea2880-a909-11ea-8d8e-f9d657dba982.png)

**Comment by bhousel** [comment]
You need to `npm install` again to get it ..

**Comment by Adamant36** [comment]
> You need to npm install again to get it ..

Thanks. That fixed it.
