### ISSUE TITLE
FR: Add Cinéville (french cinema chain)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3950]
Hello,

Country code: FR (only)
"amenity": "cinema"
"brand": "Cinéville"
"brand:wikidata": "Q2973271"
"brand:wikipedia": "fr:Cinéville"
"name": "Cinéville"

**Comment by aayush-vish** [comment]
Hey I want to contribute in this project.

**Comment by JackRosenblatt1** [comment]
Made a pull request! #3991
