### ISSUE TITLE
FR: Add Majestic (french cinema chain)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#3951]
Hello,

Country code: FR (only)
"amenity": "cinema"
"brand": "Groupe Majestic Cinemas"
"brand:wikidata": "Q19945144"
"brand:wikipedia": "fr:Groupe Majestic Cinemas"
_"name": "Majestic"_

For name tag, there are different names on the wikipedia page so I don't know if it's relevant.
Furthermore some cinemas have this name but are not part of the group

**Comment by BillNas** [comment]
On it!
