### ISSUE TITLE
FR : Add Utopia (french cinema chain)

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#3959]
Hello, could you please add:

Country code: FR (only)
"amenity": "cinema"
"brand": "Utopia"
"brand:wikidata": "Q3552766"
"brand:wikipedia": "fr:Utopia (cinéma)"

**Comment by matthenschke** [comment]
I'll make a pull request asap as this is my first ever pull request on open source.

**Comment by matthenschke** [comment]
Just created a pull request https://github.com/osmlab/name-suggestion-index/pull/3973
