### ISSUE TITLE
Research needed for: amenity/cafe|Пельменная

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#397]
#### :thinking: We need help deciding what to do with "amenity/cafe|Пельменная"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/cafe|Пельменная` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/cafe|Пельменная`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/cafe|Пельменная`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by tohaklim** [comment]
Generic name, to be removed. Possibly a cuisine preset instead?

**Comment by matkoniecz** [comment]
In case that you are interested in making pull requests:

https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md has useful documentation

For that case https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#hocho--remove-generic-names is especially useful

Unclear or misleading instructions CONTRIBUTING.md should be fixed - please report them ( https://github.com/osmlab/name-suggestion-index/issues/new ) if you spotted something unclear!

**Comment by Adamant36** [comment]
@matkoniecz, you could have added the generic name label to it ;)

**Comment by matkoniecz** [comment]
\* visits https://github.com/osmlab/name-suggestion-index/labels to see label list \*

**Comment by matkoniecz** [comment]
If preset in iD would be useful and there is no issue requesting it - probably https://github.com/openstreetmap/iD/issues/new is the way to go,

Though maybe adding synonym would be enough - see https://github.com/openstreetmap/iD/blob/master/CONTRIBUTING.md#translating

**Comment by matkoniecz** [comment]
This one is now fixed.
