### ISSUE TITLE
B&M UK

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#3979]
I don't know how actionable this yet, more to discus the different B&M store types. In B&M language they have B&M Store, B&M Home Store, B&M Home Store with Garden Centre and B&M Express.

## B&M Store
Seems to operate with 2 fascia.

Just says "b&m" [example](https://www.bmstores.co.uk/stores/isle-of-wight-107).
Currently in [nsi](https://nsi.guide/index.html?k=shop&v=variety_store#B&M) but missing brand tags.

Fascia "b&m bargains" [example](https://www.bmstores.co.uk/stores/north-shields-beacon-shopping-centre-169).
Currently in [nsi](https://nsi.guide/index.html?k=shop&v=variety_store#B&M%20Bargains).

## B&M Home Store
Fascia says "b&m home store" [example](https://www.bmstores.co.uk/stores/plymouth-transit-way-603).
Not in nsi.
Probably variety_store.

## B&M Home Store with Garden Centre
Fascia says "b&m home store & Garden Centre" [example](https://www.bmstores.co.uk/stores/portsmouth-ocean-retail-park-665).
Not in nsi.
Probably variety_store.

## B&M Express
Fascia says "b&m express" [example](https://heronfoods.com/storelocator/store-details/ebbw-vale)
Not in nsi.
B&M bought Heron Foods, a few Heron Foods stores + some new ones have been converted to "B&M Express". Still operated by Heron Foods, so still frozen_food? convenience? But entirely branded as B&M.

**Comment by UKChris-osm** [comment]
I've added "_B&M Express_" as a convenience store for now.

I'm thinking every other type of B&M would be a variety_store.

**Comment by Cj-Malone** [comment]
Is the `brand:wikidata` global, for the entire brand, or per store type? I noticed Tesco recently changed to per store type.

**Comment by UKChris-osm** [comment]
At the moment I've used the same Wikidata for "_B&M Express_" just to get it into the NSI. It could have its own Wikidata, but as it isn't a huge brand I'm not so sure it's necessary as it's in. a different category than "_shop/variety_store_".

For the other type's of store though, which all could fall into the "_shop/variety_store_", unique Wikidata's might be necessary.

**Comment by rjw62** [comment]
FYI, there's now a specific Wikidata entry for B&M Express: https://www.wikidata.org/wiki/Q99640578 , so the NSI entry could be amended to use that.

**Comment by bhousel** [comment]
> FYI, there's now a specific Wikidata entry for B&M Express: https://www.wikidata.org/wiki/Q99640578 , so the NSI entry could be amended to use that.

ok I switched the qid in 12794c7d - that wikidata page looks a bit empty, so it would be great for you to add some more info to it so that the Wikidata community doesn't remove the page.
