### ISSUE TITLE
Bradesco and Banco Bradesco are the same thing

### ISSUE THREAD

**Issue by picsi** [osmlab/name-suggestion-index#40]
Currently if you type "Bradesco" on iD, you get suggestions for Banco Bradesco and Bradesco. These are all the same and need to be merged.

**Comment by matkoniecz** [comment]
Which value is preferable?

**Comment by ftrebien** [comment]
Currently the [bank's logo](https://banco.bradesco/html/classic/index.shtm) at its agencies fronts does not include the word "Banco", and in OSM we prefer the form that is [visible from the ground](https://wiki.openstreetmap.org/wiki/Good_practice#Map_what.27s_on_the_ground). This can be reasonably confirmed by searching "agência banco bradesco" in Google Images. "Banco Bradesco" could be added to other name tags such as alt_name.
