### ISSUE TITLE
FR : Add Megarama (french cinema chain)

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#4006]
Hello, could you please add:

Country code: FR (only)
"amenity": "cinema"
"brand": "Megarama"
"brand:wikidata": "Q96707027"

**Comment by Thusal06** [comment]
I did it.

**Comment by overflorian** [comment]
Thanks. Could you please tell me when it will be live in name-suggestion-index ?

**Comment by Thusal06** [comment]
Uh... I just made the changes and pull request.

**Comment by Thusal06** [comment]
> Thanks. Could you please tell me when it will be live in name-suggestion-index ?

Sorry, I can't understand.

**Comment by overflorian** [comment]
Thanks again. I wonder when will "Megarama" return a result in the search box of https://nsi.guide ? That's just for my information, thanks.

**Comment by bhousel** [comment]
> Thanks again. I wonder when will "Megarama" return a result in the search box of https://nsi.guide ? That's just for my information, thanks.

This will appear on https://nsi.guide once we accept the pull request, then run `npm run dist`, and push a commit with the updated data files.

**Comment by overflorian** [comment]
OK thanks
