### ISSUE TITLE
Research needed for: amenity/cafe|Шашлычная

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#402]
#### :thinking: We need help deciding what to do with "amenity/cafe|Шашлычная"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/cafe|Шашлычная` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/cafe|Шашлычная`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/cafe|Шашлычная`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
Google translates it as "barbecue" - https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%D0%A8%D0%B0%D1%88%D0%BB%D1%8B%D1%87%D0%BD%D0%B0%D1%8F

@tohaklim Can you judge is it generic name (restaurants specializing in grilled products mistagged as cafes?) or a brand name?

**Comment by tohaklim** [comment]
Same as with another one of those, a cuisine preset would be better here, it's certainly a generic name and not a brand
