### ISSUE TITLE
Is "UGC" France only or does it also operate in Belgium?

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#4020]
Hello, could you please add:
"amenity": "cinema"
"brand": "UGC"
"brand:wikidata": "Q1643241"
"brand:wikipedia": "fr:Union générale cinématographique"
"brand:website": "https://www.ugc.fr"

**Comment by bhousel** [comment]
Thanks!  
but it looks like this cinema is already in our index:  https://nsi.guide/index.html?k=amenity&v=cinema#UGC

**Comment by overflorian** [comment]
Oops, sorry about that. I looked in the issues and couldn't find UGC but I did not look on the website.

**Comment by bhousel** [comment]
Probably worth mentioning that I tried running the overpass query for UGC  https://overpass-turbo.eu/s/VVf 
It's weird that:
- there aren't any of these mapped in France
- there are a handful of them mapped in Belgium
- the Antwerp one has this Wikidata: https://www.wikidata.org/wiki/Q37936340
- that Wikidata seems to be just for that single theater in Antwerp
- but Belgian UGC seems to also be branded the same as the French UGC

So I dunno `¯\_(ツ)_/¯`
It sounds to me like we should: update our index to have it in both France and Belgium, and also update Wikidata and Wikipedia to clear up where UGC actually operates, and maybe remove that Antwerp entry as not notable, and maybe retag some of the data in OSM.  I'll reopen this issue so we don't forget about it.

**Comment by overflorian** [comment]
In France we are currently in the process of Q/A for all the cinemas of the country cf. https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:CNC#Cin.C3.A9mas_par_op.C3.A9rateur as much in OSM than in Wikidata.

Currently 36 UGCs over the 47 listed by the brand https://www.ugc.fr/cinemas.html are tagged brand=UGC cf. https://overpass-turbo.eu/s/VVk
I will complete this task in the following days.

The name is never "UGC" but "UGC Ciné Cité [NAME OF THE TOWN]" so that's why you haven't found anything with your overpass query.
I guess some work should be done by the Begian community too.

Is that clear to you? Should we close this issue?

**Comment by bhousel** [comment]
> Is that clear to you? Should we close this issue?

Thanks! That makes a lot of sense. We can close it.
We've done some brainstorming on #3990 and #3770 about the Overpass queries, so maybe we can improve this to make them less confusing.

**Comment by overflorian** [comment]
OK, I'm sure the result should be great.
Sorry I can't help: I'm real bad with overpass queries. Every time I seek for help!

Do you guys plan to add a proper form to add new brands instead of creating github issues? I can open a new issue for that it you think it makes sense.

**Comment by bhousel** [comment]
> Do you guys plan to add a proper form to add new brands instead of creating github issues? I can open a new issue for that it you think it makes sense.

That's ok, adding an intake process is mentioned in #3990 
I kind of like the GitHub issues though.

**Comment by overflorian** [comment]
OK, thanks. Will keep contributing to your great tool (and push to use it the future contribution tools I'll be developping).
