### ISSUE TITLE
fast food "immergrün" has a typo

### ISSUE THREAD

**Issue by Prince-Kassad** [osmlab/name-suggestion-index#4027]
The name for the German fast food chain "immergrün" is given as "immergün":

https://github.com/osmlab/name-suggestion-index/blob/608f3958281a6ea7761040582e70e832e01a08b9/brands/amenity/fast_food.json#L3598

This is an obvious typo that should be fixed.

**Comment by Arthur092** [comment]
I can take this issue

**Comment by Arthur092** [comment]
PR submitted #4029

**Comment by bhousel** [comment]
Thanks @Arthur092 👍
