### ISSUE TITLE
shop/convenience|Копеечка and shop/convenience|Доброном

### ISSUE THREAD

**Issue by krasnyekrylja** [osmlab/name-suggestion-index#4031]
1. shop/convenience|Копеечка
1.1 OSM tag "brand:wikidata": "Q68207105" needs to be replaced by "brand:wikidata": "Q97346327";
1.2 link https://www.wikidata.org/wiki/Q68207105 needs to be replaced by https://www.wikidata.org/wiki/Q97346327;
1.3 Wikidata Name/Description "Kopeechka" should be added;
1.4 official website link https://www.dobronom.by/ should be added;
1.5 social link https://www.instagram.com/dobronom.by/ should be added.
1.6 logo should be added.

2. shop/convenience|Доброном
2.1 OSM tag "brand:wikidata": "Q2565040" needs to be replaced by "brand:wikidata": "Q97312362";
2.2 OSM tag "brand:wikipedia": "be:Eurotorg" needs to be deleted or replaced;
2.3 Wikidata Name/Description "Evroopt" needs to be replaced by "Dobronom";
2.4 link https://www.wikidata.org/wiki/Q2565040 needs to be replaced by https://www.wikidata.org/wiki/Q97312362;
2.5 official website link https://evroopt.by/ needs to be replaced by https://www.dobronom.by/;
2.6 social links needs to be replaced by https://www.instagram.com/dobronom.by/;
2.7 logo needs to be replaced.

Thanks.

**Comment by bhousel** [comment]
Thank you for the detailed report @krasnyekrylja and welcome to GitHub 👋

**Comment by d4i** [comment]
I’m not sure where I can find [.](https://www.wikidata.org/wiki/Q68207105) . I checked the help docs and didn’t find any mentions.

**Comment by d4i** [comment]
I’m not sure where I can find [https://www.wikidata.org/wiki/Q68207105](https://www.wikidata.org/wiki/Q68207105) . I checked the help docs and didn’t find any mentions.

**Comment by krasnyekrylja** [comment]
![1](https://user-images.githubusercontent.com/68320304/88635740-b78d2400-d0c0-11ea-82ce-30446b2c48d5.PNG)

I see incorrect data and links, so I opened the question as indicated in the header. Maybe I don't understand something.
