### ISSUE TITLE
Is name required?

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#4034]
Hello,

Harvester (amenity/restaurant|Harvester) is currently listed in NSI, however each instance should have a different name tag in OSM. The [website](https://www.harvester.co.uk/restaurants) demonstrates this.

Is it possible to remove `"name": "Harvester"` from NSI, or is that needed else where in this project?

**Comment by bhousel** [comment]
Yes #3009 has some background but for now a `name` is required.  If it's causing problems, we could just remove Harvester from the index for now - let me know if you want this and I'll remove it.

At some point we want to relax this requirement, it's on my list of things to consider for #3995

**Comment by Cj-Malone** [comment]
I've not witnessed any data being lost due to it, so I wouldn't remove it just yet.

Is there anything I can help with? I'm not a node developer, but I do have a basic understanding of js.

**Comment by bhousel** [comment]
Name isn't required anymore, so I removed the `name` tag from Harvester in f0b72129
