### ISSUE TITLE
Storage rental brands

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#4035]
Some shop=storage_rental brands in the UK. 

"shop": "storage_rental"
"countryCodes": ["gb"],

"brand": "Big Yellow Self Storage"
"brand:wikidata": "Q4906703"
"brand:wikipedia": "en:Big Yellow Group"
"name": "Big Yellow Self Storage"

"brand": "Safestore Self Storage"
"brand:wikidata": "Q20713915"
"brand:wikipedia": "en:Safestore"
"name": "Safestore Self Storage"

"brand": "Lok'nStore"
"brand:wikidata": "Q6668484"
"brand:wikipedia": "en:Lok'nStore"
"name": "Lok'nStore"

(don't know whether this should have Self Storage in the name as well)

Also, a "UK Storage Company" brand was added earlier in the year, bit surprised to only find one instance of it in OSM! https://github.com/osmlab/name-suggestion-index/commit/c6e96516d638e9d1e35765ef3843224e96f8383d

**Comment by UKChris-osm** [comment]
When you say surprised about UK Storage Company, was that because I have added in incorrectly?

**Comment by UKChris-osm** [comment]
Added the suggested brands via [012da7d](https://github.com/osmlab/name-suggestion-index/commit/012da7d9af96e663563109a17d0faf5af08e38dc)

**Comment by boothym** [comment]
No it's added correctly, but normally what happens is popular brands already in OSM get added to the NSI, rather than them being added pre-emptively. I didn't check out their website out before but I see now there's a decent number so a good idea to have them in here.

Thanks for fixing this issue.

**Comment by UKChris-osm** [comment]
Ah I see, yes it was a case of I saw on their web site that they had a few sites across the UK and so decided to add it early on (and have since added a few around Somerset). There is one local to me and when I tried adding it I noticed it wasn't in the NSI - it's actually how a lot of my entries are found, by locally adding any business and seeing they aren't currently in the index.
