### ISSUE TITLE
Add Bedmart

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4036]
Zippy's is a fast food/restaurant chain. Wikipedia page here: 
https://en.wikipedia.org/wiki/Zippy%27s

Aloha Island Mart is a convenience store for Aloha Petroleum. Wikipedia page here: https://en.wikipedia.org/wiki/Aloha_Petroleum

Costco Food Court is a food court for Costco. Wikipedia page here: https://en.wikipedia.org/wiki/Costco#Food_service

Costco Optician is a optician for Costco. Wikipedia page here:
https://en.wikipedia.org/wiki/Costco#Costco_Optical

Times Supermarket is a supermarket chain. Wikipedia page here:
https://en.wikipedia.org/wiki/Times_Supermarkets

Homeworld is a furniture store chain. Wikipedia page not available. 

Slumberworld is a mattress store chain. Wikipedia page not available. 

Hele is a gas station chain. Wikipedia page not available.

Down to Earth is a health food store chain. Wikipedia page not available.

Bedmart is a furniture store chain. Wikipedia page not available.

**Comment by mds08011** [comment]
Times Supermarket added here: https://github.com/osmlab/name-suggestion-index/commit/ed6abfc0f9ff08bce1d7bf2ba1f4ce3afb5be185

**Comment by Identitaet** [comment]
Zippy's now has all the things needed for NSI in wikidata

**Comment by VJ1224** [comment]
TODO:

- [ ] Zippy's is a fast food/restaurant chain. Wikipedia page here:
https://en.wikipedia.org/wiki/Zippy%27s

- [ ] Aloha Island Mart is a convenience store for Aloha Petroleum. Wikipedia page here: https://en.wikipedia.org/wiki/Aloha_Petroleum

- [ ] Costco Food Court is a food court for Costco. Wikipedia page here: https://en.wikipedia.org/wiki/Costco#Food_service

- [ ] Costco Optician is a optician for Costco. Wikipedia page here:
https://en.wikipedia.org/wiki/Costco#Costco_Optical

- [ ] Times Supermarket is a supermarket chain. Wikipedia page here:
https://en.wikipedia.org/wiki/Times_Supermarkets

- [ ] Homeworld is a furniture store chain. Wikipedia page not available.

- [ ] Slumberworld is a mattress store chain. Wikipedia page not available.

- [ ] Hele is a gas station chain. Wikipedia page not available.

- [ ] Down to Earth is a health food store chain. Wikipedia page not available.

- [ ] Bedmart is a furniture store chain. Wikipedia page not available.

**Comment by Adamant36** [comment]
> Slumberworld is a mattress store chain. Wikipedia page not available.

They only have 8 locations. Which might be under Wikidata's notability guidelines. If not though, it would be fairly easy to add their brand information to OSM without them having an entry in the NSI. 

> Hele is a gas station chain. Wikipedia page not available.

I created Q99196505

**Comment by modaserMoj** [comment]
I made a pull request for Aloha Island Mart #4539

**Comment by amous4822** [comment]
[Par Pacific Holdings](https://en.wikipedia.org/wiki/Par_Pacific_Holdings) is a oil production company and it distributes to retail locations under the name Hele. Should I assign Par pacific's wikipedia/wikidata to Hele ?

**Comment by bhousel** [comment]
> Should I assign Par pacific's wikipedia/wikidata to Hele ?

No, if Hele has its own brand identity, it should have it's own wikipedia/wikidata page.  It would be weird to display a Par Pacific logo on the map for a Hele fueling station.

**Comment by TheAdventurer64** [comment]
Hele has been added: https://m.wikidata.org/wiki/Q99196505

**Comment by TheAdventurer64** [comment]
Down to Earth has been added: https://m.wikidata.org/wiki/Q104606414

**Comment by TheAdventurer64** [comment]
HomeWorld has been added: https://m.wikidata.org/wiki/Q104606443

**Comment by TheAdventurer64** [comment]
SlumberWorld has been added: https://m.wikidata.org/wiki/Q104606462

**Comment by TheAdventurer64** [comment]
BedMart has been added: https://m.wikidata.org/wiki/Q104606481

**Comment by Adamant36** [comment]
You could have linked to them in a single comment 😉 Anyway, you should add statements and whatnot to them. Otherwise, if there is just a name and description they will just get deleted and we can't use them without other stuff anyway.

**Comment by bryceco** [comment]
Please remember that there is a cost associated with adding things to NSI. If there are only a dozen instances of something and they're all close to each other then it's easy for the local community to ensure they're complete and consistent with each other. But every such entry in NSI requires someone's time to maintain it, and also increases the overall size of the database which bloats apps that use it, increases startup time for apps, and degrades app performance. IMO it's not worth adding things if the number of instances is < 50 or so.

**Comment by Adamant36** [comment]
> IMO it's not worth adding things if the number of instances is < 50 or so

The Wikidata entry for SlumberWorld will likely be deleted for being under their notability threshold anyway, if not the other ones also. I don't think it's worth adding entries to NSI that we won't meet Wikidata's standard and just get deleted. Since we depend on them for entries to work. Us adding to many 3 or 4 store "brands" to Wikidata might come off as spamming or whatever to them also. Which wouldn't be good.

**Comment by TheAdventurer64** [comment]
Since all of the wikidata links have been added, needs-wikidata can be removed.

**Comment by Adamant36** [comment]
So which ones still need to be added that actually meet the threshold?

**Comment by TheAdventurer64** [comment]
@UKChris-osm

**Comment by UKChris-osm** [comment]
[Costco Optical](https://nsi.guide/index.html?t=brands&k=shop&v=optician#costcooptical-5b6831) appears to already exist in the index, or have I missed something?

**Comment by Adamant36** [comment]
> Costco Optical appears to already exist in the index, or have I missed something?

I guess it does. It didn't show up for some reason I looked for it before. Maybe someone added it in the meantime. Either way, I'll strike it from the list.

**Comment by UKChris-osm** [comment]
I've just added "Hele" also :)

**Comment by Adamant36** [comment]
Thanks. I think the reason Costco didn't show up was because the original message said "Costco Optician" and the entry is for "Costco Optical." It seems as though they go by different names depending on the location. So that might be something to look into for a match name or something.

> Bedmart's Wikidata seems to have been deleted.

To bad, but not surprising. Someone can do un-deletion request, but it's questionably warranted. Not to say I told you so, but it probably it would not have been deleted if @TheAdventurer64 or someone else had of added details to it originally like I requested.

**Comment by UKChris-osm** [comment]
I've added "_Bedmart_" without the wikidata for now, so at least it's in the index. I don't know how to go about requesting an undelete, is it an easy process?

**Comment by Adamant36** [comment]
@matkoniecz has done a few undeletion requests. So he's probably the person to ask. On Costco, just leaving out the name field altogether  might be a good idea. Although likely there should be research about it first.

**Comment by matkoniecz** [comment]
Beware: info below is from 2019 and may be outdated.

1) BTW it would be useful to verify that we have no entries at risk of deletion before asking to look into it (to avoid triggering more deletions) - see https://github.com/osmlab/name-suggestion-index/pull/2605

2) See https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard/Archive/2019/04#Please_undelete_this_entries_about_brands

3) new requests may be created at https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard - I recommend commenting with user account, fixing at least some entries (if there are known entries that require fixes) and linking old discussions

**Comment by arch0345** [comment]
Looks like everything has been added. I'll close this issue
