### ISSUE TITLE
Dave and Busters and Chuck E. Cheese should be tagged as an amusement arcade

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4038]

**Comment by bhousel** [comment]
Thanks @TheAdventurer64  - it looks like these brand entries already are set up with the correct tags:

https://github.com/osmlab/name-suggestion-index/blob/f971b8185a8a73c181baaa8d64326c4ea960e43a/brands/amenity/restaurant.json#L746-L758

https://github.com/osmlab/name-suggestion-index/blob/f971b8185a8a73c181baaa8d64326c4ea960e43a/brands/amenity/restaurant.json#L571-L584
