### ISSUE TITLE
Search Wikipedia - nsi.guide

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4046]
Is the link to "_Search Wikipedia_" on the [nsi.guide](https://nsi.guide) supposed to be linking to a Google search? Or was the intention to link to a Wikipedia search directly?

**Comment by bhousel** [comment]
> Is the link to "_Search Wikipedia_" on the [nsi.guide](https://nsi.guide) supposed to be linking to a Google search? Or was the intention to link to a Wikipedia search directly?

I couldn't find a way to search all the multilingual wikipedias through their site, so I just the lazy thing and made it a google site search.

**Comment by bhousel** [comment]
I'm going to close this for now.. I did some more research and it doesn't look like there is a great way to search across all wikipedia languages.  But we can definitely change it later if it turns out there is a good way to do it.
