### ISSUE TITLE
Interstate Batteries

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#4058]
[Interstate Batteries](https://en.wikipedia.org/wiki/Interstate_Batteries) is an American chain of (automotive) battery stores with hundreds of locations.

https://www.wikidata.org/wiki/Q12060773

**Comment by UKChris-osm** [comment]
Would **"shop": "car_parts"** or **"shop": "electrical"** be the best way to categorise Interstate Batteries? They seem to deal in many type's of battery item (such as phones and laptop batteries) based on the web site.

**Comment by VJ1224** [comment]
If this is still open, i would like to take it up
