### ISSUE TITLE
Pearl in Europe is called "Pearl Opticiens" unlike "Pearl Vision" in the US/CA

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/name-suggestion-index#4064]
https://nsi.guide/index.html?k=shop&v=optician#Pearle%20Vision

https://nl.wikipedia.org/wiki/Pearle

And it has a different logo as well https://www.pearle.nl/static/img/pnl-vert-600.png

**Comment by bhousel** [comment]
I added this, but I can't have them display separate logos since they both share the same wikidata qid.

**Comment by tas50** [comment]
Yeah we had it the other way around for a while which was messing up all the brands in the US and then we swung in the other way and just broke Europe. Looks like we have it everywhere now!

**Comment by thibaultmol** [comment]
So is the solution then to have them as separate wikidata entries? (seeing as they are kind of different divisions I guess)

**Comment by bhousel** [comment]
> So is the solution then to have them as separate wikidata entries? (seeing as they are kind of different divisions I guess)

If they are really that different, then they should probably be two separate Wikidata pages, along with two separate Wikipedia pages explaining why they are different and how they are related.  It might be like Aldi North and Aldi South where there is some shared history but they do their own thing now?
