### ISSUE TITLE
Add UK fitness centres

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#4079]
I've had a look at the most popular UK fitness centre / gym brands in OSM and found a few which could be added.

All of these should be {"include":["gb"]}

"brand": "Bannatyne's"
"brand:wikidata": "Q24993691"
"brand:wikipedia": "en:Bannatyne's"
"leisure": "fitness_centre"
"name": "Bannatyne's Health Club"

Should brand be equal to name?

"brand": "David Lloyd Leisure"
"brand:wikidata": "Q7068711"
"brand:wikipedia": "en:David Lloyd Leisure"
???
"name": "David Lloyd"

This is tagged 4:1 in favour of sports_centre (though I've seen some duplicate tagging). Unsure whether it should be sports_centre the only real difference to others is the prevalence of racquet sports at their centres.

Also in countries: es, de, ie, be, it, nl

"brand": "Nuffield Health"
"brand:wikidata": "Q7068711"
"brand:wikipedia": "en:Nuffield Health"
"leisure": "fitness_centre"
"name": "Nuffield Health"

Their signs seem to display "Fitness & Wellbeing" below the name, not sure if it should be added or not (maybe official_name?).

"brand": "Total Fitness"
"brand:wikidata": "Q7828019"
"brand:wikipedia": "en:Total Fitness"
"leisure": "fitness_centre"
"name": "Total Fitness"

**Comment by UKChris-osm** [comment]
Have "Bannatyne's Health Club" updated their branding to remove the 's and are simply "Bannatyne", as in "Bannatyne Health Club"?

I think name and brand do need to match, so we couldn't just have "brand":"Bannatyne" with "name":"Bannatyne Health Club"

**Comment by boothym** [comment]
Hmm you're probably right - I went for the apostrophe as it was most common in amongst the current OSM objects, and most of the buildings I looked at used it on their signage. (Though my closest one actually has two signs on the building, with and without!)

But their online branding seems to be without the apostrophe, so probably best go with that.

**Comment by Adamant36** [comment]
@UKChris-osm do you care if I close this since it looks like you've dealt with it?

**Comment by boothym** [comment]
@Adamant36 there's still David Lloyd Leisure to be dealt with

**Comment by UKChris-osm** [comment]
@Adamant36 I think it would be better to leave this open a little longer, as like @boothym said there is one more that I haven't gotten around to yet, and someone else might be able to get to it before me.

**Comment by Adamant36** [comment]
> @Adamant36 there's still David Lloyd Leisure to be dealt with

Anyone have any opinions on if it would be better tagged as leisure=fitness_centre or leisure=sports_centre? It seems like both are used in about equal proportions (or to do they run both?).

**Comment by UKChris-osm** [comment]
I'd probably go with "_leisure=sports_centre_" as according to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_centre) a sports centre can contain a fitness centre

**Comment by UKChris-osm** [comment]
I've made a pull request #4182 for "_David Lloyd Clubs_" so it's a bit easier for others to see if it's suitable.
