### ISSUE TITLE
Revisiting the tagging schema for LANDBANK (Philippines)

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/name-suggestion-index#4104]
Similar to #2706, Land Bank of the Philippines uses capitalized letters for LANDBANK. One example of this can be found in their [About Us](https://www.landbank.com/about-us/about-landbank) page. Based on what I've found, I'm suggesting that the naming schema for LANDBANK be changed to the following:

"amenity": "bank"
"brand": "LANDBANK"
"brand:wikidata": "Q6483872"
"brand:wikipedia": "en:Land Bank of the Philippines"
"name": "LANDBANK"

**Comment by Adamant36** [comment]
It's in all caps on their store signs also. So having it in all caps in the index is fair change. Feel free to do a PR for it if you want. Otherwise, someone will probably do one eventually.

**Comment by matkoniecz** [comment]
I am still not convinced that we should follow such styling, I would treat it as a stylistic choice.

**Comment by UKChris-osm** [comment]
I noticed that we have "_Starbucks_" in the index with just a capital letter, yet the coffee shop branding is always upper-case.

Would Landbank be similar, by remaining only capitalised in the index, even though the store branding is all upper-case??

**Comment by bhousel** [comment]
I checked Google to see what they do, and looks like their labeling is all over the place.  A mix of "Land Bank of the Philippines",  "Land Bank", "Landbank", and "LANDBANK".  

<img width="600" alt="Screen Shot 2020-09-16 at 9 24 17 AM" src="https://user-images.githubusercontent.com/38784/93343449-7e3e7e00-f7fe-11ea-9d64-bf3c999eb534.png">

Given that the point of the `name` tag is to render something reasonable on a map pin or search result, I think we should just leave it as is.
