### ISSUE TITLE
Add supermarket cackback policies?

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#4105]
What's the current opinion on adding extra meta data like cashback? I know there was a previous pull request (#3048) that was rejected. However recently you have taken on tags like internet access, they seem similar on the face of it. Extra meta data in OSM is a good thing, and NSI seems to be a good place to recommend it.

**Comment by bhousel** [comment]
I think just about any business allows you to take cash back when you use a debit card to pay.  I don't see how this is a brand-specific thing?  I'd really prefer not to add so many tags that describes almost every business out there.  (it would be like adding `lit=yes` to all the stores - it may be true but nobody needs this.)

I'm also iffy on the value of adding the wifi tags, but I guess some brands use the same wifi in all their locations.

Also you call them "meta tags" - why?  Meta tags would be like, "data about the data" - like "date added" or "source".  I think there is probably a better word to describe them, but I don't know what it would be.

**Comment by Cj-Malone** [comment]
> I think just about any business allows you to take cash back when you use a debit card to pay.

I don't think you can generalise all the way to that, if you said most **supermarkets** in the UK(/EU/US/"Western world"), I'd agree, but "all" is quite inaccurate for a global project.

> I don't see how this is a brand-specific thing?

Certain chains/brands do it, certain ones don't. It's specific to the chain, not any individual location.

I guess you could argue for defaults, like all supermarkets in the UK offer cashback by default unless `cash_withdrawal=no`, but the OSM ecosystem doesn't have a standard place for data like that, nsi is the closest thing.

**Comment by tas50** [comment]
In the US you'd be really hard pressed to find a Supermarket in the index that didn't allow cash back. Some of them like certain Kroger brands may charge for that cash back, but it's assumed that debit card transaction comes with cash back here.

**Comment by Cj-Malone** [comment]
There are other tags related to cashback like fee and limit, not just the overall yes or no. See [the wiki](https://wiki.openstreetmap.org/wiki/Key:cash_withdrawal).

**Comment by lakedistrictOSM** [comment]
> Certain chains/brands do it, certain ones don't. It's specific to the chain, not any individual location.

Not necessarily. Some branches of Tesco Express offer cashback and some branches don't.

**Comment by Cj-Malone** [comment]
@lakedistrictOSM that's what Tesco said when I contacted them, so obviously it shouldn't be in the Tesco entries. On the other hand Heron Foods said none of there stores offer cash back.

**Comment by bhousel** [comment]
I thought about it more and I still think we should avoid adding extra payment tags for stores.  I'm worried that if we start adding a few, people will start adding a dozen `cash_withdrawal:*` tags to every brand.

**Comment by Cj-Malone** [comment]
What about just the explicit `cash_withdrawal=no`? Especially on POIs where it would be fair to assume they do offer it like `shop=supermarket` in the UK/US.

**Comment by bhousel** [comment]
> What about just the explicit `cash_withdrawal=no`?

People can still add whatever tags they want on the stores themselves - this index is about collecting tags that apply to _all_ of the stores.  

So if there is some brand that has made a statement about not allowing cash withdrawal at any of their stores, I guess we could add that tag here.  (Like how we added `opening_hours: 24/7` to Waffle House, it's a well-known thing about them).

Also, kind of related - I'm thinking of adding things like public transport networks to this index, and for those it might actually make sense to record what payment or smartcard options are allowed.  I'm mostly worried about adding superfluous tags like "accepts coins" to every fast food restaurant worldwide.

**Comment by Cj-Malone** [comment]
[Heron Foods](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket#heronfoods-a8278b) have removed cashback and has moved to ATMs in store. They are currently tagged as `shop=supermarket` so it would be fair for an OSM consumer to assume they offer cashback but we know they don't.

(They may be better as `shop=frozen_food`)

Would a PR be welcome in that case?
