### ISSUE TITLE
Shell in Japan needs name:ja and Japanese Wikipedia tags

### ISSUE THREAD

**Issue by nicolasmaia** [osmlab/name-suggestion-index#4109]
name:ja=ロイヤル・ダッチ・シェル
https://ja.wikipedia.org/wiki/%E3%83%AD%E3%82%A4%E3%83%A4%E3%83%AB%E3%83%BB%E3%83%80%E3%83%83%E3%83%81%E3%83%BB%E3%82%B7%E3%82%A7%E3%83%AB

**Comment by Adamant36** [comment]
> name:ja=ロイヤル・ダッチ・シェル

From my research Shell gas stations in Japan aren't branded as "Royal Dutch Shell" or "ロイヤル・ダッチ・シェル." The signs just say Shell. So, there isn't a unique Shell sub-brand specific to Japan. is the only point to this to have a link to the Japanese Wikipedia page for Shell stations in Japan or something along those lines?

**Comment by nicolasmaia** [comment]
Just シェル works too!

**Comment by Adamant36** [comment]
> Just シェル works 

Yeah, but why doesn't just Shell? Its what's on the signs and there's assumption of ground varifiability/"on the ground" rule with OSM. So why is the name:ja even needed? (I'm not saying it shouldn't be added. I'm just asking. There's a point where creating a seperate entry for every different language that's spoken where a global brand is located would get a little arduous 
and it could just be wrong. Especially if that langauge isn't what is on the businesses signs or how people there refer to the business).

**Comment by nicolasmaia** [comment]
My main concern is that data users looking for シェル won’t find Shell. But in any case, Latin alphabet letters are foreign here and people don't use them as much as their equivalents in kana in most situations. 

Also it seems to be common practice in this project to add name:ja to brands in Japan.

**Comment by Adamant36** [comment]
> Latin alphabet letters are foreign here and people don't use them as much as their equivalents in kana in most situations. Was there a specific thing that your concern is based on? 

I thought OSM based software deals with language localization if there's a whatever:ja tag present or not. 

> Also it seems to be common practice in this project to add name:ja to brands in Japan

Sure when its a Japanese brand we do. That's a completely different thing then what your requesting in this issue though. Just an FYI, there's a specifc reason I'm asking.

**Comment by bhousel** [comment]
This issue was old so I just took care of it today.

The entry looks like this now, so it will match all kinds of name strings including the ones in the thread above.  As far as I can tell, Showa Shell Sekiyu is a successor company spun out of Royal Dutch Shell a while ago, so I have these scoped to just Japan.

```js
    {
      "displayName": "昭和シェル",
      "id": "showashellsekiyu-fbe2e4",
      "locationSet": {"include": ["jp"]},
      "matchNames": ["ロイヤル・ダッチ・シェル", "昭和シェル石油"],
      "note": "Showa Shell Sekiyu was a subsidiary of Royal Dutch Shell but now operates as its own entity in Japan with qid Q277115",
      "tags": {
        "amenity": "fuel",
        "brand": "昭和シェル",
        "brand:en": "Showa Shell Sekiyu",
        "brand:ja": "昭和シェル",
        "brand:wikidata": "Q277115",
        "brand:wikipedia": "en:Showa Shell Sekiyu",
        "name": "昭和シェル",
        "name:en": "Showa Shell Sekiyu",
        "name:ja": "昭和シェル",
        "short_name": "シェル",
        "short_name:en": "Shell",
        "short_name:ja": "シェル"
      }
    },
```
