### ISSUE TITLE
Postal Office problem -- name should contain the number from `ref`

### ISSUE THREAD

**Issue by skfd** [osmlab/name-suggestion-index#4113]
It's useful and preferable to have reference number of the Postal Offices in it's name (in Ukraine).

Is there a way to do a preset with name that will also add a number variable?

Example of the current preset:
```
amenity=post_office
name:uk=Нова Пошта
name:en=Nova Poshta
ref=120
```

Example of the corrected preset:
```
amenity=post_office
name:uk=Нова Пошта №120
name:en=Nova Poshta #120
ref=120
```

**Comment by 1ec5** [comment]
NSI doesn’t have the ability to vary the tags for an individual feature belonging to a brand, only the overall brand. However, an editor should give the user the ability to customize the `name` to something more specific. If this isn’t the case for a particular editor, that would be worth mentioning in that editor’s bug tracker.

**Comment by skfd** [comment]
If it does not have this feature I propose to add one, it can be backwards compatible even. I'm mostly interested in iD, so will surely add a feature request there too :D

**Comment by bhousel** [comment]
Ah yeah just catching up with this now.. We can't support adding token replacements in the `name` tag, sorry!

I'm working on changes to the code to allow us to include entries that don't have a name, so that's what we would do for these post offices.

**Comment by bhousel** [comment]
The `name` tag isn't required anymore, so I removed it from Нова Пошта in 91975f5
