### ISSUE TITLE
Notes property?

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4114]
I've run into a few situations where it would be helpful to have a freetext notes/comments property on the entries.

For example, while disambiguating United Bank of Connecticut from United Bank of West Virginia, I discovered that the United Bank in Connecticut merged with People's United Bank in 2019.  It would be useful to capture this information in a note just so someone who comes along later to maintain all this stuff has the context, or to link to github tickets or wikipedia pages.

**Comment by UKChris-osm** [comment]
Do you mean just an NSI type note, or one that would appear within OSM? I'm guessing that either way, iD would need to be amended to ignore this note note proeprty, if it's just for the NSI? Unless JSON includes a comment ability that can be automatically ignored by any parser?

**Comment by bhousel** [comment]
> Unless JSON includes a comment ability that can be automatically ignored by any parser?

The parser we use can handle `// comments` in the files - but they get thrown away when the files are saved back to "proper" json format which doesn't support comments.

> **Edit:** Actually I guess iD wouldn't need to be amended if the note property was exclusive to the NSI, as the note just wouldn't be parsed when running npm run build?

Yep, it's just for a note that would stay within NSI for our own ease of maintenance.. I wouldn't expect any of the editors to do anything with it.

**Comment by Identitaet** [comment]
Could we change notes to NSI_notes so it can't be mistaken for the notes tag ?

**Comment by bhousel** [comment]
> Could we change notes to NSI_notes so it can't be mistaken for the notes tag ?

I'd rather not do this.. All the nsi-only properties are different from the OSM tags.  I put this note in the CONTRIBUTING guide:

"You can optionally add a `note` property to any item.  The note can contain any text useful for maintaining the index - for example, information about the brand's status, or a link to a GitHub issue.
The notes just stay with the name-suggestion-index; they aren't OpenStreetMap tags or used by other software."
