### ISSUE TITLE
Add Coast

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4124]
Women's clothing store chain located in the United Kingdom. 

https://en.wikipedia.org/wiki/Coast_(clothing)
https://www.wikidata.org/wiki/Q28135383

**Comment by UKChris-osm** [comment]
Coast no longer have any retail outlets, as they went bust and the brand bought out and retained as an online only business.

**Comment by Adamant36** [comment]
> Coast no longer have any retail outlets, as they went bust and the brand bought out and retained as an online only business.

Well that's a fail boat. I guess it's what I get for not reading the last sentence of Wikipedia article. It really could have been written clearer 😄

**Comment by UKChris-osm** [comment]
I did have to look into it a bit, as I thought the concession stands within John Lewis, Debenhams, etc still existed, but I ended up just messaging the company on facebook and asking them and they confirmed they were online only now :)
