### ISSUE TITLE
Change Mulberry tag

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4128]
Global clothing store chain. 

https://www.wikidata.org/wiki/Q87737811

**Comment by UKChris-osm** [comment]
I [added](https://github.com/osmlab/name-suggestion-index/commit/0e23b8072843db44791c3d2a4f4aadf61eccd3d7#diff-06e4e72d346758ae8e9df11495d95b74) Mulberry a while back under "__shop/fashion_accessories__", would you recommend a re-classification?

**Comment by Adamant36** [comment]
>  I added Mulberry a while back under "shop/fashion_accessories", would you recommend a re-classification?

Ummm, I thought it was another brand due to the different Wikidata entry. I'll probably merge this one with the "legitimate one" so there isn't anymore confusion about it. That said, maybe it would be better if they re-classified as shop=bag. Although, it looks like they sell shoes and "accessories." So who knows :man_shrugging:

**Comment by UKChris-osm** [comment]
I thought of Mulberry as a bag shop mostly, but because I saw they sold other things as well I thought accessories was more appropriate.

**Comment by bhousel** [comment]
Let's leave as `fashion_accessories` - that seems fine.
I've merged the Q87737811 qid into Q3866987.
