### ISSUE TITLE
Add Harris Farm Markets

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4129]
Australian supermarket chain. 

https://en.wikipedia.org/wiki/Harris_Farm_Markets
https://www.wikidata.org/wiki/Q5664888

**Comment by KamajiiSC** [comment]
I submitted a pull request for this! #4142

**Comment by modaserMoj** [comment]
Is this still open?

**Comment by Adamant36** [comment]
> Is this still open?

I guess not since there was a PR for it that was merged. Feel free to do a PR for one of the other ones though 👍
