### ISSUE TITLE
Missing UK brands

### ISSUE THREAD

**Issue by lakedistrictOSM** [osmlab/name-suggestion-index#4141]
Please can the following be added:

name=Timpson
shop=locksmith
craft=key_cutter
brand:wikidata=Q7807658

name=Poundbakery
shop=bakery
brand:wikidata=Q21061591

Roman appears at https://nsi.guide/index.html but doesn't appear in iD when searched?

name=Roman
shop=clothes
brand:wikidata=Q94579553

**Comment by UKChris-osm** [comment]
Roman was added a little while ago and will appear line when a fresh update is released, but I don't know when this will be as some alterations need to be made to either the NSI or the iD Editor.

Timpson was discussed via #3437, but so far no conclusion as to how to tag it.

**Comment by lakedistrictOSM** [comment]
Thanks for adding Poundbakery @UKChris-osm As Timpson already has an open issue, I'll hit the close button on this one now.
