### ISSUE TITLE
FR: Add Effia (parking)

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#4156]
Hello,

Country code: FR (only, but verification requested) 

"amenity":"parking"
"brand":"Effia"
"brand:wikidata":"Q3045894"
"brand:wikipedia":"fr:EFFIA"
"name":"Effia"

The name of the company is entirely in upper case so I don't know how to take it into account because OSM doesn't like names in upper case (and neither do I)

**Comment by Identitaet** [comment]
I just looked and they say on their website "EFFIA is a major player in parking in France and Belgium"
but it is unclear if they just own a company with elgian parking spaces or operate them under the effia brand
https://www.keolis.com/en/media/newsroom/press-releases/effia-strengthens-its-presence-belgium-with-acquisition-parkeren
but given the fact that the accquired brands still seem to operating under their own branding I'd say only france is correct

Also yes all the names are usually made to lower case
