### ISSUE TITLE
Edit イエロー・サブマリン

### ISSUE THREAD

**Issue by maro-21** [osmlab/name-suggestion-index#4168]
Yellow Submarine sells mainly tabletop games, models and toys, so the tag should be `shop=toys`.

Also the website is wrong. It points to a confectionery shop http://www.souhonke-surugaya.co.jp instead of https://www.yellowsubmarine.co.jp.

**Comment by maro-21** [comment]
The website is still incorrect. [Q11668496](https://www.wikidata.org/wiki/Q11668496) points to Surugaya.
https://nsi.guide/index.html?k=shop&v=hobby#yellowsubmarine-dd8d0c

**Comment by bhousel** [comment]
> The website is still incorrect. [Q11668496](https://www.wikidata.org/wiki/Q11668496) points to Surugaya.

ok, I fixed it in d21cf1f6
