### ISSUE TITLE
Research needed for: amenity/cinema|Октябрь

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#417]
#### :thinking: We need help deciding what to do with "amenity/cinema|Октябрь"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/cinema|Октябрь` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/cinema|Октябрь`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/cinema|Октябрь`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
These are probably all independently working cinemas just named Октябрь (October).
Wikipedia lists some of them on a disambiguation page: https://ru.wikipedia.org/wiki/Октябрь_(значения) ([Google Translate](https://translate.google.de/translate?sl=auto&tl=en&u=https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%259E%25D0%25BA%25D1%2582%25D1%258F%25D0%25B1%25D1%2580%25D1%258C_%28%25D0%25B7%25D0%25BD%25D0%25B0%25D1%2587%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%29))

**Comment by matkoniecz** [comment]
Yeah, Soviet Union really liked to name everything October.

Comfirmed with someone who has local knowledge.
