### ISSUE TITLE
Research needed for: amenity/fast_food|A&W

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#418]
#### :thinking: We need help deciding what to do with "amenity/fast_food|A&W"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fast_food|A&W` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fast_food|A&W`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fast_food|A&W`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by bhousel** [comment]
Hey @matkoniecz - we should double check this? 
I think A&W is going to be one of the complicated cases.
There are 2 separate A&Ws - one in US and one in CA

🇺🇸 https://en.wikipedia.org/wiki/A%26W_Restaurants
🇨🇦 https://en.wikipedia.org/wiki/A%26W_(Canada)

**Comment by bhousel** [comment]
this is like #1880

**Comment by matkoniecz** [comment]
Ops, I missed it.

**Comment by bhousel** [comment]
no worries - these are easy to miss!
