### ISSUE TITLE
Is Indian Palace a generic rstaurant name ?

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4194]
I have look for restaurants with that name but have found none belonging to any chain neither do I find a websites which is for more than one restaurant

**Comment by UKChris-osm** [comment]
I couldn't find a brand for it either, so it could just be a popular name used across the world by many independent restaurants, which was picked up by the NSI when a planet file scan was done.

**Comment by bhousel** [comment]
I agree - removed it in 691e9d5a
