### ISSUE TITLE
Api (amenity/fuel) seems to be tagged with the wrong Wikidata entry

### ISSUE THREAD

**Issue by matthewlw** [osmlab/name-suggestion-index#4196]
[Api](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#api-e8f712) is currently associated with the [American Petroleum Institute](https://www.wikidata.org/wiki/Q466043). It seems highly unlikely that an American trade association is running gas stations in Italy and only in Italy, so I'm guessing that Api instead stands for [Anonima Petroli Italiana](https://www.wikidata.org/wiki/Q646807). However, this raises two issues:
* [This Overpass query](https://overpass-turbo.eu/s/Ykg) indicates that 53 locations have already been tagged with the wrong `brand:wikidata`. Is there any existing procedure for automatically or semi-automatically correcting this?
* The same company already shows up associated with the [IP brand](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#ip-b3d110), and a cursory look at [the company's English Wikipedia page](https://en.wikipedia.org/wiki/Anonima_Petroli_Italiana) suggests that Api is the operator, rather than the brand, of the gas station. Can anyone in Italy check this?

**Comment by bhousel** [comment]
Thanks for reporting @matthewlw , and for doing the research to find the correct Wikidata QID.

> * [This Overpass query](https://overpass-turbo.eu/s/Ykg) indicates that 53 locations have already been tagged with the wrong `brand:wikidata`. Is there any existing procedure for automatically or semi-automatically correcting this?

I've done a few re-taggings like this in the past - I usually use the "export" link on Overpass Turbo to bring the mistagged entries into level0, then update them all at once.

> * The same company already shows up associated with the [IP brand](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#ip-b3d110), and a cursory look at [the company's English Wikipedia page](https://en.wikipedia.org/wiki/Anonima_Petroli_Italiana) suggests that Api is the operator, rather than the brand, of the gas station.

No, I don't think that's the case.. `operator` is the entity that operates the gas station.  It's often an individual or franchisee:

<img width="275" alt="Screen Shot 2020-09-23 at 11 03 19 PM" src="https://user-images.githubusercontent.com/38784/94096040-1fc26280-fdf1-11ea-9658-aed17ad7a719.png">

**Comment by bhousel** [comment]
I added a file config/replacements.json to keep track of all the situations where QIDs have changed and we should remap them in OSM data.
