### ISSUE TITLE
document is it used somewhere

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#42]
There is "In iD we want to help suggest the most common names with the correct formatting and spelling." in the readme, but it is unclear whatever data collected here is really used anywhere (so it is not clear whatever it makes sense to put effort here or one should find a real data source used by iD to blacklist descriptive names).

**Comment by aaronlidman** [comment]
Instructions are at the bottom here: https://github.com/osmlab/name-suggestion-index#updating-topnamesjson-from-planet

You must have nodejs installed along with the other dependencies listed there.

**Comment by matkoniecz** [comment]
Thanks!
