### ISSUE TITLE
Add brands in Germany

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4203]
brand=Vorwerk
name=Vorwerk
shop=vacuum_cleaner
brand:wikidata=Q449852
brand:wikipedia=de:Vorwerk_(Unternehmen)

brand=Zoo&Co.
name=Zoo&Co.
shop=pet
brand:wikidata=Q219979
brand:wikipedia=de:Zoo & Co.

brand=Wempe
name=Wempe
shop=jewelry
brand:wikidata=Q1483424
brand:wikipedia=de:Gerhard D. Wempe

brand=Multipolster
name=Multipolster
shop=furniture
brand:wikidata=n/a
brand:wikipedia=n/a
website=https://www.multipolster.de

brand=Poco
name=Poco
shop=furniture
brand:wikidata=Q1714820
brand:wikipedia=de:Poco (Möbelhaus)

brand=SB-Möbel Boss
name=SB-Möbel Boss
shop=furniture
brand:wikidata=n/a
brand:wikipedia=n/a
website=https://moebel-boss.de

brand=Holzleitner
name=Holzleitner
shop=electronics
brand:wikidata=n/a
brand:wikipedia=n/a
website=https://www.holzleitner.de/

brand=BayWa
name=BayWa
shop=doityourself
brand:wikidata=Q812055
brand:wikipedia=de:BayWa

brand=Vom Fass
name=Vom Fass
shop=deli
brand:wikidata=Q2533008
brand:wikipedia=de:Vom Fass

brand=Gravis
name=Gravis
shop=computer
brand:wikidata=Q1543982
brand:wikipedia=de:Gravis Computervertriebsgesellschaft

brand=Vergölst
name=Vergölst
shop=tyres
brand:wikidata=Q1673875
brand:wikipedia=de:Vergölst

brand=Jacques’ Wein-Depot
name=Jacques’ Wein-Depot
shop=wine
brand:wikidata=Q1678150
brand:wikipedia=de:Jacques’ Wein-Depot

brand=MFO Matratzen
name=MFO Matratzen
shop=bed
brand:wikidata=Q26794529
brand:wikipedia=de:MFO Matratzen

**Comment by Identitaet** [comment]
Could you help me with what the actuall label used for Möbell Boss is

I'm a bit confused there

**Comment by kjonosm** [comment]
> Could you help me with what the actuall label used for Möbel Boss is
> 
> I'm a bit confused there

their signage is a bit all over the place, but I would maybe just cut the (SB-) and go ahead with Möbel Boss...

**Comment by Identitaet** [comment]
well luckily since the newest update we can skip the name tag that's probably the best thing to do here

**Comment by bhousel** [comment]
> well luckily since the newest update we can skip the name tag that's probably the best thing to do here

No, please don't skip the `name` tag unless you have a really good reason to - i.e. every instance of this business has a unique name.
