### ISSUE TITLE
Add brands in Germany #2

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4212]
I researched some more German brands browsing through [https://wiki.openstreetmap.org/wiki/Germany/Shops]. I hope it's ok to throw them all into one issue or should I rather split them up (next time)?

- [x] name=Fränky
       brand=Fränky
       shop=beverages
       brand:wikidata=Q23787118 -> parent company Orterer Gruppe)
       brand:wikipedia=de:Fränky -> redirect to parent company Orterer Gruppe)
       website=https://www.fraenky-getraenke.de

________________

- [x] name=Finkbeiner
       brand=Finkbeiner
       shop=beverages
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=http://www.finkbeiner.biz

- [x] name=Barrique
       brand=Barrique
       shop=deli
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=https://www.barrique.com

- [x] name=TTL
       brand=TTL
       shop=doityourself
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=https://www.ttl-ttm.de

- [x] name=TTM
       brand=TTM
       shop=doityourself
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=https://www.ttl-ttm.de

- [x] name=Wolle Rödel
       brand=Wolle Rödel
       shop=wool
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=https://www.wolle-roedel.com

- [x] name=Premio
       brand=Premio
       shop=tyres
       brand:wikidata=n/a
       brand:wikipedia=n/a
        website=https://www.premio.de

- [x] name=Rupprecht
       brand=Rupprecht
       shop=books
       brand:wikidata=n/a
       brand:wikipedia=n/a
       website=https://www.rupprecht.de

**Comment by Identitaet** [comment]
Yes you can add them in a big list like that.
Also let's start going through the bits that are unsure
PC-Specialist and Fränkys

**Comment by camelCaseNick** [comment]
Are Yorma’s shop=convenience? Wikidata calls them _Imbisskette_, Wikipedia _Systemgastronomie_. I wouldn't have had considered them a convenience store.

**Comment by Identitaet** [comment]
Good question they sell a lot of things but also have the sandwiches as a main focus

**Comment by Identitaet** [comment]
And the one from my train station is tagged as a Kiosk

**Comment by Identitaet** [comment]
is shop carpet accurate for tedox ?
They seem to sell a lot of things for home improvment
I'd think It'd be shop=doityourself

**Comment by kjonosm** [comment]
> is shop carpet accurate for tedox ?

yeah, tagging it as DIY also works to reflect their entire range of products.

> Are Yorma’s shop=convenience?

they are between fast_food/bakery/convenience. So fast_food might be more appropriate and in line with wikipedia.

**Comment by Identitaet** [comment]
![IMG_20200929_111219](https://user-images.githubusercontent.com/58372210/94538808-c6b95b00-0244-11eb-9592-9eb429a36c51.jpg)
![IMG_20200929_111041](https://user-images.githubusercontent.com/58372210/94538814-c7ea8800-0244-11eb-9f0c-b884d68a4522.jpg)
![IMG_20200929_110909](https://user-images.githubusercontent.com/58372210/94538822-c91bb500-0244-11eb-8592-e450ed018804.jpg)
The problem with yormas is that they operate convenience type stores and more kiosk like stores both under the same brand (and even in the same train station

**Comment by bhousel** [comment]
> The problem with yormas is that they operate convenience type stores and more kiosk like stores both under the same brand

This is ok - we can add the "yormas" to both the `shop/convenience.json` and `shop/kiosk.json` files.  Then users can choose either.

**Comment by Identitaet** [comment]
okay all the shops with wiki articles have been added

**Comment by Adamant36** [comment]
@kjonosm could you turn your original comment into a check list and check off the ones that have been done?
