### ISSUE TITLE
Add Mo'men

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4272]
Egyptian fast food sandwich shop chain. 

https://en.wikipedia.org/wiki/Mo%27men
https://www.wikidata.org/wiki/Q3317535

**Comment by ryuzaki221** [comment]
I would like to help with this

**Comment by Adamant36** [comment]
Go for it.

**Comment by ryuzaki221** [comment]
#4296 
I ran `npm run build` to generate the id. Hope that wasn't a thing

**Comment by UKChris-osm** [comment]
Merged via #4296
