### ISSUE TITLE
Add Mr Bigg's

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4273]
Nigerian fast food chain. 

https://en.wikipedia.org/wiki/Mr_Bigg%27s
https://www.wikidata.org/wiki/Q955488

**Comment by gabrielhicks** [comment]
I would like to work on this issue.

Thanks

**Comment by Adamant36** [comment]
> I would like to work on this issue.

Go for it 👍

**Comment by TheDynamicPunk** [comment]
@Adamant36 Is this being worked upon? Or can I move ahead with it?

**Comment by gabrielhicks** [comment]
@TheDynamicPunk you got it! I asked for it either but did a different one so have at it!

**Comment by TheDynamicPunk** [comment]
Thanks @gabrielhicks , I've added it and issued a pull request!

**Comment by Adamant36** [comment]
Closed in #4298.
