### ISSUE TITLE
Add Kilimanjaro

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4285]
Nigerian fast food chain. 

Country code: ng

https://en.wikipedia.org/wiki/Kilimanjaro_(restaurant)
https://www.wikidata.org/wiki/Q28453128

**Comment by 29parthi** [comment]
i would like to pick this issue

**Comment by Adamant36** [comment]
Thanks. Go for it. BTW, you don't really have to ask or let us know ahead of time do a PR for anything. Just make sure it's not something that already has a PR open for it.

**Comment by 29parthi** [comment]
#4295

**Comment by UKChris-osm** [comment]
Merged via [f02bea0](https://github.com/osmlab/name-suggestion-index/commit/f02bea05da393523ec05589c936f00b0cdb67a31)
