### ISSUE TITLE
Add Chicken Licken

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4287]
South African fast food fried chicken chain. 

Country code: za

https://en.wikipedia.org/wiki/Chicken_Licken_(restaurant)
https://www.wikidata.org/wiki/Q23461416

**Comment by TheDynamicPunk** [comment]
I would like to take up this issue. Please help further I'm new to Open Source. Hoping to learn something positive here!

**Comment by UKChris-osm** [comment]
@Adamant36 I think the Wikidata for this one should be [Q4164819](https://www.wikidata.org/wiki/Q4164819)

**Comment by TheDynamicPunk** [comment]
@UKChris-osm Yeah you're right that's what I was about to comment

**Comment by UKChris-osm** [comment]
Merged via #4293
