### ISSUE TITLE
Add Goli Vada Pav

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4304]
Indian fast food restaurant chain. 

https://en.wikipedia.org/wiki/Goli_Vada_Pav
https://www.wikidata.org/wiki/Q5580697

**Comment by pivovarnikj** [comment]
Hi, can i work on this issue?

**Comment by Adamant36** [comment]
Sure. Go for it.

**Comment by ashutoshshisodia** [comment]
Hey @Adamant36  please review.
