### ISSUE TITLE
Add Jumbo King

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4305]
Indian fast food burger restaurant chain.

https://en.wikipedia.org/wiki/Jumbo_King
https://www.wikidata.org/wiki/Q6310895

BTW, there might or might not be a space in the name. It looks like OSM favors it without a space though, but then it's mixed on if the K should be in lower or upper case. So 🤷‍♂️

**Comment by londonjob** [comment]
added in https://github.com/osmlab/name-suggestion-index/pull/4291
