### ISSUE TITLE
Add KaatiZone

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4306]
Indian cuisine fast food chain located in India. 

https://en.wikipedia.org/wiki/KaatiZone
https://www.wikidata.org/wiki/Q6343638

**Comment by SBhattacharya45** [comment]
I'm working on this

**Comment by Adamant36** [comment]
Done in #4310. Although, I'm going to wait for now to merge it.

**Comment by Adamant36** [comment]
Done in #4310 since I decided to merge it.
