### ISSUE TITLE
Add Saravana Bhavan

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4307]
Global vegetarian restaurants serving Indian cuisine. 

https://en.wikipedia.org/wiki/Saravana_Bhavan
https://www.wikidata.org/wiki/Q3528082

**Comment by valdaarhun** [comment]
Hi. I would like to work on this. Doesn't look like there have been any PRs on this one.

**Comment by Adamant36** [comment]
Closed in #4325
