### ISSUE TITLE
Add California Fried Chicken

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4312]
Indonesian fried chicken fast food chain. Going by the numbers it would be better to go with CFC for the name etc, and add California Fried Chicken with the official_name tag. 

cuisine=chicken

https://en.wikipedia.org/wiki/California_Fried_Chicken
https://www.wikidata.org/wiki/Q5020502

**Comment by valdaarhun** [comment]
Hi. I would like to work on this.

**Comment by Adamant36** [comment]
Closed in 4312. Sorry @valdaarhun, but someone already did. Feel free to work on another issue though.

**Comment by valdaarhun** [comment]
@Adamant36 No problem. Thanks for letting me know.
