### ISSUE TITLE
Add HokBen

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4313]
Indonesian fast food chain. So it goes in the fast food file.

cuisine=japanese

Also, it would be good to have a match name for Hoka Hoka Bento.

https://en.wikipedia.org/wiki/HokBen
https://www.wikidata.org/wiki/Q5877948

**Comment by bhavesh0206s** [comment]
hi @Adamant36 
I would like to work on this issue.

**Comment by ashutoshshisodia** [comment]
Hey I am working on this issue, will be done in some time hopefully! I have a query though, from where we get the "id" ?

**Comment by TheDynamicPunk** [comment]
@ashutoshshisodia _"id"_ is automatically generated when you run command `npm run build` in the terminal

**Comment by ashutoshshisodia** [comment]
Hey @TheDynamicPunk  thank you so much, although I figured it out. :) Thanks again.

**Comment by TheDynamicPunk** [comment]
@ashutoshshisodia nice! Also I'd like to suggest that it's always a good practice to make sure someone else isn't working on an issue before filing a PR for it. It helps reduce redundancy and makes it easy for everyone to collaborate! Cheers :)

**Comment by ashutoshshisodia** [comment]
Hey @TheDynamicPunk , sorry I'm new to this.l will keep this in mind. Thank you so much.

**Comment by bhousel** [comment]
Thanks all for your enthusiasm closing issues for us, you are awesome 👏

**Comment by TheDynamicPunk** [comment]
@bhousel I'm pumped to be a part of this community! Cheers everyone! 😉
