### ISSUE TITLE
Add Kebab Turki Baba Rafi

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4321]
Global fast food kebab chain. It's also known as KTBR. It would probably be better to have that as the name etc and do official_name=Add Kebab Turki Baba Rafi for the full name. 

It goes in the fast food file. 
cuisine=kebab
https://en.wikipedia.org/wiki/Kebab_Turki_Baba_Rafi
https://www.wikidata.org/wiki/Q6382370

**Comment by SBhattacharya45** [comment]
working on this

**Comment by Adamant36** [comment]
Closed in #4324.
