### ISSUE TITLE
Add Old Chang Kee

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4355]
Fast food chain located in Singapore. Goes in the fast food file. 

name:en=Old Chang Kee
name:zh=老曾记
(same for brand tags)

https://en.wikipedia.org/wiki/Old_Chang_Kee
https://www.wikidata.org/wiki/Q17005286

**Comment by hambali999** [comment]
Hey Can you assign me? XD I am interested and doo add the label 'hacktoberfest'

**Comment by Adamant36** [comment]
Hi there. Thanks for the interest. We don't assign people things. So you can just do a PR for it if you want to and there already isn't one. With the hacktoberfest label, it doesn't need to be added.

**Comment by Adamant36** [comment]
Closed in #4371
