### ISSUE TITLE
Add Sakae Sushi

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4356]
Fast food sushi chain located in Singapore. So, it goes in the fast food file. 

name:en=Sakae Sushi
name:ja=栄寿司
(same for brand tags)

cuisine=japanese

https://en.wikipedia.org/wiki/Sakae_Sushi
https://www.wikidata.org/wiki/Q14955169

**Comment by bclingan** [comment]
I will try this one, looks like no one else has yet.

**Comment by Adamant36** [comment]
Go for it.

**Comment by pushkar1393** [comment]
I am not sure how PR's are linked back to the issue in any way. So, I am adding the link here  - [](https://github.com/osmlab/name-suggestion-index/pull/4370)

**Comment by Adamant36** [comment]
Closed in #4370. BTW, if you say "closes" and the issue number in your PR it will automatically link them and close the issue when the PR is merged.
