### ISSUE TITLE
Add Tom N Toms

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4357]
South Korean coffee shop chain. 

name:en=Tom N Toms
name:ko=탐앤탐스
(also with the brand tags)

https://en.wikipedia.org/wiki/Tom_N_Toms
https://www.wikidata.org/wiki/Q18142418

**Comment by TheDynamicPunk** [comment]
Working on it

**Comment by TheDynamicPunk** [comment]
> name:en=Tom N Toms

@Adamant36 I have to add it to _**brands/shop/coffee**_ right?

**Comment by TheDynamicPunk** [comment]
> I have to add it to _**brands/shop/coffee**_ right?

@bhousel Can you help please?

**Comment by bhousel** [comment]
> @Adamant36 I have to add it to _**brands/shop/coffee**_ right?

no sorry, please add it to [brands/amenity/cafe](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/cafe.json)

OpenStreetMap draws a distinction between
* `amenity=cafe` - coffeehouses where people primarily go to drink coffee
* `shop=coffee` - retail store where people primarily go to buy beans

**Comment by TheDynamicPunk** [comment]
Okay thanks👍

**Comment by Adamant36** [comment]
> @Adamant36 I have to add it to brands/shop/coffee right?

Sorry, I could have been more specific.

**Comment by TheDynamicPunk** [comment]
Hey @Adamant36, No worries mate.
