### ISSUE TITLE
Add Rolls

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4359]
Fast food hamburger chain located in Finland. So, it goes in the fast food file. 

cuisine=burger

https://en.wikipedia.org/wiki/Rolls_(restaurant_chain)
https://www.wikidata.org/wiki/Q3195068

**Comment by Hisime** [comment]
Please assign it to me

**Comment by Adamant36** [comment]
Hi there. We don't assign things to people. So, your free to do a PR if there isn't already one for it.

**Comment by bhousel** [comment]
done in #4361
