### ISSUE TITLE
Research needed for: amenity/fast_food|Pizza King

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#437]
#### :thinking: We need help deciding what to do with "amenity/fast_food|Pizza King"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fast_food|Pizza King` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fast_food|Pizza King`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fast_food|Pizza King`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
@ENT8R, this was a couple of actual pizza companies in both America and Europe. It probably could have been split into different brands instead of just discarded.

**Comment by ENT8R** [comment]
But I don't think that this is a brand which operates at multiple locations. This seems to be just some kind of generic name... Why do you think that this would be an actual company/brand?

**Comment by Adamant36** [comment]
Wierdly, I was just randomlu reading about the founder of the American chain a few hours ago. 

https://en.m.wikipedia.org/wiki/Sir_Pizza

I haven't looked into the European ones yet, but we could at least have an entry for the American ones with a country code restriction.

**Comment by ENT8R** [comment]
Okay, but in Europe this seems to be just a generic name. Because the majority of locations there is in Denmark or Germany and there is no fast food brand/chain with that name.

**Comment by Adamant36** [comment]
Well, we could make an entry with a country exception for the ones in America at least and ignore the European ones. We do it in other instances. Maybe someone could open notes at some of the European ones also to find out what they are.

**Comment by ENT8R** [comment]
> Wierdly, I was just randomlu reading about the founder of the American chain a few hours ago.
https://en.m.wikipedia.org/wiki/Sir_Pizza

But that entry should be named `amenity/fast_food|Sir Pizza`, shouldn't it?
The Wikipedia articles mentions that only

> [i]n Indiana, they are franchised under the Pizza King name, one of two chains in Indiana using that name. 

I checked this again and in Europe there is no chain named "Pizza King" (except two companies that operate multiple (2-4) restaurants under that name in one city), so at least there is is a generic name...

**Comment by Adamant36** [comment]
That works
