### ISSUE TITLE
Add brand: OTP bank

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4377]
Hi,

OTP bank is an international banking group based in Hungary. It operates in several countries as you can see [on its website](https://www.otpbank.hu/portal/en/AboutUs/OTPGroup) and also on [Wikipedia](https://en.wikipedia.org/wiki/OTP_Bank).

It is difficult to find all its branches because the form of the name varies (small letters and capitals, with of without "bank", written separately or together, with latin or cyrillic letters etc.), e.g. otp, Otp, OTP, otpbank otp bank and so on. Thus, it would be wise to create a nice regex to it which I can't. Nevertheless I tried to create [an overpass query](http://overpass-turbo.eu/s/YO7). It gave more than 500 results.

Good luck and thanks!

Gábor

**Comment by johan7004** [comment]
#4378 i would like to work on this

**Comment by Adamant36** [comment]
OTP Bank and ОТП Банк are already in the index. Maybe they need match names or something...If you go nsi.guide and search for OTP it will come up. Then if you click on the OverPassTurbo link it likely give a bunch of miss, but closely, named POIs. Maybe that would be a place to start with figuring out the matches.

**Comment by bhousel** [comment]
Yes looks like there isn't much to do here.. I added `short_name` tags in fc9dcd33 so that OTP/ОТП will also match.
