### ISSUE TITLE
Translation for portuguese

### ISSUE THREAD

**Issue by printf-ana** [osmlab/name-suggestion-index#4391]
Hey! I'd like to translate the README file for portuguese for some of my firsts pull requests, can i?

**Comment by bhousel** [comment]
> Hey! I'd like to translate the README file for portuguese for some of my firsts pull requests, can i?

Sorry I'd prefer if people don't translate the README files.  It's too hard to keep them up-to-date as things change.  

Instead maybe you can look up the details for your local transit network?  https://nsi.guide/index.html?t=transit
We are looking for pull requests to add `network:wikidata` to all of the ones that are not yet matched..
