### ISSUE TITLE
Add eurobahn

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4402]
de:Eurobahn is the network
https://de.wikipedia.org/wiki/Eurobahn
And Keolis Germany the operator
But only Keolis exists on the wiki

> Keolis Deutschland GmbH & Co. KG mit Sitz in Düsseldorf ist eine Tochter der Keolis S.A.
https://de.wikipedia.org/wiki/Keolis

Area DE&NL

**Comment by KennethYoel** [comment]
Ok, I'll try to add it. I think my German is good enough.

**Comment by Identitaet** [comment]
Okay since Keolis Germany is a direct subsidiary and only exists for legal reasons that seems acceptable to just use Keolis
