### ISSUE TITLE
add Westfalenbahn (easy)

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4403]
https://de.wikipedia.org/wiki/Westfalenbahn network
https://de.wikipedia.org/wiki/Abellio_(Unternehmen) operator
Area DE only

**Comment by Identitaet** [comment]
Also add matchName WFL

**Comment by shubh710** [comment]
Hi @Identitaet ,
I would like to work on this but a little guidance will be required as I am new to OSS.

**Comment by Identitaet** [comment]
Sure feel free to ask any questions
As a tip I'd suggest you look at #4414 which is quite similar

**Comment by shubh710** [comment]
Thanks @Identitaet for tip it was quite helpful.
I have submitted PR #4446 
Please review and let me know if it is okay or anything is missing.
Thanks again.
