### ISSUE TITLE
add Raiffeisen Hungary

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4409]
You can add the [Hungarian](https://overpass-turbo.eu/s/YS1) branch of [Raiffeisen Bank](https://www.raiffeisen.hu/web/english).

It is a bit unclear, when to distinguish between local branches of a brand (e.g. there are 7 Raiffeisens) and when to use them as one entity for more countries (e.g. a [global Unicredit bank (comprising also Bulgaria)](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22name%22%3D%22UniCredit%20Bank%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B%0A%0A%7B%7Bstyle%3A%0Anode%5Bname%3DUniCredit%20Bank%5D%2C%0Away%5Bname%3DUniCredit%20Bank%5D%2C%0Arelation%5Bname%3DUniCredit%20Bank%5D%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%2C%0Away%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%2C%0Arelation%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%5Bbrand%3DUniCredit%20Bank%5D%5Bbrand%3Awikidata%3DQ45568%5D%2C%0Away%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%5Bbrand%3DUniCredit%20Bank%5D%5Bbrand%3Awikidata%3DQ45568%5D%2C%0Arelation%5Bamenity%3Dbank%5D%5Bname%3DUniCredit%20Bank%5D%5Bbrand%3DUniCredit%20Bank%5D%5Bbrand%3Awikidata%3DQ45568%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R) + [Bulgarian affiliate](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22name%22%3D%22%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B%0A%0A%7B%7Bstyle%3A%0Anode%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%2C%0Away%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%2C%0Arelation%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%2C%0Away%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%2C%0Arelation%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3Awikidata%3DQ7884635%5D%2C%0Away%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3Awikidata%3DQ7884635%5D%2C%0Arelation%5Bamenity%3Dbank%5D%5Bname%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3D%D0%A3%D0%BD%D0%B8%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%20%D0%91%D1%83%D0%BB%D0%B1%D0%B0%D0%BD%D0%BA%5D%5Bbrand%3Awikidata%3DQ7884635%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R)).

**Comment by Adamant36** [comment]
> It is a bit unclear, when to distinguish between local branches of a brand (e.g. there are 7 Raiffeisens) and when to use them as one entity for more countries (e.g. a global Unicredit bank (comprising also Bulgaria) + Bulgarian affiliate).

Usually either when there's different social media accounts and/or Wikidata/Wikipedia entries, or in cases where we want to create a unique entry for a brand not in it's "native" language. For instance with Starbucks, McDonald's etc. and their separate Chinese entries. I'm pretty sure in those cases we create separate Wikidata entries for them also. Which is what we have done with Raiffeisenbank. 

In this case, I'd probably create another a unique entry. Especially if they have separate social media accounts and websites. Although, only 7 branches is a little low to warrant it and might cause the Wikidata entry to get deleted.

**Comment by bhousel** [comment]
Looking at https://nsi.guide/index.html?t=brands&k=amenity&v=bank and filtering on "raiffeisen" it looks like most of the local country raiffeisenbank's have their own wikidata set up, so it seems like Hungary should also.

**Comment by amous4822** [comment]
added [wikidata](https://www.wikidata.org/wiki/Q100944002). It needs wikipedia.

**Comment by airon90** [comment]
New Wikidata ID is [Q16522506](https://www.wikidata.org/wiki/Q16522506) because I merged @amous4822's one into an existing one, which have Wikipedia links too
