### ISSUE TITLE
Add Southern Fried Chicken

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4416]
Global fast food fried chicken chain. 

cuisine=chicken

https://en.wikipedia.org/wiki/Southern_Fried_Chicken
https://www.wikidata.org/wiki/Q7569934

**Comment by TheDynamicPunk** [comment]
Working on it!

**Comment by TheDynamicPunk** [comment]
> Southern Fried Chicken is currently sold in over 700 locations, across over 79 countries worldwide.

Do I have to add each and every one of them? Also if yes, where do I find the specific countries where it's present?

**Comment by Adamant36** [comment]
> Do I have to add each and every one of them? Also if yes, where do I find the specific countries where it's present?

No just put 001. I think that's location code for the globe.
