### ISSUE TITLE
Add Tortilla

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4417]
Fast food restaurant chain located in the UK, UAE, and Saudi Arabia.

cuisine=tex-mex

https://en.wikipedia.org/wiki/Tortilla_(restaurant_chain)
https://www.wikidata.org/wiki/Q21006828

**Comment by TheDynamicPunk** [comment]
I'm working on this. Bu the way I'm just curious how's tex-mex different from italian? I mean the first search I did on Google and it showed pics of pasta and some mediterranean dishes 😅

**Comment by bhousel** [comment]
> I'm working on this. By the way, I'm just curious how's tex-mex different from italian? I mean the first search I did on Google and it showed pics of pasta and some mediterranean dishes 😅

Their website https://www.tortilla.co.uk/ shows burritos 🌯   , so `tex-mex` seems reasonable to me.

here's some links to help choose the best OSM cuisine tag:
https://wiki.openstreetmap.org/wiki/Key:cuisine
https://taginfo.openstreetmap.org/keys/cuisine#values

**Comment by TheDynamicPunk** [comment]
Oh okay, thanks @bhousel!
