### ISSUE TITLE
Add Chateau d'Ax

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4427]
```
name=Chateau d'Ax
shop=furniture
website=https://www.chateau-dax.com
website=https://www.chateau-dax.fr
website=https://www.chateau-dax.it
website=https://www.chateau-dax.be
website=https://www.chateau-dax.nl
wikidata=Q100249791
```
Currently 33 / 59 shops in France https://overpass-turbo.eu/s/YT4

Countries
```
Angola
Belgium
Canada
China
Croatia
France
Germany
Guadeloupe
Hong Kong
Italy
Malta
Martinique
Mauritius
Morocco
Mozambico
Portogallo
Portugal
Reunion Island
Singapore
Slovacchia
Spain
Switzerland
Taiwan
Tunisia
Turkey
USA
Vietnam
```

**Comment by joey2031** [comment]
Hello, I would like to work on this issue, is that ok?

**Comment by Identitaet** [comment]
Yes it's okay

**Comment by joey2031** [comment]
I just have some questions:
1. I can't find a wiki page for this company, do I just take out the "brand:wikipedia"?
2. Some countries where not on the wiki with the iso codes so I googled them and got this result:
Mozambico: MZ, Portogallo: PRT, Reunion Island: RE, Taiwan: TWN
```josn      {
      "displayName": "Chateau d'Ax",
      "id": "",
      "locationSet": {"include": ["ao", "be", "ca", "cn", "hr", "fx", "de", "gp", "hk", "it", "mt", "mq", "mu", "ma", "mz", "prt", "pt", "re", "sg", "si", "es", "ch", "twn", "tn", "us", "vn"]},
      "tags":{
        "brand": "Chateau d'Ax",
        "name": "Chateau d'Ax",
        "brand:wikidata": "Q100249791",
        "shop": "furniture"
      }
    }```
Thanks

**Comment by Identitaet** [comment]
1. Yes

2.
Taiwan is just TW
Reunion Island is RE
and the other ones seem to just be duplicates due to translation in Itallian
Portogallo = Portugal with the country code PT
Mozambico = Mozambique with the country code MZ

**Comment by joey2031** [comment]
Thanks!  Just submitted a PR. If there is anything I missed just let me know! Have a great day.

**Comment by bhousel** [comment]
Thanks @joey2031 !

I keep these pages bookmarked to lookup the codes:

code | url
--- | ---
Countries / ISO 3166-1 | https://en.wikipedia.org/wiki/List_of_countries_by_United_Nations_geoscheme
Regions / M.49 |  https://en.wikipedia.org/wiki/UN_M49

Sometimes it can be easier to use the region codes instead of adding a whole lot of country codes.  Either way is fine.

**Comment by pyrog** [comment]
Thanks guys 😃
