### ISSUE TITLE
Use GitHub actions to run npm build

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4429]
This might allow us to get rid of all the hassle with multipl people editing etc.

**Comment by bhousel** [comment]
Sorry, but I'm pretty against automating `npm run build`.  I've never seen this approach work well in practice, and the build process produces useful warnings and generates ids.  It's a script that takes seconds to run, so I don't mind doing it whenever I'm touching the project.

**Comment by Identitaet** [comment]
okay seems reasonable
And it hasn't cause big issues
