### ISSUE TITLE
add Reál

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4443]
Hi, this is will be another easy entry. Reál is a Hungarian retail chain:
- https://real.hu/
- https://hu.wikipedia.org/wiki/Re%C3%A1l_Hung%C3%A1ria_%C3%89lelmiszer_Kereskedelmi_Kft.
- http://overpass-turbo.eu/s/YUm (~270 shops in Hungary on the map)

**Comment by shubh710** [comment]
Hi @debyos 
I would like to work on this, I might require some guidance though.
Thanks.

**Comment by Adamant36** [comment]
> I would like to work on this, I might require some guidance though.
Thanks.

There's a guide on how to do things in the contributing file 
https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md

If you have any specific questions feel free to ask.

**Comment by shubh710** [comment]
Hi @Adamant36,
Sorry but I will not be able to work until weekend.
Please assign this to someone else if someone can work on it.
Thanks

**Comment by Adamant36** [comment]
No worries. We don't really assign things to people anyway. So, feel free to work on it or anything else when you have the time. Otherwise, someone else will do it eventually.

**Comment by debyos** [comment]
Hi,
thanks for doing it. I can't code, nevertheless, I can help you with information from the field.
Cheers

**Comment by amous4822** [comment]
It's a Hungarian retail company. Which file should I add it in ?

**Comment by amous4822** [comment]
please review and revert back. 
Thanks

**Comment by amous4822** [comment]
please review and revert back.
Thanks.
