### ISSUE TITLE
Add Burger Street

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4450]
American fast food burger and sandwich chain. 

cuisine=burger;sandwhich

https://en.wikipedia.org/wiki/Burger_Street
https://www.wikidata.org/wiki/Q4998556

**Comment by vandana1499** [comment]
Will u describe more ?

**Comment by Adamant36** [comment]
So, it would go in the fast food file. 

The code would be something like 

`{
  "brands/amenity/fast_food": [
    {
      "displayName": "Burger Street",
      "locationSet": {"include": ["us"]},
      "tags": {
        "amenity": "fast_food",
        "brand": "Burger Street",
        "brand:wikidata": "QQ4998556",
        "brand:wikipedia": "en:Burger Street",
        "cuisine": "burger;sandwhich",
        "name": "Burger Street",
        "takeaway": "yes"
      }
    },`

**Comment by Adamant36** [comment]
Btw there's a guide on how to add entries in the contributing file here https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md

**Comment by vandana1499** [comment]
@Adamant36 have u already assigned this yo @pushkar1393 ?

**Comment by Adamant36** [comment]
Closed in #4468

@vandana1499 we don't really assign things to people. It's kind of based on whoever decides to do the PR for it. That said, if you want to do a PR for something else that doesn't have yet feel free to. I'll probably open some new issues soon here also.
