### ISSUE TITLE
npm build strips matchnames

### ISSUE THREAD

**Issue by mneko** [osmlab/name-suggestion-index#4502]
This might just be user error, but when I `run build` after adding new brands, it removes the matchNames I added, and I have to readd them every time.

**Comment by bhousel** [comment]
> This might just be user error, but when I `run build` after adding new brands, it removes the matchNames I added, and I have to readd them every time.

This is expected, the `npm run build` script removes any matchNames that are considered redundant. 

If a "name" is just a variation on an existing name tag, or a variation in spacing or punctuation or something like that, it will already be indexed by the matcher.
