### ISSUE TITLE
Added wikidata for multiple shops

### ISSUE THREAD

**Issue by b4hub4l1** [osmlab/name-suggestion-index#4526]
Wiki references (brand:wikidata and brand:wikipedia) is missing for few brands

1. M.Видео in shops/electronics.json
2. Infiniti in shops/car.json
3. Jaguar in shops/car.json
4. Vauxhall in shops/car.json

**Comment by bhousel** [comment]
Thanks @b4hub4l1 - no need to add an extra issue you've already sent a pull request.
