### ISSUE TITLE
Coinstar payment terminals

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4528]
I've added [Coinstar](https://github.com/osmlab/name-suggestion-index/commit/8f47c4d38856eedbac6fd13ec958762033b5b214) to Payment Terminals, which is a terminal in which you can pay in coins and have either notes returned or the money paying into an Amazon account or charity donation.

But I just wanted to check if everybody is happy with how it was added? Is "_Payment terminal_" accurate, and would it be better as a nameless entry?

**Comment by bhousel** [comment]
They seem like more of a vending machine to me.  Also, I'd like to see most entries have names unless there is a really good reason not to have them.

**Comment by UKChris-osm** [comment]
If I were to move it to vending_machine.json, what tag should be used for "_vending_"?

**Comment by bhousel** [comment]
Looks like the index has Coinstar now [as a payment terminal](https://nsi.guide/index.html?t=brands&k=amenity&v=payment_terminal#coinstar-8dd7cb) - this is fine 👍 

I added a `"matchTags": ["amenity/vending_machine"],` property in case people have tried tagging them that way too.
