### ISSUE TITLE
update some clothes shop entries

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4542]
some clothes shops need an update

- [x] Inside - seems to be a generic name and should be discarded

- [x] Fashion - seems to be a generic name and should be discarded

- [x] Avenue - stores seem to be closed (bankruptcy) according to wikipedia

- [x] Edgards - seems to be a department store not just for clothes

**Comment by tordans** [comment]
About the closed store: The way I read https://github.com/osmlab/name-suggestion-index/issues/3800 we would keep thin in the NSI; is just has and end_date in wikidata.

Btw, some linkes (wikipedia, wikidata other research) would be helpful IMO.

**Comment by kjonosm** [comment]
> Btw, some linkes (wikipedia, wikidata other research) would be helpful IMO.

Avenue - see https://en.wikipedia.org/wiki/Avenue_(store)
Edgards - see https://en.wikipedia.org/wiki/Edgars_(department_store)

for both Inside and Fashion I cannot find any meaningful google or wikipedia results...hence my note

**Comment by amous4822** [comment]
so should I completely remove Fashion and Inside brands ?

**Comment by Adamant36** [comment]
I assume for Inside this the company your looking for https://inside-shops.com/en_GB
