### ISSUE TITLE
split German insurance offices Provinzial

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4544]
there are two independent insurance companies with that name:

- Provinzial Nordwest, see https://de.wikipedia.org/wiki/Provinzial_NordWest
- Provinzial Rheinland, see https://de.wikipedia.org/wiki/Provinzial_Rheinland

**Comment by tordans** [comment]
Reference to the json: https://github.com/osmlab/name-suggestion-index/blob/eb58fea43b697ed2662a41de090f3aa4b06e5522/data/brands/office/insurance.json#L748-L757

So the new JSON should be:
```
    {
      "displayName": "Provinzial NordWest",
      "id": "provinzial-422e71a", // TODO
      "locationSet": {"include": ["de"]},
      "tags": {
        "brand": "Provinzial NordWest",
        "name": "Provinzial NordWest",
        "brand:wikidata": "Q1778922",
        "brand:wikipedia": "de:Provinzial_NordWest",
        "office": "insurance"
      }
    },
    {
      "displayName": "Provinzial Rheinland",
      "id": "provinzial-422e71a", // TODO
      "locationSet": {"include": ["de"]},
      "tags": {
        "brand": "Provinzial Rheinland",
        "name": "Provinzial Rheinland",
        "brand:wikidata": "Q2114066",
        "brand:wikipedia": "de:Provinzial_Rheinland",
        "office": "insurance"
      }
    },
```

**Location:**
Looking at https://de.wikipedia.org/wiki/Provinzial_Rheinland#/media/Datei:Karte_%C3%96ffentliche_Versicherer_in_Deutschland.png, it should be possible to make the locationSet more specific to only match the green areas for one and the lightblue areas for the other.

Do you agree, @kjonosm ?

**Comment by kjonosm** [comment]
> Do you agree, @kjonosm ?

Yes, that looks great!

**Comment by bhousel** [comment]
reopening, as the latest build put the "Provinzial" item back.. caf0895f

**Comment by bhousel** [comment]
The correct way to fix this is for the 2 Provinzials to have distinct locationSets (specify the regions where they operate with a geojson) and for each entry to also match the generic "Provinzial" somehow, for example in the `short_name` tag or a `matchName` property.

**Comment by bhousel** [comment]
closing, see comments on #4569 
Apparently the companies have completed their merger this year and will all be called "Provinzial" anyway.
