### ISSUE TITLE
discard German optician Die Brille

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4545]
Please discard German optician "Die Brille" from the index. It's a generic name for several independent shops.

**Comment by tordans** [comment]
You refer to this, right? 
https://github.com/osmlab/name-suggestion-index/blob/9e7f1561e8cd7045f5864cf81908bab4050ffb6b/data/brands/shop/optician.json#L108-L117

It does not have a Wikidata and I cannot see a chain in Google either. IMO good to be removed.

I could not find any relevant history about it either (https://github.com/osmlab/name-suggestion-index/blame/b62ac37a1d9b61a2d21b416322aa19ce44e412f1/brands/shop/optician.json).

**Comment by bhousel** [comment]
Looks like it was collected from the OSM planet file recently:
https://github.com/osmlab/name-suggestion-index/blob/be35aaee141a497a8b847a2bbf088474b1869636/dist/collected/names_all.json#L8501
There are 55 POIs in osm tagged with `name=Die Brille` and `shop=optician`

https://nsi.guide/index.html?t=brands&k=shop&v=optician#diebrille-7fb7e9
https://overpass-turbo.eu/s/Zg8

Many of them do seem to have websites:
https://www.die-brille-neuss.de
https://www.die-brille-konz.de
http://www.die-brille-olching.de
https://die-brille-koenigswinter.de

But I agree it doesn't look like they are working together as a brand - just a really common name for a business.
