### ISSUE TITLE
How does the autogeneration of the id field work?

### ISSUE THREAD

**Issue by tordans** [osmlab/name-suggestion-index#4547]
In https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md#id-generated it says 
> id (generated)
Each item has a unique id generated for it. You can leave it out and the build script will generate one automatically.

How does this work in detail?

1. For my edit, I leave the `id: "",` empty.
2. Then I run `npm run build` => The value in my edited file is not changed
How do I get the id value set?

I am missing something – but what is it :-).

**Comment by bhousel** [comment]
> 2\. Then I run `npm run build` => The value in my edited file is not changed
>     How do I get the id value set?

I don't know - `npm run build` should read all the files into the index and write them back out again cleaned up and with identifiers.  Are there build errors?

**Comment by TheDynamicPunk** [comment]
>     1. For my edit, I leave the `id: "",` empty.

I generally remove the whole id tag when adding a brand and then run the command `npm run build` and it generates the id for that brand

**Comment by tordans** [comment]
Thanks for the help. It worked for https://github.com/osmlab/name-suggestion-index/pull/4548, now.

I tried to clarify the docs via https://github.com/osmlab/name-suggestion-index/pull/4553/files. IMO this makes it easier to understand.
