### ISSUE TITLE
Handling displayName for different brands with the same name

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4590]
I have two questions regarding e.g. commit 01ec0dc1eb13ce8e16fbe821ede21ae87a730f61

1. After introducing IDs, is it still necessary to have unique NSI displayName for separate entries with different location sets?
2. Should the NSI displayName correspond to the OSM name tag to avoid confusion?

**Comment by kjonosm** [comment]
found the answers in contributing.md

**Comment by bhousel** [comment]
Great  - yeah display name can be anything, but it should be unique within a category and mostly similar to the name.

> The `displayName` can contain anything, but it should be a short text appropriate for display in lists or as preset names in editor software.  This is different from the OpenStreetMap `name` tag.
>
> By convention, if you need to disambiguate between multiple brands with the same name, we add text in parenthesis.  Here there are 2 items named "Target", but they have been assigned different display names to tell them apart.
