### ISSUE TITLE
current installation instructions fail as osmium installation fails on Ubuntu 16.04 64 bit

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#46]
`npm install`, also with packages listed as required fails. I narrowed down problem to failed osmium installation and reported it at https://github.com/osmcode/node-osmium/issues/93

**Comment by ImreSamu** [comment]
As I see, this is working only with node:0.10

my test file
```Dockerfile
FROM node:0.10
RUN git clone --quiet --depth 1  https://github.com/osmlab/name-suggestion-index.git 
WORKDIR /name-suggestion-index
RUN npm install
WORKDIR /monaco
RUN wget http://download.geofabrik.de/europe/monaco-latest.osm.pbf
RUN node /name-suggestion-index/getRaw monaco-latest.osm.pbf 1
RUN ls -la
RUN cat topNames.json
```

I have modified my test Dockerfile, and
OK:
* `FROM node:0.10`  

ERROR  (`npm info lifecycle osmium@0.1.3~install: Failed to exec install script` )
* `FROM node:4`  
* `FROM node:5`  
* `FROM node:6`
* `FROM node:7`
* `FROM node:8`

Probably the `osmium@0.1.3`  is too old, maybe we need to [upgrade](https://github.com/osmlab/name-suggestion-index/blob/master/package.json#L19) to the latest [node-osmium version](https://github.com/osmcode/node-osmium/releases)

**Comment by matkoniecz** [comment]
Thanks, now it works perfectly!
