### ISSUE TITLE
Add wikidata entries

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#4603]
Here's some Wikidata entries I created or found for existing entries if anyone wants to add them to the index. I'll probably add more to the list as I create or discover them. 

bicycle rental

- [x]  Mi Bici Tu Bici (Q100272303)
- [x]  Villo! (Q2510744)

Cafes

- [x] Baggins Coffee (Q100272631)
- [x] Coffee Culture (Q100272682) - for Coffee Culture New Zealand
- [ ] Tsekh 85 (Q100282507)
- [x] Toast Box (Q100285490)

**Comment by modaserMoj** [comment]
I added all of them in #4607 except for Tsekh 85 because I coudn't find it in the cafe file.

**Comment by Adamant36** [comment]
> I added all of them in #4607 except for Tsekh 85 because I coudn't find it in the cafe file.

Awesome. Thanks. I wonder what the deal with Tsekh 85 was 🤷‍♂️

**Comment by matkoniecz** [comment]
https://overpass-turbo.eu/s/Ztr - Tsekh 85 is not tagged yet or is using a different name in OSM

**Comment by Adamant36** [comment]
> Tsekh 85 is not tagged yet or is using a different name in OSM

I probably accidently pasted it from something else I was working on. So, I'll just close this as complete.
