### ISSUE TITLE
Split "TheBus" in two

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4621]
There are two obviously [distinct clusters](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22network%22%3D%22TheBus%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B%0A%0A%7B%7Bstyle%3A%0Anode%5Bnetwork%3DTheBus%5D%2C%0Away%5Bnetwork%3DTheBus%5D%2C%0Arelation%5Bnetwork%3DTheBus%5D%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%2C%0Away%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%2C%0Arelation%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%2C%0Away%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%2C%0Arelation%5Broute%3Dbus%5D%5Bnetwork%3DTheBus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R) in Overpass; one in USA-Hawaii and one in USA-Maryland. These should be split, and their respective operators should be added. (Perhaps also some geo-fencing in the iD recommendations? I haven't seen how to do that with more precision than country.)

**Comment by michaelblyons** [comment]
> (Perhaps also some geo-fencing in the iD recommendations? I haven't seen how to do that with more precision than country.)

Looks like there's [a GeoJSON for Delaware/Maryland/Virginia](https://github.com/osmlab/name-suggestion-index/blob/main/features/giant_de_md_va.geojson) (with a little bit of WV thrown in). So we could do a `locationSet` that includes the shape for Maryland, and a `locationSet` that includes `us` and excludes the shape for Hawaii... or someone can draw a new shape for Hawaii.

**Comment by bhousel** [comment]
Yep, you got it!  

Notably, the latest country-coder we just upgraded to supports  `"locationSet": {"include": ["us-hi"]},` for just Hawaii.  So we could use that locationSet for the Hawaii "TheBus" and a custom GeoJSON for the Maryland "TheBus" .

**Comment by michaelblyons** [comment]
> Notably, the latest country-coder we just upgraded to supports `"locationSet": {"include": ["us-hi"]},` for just Hawaii. So we could use that locationSet for the Hawaii "TheBus" and a custom GeoJSON for the Maryland "TheBus" .

If it supports US States like that, is there any downside to doing `"locationSet": {"include": ["us-md"]},` for Maryland, too... or for _that_ matter, with replacing the DE/MD/VA/DC shape for `giant-e48415` with
```json
    "locationSet": {
      "include": [
        "us-dc",
        "us-de",
        "us-md",
        "us-va"
      ]
    }
```

There are lots of local transit systems whose geofence could be narrowed like that, unless there's a significant downside.

**Comment by bhousel** [comment]
> If it supports US States like that,

I don't think it does - I think it just supports `us-ak`, `us-hi`, and `conus`.  I'm not totally sure though.
