### ISSUE TITLE
Bluebikes / Blue Cross Mass. overlap?

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4623]
The only "missing data" bicycle rental listed in USA is "Blue Cross Blue Shield of Massachusetts." That's a little suspicious... and upon further investigation, it appears that "BlueBikes" (also in the database, also in Mass.) is sponsored in part by BCBS-Mass., according to the BlueBikes website.

I think these may be the same thing, and one should be placed in the `matchNames` of the other.

**Comment by bhousel** [comment]
I agree, I think they're the same thing - I added the matchName in 4d878725
