### ISSUE TITLE
Meet Fresh missing from index

### ISSUE THREAD

**Issue by BjornRasmussen** [osmlab/name-suggestion-index#4624]
https://en.wikipedia.org/wiki/Meet_Fresh
I tried to add one of these in North Carolina, but it was missing from the index.

**Comment by matkoniecz** [comment]
@BjornRasmussen  Is it always `amenity=restaurant`?

**Comment by BjornRasmussen** [comment]
As far as I know, yes.

**Comment by bhousel** [comment]
I added it.  The index actually already had the `["cn", "tw"]` version, so I added another item for `["au", "ca", "nz", "us"]` regions
