### ISSUE TITLE
D9150 and D9300 in variety_store.json

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4637]
I've just noticed two entries in "_variety_store.json_" listed as **D9150** and **D9300**, both of which return zero results via their respective Overpass Turbo links.

Any objection to them just being removed, or is there a history to them I am not aware off?

**Comment by bhousel** [comment]
Ah yeah these weird entries pop into the index sometimes.  They can be removed.
(I can't find any discussion about it before).

**Comment by UKChris-osm** [comment]
Removed via [088f465](https://github.com/osmlab/name-suggestion-index/commit/088f465646d0e6a7b5e540d7a777e642501aae88)
