### ISSUE TITLE
add Yi Fang Tea/一芳水果茶

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4640]
it has a wikidata entry Q66196395 and a wikipedia page https://zh.wikipedia.org/wiki/%E4%B8%80%E8%8A%B3%E6%B0%B4%E6%9E%9C%E8%8C%B6

I'm mainly unure with the name since they use the 一芳水果茶 name in Taiwan for example and Yi Fang Tea in the UK

**Comment by bhousel** [comment]
> I'm mainly unure with the name since they use the 一芳水果茶 name in Taiwan for example and Yi Fang Tea in the UK

This is ok, I just added 2 items..  We're tracking some other brands like this (Gong Cha, 85°C, etc)

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/118607939-bbbf3500-b7eb-11eb-8c5a-a74a56dcb637.png)

Maybe it have wrong matchName，I will try to fix
