### ISSUE TITLE
NSI Identifier - Wikidata reference

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4648]
Hi @bhousel 

I'm not sure if this would be necessary, but as a lot of Wikidata entries have a reference to the data source, would it be worth considering adding to the build process a reference source back to the NSI web site when a Wikidata entries has "_OSM Name Suggestion Index identifier_" added to it by the build script?

Example: [Greenhalgh's](https://www.wikidata.org/wiki/Q99939079) where I have added an NSI reference.

**Comment by bhousel** [comment]
Interesting - I never thought about adding references before, but the script definitely could do it.  The identifier itself already can be used to generate the url.  @1ec5 what do you think, should we be adding a reference in addition to adding the claim?

**Comment by Identitaet** [comment]
I would like to note that you can also already click the NSi value on wikidata and be transported to the correct part of the nsi site

**Comment by UKChris-osm** [comment]
> I would like to note that you can also already click the NSi value on wikidata and be transported to the correct part of the nsi site

I hadn't noticed that, ops. 

I asked about the reference as I received a PM on OSM asking about some of our NSI Wikidata entries being deleted due to lack of notability, and I'm wondering if adding a reference would protect entries from being deleted?

**Comment by Identitaet** [comment]
![Capture](https://user-images.githubusercontent.com/58372210/98287496-bca61d00-1fa5-11eb-8d1c-66ba40a08e4d.PNG)

**Comment by bhousel** [comment]
<img width="941" alt="Screen Shot 2020-11-10 at 12 35 46 PM" src="https://user-images.githubusercontent.com/38784/98710159-490f6180-2351-11eb-97da-a928d062e97e.png">

I guess we could add a "stated in" reference like how this Quora Topic ID is claimed.

**Comment by UKChris-osm** [comment]
@Identitaet does the inclusion of "_Wikidata property for an identifier that suggests notability_" to the "_OSM Name Suggestion Index identifier_" entry actually provide notability protection for any Wikidata that we create for the NSI though?

The six Wikidata's referenced on the [Wikidata:Requests for deletions](https://www.wikidata.org/wiki/Wikidata:Requests_for_deletions#Q99939344) page all included the "_OSM Name Suggestion Index identifier_" but were still classed as spam by a user - although another user countered this, and they all seem to still be live.

I wasn't sure if we were able to do more to make NSI wikidata's more protected, such as adding a linkable reference?

@bhousel would that be something like "_stated in_" "_Name Suggestion Index_"?

**Comment by Identitaet** [comment]
> @Identitaet does the inclusion of "Wikidata property for an identifier that suggests notability" to the "OSM Name Suggestion Index identifier" entry actually provide notability protection for any Wikidata that we create for the NSI though?
Well it SUGGESTS notability so it's not 100% sure and I still could add the identifier to anything and that'd be false but the idear is (as far as I know) the they assume that if a company has enough entries to be added here it's also notable enough for WD

**Comment by bhousel** [comment]
Ok the sync script will add a reference to our claims now..
```js
      const references = [{ P248: 'Q62108705' }];   // 'stated in': 'name suggestion index'
```
The script is running now, so they should all start getting this reference over the next hour or so.
