### ISSUE TITLE
Aust. Post

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4654]
Currently in the NSI, there is [Aust. Post](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office#austpost-91a3cc) and [Australia Post](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office#australiapost-536bec) listed under **Post Office**, but I think they might be the same thing!

Can anybody else confirm this either way?

**Comment by Identitaet** [comment]
given that all those aust. post locations are in Australia according to overpass this seem to be the case and some even have brand=Australian post and operator=Aust. Post so probably just weir tagging

**Comment by bhousel** [comment]
Seems fine, I just added a matchName for it in 86174325
