### ISSUE TITLE
[GB] Toytown

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#4656]
Could you please add the following brand:

brand=Toytown
brand:wikidata=Q24887651
brand:wikipedia=en:Toytown Stores
name=Toytown
shop=toys

{"include":["gb"]}

**Comment by UKChris-osm** [comment]
Thank you @boothym, added via [cc7d96f](https://github.com/osmlab/name-suggestion-index/commit/cc7d96f95fa326f8d0a0046b0f2d384d89f0b7f7)
