### ISSUE TITLE
Suggestion : store NSI data in the OSM wikibase

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4657]
The OSM wikibase (aka Data Items) is (or will be) the **repository** of OSM keys, tags, concepts…

One don't need to write an issue or a PR, just create a new data item and add properties 😃 

@nyurik

**Comment by bhousel** [comment]
Is there anything actionable for us to do?

**Comment by Identitaet** [comment]
I guess the idea is to expand the wikidata script to also add the nsi entries (and all the tags) into the OSMwikibase ?

**Comment by pyrog** [comment]
First, "discussed" if it could be a good point for NSI project and OSM 😃 
It could avoid a lot of issue… and time waiting for a PR.

But, we could write code for the website to add and edit "brand"…
Or code to convert NSI files to [Quick Statements](https://www.wikidata.org/wiki/Help:QuickStatements) or CSV to import them.
Or do that with a SPARQL query ??

**Comment by bhousel** [comment]
Sorry @pyrog but I still don't really understand what this issue is about.  
I'm happy to push the NSI data to another system with a script, but need some more guidance.

**Comment by nyurik** [comment]
I'm all for storing critical OSM metadata in the data items, but we should discuss all the logistics of that process -- how items are added, if we should have an extra UI for it, how downstream projects consume such information, issue resolution, etc.

**Comment by pyrog** [comment]
> I'm all for storing critical OSM metadata in the data items

Nice 😃 


>  we should discuss all the logistics of that process

👍 Where, here ?

> how items are added ?

* For existing brands, a script is needed to import data from NSI :
  * SPARQL ? 
  * QuickStatements ?
  * python
  * …
  * @nyurik What do you suggest ?
* For new brands :
  *  From the NSI Website ?
  * Manually ?<br/>The "Create a new Item" link is removed from the wiki.<br/>For test purpose, I created the Data Item [Q21418](https://wiki.openstreetmap.org/wiki/Item:Q21418) 😉 

> how downstream projects consume such information
With a SPARQL Query.

Currently JOSM do that to fetch [formatter URL (P8)](https://wiki.openstreetmap.org/wiki/Property:P8).
iD also query Data Items and Wikidata (at least in [iD/modules/services/osm_wikibase.js#L131](https://github.com/openstreetmap/iD/blob/2.17.3/modules/services/osm_wikibase.js#L131))

**Comment by bhousel** [comment]
> how items are added ?

We already use a node.js script to sync up all the NSI items to Wikidata so we'd probably just use that same script (or one just like it) to push our data to OSM's wikibase too.

**Comment by bhousel** [comment]
stale
