### ISSUE TITLE
Cubesmart

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#4665]
I noticed in https://nsi.guide/index.html?t=brands&k=shop&v=storage_rental there is a CubeSmart (with brand and wiki info) and CubeSmart Self Storage. One has location US and the other 001. Are these duplicates or is it supposed to be like this?

**Comment by bhousel** [comment]
> I noticed in https://nsi.guide/index.html?t=brands&k=shop&v=storage_rental there is a CubeSmart (with brand and wiki info) and CubeSmart Self Storage. One has location US and the other 001. Are these duplicates or is it supposed to be like this?

They are duplicates.. What happens is:
- we process the planet file sometimes, and collect common names of things
- if enough people have mapped stores named "CubeSmart Self Storage", that name will be collected and added to NSI.  (new entries start out with with location '001', whole world)

We can remove this duplicate if we add something to the "CubeSmart" item to cause it to also match "CubeSmart Self Storage" - either an alternate `name` tag or a `matchNames` property.

**Comment by bhousel** [comment]
There is some info in the [CONTRIBUTING](https://github.com/osmlab/name-suggestion-index/blob/main/CONTRIBUTING.md#matchnamesmatchtags) guide, but I probably need to update it.
