### ISSUE TITLE
discard Weltladen from the index

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4666]
Should [Weltladen](https://nsi.guide/index.html?t=brands&k=shop&v=convenience&cc=de&inc=true#weltladen-dc43f5) be discarded from the index? It's a shop type (fair trade) not an actual brand. In Germany some shops may share a common branding by a federal association, but they only make up about 50% of all Weltladen shops and there is no common naming of these either. In addition, there are different associations for Weltladen shops in Austria and Switzerland.

**Comment by bhousel** [comment]
I've wondered about these "world shops" too.  If there is a way to distinguish the ones that "share a common branding by a federal association", then it would be great to include them, but otherwise we can probably just filter them out.
