### ISSUE TITLE
missing wikidata on nsi.guide

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4670]
Some brands are shown as incomplete, although there is existing wikidata available, see e.g. [Boels](https://nsi.guide/index.html?t=brands&k=shop&v=tool_hire#boels-d0c09f)

**Comment by UKChris-osm** [comment]
I think this data will be pulled in from Wikidata when "_npm run wikidata_" is run!

**Comment by bhousel** [comment]
> I think this data will be pulled in from Wikidata when "_npm run wikidata_" is run!

Yes it's supposed to - but I looked at the history there and it seems like the last run should have pulled something..

**Comment by UKChris-osm** [comment]
> Yes it's supposed to - but I looked at the history there and it seems like the last run should have pulled something.

Hmm, that's odd. Is there any error catching if the Wikidata servers are overloaded at the time "_npm run wikidata_" is run? Maybe the server couldn't answer the request for data at the time?

**Comment by kjonosm** [comment]
> the last run should have pulled something..

It should have and I've noticed it before. it seems like it also occurs with brands in the shop=tool_hire, shop=trade and shop=travel_agency folders.

**Comment by bhousel** [comment]
I reran it again just now and it seems that all the data is there...
There was an error in the script that I fixed a few days ago in 58c6731e that might have caused a batch of fetches to fail - maybe that was it?

**Comment by kjonosm** [comment]
It seems like in some categories nsi.guide again fails to pull wikidata info, only showing qid, see e.g. [police stations](https://nsi.guide/index.html?t=operators&k=amenity&v=police&cc=de)

**Comment by bhousel** [comment]
> It seems like in some categories nsi.guide again fails to pull wikidata info, only showing qid, see e.g. [police stations](https://nsi.guide/index.html?t=operators&k=amenity&v=police&cc=de)

I did check of a few of these.. For all the ones where it's only showing the QID, it looks like there just isn't any more information on the Wikidata side.  If you find a QID that has more info that you expect to see, let me know!

It would be great for people to improve Wikidata to have more details.  To improve what https://nsi.guide shows, people can add this info to Wikidata:
- English label and description
- P856 Official Website
- P154 Logo Image
- P2013 Facebook ID
- P2002 Twitter ID
- (whatever other social media accounts, we collect but don't pull logos for them)

Also, NSI collects this information whenever I run `npm run wikidata` command.  The command takes about 10 minutes to complete, and I run it a few times a week or more.  So changes that people make on Wikidata might not show up in NSI for a few days.

**Comment by kjonosm** [comment]
Thanks for your explanation!
