### ISSUE TITLE
Duplicated post depot and post office : DPD Q541030

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4674]
* [x] [Post depot](https://nsi.guide/index.html?t=operators&k=amenity&v=post_depot&tt=Q541030)
* [ ] [Post office](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&tt=Q541030)

**Comment by bhousel** [comment]
The Post Depot seems like a duplicate...
But the Post Offices maybe not - they are just named different things in different places.  I agree that Speedy brand should not be linked to DPD wikidata/wikipedia

**Comment by bhousel** [comment]
Ok I removed the duplicates in post depot and the duplicate DPDs in post_office. 
I left "Speedy" w/`name` "Speedy" but updated `brand`/`operator` to be "DPD".  Speedy in Bulgaria uses the DPD logo.
