### ISSUE TITLE
Chronopost

### ISSUE THREAD

**Issue by pyrog** [osmlab/name-suggestion-index#4675]
At leat in Portugal, [Chronopost](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&tt=Q2967313) as moved to DPD.
This company (part of DPD) still keep this name (at least in [France](https://www.chronopost.fr)).

See also #4674 .

**Comment by bhousel** [comment]
OK, I did some research.. In Overpass they are really just concentrated in France:  https://overpass-turbo.eu/s/105R
And they still operate as "Chronopost" there, so I've just limited the location to France.
