### ISSUE TITLE
Add Signorizza

### ISSUE THREAD

**Issue by MatthieuOSM** [osmlab/name-suggestion-index#4686]
French restaurant chain.

https://www.wikidata.org/wiki/Q101603846
No Wikipedia page.

`amenity=restaurant`
`brand=Signorizza`
`cuisine=pizza`
`name=Signorizza`
`outdoor_seating=yes `

Example: https://www.openstreetmap.org/way/732751916

**Comment by kjonosm** [comment]
Some places are tagged as `amenity=restaurant`. What would be the correct tagging?
If they have indoor seating and table service it should rather be tagged as restaurant.

**Comment by MatthieuOSM** [comment]
Let's keep `amenity=restaurant` as in the example I put (from my own survey) there's both indoor+outdoor seating, and of course except during covid 19 you've table service.

**Comment by kjonosm** [comment]
I leave out `outdoor_seating=yes`. This should be verified on the ground.
