### ISSUE TITLE
Add V and B

### ISSUE THREAD

**Issue by MatthieuOSM** [osmlab/name-suggestion-index#4696]
V and B is a French alcohol retailer, also considered as a bar/cellar (I already went in that place, I can confirm it).
In their website they provide some stats: 350 beers, 300 wines, 200 whiskies and 100 rhums references.
You can also purchase online: https://vandb.fr/livraisons.html (takeaway and delivery options)

I'm not a fan of multi-tagging for an activity, as you buy for sure drinks but do not consume it in the same place, should we put as a secondary tag `amenity=bar`?

https://www.wikidata.org/wiki/Q100706329
No Wikipedia page.

`brand=V and B`
`brand:wikidata=Q100706329`
`drink:beer=yes`
`drink:rum=yes`
`drink:whisky=yes`
`drink:wine=yes`
`name=V and B`
`delivery=yes`
`shop=alcohol`
`takeaway=yes`

**Comment by MatthieuOSM** [comment]
Thank you @pyrog for the PR, is it possible to add also `drink:rum=yes` and `drink:whisky=yes`?

**Comment by bhousel** [comment]
> I'm not a fan of multi-tagging for an activity, as you buy for sure drinks but do not consume it in the same place, should we put as a secondary tag `amenity=bar`?

No, it's definitely not an `amenity=bar`.  Just leave it in the `shop=alcohol` category only.

I'd also skip all of the extra tags like `drink:*` and `delivery`.  We don't do this for other brands (we've specifically avoided tags like `sells:*` and `payment:*` - please see #4105 for some previous discussion on this.  These tags would be better suited for a ground survey than a blanket statement that we apply to all 100 of their stores.

**Comment by pyrog** [comment]
>No, it's definitely not an amenity=bar. Just leave it in the shop=alcohol category only.

It's really a type of "bar" (limited to vine and beer?).
But anyway, multi-tagging is not obvious in OSM and it's main activity is to sell alcohol. So that's ok for me 😃 

> I'd also skip all of the extra tags like drink:* and delivery…

Fine, thank you Bryan 😎

**Comment by bhousel** [comment]
> It's really a type of "bar" (limited to vine and beer?).
> But anyway, multi-tagging is not obvious in OSM and it's main activity is to sell alcohol. So that's ok for me 😃

Yes - I originally said it wasn't a bar based on a quick look at their website https://vandb.fr/ - but looking again it does seem like some (all?) of their locations also have a bar. 

If you want, we can add the `amenity=bar` tag too.  Multi-tagging is indeed not well supported in OSM apps, but we do allow it sometimes here in NSI - see #4008 for guidance.
