### ISSUE TITLE
Have build_wikidata.js script fetch *:wikipedia tags

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4716]
I get it - people don't want to add `brand:wikipedia` / `operator:wikipedia` etc tags because they are redundant #4672 

We are adding them anyway because many people expect the OSM tags to be mostly human-readable, and Wikidata tags are not human-readable.  But I can't just leave Pull Requests sitting unmerged because people don't want to supply this tag.  😓 

So I'm thinking of just having the `build_wikidata` script look up missing Wikipedia tags for us.  This approach also has the benefit of catching Wikipedia pages that have been added after the Wikidata pages.

My plan is to write some extremely dumb code to just choose a reasonable Wikipedia tag.  I'm not going to write code to try to guess which Wikipedia page is the best one based on what languages are spoken in what countries and for what items - this is too hard.  

It will not be as good as having a human pick a value, but at least then I won't have to hold up the project for unmerged Pull Requests.

**Comment by UKChris-osm** [comment]
I think this would be a good addition to the build script.

Would the easiest method be, if more than one :wikipedia exists, to pick the first one that existed / was associated with the :wikidata?

Could you maybe add a "note" to any generated :wikipedia tag to highlight "Wikipedia auto-selected via build script", that also shows up on the [web site](https://nsi.guide), as a hint to us that we might want to manually check the selected Wikipedia at a later date?

**Comment by bhousel** [comment]
Ok I built this.. 🎉 
I did a dryrun just now (script does no updates) and it seems to work pretty well.

The actual number of missing wikipedia tags that it catches is pretty small, so I feel confident that I can just look them over when I run the script and adjust anything that looks really wrong.  I think I prefer this approach over adding notes that will probably never get removed.

For what it's worth, each time the `build_wikidata` is run, it finds _a lot_ of stuff that needs attention and I think it would be nice to put these results somewhere for people to see it.  

Most of the warnings are about brands' Facebook or Twitter accounts being suspended, so really anybody could go to the Wikidata pages and remove or fix these.

**Comment by UKChris-osm** [comment]
On the nsi web site, do the brackets (10/15) for example, refer to 10 of the 15 entries having wikidata tags (meaning 5 are missing), or do they also refer to missing facebook / twitter data?

**Comment by bhousel** [comment]
"Each category displays a count of brands **"(complete / total)"**, where "complete" means the brands have been matched to a Wikidata identifier and a logo."

So it's only considered "complete" if it has a Wikidata tag and the Wikidata page has some kind of logo (commons logo, or Facebook or Twitter account).  I know this is a bit weird - maybe there is a way to make the description clearer or the numbers more useful?

**Comment by UKChris-osm** [comment]
No, I think the text is clear, I just wanted to see if this had changed at all with your edits :)

Does this mean that if a Facebook / Twitter account is now found to be suspended, would this counter update accordingly to reflect that?

> I think it would be nice to put these results somewhere for people to see it.

Perhaps the place where the logo is previously shown on the NSI web site could be replaced with a question mark icon to indicate something that used to be available here is no longer accessible, as a hint / invitation to open up the Wikidata page itself to check?

**Comment by bhousel** [comment]
>For what it's worth, each time the build_wikidata is run, it finds a lot of stuff that needs attention and I think it would be nice >to put these results somewhere for people to see it.
>
>Most of the warnings are about brands' Facebook or Twitter accounts being suspended, so really anybody could go to the >Wikidata pages and remove or fix these.

I pasted the output of this script into a gist:  https://gist.github.com/bhousel/de4fddf31dbef99daa6e700f2f4264bb
I'm kind of amazed that the "just lookup `*:wikipedia` tags" code worked as well as it did 😆 

> Does this mean that if a Facebook / Twitter account is now found to be suspended, would this counter update accordingly to reflect that?

Yes, the numbers would update.  `build_wikidata.js` updates [`dist/wikidata.json`](https://raw.githubusercontent.com/osmlab/name-suggestion-index/main/dist/wikidata.json).  Then nsi.guide react code calculates those numbers based on whatever it finds in `dist/wikidata.json`

> Perhaps the place where the logo is previously shown on the NSI web site could be replaced with a question mark icon to indicate something that used to be available here is no longer accessible, as a hint / invitation to open up the Wikidata page itself to check?

Maybe, but we'd have to change some things somehow.  Currently if the item doesn't have a facebook/twitter anymore, those things just don't get put into `dist/wikidata.json`.
