### ISSUE TITLE
Filter out "Mohren-Apotheke"

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4723]
[Mohren-Apotheke](https://nsi.guide/index.html?t=brands&k=amenity&v=pharmacy&cc=00#mohrenapotheke-f5140f) is not a brand, chain or franchise.

**Comment by bhousel** [comment]
whoa interesting, TIL:  https://translate.google.com/translate?sl=auto&tl=en&u=https://de.wikipedia.org/wiki/Mohrenapotheke
