### ISSUE TITLE
Filter out "Dhaba" restaurant

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4730]
[Dhaba](https://nsi.guide/index.html?t=brands&k=amenity&v=restaurant&cc=00&inc=true#dhaba-2fabb0) is more of a restaurant type than an actual brand, see [Wikipedia](https://en.wikipedia.org/wiki/Dhaba)

**Comment by TheDynamicPunk** [comment]
They're both! Although more prcisely **'Dhaba by Claridges'** is a restaurant chain and '**Dhaba**' alone is a restaurant type.

**Comment by bhousel** [comment]
It doesn't seem like there are very many of the "Dhaba by Claridges" restaurants ([website](https://dhaba1986.com/
)), so I'm just going to filter it out from NSI for now.
