### ISSUE TITLE
Filter out "independent" entries

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4732]
see [here](https://nsi.guide/index.html?t=brands&tt=independent)

**Comment by Adamant36** [comment]
Just giving one of the tags a quick look on OverPassTurbo I found https://www.yourindependentgrocer.ca/. So, likely it would be good to check all of them well before filtering them out to make sure there aren't actually brands somewhere called "Independent."

**Comment by kjonosm** [comment]
Yes, within the shown examples there are two brands that we should keep. I would only filter out:

- [ ] "Independent" [fuel stations](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=independent)
- [ ] "Independent" [motorcycle shops](https://nsi.guide/index.html?t=brands&k=shop&v=motorcycle&tt=independent)
- [ ] "Independent" [kiosks](https://nsi.guide/index.html?t=brands&k=shop&v=kiosk&tt=independent)
- [ ] "Independent" [convenience stores](https://nsi.guide/index.html?t=brands&k=shop&v=convenience&tt=independent)

It also looks like someone already deleted lots of `name=Independent` tags. According to [Overpass](https://overpass-turbo.eu/s/10A0) there are currently only 50 features left in OSM, some of them with a dedicated `nobrand=yes` tag.
