### ISSUE TITLE
use network tag with bicycle-sharing

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4736]
Continue discussion from #4734

[OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental) recommends/documents using `network=*` instead of `brand=*` when tagging `amenity=bicycle_rental` stations.

Is there a way to check which tag is used more often with regard to bicycle-sharing?

**Comment by kymckay** [comment]
According to https://taginfo.openstreetmap.org/tags/amenity=bicycle_rental#combinations

`network=*` has significantly more uses in combination

**Comment by bhousel** [comment]
Hmm that's kind of frustrating.  We moved it from `brand` to `operator` back to `brand`.  It's really `network`?  I sort of get why people would say that, but it's very unintuitive to me.

I can switch it over to be in the `transit` tree the next time I reprocess the planet, but we currently are only collecting `network` in combintion with `power` and `route`, not `amenity`.

**Comment by kjonosm** [comment]
`amenity=car_sharing` might have a similar issue. for some reason taginfo doesn't show the numbers...

**Comment by bhousel** [comment]
Yeah I will try to process another planet soon.. If I knew and had it set up already, the data would be in [`dist/collected/networks_all.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/collected/networks_all.json)

**Comment by peternewman** [comment]
The main London hire bike scheme has the whole set, network, brand and operator!:
https://github.com/osmlab/name-suggestion-index/blob/fd5e3e886d90390b00ec44e6b51945dd2e305172/data/brands/amenity/bicycle_rental.json#L1526-L1549

**Comment by kjonosm** [comment]
[`dist/collected/networks_all.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/collected/networks_all.json) now contains around 260 `bicycle_rental` networks.
Is there a way to automatically merge these into [`data/brands/amenity/bicycle_rental.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json)?

**Comment by bhousel** [comment]
> [`dist/collected/networks_all.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/collected/networks_all.json) now contains around 260 `bicycle_rental` networks.
> Is there a way to automatically merge these into [`data/brands/amenity/bicycle_rental.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json)?

I'm not sure.. from #4767 it sounds like we maybe shouldn't do this after all.

Santander Brunel and Santander Swansea both have `network=nextbike`, so I think we can't use `network` as an identifying tag for bicycle rentals.

**Comment by kjonosm** [comment]
Can #4767 be summarized as `brand=*` being the prioritized key to identify the bike sharing system with `network=*` and `operator=*` as optional extensions?

**Comment by bhousel** [comment]
> Can #4767 be summarized as `brand=*` being the prioritized key to identify the bike sharing system with `network=*` and `operator=*` as optional extensions?

Yes, you phrased it much better  👍

**Comment by kjonosm** [comment]
@bhousel Thanks for your clarification!

Many entries in [`data/brands/amenity/bicycle_rental.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json) include a `name=*` tag identical to `brand=*`.

1. Should that be left as is?
2. Should the `name=*` tag be deleted?
3. Should the `name=*` key be replaced by the `network=*` key?

**Comment by bhousel** [comment]
> Many entries in [`data/brands/amenity/bicycle_rental.json`](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json) include a `name=*` tag identical to `brand=*`.

I think this depends on how local mappers want to map these?
For example in NYC, Citi Bike docks tend to be named according to what street they are on. 
These should probably not have a `name` tag.

<img width="369" alt="Screen Shot 2020-12-14 at 2 37 03 PM" src="https://user-images.githubusercontent.com/38784/102127007-e7dc2180-3e19-11eb-9053-1adf8129f4ac.png">

**Comment by kjonosm** [comment]
I added all items collected by the `network=*` tag to `bicycle_rental.json`.

I am still unsure about whether to treat companies that run and/or provide bicycle schemes/systems like [Nextbike](https://en.wikipedia.org/wiki/Nextbike), [Cyclocity](https://en.wikipedia.org/wiki/JCDecaux#Bicycle_rental_systems), [BCycle](https://en.wikipedia.org/wiki/BCycle) etc. as `network=*` or `operator=*` only.

For now I just tagged them as operator.
