### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4739]
From what I understand, at the moment, whenever anybody runs an NSI command, such as "_npm run build_", "_npm run wikidata_" or "_npm run dist_", these actions are performed on the individuals local computer, having installed GitHub and NPM / Node.js locally, with the results then uploaded / merged back into this repository?

If that's correct, are the above commands something that could be moved over to Git Actions, which are then performed on GitHub's own servers, or have I misunderstood what Git Actions are?

**Comment by bhousel** [comment]
> If that's correct, are the above commands something that could be moved over to Git Actions, which are then performed on GitHub's own servers, or have I misunderstood what Git Actions are?

You're correct, but there are lots of reasons why I don't want to do that.  Nobody would see the warnings/errors produced, and I'm not comfortable having a bot check in broken stuff.  I'm much happier to have a human running a script and being able to judge the health of the project and data.

**Comment by UKChris-osm** [comment]
Understandable reasoning 👍
