### ISSUE TITLE
Flags 🇺🇳

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4745]
I have some free time while I wait for the planet to download, so I'm going to add a tree for `flags`.
These are features in OSM that map nicely to Wikidata - @1ec5 has already done all the hard work [here](https://wiki.openstreetmap.org/wiki/User:Minh_Nguyen/Tagsets/Flags).  👏 

For our purposes 
k/v will be `man_made/flagpole` - https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dflagpole
and n will be `flag:name` - https://wiki.openstreetmap.org/wiki/Key:flag:name

Yarrr! 🏴‍☠️

**Comment by bhousel** [comment]
Also, some things I forgot to mention
- As of today there isn't enough seed data in OSM to collect `flag:name` from OSM planet files (see [taginfo](https://taginfo.openstreetmap.org/keys/?key=flag%3Aname#values)).  These will be much easier to map eventually when NSI can generate editor presets for them.
- I'm just going to set all the `locationSets` to `{ include: ['001'] }` - any flag can validly be flown anywhere in the world.

**Comment by Identitaet** [comment]
so I'd assume for trees we're going to use 
`species=[latin term of plant]`
`species=Acer pseudoplatanus`

 and 

`species:wikidata=Q156944`

?

also will you be looking for genus as well with trees ?

**Comment by bhousel** [comment]
@Identitaet people have proposed species tagging before, and we may do it someday, but this issue is about flags. 🏴 
Species tagging is infinitely complicated, but flags are easy as there are only a few hundred of them.

**Comment by Identitaet** [comment]
oh wait I misread a tree for flags as trees OR flags

**Comment by 1ec5** [comment]
> flags are easy as there are only a few hundred of them

[This Wikidata Query Service query](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fflag%20%3FflagLabel%0A%20%20%3Fclass%20%3Ftype%0A%20%20%3Fsubject%20%3FsubjectLabel%0A%20%20%3Fimage%0AWHERE%20%7B%0A%20%20%23%20Flags%20or%20flag%20designs%0A%20%20%3Fflag%20wdt%3AP31%2Fwdt%3AP279%2a%20wd%3AQ14660%3B%20%23%20substitute%20Q69506823%20for%20flag%20designs%0A%20%20%20%20%20%20%20%20wdt%3AP31%20%3Fclass.%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%23%20Map%20common%20flag%20subclasses%20to%20flag%3Atype%20values%0A%20%20%20%20VALUES%20%28%3Fclass%20%3Ftype%29%20%7B%0A%20%20%20%20%20%20%28wd%3AQ186516%20%22national%22%29%0A%20%20%20%20%20%20%28wd%3AQ22807280%20%22regional%22%29%0A%20%20%20%20%20%20%28wd%3AQ97486724%20%22regional%22%29%20%23%20county%0A%20%20%20%20%20%20%28wd%3AQ21850100%20%22municipal%22%29%0A%20%20%20%20%20%20%28wd%3AQ97486760%20%22municipal%22%29%20%23%20township%0A%20%20%20%20%20%20%28wd%3AQ602300%20%22military%22%29%0A%20%20%20%20%20%20%28wd%3AQ27077627%20%22military%22%29%20%23%20naval%0A%20%20%20%20%20%20%28wd%3AQ83302753%20%22religious%22%29%0A%20%20%20%20%20%20%28wd%3AQ74051479%20%22advertising%22%29%20%23%20commercial%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fflag%20wdt%3AP1268%20%3FrepresentedEntity.%0A%20%20%7D%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fflag%20wdt%3AP131%20%3FadministrativeEntity.%0A%20%20%7D%0A%20%20%23%20Wrap%20this%20bind%20statement%20in%20an%20optional%20block%20to%20find%20more%20flags%20that%20need%20better%20tagging%20in%20Wikidata.%0A%20%20BIND%28COALESCE%28%3FrepresentedEntity%2C%20%3FadministrativeEntity%29%20AS%20%3Fsubject%29%0A%20%20FILTER%20BOUND%28%3Fsubject%29%0A%20%20%0A%20%20%23%20Get%20the%20flag%E2%80%99s%20image%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Fflag%20wdt%3AP18%20%3Fimage%3B%0A%20%20%20%20%20%20%20%20%20%20p%3AP18%20%3FimageStatement.%0A%20%20%20%20%23%20As%20long%20as%20it%E2%80%99s%20an%20SVG%20image%20and%20not%2C%20say%2C%20a%20photo%20of%20a%20flag%0A%20%20%20%20FILTER%28STRENDS%28STR%28%3Fimage%29%2C%20%22.svg%22%29%29%0A%20%20%20%20%23%20Excluding%20statements%20about%20former%20flag%20designs%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%0A%20%20%20%20%20%20%3FimageStatement%20pq%3AP582%20%3FimageEndTime.%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22%20%7D%0A%7D%0AORDER%20BY%20%3Ftype) returns the name, type, subject, and image of about 4,200 flags in Wikidata, not all of which have been tagged in OSM yet. It only returns freely licensed images from Wikimedia Commons; there’s also a [non-free image URL property](https://www.wikidata.org/wiki/Property:P6500), but there’d be no guarantee about the quality of those images, licensing issues aside.

**Comment by 1ec5** [comment]
> and n will be `flag:name`

How will the index handle the fact that `flag:name` is supposed to be in the local language? Would that part of the feature be localizable? Unlike with brands, flag names tend to have just as many translated names as the represented places or organizations would. For what it’s worth, `flag:name` is mostly intended to be a fallback for when there’s no Wikidata entity, though it’s harmless in cases where there is a Wikidata entity.

**Comment by bhousel** [comment]
> > flags are easy as there are only a few hundred of them
> 
> [This Wikidata Query Service query] returns the name, type, subject, and image of about 4,200 flags in Wikidata,

Awesome!  I just took a look... Maybe we can narrow it down and grab just the country/region/military ones?   
4200 is a lot..(but still a lot more managable than all species)

**Comment by bhousel** [comment]
> How will the index handle the fact that `flag:name` is supposed to be in the local language? Would that part of the feature be localizable?

I wasn't expecting to localize it, but we can pick whatever we want that tag to contain (and we can add `matchName` for variants that we want a validator to match)

**Comment by bhousel** [comment]
OK, the flags we have are on nsi.guide now, but looks like the convention is to use P18 "image" , so I'm reopening this because I need to:

- [ ]  update `build_wikidata.js` script to grab P18 "image" instead of P154 "logo image"   (for flags)
