### ISSUE TITLE
Clean up the police

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4751]
My favorite JSON in the project is currently

```jsonc
    {
      "displayName": "Police",
      "id": "police-d00fc1",
      "locationSet": {"include": ["001"]},
      "tags": {
        "amenity": "police",
        "operator": "Police"
      }
    },
```

but there are plenty of others similarly suspicious:

- Police Nationale
- Policía Nacional
- Polizia (maybe false-positive? Limited to Italy, but there are more-specific options for Italy right there)
- Several acronyms (e.g. PSP) suggested for `001`

**Comment by michaelblyons** [comment]
Actually _now_ my favorite JSON in the project is in `post_offices.json`...

```jsonc
    {
      "displayName": "???",
      "id": "d41d8c-91a3cc",
      "locationSet": {"include": ["001"]},
      "tags": {
        "amenity": "post_office",
        "brand": "???",
        "name": "???",
        "operator": "???"
      }
    },
```

**Comment by bhousel** [comment]
> ```js
>  "displayName": "???",
> ```

haha I know, I saw that too.. ❓

**Comment by UKChris-osm** [comment]
>  "displayName": "???",

Is this not the Post Office brand created by the _Black Eyed Peas_ when they were asking where [all the love was](https://feminismandreligion.files.wordpress.com/2019/10/where-is-the-love-1280x720.jpg) 👍
