### ISSUE TITLE
Sort regional flags by country code in displayName?

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4761]
Should we rename "Alaska" to (eg) "us/Alaska" ?

## Pros

- Grouping territories looks nice.
- Easier to find others if you're unfamiliar with a place.
- Easier to see if a state is missing. (Only relevant in the JSON itself. On the site, you can just search for them.)

## Cons

- Religious flags, Military flags, Org flags are not grouped, unless we do something with them, too. Eventually this becomes ludicrous.
- "us/Alaska" may not be next to "United States"
    + That leads us down the path of "us/United States" which seems silly for (eg) "vt/Vatican City"

**Comment by bhousel** [comment]
Maybe?  I haven't thought much about organization yet for big categories.

Also we have over 1400 bus lines and over 800 banks, so there are a few other categories with a lot of items in them.

**Comment by bhousel** [comment]
I ended up writing some code to keep this file sorted by country code, and I agree it's a lot nicer to work with 👍

**Comment by ArloJamesBarnes** [comment]
> Only relevant in the JSON itself. On the site, you can just search for them.

Speaking of the website, and I'm going back and forth on whether this should be a new issue: The only subcategory to https://nsi.guide/index.html?t=flags will be https://nsi.guide/index.html?t=flags&k=man_made&v=flagpole, right)? So perhaps using the value of flag:type (until something better is found) as a sort key _there_ could help?

> which seems silly for (eg) "vt/Vatican City"

Q237 is va :vatican_city:
