### ISSUE TITLE
Park operators

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4769]
What's the chance of getting an `operators/leisure/park.json`? Is it as simple as adding that file?

**Comment by bhousel** [comment]
That's a good suggestion.  It's not hard to do, but we aren't yet collecting operators for leisure/park.

You can see in [operators_all.json](https://github.com/osmlab/name-suggestion-index/blob/main/dist/collected/operators_all.json) the sorts of things we do collect already.  Like police and fire services, many larger cities park and school systems might be worth adding items for.

**Comment by michaelblyons** [comment]
USA has 62 national parks (my main target), as well as a spread of state parks. This in additional to larger counties and/or municipalities.

**Comment by UKChris-osm** [comment]
Would this sort of thing be "_operator/boundary/national_park.json_"?

**Comment by michaelblyons** [comment]
> Would this sort of thing be "_operator/boundary/national_park.json_"?

That is actually a good point. I did not know about those. However... I now would like _both._ (I'm difficult like that. 😉) The US National Park Service controls some huge swathes of land that belong in `boundary=national_park`, but also some [smaller bits](https://www.openstreetmap.org/relation/11158003#map=14/38.8867/-77.0344) that are tagged as `leisure=park`.

Also, the more I dig into this, the weirder it gets. There are 62 "National Parks," but there are at least 400 places in the "National Park System" that seem to be operated by NPS.

**Comment by bhousel** [comment]
> That is actually a good point. I did not know about those. However... I now would like _both._ (I'm difficult like that. 😉) The US National Park Service controls some huge swathes of land that belong in `boundary=national_park`, but also some [smaller bits](https://www.openstreetmap.org/relation/11158003#map=14/38.8867/-77.0344) that are tagged as `leisure=park`.

This is ok, we can support both here.  Just like "Tesco" can be a brand in both `amenity/fuel` or a `shop/supermarket`, "National Park Service" can be an operator in `leisure/park` or a `boundary/national_park`.

**Comment by UKChris-osm** [comment]
Maybe a "_matchGroup_" for both would be the best thing?

**Comment by TheAdventurer64** [comment]
This would also be good for parks owned by the government. I have a tagging schema for Honolulu parks which I think would be good in this situation: 

https://www.openstreetmap.org/way/218680183

https://www.openstreetmap.org/way/161726419

**Comment by zekefarwell** [comment]
Starting to collect a canonical list of operators for parks and other public land seems like a great idea if it feels appropriate for the NSI.  Definitely complicated though.  There are many land management agencies/organizations and the types of areas they manage can often overlap. For example, I've just learned that management of US National Monuments is spread across five different agencies (National Park Service, US Forest Service, US Fish and Wildlife Service, Bureau of Land Management, and the National Oceanic and Atmospheric Administration).
