### ISSUE TITLE
Research needed for: amenity/fuel|Drummed Fuel

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#479]
#### :thinking: We need help deciding what to do with "amenity/fuel|Drummed Fuel"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fuel|Drummed Fuel` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fuel|Drummed Fuel`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fuel|Drummed Fuel`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
I did some research on this. They are all mapped in a certain area of Indonesia by the same editor. So I sent him a message and he said its a description of the type of fuel tank, not a business or anything. Given that, I guess Drummed Fuel can be removed from the index.

**Comment by Adamant36** [comment]
same goes for the entry for minipump.
