### ISSUE TITLE
Migrate Travis CI -> GitHub Actions

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4790]
I haven't done this before, so today I'm going to try it.

**Comment by UKChris-osm** [comment]
I was looking into this as I noticed that Travis seems to take a long time to process, but it all went over my head again :)

**Comment by tas50** [comment]
Traditionally Travis was free to OSS projects. They just recently converted all the OSS accounts to trial accounts with a limited number of testing credits.

**Comment by UKChris-osm** [comment]
Ah that makes sense, thanks @tas50 👍

**Comment by bhousel** [comment]
This was done!
