### ISSUE TITLE
Show "new" items on nsi.guide

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4794]
Just out of interest, is there any scope (or current ability) for adding a flag on the NSI web site that will highlight any entries added in the latest planet run? I know there is the "_incomplete_" checkbox, but I was hoping to limit the search to just the latest planet additions.

My reason for this is because if an entry only recently appears, it tells me that it's becoming big enough to matter to us, and if that's only just happened, being able to check and correct it quickly would be beneficial.

I think this would be handy as a quick way for anyone to be able to see what entries have only just appeared, so as to check for missing data (wiki*) or possible matches that already exist ([c7cedaf](https://github.com/osmlab/name-suggestion-index/commit/c7cedafa5356c011c179f5ae09374403dcb51bc2))

My theory of how it could work would be the creation of "_/data/planet-latest.json_" which would be wiped clean before each run, and then be populated with the latest planet entries, giving people a few days between each planet run to review the latest additions on the NSI web site.

**Comment by bhousel** [comment]
It's a good idea, but I'm not really sure how I'd do it.  I think it would be great to flag some items as "new".  Even if it was just "added within the last month" that would be useful.

Items can also get added to the index because people add them manually, not just because of the planet file, so I'd want to catch those also..

**Comment by UKChris-osm** [comment]
Maybe the addition of a datestamp to "_npm run build_" that adds the date to entries (e.g. "firstbuilddate": "2020-12-14") that don't have one, so at least we have a date of when the first pass of "_npm run build_" was run?

**Comment by kjonosm** [comment]
I think it would be a good idea to not only highlight "new" items but all items with a 001 locationSet and no wikidata tags. This would cover all new items and also point to items that need some more work.

**Comment by bhousel** [comment]
> I think it would be a good idea to not only highlight "new" items but all items with a 001 locationSet and no wikidata tags. This would cover all new items and also point to items that need some more research.

The "incomplete" checkbox does at least cover these items..

**Comment by bhousel** [comment]
I think I'm just going to close this, since "incomplete" will always catch stuff that is "new"
