### ISSUE TITLE
Add flags for French regions

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [osmlab/name-suggestion-index#4795]
I've prepared a JSON file containing information for the flags for the French regions. 

Since my system is not able to run the required npm version, I'm posting the JSON here for someone else to append into `data/flags/man_made/flagpole.json` (followed by `npm run build` and pull request of course).

[regions_françaises.prettyprint.zip](https://github.com/osmlab/name-suggestion-index/files/5683116/regions_francaises.prettyprint.zip)

**Comment by UKChris-osm** [comment]
Hi @daniel-callejas-sevilla,

I see you have already forked this repository and created a "_.json_" file under the flags folder. If you copy that data into the "_flagpole.json_" file, maybe at the end, but still within the:

{
  "flags/man_made/flagpole": [
    ... existing flag data ...
    ... your new flag data ...
  }
}

... then you can create a pull request of your fork online (no need for npm) and if we can accept it, someone here could run npm run build after the merge.
