### ISSUE TITLE
Operational area of the British Transport Police is too small

### ISSUE THREAD

**Issue by davidpnewton** [osmlab/name-suggestion-index#4800]
The BTP has a scope of gb-eng at the moment in the NSI. It also operates in Wales and Scotland so the scope tag should be updated to include gb-wls and gb-sco. The only bit of the UK it doesn't operate in is Northern Ireland.

https://www.btp.police.uk/local_npt_teams.aspx

**Comment by UKChris-osm** [comment]
Ops, that may have been my mistake, thank you @davidpnewton, fixed via [3b8562f](https://github.com/osmlab/name-suggestion-index/commit/3b8562f77ad08ef31c039100ddd6fbf4e79d1a80)
