### ISSUE TITLE
ATM operators in the UK

### ISSUE THREAD

**Issue by davidpnewton** [osmlab/name-suggestion-index#4801]
So far it appears that all of the ATM operator entries are the same as those for banks. However at least in the UK there are those organisations which operate ATMs and yet are not banks.

One such organisation is Notemachine.

{
      "displayName": "Notemachine",
      "id": "",
      "locationSet": {"include": ["gb"]},
      "tags": {
        "amenity": "atm",
        "operator": "NMATM",
        "name": "Notemachine",
        "official_name": "Notemachine UK"
      }

They don't appear to have a Wikipedia or Wikidata entry, but they do operate a great many ATMs in the UK that are not associated with a particular bank branch. I have tagged three of them near where I live in the last few days and that's only in part of a medium-sized town.

https://www.notemachine.com/

Their website says they have 11,000 ATMs in operation. They also appear to have a German operation as well, and they own eurochange which is a big bureau de change and does have an NSI entry.

There are other such companies in the UK which operate at a similar kind of scale, as can be seen from the list of LINK (UK interoperability network for ATMs) members:

https://www.link.co.uk/members/members/

It's likely worth having NSI entries for any ATM operators named in that list as in order to be a member of LINK they have to be of a fair size, thus likely potentially appearing as an ATM operator at least hundreds of times in OSM, if not thousands of times like Notemachine.

**Comment by UKChris-osm** [comment]
I've just seen that the current "_atm.json_" is a template file, can additional entries be added to a template file?

**Comment by bhousel** [comment]
> I've just seen that the current "_atm.json_" is a template file, can additional entries be added to a template file?

Yes - the `atm.json` file can contain both template or regular items.

I can add one for Note Machine, but I'm unclear what the value should be. 
We have collected from the OSM planet file with these values for `operator`:

https://github.com/osmlab/name-suggestion-index/blob/677187557da08160f28040195b8d12abf5184dee/dist/collected/operators_all.json#L621-L622

**Comment by bhousel** [comment]
I guess [their own website](https://www.notemachine.com/) can't decide what they are called either.
<img width="314" alt="Screen Shot 2020-12-17 at 1 48 53 PM" src="https://user-images.githubusercontent.com/38784/102529945-a3958f00-406e-11eb-82a5-106d3e4d40d7.png">

**Comment by davidpnewton** [comment]
At least for the ATMs they operate which I have tagged recently their brand is NMATM.

**Comment by bhousel** [comment]
> At least for the ATMs they operate which I have tagged recently their brand is NMATM.

ok, I'll add NMATM in the `short_name` tag so that matches also.

**Comment by davidpnewton** [comment]
I've just created Wikidata article Q104368525 for it.
