### ISSUE TITLE
Add Unit Test

### ISSUE THREAD

**Issue by wafuwafu13** [osmlab/name-suggestion-index#4808]
Hi :)
I've already introduced Unit Test at https://github.com/osmlab/name-suggestion-index/pull/4807. 
I would be grateful if you could see it.

**Comment by bhousel** [comment]
Thanks, I already added #4788 to track adding tests to this project.
I'm more interested in testing the library code that we export (it is used by other projects), but not really interested in testing the components of the react nsi.guide site (which is just for us and we change it sometimes).
