### ISSUE TITLE
Add Abercrombie & Fitch

### ISSUE THREAD

**Issue by robertaustinbell** [osmlab/name-suggestion-index#4812]
Wikidata  https://www.wikidata.org/wiki/Q319344
Wikipedia  https://en.wikipedia.org/wiki/Abercrombie_%26_Fitch
Website  https://www.abercrombie.com/

[shop = clothes](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dclothes)

Name = Abercrombie & Fitch

Brand = A&F

**Comment by bhousel** [comment]
The index has this already:
https://nsi.guide/index.html?t=brands&k=shop&v=clothes#abercrombieandfitch-a7750e
