### ISSUE TITLE
99 speedmart is not a variety_store (MY/SG)

### ISSUE THREAD

**Issue by henkmet** [osmlab/name-suggestion-index#4816]
According to the guide on OSMwiki, a variety store is a store where all (or most) items have the same price. 99 speedmart is not such a store, it's a chain of small supermarkets or convenience stores.

**Comment by bryceco** [comment]
We should change the wiki. That's not the common practice IMO.

**Comment by henkmet** [comment]
In that case, I withdraw my issue here.

**Comment by bhousel** [comment]
Ok, I'll close for now, but you can browse through the categories for similar brands:
- variety store: https://nsi.guide/index.html?t=brands&k=shop&v=variety_store
- convenience store: https://nsi.guide/index.html?t=brands&k=shop&v=convenience

And if you or other local mappers want it to be in a different category we can change it.

Variety Store is a strange category.  In USA we commonly call these "dollar stores", but they don't absolutely use a single price - more that it's a store for random cheap stuff.

**Comment by AkuAnakTimur** [comment]
Sorry to interrupt, but 99 Speedmart is more or less KK Supermart https://nsi.guide/index.html?t=brands&k=shop&v=convenience#kksupermart-3e5671

A changeset discussion pointed me over here: https://www.openstreetmap.org/changeset/96412343

**Comment by bhousel** [comment]
Ah thanks for the link back to #4004.. I forgot that this one keeps coming back.
