### ISSUE TITLE
New pharmacy brand: Pingvin patika

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4819]
Hi there,

Pingvin Patika ('Penguin Pharmacy') is a [chain of more than 40 pharmacies](http://pingvinpatikak.hu/patika-kereso) located in South-Eastern Hungary. About [half of them can be found on OSM as well](http://overpass-turbo.eu/s/11PE).
You can cosider to include it into the brands.
Cheers

_Gábor Babos_

**Comment by UKChris-osm** [comment]
Added "_Pingvin patika_" via [eafc9ab](https://github.com/osmlab/name-suggestion-index/commit/eafc9ab35557fd8bf1e5fecf660f74b5221b84eb), still needs Wikidata!

**Comment by airon90** [comment]
@debyos Please check and add more data, e.g. headquarters location, date of foundation and even social network urls: https://www.wikidata.org/wiki/Q105626461
Website seems to be down, is it correct? If so, why?

**Comment by debyos** [comment]
Hello,
I have seen the Wikipedia entry: it seems perfect.
Cheers
Gábor
