### ISSUE TITLE
New pharmacy brand in Hungary: Szimpatika

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4823]
Dear All,

there is another pharmacy brand in Hungary called [Szimpatika](https://www.szimpatika.hu). It comprises [about 250 pharmacies across the country](https://m.szimpatika.hu/kereso), most of which are independent, i.e. they use the brand (and probably also other services e.g. medicine supply) but they (or, at least, most of them) have their respective owners.
You can consider to include it into the list of pharmacy brands.

I whish you a very happy, virusless new year!
Cheers

Gábor

**Comment by UKChris-osm** [comment]
Added "_Szimpatika_" via [706cd3c](https://github.com/osmlab/name-suggestion-index/commit/706cd3c4291f12bc3d07f2d60a8b382437e6f64d), still needs Wikidata!

**Comment by airon90** [comment]
@debyos Please check if data inserted here are correct and add more: https://www.wikidata.org/wiki/Q105626428

**Comment by debyos** [comment]
Thank you, it seems OK.
