### ISSUE TITLE
New pharmacy brand in Hungary: Alma Gyógyszertár

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4824]
Dear All,

there is another pharmacy brand in Hungary called [Alma Gyógyszertár](https://almapatika.hu/) (apple pharmacy). Currently, it comprises [274 pharmacies across the country](https://almapatika.hu/patika-kereso), most of which are independent, i.e. they use the brand (and probably also other services e.g. medicine supply) but they (or, at least, most of them) have their respective owners.
You can consider to include it into the list of pharmacy brands.

I whish you a very happy, virusless new year!
Cheers

Gábor

**Comment by maxerickson** [comment]
Creating wikidata entries for these brands will speed up making them available in editors. It's a bit easier to do accurately if you speak the language. https://www.wikidata.org/wiki/Q2078880 is an example of a pharmacy chain with quite a lot of statements, I think the label, instanceof (there's values for brands vs company) and maybe country + website are a pretty reasonable start.

**Comment by lekandev** [comment]
I would love to work on this please

**Comment by UKChris-osm** [comment]
@lekandev You're more than welcome to :)

**Comment by airon90** [comment]
@debyos @lekandev Please check if [Wikidata entry for Alma Gyogyszertar](https://www.wikidata.org/wiki/Q105626221) is correct and please add more data if you find something useful (I don't understand Hungarian, sorry)

@UKChris-osm please add the Wikidata item to #4824

**Comment by debyos** [comment]
Hi,
the Alma pharmacies' Wikidata record seems good as well.
Bye & thank you for the work done
Gábor
