### ISSUE TITLE
Harveys Furniture now defunct

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#4825]
See https://en.wikipedia.org/wiki/Harveys_Furniture

**Comment by bhousel** [comment]
Yes, that's ok.. 
We've picked up that information from wikidata in the `dissolved.json` file:
https://github.com/osmlab/name-suggestion-index/blob/ebe203534be36f859a36f3fbe90ef915f71105a4/dist/dissolved.json#L76
