### ISSUE TITLE
New supermarket brand in United States

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4826]
KTA Superstores is a chain of supermarkets. Wikidata page here: https://www.wikidata.org/wiki/Q44361030

**Comment by bryceco** [comment]
6 locations, all on the Big Island of Hawaii

**Comment by TheAdventurer64** [comment]
> 6 locations, all on the Big Island of Hawaii 

7 actually; The store in Kealakekua opened in 2019 and is called KTA Express.
