### ISSUE TITLE
Add Honolulu Police Department

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4827]
Honolulu Police Department is a chain of police stations in Honolulu Hawaii. Wikidata: https://m.wikidata.org/wiki/Q3140166

**Comment by UKChris-osm** [comment]
Added "_Honolulu Police Department_" via [ee07331](https://github.com/osmlab/name-suggestion-index/commit/ee07331faa037ac337d9e90f6fc64ca730443f2b)
