### ISSUE TITLE
Add Teapresso Bar

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4829]
Teapresso Bar is a chain of bubble tea shops based in Hawaii. Wikidata here: https://m.wikidata.org/wiki/Q104606222

**Comment by UKChris-osm** [comment]
Added "_Teapresso Bar_" via [c3c9ed1](https://github.com/osmlab/name-suggestion-index/commit/c3c9ed13423a3c5abde24c9c04b6d661a549cee8).
