### ISSUE TITLE
Burger King Hawaii operator

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#4832]
In my area, Burger King's are operated by Burger King Hawaii. Is there a way to distinguish this?

**Comment by UKChris-osm** [comment]
> Is there a way to distinguish this?

There is, but at the moment is seems Burger King is only based on its "_brand_" data, and not "_operator_" data, so I don't think anything would need changing in this instance!

**Comment by bhousel** [comment]
Agree with @UKChris-osm - we don't need to change anything in NSI, but you can make these changes in OSM itself. 

NSI is really for tags which we believe to be correct everywhere, so that's why we leave out the `operator` tags from the brands.
