### ISSUE TITLE
Revolution Laundry (was: add laundry.json)

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4841]
Currently we only support `shop=dry_cleaning`.
Can someone add `laundry.json` to collect self service laundry shops [`shop=laundry`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dlaundry)?

**Comment by bhousel** [comment]
Thanks for opening this - this one is interesting..
It looks like we specifically exclude this kind of shop, but I don't remember the details why.
https://github.com/osmlab/name-suggestion-index/blob/47661e89ea920a9a40a3fcbb6739b44c32765dab/dist/trees.json#L50


This is what we've collected from the OSM planet:
https://github.com/osmlab/name-suggestion-index/blob/47661e89ea920a9a40a3fcbb6739b44c32765dab/dist/collected/names_all.json#L8518-L8533

As far as I can tell, they are all either generic words or there are a few like "Speed Queen" and "Laverap" which I think are stores which sell washing machines, and they should probably instead be tagged as [`shop=appliance`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dappliance).

**Comment by kjonosm** [comment]
In Germany we have a franchise called Eco-Express ([overpass-link](https://overpass-turbo.eu/s/11Zo), [website](https://www.mein-waschsalon.de)) that lots of (former) students probably know. I don't know about other countries though...

**Comment by kjonosm** [comment]
> "Speed Queen" and "Laverap" which I think are stores that sell washing machines

Actually they are indeed laundry services, see [Speed Queen](https://franchise.speedqueen.com) and [Laverap](http://www.laverap.com) websites.

**Comment by bhousel** [comment]
> Actually they are indeed laundry services, see [Speed Queen](https://franchise.speedqueen.com) and [Laverap](http://www.laverap.com) websites.

cool!, thanks I didn't realize that on first look..
I'll merge in the `launday.json` file now.

**Comment by UKChris-osm** [comment]
How would something like [Revolution Laundry](https://www.revolution-laundry.com/) appear in the index? Still under shop, or maybe as a vending machine?

**Comment by bhousel** [comment]
> How would something like [Revolution Laundry](https://www.revolution-laundry.com/) appear in the index? Still under shop, or maybe as a vending machine?

whoa, I didn't know about those.. 

Here's what I see on [`shop=laundry`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dlaundry) wiki page today:

<img width="400" alt="Screen Shot 2021-01-18 at 9 29 26 AM" src="https://user-images.githubusercontent.com/38784/104927671-b4883780-596f-11eb-823f-8a375ca45946.png">

So it sounds like the guidance used be to map it as a vending machine, but now it's [`amenity=washing_machine`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwashing_machine)
