### ISSUE TITLE
Duplication of ほっともっと?

### ISSUE THREAD

**Issue by venue-map** [osmlab/name-suggestion-index#4847]
[ほっともっと(amenity=fast_food)](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=%E3%81%BB%E3%81%A3%E3%81%A8%E3%82%82%E3%81%A3%E3%81%A8), [ほっともっと(shop=deli) ](https://nsi.guide/index.html?t=brands&k=shop&v=deli&tt=%E3%81%BB%E3%81%A3%E3%81%A8%E3%82%82%E3%81%A3%E3%81%A8)

According overpass all are in Japan,.

**Comment by bhousel** [comment]
Oh that's Hotto Motto.
I'll deduplicate them.. it seems like `amenity=fast_food` is the preferred tagging:

```js
"amenity/fast_food|HottoMotto ほっともっと": 69,
"amenity/fast_food|ほっともっと": 353,
"shop/deli|ほっともっと": 120,
```
