### ISSUE TITLE
ATM can't auto-suggestion in iD editor

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#4849]
when I input ```operator``` or ```name``` correctly in iD and have tag ```amenity=atm```, it won't give me suggestion about ```brand=*```、```brand:wikidata=*```、```brand:wikipedia=*```.

![NOT ANY USEFUL](https://user-images.githubusercontent.com/42690037/103988065-6e411480-51c8-11eb-9f4a-567311188522.png)

It still a single tiny poi, not a chain ATM of a bank.

This problem not only in China region.

**Comment by LaoshuBaby** [comment]
Have those bank info inherit by ATM？

```
{
  "brands/amenity/atm": [
    {
      "templateSource": "brands/amenity/bank",
      "templateTags": {
        "amenity": "atm",
        "operator": "{source.tags.brand}",
        "operator:wikidata": "{source.tags.brand:wikidata}",
        "operator:wikipedia": "{source.tags.brand:wikipedia}"
      }
    },
    ……
  ]
}
```

**Comment by bhousel** [comment]
Yeah the new stuff isn't in iD yet - what they have is almost a year old.
I'm working on this today.

**Comment by LaoshuBaby** [comment]
@bhousel Thank you for reading my stupid problem！

**Comment by LaoshuBaby** [comment]
Emmmm……

Why Sometimes points can't auto-suggest……

I don't know how to find it.

the bank is truly in data

![图片](https://user-images.githubusercontent.com/42690037/104091118-43cd8500-52b6-11eb-9553-86cab2ab7459.png)

but it is truly can't be search and can't auto-suggest
This is a video screenshot

https://user-images.githubusercontent.com/42690037/104091528-e6870300-52b8-11eb-8b8e-b0d2e2a6e895.mp4
