### ISSUE TITLE
TUI France

### ISSUE THREAD

**Issue by Snaxeko** [osmlab/name-suggestion-index#4858]
https://www.tui.fr/

https://nsi.guide/index.html?t=brands&k=shop&v=travel_agency&tt=TUI

**Comment by nuxper** [comment]
Hi @Snaxeko 
What would be the problem with TUI ?
It is present in nsi worlwilde hence covers France.

**Comment by nuxper** [comment]
I'm closing the issue as it's been silent for one month. If I missed something we can reopen it.
