### ISSUE TITLE
Check UPS mail drop boxes

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4866]
I'm feeling mostly good about how mail boxes look in NSI v5, _except for UPS._

UPS looks weird because we use a template to expand all of the post offices into mail drop locations. The post office is branded/named/operated by "The UPS Store" (fine) but the mail drop boxes really should just be branded/named/operated by "UPS"  (which has a different QID from the UPS Store).

I was hoping to avoid this, but it looks like I need to figure out a way to make the templates slightly smarter. We need a way of saying which items to  _not_ expand from the templateSource.  😓 

https://github.com/osmlab/name-suggestion-index/blob/d779cfbf63f3d98d1075755fff267ef9dd429fc7/data/operators/amenity/post_box.json#L2-L10

<img width="350" alt="Screen Shot 2021-01-18 at 10 18 08 PM" src="https://user-images.githubusercontent.com/38784/104983692-46795a00-59db-11eb-9b50-b476635ac73a.png">
<img width="350" alt="Screen Shot 2021-01-18 at 10 18 20 PM" src="https://user-images.githubusercontent.com/38784/104983698-49744a80-59db-11eb-9018-86479fe54639.png">
<img width="350" alt="Screen Shot 2021-01-18 at 10 20 36 PM" src="https://user-images.githubusercontent.com/38784/104983781-745e9e80-59db-11eb-9d6a-87ee8df0c1c7.png">
<img width="350" alt="Screen Shot 2021-01-18 at 10 18 50 PM" src="https://user-images.githubusercontent.com/38784/104983713-5002c200-59db-11eb-8229-dfb8df221b03.png">

**Comment by tas50** [comment]
I just came here to report this one. It's going to cause a lot of issues since iD is suggesting updating actual UPS mailboxes to be UPS Store mailboxes.

**Comment by bhousel** [comment]
I did this!   Template items now support include/exclude patterns that will match against the ids.
I added an exclude for the "upsstore" post office and created an item for "UPS" operated mail boxes:

<img width="350" alt="Screen Shot 2021-01-19 at 5 20 14 PM" src="https://user-images.githubusercontent.com/38784/105100021-a5da7700-5a7a-11eb-818f-53d2da14394e.png">
