### ISSUE TITLE
Duplication of Japanese mobile_phone

### ISSUE THREAD

**Issue by venue-map** [osmlab/name-suggestion-index#4868]
[Softbank](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=softbank)
[docomo](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=docomo)

According overpass all are in Japan,.

**Comment by nuxper** [comment]
Hi @venue-map

Do you know Softbank ?

I understand there are two brands in wikidata for mobile_phone shops:
* SoftBank Telecom (Q7553832)
* SoftBank Shop (Q11315281)
Are both legitimate and distinct retail chains ?

Then there are 258 nodes with just name=SoftBank in openstreetmap. Hence name-suggestion-index automatically creates an entry fot this third brand. Do you think nodes with name=SoftBank are actually part of Q7553832 ? or Q11315281 ? or a third retail network maybe ?

**Comment by venue-map** [comment]
Hi @nuxper -san
Sorry for the late reply.

> I understand there are two brands in wikidata for mobile_phone shops:
> SoftBank Telecom (Q7553832)
> SoftBank Shop (Q11315281)
> Are both legitimate and distinct retail chains ?

The Japanese version of Wikipedia clearly states that "SoftBank Telecom has merged with SoftBank Mobile.".
[ソフトバンク - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%95%E3%83%88%E3%83%90%E3%83%B3%E3%82%AF)
> 2015年4月1日付で、ソフトバンクモバイルがソフトバンクBB、ソフトバンクテレコム（ソフトバンクテレコム販売と逆さ合併した2代目）、ワイモバイルを吸収合併。

By the way, I don't think there was a store for "SoftBank Telecom (Q7553832)" itself.

------
> Then there are 258 nodes with just name=SoftBank in openstreetmap. Hence name-suggestion-index automatically creates an entry fot this third brand. Do you think nodes with name=SoftBank are actually part of Q7553832 ? or Q11315281 ? or a third retail network maybe ?

For "name = SoftBank", the Wikidata for "Q11315281" is correct.
The signboard of "Softbank shop" says "Softbank", so I think that's what it says.

**Comment by nuxper** [comment]
I think I did the required modifications. Is that ok with you @venue-map ?

**Comment by venue-map** [comment]
Hi @nuxper -san.

Thank you for editing.
However, it seems that the data of SoftBank Telecom (Q7553832) remained, so I merged it with SoftBank Shop (Q11315281) and made a pull request here.
