### ISSUE TITLE
UK supermark brand Tesco has no icon?

### ISSUE THREAD

**Issue by TurnrDev** [osmlab/name-suggestion-index#4875]
Not sure if this is related to the NSI or not but the folks on the OSM World discord reckon it might me but... None of the Tesco entries have an icon. How do we resolve this?
![image](https://user-images.githubusercontent.com/11667059/105618975-c0e41880-5de5-11eb-971f-b542a5d53693.png)

Here's some images I could suggest using:
![image](https://user-images.githubusercontent.com/11667059/105618983-d5281580-5de5-11eb-9295-ecf95714dd22.png)
![image](https://user-images.githubusercontent.com/11667059/105618989-dfe2aa80-5de5-11eb-8f2b-e043699af70c.png)
![image](https://user-images.githubusercontent.com/11667059/105618994-e7a24f00-5de5-11eb-83d9-202bbdeb9e86.png)
![image](https://user-images.githubusercontent.com/11667059/105619005-f852c500-5de5-11eb-8310-ff1bc0b119d2.png)
![image](https://user-images.githubusercontent.com/11667059/105619012-07d20e00-5de6-11eb-9c95-4de5a770fbcf.png)

**Comment by bhousel** [comment]
Thanks for reporting @TurnrDev - My guess is that it's just that the data iD is using is many months old.
I'm working on updating it now over on https://github.com/openstreetmap/iD/pull/8305 so it will probably be updated pretty soon.   (I'll leave this issue open for now).

You can also check on https://nsi.guide to see whether the brands have reasonable descriptions and icons.  If an entry is missing an icon, we can add a social media account to it's wikipedia page or a commons image, and we'll pull an icon from there.

**Comment by UKChris-osm** [comment]
It seems Tesco have their Facebook set to be restricted to logged in users only, so that might have caused it, but the Twitter logo and available commons logos seem okay 👍

**Comment by bhousel** [comment]
> It seems Tesco have their Facebook set to be restricted to logged in users only, so that might have caused it, but the Twitter logo and available commons logos seem okay

Yeah, our `build_wikidata.js` script catches this and falls back to using the Twitter or Commons logo.
The data in iD is just old.

**Comment by TurnrDev** [comment]
> The data in iD is just old.

I'm shocked iD isn't updated regularly

**Comment by bhousel** [comment]
> I'm shocked iD isn't updated regularly

This is no longer my job but I'm working on it anyway.  PM me if you want the full story.
After 8305 merges, iD will be able to take updates as NSI releases them.

**Comment by TurnrDev** [comment]
> This is no longer my job but I'm working on it anyway.  PM me if you want the full story.

Oh I wasn't complaining, just thought that would be something that could have been automated, but I also don't know how the system works so my opinion informed!

**Comment by bhousel** [comment]
I'm going to close here, since I'm seeing Tesco logos in my nsi_v5 branch of iD.  Main iD will hopefully get it eventually 👍 

<img width="300" alt="Screen Shot 2021-01-29 at 5 36 33 PM" src="https://user-images.githubusercontent.com/38784/106334417-96b4af80-6258-11eb-8255-905dfa50d8b2.png">
