### ISSUE TITLE
GB Post Office/Box Operators Templating

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#4878]
Hi all,

So after @bhousel added templates, I wonder if GB amenity=post_office should be generated via them. For a prime case in point see this:
https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&cc=gb#onestop-2ecbba
Compared to the convenience store version:
https://nsi.guide/index.html?t=brands&k=shop&v=convenience&cc=gb#onestop-232829

Clearly ideally this data should be templated across from the other source. I guess we just need to templateInclude though, as they don't all necessarily operate post offices?

Linked to this, this is currently incorrectly done for post boxes in the UK:
https://github.com/osmlab/name-suggestion-index/blob/93ae4a408ce1e50854ed85406e397f82ce863736/data/operators/amenity/post_box.json#L3-L10

Can we have a templateExcludeLocationSet or something @bhousel which is overridden by templateInclude so we can just merge Royal Mail in from the post offices? There seem to be a tiny handful which claim other operators, which I suspect may be in error, certainly the Post Box inside a Tesco near me is all badged up as Royal Mail I think:
https://overpass-turbo.eu/s/12JO

There's also some other matchNames in that query we probably need to deal with...

**Comment by bhousel** [comment]
Sorry @peternewman  I don't really understand what this issue is about.

Is it normal for grocery/convenience stores in the UK to also function as post offices?  As an American this seems weird to me, but maybe it's correct?  I kind of assumed that these stores had some post office counter mapped as a node within the store.

I guess what I'm trying to understand is where the mistake is.  Am I right to assume that the post offices tagged as "One Stop" should really be tagged as "Royal Mail" on a node placed somewhere within a One Stop convenience store?

**Comment by peternewman** [comment]
In a lot of smaller villages and towns, there's no longer a dedicated post office, just a counter within the shop. Sales pitch here:
https://runapostoffice.co.uk/benefits-services

I think it's all run by the shop, it's just an amenity they have, in the same way as they might let you top up your oyster travelcard, sell lottery tickets or soft drinks, or have a cash machine inside or out.

Saying that I've often micro-mapped cash machines, but it seems a bit odd to have a node within it for something that could merge, or I think in theory could be served from the main shop counter.

For example this one has been tagged:
https://www.openstreetmap.org/node/21509246
```
    "amenity": "post_office",
    "brand": "One Stop",
    "brand:wikidata": "Q65954217",
    "name": "One Stop",
    "operator": "One Stop",
    "shop": "convenience"
```

**Comment by UKChris-osm** [comment]
> Is it normal for grocery/convenience stores in the UK to also function as post offices?

This happens a lot, yes. Many convenience stores will have a post office counter inside of it, and will often be run by the convenience store itself, some even share the same till counter and the people at the till will do both shop and post office transactions.

The post office is like a franchise in a way, except the post office pay the convenience store to run the post office counter. The Post Office as a company / brand don't just deal with postal products anymore, they enable banking transactions, currency exchange, and even sell broadband.

The Royal Mail only collect post, and don't have any other involvement, and I don't think they operate any post office's themselves.

Some people tag Post Office's within shops as a node in it's own right, or use "_opening_hours:post_office_" on the store along with "_amenity=post_office_".

I don't really know the best way to handle that within the NSI, 

> For example this one has been tagged:
> https://www.openstreetmap.org/node/21509246

Looking at the One Stop web site, that location isn't a One Stop, so could be a mix of old and newer tags.

**Comment by bhousel** [comment]
I think we could support this if we could encourage people to map the grocery store separately from the post office counter.  I dont think we can support having all the tags on a single feature.  

Having the `amenity=post_office` and `shop=convenience` together like this goes against ["one feature, one element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element), and will cause problems in iD (I'm not sure which preset iD would choose for it).

**Comment by kjonosm** [comment]
a tag proposal for shops with post office counters is currently in preparation, see [wiki proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/shop_as_post-partner). it might be worth waiting to see how that turns out.

**Comment by bhousel** [comment]
> a tag proposal for shops with post office counters is currently in preparation, see [wiki proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/shop_as_post-partner). it might be worth waiting to see how that turns out.

Oh that is interesting.. But the examples still show adding `post_partner*` tags to a `shop=*` feature, which I still can't really support.  Post Offices (or Partners) really need to be mapped as separate features.

**Comment by peternewman** [comment]
> > For example this one has been tagged:
> > https://www.openstreetmap.org/node/21509246
> 
> Looking at the One Stop web site, that location isn't a One Stop, so could be a mix of old and newer tags.

Doh, it looks more like it had some red branding but a lot of blue (presumably for One Stop) so I wonder if it's just closed/changed ownership in the eight years since some relevant tagging:
https://goo.gl/maps/Cei1ayuLKGhDtudj8

> I think we could support this if we could encourage people to map the grocery store separately from the post office counter. I dont think we can support having all the tags on a single feature.

Surely that doesn't work unless we're micro-mapping, and only if they are different counters. We're not supposed to map the deli, fish and bakery bits of a supermarket separately now are we (although I know the café is often done as such)?

> Having the `amenity=post_office` and `shop=convenience` together like this goes against ["one feature, one element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element), and will cause problems in iD (I'm not sure which preset iD would choose for it).

But it is one feature, the building/shop is the feature. In the same way as we tag if a bus stop has a shelter, bench or bin, we're tagging if this convenience store has a post office counter, or does Oyster top up or National Lottery or whatever.

Otherwise shouldn't we be going down the school route and tagging the building with it's opening hours, and then nodes within it with the amenities (I guess the main argument for this is does the post office counter have different opening hours to the rest of the shop - I think it can).

In terms of which preset iD chose, if we did my suggestion it wouldn't matter (whereas it does currently), because they'd both have the same tags.

**Comment by bhousel** [comment]
Again, mappers can't combine toplevel tags (like `amenity=*` and `shop=*` on a feature and expect software to know how to treat it (#4008 has more on this).  This has been true going back at least when Potlatch was the default editor.

This is why a bunch of UK convenience stores have ended up in the Post Office file.

I don't really want to nitpick over what "one feature one element" means.  For NSI and iD and many other softwares, it means that a post office really needs to be its own thing.  

If UK mappers don't want to map that way, we can filter Royal Mail out of NSI.  This project exists to generate convenience presets for iD and power the iD validator, but it's not critical software and people can map however they want to.

**Comment by doublah** [comment]
Even without the "one feature one element" rule, mapping the shops/post offices seperately makes a lot of sense imo as the post office hours and shop hours are frequently different, as well as the post office and shop having different names/brands. We have seperate nodes for pharmacy counters and Argos counters in Sainsbury's so it makes sense for Post Office counters.

**Comment by Adamant36** [comment]
> Even without the "one feature one element" rule, mapping the shops/post offices seperately makes a lot of sense imo as the post office hours and shop hours are frequently different, as well as the post office and shop having different names/brands. We have seperate nodes for pharmacy counters and Argos counters in Sainsbury's so it makes sense for Post Office counters.

👍 

Also, how would it work for the brand tags if the convenience store and post office was tagged on the same node anyway? Because I don't see how it could be done without relying on something "stupid" like brand_1=whatever + brand_2= Etc. Etc. Which shouldn't be done.

**Comment by bhousel** [comment]
For now I've filtered out the uk convenience stores from being included in the `operators/amenity/post_office.json` category:

Fortunately these all have kind of low usage, so they really could be mapped as `amenity=post_office` as a node within a store, if people want to do it.

```js
  "amenity/post_office|Costcutter": 17,
  "amenity/post_office|Londis": 19,
  "amenity/post_office|McColl's": 14,
  "amenity/post_office|McColls": 13,
  "amenity/post_office|One Stop": 12,
  "amenity/post_office|Premier": 16,
  "amenity/post_office|The Co-operative Food": 18,
  "amenity/post_office|WHSmith": 13,
```
