### ISSUE TITLE
wrong website on VIA Rail entry

### ISSUE THREAD

**Issue by claysmalley** [osmlab/name-suggestion-index#4879]
website is listed as http://www.viarailcanada.co.kr/default/ and should be https://www.viarail.ca/

**Comment by UKChris-osm** [comment]
The web site address is taken from Wikidata, and it looks like the Wikidata for [VIA Rail](https://www.wikidata.org/wiki/Q876720) has a lot of web addresses associated with it.

**Comment by Adamant36** [comment]
It doesn't really matter on our end anyway. Since we don't use websites in the presets.

**Comment by claysmalley** [comment]
Sounds like this is pretty low-impact, then. Cheers
