### ISSUE TITLE
BMW uses a few different QIDs?

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4883]
Is this right?

<img width="300" alt="Screen Shot 2021-01-28 at 5 06 33 PM" src="https://user-images.githubusercontent.com/38784/106204601-3c99e880-618b-11eb-96fa-a1d39238338e.png">

**Comment by UKChris-osm** [comment]
"_BMW Motorrad_" is the motorcycle division for BMW, and seems to have it's own Wikipedia / Wikidata entry, and has it's own social media links, so I'd say them being seperate entries is reasonable, but I would probably rename the Motorcycle Dealership to include "_Motorrad_" in the name.

**Comment by bhousel** [comment]
> "_BMW Motorrad_" is the motorcycle division for BMW, and seems to have it's own Wikipedia / Wikidata entry, and has it's own social media links, so I'd say them being seperate entries is reasonable,

Cool, we can leave it as-is.. I just thought it looked strange :)
