### ISSUE TITLE
New café brand: Frei Cafe

### ISSUE THREAD

**Issue by debyos** [osmlab/name-suggestion-index#4884]
Dear All,

[Cafe Frei is a Hungary](https://www.cafefrei.hu/)-based [international café chain](https://www.cafefrei.com/) with branches is several countries, you can find on their website. On OSM they have [more than 30 shops in Hungary](https://overpass-turbo.eu/s/12YO).
You may consider to include them into the other brands.
Cheers

Gábor

**Comment by nuxper** [comment]
I created the wikidata item : Q105210995
