### ISSUE TITLE
List amenity=clinic and amenity=hospital in operator tree?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4890]
Judging the situation in Germany, I think I could make sense to move `amenity=clinic` and `amenity=hospital` features in the `operator` tree. These healthcare facilities almost never share a common name while being likely operated by one of a few private healthcare providers, e.g.:

- [Vivantes](https://mvz.vivantes.de/arztpraxis-finden)
- [Sana](https://www.sana.de/kliniken)
- [Helios](https://www.helios-gesundheit.de/kliniken/)

Don't know about other countries though...

**Comment by bhousel** [comment]
Yes I agree, these things should be more `operator`. . 
Should we set `brand` tag also, or do you think it's unnecessary?  (I don't have an opinion)

**Comment by kjonosm** [comment]
I guess not including `brand` by default is fine. People can still add the tag manually if they want to.

**Comment by bhousel** [comment]
I did this!
This pulled in a lot of new clinics and hospitals that need to be checked and cleaned up, as the threshold for `operator` is much lower than for `name`.
