### ISSUE TITLE
npm install, requiring upgrades?

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4896]
When running "_npm install_" I saw a lot of warnings about deprecated entries, a couple of which said would break upon node 14+ usage, as well as a couple of vulnerabilities, one being high.

Are these warnings related to the NSI package, or more about Node.js / NPM itself?

**Comment by bhousel** [comment]
I'll check!  Warnings like these are usually related to other software that we depend on.

**Comment by UKChris-osm** [comment]
Thanks @bhousel 

Looks like I tried running "_npm run build_" at the same time as you, that shouldn't cause any problems should it?

**Comment by bhousel** [comment]
> Looks like I tried running "npm run build" at the same time as you, that shouldn't cause any problems should it?

Yeah it should be no problem.. Regardless of who runs it, `npm run build` should do the same things.

Here is what I found for the deprecated dependencies when I run a fresh install on Node v14:

```bash
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
```

we can use `npm ls` to track down where the dependency comes from, for example **chokidar**:
```bash
~/Projects/name-suggestion-index [main|✔] % npm ls chokidar
name-suggestion-index@5.0.0-pre /Users/bhousel/Projects/name-suggestion-index
└─┬ parcel-bundler@1.12.4
  └─┬ @parcel/watcher@1.12.1
    └── chokidar@2.1.8 
```

So this is used by `parcel-bundler`, which we use to build the nsi.guide react site.  This isn't something that we have control over, and it looks like the parcel project is already aware that they need to upgrade:  https://github.com/parcel-bundler/parcel/issues/4623

Anyway, for each of these warnings, we can check and see whether it's something we can fix by bumping a dependency version. Otherwise we can just wait for things to break. 😅  (e.g. if `parcel` stopped working, we could probably use something else to build nsi.guide).

**Comment by bhousel** [comment]
The most pressing of these right now seems to be parcel:
```
npm WARN deprecated parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
```
From what I can tell,  [parcel 1](https://www.npmjs.com/package/parcel-bundler) is deprecated, and [parcel 2](https://www.npmjs.com/package/parcel) is available in beta.

**Comment by bhousel** [comment]
I upgraded parcel this morning, now the list looks like this:
```
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

Now that Node 16 is released, and Node 10 is days away from End of Life - I'm taking a pass over these to see whether any of this stuff matters in the short term.

**Comment by bhousel** [comment]
I'm going to close this, as we don't really need an open issue for the warnings unless something is actually broken.  Keeping the dependencies updated is just good project hygiene.
