### ISSUE TITLE
Benu Vet's

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4898]
I think [Benu](https://nsi.guide/index.html?t=brands&k=amenity&v=veterinary#benu-ae5565) listed under "_amenity/veterinary_" is a mistake, would anybody disagree?

Edit: Hmmm, maybe not [New in BENU Pharmacies - VET assortment](https://www.benu.lv/jaunumi/page:17/benu-aptiekas-jaunums-vet-sortiments.html)

**Comment by kjonosm** [comment]
currently there is one vet with such name in OSM ([overpass turbo](https://overpass-turbo.eu/s/13jy)). I think it's safe to delete the entry in nsi.
