### ISSUE TITLE
Proposal: Flower Burger

### ISSUE THREAD

**Issue by airon90** [osmlab/name-suggestion-index#4907]
{
      "displayName": "Flower Burger",
      "locationSet": {"include": ["it", "fr"]},
      "tags": {
        "amenity": "fast_food",
        "brand": "Flower Burger",
        "brand:wikidata": "Q67168925",
        "cuisine": "burger", 
        "name": "Flower Burger",
        "diet:vegan": "only"
      }
    },

**Comment by nuxper** [comment]
Hi @airon90 and thanks for the proposal.

I understand from their website that Flower Burger  is a franchise. The operator of each franchised restaurant will probably be different, won't it ? If so, I would remove the operator line.

**Comment by airon90** [comment]
You were right! Updated
