### ISSUE TITLE
Proposal: Roadhouse Grill

### ISSUE THREAD

**Issue by airon90** [osmlab/name-suggestion-index#4914]
```
{
  "displayName": "Roadhouse Grill",
  "locationSet": {"include": ["001"]},
  "tags": {
    "amenity": "restaurant",
    "cuisine": "steak_house",
    "brand": "Roadhouse Grill",
    "brand:wikidata": "Q7339591",
    "name": "Roadhouse Grill"
  }
},
```

**Comment by nuxper** [comment]
Thanks again @airon90 ;)

I see that about 50% of those restaurants are named "Roadhouse" and 50% "Roadhouse Grill" + the url roadhousegrill.it now redirects to Roadhouse.it . The logo and brand on the website seems to say "Roadhouse" (without the word "Grill"). Is there a change of name in progress ?

I understand from the English wikipedia ( https://en.wikipedia.org/wiki/Roadhouse_Grill ) (sorry I don't speak Italian ;) ) that the original American brand was forced into liquidation but that "Independently owned international venues of the chain following the same name and concept continue to operate in Italy,[1] Bulgaria[2] and Brazil.[3]" . Are the venues in Italy, Bulgaria and Brazil part of the same organizations ? If not, maybe we should have separate wikidata entries and separate nsi entries for all three countries.

**Comment by airon90** [comment]
> I see that about 50% of those restaurants are named "Roadhouse" and 50% "Roadhouse Grill" + the url roadhousegrill.it now redirects to Roadhouse.it . The logo and brand on the website seems to say "Roadhouse" (without the word "Grill"). Is there a change of name in progress ?

You are right. I suppose "Roadhouse Grill" was rebranded into "Roadhouse". You can use just "Roadhouse"

> sorry I don't speak Italian ;)

I forgive you :D

> I understand from the English wikipedia ( https://en.wikipedia.org/wiki/Roadhouse_Grill ) (sorry I don't speak Italian ;) ) that the original American brand was forced into liquidation but that "Independently owned international venues of the chain following the same name and concept continue to operate in Italy,[1] Bulgaria[2] and Brazil.[3]" . Are the venues in Italy, Bulgaria and Brazil part of the same organizations ? If not, maybe we should have separate wikidata entries and separate nsi entries for all three countries.

That is correct but websites [2] and [3] are down, so I suppose that even chains outside Italy have been liquidated or similar. Because of your proposal, I suggest you to just change "locationSet" to include only Italy, so that a Brazilian or a Bulgarian user could eventually add their Roadhouse later.

> Thanks again @airon90 ;)

Thank you for everything! :) I will make more proposal because there are many chains in Italy.

**Comment by nuxper** [comment]
OK I'll do that.

By the way : would you want me to show you how to contribute directly ? I'm happy to continue integrating your proposals, they are of good quality. But it may be more efficient for you to directly submit pull requests. We can have a visio or something. (in english ;) )

**Comment by airon90** [comment]
That's okay. Contact me privately, see my profile ;) Keep in mind that I'm not a professional coder
