### ISSUE TITLE
Proposal, Fix and a question

### ISSUE THREAD

**Issue by airon90** [osmlab/name-suggestion-index#4915]
1. u2-0cb133 should have brand:wikidata=Q105542216
2. A copy of u2-0cb133 should be done with "U!" instead of "U2" as name and brand. Moreover, brand:wikidata should be Q105542347
3. How to add logos?

**Comment by nuxper** [comment]
logos actually obtained fist from the social medias or from wikicommons:

The modifications need to be done directly on wikidata:
- to add the link to the facebook page, set the https://www.wikidata.org/wiki/Property:P2013 ( nome utente Facebook )
- to add the link to the instagram page, set the https://www.wikidata.org/wiki/Property:P2003 ( nome utente Instagram )
- to add the link to the pinterest page, set https://www.wikidata.org/wiki/Property:P3836 ( nome utente Pinterest )
- to add the link to the wikicommons logo, set https://www.wikidata.org/wiki/Property:P154 ( logo ). If the logo doesn't exist in wikicommons, you can upload it but be very careful about the copyright aspect.

I'll check the u2-0cb133, thanks

**Comment by nuxper** [comment]
@airon90 : Note: I noticed that you create the wikidata items.

By experience, I advise you to add reference links (any link to a newspaper describing the brand is fine). All the items  I created were deleted before any warning. the name-suggestion-index identifier property helps but I understand the wikidata community likes links to external articles.

**Comment by nuxper** [comment]
I could find only one "U!" in Italy via overpass. Is that normal ?

**Comment by airon90** [comment]
> If the logo doesn't exist in wikicommons, you can upload it but be very careful about the copyright aspect.

I fear of copyright aspect and legal consequences so I prefer not to upload such material. 

>  I advise you to add reference links

I know that but I don't think there are good references for a small Northern Italian supermarker chain. I will search and add something later

> I could find only one "U!" in Italy via overpass. Is that normal ?

I'm not good at Overpass Turbo. Have you tried to query for "Unes"? It is not correct to add them in this way because one cannot distinguish from "U!" and "U2". Keep in mind that [it is a small Nothern Italian chain](https://it.wikipedia.org/wiki/Unes#Punti_vendita)

**Comment by nuxper** [comment]
overpass : https://overpass-turbo.eu/s/13Pq

basically start the wizard and type << name="U!" >>  ;)

Anyway I included the "U!" brand in nsi
