### ISSUE TITLE
GB: Add Beefeater

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#4917]
Another brand of pub/restaurant with unique names for each instance
https://www.beefeater.co.uk/en-gb/locations

**Comment by UKChris-osm** [comment]
[Beefeater](https://nsi.guide/index.html?t=brands&k=amenity&v=restaurant&tt=beef#beefeater-9b5453) is already in the index @peternewman  :)

**Comment by peternewman** [comment]
Ah yes, thanks @UKChris-osm , it's just got stuck in limbo and not made it into iD.

I'll close this now anyway...
