### ISSUE TITLE
Changing/adding some Wikidata ID to nsi

### ISSUE THREAD

**Issue by airon90** [osmlab/name-suggestion-index#4922]
To be added:

* [x] tobike-3d5df6 → brand:wikidata=Q245660
* [x] bikemi-3d5df6 → brand:wikidata=Q2902552
* [x] goodbikepadova-3d5df6 → brand:wikidata=Q105555683

To be changed:

* [ ] pam-d52198 → brand:wikidata=Q105615038 because now this item is about the supermarket chain. On nsi.guide, WIkidata item points to the group of the company which owns the chain

**Comment by airon90** [comment]
I fixed every old brand:wikidata and brand:wikipedia about PAM stores. Please fix it now :)

**Comment by bhousel** [comment]
> I fixed every old brand:wikidata and brand:wikipedia about PAM stores. Please fix it now :)

I can fix this in our index, but it is kind of confusing, and there really should be some more supporting references on the Wikidata side to avoid having these pages getting merged back together by admins.

**Comment by airon90** [comment]
All data about PAM and its chains were taken from [Italian Wikipedia](https://it.wikipedia.org/wiki/Gruppo_PAM). Why do you say it is kind of confusing? Meanwhile I will look for sources to be added on Wikidata if useful
