### ISSUE TITLE
Have the matcher handle generic/common words too

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4924]
Currently the matcher code is only used for matching canonical items in NSI:

```js
result = matcher.match('amenity', 'fast_food', 'Honey Baked Ham');
>  [{"match":"primary","itemID":"honeybakedham-4d2ff4",kv":"amenity/fast_food","nsimple":"honeybakedham"}]
```
But it doesn't do anything for generic names
```js
result = matcher.match('amenity', 'fast_food', 'Food Court');  // generic
>  null
result = matcher.match('amenity', 'fast_food', 'Kebabai');   // named
>  null
```

#### generic/named?
Up until last week, NSI had a bunch of discard regular expressions in both the `config/genericWords.json` file, but also in the `keepKV` and `discardKVN` properties in the `config/trees.json` file.  This was confusing so I changed it - NSI now can differentiate between generic/named words, and these are stored with each category (#4906).  

This relates to https://github.com/openstreetmap/iD/issues/6055 - it's basically saying that iD needs to be smarter about whether a word is really a generic word or whether it's a common name in some contexts.

A note on terminology (I need to document this, sorry):
- **generic** - a generic word that is probably not really a name.  For these, iD should warn the user "Hey don't put 'food court' in the name tag".
- **named** - a real name like "Kebabai" that is just common, but not a brand.  For these, iD should just let it be. We don't want this in NSI, but we don't want to warn users about it either.

#### going forward
So what I'd really like to do is have the matcher do a bit more and handle the generic words too.

This will make things simpler on the iD validator side, because it will mean fewer files to fetch and all the code for matching names can be in one place.

**Comment by UKChris-osm** [comment]
The [recent planet scan](https://github.com/osmlab/name-suggestion-index/commit/11496df88a6aa5a0bd863166412fc18f05f0708f#diff-dadd61d16a64d4d04af8ef0e83772405fd59a9c395fe6ec321918cb3c62f3c5f) added "_NHS_" to the [ambulance_station.json](https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/emergency/ambulance_station.json) file, but as the operators are already locally defined, would the below code exclude it from returning?

 "properties": {
    "path": "operators/emergency/ambulance_station",
    "exclude": {
      "generic": ["^ambulance station$"],
      **"named": ["^(nhs|national health service)$"]**
    }
  },

**Comment by bhousel** [comment]
> The [recent planet scan](https://github.com/osmlab/name-suggestion-index/commit/11496df88a6aa5a0bd863166412fc18f05f0708f#diff-dadd61d16a64d4d04af8ef0e83772405fd59a9c395fe6ec321918cb3c62f3c5f) added "_NHS_" to the [ambulance_station.json](https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/emergency/ambulance_station.json) file, which I removed, but "_npm run build_" put it back again - as the operators are already locally defined, would the below code exclude it from returning?

Does NHS operate ambulance stations? 
Adding those patterns would stop them from appearing in the index, but if they are common maybe it's correct?

**Comment by UKChris-osm** [comment]
NHS is like the parent organisation, and under it is regional organisations which run the ambulance stations / service, such as:

- [East Midlands Ambulance Service](https://nsi.guide/index.html?t=operators&k=emergency&v=ambulance_station&cc=gb#eastmidlandsambulanceservice-4d00c7)
- [London Ambulance Service](https://nsi.guide/index.html?t=operators&k=emergency&v=ambulance_station&cc=gb#londonambulanceservice-aece76)
- [South Western Ambulance Service](https://nsi.guide/index.html?t=operators&k=emergency&v=ambulance_station&cc=gb#southwesternambulanceservice-bba5ce)

... so while I think it's reasonable for people to mark an ambulance station as being run by the NHS, it would be more correct for the regional organisation to be tagged (such as those listen above), and perhaps "_NHS_" to be a matchname for each region.

**Comment by bhousel** [comment]
> so while I think it's reasonable for people to mark an ambulance station as being run by the NHS, it would be more correct for the regional organisation to be tagged (such as those listen above), and perhaps "_NHS_" to be a matchname for each region.

Makes sense - yes it would be ok to `matchName` "nhs" and "national health service" for all of the regional organizations, then iD would be able to suggest a tag upgrade.
