### ISSUE TITLE
Add H&T Pawnbrokers

### ISSUE THREAD

**Issue by doublah** [osmlab/name-suggestion-index#4927]
UK pawnbrokers with 253 stores according to website https://handt.co.uk/stores

**Comment by UKChris-osm** [comment]
[H&T Pawnbrokers](https://nsi.guide/index.html?t=brands&k=shop&v=pawnbroker#handtpawnbrokers-c861e3) is already in the index, but does still need a Wikidata!

**Comment by UKChris-osm** [comment]
Added Wikidata via [386d7d7](https://github.com/osmlab/name-suggestion-index/commit/386d7d7e75675f351ef62dc75c8c0c61eb1bbaa8)
