### ISSUE TITLE
how should 'Brazier' be handled?

### ISSUE THREAD

**Issue by ArloJamesBarnes** [osmlab/name-suggestion-index#4928]
https://flickr.com/photos/ezeiza/5104212490

It's a brand of grill (the restaurant genre, not the cooking implement) associated with Dairy Queen. Not all DQs are/have Braziers, but all Braziers are / have as parent brand DQ.

**Comment by 1ec5** [comment]
This whole time I thought Brazier was just a DQ store format, like Pizza Hut Express. If in fact it’s a store within a store, then it deserves its own Wikidata item and NSI entry, similar to Green Burrito (Carl’s Jr.) or Tastee-Freez (Wienerschnitzel).

**Comment by ArloJamesBarnes** [comment]
You may be right, 'store format' isn't a familiar phrase to me so it's possible I could be mistaken.

**Comment by bhousel** [comment]
Oh yeah, "Brazier" is their word for whether the Dairy Queen serves grill food like hot dogs and hamburgers.
From wikipedia, it looks like they are phasing out the usage of that - if you see it, it's a legacy signage:  https://en.wikipedia.org/wiki/Dairy_Queen#Dairy_Queen_Brazier
It's not really a different enough brand that it would warrant having its own Wikidata QID.

Some of them say "Grill & Chill" or "DQ Restaurant" now in smaller signage.  So while these are slightly different store formats, I really think it would be fine for them all to be consistently branded as "Dairy Queen" in OSM. 

If people really want, we can now do the #4906 thing and allow mappers to adjust the name tag on Dairy Queen (but I think that's not really needed).

**Comment by tas50** [comment]
We have an entry for Grill & Chill vs. the traditional DQ since the Grill & Chill is the more modern fast food format. The buildings are laid out like any other American fast food chain and the menu is different than the old school DQ drive up format.

**Comment by bhousel** [comment]
Going to close here, as it's getting phased out anyway.
