### ISSUE TITLE
Wacky Warehouse isn't a pub, is it?

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4929]
I was surprised to see "_Wacky Warehouse_" appear in **pub.json** after the latest planet scan, as it's an indoor play area aimed at children, but it seems this is because a lot of pubs have been marked up in this way in OSM recently.

Is this something that should be amended within the NSI? I don't think it belongs within **pub.json**, as the pubs that some of the entries are a part of are actually other brands of pub ([Hungry Horse](https://nsi.guide/index.html?t=brands&k=amenity&v=pub#hungryhorse-eaed91) etc).

One example being [New Inn](https://www.openstreetmap.org/way/42221089), branded as "_Whacky Warehouse_" in OSM, but should (in my opinion) be branded "_Hungry Horse_".

Should "_Wacky Warehouse_" be removed from **pub.json**?

**Comment by bhousel** [comment]
> I was surprised to see "_Wacky Warehouse_" appear in **pub.json** after the latest planet scan, as it's an indoor play area aimed at children, but it seems this is because a lot of pubs have been marked up in this way in OSM recently.

Yeah it looks weird to me too, but apparently that's how it's being tagged:
https://overpass-turbo.eu/s/14ib

If they have `amenity=pub` combined with `brand=Wacky Warehouse` and > 50 occurrences, it will be added to the index like this.

**Comment by Adamant36** [comment]
Apparently it has to do with the fact that they are operated by Greene King (a company that operates pubs) and there is a lot of cross over. For instance, in the example picture it looks there is a Wacky Warehouse above a Greene King pub so kids can play while their parents drink 👍 

Really, they should be split off as their own thing and just have the same operator as the pubs similar to how the play areas in McDonald's currently are in the index. 

![wacky-warehouse](https://user-images.githubusercontent.com/30259065/112712820-fd3bff80-8e8e-11eb-923c-4e8a88aaa23e.jpg)

**Comment by bhousel** [comment]
Closing as stale.  As far as OSM/Overpass is concerned, Wacky Warehouse is a pub.  
If it's not a pub, someone needs to go through https://overpass-turbo.eu/s/14ib and fix them all.

**Comment by SomeoneElseOSM** [comment]
A "Wacky Warehouse" is a kids' play area associated with a Greene King pub.  

Taking a local one https://www.openstreetmap.org/way/485744356 as an example, the site has both "Greene King" and "Wacky Warehouse" branding.  Websites exist both if you search via Greene King https://www.greeneking-pubs.co.uk/pubs/north-yorkshire/riverside-farm/ and Wacky Warehouse https://www.wackywarehouse.co.uk/riverside-farm/ , so having one of those branded as "Wacky Warehouse" seems just as reasonable to me as having it branded "Greene King".  

It could be worse - some UK pubcos have 3 levels of branding!
