### ISSUE TITLE
Handle new format in name-suggestion-index

### ISSUE THREAD

**Issue by nuxper** [osmlab/name-suggestion-index#4931]
name-suggestion-index output file "nsi.json" had a change in format.
For each tag path (for ex. brands/amenity/atm), the nsi.json now contains:
- a "properties" element containing a dictionary
- a "items" element containing the list of brands / operators.

I create this issue to track the update of TagFix_brand.py to follow this change of format.

The change is ready. I'll create a PR in a moment.

**Comment by UKChris-osm** [comment]
Is this in reference to Osmose backend? https://github.com/osm-fr/osmose-backend/pull/1202

**Comment by nuxper** [comment]
Arg you are right. I created the issue on the wrong project!!!

**Comment by bhousel** [comment]
Yes sorry for the changes, though it is prerelease stuff.  
We are pretty close to releasing V5 for real, so I don't think the file format will change anymore..
(One good thing about having properties in a dedicated `properties: {}` object is that we can add stuff without changing the file format anymore).
