### ISSUE TITLE
P8972 "small logo or icon"

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4936]
from @1ec5 

https://www.wikidata.org/wiki/Property:P8972 could be useful for some NSI purposes as an alternative to the usual logo property.
small logo or icon - logo or icon that represents the item and can be rendered at sizes as small as 16×16 pixels

I agree our script should collect these 👍

**Comment by UKChris-osm** [comment]
If a small icon isn't available, could the favicon.ico be pulled direct from the web site referenced in the wikidata?

**Comment by bhousel** [comment]
> If a small icon isn't available, could the favicon.ico be pulled direct from the web site referenced in the wikidata?

Sort of - it's a bit challenging because `favicon.ico` is a tricky format to work with, but many websites provide higher quality icons now with `<link rel="icon"...` tags.  I'd rather not add a bunch of scraping logic into our NSI scripts, but this is probably something that someone else could build to add value on the Wikidata side.
