### ISSUE TITLE
Duplication of 昭和シェル

### ISSUE THREAD

**Issue by venue-map** [osmlab/name-suggestion-index#4937]
[昭和シェル(amenity=fuel)](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=%E6%98%AD%E5%92%8C%E3%82%B7%E3%82%A7%E3%83%AB), [昭和シェル(shop=convenience)](https://nsi.guide/index.html?t=brands&k=shop&v=convenience&tt=%E6%98%AD%E5%92%8C%E3%82%B7%E3%82%A7%E3%83%AB)

According overpass all are in Japan.
昭和シェル(Q277115) is japanese fuel station chain. It is not a convenience store chain.
(Some fuel stations also have convenience stores, but they are chain stores such as Seven-Eleven and FamilyMart.)

**Comment by bhousel** [comment]
Thanks @venue-map - I think it was me that added these.
I've removed them and added some patterns to match them in the "named" exclude list.
