### ISSUE TITLE
Amazon Fresh / Amazon Go

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#4938]
I've just added [Amazon Fresh](https://github.com/osmlab/name-suggestion-index/commit/a112c8c1ad35c88e3fe6d3ad98758a415dc78235) as a worldwide convenience store, and [Amazon Go](https://github.com/osmlab/name-suggestion-index/commit/3cb6d77dc2d77b21548b22c33560d8d7fd2b1cb7) as US only, as Amazon seem to be intent on building up a large chain, but would anybody disagree with this?

Should it be a supermarket? Should it be locatonSet'd? Should it be in the index at all, as the numbers are still low, but I can't imagine Amazon taking long to expand?

**Comment by bhousel** [comment]
I'd call Amazon Fresh a supermarket, based on photos here:
https://www.engadget.com/amazon-fresh-woodland-hills-la-open-to-public-200248518.html
But I think it's fine for them to be in the index.
