### ISSUE TITLE
MetroPCS

### ISSUE THREAD

**Issue by cicku** [osmlab/name-suggestion-index#4942]
Interesting...

Metro by T-Mobile still uses old name MetroPCS but all wiki tags had been updated.

IMO it should be `name=Metro by T-Mobile`

**Comment by tas50** [comment]
It seems like T-Mobile is still in the early stages of this rebrand and there's always a really tricky balancing act with this index in updating the names. OSM users get really upset when tags on buildings don't match the branding on storefront signs. Right now at least where I live none of the MetroPCS signage has been updated. We'll probably want to update this, but we should wait until they roll out their updating signage nationally.

**Comment by zyphlar** [comment]
The branding update appears to be in full swing, this might be worth revisiting.

**Comment by tas50** [comment]
I think we're good to update this one now.

**Comment by tas50** [comment]
Let's make sure it has an alt_name tag for MetroPCS though

**Comment by zyphlar** [comment]
FYI I've created a MapRoulette challenge to update American MetroPCS locations as appropriate

**Comment by bhousel** [comment]
> FYI I've created a MapRoulette challenge to update American MetroPCS locations as appropriate

Can you pause the challenge until I publish a NSI version that includes the new tags?  
Releasing NSI doesn't take long to do, but I think we can wait a day for editor software to start fetching the new data.

**Comment by zyphlar** [comment]
For sure, I doubt anyone but me will get to it anytime soon anyway

**Comment by bhousel** [comment]
> Can you pause the challenge until I publish a NSI version that includes the new tags?
> Releasing NSI doesn't take long to do, but I think we can wait a day for editor software to start fetching the new data.

I published v6.0.20210729 yesterday and the iD/RapiD now have it 👍 

<img width="377" alt="Screen Shot 2021-07-30 at 11 12 02 AM" src="https://user-images.githubusercontent.com/38784/127673984-edb3aa7d-9d29-46fb-bb7b-20774e117b92.png">
