### ISSUE TITLE
`operator` tags are often wrong in the transit tree

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4944]
Thanks @kjonosm for raising this: 

> For each transit network collected from the planet, the `operator` value is automatically added by just duplicating the `network` value. In many cases this is a mistake and leads to wrong data. See e.g. following networks where the operator tag in nsi is just a copy of the network tag, deviating from the actual tagging in OSM you can compare in the given overpass turbo links:

Ah yeah I see now.  Since so many are wrong, I think I'm just going to remove all the `operator` values from the transit tree, and people will need to put them back manually.  This is annoying and I feel bad about it, but at least it will prevent the validator from pushing wrong tags.  I'm going to open a new issue for it, so everyone knows..

_Originally posted by @bhousel in https://github.com/osmlab/name-suggestion-index/issues/4543#issuecomment-793051017_

**Comment by kjonosm** [comment]
Is it worth keeping existing `operator` data in nsi when different from `network` tag?

**Comment by michaelblyons** [comment]
> Is it worth keeping existing `operator` data in nsi when different from `network` tag?

Yes, please.

**Comment by bhousel** [comment]
> Is it worth keeping existing `operator` data in nsi when different from `network` tag?

Ok, I can do that (in other words, only remove the `operator` if it is the same as `network` because this may be have been added wrongly).

**Comment by bhousel** [comment]
Let me know if it looks better now!   I changed the script so that new collected items won't be set up like this by default.
