### ISSUE TITLE
network can only have one operator

### ISSUE THREAD

**Issue by Identitaet** [osmlab/name-suggestion-index#4946]
we have an issue with it not liking the existance of duplicates networks which is the case here because the network has different operators

**Comment by Identitaet** [comment]
relavant log part:



Error - Duplicate id 'vrr-3b9544' in:
  Stadtwerke Remscheid
  ./data/transit/route/bus.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by bhousel** [comment]
Yes, this is true - if the network can have multiple operators, we need to not include the operator tags, then mappers will need to supply it.

**Comment by bhousel** [comment]
> okay good to know - is there a work around where we have it as separate entries ?

If they are geographically distinct, you could do it,

```js
    {
      "displayName": "VRR (City1)",
      "locationSet": {"include": ["city1.geojson"]},
      "tags": {
        "network": "VRR",
        "network:wikidata": "Q448199",
        "operator": "operator1",
        "operator:wikidata": "Qxxxx",
        "route": "bus"
      }
    },
    {
      "displayName": "VRR (City2)",
      "locationSet": {"include": ["city2.geojson"]},
      "tags": {
        "network": "VRR",
        "network:wikidata": "Q448199",
        "operator": "operator2",
        "operator:wikidata": "Qxxxx"
        "route": "bus"
      }
```
 
The risk is that we don't want iD's validator suggesting to upgrade the tags to the wrong thing.  This is a really hard problem.  If city1.geojson and city2.geojson overlap, the matcher will just pick something, and it could be wrong.

Right now NSI can only consider  `[key, value, name, location]` (e.g. `['route', 'bus', 'VRR', [lon/lat]]`) to decide what a thing is.

**Comment by Identitaet** [comment]
I can't really see how that would happen since it's always the same vrr 
Basically it's a club of local public transport operators who agreed that they'll respect each others tickets to make it easier to travel

So they all have different operators but only one network

**Comment by Identitaet** [comment]
And they're kinda distinct but there's a lot of overlap

**Comment by bhousel** [comment]
For now, let's just get the networks mapped with `network:wikidata`, and worry about `operator` later.

👉  A different thing I'm a bit worried about is that `bus.json` contains both 
- `network` like "VRR" with `matchName` like "verkehrsverbund rhein-ruhr", and
- `network` like "Rhein-Main-Verkehrsverbund" with `network:short` like "RMV"

Either way is ok, but I worry that there might be duplicates if the community is mapping inconsistently full names or short names.

**Comment by Identitaet** [comment]
yeah I'm unsure about that 
but that just something we'll have to see and hopefully get reports on
