### ISSUE TITLE
FR : Add Sadaharu Aoki (japanese pastry in France and Japan)

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#4951]
Hello, could you please add:

Country code: FR and JP
"shop": "pastry"
"cuisine": "japanese"
"brand": "Sadaharu Aoki"
"brand:wikidata": "Q3461079"

**Comment by nuxper** [comment]
Done in dcfb3dadcca6773fa9ada33950aa0aeb6c502a29

**Comment by overflorian** [comment]
thanks
