### ISSUE TITLE
Please remove item with generic name

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4953]
- [Greengrocer](https://nsi.guide/index.html?t=brands&k=shop&v=greengrocer&inc=true#boutiquealimentation-99d278)
- [Pastry shop](https://nsi.guide/index.html?t=brands&k=shop&v=pastry&cc=001&inc=true#beignetariat-4f1341)

**Comment by bhousel** [comment]
Wow that Boutique_Alimentation greengrocer is weird.  In some places they added it to every house.
https://overpass-turbo.eu/s/14Ty
