### ISSUE TITLE
美而美 in Taiwan

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#4956]
@Supaplextw left some feedback on [my wikidata talk page](https://www.wikidata.org/wiki/User_talk:Bhousel#%E7%BE%8E%E8%80%8C%E7%BE%8E_in_Taiwan):

> 美而美 is a collective terms for brands previous use the name 美而美. Now 美而美 is four separated band that was operated by different companies. You could use Google Translate to figure it out on zh Wikipedia.

Is there anything actionable for us to do on the NSI side?
The brand they are referring to is "Mei and Mei"
https://nsi.guide/index.html?t=brands&k=amenity&v=restaurant#meiandmei-aafd63
https://www.wikidata.org/wiki/Q56197246

It sounds like we might be linked to the wrong thing, or this is actually a generic name to exclude?  Anyone have more context?

**Comment by LaoshuBaby** [comment]
I will try to review this, thanks!
