### ISSUE TITLE
Shopping malls

### ISSUE THREAD

**Issue by lkernan** [osmlab/name-suggestion-index#4958]
Wondering if it's possible to add shop=mall as an option?   
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmall

Here in Australia there are two major mall operators I can think of, plus several smaller ones.   
Scentre group (wikidata Q18378048) trading as Westfield
Vicinity Centres (wikidata Q1054327)

I noticed that Westfield in the US/UK/etc (Unibail-Rodamco-Westfield) is currently listed under department_stores which doesn't seem right to me.  It's a mall operator, not a store such as Macy's.

**Comment by 1ec5** [comment]
Westfield was originally added as a `shop=mall` in #2735, but 671b85f564906f0eb3e79ff6b693dea84afc4a0c removed it. 82fda4ece49824fa610a1f35274d8603979f1d91 added a different Westfield entry as a `shop=department_store` with possibly problematic wiki tags. I think the department store entry should be removed, but I’m not sure if the circumstances that led to the `shop=mall` entry’s removal are still relevant.

/cc @bhousel

**Comment by lkernan** [comment]
As some more examples:
Direct Factory Outlets (Q5280270) also known as DFO
GPT Group (Q3100507)

**Comment by bhousel** [comment]
Thanks - I added these in 5ce3c226f 
That closed the issue, but I did want to put out there - should I maybe move these to the `operators` tree?
The name-suggestion-index contains:
- things that are definitely brands
- things that are definitely operators
- things that are both, but more brandlike
- things that are both, but more operatorlike
- amenity/bicycle_rental 🤷
