### ISSUE TITLE
Commerce Boutique doesn't look like a brand name

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#4965]
see [Commerce Boutique](https://nsi.guide/index.html?t=brands&k=shop&v=confectionery&tt=Commerce%20Boutique#commerceboutique-311d19)

**Comment by chuqtas** [comment]
You're right. It looks like incorrect OSM tagging.  While it could be excluded from NSI, it's probably best to fix the raw OSM data?

**Comment by bhousel** [comment]
> You're right. It looks like incorrect OSM tagging. While it could be excluded from NSI, it's probably best to fix the raw OSM data?

It's good to fix things in the raw OSM data!  One benefit of adding it to NSI is that going forward, iD's validator will be able to warn mappers if they are typing things into the `name` tag that look suspicious.
