### ISSUE TITLE
How are ATMs generated?

### ISSUE THREAD

**Issue by kubahaha** [osmlab/name-suggestion-index#4975]
Hello, I'd like to update several ATM brands in Poland. I found out several of them have "bank" word in names eg. [Pekao](https://nsi.guide/index.html?t=brands&k=amenity&v=atm#bankpekao-53bcca).
Operator is correct, but name should not have "bank" word. How can I edit that?

**Comment by kubahaha** [comment]
I believe that the name of the ATM should not include word bank for some brands. At the same time, this word is perfectly fine for an ATM operator and amenity=bank name.
Eg: [this](https://otopress.pl/wp-content/uploads/2020/08/ING-Bank-Slaski.jpg) photo shows typical ATM of [ING Bank](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&cc=pl#ingbankslaski-53bcca). I would find it misleading to name it as bank.

**Comment by bhousel** [comment]
Sorry @kubahaha but I really don't find it confusing. Many banks have the word "Bank" in their name, and the ATMs associated with those banks have the same name. 

Couple random screenshots from Google Maps, for comparison:

<img width="400" alt="Screen Shot 2021-03-21 at 2 07 34 PM" src="https://user-images.githubusercontent.com/38784/111915927-fa847900-8a4e-11eb-8f62-2e99fbce0a4a.png">
<img width="400" alt="Screen Shot 2021-03-21 at 2 08 32 PM" src="https://user-images.githubusercontent.com/38784/111915928-fa847900-8a4e-11eb-93e6-465f81053ba8.png">
