### ISSUE TITLE
Lots of sports_centre values are suspiciously generic

### ISSUE THREAD

**Issue by michaelblyons** [osmlab/name-suggestion-index#4977]
- Tennis
- Tennishalle
- Schulsporthalle
- Centro Sportivo?
- Others?

**Comment by kjonosm** [comment]
- Turnhalle
- Sportplatz
- Sporthalle
- Schützenhaus
- Reithalle
- Mehrzweckhalle
- Hallenbad

**Comment by Identitaet** [comment]
Contiuing it:
Boulodrome
Complexe Sportif
Ginásio de Esportes
Hala Sportowa
Pabellón de Deportes
Palazzetto dello Sport
Palestra
Palestra Comunale
Piscina Municipal
Piscine Municipale
Polideportivo
Polideportivo Municipal
Salle des Sports

**Comment by Identitaet** [comment]
okay I'll make a pr for this soon

**Comment by michaelblyons** [comment]
Palazetto dello Sport has a wikipedia page. Unsure if the things tagged are affiliated with that stadium, or are their own separately-tagged "little sport palace." 😉

**Comment by bhousel** [comment]
Yeah I might have recently dropped some rules that were filtering these out .. 

We can put them back in to the `data/brands/leisure/sports_centre.json` page, similar to how we have rules on other pages..

For example here's how the kiosks do it:

https://github.com/osmlab/name-suggestion-index/blob/71d797ddc747183cfd3d252d7f796d55b5c2aa28/data/brands/shop/kiosk.json#L5-L18

- use `generic` for name patterns to match generic words that aren't names (iD validator will warn users not to add that name)
- use `named` for patterns to match actual names, just common and not branded (iD validator will ignore them)

**Comment by Identitaet** [comment]
just to clarify things like 
sports hall etc should go into generic
also what about stuff like "Schulsporthalle" (School-sports-hall) that too ?

**Comment by Identitaet** [comment]
Someone should probably also check the ones which are left and see if I missed any and check the ones in kyrilic and arabic script

**Comment by matkoniecz** [comment]
I will make PR to remove Orlik, as it can be considered as brand only with extremely broad interpretation ( https://pl.wikipedia.org/wiki/Orlik_2012 ).

**Comment by UKChris-osm** [comment]
Orlink was removed via #5018

**Comment by bhousel** [comment]
Going to close this, I think it's been done for a while..
