### ISSUE TITLE
Add invalid tag 'clothers'

### ISSUE THREAD

**Issue by mueschel** [osmlab/name-suggestion-index#4998]
Some preset automatically adds the misspelled tag 'clothers' since a long time.
E.g. https://www.openstreetmap.org/node/6249520504/history

https://github.com/openstreetmap/iD/issues/7924

**Comment by UKChris-osm** [comment]
@mueschel I'm sure this was already fixed on the NSI side, so we're just waiting on openstreetmap/iD#8305 to be merged and published on the iD side for this issue to disappear for good :)
