### ISSUE TITLE
Twitter logo not showing up in nsi.guide

### ISSUE THREAD

**Issue by chuqtas** [osmlab/name-suggestion-index#5001]
Does anyone know why the twitter logo for Queensland Electric Super Highway / Yurika isn't showing up at https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station&tt=yurika#yurika-943805 ?  The Wikidata item is shown, and the twitter link appears in the "social links" section - just not in the right hand icon column.

I recently updated this entry to refer to the Yurika brand and logo instead of the Queensland Electric Super Highway - in this PR https://github.com/osmlab/name-suggestion-index/pull/4999 - so clearly I've done something wrong!  It's a bit complicated - see the description of that PR.

**Comment by bhousel** [comment]
It will show up after I run `npm run wikidata` to sync everything.  The process isn’t automatic yet because it takes a while for the script to run, and it lets me know if anything is broken (like if wikidata has removed or merged a qid).

**Comment by chuqtas** [comment]
Thanks @bhousel  for the info - sorry to nag - I wasn't sure why and was just checking it wasn't me :)
