### ISSUE TITLE
Show the current version on nsi.guide somewhere

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5008]
I just want to be able to see how fresh nsi.guide is.  The version has the datestamp in it now, so it would be good enough to just display that somewhere.

**Comment by UKChris-osm** [comment]
How is a release made available? Is it done via an NPM command?

**Comment by bhousel** [comment]
> How is a release made available? Is it done via an NPM command?

I put some info here: https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers#releasing

https://nsi.guide will pull the latest files under `dist/*`
Anyone can run `npm run dist` to regenerate these.
