### ISSUE TITLE
Preset file for StreetComplete

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5016]
After merging #5014 I noticed the following on the StreetComplete repository: 

"_// since we already read the JSON and it is so large, let's drop some properties that are_"
"_// (currently) not used, to make it a bit smaller: icon, imageURL_"

... if StreetComplete is currently trimming down a preset file, perhaps we could auto generate a stripped down file for them on our side?

**Comment by bhousel** [comment]
Good idea - can you link to the thing in StreetComplete where they trim down the preset file?

**Comment by bhousel** [comment]
oh looks like it's here:
https://github.com/streetcomplete/StreetComplete/blob/master/buildSrc/src/main/java/UpdateNsiPresetsTask.kt

If all they are doing is removing 2 properties, I don't think we need to make them a special file.

Also - it makes me nervous when people just pull a file off our `main` branch.
NSI publishes releases so downstream projects don't need to worry about breakage.

More info here: 
https://github.com/osmlab/name-suggestion-index/wiki/Downloading-the-Data

They should probably fetch the latest _stable_ presets with a semver-range URL like:
`https://cdn.jsdelivr.net/npm/name-suggestion-index@5/dist/presets/nsi-id-presets.min.json`

**Comment by matkoniecz** [comment]
Created https://github.com/streetcomplete/StreetComplete/issues/2731

And in this case extra release file is likely not the best idea, but thanks to @UKChris-osm  for caring about it!

Having own processing makes easy to change how file is generated with immediate effects rather than waiting for PR review, regeneration of released files and so on.

**Comment by UKChris-osm** [comment]
> They should probably fetch the latest stable presets with a semver-range URL like:
https://cdn.jsdelivr.net/npm/name-suggestion-index@5/dist/presets/nsi-id-presets.min.json

This has been done via: [193a969](https://github.com/streetcomplete/StreetComplete/commit/193a969ad1db75b658cd6d5302251a6bd4d5f675)
