### ISSUE TITLE
What are the sources of the data?

### ISSUE THREAD

**Issue by tuxayo** [osmlab/name-suggestion-index#5022]
It's useful to know for the reuse of the data because even though it's libre, some projects are very strict about the origin of the data. Due to the need to be reusable in every country. And thus need more info about the sources.

For example I guess Wikipedia is one of the sources for the exact way to write some names.
Same question for Wikidata.

**Comment by bhousel** [comment]
Here's an overview of the data pipeline :
- We process the OpenStreetMap planet file to produce "collected" data files in [`dist/collected/*`](https://github.com/osmlab/name-suggestion-index/tree/main/dist/collected).  These files contain counts of frequently occurring tag values.  (Per #2437 the OSM LWG has indicated that what we're doing does not produce a substantial extract of OpenStreetMap). (We'll call this _"collected data"_).
- We filter the collected data and merge them into the "category" files under [`data/*`](https://github.com/osmlab/name-suggestion-index/tree/main/data).  The category files (and the  [`dist/nsi.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/nsi.json), which is just a merge of all of them) are sourced from both the collected data and our contributors. (We'll call this _"NSI data"_)
- We lookup data from the Wikidata API that relates to the QIDs found the NSI data and save that as [`dist/wikidata.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/wikidata.json) and [`dist/dissolved.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/dissolved.json).  These files are sourced from both the NSI data and Wikidata.
- We build editor preset files [`dist/presets/*`](https://github.com/osmlab/name-suggestion-index/tree/main/dist/presets) which also contain a mix of NSI data and Wikidata.
- Any other files you find (for example [`dist/trees.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/trees.json), [`dist/matchGroups.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/matchGroups.json), [`dist/featureCollection.json`](https://github.com/osmlab/name-suggestion-index/blob/main/dist/featureCollection.json)) were created for this project by our contributors.
