### ISSUE TITLE
How to tag Las Vegas Loop

### ISSUE THREAD

**Issue by chuqtas** [osmlab/name-suggestion-index#5024]
For those not familiar with the loop - the simplest way to describe it is a private underground tunnel system with electric cars operating as taxis.  Or alternatively, a subway but with cars-on-demand instead of trains. 

I've posted about it here in detail - including a link to a video if anyone is unfamiliar: https://wiki.openstreetmap.org/wiki/Talk:Key:highway#Tags_for_Boring_Company_tunnel_at_Las_Vegas

I would like to add an entry to NSI for it but it doesn't fit any of the existing categories under /transit/route.
  
(The current ones are: aerialway, bus, ferry, light_rail, subway, train, tram, trolleybus, walking_bus)

Thoughts?

I expect the initial entry will look something like this:

```
{
  "properties": {
    "path": "transit/route/**?????**",
  },
  "items": [
    {
      "displayName": "LVCC Loop",
      "id": "[TBA]",
      "locationSet": {"include": ["us"]},
      "tags": {
        "network": "LVCC Loop",
        "network:wikidata": "Q106520630",
        "operator": "The Boring Company",
        "operator:wikidata": "Q28874479",
        "route": "**?????**"
      }
    }
  ]
}

```

**Comment by Identitaet** [comment]
Well they call it LOOP (As in that's the type of transit)
I'm unsure as to what degree that's an accepted term and if it would cause problems with falsely tagged routes which go in a circle.
So either route=LOOP
Or
route=loop

~route=shitty_subway_replacement~ is probably not wanted 😆

**Comment by chuqtas** [comment]
I did consider route=loop but held back, thinking it might be considered more of a Boring Company specific name, but fortunately you came up with the same idea so I'll use that :)  Besides I don't think any other companies are planning anything similar at the moment!

And to digress, I recently added some hydrogen networks to NSI and restrained myself from adding my personal views on the hydrogen cars... trying to keep an NPOV like on Wikipedia :P

**Comment by bhousel** [comment]
I think since it doesn't actually exist yet, and its the only thing of it's kind in the world, we don't need to worry about it for name-suggestion-index.  This project is really more about capturing the common tags of frequently occurring features.

It might be worthwhile to ask on the tagging mailing list what other people think the Las Vegas Loop should be tagged as.
