### ISSUE TITLE
npm run build auto-remove newly added matchName

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5047]
This is the commit that a matchName was added to a supermarket

https://github.com/osmlab/name-suggestion-index/commit/d5cbdc28cca6fada61318d4ca7b1b7b28d2683b4#diff-478a5b2128693e6e200c127873c89cd5231498ceca1ba5df34691011fb656d4eL614

And when I run ```npm run build``` , this matchName will be delete by script.

https://github.com/osmlab/name-suggestion-index/commit/1c020ae707516c54eb34ab5e6c9a7d28a7040017#diff-478a5b2128693e6e200c127873c89cd5231498ceca1ba5df34691011fb656d4eL614

But the matchName is not the same as brand name. So will this special syntax in name have effect when matching items?

**Comment by bhousel** [comment]
Yes this is expected..

https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#matchNames-matchTags

> We don't need to add matchNames for:
> 
> - variations in capitalization, punctuation, spacing (the middots common in Japanese names count as punctuation, so "V・ドラッグ" already matches "vドラッグ")
> - variations that already appear in the name, brand, operator, network.
> - variations that already appear in an alternate name tag (e.g. alt_name, short_name, official_name, etc.)
> - variations that already appear in any international version of those tags (e.g. name:en, official_name:ja, etc.)
> - variations in diacritic marks (e.g. "Häagen-Dazs" already matches "Haagen-Dazs")
> - variations in & vs. and
> 
> Bonus: The build script will automatically remove extra matchNames and matchTags that are unnecessary.
> 

So in the above case "BonÀrea" is considered same as "bon area" or even "bOn! ArEa!".  
(Internally, the matcher code creates its index based on the simplified name, `bonarea`)

**Comment by LaoshuBaby** [comment]
I can rest assured that!

Thank you for your patience! 

It seems that I mistakenly merged an unnecessary PR without understanding the principle of matchName. This wrong will not happen next time!
