### ISSUE TITLE
Add Local Insurance Chain

### ISSUE THREAD

**Issue by rspinabella** [osmlab/name-suggestion-index#5048]
Hello,
I've been noticing billboards for this insurance company and I thought I would like to suggest adding it to nsi.guide at this URL https://nsi.guide/?t=brands&k=office&v=insurance . Can you guys help me out with this, not exactly sure what information I need to provide?
brand=Insurance Navy Brokers
brand:wikidata=Q106564453
name=Insurance Navy Brokers
office=insurance

**Comment by bhousel** [comment]
Hi @rspinabella 👋 
This looks like a good addition to the index..

It would go in this file:
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/office/insurance.json

You can use the GitHub editor to paste it anywhere in the file.  The next time someone runs `npm run build` it will get checked and have an `id` property generated.

Our project wiki contains the [contributing guide](https://github.com/osmlab/name-suggestion-index/wiki/Contributing) and lots of other info that will get you started!

**Comment by rspinabella** [comment]
Great, I just added it! Thanks

**Comment by UKChris-osm** [comment]
Hi @rspinabella, when you say you've just added it, have you added it to your own forked copy? If so, you will need to submit a "_pull request_" for us to be able to merge it into the Name Suggestion Index 👍

**Comment by rspinabella** [comment]
The official name on OSM is Insurance Navy Brokers, I think they go by insurance navy for short.

**Comment by rspinabella** [comment]
Ok, I created a pull request https://github.com/osmlab/name-suggestion-index/pull/5049

**Comment by UKChris-osm** [comment]
Thanks for this @rspinabella, all merged 👍
