### ISSUE TITLE
Multiple unrelated transit agencies are under the same entree: PAT

### ISSUE THREAD

**Issue by kolgza** [osmlab/name-suggestion-index#5052]
https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=pat

The transit agencies are:
- Port Authority of Allegheny County (Q7230500)
- Petersburg Area Transit (Q7178176)
- Prince Albert Transit (Q7243789)

**Comment by kolgza** [comment]
Port Authority of Allegheny County should be abbreviated to `PAAC`.

**Comment by LaoshuBaby** [comment]
> 
> 
> https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=pat
> 

But there are only one ```PAT```

![图片](https://user-images.githubusercontent.com/42690037/117614651-327c8280-b19b-11eb-9169-eb9bf1a67204.png)

**Comment by kolgza** [comment]
Click "Search Overpass Turbo"
![image](https://user-images.githubusercontent.com/46303203/117661183-08f83280-b16c-11eb-8148-8b33664b7011.png)

**Comment by bhousel** [comment]
In 3165768 I split "PAT" into the three items.. Check it out!
I gave each item a circular locationSet around where the transit company operates and they all `matchName` "PAT", so they will be matched in OSM.
