### ISSUE TITLE
Please help Add

### ISSUE THREAD

**Issue by YuriyBorodulya** [osmlab/name-suggestion-index#5056]
pharmacy.json
{
      "displayName": "Аптека Твоєї Родини",
      "id": "aptekayf-996e17",
      "locationSet": {"include": ["ua"]},
      "matchNames": ["аптека твоей родини", "твоєї родини", "атр"],
      "tags": {
        "amenity": "pharmacy",
        "brand": "Аптека Твоєї Родини",
        "brand:wikidata": "Q106424150",
        "healthcare": "pharmacy",
        "name": "Аптека Твоєї Родини",
	"name:uk": "Аптека Твоєї Родини",
        "name:en": "Pharmacy Your Family"
      }
},

**Comment by bhousel** [comment]
Thanks @YuriyBorodulya  - not sure why you closed it but it seems ok to me, so I added it in d8fb3a19a
