### ISSUE TITLE
Clarify between IGA (US/worldwide) and IGA (Australia) - supermarket brands

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#5076]
Was #1695

In Australia, though the branding is very similar, https://en.wikipedia.org/wiki/IGA_(Australian_supermarket_group) / wikidata Q5970945 is understood to be a brand of Metcash Limited; even if the stores are independent.

I believe this is distinct enough from the current use of IGA - https://en.wikipedia.org/wiki/IGA_(supermarkets) - that for editing in the australian locale; it should default to that version rather than the currently implemented one.

From the main article, it might be also worth splitting between IGA (Canada) and others.
> In Canada (apart from British Columbia), IGA is a group of independent grocers supplied by Sobeys, which franchises the name. Acquired by Sobeys as part of its purchase of the Oshawa Group Ltd., it now operates primarily in Quebec.

**Comment by lkernan** [comment]
I separated the Australian IGA from the US version in March.
https://github.com/osmlab/name-suggestion-index/commit/4f14014540268bb3b88d8c0b32aa912f197d5472

There is also a separate entry now for Ritchies as well.

**Comment by CloCkWeRX** [comment]
Ah nice; must not have hit production yet
