### ISSUE TITLE
Include brand for Drakes Supermarkets (Australian locale)

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#5077]
https://en.wikipedia.org/wiki/Drakes_Supermarkets - 60+ locations, and as of 2019 went through a rebranding way from a number of subsidaries.
https://www.wikidata.org/wiki/Q48988077

**Comment by UKChris-osm** [comment]
Thanks for the suggestion @CloCkWeRX, I have added this via the [fda3660](https://github.com/osmlab/name-suggestion-index/commit/fda366005b46760f19405bc10bb3d26051720fb6) update.
