### ISSUE TITLE
Clarification needed: companies without wikidata record

### ISSUE THREAD

**Issue by Contrib1043** [osmlab/name-suggestion-index#5102]
Clarification needed on the NSI specification:

**Is it ok to add brands even if they have no wikidata record yet?** 

What's the preferred proceeding in such situations: include in NSI even without wikidata record or manually create wikidata record?

Looking forward for guidance..

**Comment by Contrib1043** [comment]
e.g. https://www.orovivo.de/de_DE/Unsere-Filialen/

**Comment by Identitaet** [comment]
Ideally we'd just add it to wikidata

**Comment by bhousel** [comment]
> Is it ok to add brands even if they have no wikidata record yet?

Yes this is allowed, but without a linked Wikidata qid, an item here won't get a generated preset for other projects like iD, StreetComplete, JOSM.

Items that are notable enough for NSI should be notable enough for Wikidata - so if you create one, make sure that it has supporting references.

**Comment by Contrib1043** [comment]
Appreciate your feedback and explanations, thanks!

> Items that are notable enough for NSI should be notable enough for Wikidata - so if you create one, make sure that it has supporting references.

That's my only concern: after scanning square miles of German pedestrian areas I identified some pretty common local stores here, which are very present on ground and you'll find probably in any major pedestrian area in Germany, although these companies don't necessarily fulfill **wikipedia** relevance criteria (e.g. since they are only part of larger corporates, they're just active in one state and so on).

Since I think NSI would benefit from inclusion though, I'll create a **wikidata** record for them to make this information available for editors like iD and JOSM if this is the preferred way.

**Comment by bhousel** [comment]
> Since I think NSI would benefit from inclusion though, I'll create a **wikidata** record for them to make this information available for editors like iD and JOSM if this is the preferred way.

This seems ok to me.  As long as the brand exists a few dozen times, and has something written about it in the news, it should be notable enough for wikidata.
