### ISSUE TITLE
Internet cafe Hot Spot looks like a generic name.

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5103]
Internet cafe [Hot Spot](https://github.com/osmlab/name-suggestion-index/blob/5fe51617a2d6faa8aff1a4995bbf889d1371b098/data/brands/amenity/internet_cafe.json#L38) looks like a generic name.

**Comment by bhousel** [comment]
Yes it looks like someone mistakenly added a lot of these around here:  https://overpass-turbo.eu/s/183m
They probably meant to map access points, not "internet cafes".
