### ISSUE TITLE
ITV looks like a generic name

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5104]
[ITV](https://github.com/osmlab/name-suggestion-index/blob/7eef559e630207ce727dbb0da6b1cc50b7c0fa8f/data/brands/amenity/vehicle_inspection.json#L58) looks like a generic name for a vehicle inspection. It's the short form for "Inspección técnica de vehículos" but I don't know if there is an actual brand behind it. Maybe some Spanish contributors can double check...

**Comment by bhousel** [comment]
Interesting - I feel like it's reasonable for there to be a dedicated `brand:wikidata` for the state-run ITV in Spain:
https://itv.com.es/

But right now the only wiki resources I can find are written with generic "vehicle inspection" content: 
https://es.wikipedia.org/wiki/Inspecci%C3%B3n_t%C3%A9cnica_de_veh%C3%ADculos
https://www.wikidata.org/wiki/Q978659

**Comment by KBNorth** [comment]
It's the type of test that is done to inspect the vehicles.

**Comment by UKChris-osm** [comment]
Is ITV in Spain an actual company / organisation that runs the testing sites, or does ITV simply make the rules of what needs to be tested - similar to a UK MOT, which are defined by government guidelines, but mostly carried out by the private sector, such as by [Kwik Fit](https://nsi.guide/index.html?t=brands&k=shop&v=car_repair#kwikfit-df570c), [Halfords Autocentre](https://nsi.guide/index.html?t=brands&k=shop&v=car_repair#halfordsautocentre-3b6d68), [ATS Euromaster](https://nsi.guide/index.html?t=brands&k=shop&v=car_repair#atseuromaster-3b6d68) etc.
