### ISSUE TITLE
"The Cutting Room" looks like a generic name for hairdressers

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5114]
hairdresser name [The Cutting Room](https://github.com/osmlab/name-suggestion-index/blob/62e543b102f4c49cada7ee6bf2dbc7b95fb60d29/data/brands/shop/hairdresser.json#L509) seems to be used for several different independent hairdressing saloons.

**Comment by bhousel** [comment]
Thanks @kjonosm I just removed it..

I wanted to get rid of "The Barbers" too - but it turns out that one is actually a chain in the Pacific Northwest!
https://thebarbersonline.com/locations/
They don't have a wiki presence yet.
