### ISSUE TITLE
Add "The Halal Guys"

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#5130]
Wikidata: https://www.wikidata.org/wiki/Q10846129

amenity=fast_food
name=The Halal Guys
wikidata=Q10846129
diet:halal=yes
cuisine=chicken;falafel;gyros

**Comment by matkoniecz** [comment]
@LaoshuBaby Is it deliberate that they are marked as having halal food but not only halal food?

It seems likely that it should rather be ` diet:halal=only`
