### ISSUE TITLE
Add Lotte Hotel: nsi guide(Korea)

### ISSUE THREAD

**Issue by chrish8510** [osmlab/name-suggestion-index#5146]
official website: https://www.lottehotel.com/seoul-hotel/en.html

instagram: https://www.instagram.com/lottehotel_seoul/

facebook: https://www.facebook.com/lotteseoul

youtube: https://www.youtube.com/user/LotteHotels

official blog(it's in Korean): https://blog.naver.com/lotte_hotels

Wikidata: [Q326720](https://www.wikidata.org/wiki/Q326720)

**Comment by sh3rins** [comment]
They have multiple restaurants

**Comment by bhousel** [comment]
done in #5165
