### ISSUE TITLE
ATM / AMT (Barcelona)

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5147]
I've just noticed two similar networks in Barcelona, and I think one is an error:

- [ATM (Barcelona)](https://nsi.guide/index.html?t=transit&k=route&v=bus#atm-cbced8) (correct)
- [AMT (Barcelona)](https://nsi.guide/index.html?t=transit&k=route&v=bus#amt-cbced8) (incorrect & should be matched with the above)

... would anybody disagree?

**Comment by UKChris-osm** [comment]
This was fixed by a local mapper (95893799)[https://www.openstreetmap.org/changeset/95893799] so I have fixed it here via [207b19d](https://github.com/osmlab/name-suggestion-index/commit/207b19ddd21fef1697450cfc81bd63788a1a27dd)

**Comment by bhousel** [comment]
Thanks @UKChris-osm - This looks great 👍 

I checked overpass and the Milan and Barcelona clusters are the main ones.
https://overpass-turbo.eu/s/19UO

There is a `network=ATM` in India that is just an ATM probably mistagged..
And a `network=ATM` on a bus route in Guayaquil, Ecuador.  

I can't actually tell if this is a bus route or a lone mistagging, but maybe someone with local knowledge in Ecuador could figure it out.  It might be a local bus route run by the Guayaquil transportation department and operated by Metrovía.  https://www.atm.gob.ec/
