### ISSUE TITLE
MAPCO

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#5149]
https://www.mapcorewards.com/store-locator

I guess there may be multiple related brands. Currently owned by https://en.wikipedia.org/wiki/Empresas_Copec and doesn't have a separate Wikidata/Wikipedia entry.

**Comment by UKChris-osm** [comment]
Is Mapco just a gas station brand?

I've started a Wikidata for it: [Q107589462](https://www.wikidata.org/wiki/Q107589462)

**Comment by maxerickson** [comment]
Their Twitter mentions several types of location: https://twitter.com/MAPCO

**Comment by MuskanTripathi** [comment]
> Is Mapco just a gas station brand?
> 
> I've started a Wikidata for it: [Q107589462](https://www.wikidata.org/wiki/Q107589462)

Mapco is owned by Chile's COPEC, Mapco's competitive advantage is that it operates under seven brands: Mapco Express, Mapco Mart, East Coast, Fast Food and Fuel, Favorite Markets, Delta Express and Discount Food Mart. The chain's former owner, Delek US Holdings, sold the Mapco retail assets to the Santiago, Chile-based energy conglomerate in 2016. Mapco's c-stores offer a standard range of convenience items, including cigarettes, snacks, drinks and beer and, increasingly, proprietary made-to-order meals. Some units also feature a branded quick-service restaurant partner, with brands that include Subway, Quiznos and Blimpie. Most of the chain's stores are freestanding structures with attached gas stations that are generally located on heavily trafficked intersections.

**Comment by aayush920** [comment]
Hi ! I would like to work on this  issue but I would like some guidance.

**Comment by bhousel** [comment]
Hey @aayush920 welcome 👋 
We have some contributing information on the project wiki: https://github.com/osmlab/name-suggestion-index/wiki
You can also look on https://nsi.guide for items in our index which need a link to a wikidata item or which need a better location.

**Comment by aayush920** [comment]
Hey @bhousel 
I have one query. It seems that mapco doesn't have a wikipedia page. Should I just leave it or add the wikipedia page of its parent company "Delek US".
Thanks in advance.

**Comment by bhousel** [comment]
> I have one query. It seems that mapco doesn't have a wikipedia page. Should I just leave it or add the wikipedia page of its parent company "Delek US".

It's ok to skip it.  The `brand:wikidata` tag is the important tag, and the `brand:wikipedia` is optional.

**Comment by aayush920** [comment]
I have generated a pull request. Please check whenever possible.

**Comment by arch0345** [comment]
Closed with #5255
