### ISSUE TITLE
Dunelm

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#5157]
Dunelm is a "British home furnishings retailer". It was added as shop=furniture however I think it would be better suited to shop=interior_decoration (or perhaps houseware). Have a look at Google Images and you'll see the inside of their shops.

Of the 117 OSM objects with the name Dunelm and shop=*, currently 57 are furniture, 29 interior_decoration, 21 houseware, 5 department store, 2 fabric, plus homeware, household_linen, and soft_furnishings.

I think a lot of those furniture tags will have been from people clicking iD's upgrade tag issue prompt. IMO there is enough there to suggest that is the incorrect tag - as the main focus of the shops isn't selling furniture (like for example Ikea).

**Comment by trigpoint** [comment]
I agree with Michael
Furniture is a very small part of their range.

They are mostly soft furnishings and homeware. They sell bedding and curtains, they have a factory which makes made to measure curtains.

They also sell cookware and a large range of fabrics, a feature of their shops is always a large table for measuring and cutting fabrics.

**Comment by UKChris-osm** [comment]
I'd probably go with "_shop=interior_decoration_" for Dunelm myself.

**Comment by UKChris-osm** [comment]
Closed via [855f791](https://github.com/osmlab/name-suggestion-index/commit/855f7911221e45beac8619a4cb3f4d285a277788)
