### ISSUE TITLE
Include route_master relations in validation

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5184]
Maybe an iD issue? iD now checks for incomplete or inconsistent tagging of route relations. Unfortunately this check doesn't seem to also cover the corresponding parent [route_master relations](https://wiki.openstreetmap.org/wiki/Relation:route_master). Is there a way to also include those when validating?

**Comment by bhousel** [comment]
Oh interesting - yes that might go here.  I hadn't thought about adding items for the `route_master` relations before, and my impression was that they are kind of rare.  e.g. we would not want to auto-generate a `route_master` for every `route=*`.

**Comment by kjonosm** [comment]
On a quick look, I'd say they are in widespread use - in Germany anyway. Nearly all two way routes have a corresponding route_master.

You might want to have a look at https://ptna.openstreetmap.de a qa tool with lots of checks used in quite a few countries. The problem described above has prompted validation errors over there.

**Comment by osm-ToniE** [comment]
@bhousel 
>  e.g. we would not want to auto-generate a route_master for every route=*.

Oh no, the issue is just that the 'network' tag of an existing route_master differs from the 'network' tag of the route members after the changes.

Example: https://ptna.openstreetmap.de/results/DE/NW/DE-NW-AVV-Analysis.html#bus_234

Do not auto-create route_masters, that doesn't make sense.

**Comment by bhousel** [comment]
> Do not auto-create route_masters, that doesn't make sense.

Yes I agree!  But I think I can add something on the iD side so that if it _sees_ a `route_master`, it can just treat it like a `route`.

**Comment by osm-ToniE** [comment]
Yeah would be great to have this ASAP, number of problematic cases is exploding now
