### ISSUE TITLE
ソフトバンクショップ misspelling

### ISSUE THREAD

**Issue by Tjekrova** [osmlab/name-suggestion-index#5195]
The tags for the brand ソフトバンクショップ (SoftBankShop), have the thrice repeated misspelling _oficial_name=_ instead of _official_name=_.

[Direct link](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=oficial#softbank-0a8be9)

**Comment by UKChris-osm** [comment]
Thank you @Tjekrova - I have corrected this 👍
