### ISSUE TITLE
Otto's is shop=variety_store, not shop=department_store

### ISSUE THREAD

**Issue by dafadllyn** [osmlab/name-suggestion-index#5196]
https://github.com/osmlab/name-suggestion-index/blob/910bb38d02a80d4097acbea04e82be28cfcd45d7/data/brands/shop/department_store.json#L915-L926

Otto's is not a department store, but a discount store (`shop=variety_store` in OSM). (It buys remaining stocks from other retailers – about anything: from drinks to clothes to sports equipment to furnitures – and resells them at a lower price than the original price.)

**Comment by dafadllyn** [comment]
@kjonosm: Thank you! ☺️

**Comment by UKChris-osm** [comment]
@kjonosm in this instance, you would also need to add **"named": ["otto's"]** to the exclusion list at the top of "_department_store.json_" otherwise it will keep returning :)

**Comment by bhousel** [comment]
> @kjonosm in this instance, you would also need to add **"named": ["otto's"]** to the exclusion list at the top of "_department_store.json_" otherwise it will keep returning :)
> 
> This is caused by the planet data currently having Otto's appear more than 50 times as a department store, and so will automatically be added every time "_npm run build_" is actioned.

I think even better than that would be to add `"matchTags: ["shop/variety_store"]` to the new Otto's entry.  Then it will match on that less preferred tag as well.

**Comment by UKChris-osm** [comment]
> I think even better than that would be to add `"matchTags: ["shop/variety_store"]` to the new Otto's entry. Then it will match on that less preferred tag as well.

Add `"matchTags: ["shop/variety_store"]`?? I thought being in the variety_store.json file was sufficient?? Or have I misunderstood?

**Comment by bhousel** [comment]
> Add `"matchTags: ["shop/variety_store"]`?? I thought being in the variety_store.json file was sufficient?? Or have I misunderstood?

oh sorry- I meant to add "shop/department_store" so it would match that also..

**Comment by UKChris-osm** [comment]
Oh I see what you mean now, yes that make sense :)
