### ISSUE TITLE
Verizon Wireless vs Verizon Authorized Dealer

### ISSUE THREAD

**Issue by cicku** [osmlab/name-suggestion-index#5200]
These two are not the same, but they are currently under the same tag. I've seen numerous Verizon tags being used on dealers.

For example: Cellular Sales/Wireless Zone are authorized by Verizon, but they are not Verizon.

Their relation with Verizon seems to be shady in my opinion.

My suggestion is:

![image](https://user-images.githubusercontent.com/686438/128224165-3b88a2ae-c6f7-45e8-9b18-7d51e92b6bca.png)

However it is also feasible to add these dealers into NSI. What should be done next under NSI?

**Comment by 1ec5** [comment]
Branding varies quite a bit for Verizon Authorized Dealers. I’ve seen some where you have to squint at the sign or step inside to notice that it isn’t a company-owned store and others that have a distinct name and relegate the Verizon logo to a sticker on the storefront window.

Is there a corresponding tag for “Franchisor”, or would it affect the `brand:wikidata` value? The latter would be more complicated than adding a separate NSI entry and Wikidata entity for Verizon Authorized Dealers.

**Comment by bhousel** [comment]
Hmm I dont know the best solution.  I already think there are far too many fields on this screen.

When I'm not sure, I just try to consider how I'd want the POI to display on a map pin or whether anyone is likely to use this data for map making.  If the POI is not a true "Verizon Wireless" people shouldn't be picking the preset, right?

**Comment by bhousel** [comment]
> If there are separate Verizon and Verizon Authorized Dealer presets, then I suppose some mappers will choose carefully based on what they can determine. But would this distinction be useful to a user searching for Verizon stores if not every mapper is able to do that consistently?
> 
> For what it’s worth, whenever I map a Verizon Authorized Dealer and can tell that it isn’t an O&O, I change the `name` from “Verizon Wireless” to the franchisee name. That requires me to use the raw tag editor, because iD not only locks the Name field but also replaces the name with “Verizon Wireless” when I apply the preset to an existing POI.

Yeah this really is confusing.  There is actually a "Verizon" store in my town and I had no idea it was an authorized reseller without checking Google Maps.  I'd rather not make 2 presets, but I can definitely make it so the `name` field isn't locked.

<img width="1661" alt="Screen Shot 2021-08-10 at 2 10 59 AM" src="https://user-images.githubusercontent.com/38784/128817002-9e49d68f-5576-4d89-9a14-6a9d930d470c.png">

**Comment by cicku** [comment]
Another example:

![image](https://user-images.githubusercontent.com/686438/128878126-2e013266-146a-463f-af92-3a0978bfc427.png)

**Comment by bhousel** [comment]
Going to close this issue, as the NSI situation is probably as good as it will get.  

We provide a preset for branded Verizon Wireless stores, and we've configured this item as having a flexible `name` so that mappers can replace it with an "authorized dealer" name if they want to.
