### ISSUE TITLE
De Lijn (Flemish, Belgian transport agency) links to the french wikipedia page somehow

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/name-suggestion-index#5201]
Hi,

While the actual source file seems correct (linking to the NL, dutch wikipedia language. Since De Lijn is only active in the Flemish/dutch speaking part of belgium):
https://github.com/osmlab/name-suggestion-index/blob/d2531645f52c6056d0e853fd1e5d7f061f2ebc8b/data/transit/route/tram.json#L93-L102
(there's multiple De Lijn entries)

But on the nsi guide and iD it shows the FR wikipedia tag:
https://nsi.guide/index.html?t=transit&k=highway&v=bus_stop&tt=lijn

**Comment by arch0345** [comment]
I believe bus stops get their Wikipedia tags from bus.json, instead of tram.json you linked in this issue. After a bit of searching bus.json still has the French wikipedia pages linked. Do you want me to change these to 'nl'?

**Comment by thibaultmol** [comment]
Oh yeah, indeed I was looking at the wrong file. Feel free to change those yeah!
