### ISSUE TITLE
Brazil Brands 2

### ISSUE THREAD

**Issue by Playzinho** [osmlab/name-suggestion-index#5202]
Hey, here are some Brazilian brands 

amenity=bank
brand=BRB
brand:wikidata=Q4854119
brand:wikipedia=:Banco de Brasília
name=Banco de Brasília

**Comment by Playzinho** [comment]
amenity=atm
brand=BRB
brand:wikidata=Q4854119
brand:wikipedia=:Banco de Brasília
name=Banco de Brasília

**Comment by Playzinho** [comment]
amenity=fastfood
brand=Giraffas
brand:wikidata=Q5564100
brand:wikipedia=:Giraffas
name=Giraffas

**Comment by Playzinho** [comment]
amenity=fastfood
brand=Spoleto
brand:wikidata=Q7578935
brand:wikipedia=:Spoleto (Restaurante)
name=Spoleto
cuisine=italian

**Comment by Playzinho** [comment]
amenity=fastfood
brand=China in Box
brand:wikidata=Q18463999
brand:wikipedia=:China in Box
name=China in Box
cuisine=chinese

**Comment by arch0345** [comment]
Which Wikipedia language should I use for the brand:wikipedia tags, English or Portuguese?

**Comment by bhousel** [comment]
> Which Wikipedia language should I use for the brand:wikipedia tags, English or Portuguese?

Portuguese if its available
