### ISSUE TITLE
Power company operators, for substations etc.

### ISSUE THREAD

**Issue by arrival-spring** [osmlab/name-suggestion-index#5218]
Often when I am surveying I like to add power substations to the map.

I notice that there is nothing for any power company, is adding this something that would be accepted?

The sorts of tags would normally be something like
power=substation
operator=*
operator:wikipedia=*
operator:wikidata=*

**Comment by bhousel** [comment]
I agree, I intended to add these a while ago and never got around to it.. 
We collect them from the planet already so it would be really easy to add.

**Comment by bhousel** [comment]
I did this and just included them in the v6.0.20210809 release ⚡ 

Check out https://nsi.guide/index.html?t=operators to browse through the new categories:
 - power/generator
 - power/line
 - power/minor_line
 - power/plant
 - power/substation
 - power/transformer
 - route/power

**Comment by arrival-spring** [comment]
Great, thanks very much! I'll open a PR to add more details to my local power company then.
