### ISSUE TITLE
Add EAT to the dissolved list

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#5219]
As per https://osm.mathmos.net/ghosts/eat/

https://en.wikipedia.org/wiki/Eat_(restaurant)

I think this needs a Wikidata change?

> As of March 2020, there are two remaining non-UK entities of EAT., Paris Gare du Nord (under franchise partner SSP Group) and in Spain (under franchise partner Ibersol). 

So does this just need the location updating?

**Comment by bhousel** [comment]
If someone updates their Wikidata page [Q5331219](https://www.wikidata.org/wiki/Q5331219) with a "Dissolved Date" it will show up in our dissolved list next time I run the wikidata sync script.  I think it's probably ok to leave it in the index for a while until all the EATs have been removed from OSM.

**Comment by Adamant36** [comment]
> If someone updates their Wikidata page Q5331219 with a "P576 - Dissolution date" claim, it will show up in our dissolved list next time I run the wikidata sync script. I think it's probably ok to leave it in the index for a while until all the EATs have been removed from OSM.

I'm not sure that would work because there's still two restaurants.

**Comment by peternewman** [comment]
> I'm not sure that would work because there's still two restaurants.

We could remove GB from the locationSet, but then it doesn't need to be dissolved. Or split the wikidata if its now in two different states.
