### ISSUE TITLE
ウエルシア and ウエルシア薬局 are the same place

### ISSUE THREAD

**Issue by nicolasmaia** [osmlab/name-suggestion-index#5223]
They need to be merged.

**Comment by arch0345** [comment]
Which one should be kept and which one should be removed?

**Comment by nicolasmaia** [comment]
ウエルシア薬局 seems to be the proper name:
https://www.ecosia.org/search?q=%E3%82%A6%E3%82%A8%E3%83%AB%E3%82%B7%E3%82%A2

**Comment by arch0345** [comment]
While searching these on nsi.guide I also found ハックドラッグ, which is linked to the same Wikidata page. Do you know if this is also the same brand or is it a different brand of the same parent company?

**Comment by nicolasmaia** [comment]
The relevant Wikipedia page says ハックドラッグ is a brand name that has been merged with ウエルシア薬局, so I think they should all just say ウエルシア薬局.
