### ISSUE TITLE
Multiple Aurora Energy entries

### ISSUE THREAD

**Issue by chuqtas** [osmlab/name-suggestion-index#5228]
Under operators/power/transformer and operators/power/substation, there are three companies listed named Aurora Energy:

Aurora Energy (Alaska)
auroraenergy-9a842a

Aurora Energy (New Zealand)
auroraenergy-05e84a

Aurora Energy (Tasmania)
auroraenergy-ace77b

Each is a separate business which happens to have the same name, each correctly linked to a discrete Wikidata entry.

The Overpass turbo search for each presumably searches by name, since they give the same result, which is entirely infrastructure in New Zealand.

I'm aware that the Tasmanian company is a retailer only (i.e. does not manage physical infrastructure) which would explain nothing there - so it can probably be removed completely.  I thought the Alaskan company would be in the same situation (given how nothing appears in Overpass Turbo search) but according to their website they appear to have a generation facility.

Is there an easy way to do a bulk change of the NZ infrastructure to definitively align it to the NZ company?  Do we need to wait for the the next revision of the NSI data in OpenStreetMap?

**Comment by arch0345** [comment]
Thanks for letting me know about the Tasmanian company not operating substations/transformers. I'll remove the Tasmanian company from the index.

As for the two remaining companies, I made sure to add locationSets when distinguishing these to these to ensure that only the correct one will show up in their respective country.
