### ISSUE TITLE
Wrongly using old_name for identification

### ISSUE THREAD

**Issue by Rovastar** [osmlab/name-suggestion-index#5229]
I am a great fan of this feature and use it a lot in ID however in recent weeks it has gone horribly wrong in the UK at least.

It is suggesting changed based on the old_name tag. 

Lets say the store was a McDonalds and now it is myOwnBurgerPlace without a NSI it is suggesting changing it. This is happening all over the place.

e.g. this node https://www.openstreetmap.org/node/5345720671 it will suggest changing back to a Burger King which it is not anymore.

Honestly, I am not sure this is the correct place to post this.
 If it is this project or some part of OSM website project or one of the ID project websites but I think this is the correct place if not please let me know.

**Comment by bhousel** [comment]
Thanks for reporting, I fixed this upstream already in https://github.com/openstreetmap/iD/pull/8618
There will probably be a release soon that includes it.

**Comment by Rovastar** [comment]
Nice one thank you. Not sure who thought old_name would be good but anyway hopefully not too much damage done. Everywhere around me has (mutiple) old_name tags so it is light up like a christmas tree in ID,
