### ISSUE TITLE
validator complains about valid tag

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5230]
Why does the validator suggest to remove `internet_access=yes`?
See here: https://www.openstreetmap.org/node/4423364915
![Bildschirmfoto 2021-08-14 um 16 11 15](https://user-images.githubusercontent.com/51236777/129449098-7ad7f414-be46-463f-86f7-1e6b24eed458.png)

**Comment by bhousel** [comment]
Oh yeah this is https://github.com/openstreetmap/iD/issues/8615 which is fixed in https://github.com/openstreetmap/iD/pull/8618 .. There will probably be an iD release soon that includes this fix.
