### ISSUE TITLE
Charles Schwab

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5231]
I'm not sure whether to add [Charles Schwab](https://en.wikipedia.org/wiki/Charles_Schwab_Corporation) in amenity=bank, office=financial, or both. I noticed that the majority of branches are tagged with either of these two.

**Comment by tas50** [comment]
That should be financial advisor. You can get a checking account but it's linked to your investment account

**Comment by arch0345** [comment]
Ok, I'll add it to office=financial_advisor
