### ISSUE TITLE
npm run wikidata

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5242]
If I understand it correctly, running "_npm run wikidata_" will fetch data from Wikidata, and also fetch logos from Facebook.

Fetching logos from Twitter will only occur if the individual running the above has a log in for Twitter, and has these log in details stored somewhere in a secrets file, is that correct?

In the same way, syncing / uploading NSI data to Wikidata (such as ID's) will only occur if the individual running the above command has a Wiki* log in, again stored in a secrets file?

**Comment by bhousel** [comment]
Yes, my `secrets.json` file looks like this:

```text
{
  "twitter": [
    {      
      "twitter_consumer_key": "••••••••••",
      "twitter_consumer_secret": "••••••••••",
      "twitter_access_token_key": "••••••••••",
      "twitter_access_token_secret": "••••••••••"
    },
    … + a few more of these to avoid the rate limit …
  ],
  "wikibase": {
    "username": "bhousel",
    "password": "••••••••••"
  }
}
```

If you ping me on Slack, I can set you up with the twitter app keys.. It would be great to have more people who can run the `npm run wikidata` script 👍

**Comment by UKChris-osm** [comment]
I don't have Slack unfortunately, but you're welcome to use my [OSM account](https://www.openstreetmap.org/user/UKChris) to message me.

Would I need my own Wiki / Twitter account(s) or could we set up an NSI account for use within the scrips?

**Comment by bhousel** [comment]
> Would I need my own Wiki / Twitter account(s) or could we set up an NSI account for use within the scrips?

I guess for now it's probably just fastest for you to use your own accounts..
https://github.com/osmlab/name-suggestion-index/issues/4727 is about setting up an NSI account at least for the wikidata updates.

**Comment by UKChris-osm** [comment]
Where would the secrets.json file go?

**Comment by bhousel** [comment]
> Where would the secrets.json file go?

It goes in the project root (same folder as `package.json` and `README.md` etc)
