### ISSUE TITLE
A cafe in China can't give proper suggestion

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5248]
This is a very long problem, and my mapper friends in China have PM me for this for a lot of time.

First, we can sure that this cafe is in NSI

![cafe.json](https://user-images.githubusercontent.com/42690037/130088225-ac2b5c5d-930b-4a44-981a-ea234dfcbf31.png)

But I can't find it in ID, and even I fill the name it don't give me any suggestion.

![searchbox](https://user-images.githubusercontent.com/42690037/130088394-cbebce9e-5aff-4675-a68e-96b4763b3c86.png)
![input name](https://user-images.githubusercontent.com/42690037/130088379-5b711677-24b2-46e8-a902-3fbf03867286.png)

---------
![图片](https://user-images.githubusercontent.com/42690037/130088754-9723ec2f-9342-44b2-abf8-666eb15faf49.png)
![图片](https://user-images.githubusercontent.com/42690037/130088769-640dd87e-640b-4147-b0e9-0fce6ef1debc.png)
![图片](https://user-images.githubusercontent.com/42690037/130088765-4ccc4a37-8a1a-428f-afa2-3dc2e2264957.png)

👆this have been a long time, and not only occur me.

**Comment by bhousel** [comment]
Oh! only items with `brand:wikidata` get turned into presets.. it's probably that?

**Comment by LaoshuBaby** [comment]
😅
Thank you for reason
Is there already have some way to find brand in specific country that missing wikipedia?



---Original---
From: "Bryan ***@***.***&gt;
Date: Fri, Aug 20, 2021 00:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [osmlab/name-suggestion-index] A cafe in China can't give proper suggestion (#5248)




 
Oh! only items with brand:wikidata get turned into presets.. it's probably that?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bryceco** [comment]
https://m.wikidata.org/wiki/Q107406476

**Comment by bhousel** [comment]
Searching on https://nsi.guide for "country code" `cn` and "incomplete" checked will show the list of things that we have in the index but with either no wikidata or some missing logo:

<img width="600" alt="Screen Shot 2021-08-19 at 1 50 27 PM" src="https://user-images.githubusercontent.com/38784/130119138-9808ce03-9adb-4d72-8d1e-4e7fa026d61e.png">
<img width="1535" alt="Screen Shot 2021-08-19 at 1 52 01 PM" src="https://user-images.githubusercontent.com/38784/130119369-67621fe5-645b-46d8-9aa1-805d05804a4b.png">

The country code search is not perfect right now, but it would find some things like this cafe that need attention.

Also I notice this cafe has:  "brand:wikipedia=zh:蜜雪冰城", so this is close to being fixed!  You can go to this wikipedia page and figure out the Wikidata from this link.. Every Wikipedia page has a associated Wikidata item.

<img width="989" alt="Screen Shot 2021-08-19 at 1 54 25 PM" src="https://user-images.githubusercontent.com/38784/130119938-73f24b87-d6ff-44e6-b21c-84370f3ca878.png"> 

Link goes here:
<img width="879" alt="Screen Shot 2021-08-19 at 1 57 17 PM" src="https://user-images.githubusercontent.com/38784/130120126-d20f430b-612f-4fa8-9da5-8a3ebf5dfe58.png">

**Comment by LaoshuBaby** [comment]
> 
> 
> Oh! only items with `brand:wikidata` get turned into presets.. it's probably that?

Sorry for this reason

But a brand haven't got a wikipedia is able to be suggested.

![图片](https://user-images.githubusercontent.com/42690037/130171412-a5012752-b611-44ce-ba9a-1cf5243dce87.png)

![图片](https://user-images.githubusercontent.com/42690037/130171455-d7de4332-2946-481a-a66b-16935b3bb2aa.png)

**Comment by LaoshuBaby** [comment]
Opps! I got……** It is my fault! I haven't complete ```brand:wikidata```! **

Thanks for everyone help me find this problem!

**Comment by bhousel** [comment]
> But a brand haven't got a wikipedia is able to be suggested.

yeah that is ok - 
It's `brand:wikidata` that is the real identifier .. `brand:wikipedia` is really just an optional extra tag for people to look at.

(I saw you removed the question above, but I think it is ok to have this answer here in case other people want to know) 

No worries, I'm glad to have you helping and improving the index 🤗
