### ISSUE TITLE
Refine locationSets for CATs

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5252]
iD is suggesting changing 'CAT' bus routes in Portland, OR from Columbia Area Transit to Canby Area Transit. Canby Area Transit only has one line from Woodburn, OR to Oregon City (south of Portland). Due to the larger area Columbia Area Transit covers, you could add an 'exclude' argument covering the location of Canby Area Transit as its lines do not reach there.

**Comment by LaoshuBaby** [comment]
Related #5182 #5205

**Comment by bhousel** [comment]
Thanks for letting us know @arch0345  -
CAT (Canby Area)- https://nsi.guide/index.html?t=transit&k=route&v=bus#cat-85ea0e
CAT (Columbia Area) - https://nsi.guide/index.html?t=transit&k=route&v=bus#cat-755fdf

They are currently set up to overlap.. I'll do some research today to figure out how to make these locations distinct.

**Comment by LaoshuBaby** [comment]
Maybe bacause I set the radius too big，you can set a proper value @arch0345

**Comment by bhousel** [comment]
I made the locationSets like this so the dont interfere:

<img width="849" alt="Screen Shot 2021-08-20 at 12 03 38 PM" src="https://user-images.githubusercontent.com/38784/130261915-b28692d1-fa42-4f2c-9f94-483594bafa69.png">

The next NSI update will have it 👍
