### ISSUE TITLE
Brand display name is generic name

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5254]
This is a single problem

In ```cafe.json```, it contain a Japanese cofe brand called ```珈琲館``` and have it detailed wikipedia, so we can sure that it is really called this name.
![图片](https://user-images.githubusercontent.com/42690037/130222165-ac31e9ef-d797-4ca9-9e2b-047bc2e4db29.png)

But we also can found a generic name ```"^珈琲館$"``` in this json. The word means "cafe" in Japanese.
![图片](https://user-images.githubusercontent.com/42690037/130222123-9905128d-0d54-4be0-911f-be54007354da.png)

So if I try to rename a cafe in Japan with name ```珈琲館```, iDeditor will only told me this name is doubtful.
![图片](https://user-images.githubusercontent.com/42690037/130221741-459db1ad-0960-4d7f-8e74-b35e29f45834.png)

That will cause Japan editor can't add a new branch store for this brand.

**Comment by LaoshuBaby** [comment]
This generic name is imported in https://github.com/osmlab/name-suggestion-index/commit/e4667208c70d446bc4d38030352867be95f86ede

And here are taginfo search result for 珈琲館:

![图片](https://user-images.githubusercontent.com/42690037/130222437-00c7b297-5abd-457b-8e6a-5d1aa5b18795.png)

We can see that most item with ```name=珈琲館``` have a ```brand=珈琲館```

So, I think we can remove this word from generic name list.

**Comment by bhousel** [comment]
> So, I think we can remove this word from generic name list.

Thanks @LaoshuBaby 👍  I removed it just now
