### ISSUE TITLE
Beales re opening

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#5260]
Beales/`beales-b626d5` has been re opening. The original company folded under debt, a [new company](https://find-and-update.company-information.service.gov.uk/company/12477776) now owns the brand and is opening [stores](https://beales.co.uk/pages/our-stores). [src](https://www.dorsetbiznews.co.uk/sold-for-5k-the-sum-owners-of-new-beales-paid-for-name-and-ip-going-back-generations/)

I'm not sure how Wikidata should be updated, should [Q4876141](https://www.wikidata.org/wiki/Q4876141) be about a defunct company, or updated to reflect the brands new ownership?

**Comment by UKChris-osm** [comment]
I think the same Wikidata article can be kept, as the Wikipedia article associated with it seems to have been updated with the new company details.

**Comment by Cj-Malone** [comment]
OK, looks like someone (you?) added another start date to it, I've just added the new Companies House number. Still not sure it's tagged right as Wikidata is not something I've done a deep dive into, but I'm sure it'll sort itself out.

I guess the next thing is to take it off the NSI dissolved list, so it can get back into editors.

**Comment by UKChris-osm** [comment]
Yes I just added a fresh inception date, but like you I'm not clued up on Wikidata so that could be the incorrect way of dealing with it.

I think it might be better to see what @bhousel has to say about the dissolved list, as simply deleting Beales may cause it to come back after the next "_npm run Wikidata_".

**Comment by bhousel** [comment]
> I think the same Wikidata article can be kept, as the Wikipedia article associated with it seems to have been updated with the new company details.

Agree with this 👍 

> Yes I just added a fresh inception date, but like you I'm not clued up on Wikidata so that could be the incorrect way of dealing with it.

This part I don't know too well what the best way to represent it in wikidata would be.  There is still a P576 - Dissolved Date property, so our `npm run wikidata` code will still consider Beales as dissolved.  There are maybe 2 ways to make that go away:
- Mark that claim with a "deprecated" rank - that's like saying that it's not dissolved anymore, and our code should no longer pick up the P576 claim.
- Add an additional P576 claim, with a special "novalue" value and date qualifiers on both claims to say when the brand was dissolved and then undissolved.  Our code should also ignore the "novalue" value.

I'm going to try the second option and then run the `npm run wikidata` today and see what it does.

**Comment by bhousel** [comment]
ok I ended up doing both of those things to [Beales Q4876141](https://www.wikidata.org/wiki/Q4876141), but our script still added it to the dissolved.json , sort of: 

https://github.com/osmlab/name-suggestion-index/blob/99070f7a8adb96f15966c9a82c13b824e8dff452/dist/dissolved.json#L49-L51

So it looks like I need to edit the script to specifically ignore novalue P576 claims.
