### ISSUE TITLE
Currently used network=call-a-bike is suggested to be replaced by new tag network=Call a Bike

### ISSUE THREAD

**Issue by xuiqzy** [osmlab/name-suggestion-index#5271]
Currently the tag documented in the wiki ( [network=call-a-bike](https://wiki.openstreetmap.org/wiki/Tag:network%3Dcall-a-bike) and [german amenity=bicycle_rental](https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dbicycle_rental) and [Cologne Bicycle Rental](https://wiki.openstreetmap.org/wiki/Cologne/Bicycle_Rental#Deutsche_Bahn.2C_.27Call_a_Bike.27) and [Berlin Bicycle Rental](https://wiki.openstreetmap.org/wiki/Berlin/Bicycle_Rental#Call_a_Bike) and maybe more ) and used so far ( 224 vs 3 uses, search for "call" here [network values taginfo](https://taginfo.openstreetmap.org/keys/network#values) ) for tagging the Call a Bike network is `call-a-bike`.
The name-suggestion-index contains and thus current id editor suggests to change it to `Call a Bike`. [NSI Code](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json#L914)

Is this an agreed upon change? If yes, maybe the wiki should be updated to reflect that?
If no, maybe the entry here should be changed to `network=call-a-bike`?

**Comment by bhousel** [comment]
Thanks @kjonosm & @xuiqzy - it sounds like we're good to close this.

**Comment by kjonosm** [comment]
There wasn't a lot of feedback in the German forum, so it doesn't seem to be controversial to keep the suggestion here as is.
I updated the wiki pages accordingly.

**Comment by xuiqzy** [comment]
Thanks for looking at this everyone!
@kjonosm Thanks for updating the wiki, but which pages? All the ones linked in the first post in this issue still have the `call-a-bike` value listed or am I misunderstanding something?
