### ISSUE TITLE
Adding `brand/operator:website` when running `npm run wikidata`

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5275]
I noticed that [```brand:website```](https://taginfo.openstreetmap.org/keys/brand%3Awebsite) is a somewhat prominent tag for brand websites. I was wondering if this tag could be automatically added from the 'official website' statement of the respective wikidata page similarly to how brand:wikipedia tags are added.

**Comment by peternewman** [comment]
Hopefully it goes without saying, but we shouldn't set `website` as that's often used for a link to a particular store.

What would be really cool with all these things is if something could automatically enrich the data, so you could use Overpass Turbo for example, or the OSM API, either directly or in an enriched mode where these fields would be set if missing based on the impliedTags values. So people get the best of all worlds.

**Comment by Adamant36** [comment]
> Hopefully it goes without saying, but we shouldn't set website as that's often used for a link to a particular store.

Well I don't support this change, I don't think that would be an issue because the `website` field would still be empty if `brand:website` was auto filled.

**Comment by arch0345** [comment]
I'm going to close this because, as @bhousel mentioned, you could just get this information from the wikidata page, and a more relevant website pertaining to that specific location might already be in the `website` tag
