### ISSUE TITLE
Games Workshop retail locations in the UK have rebranded to Warhammer

### ISSUE THREAD

**Issue by davidpnewton** [osmlab/name-suggestion-index#5288]
Games Workshop retail locations located in the UK have all been rebranded to Warhammer. This means that the NSI is causing ID to falsely suggest that Warhammer retail locations need their tagging updated.

https://www.retail-week.com/main-navigation/games-workshop-to-rebrand-stores-warhammer/7018262.article?authent=1

Please update the NSI accordingly.

**Comment by LaoshuBaby** [comment]
This item are stored at：

https://github.com/osmlab/name-suggestion-index/blob/f83dc374e536c0cad78d7c11c21ed33e664ba166/data/brands/shop/games.json#L8-L18

For a simple for rebrand I meet ：

https://github.com/osmlab/name-suggestion-index/pull/5251#issuecomment-902449263

**Comment by LaoshuBaby** [comment]
But wikipedia still say it named with "Games Workshop" :

![图片](https://user-images.githubusercontent.com/42690037/131364966-d8e26e20-c960-421a-a7a5-51a5902ccafe.png)

If still need rename, you can override this part with:

```json
    {
      "displayName": "Warhammer",
      "id": "Warhammer-acdf54",
      "matchNames":["Games Workshop"],
      "locationSet": {
        "include": ["de", "fr", "gb", "nl", "us"]
      },
      "tags": {
        "brand": "Warhammer",
        "brand:wikidata": "Q587270",
        "brand:wikipedia": "en:Games Workshop",
        "name": "Warhammer",
        "shop": "games"
      }
    }
```

**Comment by davidpnewton** [comment]
Oh Wikipedia says it does it! How marvelous. How authoritative. How worthlessly wrong. I provided a source for my request. If you wished to check recent Google Streetview data on any of the Warhammer stores you could have seen that not only is the source relevant, but the rebranding has actually been done.

Instead you went to Wikipedia for the "truth". Instead you regurgitated something that is utterly worthless in determining what has actually happened. If a trade publication news story is not enough how about the website of the company concerned itself:

https://stores.warhammer.com/

That authoritative enough for you? That correct enough for you?

**Comment by bhousel** [comment]
@davidpnewton Please don't be a jerk.  This project tracks brands all around the world and our maintainers are not going to be super familiar with the details of all of them.  Our data is linked to Wikidata and Wikipedia, so checking what it says there is a reasonable thing to do.

@LaoshuBaby's suggestion on renaming the brand in the index and matching the old name is exactly the correct thing to do, so I'll make the change.

**Comment by davidpnewton** [comment]
Oh the suggestion on how to rename using the code was quite correct alright. It wasn't that which was the problem.

It was the reflexive trusting of Wikipedia in preference to the source which I had provided which annoyed me. Wikipedia is a tertiary source. I linked to a primary source on the matter. Besides I would also point out that I specifically said it was a rebrand. That does not mean the base name of the organisation has changed. That means the brand name of the shops has changed. Changing the brand name of the shops is hardly enough by itself to merit changing the Wikipedia article name.

This was nothing to do with "not … super familiar with the details of all of them". This was using completely the wrong method to become familiar with the specific brand in question. Not being "super familiar" with something means researching to become familiar enough when necessary. Doing that research in an incorrect way is a general problem, not a specific one linked to a particular brand.

Ignorance is quite reasonable. By definition you can't know everything. Ignorance can also be cured through research. Faulty research is an entirely different matter. This was faulty research, not ignorance.
