### ISSUE TITLE
Add office/water_utility category

### ISSUE THREAD

**Issue by starwatcher11** [osmlab/name-suggestion-index#5291]
Hello. I'd like to suggest some more local brands to add in OSM in Greece.
brand=WIND Hellas
brand:wikidata=Q10711016
brand:wikipedia=el.WIND_Hellas
shop=mobile_phone

brand=Public Power Corporation SA
brand:wikidata=Q326345
brand:wikipedia=el.Δημόσια_Επιχείρηση_Ηλεκτρισμού
office=energy_supplier

brand=Watt+Volt
brand:wikidata=Q25047624
brand:wikipedia=en.Watt%2BVolt
office=energy_supplier

brand=Elpedison
brand:wikidata=Q28026003
office=energy_supplier

brand=EYDAP
brand:wikidata=Q15088495
brand:wikipedia=el.Εταιρεία_Υδρεύσεως_και_Αποχετεύσεως_Πρωτευούσης
office=water

brand=ΕΥΑΘ
brand:wikidata=Q15088495
brand:wikipedia=el.Εταιρεία_Ύδρευσης_και_Αποχέτευσης_Θεσσαλονίκης
office=water

Thanks.

**Comment by arch0345** [comment]
Here are the brands from this issue:

shop/mobile_phone
- [ ] WIND Hellas

office/energy_supplier
- [ ] Public Power Corporation SA
- [ ] Watt+Volt

office/water
- [ ] EYDAP
- [ ] ΕΥΑΘ

We currently don't have a office/water category, but this could easily be added in the future.

**Comment by kjonosm** [comment]
Hey @arch0345, do you mean [`office=water_utility`](https://wiki.openstreetmap.org/wiki/Tag:office%3Dwater_utility)?

**Comment by arch0345** [comment]
> Hey @arch0345, do you mean [`office=water_utility`](https://wiki.openstreetmap.org/wiki/Tag:office%3Dwater_utility)?

Yes, I meant office/water_utility. Thanks for catching this!

**Comment by bhousel** [comment]
I'm going to move these utility offices from the `brands` tree to the `operators` tree, so they are with the other utility features.
