### ISSUE TITLE
```hot_pot``` or ```hotpot```?

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5292]
I use ```cuisine=chinese;hotpot``` for those restaurant that serves "火锅" in ```restaurant.json```

But today I found ```hot_pot``` also been widely used, and another "hot-prefix" western food "hot dog" usually use ```hot_dog```

So I want to ask for community suggestion that which I should use in NSI

This question I will ask both in Github and Chinese local community.

![图片](https://user-images.githubusercontent.com/42690037/131494022-4bdfa424-eead-4e25-9bd2-106e78302998.png)

**Comment by tntchn** [comment]
I'm not sure what kind of `hotpot` or `hot pot` those existing restaurants in OSM are, but I think hot pot is much better.

After googling for a while, I found that there was a English dish call "[Lancashire hotpot](https://www.bbcgoodfood.com/recipes/lancashire-hotpot)", not sure if this dish is widespread or not. But I still think using `hot_pot` is a easy way to avoid the confusion.

**Comment by sorz** [comment]
[enwiki](https://en.wikipedia.org/wiki/Hot_pot) uses "Hot pot" as page title.
Although they also mentioned and used "hotpot" in the article and the talk page, "hot pot" is use more frequently (13 vs 82 times by a quick Ctrl-F).

**Comment by 1ec5** [comment]
At least in the U.S., “hotpot” or “hot pot”, unqualified, would refer to the Asian dish of Chinese origin; a Lancashire hotpot would need to be qualified as such to be recognizable.

I don’t think it’s necessary to avoid every potential naming conflict. After all, `cuisine=noodles` is reserved for Asian-style noodle dishes, as opposed to American-style chicken noodle soup, for example.

**Comment by bhousel** [comment]
I think it's ok to just use `cuisine=hotpot` (or `cuisine=chinese;hotpot` is fine too) 
because it is the most frequently occurring value right now: 

<img width="832" alt="Screen Shot 2021-09-01 at 5 52 30 PM" src="https://user-images.githubusercontent.com/38784/131750341-cf794ccb-1fc1-4b15-b380-baa489973595.png">


A long time ago, this index contained a mix of `hotdog` and `hot_dog` tags, but I [changed them all to `hot_dog`](https://www.openstreetmap.org/changeset/74910608) just to match what the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dhot_dog) said to do.

**Comment by LaoshuBaby** [comment]
> A long time ago, this index contained a mix of `hotdog` and `hot_dog` tags, but I [changed them all to `hot_dog`](https://www.openstreetmap.org/changeset/74910608) just to match what the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dhot_dog) said to do.

That's also what I want to do.

**Comment by LaoshuBaby** [comment]
According to above comment and the talk in Chinese local community (they all think use ```hot_pot``` is better), we prefer to use ```hot_pot```, the same spelling as English Wikipedia to create a ```cuisine=hot_pot```. This will be used for automatical match for ```cuisine```.

![图片](https://user-images.githubusercontent.com/42690037/131767857-1fd6275b-aa95-4c10-a55a-03e86041c766.png)



Thanks for everyone's advice!

**Comment by Cj-Malone** [comment]
`hotpot` now seems to be more common, and is used in iD. I don't have a preference on which we use, but I think we should be unified.

**Comment by LaoshuBaby** [comment]
Closing this as fixed via `hotpot`. It seems the convention here just follows whichever value was introduced first.

<details>
<summary>Note</summary>

~~Coming from a Chinese cultural background, I'd lean toward the underscore variant. There seem to be several "hot"-related tags in OSM, but only one uses an underscore — might be worth unifying these at some point?~~

Also, shabu-shabu and sukiyaki are generally seen as distinct Japanese cooking styles, and are usually tagged directly with their own names, e.g. `cuisine=shabushabu` or `cuisine=sukiyaki`.

<img  height="514" alt="Image" src="https://github.com/user-attachments/assets/882ed2a2-ca65-4f41-a7e6-b2d48c4927f5" />

(I'd guess there may also be a future discussion on whether to keep the hyphen in "shabu-shabu".)

</details>

**Comment by Cj-Malone** [comment]
Looking at your original screenshot, I would have done the same with an underscore. This wasn't a fault with you. You unified them with NSI to the standard tag, thank you.

iD and OSM data changed, so I believe NSI should change too, it's easier than changing iD and OSM.

**Comment by LaoshuBaby** [comment]
> be more common

<img height="514" alt="Image" src="https://github.com/user-attachments/assets/fa73306f-3e63-45a9-9cdd-06a7aae3d4e6" />

Yes, that's the situation, that if a tag is used a very large number of times, it becomes more likely to keep being used, compared to the screenshot in 2021 you can see the increasing speed of each value combination—there are plenty of examples of this in OSM. So after looking into the current usage numbers on OSM, I think this choice made in the iD tag schema does have a real basis. Maybe in the next decade there will be new proposals, but as far as OSM data goes for the next few years, I think this is the choice made by mappers of current time—it might get reopened in the future, but closing this issue and end discussion now is perfectly reasonable.
