### ISSUE TITLE
Swisscom is shop=telecommunication, not shop=mobile_phone

### ISSUE THREAD

**Issue by dafadllyn** [osmlab/name-suggestion-index#5295]
https://github.com/osmlab/name-suggestion-index/blob/e6d95b381085b817c80a51a28b3d60a3d8279569/data/brands/shop/mobile_phone.json#L708-L720

Swisscom is `shop=telecommunication`, not `shop=mobile_phone`. (Swisscom, a Swiss telecom provider, doesn't only sell mobile phones, but also/mainly mobile, internet and TV contracts.)

**Comment by kjonosm** [comment]
Hey @dafadllyn, I am hesitant of this change as `shop=telecommunication` is not an established tag and `shop=mobile_phone` has a broader meaning than just selling mobile phones. Checking the OSM wiki, I think that `shop=mobile_phone` still fits well enough to be suggested by NSI.

**Comment by bhousel** [comment]
We did have some previous discussion on #2900, #3113, #3120 about using the `shop=telecommunication` tag for retail storefronts.  I thought that it was settled 2 years ago and documented on the wiki, but I can't find it now. 🤷

**Comment by dafadllyn** [comment]
Oddly enough, a wiki entry for `shop=telecommunication` doesn't seem to exist.  There's an entry for [`office=telecommunication`](https://wiki.openstreetmap.org/wiki/Tag:office%3Dtelecommunication), but obviously this is for the office, not for the retail store. On the other hand, [`shop=mobile_phone`](https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dmobile_phone) ("a shop that primarily sells mobile phones and accessories") doesn't fit either for shops of telecommunication companies. (Note that some don't operate a mobile network and thus don't sell mobile phones.)

**Comment by dafadllyn** [comment]
Thanks, @bhosel, for correcting it. I've now created a wiki entry for [`shop=telecommunication`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dtelecommunication).
