### ISSUE TITLE
Belle Property should use "Belle Property" as a name

### ISSUE THREAD

**Issue by stragu** [osmlab/name-suggestion-index#5308]
The [Belle Property](https://nsi.guide/index.html?t=brands&k=office&v=estate_agent&tt=belle#belle-d66f4e) (wikidata [Q104721339](https://www.wikidata.org/wiki/Q104721339)) should use the full "Belle Property" name rather than only "Belle".

In iD, the issue tool came up with these tags as a fix for the current tagging of a node:

```
+ branch=Property
+ brand=Belle
+ brand:wikidata=Q104721339
- name=Belle Property
+ name=Belle
```

I don't see why that `branch` value is used. I think both `brand` and `name` should be "Belle Property", and no branch value should be used.

Maybe that's iD trying to parse whatever is behind "Belle" as the branch location, like it would in, say, "Belle West End"?

**Comment by LaoshuBaby** [comment]
Another “branch  problem” like #5281 
@bhousel
