### ISSUE TITLE
"L" in "Translink" should be capitalised

### ISSUE THREAD

**Issue by stragu** [osmlab/name-suggestion-index#5309]
The ["Translink" item](https://github.com/osmlab/name-suggestion-index/blob/895f8f1b44dc28ac576ea23567df327fcf3c9b39/data/transit/route/train.json#L1901) should have its "L" capitalised for both the `displayName` property and the `network` tag, just like it is on the [official website](https://translink.com.au/) and in the Wikidata item [Q7833625](https://www.wikidata.org/wiki/Q7833625).

**Comment by LaoshuBaby** [comment]
Fixed

**Comment by stragu** [comment]
far out that was quick
