### ISSUE TITLE
Figure out a better way to extract names from the OSM planet file

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5311]
It's gotten really difficult to process the OSM planet because node-osmium is [more or less abandoned now](https://github.com/osmcode/node-osmium/issues/116).  For now I've done some hacky workarounds to let me use older versions of the dependencies, but this is only going to get more difficult with each new version of node.  The thing I'm doing today works on my machine, but it wouldn't surprise me if it fails on a Windows machine or a newer M1 MacBook.  

I'm going to [update the instructions on our wiki](https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers#collecting-names-from-the-osm-planet) and create a special branch for working with osmium, but beyond that we should start looking for alternatives.

**Comment by tas50** [comment]
I've been meaning to do this. It's a real mess at the moment and I can't get it to work on my m1. I was debating creating a container for it so it would be easier to control node and osmium deps.

**Comment by bhousel** [comment]
I added some hacky scripts to juggle `package.json` around, and I [updated the instructions](https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers#collecting-names-from-the-osm-planet) on the project wiki (See below).

This is bad and doing this in a container or another project would probably be better, but at least it lets us kick the problem down the road a bit.  I can keep doing this sometimes as long as I still have a Core i7 Mac and can get Node 10 to work on it.

---

## Collecting names from the OSM planet

This takes a long time and a lot of disk space. It can be done occasionally by project maintainers.

See https://github.com/osmlab/name-suggestion-index/issues/5311 for ongoing discussion on how to make this better.

#### Get a planet file and prefilter it
- Install `osmium` command-line tool (may only be available on some environments)
  - `apt-get install osmium-tool` or `brew install osmium-tool` or similar
- [Download the planet](http://planet.osm.org/pbf/)
  - `curl -L -o planet-latest.osm.pbf https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf`
- Prefilter the planet file to only include named items with keys we are looking for:
  - `osmium tags-filter planet-latest.osm.pbf -R name,brand,operator,network -o filtered.osm.pbf`

#### Run the collection script 
This should be done in the name-suggestion-index project. Results will go in `dist/collected/*.json`.
This is complicated because node-osmium is available prebuilt only for older environments.
- Try to use Node 10?  This requires something like [`nvm`](https://github.com/nvm-sh/nvm) to switch node versions.
  - `npm run osmium:setup`
  - `nvm use 10`
  - `npm install`
- Run the script
  - `node scripts/collect_all.js /path/to/filtered.osm.pbf`
- Try to restore your normal environment
  - `npm run osmium:restore`
  - `nvm use 16`
  - `npm install`

#### A new challenge
- Attempt an `npm run build`.  Now that unique `id` properties are generated, it is possible that this command will fail.
- This can happen if there are *multiple* new items that end up with the same `id` (e.g. "MetroBus" vs "Metrobus")
- You'll need to just pick one to keep, then keep trying to run `npm run build` until the duplicate `id` issues are gone.

#### Check in the collected names
- `git add . && git commit -m 'Collected common names from latest planet'`

**Comment by tas50** [comment]
You might want to add `--overwrite` to the osmium command.

**Comment by bhousel** [comment]
I ended up creating another project https://github.com/ideditor/nsi-collector  where we can run the collection script and publish the data files - Now name-suggestion-index can depend on that other thing, and we can drop the hacky `package.json` swapping ..  

@tas50 I made you an admin on that other project too..
