### ISSUE TITLE
American Crypto ATM not amenity=bank

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5312]
Checking their website, should [American Crypto ATM](https://www.americancrypto.com/atms-emlenton-pa) not rather be listed under `amenity=payment_terminal` or `amenity=atm`?

https://github.com/osmlab/name-suggestion-index/blob/1fec6bb2aa56891576fc21bc8fb21c9b82194473/data/brands/amenity/bank.json#L405-L414

**Comment by Adamant36** [comment]
Some of them you can buy and sell. Some you can't do both. So, I'd say the ones you can do both with amenity=atm is fine. With the other ones, I don't think it really matters and they still have ATM in the name. Given that, I see no issue with them also being tagged as amenity=atm. It's always better IMO to tag things in a way that follows how the company sees themselves.
