### ISSUE TITLE
Maxi Zoo has a wrong Wikidata and Wikipedia entry

### ISSUE THREAD

**Issue by airon90** [osmlab/name-suggestion-index#5314]
https://nsi.guide/?t=brands&k=shop&v=pet#maxizoo-3e2920

Correct Wikidata item is [Q108403242](https://wikidata.org/wiki/Q108403242) and there is no Wikipedia page

**Comment by LaoshuBaby** [comment]
Yes, I've checked, you are right. The couse maybe someone added this entry by copy below/above entry, then modify some keywords, but forget to check the wikidata value.
