### ISSUE TITLE
Encourage adding operator's name on power supports in France

### ISSUE THREAD

**Issue by flacombe** [osmlab/name-suggestion-index#5317]
Dear maintainers,

Following this issue's discussion on iD presets schemes, I've be encouraged to look at NSI to improve operator's name tagging encouragement on French power poles/towers.
https://github.com/openstreetmap/id-tagging-schema/issues/219

Background is we currently achieve hard work to map millions of power poles in France and providing them with their operator's name in `operator=*` key is very important.
You'll find further information about this project here: https://www.openstreetmap.org/user/InfosReseaux/diary/396044
I've been manually completing existing ones from the beginning of 2021 but as contribution increases on this particular topic, the gap is now wider than when all of this began.

There are 119 power distribution operators in France, some of them are already listed there:
https://wiki.openstreetmap.org/wiki/Power_networks/France#Entreprises_de_distribution

Is that right NSI could help to encourage mappers to add operator's name in several editors and what would be the best way to achieve that in coming weeks?

All the best

**Comment by kjonosm** [comment]
Hey @flacombe! For a start have a look of the power features that are already supported by NSI. For distribution infrastructure it currently supports [`power=line`](https://nsi.guide/index.html?t=operators&k=power&v=line) and [`power=minor_line`](https://nsi.guide/index.html?t=operators&k=power&v=minor_line) features.

I would think that any company operating the actual line oder minor_line network is also in charge of the poles...

**Comment by Adamant36** [comment]
> I would think that any company operating the actual line oder minor_line network is also in charge of the poles...

I know in America that the people who operate the poles versus the lines are often different. So it would still be good to support power poles in the Name-Suggestion-Index at some point regardless of how things are in France. 

> There are 119 power distribution operators in France

If someone wants to create a list of which are/aren't in the index yet I can go through Wikidata/Wikipedia to check them there and open issues for the ones that we don't have support for. They would probably be good first issues for Hacktober. I assume it's going on this year.

**Comment by flacombe** [comment]
Thanks @kjonosm, it's a good point to start with.

> I know in America that the people who operate the poles versus the lines are often different. So it would still be good to support power poles in the Name-Suggestion-Index at some point regardless of how things are in France.

It's true, adding operator on both poles and lines is a valuable thing.

> If someone wants to create a list of which are/aren't in the index yet

The list is here. My bad, 121 instead of 119.
https://agenceore.opendatasoft.com/explore/dataset/referentiel-distributeurs-denergie/table/?refine.energie=%C3%89lectricit%C3%A9

However, it remains to define the appropriate `operator=*` value for each. I'll try to have a look to it as to add them to the index once and for all

**Comment by bhousel** [comment]
This seems ok to me - When I originally added the power features [a few weeks ago](https://github.com/osmlab/name-suggestion-index/issues/5218), I didn't add `power/tower` or `power/pole` because I wasn't sure how useful or accurate those categories would be. 

- The values that we've collected from the OSM planet can be found here:  https://raw.githubusercontent.com/osmlab/name-suggestion-index/main/dist/collected/operators_all.json
(it's a big file, but you can search for `power/` - take a look and see if everything you are expecting to find is there already?)
- We can add these values as-is (how we collect them) -or- we can use templates to define rules like "for every `power/line` make a `power/tower`" and "for every `power/minor_line` make a `power/pole`".   Using templates makes things easier because then we can define the operators in fewer files.

**Comment by bhousel** [comment]
> * we can use templates to define rules like "for every `power/line` make a `power/tower`" and "for every `power/minor_line` make a `power/pole`".   Using templates makes things easier because then we can define the operators in fewer files.

☝️  I did this..

Now the items in `operators/power/line` will get template-expanded to  
- `operators/power/tower`
- `operators/power/minor_line`
- `operators/power/pole`

People can review these lists on https://nsi.guide/index.html?t=operators and let us know if anything is missing.
