### ISSUE TITLE
Add healthcare/alternative

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5329]
[The Joint Chiropractic](https://www.thejoint.com/) has hundreds of locations in the US. In addition to not having a wikidata page, healthcare/alternative doesn't yet exist so this would need to be created before adding this brand.

**Comment by Adamant36** [comment]
> healthcare/alternative doesn't yet exist so this would need to be created before adding this brand.

I think you can just create one by copying another file, renaming it, and adding the new tagging scheme. At least that's how new files were created back in the day. That said, a lot has changed since I tried it. So don't blame me if it breaks something. 😅
