### ISSUE TITLE
Add copyright warning for some commercial mapservice in China

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5343]
I noticed a road with ```source=google``` touched a rule and iDeditor give a warning about removing it. I think this good and want to add some canonical commercial mapservice such as "baidu" or  "amap" to the list.

![图片](https://user-images.githubusercontent.com/42690037/133443031-4fa548fa-8e98-4a54-b1da-5a8cc9bfb04b.png)

I found no files in NSI have those rule, maybe because I'm careless.  Where should I go? If in other repository, which files should I edit?  Thanks!

**Comment by bhousel** [comment]
Oh yeah this is one of the other tag validations that iD does.  It's not related to the NSI.
Can you open this issue in https://github.com/openstreetmap/iD instead, thanks!

**Comment by LaoshuBaby** [comment]
> 
> 
> Oh yeah this is one of the other tag validations that iD does. It's not related to the NSI.
> Can you open this issue in https://github.com/openstreetmap/iD instead, thanks!

https://github.com/openstreetmap/iD/issues/8700

I've already raise it in iD's repository, but last time I raise a issue in iD's repo I haven't been replied, looks like that there is a lack of maintainer in iD?

Thanks you for your patient reply! I'll waiting for iD community's suggestion.

**Comment by bhousel** [comment]
> I've already raise it in iD's repository, but last time I raise a issue in iD's repo I haven't been replied, looks like that there is a lack of maintainer in iD?

Yeah this is a really sad story.. I was the main iD maintainer for many years until I was abruptly fired last year and had my maintainer rights removed by Mikel and the OSMF board. Most people have heard all about this by now, but anyway this is why the iD project has stalled.  A project of that size really needs someone with experience steering the ship.

I work with the [RapiD](http://mapwith.ai/rapid) team now and we are continuing to send fixes and improvements back to the iD project where we can.  You should give RapiD a try!
