### ISSUE TITLE
Hypermarket Target locations

### ISSUE THREAD

**Issue by nchristensen** [osmlab/name-suggestion-index#5371]
Certain Target locations, formerly known as SuperTargets, have full grocery stores making them hypermarkets like Walmart Supercenters. The OSM wiki indicates hypermarkets are typically tagged as `shop=supermarket`. Should we add a supermarket option for these Target locations alongside the `shop=department_store` option already present?

**Comment by bhousel** [comment]
Seems good to me, thanks for the suggestion 👍
