### ISSUE TITLE
Error when running npm run build

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5372]
When I ran build a few minutes ago it gave me this error:
`Error: ENOENT: no such file or directory, open './node_modules/@ideditor/nsi-collector/dist/osm/names_all.json'`

Does this have to do with [this commit](https://github.com/osmlab/name-suggestion-index/commit/99005a4817d09754783382b32026d52cff0fb238)?

**Comment by Adamant36** [comment]
Did you try running npm install or npm update? If not, either one or doing npm update and then npm install might help.

**Comment by arch0345** [comment]
Thanks for the advice - running both of these fixed it
