### ISSUE TITLE
Routes should be tagged type=route

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#5375]
In iD, if I create a new relation and directly apply one of NSI’s `route` presets, it ends up missing a `type=route` tag. None of the transit/route entries in this project list `type=route` under `tags`. Was that an oversight, or should a consumer such as iD know to apply `type=route` based on the presence of `route`? (`route=ferry` is the oddball because it’s also tagged on ways.)

**Comment by bhousel** [comment]
I'll look into it, it might be a bug on the iD side..  The presets NSI generates include `type=route` so I don't know of the top of my head what the issue could be.  (I did add [special code](https://github.com/osmlab/name-suggestion-index/blob/b0e510cad9e5fdf7d7ce248b5aa5a32c71af113a/scripts/dist_files.js#L163-L171) to handle the ferry situation).

```js
    "type/route/bus/njtransit-a21cc9": {
      "name": "NJ Transit",
      "locationSet": {"include": ["us"]},
      "icon": "temaki-bus",
      "geometry": ["relation"],
      "matchScore": 2,
      "imageURL": "https://graph.facebook.com/NJTRANSIT/picture?type=large",
      "terms": ["new jersey transit", "nj transit"],
      "reference": {"key": "route", "value": "bus"},
      "tags": {
        "network:wikidata": "Q498553", 
        "route": "bus", 
        "type": "route"
      },
      "addTags": {
        "network": "NJ Transit",
        "network:wikidata": "Q498553",
        "network:wikipedia": "en:NJ Transit",
        "route": "bus"
      }
    },
```
