### ISSUE TITLE
Pizza Hut Delivery Wikidata

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#5382]
Hi all,

CC @rjw62 as he's done most of the Pizza Hut Delivery Wikidata Edits.

There's a Wikidata item for Pizza Hut Delivery:
https://www.wikidata.org/wiki/Q107293079

There's another for Pizza Hut:
https://www.wikidata.org/wiki/Q191615

We currently only use the latter (for both brands):
https://nsi.guide/?t=brands&k=amenity&v=fast_food&tt=pizza hut

Should we either split, or should the former be redirected to the latter within Wikidata?

Also seeing the NSI page, there's a Japan specific one, should the main Pizza Hut Express exclude Japan, or does it auto-select the most location relevant one for the area you are in?

**Comment by rjw62** [comment]
"Pizza Hut Delivery" is a separate fascia brand, and the outlets has a significantly different character/format to the regular Pizza Hut restaurants. I don't think there's any question over whether "Pizza Hut Delivery" can have it's own wikidata entry. (That's not a question for NSI anyway.) It's more open as to what brand:wikidata tag should be used for "Pizza Hut Delivery" in OSM. I think given the distinct nature of two different types of outlets (and the different branding) it would be better to use the two different brand:wikidata values. It should also help distinguish between the two, and help with spotting mis-tagging.

**Comment by peternewman** [comment]
Thanks @rjw62 @UKChris-osm . 

Does NSI auto-select the most location relevant one for the area you are in? Or do we need to narrow the locations of some of these versions?

I've also created #5474 to do a bit more related tidying.
