### ISSUE TITLE
Caterpillar

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/name-suggestion-index#5384]
Hi,

When I create a new point and if I research "caterpillar", I find one. But the informations are bad : ID gives the tag "shop:trade" and the tag "trade:agricultural_equipement" which are false : they don't work for agriculture (even if they also sell tractors and combine harvesters). The good tag should be "shop:construction_equipement" because their first job is to sell bulldozers, asphalt pavers, excavators, loaders, dump trucks, road rollers and so on.

For example on wikipedia, you will find for the definition of the compagny : Caterpillar Inc. is "the world's largest construction-equipment manufacturer". And this wikipedia page was not written by me ;)

Best regards

**Comment by arch0345** [comment]
Nice catch! It looks like that the entry for CAT was copied from John Deere, which does sell agricultural equipment, over a year ago and nobody had noticed this mistake. I'll fix this right away!
