### ISSUE TITLE
Unecessary name changes

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5386]
This issue was first reported on the OSM Slack tagging channel. These variations of brands have a suggested name change when they're not necessary:

- [ ] JOANN Fabrics and Crafts (`branch=Fabrics and Crafts` shouldn't be added)
- [ ] Chico's Off the Rack (`branch=Off the Rack` shouldn't be added)
~~Ikea Furniture Pick-up~~ (inconsistent naming)
- [ ] Sally Beauty (rebranded from Sally Beauty Supply

**Comment by tas50** [comment]
- Chico's Off the Rack should get added in addition to Chico's
- Ikea Furniture Pick-up really needs to be up to local mappers to ignore. Ikea isn't consistent with how they brand these so we can add an index item to them
- Jo-Ann should actually be Joann now without the -. They've rebranded and they're changing signage throughout the US. The old name can be marked as the official name, but it's not the name of the chain. This is similar to Dunkin' Donuts becoming Dunkin' or Domino's Pizza becoming just Domino's. There's always resistance to people who are accustomed to the old names, but if a brand renames the map should update to that. We have tags to make search still work. If someone locally disagrees with that they are more than welcome to ignore NSI suggestions.

**Comment by arch0345** [comment]
Thanks @tas50 for fixing these issues!
