### ISSUE TITLE
Add Proactiv vending machines

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5398]
Kroger is putting these in the entrances to many of their stores.

**Comment by arch0345** [comment]
Added these a couple weeks ago:
https://github.com/osmlab/name-suggestion-index/blob/25b17012bcdc2ca933b47a35ffc995dd76e6c57c/data/brands/amenity/vending_machine.json#L532-L544

**Comment by tas50** [comment]
Even better. I look forward to being able to tag the Hollywood Fred Meyer one soon.
