### ISSUE TITLE
Wikidata entries for Dutch public transport networks

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#5414]
All Dutch public transport networks (concession areas) now have a Wikidata entry. These Wikidata links are not yet in the Name Suggestion Index.

Wikidata tag can be added to existing NSI entry:
* Achterhoek-Rivierenland, network=Achterhoek-Rivierenland, route=bus, network:wikidata=Q108716027 (achterhoekrivierenland-2f3200)
* Achterhoek-Rivierenland, network=Achterhoek-Rivierenland, route=train, network:wikidata=Q108716027 (achterhoekrivierenland-948004)
* Amstelland-Meerlanden, network=Amstelland-Meerlanden, route=bus, network:wikidata=Q108716043 (amstellandmeerlanden-2f3200)
* Arnhem-Nijmegen, network=Arnhem-Nijmegen, route=bus, network:wikidata=Q108716067 (arnhemnijmegen-2f3200)
* Bus Rotterdam, network=Bus Rotterdam, route=bus, network:wikidata=Q108716132 (busrotterdam-2f3200)
* Busvervoer Almere, network=Busvervoer Almere, route=bus, network:wikidata=Q108716136 (busvervoeralmere-2f3200)
* Drechtsteden, Molenlanden en Gorinchem, network=Drechtsteden, Molenlanden en Gorinchem, route=bus, network:wikidata=Q108716138 (drechtstedenmolenlandenengorinchem-2f3200) 
* Gooi- en Vechtstreek, network=Gooi- en Vechtstreek, route=bus, network:wikidata=Q108723753 (gooienvechtstreek-2f3200)
* Groningen-Drenthe, network=Groningen-Drenthe, route=bus, network:wikidata=Q108742233 (groningendrenthe-2f3200)
* Haaglanden Stad, network=Haaglanden Stad, route=bus, network:wikidata=Q108718022 (haaglandenstad-2f3200)
* Haaglanden Streek, network=Haaglanden Streek, route=bus, network:wikidata=Q108709937 (haaglandenstreek-2f3200)
* Haarlem-IJmond, network=Haarlem-IJmond, route=bus, network:wikidata=Q66991285 (haarlemijmond-2f3200)
* Hoeksche Waard - Goeree-Overflakkee, network=Hoeksche Waard - Goeree-Overflakkee, route=bus, network:wikidata=Q108721362 (hoekschewaardgoereeoverflakkee-2f3200)
* IJsselmond, network=IJsselmond, route=bus, network:wikidata=Q108742700 (ijsselmond-2f3200) 
* IJssel-Vecht, network=IJssel-Vecht, route=bus, network:wikidata=Q108721383 (ijsselvecht-2f3200)
* Limburg, network=Limburg, route=bus, network:wikidata=Q108713758 (limburg-80be78)
* Limburg, network=Limburg, route=train, network:wikidata=Q108713758 (limburg-948004)
* Noord- en Zuidwest-Fryslân en Schiermonnikoog, network=Noord- en Zuidwest-Fryslân en Schiermonnikoog, route=bus, network:wikidata=Q108742235 (noordenzuidwestfryslanenschiermonnikoog-2f3200)
* Noord-Holland Noord, network=Noord-Holland Noord, route=bus, network:wikidata=Q2271893 (noordhollandnoord-2f3200)
* Oost-Brabant, network=Oost-Brabant, route=bus, network:wikidata=Q108712935 (oostbrabant-2f3200)
* Provincie Utrecht, network=Provincie Utrecht, route=bus, network:wikidata=Q108742249 (provincieutrecht-2f3200)
* Publiek Vervoer Groningen-Drenthe, network=Publiek Vervoer Groningen-Drenthe, route=bus, network:wikidata=Q108742243 (publiekvervoergroningendrenthe-2f3200)
* Rail Haaglanden, network=Rail Haaglanden, route= tram, network:wikidata=Q108718111 (railhaaglanden-50b0a0)
* Rail Rotterdam, network=Rail Rotterdam, route= tram, network:wikidata=Q108718112 (railrotterdam-50b0a0) 
* Rail Rotterdam, network=Rail Rotterdam, route= subway, network:wikidata=Q108718112 (railrotterdam-a19aa3)
* Regionaal spoorvervoer Fryslân en Groningen, network=Regionaal spoorvervoer Fryslân en Groningen, route=train, network:wikidata=Q108742239 (regionaalspoorvervoerfryslanengroningen-948004)
* Regio Utrecht, network=Regio Utrecht, route=bus, network:wikidata=Q108742251 (regioutrecht-2f3200) 
* Stadsvervoer Amsterdam, network=Stadsvervoer Amsterdam, route=bus, network:wikidata=Q108742702 (stadsvervoeramsterdam-2f3200) 
* Stadsvervoer Amsterdam, network=Stadsvervoer Amsterdam, route=tram, network:wikidata=Q108742702 (stadsvervoeramsterdam-50b0a0)
* Stadsvervoer Lelystad, network=Stadsvervoer Lelystad, route=bus, network:wikidata=Q108742704 (stadsvervoerlelystad-2f3200)
* Twente, network=Twente, route=bus, network:wikidata=Q108741255 (twente-2f3200) 
* Voorne-Putten en Rozenburg, network=Voorne-Putten en Rozenburg, route=bus, network:wikidata=Q108718063 (voorneputtenenrozenburg-2f3200)
* Waterland, network=Waterland, route=bus, network:wikidata=Q108742714 (waterland-2f3200)
* West-Brabant, network=West-Brabant, route=bus, network:wikidata=Q108742718 (westbrabant-a315fc)
* Zaanstreek, network=Zaanstreek, route=bus, network:wikidata=Q3519297 (zaanstreek-2f3200)
* Zeeland, network=Zeeland, route=bus, network:wikidata=Q108718030 (zeeland-a315fc)
* Zuid-Holland Noord, network=Zuid-Holland Noord, route=bus, network:wikidata=Q108718025 (zuidhollandnoord-2f3200)
* Zuidoost-Brabant, network=Zuidoost-Brabant, route=bus, network:wikidata=Q108710205 (zuidoostbrabant-a315fc)
* Zuidoost-Fryslân en Wadden, network=Zuidoost-Fryslân en Wadden, route=bus, network:wikidata=Q108742721 (zuidoostfryslanenwadden-2f3200)

The following networks are not yet in the Name Suggestion Index

Network exists but not for this transportation mode:
* The tram lines of network Regio Utrecht, network=Regio Utrecht, route=tram, network:wikidata=Q108742251 (example: https://www.openstreetmap.org/relation/10396258)
* The subway lines of network Stadsvervoer Amsterdam, network=Stadsvervoer Amsterdam, route=subway, network:wikidata=Q108742702 (example: https://www.openstreetmap.org/relation/4515354)
* The train lines of network Arnhem-Nijmegen, network=Arnhem-Nijmegen, route=train, network:wikidata=Q108716067 (example: https://www.openstreetmap.org/relation/1323495)
* The train lines of network Drechtsteden, Molenlanden en Gorinchem, network=Drechtsteden, Molenlanden en Gorinchem, route=train, network:wikidata=Q108716138 (example: https://www.openstreetmap.org/relation/3017158)
* The train lines of network Twente, network=Twente, route= train, network:wikidata=Q108741255 (example: https://www.openstreetmap.org/relation/5291208)

Train networks without an entry:
* Treindienst Amersfoort - Ede-Wageningen, network=Treindienst Amersfoort - Ede-Wageningen, route= train, network:wikidata=Q108742705 (example: https://www.openstreetmap.org/relation/321926)
* Treindienst Gouda - Alphen aan den Rijn, network=Treindienst Gouda - Alphen aan den Rijn, route=train, network:wikidata=Q108718103 (example: https://www.openstreetmap.org/relation/5281316)
* Vechtdallijnen, network=Vechtdallijnen, route= train, network:wikidata=Q108742711 (example: https://www.openstreetmap.org/relation/5253803)
* Zwolle - Kampen en Zwolle - Enschede, network=Zwolle - Kampen en Zwolle - Enschede, route=train, network:wikidata=Q108742725 (example: https://www.openstreetmap.org/relation/324857)

Bus networks without an entry:
* Parkshuttle Rivium, network=Parkshuttle Rivium, route=bus, network:wikidata=Q108721420 (example: https://www.openstreetmap.org/relation/535557)
* Schiphol Landside/Airside, network=Schiphol Landside/Airside, route=bus, network:wikidata=Q108742701 (example: https://www.openstreetmap.org/relation/12014320)

Ferry networks without an entry:
* Fast Ferry Hoek van Holland - Maasvlakte, network=Fast Ferry Hoek van Holland - Maasvlakte, route=ferry, network:wikidata=Q108720466 (example: https://www.openstreetmap.org/relation/11302804)
* Fast Ferry Vlissingen - Breskens, network=Fast Ferry Vlissingen - Breskens, route=ferry, network:wikidata=Q108720434 (example: https://www.openstreetmap.org/relation/4298224)
* IJ- en Noordzeekanaalveren, network=IJ- en Noordzeekanaalveren, route=ferry, network:wikidata=Q108720424 (example: https://www.openstreetmap.org/relation/12234843)
* Veer Kop van 't Land, network=Veer Kop van 't Land, route=ferry, network:wikidata=Q108742712 (example: https://www.openstreetmap.org/relation/4298905)
* Waterbus Rotterdam-Drechtsteden, network=Waterbus Rotterdam-Drechtsteden, route=ferry, network:wikidata=Q1845402 (example: https://www.openstreetmap.org/relation/442843)

**Comment by arch0345** [comment]
I've organized these into checklists to make these easier to keep track of:

Add wikidata:
route/bus
- [ ] Achterhoek-Rivierenland (Q108716027)
- [ ] Amstelland-Meerlanden (Q108716043)
- [ ] Arnhem-Nijmegen (Q108716067)
- [ ] Bus Rotterdam (Q108716132)
- [ ] Busvervoer Almere (Q108716136)
- [ ] Drechtsteden (Q108716138)
- [ ] Gooi- en Vechtstreek (Q108723753)
- [ ] Groningen-Drenthe (Q108742233)
- [ ] Groningen-Drenthe (Q108742233)
- [ ] Haaglanden Stad (Q108718022)
- [ ] Haaglanden Streek (Q108709937)
- [ ] Haarlem-IJmond (Q66991285)
- [ ] Hoeksche Waard - Goeree-Overflakkee (Q108721362)
- [ ] IJsselmond (Q108742700)
- [ ] IJssel-Vecht (Q108721383)
- [ ] Limburg (Q108713758)
- [ ] Noord- en Zuidwest-Fryslân en Schiermonnikoog (Q108742235)
- [ ] Noord-Holland Noord (Q2271893)
- [ ] Oost-Brabant (Q108712935)
- [ ] Provincie Utrecht (Q108742249)
- [ ] Publiek Vervoer Groningen-Drenthe (Q108742243)
- [ ] Regionaal spoorvervoer Fryslân en Groningen (Q108742239)
- [ ] Regio Utrecht (Q108742251)
- [ ] Stadsvervoer Amsterdam (Q108742702)
- [ ] Stadsvervoer Lelystad (Q108742704)
- [ ] Twente (Q108741255)
- [ ] Voorne-Putten en Rozenburg (Q108718063)
- [ ] Waterland (Q108742714)
- [ ] West-Brabant (Q108742718)
- [ ] Zaanstreek (Q3519297)
- [ ] Zeeland (Q108718030)
- [ ] Zuid-Holland Noord (Q108718025)
- [ ] Zuidoost-Brabant (Q108710205)
- [ ] Zuidoost-Fryslân en Wadden (Q108742721)

route/train
- [ ] Achterhoek-Rivierenland (Q108716027)
- [ ] Limburg (Q108713758)
- [ ] Regionaal spoorvervoer Fryslân en Groningen (Q108742239)

route/tram
- [ ] Rail Haaglanden (Q108718111)
- [ ] Rail Rotterdam (Q108718112)
- [ ] Stadsvervoer Amsterdam (Q108742702)

route/subway
- [ ] Rail Rotterdam (Q108718112)

Add transit:
route/tram
- [ ] Regio Utrecht (Q108742251)

route/subway
- [ ] Stadsvervoer Amsterdam (Q108742702)

route/train
- [ ] Arnhem-Nijmegen (Q108716067)
- [ ] Drechtsteden, Molenlanden en Gorinchem (Q108716138)
- [ ] Twente (Q108741255)
- [ ] Treindienst Amersfoort (Q108742705)
- [ ] Treindienst Gouda (Q108718103)
- [ ] Vechtdallijnen (Q108742711)
- [ ] Zwolle (Q108742725)

route/bus
- [ ] Parkshuttle Rivium (Q108721420)
- [ ] Schiphol Landside/Airside (Q108742701)

route/ferry
- [ ] Fast Ferry Hoek van Holland - Maasvlakte (Q108720466)
- [ ] Fast Ferry Vlissingen - Breskens (Q108720434)
- [ ] IJ- en Noordzeekanaalveren (Q108720424)
- [ ] Veer Kop van 't Land (Q108742712)
- [ ] Waterbus Rotterdam-Drechtsteden (Q1845402)

**Comment by bhousel** [comment]
Wow thanks for organizing these @A67-A67 & @arch0345 👏 
This looks like a lot of work.. Is it the sort of thing where we can write up some simple instructions and invite [Hacktoberfest](https://hacktoberfest.digitalocean.com/) participants to submit PRs for it?

**Comment by pdejan** [comment]
> Wow thanks for organizing these @A67-A67 & @arch0345 👏 This looks like a lot of work.. Is it the sort of thing where we can write up some simple instructions and invite [Hacktoberfest](https://hacktoberfest.digitalocean.com/) participants to submit PRs for it?

I'd be happy to help with few just few pointers. As fairly new to contributing this would be nice experience.

**Comment by kjonosm** [comment]
@A67-A67 to prevent mistakes from beginners maybe you could update your post to use the `network` key instead of the `name` key, e.g. `network=Achterhoek-Rivierenland` instead of `name=Achterhoek-Rivierenland`.
