### ISSUE TITLE
Add EcoATM kiosks

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5427]
Mobile Phone recycling kiosks.

ecoatm.com

**Comment by arch0345** [comment]
I'm not sure if this should go in `amenity=vending_machine` or `amenity=recycling`. `vending=recycling` isn't currently in use (but makes more sense IMO), but `recycling_type=vending_machine` is.

**Comment by arch0345** [comment]
I've added it as `amenity=recycling` just like how you tagged it at the [Hollywood Fred Meyer](https://www.openstreetmap.org/node/9294826112)

**Comment by tas50** [comment]
That's probably the closest thing. I wish we had a simple tagging for "I get money for this item"
