### ISSUE TITLE
Facebook is offline

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5431]
Everything [Facebook](https://facebook.com) seems to be offline at the moment due to a DNS / BGP issue - this means that all Facebook linked logos on the [nsi.guide](https://nsi.guide) web site will return an error, and running "_npm run wikidata_" will **not** fetch any Facebook hosted Logos, so it's probably best not to run it until Facebook is back online.

**Comment by arch0345** [comment]
Looks like Facebook is [back online](https://www.theverge.com/platform/amp/2021/10/4/22708989/instagram-facebook-outage-messenger-whatsapp-error)
