### ISSUE TITLE
Incorrect operator tags for UK Post Offices

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#5446]
I've just had an incorrect "tag upgrade" suggestion from iD that I think is due to an NSI entry in data/operators/amenity/post_office.json . It involved suggesting the addition of the following tags to an amenity=post_office object:

operator=Post Office
operator:wikidata=Q1783168
operator:wikipedia=en:Post Office Ltd

In the UK, only a small number of larger branches (known as "Crown Post Offices") are directly operated Post Office Ltd. The rest (the majority) are run on a franchise model either by other businesses or individual sub-postmasters. So while it would be correct to offer to add Post Office Ltd brand and brand:* tags to individual post offices (as long as the amenity=post_office isn't on another shop=* node that might need a different brand), the operator tags above will normally be incorrect.

**Comment by UKChris-osm** [comment]
Did you get my latest post office FOI dataset Robert?

**Comment by bhousel** [comment]
Oh this is the part I sort of missed before:

> So while it would be correct to offer to add Post Office Ltd brand and `brand:*` tags to individual post offices ..., the `operator*` tags above will normally be incorrect.

I see now that this is the same thing as #5561, that post offices really need to go back to the brand tree.. 😅
