### ISSUE TITLE
Add Boot Barn Wikidata

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5452]
Western clothing store.

Owned by https://en.wikipedia.org/wiki/Freeman_Spogli_%26_Co.

**Comment by UKChris-osm** [comment]
[Boot Barn](https://nsi.guide/index.html?t=brands&k=shop&v=shoes&tt=boot%20b#bootbarn-c5ede1) just needs a Wikidata :)

**Comment by arch0345** [comment]
I moved Boot Barn to `shop/clothes` as just like other brands such as Nike they've started to move their focus towards their apparel.
