### ISSUE TITLE
Rename Verizon Wireless to just Verizon

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5454]
They've rebranded their stores. We should move the Verizon Wireless name to a full name tag.

**Comment by arch0345** [comment]
@itsmeAnubhab Verizon is in data/brands/shop/mobile_phone.json. You can Ctrl+F to find Verizon and edit its properties from there

**Comment by itsmeAnubhab** [comment]
> It looks like we're preserving names for Verizon because of how authorized dealers also use the brand tag - is there a way to only change locations with "Verizon Wireless" as their name?

did you mean the location needs to be changed as well?

**Comment by arch0345** [comment]
> did you mean the location needs to be changed as well?

No, your PR was fine. I'm just saying that the name for existing POIs will stay as "Verizon Wireless" because of how the name is in `preserveTags`

**Comment by arch0345** [comment]
I'll just create a MapRoulette challenge for this
