### ISSUE TITLE
Add Good 2 Go

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#5460]
Smallish chain with stores in several western states.

https://good2gostores.com/locations

https://en.wikipedia.org/wiki/Good_2_Go is for a 90s music group.

**Comment by Adamant36** [comment]
> https://en.wikipedia.org/wiki/Good_2_Go is for a 90s music group.

Apparently there's also an album called Good 2 Go by Elephant Man. They should do a collaboration/tie in 🤣
