### ISSUE TITLE
Add School of Rock

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5482]
[School of Rock](https://en.wikipedia.org/wiki/School_of_Rock_(company)) currently has 260 open locations in nine countries serving more than 30,000 students.

https://www.schoolofrock.com/
https://locations.schoolofrock.com/
https://en.wikipedia.org/wiki/School_of_Rock_(company)
https://www.wikidata.org/wiki/Q7756376

This brand belongs under `brands/amenity/music_school.json`

```js
    {
      "displayName": "School of Rock",
      "locationSet": {"include": ["au", "br", "ca", "cl", "co", "mx", "py", "pe", "ph", "za", "es", "tw", "us"]},
      "tags": {
        "amenity": "music_school",
        "brand": "School of Rock",
        "brand:wikidata": "Q7756376",
        "brand:wikipedia": "en:School of Rock (company)",
        "name": "School of Rock"
      }
```

**Comment by lmpham1** [comment]
Sounds simple! I'd like to work on this
