### ISSUE TITLE
Bus networks North-West England

### ISSUE THREAD

**Issue by Falsernet** [osmlab/name-suggestion-index#5488]
I often find "Stagecoach in Lancashire" and "Warrington's Own Buses" tagged bus routes. Can these be added to name suggestion?

https://en.wikipedia.org/wiki/Warrington%27s_Own_Buses
https://www.wikidata.org/wiki/Q7000937

https://en.wikipedia.org/wiki/Stagecoach_Merseyside_%26_South_Lancashire
https://www.wikidata.org/wiki/Q7596858

https://en.wikipedia.org/wiki/Stagecoach_Cumbria_%26_North_Lancashire
https://www.wikidata.org/wiki/Q7596840

**Comment by arch0345** [comment]
Thanks for your patience!
