### ISSUE TITLE
Some changes to default name suggestions to revolve inconsistencies

### ISSUE THREAD

**Issue by sommerluk** [osmlab/name-suggestion-index#55]
Some changes to default name suggestions to revolve inconsistencies

- “ALDI”: default should be “Aldi” because also “Aldi Süd” and “Aldi Nord” do not use all-capitals.

- “Adler Apotheke” is wrong orthography. Default should be “Adler-Apotheke” which is correct orthography.

- “Citroen” does probably only exist because many keyboard layouts don’t provide “ë”. Default should be “Citroën”, which also the enterprise itself uses in general.

- “NETTO”: Default should be “Netto” because all the other German supermarkets in the list are also not all-capitals.

- “REWE Getränkemarkt”: Default should be “Rewe Getränkemarkt” because also the main store “Rewe” does not use all-capitals.

- “LAWSON”: I suppose that also here the default should be “Lawson”, but I’m not sure here because I’ve never been in one of these stores.

**Comment by sommerluk** [comment]
It might be useful to add to the list:

- “REWE City”: The default value should be “Rewe City” for consistency with “Rewe”.

**Comment by math1985** [comment]
Yes, makes sense!

Could you create a pull request?
