### ISSUE TITLE
Wrong suggestion for Brasov Tolleybuses

### ISSUE THREAD

**Issue by szjozsef** [osmlab/name-suggestion-index#5504]
Because of this entry :
```
    {
      "displayName": "R.A.T. Brașov",
      "id": "ratbrasov-6b6251",
      "locationSet": {"include": ["ro"]},
      "tags": {
        "network": "R.A.T. Brașov",
        "network:wikidata": "Q929687",
        "network:wikipedia": "de:Societatea de Transport Public Timișoara",
        "route": "trolleybus"
      }
```
in the file: **data/transit/route/trolleybus.json**
any edit on the tolleybuses objects in the openstreetmap web editor triggers an error suggesting to replace the existing object properties from the one from this this, which is incorrect thet wikidata ID / wikipedia page reference is for Timișoara. The correct wikidata ID should be: Q7258031 with the wikipedia text: "ro:Regia Autonomă de Transport Brașov" or from the English page: "en:RAT Brașov". Also  the suggested network name / display name should be: **RAT Brașov**
The similar object for the **Bus** objects are correct:
```
    {
      "displayName": "RAT Brașov",
      "id": "ratbrasov-9c403a",
      "locationSet": {"include": ["ro"]},
      "tags": {
        "network": "RAT Brașov",
        "network:wikidata": "Q7258031",
        "network:wikipedia": "ro:Regia Autonomă de Transport Brașov",
        "route": "bus"
      }
```

**Comment by bhousel** [comment]
> How long it takes until ID will use the new values for suggestions ? (after 5 days, is not yet updated)

I usually run the script about once a week, but I can run it today.
