### ISSUE TITLE
JYSK in lowercase

### ISSUE THREAD

**Issue by NKAmapper** [osmlab/name-suggestion-index#5509]
The correct brand name text for JYSK is "Jysk", according to Scandinavian grammar (names which are pronounced  like a normal word should have lowercase letters). Jysk also happens to be a normal word for in the Danish language, for the Jutlandic dialect.

Examples in Wikipedia: https://en.wikipedia.org/wiki/Jysk

shop/furniture

**Comment by bhousel** [comment]
Are you really sure?  I really don't want to change this unless there's a good reason to.

There is plenty of evidence that the brand calls themselves "JYSK":

1. We try to use the name that most mappers in OSM prefer.  Our scripts have collected these counts from the OSM planet file:
https://github.com/ideditor/nsi-collector/blob/80803dadd41281f870ea52111c6b20fcce07ec6c/dist/osm/names_all.json#L8696-L8697
```js
"shop/furniture|Jysk": 181,
"shop/furniture|JYSK": 839,
```

2. The JYSK about us page:
https://jysk.no/om-jysk
<img width="847" alt="Screen Shot 2021-10-15 at 12 48 13 PM" src="https://user-images.githubusercontent.com/38784/137523962-7adcb06b-7f7e-4a82-8a5a-04f219aa14a3.png">


3. They seem to be styled as "JYSK" everywhere, even in Norway:
<img width="1169" alt="Screen Shot 2021-10-15 at 12 45 25 PM" src="https://user-images.githubusercontent.com/38784/137523697-b8a1451c-90a7-4013-8f41-8326e0958b5a.png">
