### ISSUE TITLE
brand=ROSSMANN is incompatible with the naming convention

### ISSUE THREAD

**Issue by wzbartczak** [osmlab/name-suggestion-index#5510]
According to the accepted convention of using names, it should be "Rossman" in "brand" and "name"

**Comment by bhousel** [comment]
It seems like we are getting a lot of requests to adjust the capitalization of the names.
#4104 #5109 #5410 #5509 

It does take a lot of time for me to research each of these requests to be sure that it's really the correct thing to do.

Can you follow similar steps to https://github.com/osmlab/name-suggestion-index/issues/5509#issuecomment-944450197 to let me know:
1. the capitalization of names collected from the osm planet (we try to match the name preferred by mappers)
2. how the brand calls itself in their communications (we try to match what the brand calls themself)
3. how other maps display the brand (we try to match people's expectations of how maps work)

I can do this research myself but it feels better when a request like this comes with supporting evidence for the change.

**Comment by wzbartczak** [comment]
Most likely, the attempts are related to the way Osmose errors are detected. [My level 1 - errors](https://osmose.openstreetmap.fr/en/byuser/Cristoffs?level=1)

Anyway, our wiki tells you how the names should be spelled. So we either change the convention in the wiki and in Osmose, or here ....
from OSM wiki:

**Uppercase characters**
General recommendation is to use mixed case with the first letter of each word capitalised, e.g., Church Street, not Church street but regional rules have preference over general rules. For example, in Flemish, capitalisation of last names gives a hint about the nobility status of the person. Street or company names derived from those last names should copy the same capitalisation. In non-Latin based languages, it's often not even possible to capitalise a name.

[wiki link](https://wiki.openstreetmap.org/wiki/Names#Uppercase_characters)

**Comment by matkoniecz** [comment]
ROSSMANN is a stylistic capitalization, in the same way as a centaur embedded on O.

See for example https://duckduckgo.com/?q=Rossmann+site%3Agazeta.pl&t=ffab&ia=web https://duckduckgo.com/?q=Rossmann+site%3Arp.pl&t=ffab&ia=web https://duckduckgo.com/?q=Rossmann+site%3Aforum.openstreetmap.org&t=ffab&ia=web how Rossmann is named in articles etc.

It definitely should be `name=Rossmann`, not `name=ROSSMANN` or `name=<ref>ROSSMANN</red>` or `name=R🐎SSMANN`.

I can make thread on Polish forum if there is any doubt at all about it to confirm that.

Though I would not care too much about Osmose, it loves to make invalid complaints.
