### ISSUE TITLE
"Mama lishe" doesn't seem to be a brand

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#5516]
It seems to be a common name in [Swahili](https://mymemory.translated.net/en/Swahili/English/mama-lishe) for a local restaurant.

https://github.com/osmlab/name-suggestion-index/blob/d6e8fd5b5c5aaacadd0fa4554aefe64b5d3ca9a9/data/brands/amenity/restaurant.json#L2161-L2170

**Comment by LaoshuBaby** [comment]
Do you means add "Mama lishe" to this part and treat it as a generic name?

https://github.com/osmlab/name-suggestion-index/blob/16ed12cb1a2ef1f9029dafef50c56ef469a597e6/data/brands/amenity/restaurant.json#L5-L17
