### ISSUE TITLE
Prevent build script from overwriting new data with old data

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5519]
Yesterday @tas50 appeared to [import the newest planet dataset](https://github.com/osmlab/name-suggestion-index/commit/775a56b0e9f845433472ce2f07ed4100b652624d) from [@ideditor/nsi-collector](https://github.com/ideditor/nsi-collector), but I saw this was failing a build check due to an ID being repeated twice (_eondanmark-c22d3a_) for "_E.On Danmark_" and "_E. On Danmark_" (note the space between the **E.** and **On** in the second entry).

To resolve this, I removed the entry with the space, as this seemed to be the incorrect variation, and added a matchname to the original. Running "_npm run build_" seemed to have worked fine.

However, pushing the change via GitHub Desktop seemed to have split the push into two pushes, and removed the matchname that I had added.

I see the [commit I made](https://github.com/osmlab/name-suggestion-index/commit/c0c853800303892aad86dfc2ba66ef079b1bd89d) on this has two comments, yet no comments are shown when I look - I also received two emails that said @tas50 and @bhousel had commented, but the emails contained no body text.

I then saw that @tas50 [added back the planet data](https://github.com/osmlab/name-suggestion-index/commit/a39544479b9d92f4b30ee9ac8ea18b49e62df81c) in another commit, so I'm quite confused as to what's gone on.

Did my edit cause any issues?

**Comment by bhousel** [comment]
I think I need to adjust the build script so that 
- the `dist/filtered/*` files know what version of the collected files they came from and
- the build script won't overwrite newer files with older ones.

**Comment by bhousel** [comment]
> * the `dist/filtered/*` files know what version of the collected files they came from and
> * the build script won't overwrite newer files with older ones.

I think this stuff is working now, but I'll keep an eye on it..

The build script should now be aware of what version of nsi-collector we're up to, and should avoid overwriting files if they look like they were generated based on a equal or newer version..
