### ISSUE TITLE
Currys/PC World rebranded to Currys

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#5541]
Currys/PC World have gone though a rebrand, again, it is now just branded as "Currys".

I guess there needs to be some Wikidata updates too.

**Comment by UKChris-osm** [comment]
Thank you @Cj-Malone  - Closed via [db8010a](https://github.com/osmlab/name-suggestion-index/commit/db8010a9bd5a5c2c73a30f05b75288fa69820532)
