### ISSUE TITLE
Research needed for: amenity/fuel|Station Service E. Leclerc

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#555]
#### :thinking: We need help deciding what to do with "amenity/fuel|Station Service E. Leclerc"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fuel|Station Service E. Leclerc` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fuel|Station Service E. Leclerc`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fuel|Station Service E. Leclerc`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by mmd-osm** [comment]
Belongs to https://fr.wikipedia.org/wiki/E.Leclerc  - https://www.wikidata.org/wiki/Q1273376
See http://www.e-leclerc.com/catalogue/nos-magasins/magasins-specialises/carburant-energie-1

**Comment by Adamant36** [comment]
Thanks. There's an unresolved discussion currently going on in #1676 about how to handle E. Leclerc brands in general, including this one. I guess they operate a lot of stuff.
