### ISSUE TITLE
iD suggests to replace LA Metro Express/Limited with Local

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5554]
When fixing issues in Los Angeles, iD suggested replacing the Metro Express network tag to Metro Local, even though there's a preset for Metro Express. I'm not sure if this is an issue with NSI or iD.
![image](https://user-images.githubusercontent.com/85302075/138610212-93d5d960-f21e-4f4d-b2b1-26c8b9a7cd03.png)

Edit: The same thing is happening with Metro Limited:
![image](https://user-images.githubusercontent.com/85302075/138610523-52b2b742-0d90-4d80-be23-e35741c044f0.png)

**Comment by bhousel** [comment]
Thanks!  It turned out that this was just because "Metro Local" was the only one with wiki tags assigned.  I added the tags and I think this should work ok after the next release.

**Comment by bhousel** [comment]
I can confirm that this is working now  - also thanks for doing the release @arch0345!  🎉
