### ISSUE TITLE
Possible / Update Brand Categories in NSI

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5579]
Please note that these are all suggestions for possible nsi improvement.

Possible Ideas Include: 

brands/dining
 - brands/dining/bakery
 - brands/dining/bar
 - brands/dining/cafe
 - brands/dining/fast_food
 - brands/dining/ice_cream
 - brands/dining/pastry
 - brands/dining/pub
 - brands/dining/restaurant

brands/financial
 - brands/financial/atm
 - brands/financial/bank
 - brands/financial/bureau_de_change
 - brands/financial/financial_advisor
 - brands/financial/money_lender
 - brands/financial/money_transfer
 - brands/financial/payment_centre
 - brands/financial/payment_terminal
 - brands/financial/tax_advisor

**Comment by arnowrld** [comment]
Based on feedback & experience from other NSI contributors, I will do better with any new suggestions, recommendations, & additions to the project.

**Comment by 1ec5** [comment]
You’re probably not alone in assuming this project could develop its own categories. If there’s a better way to make our dependence on OSM tagging conventions clearer in the documentation, we’d welcome a PR to that effect. Also, if you find that OSM is missing a tag for something, let’s discuss it on Slack or the [tagging](https://lists.openstreetmap.org/pipermail/tagging/) mailing list in case there are already less obvious equivalents or other considerations. Thanks for your ideas!
