### ISSUE TITLE
Updating Various Existing Hotels on NSI

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5592]
Every chain shown here now has its own Wikidata.

- [ ] EDITION: https://www.wikidata.org/wiki/Q91218404
- [ ] Element Hotels: https://www.wikidata.org/wiki/Q91948072
- [ ] Hyatt Centric: https://www.wikidata.org/wiki/Q109277705
- [ ] Hyatt House: https://www.wikidata.org/wiki/Q109292191
- [ ] Marriott Hotels & Resorts: https://www.wikidata.org/wiki/Q3918608
- [ ] Tapestry Collection: https://www.wikidata.org/wiki/Q109275422
- [ ] The Luxury Collection: https://www.wikidata.org/wiki/Q2412604
- [ ] Tribute Portfolio: https://www.wikidata.org/wiki/Q92021343

**Comment by UKChris-osm** [comment]
Thanks @arnowrld - I've converted these into "_tasks_", which can be ticked off one by one as they are completed. You can make any future lists into tasks by using a hyphen / dash, followed by a space, then an open square brace / bracket, then a space, then a closed square brace / bracket, for example **- [ ] Task** or by first writing the list, then highlighting it and using the tasks icon above, which looks like a box with a tick inside it.
 - [ ] Task 1
 - [ ] Task 2
 - [ ] Task 3
