### ISSUE TITLE
Correct apostrophe handling

### ISSUE THREAD

**Issue by sommerluk** [osmlab/name-suggestion-index#56]
Correct apostrophe handling

Instead of using the correct apostrophe character, people often use the character U+0027 because it’s easier to access on many keyboard layouts (as it dates from the times of ASCII).

To quote from Unicode Standard about U+0027:

> * neutral (vertical) glyph with mixed usage
> * 2019 is preferred for apostrophe
> * preferred characters in English for paired quotation marks are 2018 & 2019
> * […]

Of course U+0027 is used in technical context (programming languages…), but indeed I don’t know of any typographically valid use case for U+0027 in normal text.

I would suggest to always use a variant with U+2019 as default (canonical) variant. 

I’ve checked the current canonical.json (2017-09-22) and for the all names in this list, indeed it seems that for all occurencies of U+0027 that the correct character would be U+2019 (and not 2018, 2019, 2032).

**Comment by bhousel** [comment]
Honestly, I'd rather leave this alone.  I don't have a strong preference, but I think it's better to use the version of the name that people commonly type on their keyboards.

e.g. for comparison:
U+0027: Applebee's 
U+2019: Applebeeʼs

**Comment by bhousel** [comment]
Yeah I thought about it some more and lets not do this.
