### ISSUE TITLE
Suggesting to merge brands in hotels

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5617]
The ones in question are Fairfield by Marriott, Gaylord Hotels, Hampton by Hilton, Holiday Inn Express, La Quinta by Wyndham, & Microtel by Wyndham.

**Comment by mathiash98** [comment]
Would be nice with reasoning and source, to make it easier to make a decision

**Comment by arnowrld** [comment]
For instance, Fairfield by Marriott was recently rebranded to "Fairfield by Marriott" in 2019. Hampton by Hilton was rebranded from "Hampton Inn" & "Hampton Inn & Suites" to Hampton by Hilton".

**Comment by bhousel** [comment]
I think for all these examples you gave, we already include tags for the both (old and new) variants of the name:
https://nsi.guide/index.html?t=brands&k=tourism&v=hotel&tt=hampton
https://nsi.guide/index.html?t=brands&k=tourism&v=hotel&tt=fairfield
