### ISSUE TITLE
Can we allow categories to be in both 'operators' and 'brands' trees

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5625]
This is affecting kind of a lot of things now, and I need to think if I can just make some minor adjustments - but not a whole rewrite - to make it work ok.

> It seems to be working - I made sure to add `skipCollection` to the one in the brands tree and the ones in the brands tree won't also get added to the operators one as a city, county, or NGO operates the individual libraries

I'm just thinking out loud about the things that might be an issue:
- [x] Revert #5613 if it turns out I can pull this off with minimal effort.
- [x] The NSI matcher code probably will have subtle issues, because its match index is built on `k/v`.  This might mean the items and the exclude lists from one file may overwrite those things from other file.  I expect that this code will just never match stuff in whatever file it parsed first.
- [x] Raise a warning (by `matcher.buildMatchIndex`?) if a same-named item exists in several trees. re [#5625-comment]( https://github.com/osmlab/name-suggestion-index/issues/5625#issuecomment-956513420)
- [x] In iD there is other code to try to "guess" what tree a `k/v` pair belongs to.  (This code might guess wrong, but it might be ok anyway because brands and operators are similar - I dont know).  The reason for this "tree guessing" is because iD is just looking at raw OSM tags and it needs to decide which tags are considered "namelike".  
UPDATE: I checked the [code here](https://github.com/openstreetmap/iD/blob/3e7fd6e0330a14319206c9c9eb47afb3d97ca8d9/modules/services/nsi.js#L288-L299) and I _think_ it's ok.  Any items that appear in both trees will still be checked for `name`, `operator`, and `brand` keys.
- For example, the iD validator sees a `shop=yes`+`name:en=USPS - Morristown`+`height=3.5`+`roof:colour=orange`, it should be able to run the `name:en` tag through the matcher and guess that that is probably a US Post Office, even without actually seeing a defining tag like `amenity=post_office`, and also not matching the "Orange" mobile phone brand because of that `roof:colour` tag..

This probably just needs to be its own issue now, because the 'brand'-'operator' split is causing a whole lot of grief for me lately, and I _just_ moved the post offices in #5613 (mostly for Norway, UK, and things like UPS store) and I'm still not sure I did the right thing.

_Originally posted by @bhousel in https://github.com/osmlab/name-suggestion-index/issues/5623#issuecomment-956279182_

**Comment by bhousel** [comment]
> * The NSI matcher code probably will have subtle issues, because its match index is built on `k/v`.  This might mean the items and the exclude lists from one file may overwrite those things from other file.  I expect that this code will just never match stuff in whatever file it parsed first.

I wrote some tests, and it turns out this already working ok after all.

**Comment by UKChris-osm** [comment]
I just tried two library examples in OSM, one from the brand tree ([Leo](https://nsi.guide/index.html?t=brands&k=amenity&v=library#librariesofeasternoregon-0b187f)) and one from the operator tree [(Birmingham City Council)](https://nsi.guide/index.html?t=operators&k=amenity&v=library#birminghamcitycouncil-b45619) and it seemed to work just fine, so I don't think having a category span multiple trees is an issue - the only issue I could see is if Leo appeared in both - and perhaps this is something the build script could flag up before we dist - such as:

**warning**: "_Leo appears under brand and operator for amenity/library_"

I always thought the matcher was based on what a user was typing, and matched it with a name / brand / operator - is it currently possible for it to match based on the "_roof:colour_" value?

**Comment by arch0345** [comment]
> I always thought the matcher was based on what a user was typing, and matched it with a name / brand / operator - is it currently possible for it to match based on the "_roof:colour_" value?

I think he was trying to say that iD only looks for certain keys, `name:en` being one of them and `roof:colour` not being one of them

**Comment by bhousel** [comment]
> > I always thought the matcher was based on what a user was typing, and matched it with a name / brand / operator - is it currently possible for it to match based on the "_roof:colour_" value?
> 
> I think he was trying to say that iD only looks for certain keys, `name:en` being one of them and `roof:colour` not being one of them

☝️ yes it's this..
And it's _tree-specific_ which tags it considers namelike and which tags take priority:
https://github.com/osmlab/name-suggestion-index/blob/main/config/trees.json

**Comment by bhousel** [comment]
> the only issue I could see is if Leo appeared in both - and perhaps this is something the build script could flag up before we dist - such as:
> 
> **warning**: "_Leo appears under brand and operator for amenity/library_"

This is a good point:  I'm adding it as a task above, and I'll test that it works when I rebuild the post offices...

**Comment by bhousel** [comment]
Update on this - I did a bunch of investigation and I think we are ok to have categories in both trees, for example:
- brands/amenity/post_office.json
- operators/amenity/post_office.json

I've added tests to make sure that our matcher can handle this, and I've added a warning in case an item happens to appear in both trees.

### The rules:

IF an item is in the `brands` tree:
* the `brand` tag is required and `brand:wikidata` is used as main identifying tag for fetching the logo.  
* `operator*` tags are optional, as they are likely to be inconsistent / irrelevant across that brand.  (This includes things like privately operated post offices, like found in Norway, the United Kingdom, and stuff like the UPS Store and Mailboxes Etc..)

IF an item is in the `operators` tree: 
* the `operator` tag is required, and `operator:wikidata` is used as the main identifying tag for fetching the logo. 
* `brand*` tags are optional, as they are likely to be redundant / irrelevant / unusual in these situations (We wouldn't say that a public police force or school district is "branded").

I hope this is helpful - if there are any outstanding issues related to the brand-operator confusion, I will try to close them in the next few days.
