### ISSUE TITLE
Caledonian MacBrayne

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#5628]
Ferry operator in west of Scotland, for example: https://www.openstreetmap.org/relation/6241838

Not sure if it should be operator or network?

https://en.wikipedia.org/wiki/Caledonian_MacBrayne

https://www.wikidata.org/wiki/Q1026582

Also possibly short_name=CalMac

**Comment by arch0345** [comment]
I just added it to both as `operator=*` is already being used in OSM and the transit part of the NSI is based on `network=*`
