### ISSUE TITLE
Different contributor's `npm run build` lead to different result ?

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#5634]
This issue was first raised in https://github.com/osmlab/name-suggestion-index/commit/4bc3058ce201831104cc2e4a2aca3990f4452696 (6 days ago), and I'm suggested to use ```npm run build``` to install the latest collection files because #5519 .

But today I noticed my commit (https://github.com/osmlab/name-suggestion-index/commit/a1677c8fba2e3b001e1fea937990617f8827e7e7) after archpdx's (https://github.com/osmlab/name-suggestion-index/commit/e1ac640205c8b9579bf01e00ca6a763a54346877), we are all use the same command, but the counter still changes those number.

Some are increased, and another are reduced. Is this a problem with current program?

**Comment by tas50** [comment]
When we split out the NSI collector work and the counts of all the brand/operator data we created this problem:

https://github.com/ideditor/nsi-collector

If someone doesn't always `npm install` first they're going to potentially run `npm run build` with old data counts. That creates the flip/flop PRs.

**Comment by LaoshuBaby** [comment]
> 
> 
> When we split out the NSI collector work and the counts of all the brand/operator data we created this problem:
> 
> https://github.com/ideditor/nsi-collector
> 
> If someone doesn't always `npm install` first they're going to potentially run `npm run build` with old data counts. That creates the flip/flop PRs.

So, will we take action to force developer run `npm install`, using latest version, before they done a build?

**Comment by UKChris-osm** [comment]
Is it a big issue if the two repo's have different version numbers?

As of now, [nsi-collector package.json](https://github.com/ideditor/nsi-collector/blob/main/package.json) refers to itself as version 1.0.20211016, but our [package.json](https://github.com/osmlab/name-suggestion-index/blob/main/package.json) file calls for it using "@ideditor/nsi-collector": "1.0.20211024",

**Comment by bhousel** [comment]
oh yeah this is #5519 
I'd like to make it so that the build script won't overwrite the filtered data with older versions of the collected data.
