### ISSUE TITLE
Add DMV payment terminals

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5637]
It looks like many state DMVs have self-service kiosks, for example:
- [x] [California DMV NOW](https://cadmvnowkiosk.com/)
- [x] [Nevada DMV NOW](https://dmvnv.com/kiosk.htm)
- [x] [Hawaii DMV NOW](https://hawaiidmvnowkiosk.com/)
- [x] [Florida MV Express](https://flmvexpresskiosk.com/)
- [x] [Colorado MV Express](https://comvexpress.com/)
- [x] [Michigan Self Service Station](https://miselfservicestation.com/)
- [x] [EZ-TAB (Wisconsin)](https://www.ez-tab.com/)

**Comment by 1ec5** [comment]
Here’s [an example of a California DMV NOW kiosk](https://www.openstreetmap.org/node/6300538040). I’m not 100% certain that I’m using the `network` tag correctly; I was throwing everything against the wall to see what sticks.

**Comment by arch0345** [comment]
I decided to leave `network` out and instead use the `brand` tag for this: the branding on the kiosks seems to just be DMV Now:
![image](https://user-images.githubusercontent.com/85302075/139963232-02a4e8ac-8f4c-4bc0-9814-973dafd023bb.png)

**Comment by PierceWHoward** [comment]
Added Wikidata entries for:

Nevada DMV NOW - https://www.wikidata.org/wiki/Q110265699
Hawaii DMV NOW - https://www.wikidata.org/wiki/Q110265704
Florida MV Express - https://www.wikidata.org/wiki/Q110265714
Colorado MV Express - https://www.wikidata.org/wiki/Q110265726
Michigan Self Service Station - https://www.wikidata.org/wiki/Q110265731
EZ-TAB (Wisconsin) - https://www.wikidata.org/wiki/Q110265735
