### ISSUE TITLE
Add Muni

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5667]
[Muni](https://www.sfmta.com/muni-transit) is a network of bus, light rail (Metro and historic streetcar), trolleybus, and tram (cable car) routes which are operated by the San Francisco Municipal Transportation Agency (SFMTA):
https://en.wikipedia.org/wiki/San_Francisco_Municipal_Railway

**Comment by 1ec5** [comment]
Looks like we already have [bus](https://nsi.guide/index.html?t=transit&k=route&v=bus#muni-97b81c) and [trolley bus](https://nsi.guide/index.html?t=transit&k=route#muni-3634a8) entries for Muni as of 8a86d592cf898ece3f81a50a5ac8df1689d0294f, but no entry yet for either the [cable car system](https://www.wikidata.org/wiki/Q374956) or [Muni Metro](https://www.wikidata.org/wiki/Q278074). It’s the cable car lines that are tagged as `tram` routes in OSM; the Muni Metro lines and F Market & Wharves line are tagged as `light_rail`.
