### ISSUE TITLE
Add public transport operator around the federal city of Bern, Switzerland (Bernmobil AG)

### ISSUE THREAD

**Issue by habi** [osmlab/name-suggestion-index#5670]
The public transport operator in Bern, Switzerland is missing.
It's 'marketed' as Bernmobil, but it's official commercial name is 'Städtische Verkehrsbetriebe Bern', which is abbreviated as 'SVB'.

https://www.bernmobil.ch/
https://en.wikipedia.org/wiki/St%C3%A4dtische_Verkehrsbetriebe_Bern
https://www.wikidata.org/wiki/Q681700

I would suggest `brand=Bernmobil` and `operator=SVB`.

**Comment by arch0345** [comment]
Hi, thanks for opening this issue! Could you please specify what mode(s) of public transport Bernmobil/SVG provides? You can find a list of ones we support [here](https://github.com/osmlab/name-suggestion-index/tree/main/data/transit/route).

**Comment by habi** [comment]
Bus, tram and trolleybus.

**Comment by habi** [comment]
Awesome, thanks!
