### ISSUE TITLE
Should We Add Warehouses?

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5674]
I have been noticing that brands like Amazon, FedEx, & others have branded warehouses with different purposes. But that poses a question? Should we add them? Especially since there are different types of warehouses that these brands use?

**Comment by bhousel** [comment]
Many of these seem to have ended up in the `amenity=post_depot` tag
https://nsi.guide/index.html?t=brands&k=amenity&v=post_depot

**Comment by UKChris-osm** [comment]
I think either tag would be suitable, so would be inclined to suggest they are kept as post_depot for now as they are already in place within OSM - even if it is in low numbers at the moment.

**Comment by bhousel** [comment]
Closing for now, we can leave these as `amenity=post_depot`
