### ISSUE TITLE
change German Red Cross

### ISSUE THREAD

**Issue by martin-scholtes** [osmlab/name-suggestion-index#5675]
Hello,

as I unfortunately had to notice again and again, a lot of objects in Germany that seem to belong to the German Red Cross are tagged with operater="Deutsches Rotes Kreuz", as well as operator:wikidata and operator:wikipedia.
Unfortunately, this is wrong in 99 percent of cases. 
To explain: The German Red Cross (DRK) is represented at each association level by independent registered associations. From the federal association to the regional associations to the local association.
This results in a different operator for all kinds of objects. For example, old clothes containers are usually the responsibility of regional associations, whereas rescue stations are often run by district associations or their subsidiaries.
Thus, it would be better if facilities of the German Red Cross were tagged with brand="Deutsches Rotes Kreuz" instead of the operator.
The same applies to other aid organisations that have similar structures to the German Red Cross.

**Comment by bhousel** [comment]
Hey @martin-scholtes , can you give us a list of the types that you want to see tagged consistently? 
(I mean, are they blood donation centers, charity shops, recycling containers, something else?)

For example, https://nsi.guide contains a list of the categories that we currently include in the index.

This index is already tracking some Red Cross things, but we don't have any items for the "Deutsches Rotes Kreuz" you are seeing in Germany, so we can add them!

Blood Donation Centers (USA, AUS, Thailand):
  https://nsi.guide/index.html?t=brands&k=healthcare&v=blood_donation&tt=red%20cross
Charity Shops (UK)
  https://nsi.guide/index.html?t=brands&k=shop&v=charity&tt=red%20cross
Red Cross Flags
  https://nsi.guide/index.html?t=flags&k=man_made&v=flagpole#redcross-e5dc93

**Comment by kjonosm** [comment]
I guess @martin-scholtes refers to suggestions like [here](https://www.openstreetmap.org/node/5203211220).
Is it possible to just add `brand=Deutsches Rotes Kreuz` instead of replacing the current `operator` value?

**Comment by bhousel** [comment]
> I guess @martin-scholtes refers to suggestions like [here](https://www.openstreetmap.org/node/5203211220).
> Is it possible to just add `brand=Deutsches Rotes Kreuz` instead of replacing the current `operator` value?

oh sorry, you are right!
I somehow didn't see them when I searched before.
Yes we can make these brands instead of operators.

**Comment by bhousel** [comment]
I moved these over to the brand tree earlier today and just published a new NSI release...

Now the iD validator no longer suggests changing the `operator` and instead suggests a `brand` tag addition.  
This looks good!
(aside: I think it's pretty amazing that we can turn around requests like this so quickly 🚀 ).


<img width="300" alt="Screen Shot 2021-11-10 at 11 02 34 PM" src="https://user-images.githubusercontent.com/38784/141235005-b64ed3eb-33d9-4b80-9635-9062fb852264.png">

**Comment by martin-scholtes** [comment]
Thank you very much for the quick implementation. Yes, kjonosm is right, it was only about the change from operator to brand.
I will write a few tickets for the other aid organisations in the next few days with the corresponding brand content.

**Comment by kjonosm** [comment]
@bhousel 
[Here](https://www.openstreetmap.org/way/53038853) the validator wrongly suggests to change the `emergency=*` value. How can this be fixed?

**Comment by kjonosm** [comment]
[Here](https://www.openstreetmap.org/node/3708870348) the validator wrongly suggests to change `name=*` despite `preserveTags` setting in the NSI entry.

**Comment by martin-scholtes** [comment]
Unfortunately, I have to open here again.
As I have seen in the following [change](https://www.openstreetmap.org/changeset/114319409), [short_name=DRK](https://www.openstreetmap.org/node/5838000773) is also set. This does not apply in 99.99% of cases and should not be added semi-automatically.
This should be improved

**Comment by bhousel** [comment]
Thanks @kjonosm and @martin-scholtes , I've made some changes in 0aafc25:

- create a `brands/amenity/hospital` category for Deutsches Rotes Kreutz,
  so it won't match as ambulance station or change the `emergency` tag
- remove `short_name=DRK` tags
