### ISSUE TITLE
Add Topgolf

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5678]
Not sure what category [Topgolf](http://www.topgolf.com/) should go in - an [overpass query](https://overpass-turbo.eu/?w=%22name%22%3D%22Topgolf%22+global&R) shows that some of these are tagged as golf courses (is this a valid use of `leisure=golf_course`?) while others are tagged as `tourism=attraction`
```
    {
      "displayName": "Topgolf",
      "locationSet": {"include": ["001"]},
      "tags": {
        "brand": "Topgolf",
        "brand:wikidata": "Q7824379",
        "brand:wikipedia": "en:Topgolf",
        "name": "Topgolf"
      }
    }
```

**Comment by Mortein** [comment]
I'd suggest the countries with stores rather than worldwide. https://www.topgolf.com/select-topgolf-region/
China and Thailand have stores "coming soon", so they could also be included.

`"locationSet": {"include": ["us", "mx", "uk", "de", "ae", "cn", "th", "au"]}`

**Comment by TheAdventurer64** [comment]
There was a discussion on Slack that said that `leisure=sports_centre` + `sport=golf` could work.
