### ISSUE TITLE
State run alcohol shops should have state geojsons

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5680]
H/T to @jleedev for noticing this in https://www.openstreetmap.org/changeset/112856953

**Comment by jleedev** [comment]
Some others:

- BC Liquor Store
- LCBO
- Liquor Depot
- NSLC
- The Beer Store

**Comment by bhousel** [comment]
cool - I just did the ones I found but can reopen if I missed some!
