### ISSUE TITLE
new brands to aid organisations

### ISSUE THREAD

**Issue by martin-scholtes** [osmlab/name-suggestion-index#5682]
Hello,

as already written in ticket  #5675 , here is the next stamp that should be created as well.

brand=Malteser Hilfsdienst
brand:wikidata=Q1318397
brand:wikipedia=de:Malteser Hilfsdienst

brand=Deutsche Lebens-Rettungs-Gesellschaft
brand:wikidata=Q871679
brand:wikipedia=de:Deutsche Lebens-Rettungs-Gesellschaft

brand=Arbeiter-Samariter-Bund
brand:wikidata=Q627071
brand:wikipedia=de:Arbeiter-Samariter-Bund Deutschland

brand=Johanniter-Unfall-Hilfe
brand:wikidata=Q14751117
brand:wikipedia=de:Johanniter-Unfall-Hilfe

I am happy if this can be implemented just as quickly.

**Comment by arch0345** [comment]
Thanks for linking the respective Wikidata/Wikipedia for each of these organisations. Can you please specify which category (or categories) these should be added in?

**Comment by kjonosm** [comment]
@martin-scholtes I added your suggestions and some more organisations to features tagged as `amenity=social_facility`, `emergency=ambulance_station` and `office=association`. Do you think we need to add them to any other features?

**Comment by martin-scholtes** [comment]
> Can you please specify which category (or categories) these should be added in?
kjonsom has already made a few suggestions.
I would add emergency=lifeguard and healthcare=*.

**Comment by bhousel** [comment]
Hey @kjonosm it looks like you finished this? Can it be marked closed?
