### ISSUE TITLE
Tag to be deleted

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#5686]
https://nsi.guide/index.html?t=brands&k=shop&v=furniture&tt=porta#porta-29dff1

I think "brand:porta=de:Porta Möbel" should be deleted. Seems like a duplicate made by error while adding "brand:wikipedia=de:Porta Möbel"

**Comment by arch0345** [comment]
Thanks for catching this @ivanbranco! I'll remove this right away
