### ISSUE TITLE
Fix "Цех 85 54c425-1c12ef

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5717]
amenity=cafe
contact:email=info@tseh85.ru
contact:instagram=https://instagram.com/tseh85
contact:phone=+7 812 7757785
contact:vk=https://vk.com/tseh85
contact:website=https://tseh85.ru
name=Цех 85
opening_hours=Mo-Su 08:00-22:00
opening_hours:covid19=same
operator=Щеглова
payment:cash=yes
payment:credit_cards=yes
payment:debit_cards=yes
shop=bakery

**Comment by arch0345** [comment]
Duplicate of #5718
