### ISSUE TITLE
Fix "Цех 85" to "ЦЕХ85" 

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5718]
now:
```
amenity=cafe
brand=Цех 85
cuisine=coffee_shop
name=Цех 85
takeaway=yes

```
properly:
```
amenity=cafe
shop=bakery
brand=ЦЕХ85
cuisine=coffee_shop
name=ЦЕХ85
takeaway=yes
contact:email=info@tseh85.ru
contact:instagram=https://instagram.com/tseh85
contact:phone=+7 812 7757785
contact:vk=https://vk.com/tseh85
contact:website=https://tseh85.ru
name=ЦЕХ85
payment:cash=yes
payment:credit_cards=yes
payment:debit_cards=yes
```
thx

**Comment by UKChris-osm** [comment]
Hi @afanasovich - just to let you know we tend to stick with just the "_name_" tag, as well as "_brand_" or "_operator_", depending on the category. We don't include "_contact_" or "_payment_" tags.

I think "_amenity=cafe_" and "_shop=bakery_" would also clash, so it would have to be either one or the other.

**Comment by afanasovich** [comment]
Hi @UKChris-osm! 

thanks for the explanation, i get it. 

I create Item https://www.wikidata.org/wiki/Q109682756. Сould you add the wikidata to this  Item?

**Comment by afanasovich** [comment]
👋!  Thanks for the clarification.  I don’t understand very well how github works and don’t know English very well)) But I understood something.

I have created the item  https://www.wikidata.org/wiki/Q109682756. Сould you add the wikidata to this Item?

amenity=cafe
brand=ЦЕХ85
brand:wikidata = [Q109682756](https://www.wikidata.org/wiki/Q109682756) 
cuisine=coffee_shop
name=Цех 85
takeaway=yes

**Comment by arch0345** [comment]
Thanks for adding the wikidata page! I'll add this as soon as I can.

If you create a PR I could merge it right away: just go to `data/brands/amenity/cafe.json` and edit (pencil icon). You should be able to find the entry by using Ctrl+f.
