### ISSUE TITLE
Add OZON outpost 

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5719]
Add please OZON. 

Ozon is one of the first e-commerce companies in Russia, sometimes referred to as "the Amazon of Russia”.

name = OZON
brand = OZON
brand:wikidata = Q2365235
brand:wikipedia = ru:Ozon 
contact:phone = +7 800 2347000
contact:website = https://www.ozon.ru/
contact:email = help@ozon.ru
contact:Instagram = ozonru
contact:facebook = ozon.ru
contact:twitter = Ozon_ru
contact:vk = ozon
contact:telegram = ozonhq
shop = outpost

**Comment by UKChris-osm** [comment]
Hi @afanasovich, thank you for the suggestion - [Ozon](https://nsi.guide/index.html?t=brands&k=shop&v=outpost#ozon-968c70) seems to already be in the index, and would just need the [wikidata](https://github.com/osmlab/name-suggestion-index/commit/d6cac75ea08764f7d85381be278c64024ba5496e) tag adding to allow it to be added as a suggestion in the iD editor, which I have now done.
