### ISSUE TITLE
Add Yandex.Market

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5720]
Add please Yandex.Market

name = Яндекс.Маркет
brand = Яндекс.Маркет
brand:wikidata = Q4537982
brand:wikipedia = ru:Яндекс.Маркет
contact:phone = 8 800 234-27-12
contact:website = https://market.yandex.ru/
contact:Instagram = yandex.market
contact:facebook = yandex.market
contact:vk = yandex.market
shop = outpost

**Comment by arch0345** [comment]
I'll just add the name, brand, and shop tags as we don't include contact tags in the index
