### ISSUE TITLE
FedEx Office and UPS Store need to be copy/post office

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5749]
Both of these stores offer the services of a traditional copy store and the services of a post office. FedEx is primarily a copy store due to their roots as the Kinko's chain, but they also offer full service mailing via FedEx. The UPS store is primarily a place to mail packages via UPS, but each store also offers B&W and Color copying and print services.

**Comment by 1ec5** [comment]
> FedEx is primarily a copy store due to their roots as the Kinko's chain, but they also offer full service mailing via FedEx.

If I’m not mistaken, FedEx Office is focused on the Kinko’s services, whereas FedEx Ship Center is focused on the parcel delivery services. I’m unsure if The UPS Store makes a similar distinction.

**Comment by tas50** [comment]
FedEx Office is the business formed out of Kinkos and they do both shipping and copying. Do you have an example of one of the other locations?

**Comment by 1ec5** [comment]
https://local.fedex.com/ explains the differences between each store format. Here’s [an example](https://www.openstreetmap.org/way/26346588) of a FedEx Ship Center I’ve mapped in a light industrial park ([Mapillary](https://www.mapillary.com/app/?pKey=233409795247068)). It’s quite different than a former Kinko’s/current FedEx Office.

**Comment by SafetyIng** [comment]
> We could probably dual-tag them with both `amenity=post_office`+`shop=copyshop`

For something like this, there were "[shop as a post-partner](https://wiki.openstreetmap.org/wiki/Key:post_office)" proposed and accepted. Would this fit? 
So FedEx office could be shop=copyshop + post_office=bureau + post_office:*=*

For UPS store I don't know, if this tagging would fit?

**Comment by SafetyIng** [comment]
> I didn't really understand it then either.

What of this you don't understand? 
You can youse post_office=post_partner or others on other shops, to indicate postal services/a shop-in-shop-post_office

**Comment by bhousel** [comment]
> What of this you don't understand?

I wrote a bunch about this on #4878 

But basically, this style of tagging goes against the “one feature one element” rule and existing software that needs to decide “what a thing is” (including the name-suggestion-index) won’t understand it.

**Comment by SafetyIng** [comment]
> this style of tagging goes against the “one feature one element” rule

I just find that it strictly follows "one feature one element". Because it is not either XY or ZW, but both at the same time. Thus, the element must also represent both elements, which belong together and form a store together. 

> existing software that needs to decide “what a thing is” (...) won’t understand it.

Why not? Some elements can handle two "services" at the same time, why not mark them together? 

> including the name-suggestion-index

There are simply limits to the NSI somewhere. But I think, that here the NSI could handle it with the approved tagging.....
