### ISSUE TITLE
`operator` vs `network` for charging stations

### ISSUE THREAD

**Issue by MikiDi** [osmlab/name-suggestion-index#5752]
Together with the Belgian OSM community I have been recently [looking in to](https://github.com/pietervdvn/MapComplete/issues/389) improving the coverage of electrical (car) charging stations on the map. Given the fragmented nature of the charging landscape (different authentication methods, plans, key-cards, ...), providing information on which network a certain charge point belongs to, seems quite important. NSI came to mind.
In the NSI, tagging for charging stations seems to be [built around the operator tag](https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station).

In practice however (at least in Belgium) it is rarely clear who the real [operator](https://wiki.openstreetmap.org/wiki/Key:operator) of a station is. What mostly ís clear, is the name of the _network_. A quick [search in the issues here](https://github.com/osmlab/name-suggestion-index/issues?q=charge+network) suggests that this is more often the case than one might think. 

a) Would PR's for `amenity=charging_station` suggestions adding `network` instead of `operator` be accepted?
b) Am I right in questioning if some of the suggestions marked with `operator` [here](https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station) should actually be `network`?

**Comment by bhousel** [comment]
> In the NSI, tagging for charging stations seems to be built around the operator tag.

Charging Stations are one of those categories that hasn't neatly fit into NSI:
- It was originally built around the `brand` tag,
- Then I moved it to the `operator` tag in #2928,
- Then to better match Tesla https://github.com/osmlab/name-suggestion-index/pull/5623#issuecomment-958647514 I made it possible for them to be listed either in `operator` or `brand`.

So it sounds like in your case (where the `operator` can be anything) - these charging stations could be moved to `brand`, scoped with reasonable locationSets, and you can add a `network` tag if you want to.  That's what I'd do.

**Comment by MikiDi** [comment]
Did some more research and (at least for Brussels) I managed to figure out the operating structure and documented on wikidata. Opened #5809 .
