### ISSUE TITLE
Suggest links to location- and feature-specific documentation

### ISSUE THREAD

**Issue by ZeLonewolf** [osmlab/name-suggestion-index#5753]
When editing the map, it would be useful if the mapper can be shown context-specific documentation that is relevant to the location and/or feature they are editing.  Below are some examples of location AND feature-specific tagging guidelines:

* [Vermont highway classification](https://wiki.openstreetmap.org/wiki/Vermont#Highway_classification_in_the_general-purpose_road_network)
* [Dutch highway conventions](https://wiki.openstreetmap.org/wiki/NL:Overzicht_Nederlandse_Verkeersborden)
* [Deprecation of associatedStreet in Germany](https://wiki.openstreetmap.org/wiki/Talk:Relation:associatedStreet#Deprecation_of_associatedStreet_in_Germany)
* [Ireland boundary guidelines](https://wiki.openstreetmap.org/wiki/Ireland/Mapping_Townlands)

In addition, there are guidelines which apply to a specific location broadly.  These might be shown when the map is centered on specific regional locations:

* [East Africa tagging guidelines](https://wiki.openstreetmap.org/wiki/East_Africa_Tagging_Guidelines)
* [Chinese tagging guidelines](https://wiki.openstreetmap.org/wiki/Chinese_tagging_guidelines)
* [Australian tagging guidelines](https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines)
* [India tagging guidelines](https://wiki.openstreetmap.org/wiki/India#tagging_guidelines)

By creating a stronger link to the project's documentation, it encourages tagging consistent with local community expectations and also increases the motivation for mappers to develop documentation.

**Comment by 1ec5** [comment]
Some regional wiki pages are already listed in the osm-community-index ([example](https://github.com/osmlab/osm-community-index/blob/9cafacad66822194ac6b7de351483978c35e3d5c/resources/north-america/united_states/US-MI-Wiki.json#L10)), but the post-save screen is rather late to present some of the more tagging-centric pages.

There’s also an opportunity to ensure that the more important tagging guidelines are stored somewhere in machine-readable format so editors can help mappers do the right thing, even by default in some cases. But that’s probably more relevant to [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/) than this repository.

**Comment by bhousel** [comment]
Yea agree with @1ec5 that "link to guidance" property is something that belongs more in id-tagging-schema.. But if that project ever did implement such a thing, it would be useful for some NSI generated presets too.

https://github.com/openstreetmap/iD/issues/3022#issuecomment-195643286 is an old ticket about embedding tag guidance in iD.
