### ISSUE TITLE
Forever 21 preset missing

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#5758]
We have an entry for it
https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=forever#forever21-3937bd

But I don't see it `dist/presets/nsi-id-presets.json`, so there's no preset for it in iD:
<img width="682" alt="Screen Shot 2021-11-29 at 5 34 01 PM" src="https://user-images.githubusercontent.com/38784/143954463-e858d5ca-ff03-4adf-a738-8ebcfe91ff3c.png">

I don't see any obvious reason why this would be missed, so I'm going to look into why it's missing.

**Comment by maxerickson** [comment]
Marked as defunct in Wikidata (parallel edit to the one that marked Mobil defunct, as discussed on OSM US Slack).

**Comment by bhousel** [comment]
Oh good call @maxerickson 👍 

It makes sense now, but I find the behavior kind of surprising.  Maybe we should generate these as non-addable presets?

**Comment by bhousel** [comment]
> Maybe we should generate these as non-addable presets?

☝️  I did this in a0a3505ba
