### ISSUE TITLE
Conoco

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/name-suggestion-index#5762]
Hi,

I found a station with the name Conoco and the brand ConocoPhillips.
ID wants to change the brand to Conoco (and to change the wikidata too).

Conoco is the old name of the compagny : it became ConocoPhillips in 2002 like you can read it on wiki : [Conoco](https://en.wikipedia.org/wiki/Conoco) and [ConocoPhillips](https://en.wikipedia.org/wiki/ConocoPhillips).

So the informations in osm are ok (including the wikidata), not what ID wants to do.

Please correct that.
Best regards

**Comment by arch0345** [comment]
Related to #5620

**Comment by arch0345** [comment]
I haven't taken a good look at this but at first glance it seems that the updated Wikipedia article refers to both the brand and the defunct company. We usually use the wikidata/wikipedia of the brand itself rather than the parent company except for cases like Choice Hotels when they don't have their own articles.

**Comment by bhousel** [comment]
@1ec5 knows about this.

**Comment by 1ec5** [comment]
The brand is still called Conoco, even if the company has merged into ConocoPhillips. Wikidata correctly distinguishes the brand as it is today: https://github.com/osmlab/name-suggestion-index/pull/5620#discussion_r740041078. The English Wikipedia is in awkward spot because a single article talks about both the brand and the former company. It would be incorrect to link to the “ConocoPhillips” article in `brand:wikipedia`, but we could remove `brand:wikipedia` if it’s too confusing.

**Comment by Mahabarata** [comment]
Hi,

I think the current wikidata is ok in ID : the number [109341187](https://www.wikidata.org/wiki/Q109341187) is the brand, still alive. 

You also have 3 different wikidatas for the compagny = [Conoco Inc](https://www.wikidata.org/wiki/Q1126518), ending 2002, [ConocoPhillips](https://www.wikidata.org/wiki/Q214763), still alive but they split in 2012 the upstream from the midstream/downstream, and they own no more the Conoco brand, and [Phillips 66](https://www.wikidata.org/wiki/Q1656230), the actual name of the compagny, owner of the brand.

A link to one (or more) of these 3 wikidatas is not needed.

The problem is the tag "brand:wikipedia" : in fact, on wikipedia, you have no page for the brand. If you search "conoco", wikipedia gives you the compagny Conoco Inc, which ended in 2002.

On this page, you have a section for the "Conoco brand" so you could think that it is ok.

But you also have informations about the Conoco brand on the wikipedia page of the new name of the compagny [Phillips 66](Phillips 66) (in the sections "Gas stations" and "Mergers").

So, because there is no page for the brand, I think a link to the new name of the compagny selling the brand is better than a link to the dead compagny.

Best regards

**Comment by 1ec5** [comment]
The article was [recently rewritten](https://en.wikipedia.org/wiki/Special:Diff/1058166213) to deemphasize the brand in favor of the former company. We could append `#Conoco_brand` to the `wikipedia` tag and hope the section remains titled that way, but I think it would be more appropriate to delete the `wikipedia` tag altogether. This is a great example of how Wikipedia is too unspecific and unstable to link to compared to Wikidata.

**Comment by arch0345** [comment]
I removed the `brand:wikipedia` tag and also unlinked the article from the wikidata page for now so that it doesn't get added the next time `npm run wikidata` is run

**Comment by 1ec5** [comment]
The Conoco Inc. article was correctly linked to the Wikidata item about Conoco Inc., which is distinct from the item about the brand that NSI is using.

**Comment by arch0345** [comment]
For some reason the English article was linked to the Wikidata item for the brand, I'll link it to the item that's about the defunct company

**Comment by arch0345** [comment]
>The Conoco Inc. article was correctly linked to the Wikidata item about Conoco Inc., which is distinct from the item about the brand that NSI is using.
Shouldn't the article be linked to [Q1126518](https://www.wikidata.org/wiki/Q1126518)?

**Comment by 1ec5** [comment]
Yes, it’s correct now. Though it looks like the Japanese article for the brand got lost in the shuffle.
