### ISSUE TITLE
The Possibility of adding `network` to Hotels

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5766]
This is an amend to my suggestion on #5691 with any sort of additions to the hotel category in nsi. Thanks to #5752 for the possibility of this improvement.

Thanks to bhousel & his input as well as reading up on the OSM wiki again, left me pondering on how to improve in terms of the OSM community, so I come back with a different approach, adding network into hotel chains via loyalty program affiliation.

`network` could work in this possible addition, but only in speculation for now, as a practice has not been yet done. This is only posted to have a conversation on any sort of implementation or improvement on this concept.

**Comment by bhousel** [comment]
> `network` could work in this possible addition, but only in speculation for now, as a practice has not been yet done. This is only posted to have a conversation on any sort of implementation or improvement on this concept.

I guess as of today the `network` tag isn't used this way by OpenStreetMap:
https://wiki.openstreetmap.org/wiki/Key:network

This NSI project isn't really in a position to expand the use of the tag into other purposes, and I'm not even sure it's the right thing to do.  @arnowrld I'm going to close this issue, but I'd like to chat more with you about the sorts of issues you've been opening and why you want these things.  Maybe we can chat on Slack?
