### ISSUE TITLE
Issue on bicycle rental network

### ISSUE THREAD

**Issue by Kalepom** [osmlab/name-suggestion-index#5772]
Hi,
On bike rentals operated by JCDecaux, the preset suggest you to swith to network "Bicloo", which is the bike network in Nantes, but not in every city of France.
![142781738-551c24f8-c7eb-4fc9-b684-4620bc60a611 1](https://user-images.githubusercontent.com/12937457/144251222-befbcf83-a8ee-4805-85b3-9ab64a2200f9.png)

**Comment by arch0345** [comment]
Related to ##5562

**Comment by arch0345** [comment]
Thanks for catching this! It looks like this might get fixed by adding Vélo'v to the index so I'll add it as soon as possible
