### ISSUE TITLE
Ippudo and Coco Ichibanya restaurants in the UK

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#5776]
Both Ippudo and Coco Ichibanya have restaurants in the UK, should their existing entries be updated to reflect this or is there a precedent for creating a new entry if it has a different website though is still part of the same brand?

https://www.ippudo.co.uk/
https://ichibanya.uk/

**Comment by arch0345** [comment]
I would create a new entry for these as the ones in the index currently don't have the English name in `name=*`. You just need to replace the displayName, name, brand, and brand:wikipedia for the new entries.

**Comment by codeinabox** [comment]
> I would create a new entry for these as the ones in the index currently don't have the English name in `name=*`. You just need to replace the displayName, name, brand, and brand:wikipedia for the new entries.

So the new entry would have the same id or different?

**Comment by arch0345** [comment]
Don't worry about the id, we have a script that automatically generates unique ids for each entry.

**Comment by UKChris-osm** [comment]
I feel like "_Coco Ichibanya_" doesn't really need its own entry for the UK as it only has two locations in London, but the chain does have locations in the US as well, so maybe an international entry for non Japan / China restaurants would be better?

Also, is "_fast food_" the correct category for "_Coco Ichibanya_"? It feels like "_restaurant_" might be more accurate?

**Comment by assanges** [comment]
It depends on different countries, their positioning varies in different markets. 

I would say some Japanese chains become rather classy when they've landed overseas, 
e.g., YAYOI (やよい軒/ Yayoyi Ken), Komeda's Coffee (コメダ珈琲店/ Komeda Kо̄hīten) in Taiwan,
think of it as your usual meal deal would take you £5-7 (maybe another 50p for exotic dishes?), 
but those classy & healthy meals might be £10-12, ~~definitely would drain out your bloody wallet for such a style~~
