### ISSUE TITLE
[JOSM] Presets can't be applied on ways

### ISSUE THREAD

**Issue by AntoninCurtit** [osmlab/name-suggestion-index#5784]
## The goal
Applying "Enedis" (electricity provider in 🇫🇷 France) informations on **[nodes](https://www.openstreetmap.org/node/7122618283)** and **[ways](https://www.openstreetmap.org/way/762276306)**.
## The issue
Being unable to apply [`power=minor_line`](https://wiki.openstreetmap.org/wiki/Tag:power%3Dminor_line) on ways.

| ✔️ Node | ❌ Way |
|-----------|---------|
| ![image](https://user-images.githubusercontent.com/30950182/144642842-3d9c5ae7-827f-41d0-9c7d-ba20e53fd601.png) | ![image](https://user-images.githubusercontent.com/30950182/144642869-1913ab32-fbf8-49e9-8fa8-6293d7ab8c11.png) |

## Tested solutions
  - **Instead of pressing F3 and searching for "Enedis", pressing SHIFT+F3 and searching.** Sadly, the selection isn't applied for no reason and without warning.
  - **Applying it via the Preset menu.** Had the warning below, saying the selection (the way) isn't compatible.
    ![image](https://user-images.githubusercontent.com/30950182/144644160-aab96e61-0888-43d0-b185-08b1ddb92227.png)

## That's all ?
Yes ! Hope you can help, thank you !

**Comment by bhousel** [comment]
Thanks for raising this @AntoninCurtit .. I haven't looked at this code in a while and all of the presets were still being generated with preset type `'node,closedway,multipolygon'`.  I added some code in f2993fa to pick better types for some categories.

**Comment by AntoninCurtit** [comment]
Glad to have helped, and thanks a lot for fixing it so quickly and for explaining ! 🤜🤛😉
