### ISSUE TITLE
flagpole preset request: Navajo Nation

### ISSUE THREAD

**Issue by ArloJamesBarnes** [osmlab/name-suggestion-index#5786]
discussion context: https://osmus.slack.com/archives/CDBMHU6QY/p1610731707001100?thread_ts=1610586392.001000&cid=CDBMHU6QY

flag WD: https://wikidata.org/wiki/Q20020313
nation WD: https://wikidata.org/wiki/Q1783171

This is quite a large polity by area, so I chose it to kick off what I hope to be a series of flagpole preset requests of indigenous sovereignties in the Americas (preceded by https://github.com/osmlab/name-suggestion-index/issues/4892) due to the likelihood of there being a significant number of mappable flagpoles IRL.

Thanks!

**Comment by bhousel** [comment]
> This is quite a large polity by area, so I chose it to kick off what I hope to be a series of flagpole preset requests of indigenous sovereignties in the Americas

I love this idea!

**Comment by tas50** [comment]
Glad to see this issue come up. I ran into a tribe flag the other day and it got me thinking about how we could get them all added to the index. It's a big project
