### ISSUE TITLE
Naming (alias) Features

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#5851]
With a full set of States in the [USA](https://github.com/osmlab/name-suggestion-index/tree/main/features/us) & [Australia](https://github.com/osmlab/name-suggestion-index/tree/main/features/au), a full set of Provence's in [Canada](https://github.com/osmlab/name-suggestion-index/tree/main/features/ca), and a sub-set of Counties within [Great Britain](https://github.com/osmlab/name-suggestion-index/tree/main/features/gb), many of which follow [ISO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) (and subset) naming conventions, I'm wondering if there is any scope for adding an optional name / alias to each feature, so we can start referring to any ISO_3166-2 subsets (that aren't part of [country-coder](https://github.com/ideditor/country-coder)) without the need for using the _.geojson_ extension? For example:

Currently:
"locationSet": {"include": ["us-ga.geojson","us-fl.geojson"]}

Could be referenced as:
"locationSet": {"include": ["us-ga","us-fl"]}

**Comment by bhousel** [comment]
I don't see an easy way to change this - having that `something.geojson` in the id is important to how https://github.com/ideditor/location-conflation works

**Comment by UKChris-osm** [comment]
Ah I see, that's understandable.

I was looking ahead to a time when lower regions might end up being available within counter-coder or iD and thought it might be handy if any _ISO_3166-2:subset_ we have could be referenced in our data folder directly, meaning we didn't have to update them all at a later date.

**Comment by bhousel** [comment]
> I was looking ahead to a time when lower regions might end up being available within counter-coder or iD and thought it might be handy if any _ISO_3166-2:subset_ we have could be referenced in our data folder directly, meaning we didn't have to update them all at a later date.

This is a good thought, however country-coder is kind of a "spare time" sort of project for us, and I'm really [struggling with some of the complexity of it](https://github.com/ideditor/country-coder/issues/47), so I don't want to change too much about it.  For now it's probably best to think about country-coder as "the country geometries that are built into iD".  If it ever actually breaks, we might refactor its internals or expand its scope.
