### ISSUE TITLE
VVR is matched with DE-BW-VVR instead of DE-MV-VVR

### ISSUE THREAD

**Issue by Strubbl** [osmlab/name-suggestion-index#5855]
All bus stops in Mecklenburg-Vorpommern coming from the bus network "Verkehrsgesellschaft Vorpommern-Rügen mbH (VVR)" https://www.vvr-bus.de/vvr/ want to be matched with the "Verkehrsverbund Rottweil GmbH, VVR", which is wrong.

e.g.:
https://www.openstreetmap.org/node/314391709

![image](https://user-images.githubusercontent.com/97055/145901904-3564fa1e-65d2-4379-bf4a-1a0c8db2ae0c.png)

Please do not suggest this name (Rottweil) for bus stops in Mecklenburg-Vorpommern.

**Comment by arch0345** [comment]
Thanks for catching this! It looks like that Verkehrsgesellschaft Vorpommern-Rügen has their own wikidata page already so I'll create its own entry and refine where these two are suggested to prevent this issue from occuring.
