### ISSUE TITLE
Rebel Sport Australia

### ISSUE THREAD

**Issue by aaronstar** [osmlab/name-suggestion-index#5882]
https://nsi.guide/index.html?t=brands&k=shop&v=sports&tt=rebel

Correct from Rebel to Rebel Sport

brand=Rebel Sport
brand:wikidata=Q18636397
brand:wikipedia=en:Rebel (company)
name=Rebel Sport
shop=sports

**Comment by UKChris-osm** [comment]
Rebel seems correct to me? It looks like they dropped the "_sport_" from their name?

**Comment by Mortein** [comment]
Please ensure this is for the correct one, as there are both Australian and New Zealand chains.

Australia is "Rebel" and is Q18636397
New Zealand is "Rebel Sport" and is Q110190372

**Comment by aaronstar** [comment]
Yep sorry, you guys are right they did drop the "Sport" from the Australian chain
