### ISSUE TITLE
Event Cinemas Australia

### ISSUE THREAD

**Issue by aaronstar** [osmlab/name-suggestion-index#5883]
https://nsi.guide/index.html?t=brands&k=amenity&v=cinema&tt=event

Correct from Event to Event Cinemas, delete redundant official_name

amenity=cinema
brand=Event Cinemas
brand:wikidata=Q5416698
brand:wikipedia=en:Event Cinemas
name=Event Cinemas
X<official_name=Event Cinemas>X -- DELETE

**Comment by Artumira96** [comment]
Hello, I created a PR for this issue, can you review it please? :)
