### ISSUE TITLE
Is the Name_Suggestion_Index (NSI) branding recommended?

### ISSUE THREAD

**Issue by sebhan2** [osmlab/name-suggestion-index#5893]
Hello,
I hope this is the right place for my question otherwise please let me know about alternative places to ask this. I also posted my question here but haven't gotten an answer yet.
 https://help.openstreetmap.org/questions/82860/is-the-name_suggestion_index-nsi-branding-recommended

So far I assumed the Name_Suggestion_Index (NSI) feature used in the Id-editor, that allows me to use the branding for particular locations, is a recommended way to give canonical features to particular objects in OSM. I changed some package vending machines of the company DHL to use the NSI brand "DHL Packstation" in germany. This includes besides adding wikidata, also a "name" and an "alt_name".

Now I hear from a user that the "name" and "alt_name" in the branding are key-value-pairs that are not on the OSM wiki page and therefore should not be there. Here is a link: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup

As far as I understand the concern, the vending machine would be rendered differently on a map depending on whether the key "name" is given. I have not seen OSM rendering vending machines explicitly but due to my lack of experience I assume he may have a valid point.

Here are my questions: 
Is the NSI branding a recommended way to choose key-value-pairs?
Which platform should be updated in my case, the NSI branding suggestion or the OSM wiki?

**Comment by bhousel** [comment]
It sounds like @kjonosm took care of this in #5899, thanks!

Copying [my response](https://help.openstreetmap.org/questions/82860/is-the-name_suggestion_index-nsi-branding-recommended/82869) here:

---

Hello, NSI maintainer here 👋

>Is the NSI branding a recommended way to choose key-value-pairs?

Yes, we (contributors to the NSI project) believe that it represents the best way to tag things today. We know that tagging can change, and people will change the wiki, and brands will change their names, and so we tried to build it in a way that any part of it can be easily changed if needed.

> Which platform should be updated in my case, the NSI branding suggestion or the osm wiki?

That depends? Sometimes the NSI is wrong, sometimes the Wiki is wrong, and sometimes the renderer is wrong. You can ask the local community how they want Packstations tagged. NSI has maintainers from all around the world, and this might have already been discussed somewhere.If one person just told you on a changeset discussion that you're wrong, that isn't really helpful. Your community should figure it out and decide together whether the name is causing a problem, then someone can open an issue or pull request in NSI and say why they think a suggestion is wrong, and we will fix it. Someone should also update the wiki, with a link back to where the discussion happened and why it was decided a certain way.
