### ISSUE TITLE
Add Chicken Salad Chick

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#5897]
Chicken Salad Chick is a fast-casual restaurant chain.

[Q19720749](https://www.wikidata.org/wiki/Q19720749)

**Comment by UKChris-osm** [comment]
Would a fast-casual restaurant be better placed as "_amenity=fast_food_" or "_amenity=restaurant_"?? Overpass shows both are used at the moment.

**Comment by arch0345** [comment]
I just added this to `amenity/restaurant` - other fast-casual places like Noodles & Company are also in here

**Comment by bhousel** [comment]
In the past we’ve put fast casual places into `amenity/fast_food`. restaurant is more for places with table service.
