### ISSUE TITLE
Adding features for New Zealand

### ISSUE THREAD

**Issue by Mortein** [osmlab/name-suggestion-index#5916]
I've been considering tagging all the parks/reserves/playgrounds/toilets operated by [councils throughout New Zealand](https://www.localcouncils.govt.nz/lgip.nsf/wpg_URL/Profiles-Councils-by-Region-Index) and it would be nice to be able to limit these to each region using [ISO 3166-2:NZ](https://en.wikipedia.org/wiki/ISO_3166-2:NZ#Current_codes) codes.

I've had a look at [the wiki](https://github.com/osmlab/name-suggestion-index/wiki/Feature-Files) already, but was just wondering if there is a minimum requirement before a country/region can be added to `features`?

Assuming it's all good, I guess I'll learn about `geojson`...

Just out of interest, how do the polygons magically get from here into [location-conflation](https://location-conflation.com)? Or do they not?

**Comment by arch0345** [comment]
So far we don't have any requirements for regions that can be added to `features`. As for location-conflation, that project was created by @bhousel, who's also a maintainer here. Looks like the regular website only allows codes from [country-coder](https://ideditor.codes/) and point-radius, while the [referral link](https://location-conflation.com/?referrer=nsi) also allows geojsons from this project. Not sure how the geojsons get there though.

When you're creating the geojsons make sure to simplify them (most have only 20-30 points) as we want to make sure it takes the least amount of time for these to load into iD.

**Comment by UKChris-osm** [comment]
[ISO 3166-2:NZ](https://github.com/osmlab/name-suggestion-index/tree/main/features/nz) should now be available to you @Mortein 👍

**Comment by Mortein** [comment]
Fantastic! Thanks @UKChris-osm!
