### ISSUE TITLE
Add First National Bank of Long Island

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5929]
This is incorrectly matching with [First National Bank](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=first%20national#firstnationalbank-6e848a). They have around 40 locations on Long Island: https://www.fnbli.com/locations

**Comment by tas50** [comment]
It's probably worth doing a release after this to prevent more bad data slipping in.

**Comment by PierceWHoward** [comment]
Hope this was okay, I added an entry into Wikidata for it: https://www.wikidata.org/wiki/Q110265410

**Comment by arch0345** [comment]
Looks good @PierceWHoward! I'll add an entry for this when I get back
