### ISSUE TITLE
Research needed for: amenity/fuel|Татнефтепродукт

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#593]
#### :thinking: We need help deciding what to do with "amenity/fuel|Татнефтепродукт"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/fuel|Татнефтепродукт` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/fuel|Татнефтепродукт`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/fuel|Татнефтепродукт`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
Can somebody tell me how this entry is different from this one:
https://github.com/osmlab/name-suggestion-index/blob/39656f0a503b97392f8c18e553ad085c8efb3566/brands/amenity/fuel.json#L2973-L2984

During my research it looked as if both gas stations use the same logo, so this might just be another name for that brand?

**Comment by matkoniecz** [comment]
Татнефть -> Tatneft

Татнефтепродукт -> Tatneft product

both are probably referring to the same company

according to person who I bother about Russian/Belarusian/Ukrainian brands.

**Comment by Adamant36** [comment]
Going by past experience and minor research, Tatneft product is probably miss tagging and as such might be worth purging/adding to the warning system.

**Comment by ENT8R** [comment]
> During my research it looked as if both gas stations use the same logo, so this might just be another name for that brand?

I just checked again and now I found that both companies actually have a different logo and a different website:
- Татнефть (Tatneft): https://azs.tatneft.ru/
- Татнефтепродукт (Tatneft product): http://tatnp.ru/
During my first research I didn't found the website for Татнефть that's why I thought it might be the same company.
