### ISSUE TITLE
Missing tags for entries

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#5934]
Copy-pasted these warnings from the build script:

- [x]   "Naturals (naturals-2dc292)" -> missing tag? -> "beauty"
- [x]   "Regiomat (regiomat-a242c5)" -> missing tag? -> "vending"
- [x]   "Selecta (selecta-ed4d31)" -> missing tag? -> "vending"
- [x]   "Tokeny.Store (tokenystore-eb9a2c)" -> missing tag? -> "vending"
- [x]   "ALEX (alex-051971)" -> missing tag? -> "cuisine"
- [x]   "Cactus Club Cafe (cactusclubcafe-e68b16)" -> missing tag? -> "cuisine"
- [x]   "Cafe & Bar Celona (cafeandbarcelona-3fc85c)" -> missing tag? -> "cuisine"
- [x]   "Cafe Del Sol (cafedelsol-b8cc79)" -> missing tag? -> "cuisine"
- [x]   "Caravan (caravan-e997f8)" -> missing tag? -> "cuisine"
- [x]   "De Beren (deberen-2b67bf)" -> missing tag? -> "cuisine"
- [x]   "Doppio Malto (doppiomalto-94430a)" -> missing tag? -> "cuisine"
- [x]   "Earls (earls-85c92c)" -> missing tag? -> "cuisine"
- [x]   "Fournos Bakery (fournosbakery-69fbf5)" -> missing tag? -> "cuisine"
- [x]   "Honest Greens (honestgreens-1d6b00)" -> missing tag? -> "cuisine"
- [x]   "Interspar Restaurant (intersparrestaurant-c7016b)" -> missing tag? -> "cuisine"
- [x]   "Joey (joey-85c92c)" -> missing tag? -> "cuisine"
- [x]   "Karas (karas-86098b)" -> missing tag? -> "cuisine"
- [x]   "Kauai (kauai-14572f)" -> missing tag? -> "cuisine"
- [x]   "La Place (laplace-179420)" -> missing tag? -> "cuisine"
- [x]   "Lunch Garden (lunchgarden-c1dacf)" -> missing tag? -> "cuisine"
- [x]   "Madero (madero-ad49e6)" -> missing tag? -> "cuisine"
- [x]   "Mary Grace (marygrace-5259a4)" -> missing tag? -> "cuisine"
- [x]   "Mildreds (mildreds-e997f8)" -> missing tag? -> "cuisine"
- [x]   #8911
- [x]   "Romantik (romantikrestaurant-2fabb0)" -> missing tag? -> "cuisine"
- [x]   "Thyme (thyme-9b5453)" -> missing tag? -> "cuisine"
- [x]   "김밥천국 (5006b9-5f8110)" -> missing tag? -> "cuisine"
- [x]   "Do.Bro Coffee (dobrocoffee-7582d1)" -> missing tag? -> "cuisine"
- [x]   "Автосуши Автопицца (6f845a-7582d1)" -> missing tag? -> "cuisine"
- [x]   "Шаверлэнд (174051-658eea)" -> missing tag? -> "cuisine"

**Comment by Mortein** [comment]
"Vegetacion (vegetacion-2fabb0)" is `landcover=trees` [tagged with a name](https://overpass-turbo.eu/s/1eKu) in Paraguay.
The name isn't in use anywhere else.

I've removed the name from around five named "Vegetacion", but there are still over 3000 named "vegetacion".

**Comment by bhousel** [comment]
> "Vegetacion (vegetacion-2fabb0)" is `landcover=trees` [tagged with a name](https://overpass-turbo.eu/s/1eKu) in Paraguay. The name isn't in use anywhere else.

Thanks for checking, I'm removing it from the `restaurant.json` file now..

**Comment by Mortein** [comment]
"Valentino (valentino-2fabb0)" is generic, it ranges from shoes to nightclubs. Valentino (a fashion brand) is already indexed. #5991 adds an Italian restaurant chain in Nebraska.

"Farmhouse Inns (farmhouseinns-9b5453)" is British food. `cuisine=british` isn't unpopular, with over 500 uses.

"De Beren (deberen-2b67bf)" and "La Place (laplace-179420)" need somebody familiar with the Netherlands.
"Maquis Restaurant (maquisrestaurant-50bee3)" needs somebody familiar with Ivory Coast.

"Santa Lucia (santalucia-282f19)" is in Switzerland. @habi, are you able to help out?

**Comment by habi** [comment]
"Santa Lucia" sounds like a generic Italian restaurant in Switzerland, and a search confirms this: https://osm.li/EnL
It's the name of a 'chain' of restaurants from a bigger chain, Bindella: https://www.bindella.ch/die-gastronomie/santa-lucia (couldn't quickly find an English website...)

**Comment by matkoniecz** [comment]
> Parkometr podstrefa A

invalid descriptive name ("Parking ticket machine in subarea A")

**Comment by AntiCompositeNumber** [comment]
Looks like these have been done, mostly by @Snowysauce, thanks!

**Comment by kjonosm** [comment]
@arch0345 Can this issue be closed?

**Comment by Cj-Malone** [comment]
I think so, we can have a new issue when/if needed
