### ISSUE TITLE
Add `brands/office/union` catagory

### ISSUE THREAD

**Issue by 91560** [osmlab/name-suggestion-index#5937]
- [ ] IG Metall
- [ ] NGG

```json
    {
      "displayName": "IG Metall",
      "locationSet": {"include": ["de"]},
      "preserveTags": ["^official_name"],
      "matchNames": ["igm", "ig metall"],
      "tags": {
        "brand": "IG Metall",
        "brand:wikidata": "Q694821",
        "brand:wikipedia": "de:IG Metall",
        "office": "union",
        "official_name": "Industriegewerkschaft Metall"
      }
    }
```

```json
    {
      "displayName": "NGG",
      "locationSet": {"include": ["de"]},
      "preserveTags": ["^official_name"],
      "matchNames": ["ngg", "nahrung-genuss-gaststätten"],
      "tags": {
        "brand": "NGG",
        "brand:wikidata": "Q896313",
        "brand:wikipedia": "de:NGG",
        "office": "union",
        "official_name": "Gewerkschaft Nahrung-Genuss-Gaststätten"
      }
    },
```

**Comment by LaoshuBaby** [comment]
Thank you for give us those information

But we current haven't `brands/office/union` catagory.

![图片](https://user-images.githubusercontent.com/42690037/147466949-74d7c91f-9a90-4035-b990-07bfc1ba989c.png)

--

Besides, your another issue is the same problem so I close #5936 and merge them in this one issue.

**Comment by 91560** [comment]
Hello.

Oh, "office=union" (<https://wiki.openstreetmap.org/wiki/Tag:office=union>) is in use. Maybe it would be an good idea to make new category "brands/office/union"

**Comment by 91560** [comment]
Thank you

**Comment by LaoshuBaby** [comment]
You don't need to close if you want those 4 brand added, we can wait for other maintainer's discussion
