### ISSUE TITLE
Mabe police.json is written incorrectly for the Cyrillic

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5956]
I don't know the syntax for json, but I suspect there is an error on line 7 in the police file.

There may have been a confusion between the clinic and the police for the Cyrillic alphabet. Maybe i'm wrong.

https://github.com/osmlab/name-suggestion-index/blob/fed7491f0ef9690b8e4dffd310a78b256c91c530/data/operators/amenity/police.json#L7

поликлиника (rus), палiклiнiка (be)  — its a polyclinic, medical institution https://www.wikidata.org/wiki/Q695416 

A police — https://www.wikidata.org/wiki/Q35535

Паліцыя — be
Полиция — ru, bg, kk, ky
Полиција — sr, mk	
Поліція — uk	
Полиций— mhr	

In Russia it may be called:
- участковый пункт полиции (№N),
- пункт полиции,
- пункт дорожной полиции
- полиция,
- полицейский участок,
- участок полиции,
- опорный пункт полиции.

**Comment by arch0345** [comment]
This could have been a mistake when moving it from the genericWords file here:
https://github.com/osmlab/name-suggestion-index/commit/3aada3eebe96036f38b35b9bb29ea0caa21cfebd

**Comment by bhousel** [comment]
Thanks @afanasovich ! this was very helpful..

in 6145838 I did:
- move `"^пол[иі]кл[иі]н[иі]ка( №1)?$"` from "police" to the clinic-like categories
- use `"^п[ао]л(іцыя|иция|иција|іція|иций)$"` as the generic Cyrillic "police" matcher
