### ISSUE TITLE
Problem with «Кофе Хауз»

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#5957]
Кофе Хауз — its brand in Russia, and not a common name for coffee houses.

Кофе Хауз is one of the largest coffee chains in Russia and Ukraine, as well as a coffee company.

https://www.wikidata.org/wiki/Q4236456
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%84%D0%B5_%D0%A5%D0%B0%D1%83%D0%B7
https://en.wikipedia.org/wiki/Kofe_Khauz

But for `name = Кофе Хауз`, a message about a suspicious name is issued. We do not use the word «Кофе Хауз» to refer to any coffee house, but only use it for this brand. 

Fix it, pleace

![image](https://user-images.githubusercontent.com/75438207/147670708-d5beb938-29cd-42ca-b67b-c873bb275bfc.png)

**Comment by arch0345** [comment]
I think this is an issue with iD - NSI doesn't have a list of suspicious names. You can open an issue in the iD repo here: https://github.com/openstreetmap/iD/issues/new/choose

**Comment by UKChris-osm** [comment]
@arch0345 I think this was an NSI issue, as there was a regEx telling the NSI to [discard Кофе Хауз](https://github.com/osmlab/name-suggestion-index/blob/64513ab0e7a69468f6584ed05e0b209a0cddc843/dist/filtered/brands_discard.json#L333), as this does appear to translate to just "_coffee house_", so I can understand why it was in there.

@afanasovich I have [added Кофе Хауз](https://github.com/osmlab/name-suggestion-index/commit/64513ab0e7a69468f6584ed05e0b209a0cddc843) and removed the regEx, can you confirm if it looks correct from your perspective?

Could you also conform if "_кофейня_" is just a generic name, or if that should be a brand too?

**Comment by afanasovich** [comment]
> 
“‘Кофейня’” — it’s common name for any coffee house (cafe with a focus on coffee) in Russian language, not brand. https://ru.m.wikipedia.org/wiki/Кофейня 

But we have a big chain «Венская кофейня». CoffeeShop Company (https://www.wikidata.org/wiki/Q873767) uses both name in Russia: «Венская кофейня» and “CoffeeShop”.

**Comment by bhousel** [comment]
I think @UKChris-osm's edits took care of all these!  Let us know if there is anything else..
