### ISSUE TITLE
Please Add City Colleges of Chicago

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#5970]
https://en.wikipedia.org/wiki/City_Colleges_of_Chicago

**Comment by iamericfletcher** [comment]
I can help with this. I just got the project up and running locally, so it may be a day or two. This will be my first time contributing, so please bare with me as I am learning the project from the backend.

**Comment by bhousel** [comment]
Can we not do this yet?  We don't currently add universities to the index, except for the ones that operate like a branded business in multiple locations, such as DeVry or University of Phoenix. 

It looks like the City Colleges of Chicago only operate 12 campuses in the Chicago area.

**Comment by Zol87** [comment]
@bhousel Thanks, I understand.
