### ISSUE TITLE
Please Add AT&T under brands/office/telecommunication

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#5971]
AT&T needs a separate category for its' telecom offices.
https://en.wikipedia.org/wiki/AT%26T

**Comment by LaoshuBaby** [comment]
Yes, both `brands/office/telecommunication` and `brands/shop/telecommunication` don't have `AT&T`

I think it is well-known enough to be added

```json
    {
      "displayName": "AT&T",
      "locationSet": {"include": ["001"]},
      "matchNames": ["ATT"],
      "tags": {
        "brand": "AT&T",
        "brand:wikidata": "Q35476",
        "brand:wikipedia": "en:AT&T",
        "name": "AT&T",
        "office": "telecommunication"
      }
    },
```

**Comment by LaoshuBaby** [comment]
But I search on taginfo

There are no element named of `AT&T`

![图片](https://user-images.githubusercontent.com/42690037/147846293-287a97f6-9b7f-405a-b9c6-db40c53e12e2.png)

also `AT and T` have no result

![图片](https://user-images.githubusercontent.com/42690037/147846300-eac526a0-f671-47b5-b3c8-a45f9a70d8f0.png)

But `ATT` have a lot of element

Maybe you can confirm the name it should used, then I will add it into NSI

![图片](https://user-images.githubusercontent.com/42690037/147846321-4c0e4c6e-f579-40fa-9327-9774ee162b01.png)

**Comment by arch0345** [comment]
If you search for `name=AT&T` it shows that there's over 2000 features that have the same name:
![Screenshot_20220101-120622.png](https://user-images.githubusercontent.com/85302075/147859246-24f6b2f6-d957-44d0-816c-510b9ae4cba1.png)

**Comment by tas50** [comment]
Are the shop/telecommunication shops different than their mobile phone stores?

**Comment by LaoshuBaby** [comment]
> If you search for `name=AT&T` it shows that there's over 2000 features that have the same name:

![图片](https://user-images.githubusercontent.com/42690037/147936270-f919e316-34ec-4f69-8a6c-34ce6191995c.png)
Yes, a strange thing……Thank you remind me this.

I will add it soon.

**Comment by Zol87** [comment]
@tas50 Yes, AT&T runs the Telecom Infrastructure for landline phones in Chicagoland.
