### ISSUE TITLE
JEA also runs the water infrastructure in Jacksonville

### ISSUE THREAD

**Issue by BHGobuchul** [osmlab/name-suggestion-index#5990]
Nice to see the electrical infrastructure in Jacksonville tagged with the JEA logo, but they also do all the water infrastructure too

i.e.
https://www.openstreetmap.org/relation/13631134

Thanks,
Horza

**Comment by arch0345** [comment]
Thanks for your suggestion! I was looking into what other categories we could add for water utilities in #5499: so far we support `man_made=wastewater_plant`, `man_made=water_works`, `man_made=water_tower`, and `office=water_utility`. I'll add an entry under `man_made=wastewater_plant` for now. Let me know if any other of the categories above also apply for JEA

**Comment by bhousel** [comment]
oh @arch0345  I just did this - I added it to a bunch of the categories, and made locationset smaller too..

**Comment by arch0345** [comment]
Thanks @bhousel, didn't notice we have a `natural/water` category for reservoirs

**Comment by BHGobuchul** [comment]
They have water treatment plants, so man_made=water_works, and apparently have over 120 wells. Not sure about everything else @arch0345

Thanks

**Comment by UKChris-osm** [comment]
> Thanks @bhousel, didn't notice we have a `natural/water` category for reservoirs

I only added this very recently to the index.
