### ISSUE TITLE
Change to new tagging scheme for parcel lockers

### ISSUE THREAD

**Issue by Eifelkobold** [osmlab/name-suggestion-index#6026]
Hello, since 3rd January 2022 a [new tagging scheme](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker#Tagging) for parcel lockers is approved. It changes `amenity=vending_machine` to `amenity=parcel_locker` and deprecates the `vending=parcel_*`. Also the news tags `refrigerated=yes`, `parcel_pickup=yes / no` and `parcel_mail_in=yes / no / returns_only` were introduced. I think we should change the name suggestion index as well.

I have listed below my tagging suggestion for affected features:

- **DHL Packstation:**
change `amenity` to `amenity=parcel_locker`
add `parcel_pickup=yes` and `parcel_mail_in=yes`
remove `vending`
- **DHL Paketbox:**
change `amenity` to `amenity=vending_machine` and brand to `brand=DHL Paketbox`
add `parcel_pickup=no` and `parcel_mail_in=yes`
remove `name` and `vending`
- **Amazon Hub Locker:**
change `amenity` to `amenity=vending_machine` and `brand` to `brand=Amazon Hub Locker`
add `parcel_pickup=yes`, `parcel_mail_in=returns_only` and `operator=Amazon`
remove  `name` and `vending`
- **Amazon Hub ロッカー**
change `amenity` to `amenity=vending_machine`
add `parcel_pickup=yes`, `parcel_mail_in=returns_only` and `operator=Amazon`
remove `name` and `vending`
- **Other companies where I don´t have local knowledge** _([see NSI-search](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=parcel_))_**:**
change `amenity` to `amenity=parcel_locker`
add `parcel_mail_in=yes / no / returns_only`, `parcel_pickup=yes / no` depending on old `vending`.
add `operator` if missing
remove `vending`
remove `name` if same with `brand`

Some parcel lockers who only had the `parcel_pickup` tag may allow returns too. Maybe locals can help?

**Comment by bhousel** [comment]
This seems ok, but we should wait for [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) to update the presets first.

**Comment by arch0345** [comment]
#6020 will add this new tagging scheme

**Comment by bhousel** [comment]
> #6020 will add this new tagging scheme

yea, but let's leave open for now because I think we will have to actually change some things on our end too whenever the new release of the id-tagging-schema is out..

**Comment by bhousel** [comment]
specifically we'll have to change this, but we shouldn't change it yet:
https://github.com/osmlab/name-suggestion-index/blob/fe358961bf175d06732c0a048dcd730602b363e0/scripts/dist_files.js#L238-L242

**Comment by overflorian** [comment]
> > #6020 will add this new tagging scheme
> 
> yea, but let's leave open for now because I think we will have to actually change some things on our end too whenever the new release of the id-tagging-schema is out..

Hi, I made such a request today and also to JOSM, Vespucci and more. See full list here https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup#Tools
I suggest you don't wait to implement it. If all the projects wait for a change, it will never happen.
Regards

**Comment by arch0345** [comment]
> specifically we'll have to change this, but we shouldn't change it yet:
> 
> https://github.com/osmlab/name-suggestion-index/blob/fe358961bf175d06732c0a048dcd730602b363e0/scripts/dist_files.js#L238-L242

I'm thinking of doing a release today to fix some issues that were fixed this past week such as #6069, do you think we should wait for the id-tagging-schema release or maybe, release as-is (after changing `dist_files`), or move the addition of `amenity/parcel_locker` to its own branch until the next version of id-tagging-schema is released?

**Comment by bhousel** [comment]
> I'm thinking of doing a release today to fix some issues that were fixed this past week such as #6069,

Yeah I'd also like to get a release out today - @arch0345 can you work through any other backlog PRs and other stuff that you can finish up in the next few hours, and I'll look into these lines of code to see what is needed?

**Comment by bhousel** [comment]
ok I think we're good to generate new parcel locker presets now:
- 33e2007c7 Remove hack for `vending=parcel_pickup;parcel_mail_in` (closes #6026)
- dad1ce5b2 Generate an NSI preset even if we don't match an iD preset re: https://github.com/openstreetmap/id-tagging-schema/issues/352

Before the script was depending on id-tagging-schema to have a preset, but now we will just fallback to a generic one (like `shop=yes`) if we don't match anything specific.  This way we're not waiting on them to release stuff.
