### ISSUE TITLE
Janovic Paint gets overwriten by Benjamin Moore preset

### ISSUE THREAD

**Issue by mxxcon** [osmlab/name-suggestion-index#6031]
node 5797537804
https://janovic.com/location/upper-east-side/
I don't know the exact relationship between Janovic Paint and Benjamin Moore Paint, but it looks like many(all?) of their stores are co-branded(?), so it seems incorrect for iD to want to completely overwrite Janovic's branding with Banjamin Moore's..

**Comment by UKChris-osm** [comment]
Being in the UK I can't access the Janovic Web Site, so I'll have to let someone else look into this, but looking at the Benjamin More web site, it looks like they don't have any of their own shops, but simply sell their paint brand via other shop brands, is that correct?

**Comment by mxxcon** [comment]
According to https://www.thecsigroup.com/case-studies/janovic
> Janovic, the exclusive retailer for Benjamin Moore paint in New York City

**Comment by arch0345** [comment]
I preserved the name for Benjamin Moore as well as Ace Hardware and True Value so that iD won't suggest to replace local names like Janovic's

**Comment by tas50** [comment]
@UKChris-osm they franchise and some locations just use the name while others use the original independent paint stores name.
