### ISSUE TITLE
Duplicate entries in amenity/kindergarten

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6051]
Copy-pasted from build script:
Duplicate cache key "amenity/kindergarten/arbeiterwohlfahrt" in trees "operators" and "brands", check items: arbeiterwohlfahrt-747d0f
Duplicate cache key "amenity/kindergarten/awo" in trees "operators" and "brands", check items: arbeiterwohlfahrt-747d0f
Duplicate cache key "amenity/kindergarten/q627256" in trees "operators" and "brands", check items: arbeiterwohlfahrt-747d0f

These should either be only in the brand or operator tree, not sure which tree is best suited for these.

**Comment by kjonosm** [comment]
These should be in the brand tree only. However, the amenity=childcare entry for `Arbeiterwohlfahrt` should be placed there as well, otherwise there are wrong suggestions in iD to change the tag from kindergarten to childcare.

**Comment by kjonosm** [comment]
Will moving the item from `operator` to `brand` still prevent NSI collector from not re-adding it to the `operator` tree?

**Comment by arch0345** [comment]
> Will moving the item from `operator` to `brand` still prevent NSI collector from not re-adding it to the `operator` tree?

Just checked it - it looks like if the entry is in one tree it shouldn't get readded to the other
