### ISSUE TITLE
Create a .json for outdoor advertising operators

### ISSUE THREAD

**Issue by afanasovich** [osmlab/name-suggestion-index#6053]
Hi!

I do not know how in other countries, but in Russia there are large operators of outdoor advertising, for example: 

- https://www.wikidata.org/wiki/Q2029984
- https://www.wikidata.org/wiki/Q4039222
- http://www.poster-group.ru/

Maybe should add a template for advertising operators `name-suggestion-index/data/operators/advertising/...`? 
I do not know how to add new categories. But I can add major players on the Russian market.

**Comment by bhousel** [comment]
> I do not know how to add new categories.

Good point - I should write down how this works 👍 

### "Top Level" tags

NSI can support any category that is defined by a _"top level"_ tag.  What does this mean?

There is a concept in OSM of "top level" / "defining" / "physical" tags which is not well documented, but basically - it's any tag pair that can stand alone by itself and define what a thing _is_. 

For example `amenity=post_office` is a "toplevel" tag.  `surface=dirt` is not, it's just an "attribute" tag that must go alongside something else.  Another example, you can not just draw a rectangle and tag it with the "attribute" tag `sport=soccer` you also need to add the "physical" tag `leisure=pitch`.

The list of "top level" tags we support, is pretty much anything under the id-tagging-schema presets folder:
https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets

### Adding a category to NSI

So we can look at the OSM documentation for the advertising tag:
  https://wiki.openstreetmap.org/wiki/Key:advertising
And we can find it in the id-tagging-schema project:
  https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets/advertising

And it looks ok for use as a "top level" tag, like `advertising=billboard` or `advertising=column`.  

We can make files in the NSI for these as categories, like:
  `data/operators/advertising/billboard.json` 
  `data/operators/advertising/column.json`

And our build script will generate presets that will work in RapiD, JOSM, etc.

### Collecting common "names"

NSI can try to fill the files up these files with common operators collected from the OSM planet, unless the category has [`skipCollection: true`](https://github.com/osmlab/name-suggestion-index/wiki/Category-Property-Reference#skipCollection) property set.

The scripts that do this "name" collection are kind of hacky, and live here: 
https://github.com/ideditor/nsi-collector

This project is not yet collecting any operators tagged alongside the `advertising=` key, so no common operators will get automatically added to a `billboard.json` file.
But if we did want to start collecting operators tagged on advertising stuff, we could add `'advertising'` to this line:
https://github.com/ideditor/nsi-collector/blob/0594a6049c45e3bb91a96d6d29b443b164aff360/collect_osm.js#L30

**Comment by Snowysauce** [comment]
Closing as completed - [this category](https://github.com/osmlab/name-suggestion-index/tree/main/data/operators/advertising) was created in March 2023.
