### ISSUE TITLE
All pubs containing name "Irish Pub" are flagged as generic

### ISSUE THREAD

**Issue by andrewpmk** [osmlab/name-suggestion-index#6068]
All pubs in iD editor containing the name Irish Pub are flagged as generic.

![image](https://user-images.githubusercontent.com/10249827/149608442-fa2ff508-7ec2-4d2d-8140-11223cee0266.png)

Looks like there's an issue with the regular expression matching "irish pub" - should be /^irish pub$/ not /irish pub/

**Comment by andrewpmk** [comment]
![image](https://user-images.githubusercontent.com/10249827/149608425-d1b17b26-4a6e-41b9-84a0-3264cb25a029.png)
Here's a better example this example "Dublin's Best Irish Pub" should NOT match the previous one "Irish Pub" should match

**Comment by JesseWeinstein** [comment]
I've traced all the (very few) other excluded lines that don't have a `^` or `$` here: https://github.com/osmlab/name-suggestion-index/issues/6098
