### ISSUE TITLE
Minor change about Gendarmerie nationale

### ISSUE THREAD

**Issue by gendy54** [osmlab/name-suggestion-index#6070]
Hi,

During a quality control, I discovered that the wikipedia tag linked to the english page instead french page. This is not the case for the other police structures.

https://github.com/osmlab/name-suggestion-index/blob/6145838009f912a5a404e42e624674853f30fc7f/data/operators/amenity/police.json#L466-L474

**Actually:**

{
      "displayName": "Gendarmerie nationale (France)",
      "id": "gendarmerienationale-714d2d",
      "locationSet": {"include": ["fr"]},
      "tags": {
        "amenity": "police",
        "operator": "Gendarmerie nationale",
        "operator:wikidata": "Q1422336",
        "operator:wikipedia": "en:National Gendarmerie"
      }

**Correction**

{
      "displayName": "Gendarmerie nationale (France)",
      "id": "gendarmerienationale-714d2d",
      "locationSet": {"include": ["fr"]},
      "tags": {
        "amenity": "police",
        "operator": "Gendarmerie nationalec,
        "operator:wikidata": "Q1422336",
        "operator:wikipedia": "fr:Gendarmerie nationale française"
      }

During the [project of the month](https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month/Gendarmerie_nationale), the French wikipedia page was added. This is currently adding errors to ID

Thanks

**Comment by kjonosm** [comment]
As `fr:Gendarmerie nationale française` is a redirect only, I added `fr:Gendarmerie nationale (France)` insteead.

**Comment by gendy54** [comment]
Perfect. Thanks a lot.
