### ISSUE TITLE
Add Wilco farm stores

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#6074]
OR/WA Farm store

https://www.farmstore.com/

**Comment by arch0345** [comment]
I added Wilco a few months ago:
https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=wilco

Should the name be changed to 'Wilco Farm Stores' or should this be an `official_name`?

**Comment by arch0345** [comment]
I've added it as alt_name as it seems like they've rebranded to just Wilco
