### ISSUE TITLE
name change suggestion despite preserveTags?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#6085]
[Here](https://www.openstreetmap.org/node/5579307932) I get a suggestion to also change the name of an office=association despite preserveTags being set in NSI, see screenshot.

<img width="439" alt="Bildschirmfoto 2022-01-16 um 12 16 33" src="https://user-images.githubusercontent.com/51236777/149657786-231cbaa8-f9c7-45e5-9b70-3cacbba1938a.png">

**Comment by UKChris-osm** [comment]
Also, where is the "_branch_" data coming from in this instance?

**Comment by matkoniecz** [comment]
If NSI data is correct, then it would be an iD bug, right ( https://github.com/openstreetmap/iD )

**Comment by arch0345** [comment]
Yeah this is probably an iD bug

**Comment by arch0345** [comment]
> Also, where is the "_branch_" data coming from in this instance, as I don't see it under the [Arbeiter-Samariter-Bund](https://nsi.guide/index.html?t=brands&k=office&v=association#arbeitersamariterbund-496920) data?

The branch likely comes from the part of the name that doesn't include `Arbeiter-Samariter-Bund` or its matchName `asb`.

> If a "_preserveTags_" exists, shouldn't the "_name_" field be removed from the NSI data as well?

The name is only used when a new POI is added: with `preserveTags` it shouldn't suggest to change the name.

**Comment by arch0345** [comment]
I've opened an issue on the iD repo as everything looks fine in NSI and this issue can still be reproduced.

**Comment by tyrasd** [comment]
see https://github.com/openstreetmap/iD/issues/8968#issuecomment-1032608982:

> The nsi entry defines its own `preserveTags` on [line 73](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/office/association.json#L73), which doesn't include the `name` tag. This overwrites the value specified for the nsi category (defined on [line 4](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/office/association.json#L4)). The [NSI](https://github.com/osmlab/name-suggestion-index/wiki/Category-Property-Reference#preserveTags) [documentation](https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#preservetags) isn't super clear if the values for  `preserveTags` should be combined in such cases or not, but since @bhousel wrote the [code of this module](https://github.com/openstreetmap/iD/blob/v2.20.4/modules/services/nsi.js#L519-L520) in iD, I would assume the way iD handles it is correct.
