### ISSUE TITLE
New amenity=parcel_locker tag to use

### ISSUE THREAD

**Issue by overflorian** [osmlab/name-suggestion-index#6093]
A new tag just has been approved: [amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker) and describes a parcel locker. [See documentation here](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker).
It replaces previously used amenity=vending_machine + vending=parcel_pickup

I propose such a replacement of tags for the following existing objects:
* https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=amazon#amazonhublocker-e80bf6
* https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=amazon#amazonhublocker-bf11a2

Once it's done, I will create the NSI objects for France for the brands "Amazon", "La Poste" and "FNAC" which are the most widely used in the country.
Thanks

**Comment by bhousel** [comment]
yes, this is #6026 
I was sort of waiting for an id-tagging-schema release that includes the new tag, just so things look more correct in the iD editor when people use these presets, but I guess we don't really have to wait for that.

**Comment by overflorian** [comment]
Thanks, sorry for the duplicate. I did comment on the other issue directly.
