### ISSUE TITLE
Please Add Rosati's Pizza

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#6094]
https://en.wikipedia.org/wiki/Rosati%27s_Authentic_Chicago_Pizza

**Comment by arch0345** [comment]
Would you consider this to be `amenity/fast_food` or `amenity/restaurant`? Rosati's is currently inconsistently tagged as one of these two

**Comment by Zol87** [comment]
Fast Food for Both. Rosati's is takeout only.
