### ISSUE TITLE
USPS amenity=post_box should not be tagged with short_name=USPS

### ISSUE THREAD

**Issue by pkoby** [osmlab/name-suggestion-index#6140]
I noticed that a lot of USPS post boxes have been upgraded using this database (probably through iD) to use `operator` tags, but also `short_name=USPS`. Osmose has flagged these as erroneous because they have a `short_name` without a `name`.

Can this be changed to tag with `operator:short=USPS` instead? See https://wiki.openstreetmap.org/wiki/Key:operator#Further_Details.

**Comment by UKChris-osm** [comment]
Thanks for letting us know @pkoby - all done 👍

**Comment by Adamant36** [comment]
Whoever came up with that tag really should have gone with `operator:short_name` since `Operator:short ` is nonsensical.

**Comment by bhousel** [comment]
Looks like this was done already.
