### ISSUE TITLE
Brands presets are getting too large

### ISSUE THREAD

**Issue by westnordost** [osmlab/name-suggestion-index#6146]
The `presets.json` in the distribution is quickly getting too large. Just this year, it doubled in size compared to beginning of 2021.

I noticed some "out of memory" issues now just parsing this file on old Android devices (StreetComplete uses the presets.json from name-suggestion-index). At the rate this file is growing, it may soon become not worthwile to include it at all.

I can think of the following solutions:
1. change the format in which those are distributed to for example a sqlite table. After all, this is structured data and not a free-form object graph. Though, at the rate this index is growing, it may only result in a temporary reduction. Also, this will not reduce the size it has in memory
2. Split it into several files. One large file that includes international presets and then for each country additional presets that are to be found in that country (only). Though, I have no overview how much that would really reduce this main/international preset file. Maybe many brands actually only available in one/few countries are not marked as such (yet). Maybe it would be worth it to write a script that looks for that by searching through taginfo/planet.
3. Include counts/popularity field for each preset so that an automatic build process (of StreetComplete) could take only the X most popular brands

**Comment by bhousel** [comment]
yeah this is #6066

**Comment by westnordost** [comment]
Ok, I'll add my text to that issue and close this one
