### ISSUE TITLE
Please transfer Norwegian charging stations to brand section

### ISSUE THREAD

**Issue by NKAmapper** [osmlab/name-suggestion-index#6147]
Please remove the Norwegian charging stations from the operator section. We tag them with brand in Norway. They are large sites with clear branding. Please also exclude Tesla Superchargers for Norway - they are also tagged with brand.

Most of the listed entries for Norway are neither operators nor brands. Not sure why they are there. The charging station brands which are recognized in Norway are: **Tesla**, **Mer** (former Grønn kontakt, now rebranded), **Recharge** (former Fortum, now rebranded), **Ionity** and **Eviny** (former BKK, now being rebranded). The other ones should be deleted from the list.

Also, we assign names to each station, for example "Tesla Larvik Supercharger", "Mer Arendal" etc.

**Comment by arch0345** [comment]
I've moved all charging stations to the brands section. The whole charging station category preserves existing names in OSM, so I've left the names for those entries.
