### ISSUE TITLE
Charging station improvements

### ISSUE THREAD

**Issue by NKAmapper** [osmlab/name-suggestion-index#6160]
Thank you for the nice cleanup for charging stations in #6147 for Norway. Just a couple of final adjustments:

1. In the brand folder for charging stations, please remove all the three lines with **operator** tags for all the charging stations. We handle them as **brands**, not operators, and there is a lot of duplication now. We use the **operator** tag specifically for the cases where a different local company is the operator for a charging station of one of these brands, in the same way as the **operator** tag is used elsewhere in OSM. The operator name is usually not visible to the end consumer, but it needs to be different from **brand** when used.
2. We do not consider Tesla Destination Charger as a brand. It is not branded as such, at least not in Norway. It is a product made by Tesla to allow hotels and other establishments to offer charging to Tesla car owners. So it think it should be removed from the index, at least for Norway. Proper tagging for Tesla destination chargers is already done through the **socket** tag.
3. The brand (in Norway) is **Tesla**, not Tesla Supercharger. Only Tesla is displayed on the brand signs for the charging stations. We use "Tesla <place> Supercharger" in the the name of each location though, to separate from Tesla the car dealer. Also, please use just "Tesla" in the brand tag, not "Tesla, Inc.", because that company incorporation is not correct in a number of countries.
4. Please delete the following entries from the operator folder:
- BKK Nett AS for Hordaland fylkeskommune - BKK has been merged into Eviny (in the brand folder).
- Charge 365 - It is a brand, move to brand folder (with brand tag, not operator)
- EB Elbil AS - It is just an office with chargers outside
- EuroPark AS - It is not a charging station brand
- Ishavsveien - It is a brand, move to brand folder (with brand tag, not operator)
- Jernbaneverket - It is a company with private chargers
- Oppegård kommune - It is not a charging company, it is a municipality, and they do not operate anything themselves
- Oslo kommune - Ditto
- Stavanger kommune - Ditto
- Trondheim kommune, Miljøetaten - Ditto
- Ringeriks-kraft - It has been merged into a new company, Kople, which belongs to the brand folder (without operator tag).
- Sunnfjord energi - It has been merged into Eviny (in the brand folder).

Note (for iD?): Charging station brands generally only caters for output from 22kW an up and the corresponding sockets (type2_combo, tesla_supercharger, chademo), so it probably is safe to only trigger a tagging recommendation if these conditions are true, otherwise a lot of private chargers could get recommendations for brand or operator. This is perhaps why some of the strange entries above got into this list.

**Comment by arch0345** [comment]
Thanks for finding all of these issues! I've fixed some of these, but I have questions about the following:

> EB Elbil AS - It is just an office with chargers outside

It [looks like](https://overpass-turbo.eu/?w=%22operator%22%3D%22EB+Elbil+AS%22+global&R) they're in more than one location?

> EuroPark AS - It is not a charging station brand

What brand should this get matched to then, if any?

> Jernbaneverket - It is a company with private chargers

It looks like [a majority of these](https://overpass-turbo.eu/s/1fMO) are tagged with `access=yes`. Should I add `access=private` to this entry?

> Oppegård kommune - It is not a charging company, it is a municipality, and they do not operate anything themselves
Oslo kommune - Ditto
Stavanger kommune - Ditto
Trondheim kommune, Miljøetaten - Ditto

What brand/operator should these get matched to then, if any?
