### ISSUE TITLE
Edinburgh Woollen Mill

### ISSUE THREAD

**Issue by SK53** [osmlab/name-suggestion-index#6162]
The stores appear to be named "The Edinburgh Woollen Mill" on the fascia, not plain "Edinburgh Woollen MIll".  Will try & find a photo to confirm.

**Comment by trigpoint** [comment]
Definitely "The Edinburgh Woollen Mill", photo attached

![DSC_0010_1](https://user-images.githubusercontent.com/8437076/152532076-8a9a6f76-b4cd-4561-8aec-bd0ab0bb178a.JPG)
