### ISSUE TITLE
Do all Amazon Hub lockers have a drop-off option?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#6166]
According to their [German website](https://www.amazon.de/ulp/view), Amazon Hub counters and lockers only offer a pick-up service (no mail-in / drop-off option). I don't know the situation in other countries outside the US...

**Comment by arch0345** [comment]
I've added a separate entry for Germany for now, but I'll leave this issue open to see if this is the case for other countries. I'm not even sure if all Amazon parcel lockers in the US have a drop-off option, but then again I haven't used one in a while.
