### ISSUE TITLE
Add Packeta to list of parcel locker brands

### ISSUE THREAD

**Issue by aceman444** [osmlab/name-suggestion-index#6171]
Hi, the Packeta brand of parcel_lockers is missing on https://nsi.guide/index.html?t=brands&k=amenity&v=parcel_locker&tt=parcel_locker .
See https://www.packeta.sk/pobocky
They even use OSM as underlying map, albeit without attribution.

**Comment by aceman444** [comment]
Thanks. But their lockers are called Z-Box so name=Packeta does not look correct. brand=Packeta seems OK. Also the operator can vary, e.g. the company seems to be "Packeta Slovakia" in Slovakia but may be different in other countries. So omitting operator from your list seems OK.

**Comment by arch0345** [comment]
I've changed the name to `Z-Box` in https://github.com/osmlab/name-suggestion-index/commit/226b315738f8a19805ed1a875e36129e360efc41 and preserved the name so that iD won't suggest to change the name of existing parcel lockers.

**Comment by aceman444** [comment]
Thanks. This data will be used by iD editor?

**Comment by arch0345** [comment]
> Thanks. This data will be used by iD editor?

Yes, the iD preset will show up in the next release of NSI. I usually do a new release every Monday.

**Comment by aceman444** [comment]
Nice, thanks.
