### ISSUE TITLE
Add suggestion for searches for "music venue" and "concert hall"

### ISSUE THREAD

**Issue by AndyCarnevale** [osmlab/name-suggestion-index#6173]
`amenity=theatre` is the most popular way to tag music venues: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtheatre

There is a proposal to add a tag for music venues, but the wiki shows the most popular way to tag a music venue is still `amenity=theatre`
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmusic_venue

Common synonyms for music venue / concert hall / etc. should point to `amenity=theatre`

**Comment by arch0345** [comment]
I'm guessing you're referring to iD (the browser editor): if this is the case [_openstreetmap/id-tagging-schema_](https://github.com/openstreetmap/id-tagging-schema) would be the appropriate place for this issue. This repo only manages the presets for common brands/operators like McDonald's, hope this helps
