### ISSUE TITLE
Addition Thought: amenity/swim_school

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#6206]
I've been scouting out Google Maps & other services, noticing the rise of Swim School chains. As we have since added Music Schools as a suitable category for future expansion, I suggest we do the same for Swim Schools.

**Comment by arch0345** [comment]
While this is a good suggestion, there are currently no features tagged as [`amenity=swim_school`](https://taginfo.openstreetmap.org/tags/amenity=swim_school). Most swim schools are currently tagged as `leisure=sports_centre` + `sport=swimming` such as [here](https://www.openstreetmap.org/way/674760191). I can see how this tagging scheme can be generic so if you're interested in getting this tag to be used in OSM I recommend creating a [proposal](https://wiki.openstreetmap.org/wiki/Proposal_process) on the wiki to get some feedback from the community.
