### ISSUE TITLE
Holey Moley bars with mini-golf 

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6213]
Holey Moley is a chain of bars with mini-golf https://www.holeymoley.com.au/

What would be the best way to tag these? Looking at the ones already mapped they use both `leisure=miniature_golf` and `amenity=bar`

**Comment by peternewman** [comment]
See also e.g. https://www.puttshack.com/
https://www.openstreetmap.org/node/9522414836

Which is just `leisure=miniature_golf`. I thought one feature one object means we should pick the main one. People don't go there for drinks only, so it should just be mini golf.

Maybe the drinks key should be added instead:
https://wiki.openstreetmap.org/wiki/Key:drink

**Comment by peternewman** [comment]
> Happy to add some `drink` and the `food` tag as the locations do serve both - https://www.holeymoley.com.au/about/bar-food - 
> however @bhousel I remember you saying the `drink` tag is not well established?

Yeah I didn't realise quite how limited usage drink was. I'm not quite clear if the bar should be tagged separately, but if not, it feels justified to me to differentiate from all the crazy golf courses which don't serve food and drink.

**Comment by peternewman** [comment]
You didn't add drink then?

I guess I should add Puttshack now...

**Comment by codeinabox** [comment]
> You didn't add drink then?
> 
> I guess I should add Puttshack now...

I considered it but their online drink menu only focussed on cocktails and I couldn't find a drink key for it

**Comment by codeinabox** [comment]
On reflection I wonder if it would be better to tag these like I did with Flight Club #6690 where it is a bar and you add the `sport` tag - would this be an improvement? The wiki for [sports=darts](https://wiki.openstreetmap.org/wiki/Tag:sport%3Ddarts) says it can be used with `amenity=bar` so I don't see why miniature golf can't be either. After all Holey Moley is bars that offer miniature golf rather than miniature golf pitch with a bar.


```json
      "tags": {
        "amenity": "bar",
        "brand": "Holey Moley",
        "brand:wikidata": "Q85766991",
        "brand:wikipedia": "en:Holey Moley (restaurant chain)",
        "name": "Holey Moley",
        "sport": "miniature_golf",
        "food": "yes"
      }
```

**Comment by peternewman** [comment]
They mention kids parties on their website, I wouldn't expect to go to a bar for one of those (whereas Flight Club is explicitly 18+ for darts). Pretty certain there were lots of kids at Putt Shack.

Also interesting that Wikipedia lists it as a restaurant chain!

I've not been inside one, but what's the reasoning for?:

> After all Holey Moley is bars that offer miniature golf rather than miniature golf pitch with a bar.

Their website lists the golf before the bar. Is some of it also the distinction between a pool/snooker hall (which has somewhere to get a drink), versus a pub/bar with one or two snooker/pool tables?

We ought to do matchTags both ways to cover people who think the opposite anyway!

**Comment by codeinabox** [comment]
> I've not been inside one, but what's the reasoning for?:
> 
> > After all Holey Moley is bars that offer miniature golf rather than miniature golf pitch with a bar.
> 
> Their website lists the golf before the bar. Is some of it also the distinction between a pool/snooker hall (which has somewhere to get a drink), versus a pub/bar with one or two snooker/pool tables?

Good question, I've only been to one Holey Moley venue in Newtown, Australia and it used to a pub but now they've installed a miniature golf course inside it. Similarly Shoreditch Balls in London was previously a bar but now has miniature golf inside it.

So my question is would a bar with the primary attraction of miniature golf inside it be tagged differently to an outdoor miniature golf course that also serves alcoholic drinks?

**Comment by jleedev** [comment]
For TopGolf (https://github.com/osmlab/name-suggestion-index/issues/5678) we used `leisure=sports_centre`. That can communicate that it's more than your typical leisure=miniature_golf` but that's still the primary feature.

**Comment by codeinabox** [comment]
I am going to keep Holey Moley tagged as `leisure=miniature_golf`with an added `bar=yes` as they advertise themself as a "mini golf course and bar " #6969
