### ISSUE TITLE
Duplicated suggestion for Fire & Rescue New South Wales 

### ISSUE THREAD

**Issue by Fizzie41** [osmlab/name-suggestion-index#6214]
If you mouse over an older entry for Fire & Rescue Stations in New South Wales (Australia) you get two auto-update suggestions, one for "Fire & Rescue NSW" then a second for "Fire & Rescue New South Wales", which won't then update, I'm guessing because it has the same wikidata?

e.g. https://www.openstreetmap.org/way/727448093

![image](https://user-images.githubusercontent.com/35707521/155034206-c6ba22b0-ec2d-458b-b9ad-cd593d54133c.png)

Not sure which one should be kept though, as their website shows the official name as New South Wales, but they refer to themselves as NSW:
https://www.fire.nsw.gov.au/

**Comment by arch0345** [comment]
That's strange, [nsi.guide](https://nsi.guide/index.html?t=operators&k=amenity&v=fire_station&tt=new%20south%20wales) is only showing `Fire and Rescue NSW`. Would you be able to screenshot the two suggestions you're seeing?

**Comment by Fizzie41** [comment]
Still looking for a Fire & Rescue example, but heres a similar thing for NSW Rural Fire Service.

Currently mapped at https://www.openstreetmap.org/way/761385756 with operator=NSW Rural Fire Service

When you go over it in edit mode: https://www.openstreetmap.org/edit?way=761385756#map=19/-34.37028/150.54382 it suggests an upgrade to operator=en:New South Wales Rural Fire Service

(I haven't changed it so you can still check it if you need to)

[NSW RFS.docx](https://github.com/osmlab/name-suggestion-index/files/8145774/NSW.RFS.docx)

**Comment by Fizzie41** [comment]
& here's the other one!

https://www.openstreetmap.org/way/761385616 has operator=Fire and Rescue NSW with wikidata code Q5451352. 

It suggests an upgrade to operator:wikipedia=en:Fire and Rescue New South Wales
https://www.openstreetmap.org/edit?way=761385616#map=19/-34.47769/150.42011

[F&R New South Wales.docx](https://github.com/osmlab/name-suggestion-index/files/8145804/F.R.New.South.Wales.docx)

Hope that helps?

**Comment by arch0345** [comment]
We have a script that adds Wikipedia articles of the brand/operator linked on the respective Wikidata item, in this case [`Q7011777`](https://www.wikidata.org/wiki/Q7011777), with a `:wikipedia` tag. There have been talks in the past about removing `:wikipedia` tags in NSI altogether to prevent foreign language articles from being added like in https://github.com/osmlab/name-suggestion-index/issues/5790#issuecomment-987556773

**Comment by arch0345** [comment]
The `:wikipedia` tags have been removed from the index in #6481
