### ISSUE TITLE
Flag of South Vietnam preferred over flag of Vietnam

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#6223]
[This node](https://www.openstreetmap.org/node/6550416577) was tagged `man_made=flagpole` `flag:type=national` `country=VN`, which triggered the feature for the [flag of South Vietnam](https://github.com/osmlab/name-suggestion-index/blob/763b887e7b8262cf4c05401231434a677043bd61/data/flags/man_made/flagpole.json#L5254-L5268) in iD. If you choose “[not this flag of South Vietnam](https://www.openstreetmap.org/node/9365035799)”, you get a suggestion for the [flag of Vietnam](https://github.com/osmlab/name-suggestion-index/blob/763b887e7b8262cf4c05401231434a677043bd61/data/flags/man_made/flagpole.json#L5269-L5282). (Both are correctly tagged `country=VN` because the ISO&nbsp;3166 code got repurposed.)

It’s kind of cool that the validator is capable of presenting a series of suggestions like this, but the internationally diplomatically recognized flag is a more appropriate default for this feature than a largely historical flag, even if it is commonplace in some regions. This is particularly true in Vietnam, where flying the South Vietnamese flag is probably against the law. A location set excluding Vietnam would be appropriate for that feature.

**Comment by bhousel** [comment]
Yeah, I can see why it would do this, but I kind of think only one of these entries in NSI should have a `country` tag 😕

**Comment by 1ec5** [comment]
> Yeah, I can see why it would do this, but I kind of think only one of these entries in NSI should have a `country` tag 😕

So far, the South Vietnamese flag has always been tagged `flag:type=national`, which would typically go along with `country`. ISO&nbsp;3166 codes usually aren’t repurposed like this, but that’s how history played out. Historical versions of the UK and U.S. flags have also been tagged with `country`; not sure if that causes a similar problem.

If we decide instead to tag the South Vietnamese flag as `flag:type=cultural`, `political`, or `historical`, then `country` could probably be omitted without any problem. But the same flag is used for any of these purposes depending on the context: one flying outside a church is cultural but not political; one flying outside a certain NGO may be political but not cultural or historical. It’s less complicated to just tag it as a national flag.
