### ISSUE TITLE
Duplicate entry in data/transit/route/bus.json for Q2516468

### ISSUE THREAD

**Issue by noah-ja** [osmlab/name-suggestion-index#6234]
I found a duplicate wikidata tag in data/transit/route/bus.json: Q2516468 can be found twice with different network tags. This leads to problems in iD. I don't quite know which to delete, but the tags for Q2516468 should be:

`"network": "Verkehrsverbund Mittelthüringen",`
`"network:short": "VMT",`
`"network:wikidata": "Q2516468",`
`"network:wikipedia": "de:Verkehrsverbund Mittelthüringen",`
`"network:guid": "DE-TH-VMT",`
`"route": "bus"`

Whoever takes care of this may also add two guid tags to other entries:
`"network:guid": "DE-SN-VVV"` to Q2516490 and
`"network:guid": "DE-TH-VGLG"` to Q81440717

Thanks!

**Comment by arch0345** [comment]
Thanks for catching this @noah-ja!
