### ISSUE TITLE
NTT is a brand, but what should we do by region?

### ISSUE THREAD

**Issue by blendy-map** [osmlab/name-suggestion-index#6235]
Hello.
Thank you for editing "operators/amenity/telephone.json".

After editing, I suddenly thought, "Isn't NTT (nippontelegraphandtelephone-8c2f5b) a brand managed by NTT East (nippontelegraphandtelephoneeest-8c2f5b) and NTT West (nippontelegraphandtelephonewest-8c2f5b)?"

It is said that in 1999, NTT's business was reorganized into a holding company structure and the business was transferred to wholly owned subsidiaries by region (NTT East Japan, NTT West Japan).

Therefore, it is necessary to rewrite the NTT item according to "brands/amenity/telephone.json" and separate the include of NTT East and NTT West.

I'm wondering if I should use GEOJSON for each prefecture when splitting the include statement, or GEOJSON for the jurisdiction of NTT East and NTT West.

### prefecture-split pattern
```json:prefecture-split.json
    {
      "displayName": "NTT東日本",
      "id": "nippontelegraphandtelephoneeest-8c2f5b",
      "locationSet": {"include": ["jp-tokyo.json","jp-nagano.json","jp-miyagi.json"]},
      "tags": {
        "amenity": "telephone",
        "operator": "東日本電信電話株式会社",
        "operator:en": "Nippon Telegraph and Telephone Eest",
        "operator:ja": "東日本電信電話株式会社",
        "operator:short": "NTT東日本",
        "operator:wikidata": "Q11527212",
        "operator:wikipedia": "ja:東日本電信電話"
      }
    },
```
### jurisdiction-split pattern
```json:jurisdiction-split.json
    {
      "displayName": "NTT東日本",
      "id": "nippontelegraphandtelephoneeest-8c2f5b",
      "locationSet": {"include": ["jp-ntt-east.json"]},
      "tags": {
        "amenity": "telephone",
        "operator": "東日本電信電話株式会社",
        "operator:en": "Nippon Telegraph and Telephone Eest",
        "operator:ja": "東日本電信電話株式会社",
        "operator:short": "NTT東日本",
        "operator:wikidata": "Q11527212",
        "operator:wikipedia": "ja:東日本電信電話"
      }
    },
```
I presented an example like this. (There is a misspelling "s/Eest/East/" in the original, but I will fix it later.)
Please let me know if there is any good way.

**Comment by arch0345** [comment]
Either option would be fine. Although creating geojsons for each prefecture would take more work, these could be used for other brands/operators in the index.

**Comment by blendy-map** [comment]
@arch0345 -san

Thank you for your reply.

For the time being, I will make it with jurisdiction-split pattern and make it a prefecture-split pattern again.
(There is a repository where you can see his GEOJSON in each prefecture on GitHub, but I wondered what it was like in terms of license)

By the way, is there any service / software that will convert the prefectural border to his GEOJSON with OSM?

**Comment by LaoshuBaby** [comment]
> convert the prefectural border to his GEOJSON with OSM?

For online tools you can see [polygons.openstreetmap.fr](https://polygons.openstreetmap.fr), need to give a specify OSM relation id.

For software you can try JOSM, download a relation and modify tag, then save as a geojson, maybe a little trouble when there need a lot of region geojson.

**Comment by blendy-map** [comment]
@LaoshuBaby -san

Thank you for telling us about [hpolygons.openstreetmap.fr](https://polygons.openstreetmap.fr/).
However, if you use the GeoJSON generated by get_geojson.py as it is, an error will occur, so let's create a slightly different script to generate GeoJSON.

**Comment by LaoshuBaby** [comment]
> let's create a slightly different script to generate GeoJSON.

Emm, maybe we can reuse other famous polygon file created by other osm project? (The license check may need other maintainer to do). What about those works? (We can use JOSM convert it to geojson)

### Organicmap's polygon file

https://github.com/organicmaps/organicmaps/tree/master/data/borders

![Screenshot 2022-03-03 at 14-43-59 organicmaps China_Hebei poly at master · organicmaps organicmaps](https://user-images.githubusercontent.com/42690037/156511249-78c31d12-4a83-42e2-9858-5df7fb028280.png)

Total 50 files.

BTW, organicmap's monorepo is too big to clone, if need, just download a single file, I think.

### OsmAnd's polygon file

OsmAnd offer 2 kinds of polygon file, [metropolis](https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/metropolis-polygons/asia/japan) and [single prefecture](https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/polygons/asia/ocean-asia/japan)

![图片](https://user-images.githubusercontent.com/42690037/156512614-7711f08d-ca1d-477f-b2e1-b9fab3c286ad.png)

![图片](https://user-images.githubusercontent.com/42690037/156512637-0821f7e5-b6fc-4d33-85f8-830d4c09a99a.png)

**Comment by blendy-map** [comment]
polygon.osmfr can be seen normally in this environment as well.

The problem is that when I npm the GeoJSON file generated by [get_geojson.py](https://polygons.openstreetmap.fr/get_geojson.py?id=1543125&params=0), I get a validation error.
```bash:console
$ npm run build:features 

> name-suggestion-index@6.0.20220228 build:features
> node scripts/build_features.js

----------------------------------------------------------------------
🧩  Build features
----------------------------------------------------------------------

🏗   Building features...
Error - Schema validation:
  features/jp/tokyo.geojson: 
  instance does not match allOf schema <http://json.schemastore.org/geojson.json#/definitions/feature> with 2 error[s]:
  instance requires property "geometry"
  instance.type is not one of enum values: Feature
```

**Comment by arch0345** [comment]
NSI [only supports](https://github.com/osmlab/name-suggestion-index/wiki/Feature-Files) a single geojson `Feature` (or a FeatureCollection containing a single `Feature`) and either `Polygon` or `MultiPolygon` geometries. I recommend drawing these by hand instead with geojson.io using the polygon tool as suggested in the wiki article linked above as we try to use as few points as possible, see https://github.com/osmlab/name-suggestion-index/issues/4784#issuecomment-742003434. It looks like other geojsons use less than 100 points.

**Comment by blendy-map** [comment]
> It looks like other geojsons use less than 100 points.
Is it the number per polygon? Or is it the number per file?

I tend to ask for the accuracy of the prefectural border, so I feel that 100 points is not enough.

I read #4784.
> try not to include/exclude too many things in a locationSet
In the case of NTT East, there are 17 prefectures, and in the case of NTT West, there are the remaining 30 prefectures.
(I don't know if this is more or less.)
