### ISSUE TITLE
Add Brand: Bread Ahead bakery in London 

### ISSUE THREAD

**Issue by bazoch24** [osmlab/name-suggestion-index#6244]
Hi folks!

I would love to ask if you could add Bread Ahead bakery chain in London.

shop type: Bakery
name:Bread Ahead
brand:Bread Ahead 
brand:wikidata:Q110984949
brand:wikipedia=(https://en.wikipedia.org/wiki/Bread_Ahead)
website=https://www.breadahead.com/
country codes:uk

Thanks!

**Comment by LaoshuBaby** [comment]
Hello, I've add it in https://github.com/osmlab/name-suggestion-index/commit/30c2242aa891486a26af86dc4f5dc8349e5b8eb7

https://github.com/osmlab/name-suggestion-index/blob/30c2242aa891486a26af86dc4f5dc8349e5b8eb7/data/brands/shop/bakery.json#L679-L693

1. `website` means this is the website of single shop, not the brand. And we don't store `brand:website` tag, this had been discussed in #5275 , people can use wikidata to access the website.
2. I looked for the wikipedia and choose `gb-lon` region as location, if not accurate you can ask for modify.

Thank you!

**Comment by bazoch24** [comment]
Thank you buddy
________________________________
