### ISSUE TITLE
NSI should stop asking to replace actual names with `name=YMCA` (preserveTags)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#6247]
properties object needs a preserveTags property

see https://osmus.slack.com/archives/C2VJAJCS0/p1646219577188909 at US Slack

**Comment by pardthemonster** [comment]
I posted this on Slack conversation about topic, but will here too...Any benefit for YMCA now having short_name=YMCA as part of NSI?
