### ISSUE TITLE
Add Tiger Sugar

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6270]
International chain of bubble tea cafes:
https://en.tigersugar.com/

**Comment by assanges** [comment]
That would be [Q76099070](https://www.wikidata.org/wiki/Q76099070). Cheers!

**Comment by arch0345** [comment]
Thanks for finding this @assanges!

**Comment by assanges** [comment]
No problemo mate!
![](https://c.tenor.com/UO7JAFOUkJwAAAAC/terminator-arnold-schwarzenegger.gif)
