### ISSUE TITLE
Brazil Brands

### ISSUE THREAD

**Issue by Playzinho** [osmlab/name-suggestion-index#6277]
name=Hering
shop=clothes
wikidata=Q5119055
wikipedia=pt:Companhia Hering

**Comment by Playzinho** [comment]
name=Zeiss
shop=optician
wikidata=Q282186
wikipedia=en:Carl Zeiss AG

**Comment by Playzinho** [comment]
name=Brooksfield
shop=clothes
wikidata=Q3645372
wikipedia=it:Brooksfield

**Comment by Playzinho** [comment]
name=Colombo
shop=clothes
wikidata=Q10319581

**Comment by Playzinho** [comment]
name=Ibyte
shop=electronics
wikidata=Q111108566

**Comment by Playzinho** [comment]
name=Lupo
shop=clothes
clothes=underwear;sports
wikidata=Q48855225
wikipedia=pt:Lupo (empresa)

**Comment by Playzinho** [comment]
name=Igreja Universal do Reino de Deus
amenity=place_of_worship
religion=christian
denomination=pentecostal
wikidata=Q958306
wikipedia=pt:Igreja Universal do Reino de Deus

**Comment by m-hue** [comment]
Hi @[Playzinho],

Most of these have been added.
Could you double check colombo please.  Looking at https://www.colombo.com.br/ it seems that they sell pretty much everything...bikes, fridges, furniture, kitchenware, pet food, .... is this really just shop=clothes, or would shop=department_store be a better fit? I left this one open for now.

Regarding Igreja Universal do Reino de Deus, it doesn't appear that we've maintained places of worship in the NSI so far. Neither the brand nor the operator subtrees feel like a 100% fit, so I left that one open for now also. Maybe someone else has an idea where to put it.

Thanks!

**Comment by Playzinho** [comment]
Hi @m-hue ,

I got confuse with Colombo, the correct Colombo wikidata is Q18469053 to Colombo Shop=Clothes and  Lojas Colombo is shop=departament store wikidata=Q10319581

thanks for add!!

**Comment by m-hue** [comment]
Thanks for clarifying @Playzinho. Both the department store and the clothing store have been added as well.

**Comment by michaelblyons** [comment]
Anything left to do here?

**Comment by bhousel** [comment]
I'll close it, I think they've all been added except for the place_of_worship, which we dont track (yet).
