### ISSUE TITLE
Ressourcerie (under shop=second_hand) truly a brand?

### ISSUE THREAD

**Issue by m-hue** [osmlab/name-suggestion-index#6278]
Hello,

Does the Ressourcerie entry we have under shop=second_hand (ressourcerie-c55c73) truly represent a brand? Based on my research this appears may be a generic term describing a second hand/thrift shop, but it doesn't appear to be a brand really. More like unrelated, individual stores using the same name.

Summoning @bmillemathias and @pyrog since you're both on the local experts list for France and the only instances I was able to find are located in France.

Thanks!

**Comment by bhousel** [comment]
I agree it doesn't look like a brand.. I've added it to the generic word list for the `shop/second_hand` category.
