### ISSUE TITLE
Research needed for: amenity/pharmacy|Dbam o Zdrowie

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#628]
#### :thinking: We need help deciding what to do with "amenity/pharmacy|Dbam o Zdrowie"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/pharmacy|Dbam o Zdrowie` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/pharmacy|Dbam o Zdrowie`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/pharmacy|Dbam o Zdrowie`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
Appears to be an existing brand without a wikipedia page.

**Comment by bhousel** [comment]
Hey @1ec5 or @nyurik  -  if we come across regional brands without a wikipedia or wikidata page, is there a good way to surface these for someone to add for us?  I think Minh mentioned a data pump? 

We could tag them in this repo so they are easy to find..

**Comment by 1ec5** [comment]
> I think Minh mentioned a data pump?

I was referring to [Wikidata’s village pump](https://www.wikidata.org/wiki/Wikidata:Project_chat) as a place to give the community a heads-up about imports.

Let’s start a page in the Wikidata: namespace of Wikidata, then propose it to the Wikidata community as a checklist. Even better, we can go ahead and add Wikidata entities for each of these missing brands, list them on a page in the Wikidata:  namespace, and ask the community to vet the list for possible duplicates of existing entities (which can be merged).

**Comment by nyurik** [comment]
I wonder if we could somehow generate a list of brands using a query, making sure there is no related items in wikidata...?  How do you come up with a list in the first place?

**Comment by matkoniecz** [comment]
> I wonder if we could somehow generate a list of brands using a query

It is unclear what you want here. This project generated list of popular brands based on OSM data and now we are reviewing it.

**Comment by nyurik** [comment]
@matkoniecz I was replying to @bhousel 's  _"is there a good way to surface these for someone to add for us"_.  I didn't notice that this issue was centered around a single brand.  So if there is a well know list of missing brands, it should be relatively easy to add them by hand to Wikidata. If we want to set up a process on adding them in an ongoing basis, we would need a good way to spot them, e.g. with a query.

**Comment by bhousel** [comment]
> So if there is a well know list of missing brands, it should be relatively easy to add them by hand to Wikidata. If we want to set up a process on adding them in an ongoing basis, we would need a good way to spot them, e.g. with a query.

Oh, I think this was just the first brand we came across that was not in Wikidata.. 

There are not very many, so I think an automated process would be overkill.  For now we've been adding the "needs wikidata" label, and anyone who feels comfortable editing Wikidata can add them.
