### ISSUE TITLE
Pôle emploi

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/name-suggestion-index#6298]
Hi,

the french administration taking care of the unemployed people has the name "Pôle emploi".

ID wants to change the brand:wikipedia=fr:Pôle emploi by the page in english. The main page is of course the page in french, not in english.

Could you fix that ?

Best regards

**Comment by UKChris-osm** [comment]
Sorry about that @Mahabarata - I have just updated the core data, which should filter through to iD in a few days hopefully.
