### ISSUE TITLE
Recolight light bulb recycling containers

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6367]
I've stumbled upon a few Recolight light bulb recycling containers around London though I am not sure whether to treat them as the brand, operator or both? The recycling containers clearly have their logo on them ie https://www.recolight.co.uk/map/

**Comment by codeinabox** [comment]
@peternewman @UKChris-osm keen to hear your thoughts on this

**Comment by peternewman** [comment]
From their website it sort of sounds like they might do both. If they're labelled as them then they must be the brand surely. I guess it might be hard to tell if they're actually the operator (see e.g. Santander Cycles and Serco or whoever currently moves them around).
