### ISSUE TITLE
Add Batopin the new operator of Belgian ATM's

### ISSUE THREAD

**Issue by JoeyKentin** [osmlab/name-suggestion-index#6403]
amenity=atm
brand=Batopin
brand:wikidata=Q97142699
brand:wikipedia=nl:Batopin
operator:wikidata=Q97142699
operator:wikipedia=nl:Batopin
operator=Batopin
name=Batopin

**Comment by thibaultmol** [comment]
@JoeyKentin technically while the company that manages the atm's is called Batopin. Their branding for those locations doesn't mention Batopin, they're branded as 'CASH' points https://www.batopin.be/nl/onze-cash-punten
So maybe something needs to change here?

**Comment by JoeyKentin** [comment]
@thibaultmol I think you are right we should fix that asap

**Comment by JoeyKentin** [comment]
Yeah I think so but then someone should make a new Wikidata as it doesn't exist at the moment

**Comment by thibaultmol** [comment]
I've created it
https://www.wikidata.org/wiki/Q112875867
But they don't have social media accounts, so can't get the logo from there.
Can the NSI guide also take an image from the wikidata if it were to be uploaded to Wikimedia Commons?

**Comment by JoeyKentin** [comment]
I don't know if they can take ik from Wikimedia Commons

**Comment by thibaultmol** [comment]
@LaoshuBaby what do you suggest we do?
