### ISSUE TITLE
ICBC in Japan should be tagged with Japanese instead of English.

### ISSUE THREAD

**Issue by Jyunhou** [osmlab/name-suggestion-index#6410]
![image](https://user-images.githubusercontent.com/45530478/161410650-c87d03bf-ac84-426a-970f-f307063a6e13.png)
Japanese:中国工商銀行
English:ICBC

**Comment by LaoshuBaby** [comment]
Thank for this reply, we will create new entry in Japan for those oversea China bank brand.
