### ISSUE TITLE
Need for fire stations to be added to emergency

### ISSUE THREAD

**Issue by EOEboh** [osmlab/name-suggestion-index#6414]
We need a separate JSON file for every fire station. Actually, not every country have the privilege of calling an emergency number like 911 before getting help from firefighters, ambulance or even the police. 
Hence, if we can list these stations on the index and map, it would solve that dearth.

**Comment by bhousel** [comment]
The fire station operators that we've collected and tagged are in this file:
https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/amenity/fire_station.json

**Comment by EOEboh** [comment]
> The fire station operators that we've collected and tagged are in this file: https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/amenity/fire_station.json

Okay, my bad then. Thank you.
