### ISSUE TITLE
"Métropole Nice Côte d'Azur / Veloway by Transdev" instead of "Véolia"

### ISSUE THREAD

**Issue by V75014** [osmlab/name-suggestion-index#6417]
Hello,

I am a new contributor for GitHub.

I would like change operator for Vélo Bleu in Nice (France)

https://github.com/osmlab/name-suggestion-index/blob/86dd7001b46ac3ef900d698addccdb0c4260f7d3/data/brands/amenity/bicycle_rental.json#L3677

The **new operator** is "**Métropole Nice Côte d'Azur / Veloway by Transdev**".

You can see https://www.velobleu.org/mentions-legales/

Thanks
Vincent / V75014

![Vélo Bleu - Mentions légales](https://user-images.githubusercontent.com/101467176/161628818-d705a9ab-8e69-4f3c-a579-8705eb9a32de.jpg)

**Comment by bmillemathias** [comment]
I'm seeing the change has [landed](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bicycle_rental.json#L3456)

Could this issue be closed or is there something remaining to do ?

**Comment by bhousel** [comment]
looks closed to me! 👍
