### ISSUE TITLE
Add pizza/arcade chains

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6442]
- [ ] [John's Incredible Pizza Company](https://en.wikipedia.org/wiki/John%27s_Incredible_Pizza_Company)
- [ ] [America's Incredible Pizza Company](https://en.wikipedia.org/wiki/America%27s_Incredible_Pizza_Company)
- [ ] [Pietro's Pizza](https://en.wikipedia.org/wiki/Pietro's_Pizza)

**Comment by Adamant36** [comment]
@arch0345 I created a new issue for John's Incredible Pizza Company. The other two have an extremely small number of locations, especially Pietro's Pizza. So I don't think they are worth adding.
