### ISSUE TITLE
processEntities expects outdated response format from Wikidata API

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#6456]
Wikidata recently deployed a change to its [API response format](https://lists.wikimedia.org/hyperkitty/list/wikidata-tech@lists.wikimedia.org/thread/3LA6FDOZGSK6HSQY73XCFNT4BTYWOY64/) that may affect the `processEntities` function of the build_wikidata.js script:

https://github.com/osmlab/name-suggestion-index/blob/85015fe18b06816e65be089ede3b5534b6767215/scripts/build_wikidata.js#L274-L297

This code may also be affected by [a further proposed change to the response format](https://phabricator.wikimedia.org/T304878). I haven’t done any investigation beyond code inspection to determine the impact.

/ref https://github.com/openstreetmap/iD/issues/9067#issuecomment-1098414653

**Comment by bhousel** [comment]
I did some more investigation and it looks like this script is working correctly - the important line is before, where it actually does go down into the `labels` object and get the `en` label if there is one.

https://github.com/osmlab/name-suggestion-index/blob/9a77370e1a732bd37cae5c551709b55a7f147d88/scripts/build_wikidata.js#L264
