### ISSUE TITLE
Add this company

### ISSUE THREAD

**Issue by ishovonahmed** [osmlab/name-suggestion-index#6462]
Hi, Kindly add this company.
This company is listed by forbes.

Name : Scherzinger Holding GmbH 
Founded date : 5th of November 2021
Head quarter : Frankfurt am Main, Germany 
Website : Scherzingerholding.com
Founder name : Patrick Scherzinger 
Wikidata : https://www.wikidata.org/wiki/Q111608267

Instagram : https://www.instagram.com/Scherzingerholding

**Comment by ishovonahmed** [comment]
Forbes : https://profiles.forbes.com/members/business/profile/Patrick-Scherzinger-Managing-Shareholder-Scherzinger-Holding-GmbH/6ac760ac-045d-4393-a341-03ccd12c48fc

https://markets.businessinsider.com/news/stocks/patrick-scherzinger-accepted-into-forbes-business-council-1031350749

**Comment by bhousel** [comment]
In #6325 you were told that  "this index is for brands that operate a lot of retail chain locations (things like fast food places like McDonalds). "

Please stop opening issues here for businesses that don't belong in our index.  It's not a general business directory.
