### ISSUE TITLE
Please add convenience - Delikatesy SLAWEX

### ISSUE THREAD

**Issue by kpv8** [osmlab/name-suggestion-index#6464]
brand=SLAWEX 
brand:wikidata=Q110801396
name=Delikatesy SLAWEX
shop=convenience

**Comment by kjonosm** [comment]
For which country or countries?

**Comment by kjonosm** [comment]
Guessing by the name, are you sure this is not a [`shop=deli`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddeli)?

**Comment by kpv8** [comment]
No it's not, it's a typical convenience store but has Deli in a name.

**Comment by kpv8** [comment]
This brand owns supermarkets and convenience stores in Polesie (It's a region in Poland)
