### ISSUE TITLE
Covirán wikipedia

### ISSUE THREAD

**Issue by carlosarc87** [osmlab/name-suggestion-index#6473]
Hi, I have checked the brand Covirán and the Wikipedia page should be in spanish and not in euskera.
The Wikipedia spanish article was created after adding the brand to the list of brands.

I hope you can fix it. 
Regards

**Comment by bhousel** [comment]
No problem, I just fixed it..
BTW these `brand:wikipedia` tags are really not that important and we are going to remove them soon.
