### ISSUE TITLE
Add The Flame Broiler brand (USA)

### ISSUE THREAD

**Issue by pyricc** [osmlab/name-suggestion-index#6478]
amenity=fast_food
brand=The Flame Broiler
brand:wikidata=Q30593122
cuisine=asian
name=The Flame Broiler

---

contact:facebook=https://twitter.com/TheFlameBroiler
contact:instagram=https://www.instagram.com/theflamebroiler/
contact:twitter=https://twitter.com/i/user/2317684488
website=https://flamebroilerusa.com/

**Comment by LaoshuBaby** [comment]
Usually we don't contain those social media contact in NSI, also the website. They are available with wikidata.

I'll add other information.
