### ISSUE TITLE
Remove the *:wikipedia tags

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#6481]
We often get feedback that tags like `brand:wikipedia` are redundant and we could probably stop adding it.   This issue is just for me to remove the `*:wikipedia` tags from the index and also from all the `build_wikidata` script that gathers them.

_Followup on comment posted by @bhousel in https://github.com/osmlab/name-suggestion-index/issues/5275#issuecomment-905798587_

**Comment by bhousel** [comment]
This is done! 
As of today's release v6.0.20220421 these tag updates won't be suggested anymore.

**Comment by Lukas458** [comment]
Okay well, thank you, but I only hope that's the consensus here that these data are kind of redundant, so noone will come up with the idea to re-add them.
