### ISSUE TITLE
Paul Smith clothes shop brand

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6485]
There are Paul Smith clothes shops all over the world but in creating an index entry for it, should a Wikidata entry be created for the brand? Paul Smith the person who started the brand already has a Wikidata entry but a person and the brand they've created are two different things right?

**Comment by bhousel** [comment]
Yes they should be split up so that the business is separate from the person.

This is pretty common on clothes/fashion places, for example:
- Calvin Klein (the person) https://www.wikidata.org/wiki/Q214800
- Calvin Klein (the business) https://www.wikidata.org/wiki/Q1068628 (what we want for NSI)

**Comment by m-hue** [comment]
Q56356277 appears to be the entry for the brand.

**Comment by codeinabox** [comment]
> Q56356277 appears to be the entry for the brand.

Thank you and well spotted!
