### ISSUE TITLE
EDP and E-REDES

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#6531]
According to the new rules for liberalizing the electricity market in the European Union, it is mandatory to separate distribution (network infrastructure) and commercialization companies. 
Since 29 January 2021, EDP Distribuição, the entity in charge of managing the electricity distribution network in mainland Portugal that belongs to the EDP group, has been renamed E-REDES. So I ask that a new E-REDES brand be created with the new logo and also update the EDP logo which was not correct.

https://www.e-redes.pt/pt-pt

Thank you
![EDP_logo](https://user-images.githubusercontent.com/54463127/166161393-ed52d6d6-e1ae-4ed7-8d39-a6fce0cebe73.svg)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/54463127/166161561-3a8b7b64-b0bf-4fdc-8fff-594dd43ae4b0.jpg)

**Comment by DiogoBaptista98** [comment]
wikidata created https://www.wikidata.org/wiki/Q111843687

**Comment by LaoshuBaby** [comment]
In current code have 3 place related to your requested E-REDES:

* https://github.com/osmlab/name-suggestion-index/blame/260cb942b4771a0dc42c65dae0536084cacaeef8/data/operators/power/substation.json#L1797-L1807
* https://github.com/osmlab/name-suggestion-index/blame/260cb942b4771a0dc42c65dae0536084cacaeef8/data/operators/office/energy_supplier.json#L11-L21
* https://github.com/osmlab/name-suggestion-index/blame/260cb942b4771a0dc42c65dae0536084cacaeef8/data/operators/power/line.json#L1553-L1563

They were created in your another issue #7543 

Can you confirm whether the above content meets the requirements of this issue? If there are no problems, I will close this issue. If there are problems, hope you can point out which category you want to create a new entry with what name or delete who. 😁
