### ISSUE TITLE
`Petrol` is not being recognized as brand

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/name-suggestion-index#6552]
When a gas station has `operator=Petrol`, iD doesn't suggest the correct brand (https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/fuel.json#L5351-L5363).
![image](https://user-images.githubusercontent.com/19364673/166923845-5912554b-802f-43c3-aca8-f439f51b3fb0.png)

When the I add `name=Petrol` it suggests to remove it since it's too generic.
![image](https://user-images.githubusercontent.com/19364673/166924068-d737b7e3-6791-4eaf-a4ac-fbf2f25b04c9.png)

Is it possible to make it match with the brand instead of triggering warnings?

**Comment by bhousel** [comment]
Problem is this line in `buildMatchIndex()`, it means that the generic name never gets indexed.  I'll have to rethink this part of the code a bit.

https://github.com/osmlab/name-suggestion-index/blob/9424e0313feaa850e0b32fc1b522995357069e19/lib/matcher.js#L209

**Comment by stefanb** [comment]
We'd have identical problem with a different "Petrol" brand based in Slovenia:
- https://www.wikidata.org/wiki/Q174824

with gas stations in several other countries (and not in Bulgaria):
- https://www.petrol.eu/gas-stations/map?lng=21.134580475616776&lat=43.3540214718437&zoom=5#
- https://location-conflation.com/?locationSet=%7B%20include%3A%20%5B%27si%27%2C%20%27hr%27%2C%20%27rs%27%2C%20%27ba%27%2C%20%27me%27%5D%20%7D&referrer=nsi

**Comment by stefanb** [comment]
The generic name "Petrol" would conflict with exclusion regex:

https://github.com/osmlab/name-suggestion-index/blob/6ee28795fd7aa8f48ff8693d92888bf86db8a2af/data/brands/amenity/fuel.json#L7

**Comment by stefanb** [comment]
Are we sure this is still the case?

In Slovenia it seems to work correctly after #7725:
![telegram-cloud-photo-size-4-5967484688878648627-y](https://user-images.githubusercontent.com/319826/215864768-d0ff4080-11be-4ce0-a912-b3abc2b1fa40.jpg)

And it creates the POI as expected: 
![telegram-cloud-photo-size-4-5967484688878648628-y](https://user-images.githubusercontent.com/319826/215865027-4fc2cb32-7221-4184-876c-879fbbd82cac.jpg)

**Comment by Dimitar5555** [comment]
@stefanb The "remove suspicious name" seems to be resolved. The problem is that the brand is not suggested when you have `name=Petrol`.

![image](https://user-images.githubusercontent.com/19364673/215878129-db0da84b-a55a-4ead-961c-c8177f26ea19.png)

**Comment by Dimitar5555** [comment]
Resolved by #8730, also works with `brand` and `operator` instead of `name`. CC: @Cj-Malone.

![image](https://github.com/osmlab/name-suggestion-index/assets/19364673/66c68484-67af-4bc8-984c-73bd95957b8f)
