### ISSUE TITLE
Baltimore City and Washington, DC scoping issues

### ISSUE THREAD

**Issue by bgo-eiu** [osmlab/name-suggestion-index#6558]
Related to #6540 in which a baltimore.geojson file was added to scope Baltimore Police Department-operated light towers to Baltimore City limits. Wanted to open a separate issue since there's some counterintuitive aspects at play for scoping both Baltimore City and District of Columbia government agencies.

Despite the fact that Baltimore and DC are independent cities that have some unique forms of autonomy within the confines of their jurisdictions, their governments both own and operate a number of facilities which are not within their respective boundaries. I was initially thinking of attempting to differentiate which agencies in particular this might applied to, but I think there are factors that complicate distinguishing the different agencies within each city. Here are a couple examples:

Baltimore City owns and operates reservoirs and natural resources quite far away from Baltimore. Liberty Reservoir is one of these, and it spans a huge area which straddles Baltimore County and Carroll County: https://en.wikipedia.org/wiki/Liberty_Reservoir
Most of what goes on there would fall under the umbrella of the Baltimore City Department of Works - there's already some of the city DPW pipeline outside of Baltimore on the map from what I know. Other agencies get involved too though and there's actually a whole police force called the Baltimore Environmental Police. This article called "Environmental police are real police" was published when Carroll County residents were confused why they were seeing Baltimore police officers operating in the area as they had been deployed following an increase in funding: https://www.baltimoresun.com/maryland/carroll/cct-arc-36d59e0b-6ae4-5889-855b-c580eafbc9ce-20140308-story.html

With Washington, DC, there are similar sorts of situations. This "Department of Youth Rehabilitation Services" facility is in Anne Arundel County, MD, which is not even one of the inner ring suburban counties of DC. https://en.wikipedia.org/wiki/Department_of_Youth_Rehabilitation_Services

The baltimore_and_dc.geojson scope is kind of drawn perfectly already for a lot of purposes as it even accounts for the fact that the Maryland Transit Administration serves Martinsburg, West Virginia, or the DC area's links to Charles County, so my suggestion would be to just use baltimore_and_dc for the scope of most things operated by the city government of either. I would say generally operations related to utilities/public works, police, and fire are the most likely to extend beyond city limits, but it's hard to say for sure which departments would be only within one city as the possibility of one of them getting involved due to a connection to an out-of-city facility is there. If Baltimore City Schools gets added, or there is something else that is very unlikely to be relevant far from the city, it should probably be confined to a buffer of Baltimore rather than the exact boundary. The boundary is not related to the street network so it crosses through a lot of buildings and can make things not fully in the boundary part of the city's jurisdiction.

(This doesn't include transit, as that's mostly not city run, and is already constrained correctly as far as I can tell. baltimore_and_dc should work for any of them for now. Some issues could come up down the line when/if there are more western MD panhandle and eastern shore operators in NSI.)

**Comment by bhousel** [comment]
Thanks for the examples - I did add the baltimore.geojson just for stuff that really should be scoped to Baltimore City only, and tried to use us-md.geojson for things in Baltimore County, and agree that we can continue to use baltimore_and_dc.geojson for stuff the extends across the entire metro area.  (see links below to the actual geojsons)

The main concern here is not so much street/parcel-level accuracy but more just scoping where the presets and validations are available in RapiD/iD so that users don't think there is a bug in our work.  

For example, showing users a preset for Baltimore Police lights in DC would be seen as a bug, but showing a preset for MTA Commuter bus stations would not.

Is there anything actionable for me to change now? 

https://github.com/osmlab/name-suggestion-index/blob/main/features/us/baltimore.geojson
https://github.com/osmlab/name-suggestion-index/blob/main/features/us/baltimore_and_dc.geojson
https://github.com/osmlab/name-suggestion-index/blob/main/features/us/US-MD.geojson

**Comment by bgo-eiu** [comment]
Alright, I see what you mean - even where they may overlap, the city's departments are going to overlap in between and not in the cities themselves.

I would say for now, the most helpful change would be to scope Baltimore City Department of Public Works in pipeline.json to us-md because those are continuously being added to the map in and outside of Baltimore. (And add the wikidata item https://wikidata.org/wiki/Q108129298)

I'll try to come up with a closer boundary for each that makes sense with respect to utilities, police etc since Maryland is quite wide and it doesn't seem great to have some of these suggestions show up in the farther reaches either. Then baltimore_and_dc could be just for transit like the MTA Commuter lines as you said, and regional brands which exist in both.

**Comment by bhousel** [comment]
> I would say for now, the most helpful change would be to scope Baltimore City Department of Public Works in pipeline.json to us-md because those are continuously being added to the map in and outside of Baltimore. (And add the wikidata item https://wikidata.org/wiki/Q108129298)

ok, I did this 👍 

> I'll try to come up with a closer boundary for each that makes sense with respect to utilities, police etc since Maryland is quite wide and it doesn't seem great to have some of these suggestions show up in the farther reaches either.

Sounds good - again it doesn't have to be perfect.. For our purposes, fewer/rougher geofences are better than a whole lot of  specific custom geojsons.   Including `us-md.geojson` is actually better than trying to draw polygons for each county or each operator.

Also for now, this index is mostly for tracking things that there are a lot of.  So while it might make sense to include all the police stations in Baltimore county, we probably woudn't do the same for Kent County.
