### ISSUE TITLE
Amazon Locker and parcel_mail_in

### ISSUE THREAD

**Issue by Mannivu** [osmlab/name-suggestion-index#6560]
As far as I know, Amazon Locker do not allow sending parcels, but users can return products they have received. Therefore, I think that the best suggestion is not `parcel_mail_in=yes`, but should be `parcel_mail_in=returns_only` (which is an allowed value [based on wiki](https://wiki.openstreetmap.org/wiki/Key:parcel_mail_in)).

**Comment by UKChris-osm** [comment]
I'd agree with this change!

**Comment by bhousel** [comment]
I guess this is #6166 also

**Comment by bhousel** [comment]
I removed the `parcel_mail_in` tag from Amazon Locker in b6385d9d4

If this is not definitely true everywhere, we can leave it to mappers to add this tag on the locker if it supports sending parcels.

**Comment by Mannivu** [comment]
Well, this is not quite the same thing. Allowing returns it's different from allowing sending
