### ISSUE TITLE
Add "Ideal Food Basket"

### ISSUE THREAD

**Issue by yoasif** [osmlab/name-suggestion-index#6561]
see https://www.idealfoodbaskets.com/

and https://www.wikidata.org/wiki/Q111908729

supermarket chain in USA.

**Comment by UKChris-osm** [comment]
Thank you for the suggestion @yoasif, this has been added via edit [34b0756](https://github.com/osmlab/name-suggestion-index/commit/34b0756d54e77e085a61fb44286d3933edcca94f)
