### ISSUE TITLE
Add Bank Syariah Indonesia (BSI)

### ISSUE THREAD

**Issue by hanifalhusaini** [osmlab/name-suggestion-index#6566]
Please add Bank Syariah Indonesia (BSI) for amenity=bank and amenity=atm in Indonesia.
Wikidata: https://www.wikidata.org/wiki/Special:EntityPage/Q105574200 
An example of this bank is https://www.openstreetmap.org/way/377299619
Official website: http://bankbsi.co.id/
This bank is a merger of three banks: BNI Syariah (Q16171018), Bank Syariah Mandiri (Q12474533, already listed in the NSI as bankmandirisyariah-aa7852) and BRI Syariah. Therefore, if there are still banks tagged with the old names, they must be changed.

**Comment by UKChris-osm** [comment]
Thank you @hanifalhusaini - I have updated this via edit [96a670d](https://github.com/osmlab/name-suggestion-index/commit/96a670d6ecfd43a4ad788cc7ddccfce245b96e3b)
