### ISSUE TITLE
Wasabi tag suggestion bug

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6573]
I recently updated the entry for Wasabi to be fast food #6549 and it appears in the NSI as such but id editor is behaving strangely and suggesting changing back to a restaurant

<img width="379" alt="Screenshot 2022-05-13 at 10 45 09" src="https://user-images.githubusercontent.com/2069958/168258127-84b4dc44-ef5b-4520-8991-fe36b10c4a88.png">

**Comment by bhousel** [comment]
Can you refresh the browser and try again?  I can't think of a reason why it would do that other than maybe a stale cached file or you've left the window open for a while?  (this shouldn't really happen, but I don't know).

If it does persist, can you let me know the osm id of the feature where it's offering this suggestion?

I just tested this and I'm seeing Wasabi as `amenity=fast_food` only.
If I do try to tag it as a `restaurant`, the validator prompts me to put it back to `fast_food`
<img width="375" alt="Screen Shot 2022-05-13 at 9 51 03 AM" src="https://user-images.githubusercontent.com/38784/168298344-6b7ad6d3-75e7-4dd9-97ad-05a29bb44a19.png">

**Comment by UKChris-osm** [comment]
It seems to come up as a fast food suggestion for me as well, so I expect you have a cashed version of the NSI file still  @codeinabox

**Comment by codeinabox** [comment]
Thank you for investigating! Clearing the cache solved the issue
