### ISSUE TITLE
the relevant ID not automatically generated when "杭州公共自行车" was added into bicycle_retal.json

### ISSUE THREAD

**Issue by ydwangd** [osmlab/name-suggestion-index#6577]

**Comment by UKChris-osm** [comment]
Hi @ydwangd - an ID will be generated the next time "_npm run build_" is used, which is a script we use here at the Name Suggestion Index to tidy things up.

**Comment by ydwangd** [comment]
ok thank you

**Comment by UKChris-osm** [comment]
@ydwangd I have just run "_npm run build_" for you, and the generated ID is "_hangzhoupublicbicycle-b6480c_".

**Comment by ydwangd** [comment]
thank you so much
