### ISSUE TITLE
IGA (Australia) name issue

### ISSUE THREAD

**Issue by Scottie0001** [osmlab/name-suggestion-index#6580]
When entering some IGA stores in Australia, it says that it should be changed to the below image:

![Screen Shot 2022-05-15 at 5 50 16 pm](https://user-images.githubusercontent.com/105581438/168462824-609ebb7d-86dd-444b-9bf7-7c63565f7480.png)

The name of the individual IGA is "IGA X-press" as shown at the front door and this example is one of many with the name not being IGA. Other examples that use the IGA brand but the name isn't IGA include:
- Supa IGA
- IGA Local Grocer
- Seasons IGA
- IGA Everfresh

**Comment by UKChris-osm** [comment]
Hi @Scottie0001 

Are the other IGA's a different type of amenity, such as a convivence store?

**Comment by Scottie0001** [comment]
Just looking at all the different types of IGA's, the only one that could be a convenience store is IGA X-press. Supa IGA, IGA Local Grocer, Seasons IGA and IGA Everfresh all can be supermarkets.

**Comment by Snowysauce** [comment]
The IGA preset no longer suggests name tag corrections as of #7578
