### ISSUE TITLE
Add cosmetology schools

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6588]
I'm guessing these should go in `amenity/training`?

- [ ] [Empire Beauty Schools](https://www.empire.edu/cosmetology-schoolss) [(Wikipedia)](https://en.wikipedia.org/wiki/Empire_Beauty_Schools)
- [ ] [Aveda Institutes](https://aveda.edu/locations/) [(Wikipedia)](https://en.wikipedia.org/wiki/Aveda)
- [ ] [Paul Mitchell Schools](https://paulmitchell.edu/locations) [(Wikipedia)](https://en.wikipedia.org/wiki/John_Paul_Mitchell_Systems)

**Comment by 1ec5** [comment]
[Related OSMUS Slack thread](https://osmus.slack.com/archives/C2VJAJCS0/p1652631537450139)
[Example Aveda Institute branch](https://www.openstreetmap.org/node/5675220171)
