### ISSUE TITLE
Update Telekom stores in Germany

### ISSUE THREAD

**Issue by AlertSubject** [osmlab/name-suggestion-index#6595]
In Germany we have shops owned and operated by the "Deutsche Telekom AG"
These shops are only for phones and related services. 
(The company also operates infrastructure, office buildings, and more. But I'm not talking about those)

The NSI-object has the following ID:                                       [telekom-82963b ](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=telekom)
and can be found and used In the following countries:          "include":["de","hu","ro","si","sk"]

**My issues are as follows:**

- The official name is "Deutsche Telekom" and not just Telekom, as NSI suggests (Also visible in [Wikidata](https://www.wikidata.org/wiki/Q9396))
- Updating NSI to reflect that might cause issues in other countries since im not sure if DT operates in those other countries
- I'm not sure if the generic Telekom.com address is a good fit because it increases the chance that a mapper wont add the proper address of the specific store to a POI ([Example](https://shopseite.telekom.de/nord-ost/hamburg/wandsbeker-marktstr-79))
- And lastly, would it be fine to add an alt_name to the NSI object? The shops itself are commonly called T-Shops.

**I suggest the following changes:**

- Change the name tag to "Telekom Shop" to avoid confusion with office buildings or service buildings operated by the same company
- Add an alt_name tag to enable people to find "T-Shop" when searching for them (name applies to all shops so it makes sense to add the alt_name for every shop)
- Remove the default website tag to motivate mappers to add a specific website instead. A generic website for a company as big and with a thousand different services they provide isn't all too helpful
- Maybe remove "de" from the "include" part of the current object and create a new one, specific to Germany. Mostly because I'm less familiar with how DT operates in other countries. My expertise is based on my work in Germany

I'd love to get some input and feedback on my thoughts before I start opening a PR
Thank you for your time and help :)

**Comment by kjonosm** [comment]
@AlertSubject 

- Changing the name tag to "Telekom Shop" looks like a good refinement, as this name is used on their website: https://www.telekom.de/start/telekom-shops
- I personally wouldn't bother adding `alt_name=T-Shop`. It might make sense though to match shops named "T-Shop" to "Telekom Shop" with `matchNames`. You could also match shops named just "Telekom" or "Deutsche Telekom" accordingly.
- Removing website tags is, as far as I know, out of scope for NSI.
- You want to create a new item for German stores to include all your suggestions.

**Comment by AlertSubject** [comment]
@kjonosm

Thanks for your input

In conclusion

- I'll update the current object to feature the correct name
- remove "de" from the current object
- create a new preset only for Germany and then implement my suggestion as above

If there is no rule against it then I'd like to add the alt name to the German object regardless because of how widely used it is. And therefore it improves the user experience of finding those shops. 
I'll use the match name stuff as well (at least in the German preset)

Is that alright?

**Comment by AlertSubject** [comment]
merged into main
