### ISSUE TITLE
Should we add Travel Plazas?

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#6602]
I mean, I believe we should make Travel Plazas a different category than just convenience stores & gas stations. Another question I should possibly add is whether should it be under brand or operator.

Various Travel Plazas Include: 

- Flying J Travel Plazas
- Love's Travel Stops
- Onvo Travel Plazas
- PETRO
- Pilot Travel Centers
- Road Ranger
- Roady's Truck Stops
- TA
- Town Pump

**Comment by 1ec5** [comment]
In the U.S., these are typically tagged as [`highway=services`](https://www.openstreetmap.org/way/226295914), [`tourism=caravan_site` `landuse=retail`](https://www.openstreetmap.org/way/226933681), or [`amenity=truck_stop` `landuse=retail`](https://www.openstreetmap.org/way/220277564). Some of these tags were part of concerted mapping campaigns. `highway=services` sounds like the most correct option.

**Comment by 1ec5** [comment]
> Another question I should possibly add is whether should it be under brand or operator.

These are brands. There would be a branded `highway=services` area containing branded gas stations, convenience stores, and car washes. I guess they could also be operators for tagging the parking lots, but then lots of brands could also be operators of parking lots.
