### ISSUE TITLE
DTLR in Shoes and Clothes might be the same brand

### ISSUE THREAD

**Issue by brierjon** [osmlab/name-suggestion-index#6616]
dtlr-c5ede1
dtlr-0a21d9
https://locations.dtlr.com/ sells both short and shoes

**Comment by Snowysauce** [comment]
Marking this as resolved - DTLR has since been consolidated into one entry under `shop/clothes`, and the automatic tag matcher will suggest retagging any instances of DTLR with `shop/shoes` as `shop/clothes`.
