### ISSUE TITLE
Add Wikidata to Park District of Oak Park

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#6642]
[ Park District of Oak Park (Q112220982) ](https://www.wikidata.org/wiki/Q112220982)

**Comment by LaoshuBaby** [comment]
Hey, @Zol87 

https://github.com/osmlab/name-suggestion-index/blob/30e66729bd136d68ea70fd0643bd234e163aeee7/data/operators/leisure/park.json#L4028-L4041

Wikidata of PDOP was already added 22 hours ago in https://github.com/osmlab/name-suggestion-index/commit/30e66729bd136d68ea70fd0643bd234e163aeee7

Thank you for finding this.
