### ISSUE TITLE
Change "NORMA" back to "Norma" (shop=supermarket)

### ISSUE THREAD

**Issue by fnordiff** [osmlab/name-suggestion-index#6662]
It seems like the name/brand/displayName of "id":"norma-c1eeeb" had been changed to uppercase in [this change](https://github.com/osmlab/name-suggestion-index/commit/33904164faf229d7b4f97af2a4549c3ac94a3f34) but I don't understand why.

The typical tagging ([as of 2016](https://wiki.openstreetmap.org/wiki/Germany/Shops), without recent changes of this index) was "Norma" (1034x) vs. "NORMA" (128x). The [current tagging](https://taginfo.openstreetmap.org/keys/name#values) after 10 month with suggestion "NORMA" is still "Norma" (957x) vs. "NORMA" (632x). Since the sum of both is higher now it seems like most of the old supermarkets are still "Norma" and new ones are tagged by simply accepting any suggestion. Which means that the index has huge impact on the tagging and should be as good as possible. 

* The linked [wikidata](https://www.wikidata.org/wiki/Q450180) entry writes "Norma" (not uppercase).
* The [wikipedia](https://de.wikipedia.org/wiki/Norma_(Supermarkt)) entry writes "Norma Lebensmittelfilialbetrieb Stiftung & Co. KG". If we skip the legal form of the company as usual we end up with "Norma" (not uppercase).
* The [commercial register](https://www.online-handelsregister.de/handelsregisterauszug/by/Nuernberg/HRA/7886/Norma-Lebensmittelfilialbetrieb-Stiftung-Co-KG) writes "Norma Lebensmittelfilialbetrieb Stiftung & Co. KG". If we skip the legal form of the company as usual we end up with "Norma" (not uppercase).
* The [company itself](https://www.norma-online.de/de/impressum) writes in its imprint "Nor­ma Le­bens­mit­tel­fi­li­al­be­trieb Stif­tung & Co. KG". If we skip the legal form of the company as usual we end up with "Norma" (not uppercase).

The `brand=` might be tagged like the company communicates its brand. But the `name=` should be written like it is officially written.

There are many examples that a "brand word mark" is _not_ accepted as `name=`. People tag `name=Woolworth` ([shop=department_store](https://www.wikidata.org/wiki/Q183538)) instead of `name=WOOLWORTH`. They tag `name=Caterpillar` instead of `name=CATERPILLAR`. And so on.

For "id":"norma-c1eeeb" it should be (`name=Norma`) and (`brand=Norma` or `brand=NORMA`).

**Comment by Adamant36** [comment]
@Contrib1043

**Comment by Contrib1043** [comment]
Based on my research the official name is NORMA, the upper case spelling is used quite consistently on their homepage, in their logo, in their press releases, in their copyright and in their google listings etc. As far as I know, wikipedia forbids spelling in general, so it's not a reference for spelling issues (see ALDI, PENNY, REWE, OBI).

![image](https://user-images.githubusercontent.com/59527956/176544734-cd93e613-e3a2-412f-b2c3-3f5580ca4545.png)

![image](https://user-images.githubusercontent.com/59527956/176547283-bb6e002d-23a4-4107-9434-5dac5e106bc7.png)

So we have to choose, whether we want to copy wikipedia _or_ your mom's and dad's real world, where stores are named as corporate identify decides, whether we want to keep OSM history from 2016 _or_ to develop OSM to an relevant G* maps alternative in real life. 

I'm not convenienced of the arguments given above - but frankly, my dear fellows, please in any case, just improve OSM, check master data for your Norma or NORMA stores, add opening hours, add new stores, remove closed stores, add NSI reference - in the last couple of months I learned that unfortunately OSM is really often outdated in that regard in Germany and there are quite to few contributors.

Having said that, in case it helps to improve OSM data quality for retailers at large scale, feel free change to name="Norma" and brand="NORMA"

**Comment by bhousel** [comment]
Oh yeah we get a lot of requests like this to switch the capital named brands back and forth. 😞 
See #5509 and #5510 and whatever other issues those ones link to.

Mostly this project will just try to pick whatever `name` value the brand calls themselves, as long as looks reasonable on a map pin. 

Google Maps has them all upper case 
<img width="1175" alt="Screen Shot 2022-07-07 at 9 23 43 AM" src="https://user-images.githubusercontent.com/38784/177784363-b7deb2c8-e33b-480c-87b3-8be5b59ef744.png">

Apple Maps has them all lower case:
<img width="1134" alt="Screen Shot 2022-07-07 at 9 25 16 AM" src="https://user-images.githubusercontent.com/38784/177784993-3691fbc6-ffab-41a8-8320-5c6e034f5763.png">


I don't really care what the name is, but it bums me out to see these issues getting opened up about stuff that really doesn't matter much.
