### ISSUE TITLE
North Texas Tollway Authority

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#6677]
Add the [North Texas Tollway Authority](https://www.wikidata.org/wiki/Q13416600) to the operators tree as a ~~`man_made=toll_gantry`~~ `highway=toll_gantry` operator. NTTA is a common name for the operator that’s used on route shields and in speech; it could be `operator:short` for consistency with other entries in this tree.

**Comment by txemt1** [comment]
Wouldn't this be highway=toll_gantry, as that's how open toll gantries are labeled under OSM. They're not under the man_made tab.

**Comment by 1ec5** [comment]
Whoops, you’re right, I mixed up `highway=toll_gantry` with `man_made=gantry`.

**Comment by 1ec5** [comment]
#6703 adds this and the rest of the toll road operators in Texas.
