### ISSUE TITLE
Adding fee and payment details to Santander bicycle rental in London

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#6701]
I noticed that the Satander bicycle rental preset for London doesn't have any details on the fee and payment details - should this be added to the index?

**Comment by codeinabox** [comment]
I totally agree about the fee details as that would make extra work though what about `payment` and `authentication`? These are listed as [useful tags to add to bicycle renta](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental#Useful_tags_to_use_in_combination)

**Comment by 1ec5** [comment]
In #6703, I added some payment tags to electronic toll collection gantries, since that’s a very normal thing to tag on toll gantries and toll roads, but I tried to stick to a minimalistic set of tags.

**Comment by bhousel** [comment]
> In https://github.com/osmlab/name-suggestion-index/pull/6703, I added some payment tags to electronic toll collection gantries, since that’s a very normal thing to tag on toll gantries and toll roads, but I tried to stick to a minimalistic set of tags.

yes, I agree electronic toll collection gantries is a feature type where it does make sense to include the payment tags.
