### ISSUE TITLE
Add Mochinut as amenity/fast_food cuisine=donut;bubble_tea

### ISSUE THREAD

**Issue by hplewis** [osmlab/name-suggestion-index#6707]
Name: `Mochinut`
Wikidata: [Q112757409](https://www.wikidata.org/wiki/Q112757409)
Website: [https://www.mochinut.com/](https://www.mochinut.com/)
Type: `amenity/fast_food`
Cuisine: `donut` & `bubble_tea`

This place is primarily a donut shop, specializing in mochi donuts. However, they also have boba.

**Comment by hplewis** [comment]
While it is based in the United States, their website shows plans to expand South Korea and Thailand as well.

**Comment by arch0345** [comment]
You don't need to add an `id` as we have a script that automatically adds them:
https://github.com/osmlab/name-suggestion-index/wiki/Contributing#id-generated

**Comment by hplewis** [comment]
Thanks! #6720
