### ISSUE TITLE
Add Hidesign

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#6718]
Wikidata - https://www.wikidata.org/wiki/Q5752690
Number of Stores - Around 100 in India (https://hidesign.com/pages/store-locator)

**Comment by mann-codes2014** [comment]
Hi, I am new to Open Source. How Can I contribute to fix the issue and send a PR. Thanks

**Comment by arch0345** [comment]
> Hi, I am new to Open Source. How Can I contribute to fix the issue and send a PR? Thanks

Sorry for the late reply. We have a wiki article on how to contribute:
https://github.com/osmlab/name-suggestion-index/wiki/Contributing

Let me know if you have any questions.
