### ISSUE TITLE
Add 4 banks

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#6745]
The following companies should have both bank and ATM presets:

- [x] [First Hawaiian Bank](https://www.wikidata.org/wiki/Q3072937)
- [x] [Central Pacific Bank](https://www.wikidata.org/wiki/Q5061578)
- [x] [American Savings Bank](https://www.wikidata.org/wiki/Q4744919)
- [x] [HomeStreet Bank](https://www.wikidata.org/wiki/Q60762481)

Edit: linked to Wikidata items

**Comment by LaoshuBaby** [comment]
In fact ATM is inherited from Bank, so you only need to add those 4 bank in bank.json.

![图片](https://user-images.githubusercontent.com/42690037/177626508-cc0befa8-5afb-4079-a971-36a02c21a878.png)
