### ISSUE TITLE
Wolseley

### ISSUE THREAD

**Issue by boothym** [osmlab/name-suggestion-index#6748]
From: https://osm.mathmos.net/ghosts/plumb-center/ - don't know if there is a way to "upgrade" Plumb Center to Wolseley?

You can see the shop exterior here: https://www.mapillary.com/app/?pKey=868322580730633

name=Wolseley
shop=trade (seems to be the most used value)
brand:wikipedia=en:Wolseley UK
brand:wikidata=Q8030423

**Comment by arch0345** [comment]
I've added `matchNames`, which will prompt users to "upgrade" features that are named Plumb Center/Centre and Parts Center/Centre
