### ISSUE TITLE
Add 6 banks for India

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#6751]
- [x] City Union Bank (Q2040264)
- [ ] India Post Payments Bank (Q19895346)
- [ ] Equitas Small Finance Bank (Q29467249)
- [ ] Punjab & Sind Bank (Q2003302)
- [ ] Ujjivan Small Finance Bank (Q42529272)
- [ ] AU Small Finance Bank (Q48729722)

**Comment by ArjunSingh8769** [comment]
- Required
