### ISSUE TITLE
Revise Boyle Sports

### ISSUE THREAD

**Issue by VictorIE-OSM** [osmlab/name-suggestion-index#6757]
https://osmose.openstreetmap.fr/ is stating "The linked Wikidata item is instance of a living organism (Q21871294), which is not permitted"

BoyleSports Counterparty Limited is a company and not a human.

**Comment by arch0345** [comment]
https://www.wikidata.org/wiki/Q56760280

The Wikidata item for BoyleSports is correctly listed as an instance of a bookmaker (Q664702). Maybe the feature is also tagged with a `wikidata=*` tag or some other `:wikidata=*` tag.
