### ISSUE TITLE
Revise Honda 

### ISSUE THREAD

**Issue by VictorIE-OSM** [osmlab/name-suggestion-index#6758]
https://osmose.openstreetmap.fr/ is stating "The linked Wikidata item is instance of a living organism (Q21871294), which is not permitted"

Honda is a company and not a person.

**Comment by arch0345** [comment]
https://www.wikidata.org/wiki/Q9584

The Wikidata item for Honda isn't listed as an instance of a living organism. Maybe the feature is also tagged with a `wikidata=*` tag or some other `:wikidata=*` tag. This could also be a bug with osmose
