### ISSUE TITLE
William Hill (bookmaker)

### ISSUE THREAD

**Issue by VictorIE-OSM** [osmlab/name-suggestion-index#6759]
https://osmose.openstreetmap.fr/ is stating "The linked Wikidata item is instance of a living organism (Q21871294), which is not permitted"

William Hill plc is a company and not a person.

**Comment by arch0345** [comment]
https://www.wikidata.org/wiki/Q4053147

The Wikidata item for William Hill isn't listed as an instance of a living organism. Maybe the feature is also tagged with a `wikidata=*` tag or some other `:wikidata=*` tag. This could also be a bug with Osmose
