### ISSUE TITLE
Revise Oakfield Park (country estate, park and railway)

### ISSUE THREAD

**Issue by VictorIE-OSM** [osmlab/name-suggestion-index#6760]
https://osmose.openstreetmap.fr/ is stating "The linked Wikidata item is instance of a living organism (Q21871294), which is not permitted"

Oakfield Park (Q104351115) is a country estate, park and railway and not a human.

**Comment by arch0345** [comment]
https://www.wikidata.org/wiki/Q104351115

The Wikidata item for Oakfield Demesne is correctly listed as an instance of a townland (Q2151232). Maybe the feature is also tagged with a `wikidata=*` tag or some other `:wikidata=*` tag. This could also be a bug with Osmose
