### ISSUE TITLE
Add Pro Nails

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6774]
http://gopronails.com/locations/

**Comment by AlertSubject** [comment]
https://www.wikidata.org/wiki/Q113362663

I have created the wikidata object
Sadly there is already a store with the exact same name in NSI so the build command fails
even though "us" is excluded (Therefore not the same chain)

How do I get around this?

![grafik](https://user-images.githubusercontent.com/72819077/182002008-05a42e06-3ba4-41c2-8024-106e0024334a.png)

**Comment by AlertSubject** [comment]
nevermind, there already is an NSI entry for the requested chain
I've updated it and added the wikidata obj.
