### ISSUE TITLE
Display coat of arms for `amenity=townhall`

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/name-suggestion-index#6781]
Currently creating a node with the tags listed below doesn't display a logo. In that case, iD (or NSI) should display [coat of arms image](https://www.wikidata.org/wiki/Property:P94). It might also be a good idea to prioritise showing the coat of arms for `amenity=townhall` instead of their logo from Facebook/Twitter.
```
amenity=townhall
operator:wikidata=Q748965
operator=Община Варна
```
I'm not sure where the related part of code is contained, so I'm sending this issue here. Feel free to move it to iD's repo if this is not the right place.

**Comment by Dimitar5555** [comment]
In some countries municipalities operate villages (hence their townhalls). There are also places where a city is divided into regions/boroughs which are also operated by a local municipality.

**Comment by bhousel** [comment]
> Technically yes our `build_wikidata` script could probably fetch the P94 image as a fallback..

☝️ I did this
