### ISSUE TITLE
How should Aēsop be tagged?

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#6783]
Currently, Aēsop is tagged as `shop=cosmetics`. The issue is that the wiki says that that tag is for places that sell only cosmetics. Aēsop sells more than that - they sell soaps, which would probably fall under `shop=chemist`. The problem is that NSI uses that tag for Drugstore presets, which is definitely not what Aēsop is. What should be done?

**Comment by bhousel** [comment]
About Aēsop: https://www.aesop.com/us/r/about/

It seems similar to other types of shops are tagged with `shop=cosmetics`, so I think this tagging sounds correct.
See also:  https://nsi.guide/index.html?t=brands&k=shop&v=cosmetics
 
I guess "[cosmetics](https://en.wikipedia.org/wiki/Cosmetics)" really means more than just makeup - it includes other things like skin and hair care, lotions, soap, fragrance, shaving cream, etc.

**Comment by TheAdventurer64** [comment]
> About Aēsop: https://www.aesop.com/us/r/about/
> 
> 
> 
> It seems similar to other types of shops are tagged with [`shop=cosmetics`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcosmetics), so I think this tagging sounds correct.
> 
> See also:  https://nsi.guide/index.html?t=brands&k=shop&v=cosmetics
> 
>  
> 
> I guess "[cosmetics](https://en.wikipedia.org/wiki/Cosmetics)" really means more than just makeup - it includes other things like skin and hair care, lotions, soap, fragrance, shaving cream, etc.
> 
> 
> 
> 

Ah, alright. If this is the case, then maybe wiki should be updated accordingly. Currently, it says that places that sell personal hygiene products (in this case soap) along with cosmetics (their facial cleansers) should be tagged as `shop=chemist`.

**Comment by bhousel** [comment]
> Ah, alright. If this is the case, then maybe [the wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcosmetics) should be updated accordingly.

Yeah I agree 👍
