### ISSUE TITLE
Add government entities in Ridgefield WA

### ISSUE THREAD

**Issue by pdxrider** [osmlab/name-suggestion-index#6792]
I've been updating the map around Ridgefield, WA on OSM lately and noticed some government entities there that are not on NSI yet.

City of Ridgefield [Q1505990](https://www.wikidata.org/wiki/Q1505990) (should be listed as an operator in leisure=park, possibly other tags as well)
Ridgefield School District [Q7332752](https://www.wikidata.org/wiki/Q7332752) (operator in amenity=school)

**Comment by arrival-spring** [comment]
There are only 5 schools in that district, according to the Wikipedia page, so I think it is not notable enough for NSI

**Comment by pdxrider** [comment]
Didn't know that there has to be a minimum number of features in order to be eligible for an NSI entry, so thanks for informing me.

Only reason I brought this up is that it's the [fastest growing city in Washington state](https://en.wikipedia.org/wiki/List_of_municipalities_in_Washington) and surrounding municipalities have their own entries, which happen to be much larger than this fast-growing small town.

**Comment by 1ec5** [comment]
There has been some inconsistency on this point lately. Ten is documented as [a notability threshold](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case#notability). (It used to be higher.) However, [one user has successfully requested](https://github.com/osmlab/name-suggestion-index/issues?q=is%3Aissue+author%3AZol87) scores of smaller operators such as #7000 (grand total of two features in OSM). We should either remove those minor entries or accept many more of these requests to be fair.

/ref https://github.com/osmlab/name-suggestion-index/issues/8399#issuecomment-1676183849.
/cc @bhousel
