### ISSUE TITLE
Rename "Sea Oil" to "Seaoil"

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/name-suggestion-index#6793]
Per their [website](https://www.seaoil.com.ph/about-seaoil/who-we-are), the company calls itself Seaoil, not Sea Oil (Take note that SEAOIL is a stylistic capitalization).

**Comment by LaoshuBaby** [comment]
(In /data/brand/amenity/fuel.json)

![Image](https://user-images.githubusercontent.com/42690037/179403333-24876364-088f-4971-8dd7-64eaf41123c3.png)

Do you means change to this? I see the Wikidata and their website, their twitter, if they call them SEAOIL everywhere, they are SEAOIL. So I will prefer use the all uppercase capitalization.

---

But I'm not familiar with English so let other maintainer judge.

**Comment by ianlopez1115** [comment]
> ![Image](https://user-images.githubusercontent.com/42690037/179403333-24876364-088f-4971-8dd7-64eaf41123c3.png)
> 
> Do you mean change to this?

Yes

> [If] they call them SEAOIL everywhere, they are SEAOIL. So I will prefer use the all uppercase capitalization.
> 
> But I'm not familiar with English so let other maintainer judge.

As for name capitalization, it has been a recurring issue in NSI (See #4104, #5109, #5410, #5509, #5510, #6662). I wouldn't mind getting a second opinion from other maintainers on this matter.

**Comment by LaoshuBaby** [comment]
> As for name capitalization, it has been a recurring issue in NSI (See #4104, #5109, #5410, #5509, #5510, #6662). I wouldn't mind getting a second opinion from other maintainers on this matter.

Oh, thanks for those case, I'll see.  ♥

**Comment by ianlopez1115** [comment]
Did some research and found out that Philippine media outlets refers to it as Seaoil (see examples from [Philippine News Agency](https://www.pna.gov.ph/articles/1162146), [BusinessMirror](https://businessmirror.com.ph/2022/06/02/seaoil-to-build-oil-depotin-zamboanga-ecozone/), [Philippine Star](https://www.philstar.com/business/2021/10/22/2135740/seaoil-expand-retail-network-1000-2023), [ABS-CBN News](https://news.abs-cbn.com/business/10/22/21/seaoil-says-new-feature-can-lock-gas-prices), [Malaya Business Insight](https://malaya.com.ph/news_business/seaoil-to-build-p740m-depot/), [Philippine Daily Inquirer](https://business.inquirer.net/209681/seaoil-hits-record-income-15), [Rappler](https://Fwww.rappler.com/business/23487-seaoil-to-spend-p1b-for-expansion/), [CNN Philippines](http://www.cnnphilippines.com/news/2022/7/11/oil-price-rollback-effective-July-12.html), [Brigada News](https://brigadanews.ph/presyo-ng-mga-produktong-petrolyo-sa-camarines-norte-mataas-pa-rin-kabila-ng-dalawang-linggong-magkasunod-na-big-time-roll-back/), [Abante](https://www.abante.com.ph/bigtime-rollback-sa-petrolyo/), [Manila Standard](https://manilastandard.net/news/national/320669/oil-prices-cheaper-by-p2-liter.html) and [SunStar](https://www.sunstar.com.ph/article/1773622/manila/unioil-seaoil-to-cut-pump-prices-this-week)). Sometimes spelled as "SeaOil" in at least [one](https://business.inquirer.net/345749/oil-price-rollback-from-april-12-p1-per-liter-for-gasoline-p0-35-per-liter-for-diesel) instance though "Seaoil" is more prevalent.
