### ISSUE TITLE
Add 3 bookstore chain for India

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#6795]
- [ ]  Oxford Bookstore ([Q7115252](https://www.wikidata.org/wiki/Q7115252))
- [ ]  Higginbotham's ([Q1572944](https://www.wikidata.org/wiki/Q1572944))
- [ ]  Crossword Bookstores ([Q5188909](https://www.wikidata.org/wiki/Q5188909))

**Comment by AlertSubject** [comment]
#6848 
This issue can be closed then
