### ISSUE TITLE
Add 3 retail chains for India

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#6796]
- [ ]  Reliance Digital ([Q7311012](https://www.wikidata.org/wiki/Q7311012))
- [ ]  Hamleys ([Q60299](https://www.wikidata.org/wiki/Q60299)) 
- [ ]  Tanishq ([Q13117711](https://www.wikidata.org/wiki/Q13117711))

**Comment by Adamant36** [comment]
@bponkishore I split them up into individual issues in case different people want to do PRs for them during Hacktober Fest or whatever. Hopefully that's OK 👍
