### ISSUE TITLE
Is Starbucks everywhere (almost) the same?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#68]
If yes - amenity=restaurant, shop=coffee, maybe also amenity=fast_food should be nixed.

```
Starbucks
	 in amenity/cafe - 8463 times
	 in shop/coffee - 169 times
	 in amenity/restaurant - 54 times
	 and amenity/fast_food - 60 times
```

**Comment by bhousel** [comment]
afaict, nixing is really only useful if the wrong value is tagged more often than the right value. 
It's not really a problem to add it, but anyway iD will take the most popular one when it builds the suggestion list.
