### ISSUE TITLE
Apoteket

### ISSUE THREAD

**Issue by 1ec5** [osmlab/name-suggestion-index#6805]
[Apoteket](https://en.wikipedia.org/wiki/Apoteket) is a pharmacy chain in Sweden. Apparently iD flags `name=Apoteket` as a generic name, but this is the name.

**Comment by Adamant36** [comment]
[Wikidata entry](https://www.wikidata.org/wiki/Q1785637)
[Wikipedia article](https://en.wikipedia.org/wiki/Apoteket)

**Comment by Adamant36** [comment]
Thanks @kjonosm 👍
