### ISSUE TITLE
Update "One Network Bank" to "BDO Network Bank"

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/name-suggestion-index#6808]
One Network Bank was renamed to BDO Network Bank, change was made sometime in 2019 (see [article](https://www.philstar.com/business/2019/09/18/1952657/bdos-one-network-bank-changes-corporate-name)). Tagging schema can be changed to the following:

amenity=bank
brand=BDO Network Bank
brand:wikidata=Q7093019
name=BDO Network Bank

**Comment by LaoshuBaby** [comment]
Close because fixed in #6852
