### ISSUE TITLE
Add Road Runner Sports

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6825]
https://stores.roadrunnersports.com/

**Comment by JesseWeinstein** [comment]
It looks like this is resolved? If so, @LaoshuBaby , could you close this issue?

**Comment by LaoshuBaby** [comment]
> It looks like this is resolved? If so, @LaoshuBaby , could you close this issue?

Sorry, may I forget to add a `close #6825` in that PR, that will auto close this related issue. Thank you for telling me this.
