### ISSUE TITLE
Add AFC Urgent Care

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#6826]
They have over 250 locations across the US:
https://www.afcurgentcare.com/locations/

**Comment by Adamant36** [comment]
[Wikidata entry](https://www.wikidata.org/wiki/Q110552174)

**Comment by arch0345** [comment]
Added in https://github.com/osmlab/name-suggestion-index/commit/b144a514582f28fb853101b4375e83fd888df773
