### ISSUE TITLE
Please Add Niles Township High School District 219

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#6832]
https://en.wikipedia.org/wiki/Niles_Township_High_School_District_219

**Comment by e-papanicolas** [comment]
Hi there, I submitted a pr for this issue! It is my first contribution to open source, so I am not 100% I submitted it properly.

**Comment by UKChris-osm** [comment]
Thanks @e-papanicolas - @arch0345 has merged your PR 👍
