### ISSUE TITLE
add name=LuLu Mall 

### ISSUE THREAD

**Issue by deepthipatric** [osmlab/name-suggestion-index#6862]
name=LuLu Mall 
shop=shopping_centre
https://lulumall.in/

https://en.wikipedia.org/wiki/LuLu_Group_International

**Comment by Adamant36** [comment]
I don't think 4 locations is enough to justify them having an entry. You could just as easily add the Wikidata/Wikipedia information to OSM yourself at that point. Sorry. (The other option would be to create an entry for LuLu_Group_International as a building operator separate from the shopping centers, but I'm not sure how that would work or if it's even something there's an option for 🤷‍♂️)
