### ISSUE TITLE
Remove offering name:cz=Alza.cz on Alza shops

### ISSUE THREAD

**Issue by AF-HAF-KARTOGRAF** [osmlab/name-suggestion-index#6866]
Hello,
please change tag name:cz=Alza.cz to name:cs=Alza.cz on Alza shops. Prefix cs is prefix for Czech language but CZ is state code of the Czech Republic. Thanks!

**Comment by arch0345** [comment]
Thanks for catching this @AF-HAF-KARTOGRAF!
