### ISSUE TITLE
Webster Bank should be WebsterBank

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#6871]
There isn't usually a space between "Webster" and "Bank" on their signs. Although, sometimes they go by just "Webster" or "Bank" is on a new line if there isn't room on the sign for the words to be combined 🤷‍♂️ That said, WebsterBank without the space seems to be the more popular option. 
![450-main-st-new britain-ct-banking-center-3](https://user-images.githubusercontent.com/30259065/183139487-0d613a82-ebc0-4420-a7b1-3e4a3d044dd2.jpg)

**Comment by UKChris-osm** [comment]
Looking at their [website](https://public.websteronline.com/), they seem to include a space in their name.

**Comment by Adamant36** [comment]
> Looking at their [website](https://public.websteronline.com/), they seem to include a space in their name.

Down at the bottom of the page on the left hand side they have it both with and without a space. That said, actual locations still overwhelmingly don't have one. I guess it ultimately depends on your priorities. Go with the space because their website uses it in a few places along with no space, or go without the space because literally every location IRL doesn't have it. And really, at the end of the day the point in OSM isn't to funnel people to their website. It's to help people map things IRL.  

![Screenshot 2022-08-06 031410](https://user-images.githubusercontent.com/30259065/183244811-94d6688c-3d4f-4c41-98d8-199f25799d8f.png)
![1200x0](https://user-images.githubusercontent.com/30259065/183244859-522e8db4-f062-4b92-b815-98e40d2d5e66.jpg)
![Screenshot 2022-08-06 031550](https://user-images.githubusercontent.com/30259065/183244863-1062e22b-e235-45bf-b095-e4f85beca389.png)
![797-pine-st-forestville-ct-banking-center-2](https://user-images.githubusercontent.com/30259065/183244869-b58b25c0-e0bb-4cf1-a131-b991037dbac5.jpg)
![webster-bank-712-main-st-watertown-ct-banking-center-2]
![webster-bank-137-bank-st-waterbury-ct-banking-center_1](https://user-images.githubusercontent.com/30259065/183244887-2103278e-35fc-443e-940c-88ff04dff501.jpg)
![301-main-st-danbury-ct-banking-center-2](https://user-images.githubusercontent.com/30259065/183244891-621e87c3-2bc8-40b1-940b-f9a7d2331219.jpg)
![708-hopmeadow-st-simsbury-ct-banking-center-2](https://user-images.githubusercontent.com/30259065/183244899-7d74fbfc-eb48-4aa1-9ad1-ce4d4afeb230.jpg)
