### ISSUE TITLE
Mark Lewiatan as case where both shop=convenience and shop=supermarket are OK

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#69]
It in on border of these two, so it is tagged in both styles.

As result it appears in output of make.

Adding

```
    "Lewiatan":{
        "nix_value":[
        ]
    },
```

to canonical.josm is not removing 

```
Lewiatan
	 in shop/convenience - 565 times
	 and shop/supermarket - 255 times
```

from output of make.

**Comment by matkoniecz** [comment]
All tagged shops operating under name Lewiatan are in Poland (http://overpass-turbo.eu/s/s9t), so I expect that in this case there is low chance of situation being different in other parts of world.

**Comment by bhousel** [comment]
I think you need to add something in `nix_value`, see:
https://github.com/osmlab/name-suggestion-index/blob/1d82d9a9c55dde5f0258fb7fc3f23164b3a41100/canonical.json#L97-L104

**Comment by matkoniecz** [comment]
Would it be OK to put dummy value or is it something that should be fixed by modifying processing code?

**Comment by bhousel** [comment]
I'm not sure, @matkoniecz -  are you just trying to suppress the output from Make?  Why?

**Comment by matkoniecz** [comment]
> Why?

Maybe it is my misunderstanding, but I understood output from make as TODO list of things that should be handled.

**Comment by bhousel** [comment]
> Maybe it is my misunderstanding, but I understood output from make as TODO list of things that should be handled.

Oh, yeah I don't see it as a TODO, more just information.   I don't really have an opinion.  You are probably right that we should pick one single preset for each case that might be ambiguous.

On the iD side, we currently just pick the most popular one anyway.

**Comment by bhousel** [comment]
Did a bit of digging, 
Lewiatan is here:  https://pl.wikipedia.org/wiki/Lewiatan_(sie%C4%87_handlowa)

Based on that page, it looks like a `shop=convenience` to me.. since it is most frequently tagged that way, we don't need to do anything special.. 👍

**Comment by matthijsmelissen** [comment]
I often travel to Poland, and I would certainly also consider the Lewiatan's that I visit supermarkets. See for example [this picture](https://upload.wikimedia.org/wikipedia/commons/a/ab/Sklep_sieci_Lewiatan_w_60-tysi%C4%99cznym_Tomaszowie_Mazowieckim_w_wojew%C3%B3dztwie_%C5%82%C3%B3dzkim._Ul._Ho%C5%BCa_1.jpg). I would suggest reopening.

Thanks for going through old issues btw!

**Comment by bhousel** [comment]
> I often travel to Poland, and I would certainly also consider the Lewiatan's that I visit supermarkets. See for example [this picture](https://upload.wikimedia.org/wikipedia/commons/a/ab/Sklep_sieci_Lewiatan_w_60-tysi%C4%99cznym_Tomaszowie_Mazowieckim_w_wojew%C3%B3dztwie_%C5%82%C3%B3dzkim._Ul._Ho%C5%BCa_1.jpg). I would suggest reopening.

ok thanks for the additional info.. I'm working on canonical.json toady, and I'll change it so that we can support single name working with multiple tags.

**Comment by bhousel** [comment]
Currently Lewiatan in the `canonical.json` index twice.  I have a massive list of names to deduplicate, and I'll just not do it for this one.

Actually thinking out loud - it would be nice to add a property to say that the names are different and suppress the warning.  I'll do that and then close the issue here.

<img width="594" alt="screenshot 2018-09-14 11 52 14" src="https://user-images.githubusercontent.com/38784/45561043-c643f800-b814-11e8-90bf-aa75332cb715.png">
