### ISSUE TITLE
Malteser Hilfsdienst is brand or operator?

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#6909]
Now when run `npm run build` it will give a warning:

```
⚠️   Warning - matchIndex errors:
----------------------------------------------------------------------
  `key/value/name` occurs multiple times in the match index.
  To resolve these, make sure the key/value/name does not appear in multiple trees
    (e.g. `amenity/post_office/ups` should not be both a "brand" and an "operator"
----------------------------------------------------------------------
Duplicate cache key "amenity/recycling/q1318397" in trees "operators" and "brands", check items: malteserhilfsdienst-6737d9
total 1
```

This is because `malteserhilfsdienst-6737d9` in [operators/amenity/recycling.json](https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/amenity/recycling.json) and `malteserhilfdienst-f6fab4` in [brands/amenity/recycling.json](https://github.com/osmlab/name-suggestion-index/blame/main/data/brands/amenity/recycling.json) are same entity, they have the same wikidata.

Details are shown below:

https://github.com/osmlab/name-suggestion-index/blob/ec766cfdec7d88dfdf2ea3455fb97eae15ff64c4/data/operators/amenity/recycling.json#L2190-L2199

https://github.com/osmlab/name-suggestion-index/blob/844909e140354d8e7857a71be99401115bd0eb29/data/brands/amenity/recycling.json#L186-L198

Maybe we need a German mapper review this and select which one should be use, and select proper matchNames and tags.

**Comment by kmpoppe** [comment]
Currently discussing on https://t.me/OSM_de whether it's one or the other - or both.

Will come back to you :-)

**Comment by AlertSubject** [comment]
https://github.com/osmlab/name-suggestion-index/issues/2588

Local experts could be pinged

**Comment by AlertSubject** [comment]
Looks like the Telegram group has decided on "brand"
Operator can only be determined through survey

for later reference: https://t.me/OSM_de/81212

**Comment by kjonosm** [comment]
I agree that `brand` should rather be used as the organisation as a whole is split into regional dioceses and further into smaller branches which usually operate services on the local level.

**Comment by bhousel** [comment]
Just linking here to the comment I wrote last year that might help decide whether an item is more brand-like or operator-like:

https://github.com/osmlab/name-suggestion-index/issues/5625#issuecomment-958218478

**Comment by LaoshuBaby** [comment]
> Vermutlich. Dann wohl nur "brand"

So I merge this, and reserve the brand one in https://github.com/osmlab/name-suggestion-index/commit/4fd6a0838cf4c1ca9f107860d9a8046891ef649c

2 item's name have different so I follow de-wikipedia's entry name.

Thanks for German community's advice.
