### ISSUE TITLE
Talk N' Fix entry spelled wrong

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#6914]
Talk N' Fix is wrongly spelled as Talk n' FIx in the index. The N should be upper case and the i in "Fix" needs to be lowercase per their website. Same goes for the Wikidata entry. 

@arch0345

**Comment by habi** [comment]
Wikidata has been corrected: https://www.wikidata.org/w/index.php?title=Q108410613&type=revision&diff=1702271012&oldid=1572625692
