### ISSUE TITLE
Swiss `post_box`es should be `colour=yellow`

### ISSUE THREAD

**Issue by habi** [osmlab/name-suggestion-index#6919]
All Swiss `amenity=post_box`es operated by the Swiss postal service are distinctively yellow (see https://wiki.openstreetmap.org/wiki/Switzerland/amenity%3Dpost_box).
I'd like to add `colour=yellow` to [the relevant entry](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box&tt=Q614803#diepost-c6967d), but could *not* find it https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/amenity/post_box.json or by [searching for the relevant Wikidata ID](https://github.com/osmlab/name-suggestion-index/search?q=Q614803).

If anyone can give me a pointer on where to change this I'm happy to produce a PR.

**Comment by bhousel** [comment]
Hey @habi  - you did have the right file `amenity/post_box.json`, but the post boxes are confusing because they use "templates" to automatically create items based on items from other files.  

I ended up solving this in 53616ff by _excluding_ Swiss post from the default template, and creating a special template that only _includes_ Swiss Post but also adds the `colour=yellow` tag.

**Comment by habi** [comment]
Thanks for the explanation, which makes perfect sense. And the fix!

**Comment by UKChris-osm** [comment]
@bhousel a while ago in the UK, some post boxes were painted a different colour for various reasons (local / national celebrations) and I was just wondering how this might effect adding the colour tag in this way?

If, for example, a post box is repainted, and a local mapper updates the colour, will the NSI then continue to flag this as an error?

**Comment by LaoshuBaby** [comment]
> @bhousel a while ago in the UK, some post boxes were painted a different colour for various reasons (local / national celebrations) and I was just wondering how this might effect adding the colour tag in this way?
> 
> If, for example, a post box is repainted, and a local mapper updates the colour, will the NSI then continue to flag this as an error?

use `preserveTag:["colour"]` to avoid overwrite?

**Comment by bhousel** [comment]
Yea @UKChris-osm and @LaoshuBaby you're both right .. Adding a `colour=yellow` tag here would raise errors for occurrences of these post boxes with other colors, unless we set the `preserveTag` to allow mappers to use other values.

**Comment by UKChris-osm** [comment]
It's been a long while since I've contributed to the NSI, so am a bit behind - so does `preserveTag` prevent any suggestion appearing in iD if the tag in question already exists?

**Comment by bhousel** [comment]
> It's been a long while since I've contributed to the NSI, so am a bit behind - so does `preserveTag` prevent any suggestion appearing in iD if the tag in question already exists?

Yes - it can be set to match tag where the value is a reasonable default, but not necessarily that value works everywhere.
