### ISSUE TITLE
Replace wikidata for Thom Browne

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#6922]
Hi,

I suggest to change the wikidata for [Thom Browne](https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=thom%20b#thombrowne-3937bd) from brand:wikidata=Q3524805 (the founder) to brand:wikidata=Q113502386 (the brand).

**Comment by UKChris-osm** [comment]
Thanks @ivanbranco - a good spot 👍
