### ISSUE TITLE
add brand:wikidata to Claudie Pierlot

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#6932]
Hi,

https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=claudi#claudiepierlot-3937bd

I created the brand:wikidata entry for this brand, it's: Q113516684

**Comment by UKChris-osm** [comment]
Thanks @ivanbranco, I've added this via [d933f50](https://github.com/osmlab/name-suggestion-index/commit/d933f504de0dd3f64ab787e5b3a2df8ffa0dc013)
