### ISSUE TITLE
British Heart Foundation Home Stores

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#6954]
BHF run Home Stores, charity shops which just sell furniture and some white goods:
https://www.bhf.org.uk/shop/home-stores

Currently we don't have a separate tag for them, but it seems like it might be worthwhile assuming separate wikidata I guess?

I guess this is Tesco Metro/Superstore again effectively...

Not sure what to tag them as still charity shop but can we differentiate goods somehow?

**Comment by UKChris-osm** [comment]
I think you could use the same wikidata as the standard BHF brand.

If going for a tag other than shop=charity then adding charity=yes could also be an option.
