### ISSUE TITLE
Add Raiffeisen Bank Romania

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#6955]
Similar to #4409 we need to add also the Romanian branch of Raiffeisen Bank.

Wikidata item: [Q7283806](https://www.wikidata.org/wiki/Q7283806)
Wikipedia page: [Raiffeisen Bank România](https://ro.wikipedia.org/wiki/Raiffeisen_Bank_Rom%C3%A2nia)

**Comment by kjonosm** [comment]
Romanian branch of Raiffeisen Bank is already listed in NSI, see here:
https://nsi.guide/index.html?t=brands&k=amenity&v=bank&cc=ro#raiffeisenbank-9a9a30

**Comment by DnaX** [comment]
Sorry, I was searching it misspelled.

**Comment by kjonosm** [comment]
ok
