### ISSUE TITLE
Add parcel locker eMAG Easybox

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#6956]
In Romania, the most common ecommerce platform eMAG put lots of parcel locker.

The name is "easybox" (all lowercase) and all of them are operated by eMAG ([Q23827008](https://www.wikidata.org/wiki/Q23827008))

Could be proposed this tagging schema:

```
amenity=parcel_locker
brand=eMAG
brand:wikidata=Q23827008
name=easybox
```

Further info (in Romanian): https://www.emag.ro/easybox

**Comment by kjonosm** [comment]
Hey @DnaX! I've added easybox to the index. However, I made some adjustments to your suggestions above: easybox is the actual brand of the parcel lockers operated by eMag. According to their website each parcel locker is individually named by their location so I left out the name tag.

**Comment by DnaX** [comment]
I reopen this issue to modify the data. Those "easybox" parcel lockers, are owned and operated by Sameday, a courier company based in Romania and Hungary. Only some of them are just branded by eMAG for sponsoring reasons.

So we should modify as specified:

```
{
  "displayName": "easybox",
  "locationSet": {"include": ["ro", "hu"]},
  "tags": {
    "amenity": "parcel_locker",
    "brand": "easybox",
    "operator": "Sameday",
    "operator:wikidata": "Q114417096",
  }
}
```
