### ISSUE TITLE
Key Cutting Machine

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#6959]
I didn't realise there were so many [key cutting machines](https://www.mykeymachine.com/) available in the UK.

How would these appear in OSM / NSI - as _amenity=vending_machine_, or perhaps _craft=key_cutter_?

_craft=key_cutter_ seems to refer to a shop (a small one) rather than a machine, but _amenity=vending_machine_ doesn't include the option for _vending=key_cutting_ as far as I can tell.

**Comment by arch0345** [comment]
We're currently using [`vending=key`](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=key) for similar machines such as Fast Key, KeyMe, and Minute Key
