### ISSUE TITLE
Rebranding of Galeria Karstadt Kaufhof GmbH stores

### ISSUE THREAD

**Issue by Yelteen** [osmlab/name-suggestion-index#6965]
Last Year in August the Galeria Karstadt Kaufhof GmbH started rebranding it's stores to Galeria, as the new brand is going to be applied to all stores, the two brands "Karstadt" (karstadt-ca042d) and "Galeria Kaufhof" (galeriakaufhof-ca042d) should be merged.[Source (german)](https://www.handelsblatt.com/unternehmen/handel-konsumgueter/warenhaeuser-karstadt-und-kaufhof-verschwinden-so-sieht-das-neue-logo-von-galeria-aus/27535314.html)

The stores should be tagged as
```
brand=Galeria
brand:wikidata=Q80220059
name=Galeria
shop=department_store
```
in addition with

```
was:brand=Karstadt
old_name=Karstadt
```
```
was:brand=Galeria Kaufhof
old_name=Galeria Kaufhof
```
The description "German retail store chain" stays the same, the website is https://www.galeria.de/, their Facebook https://www.facebook.com/galeria.de.official Instagram https://www.instagram.com/galeria.de.official and YouTube https://www.youtube.com/c/GALERIA-de-official

**Comment by AlertSubject** [comment]
A merge wouldn't be possible if you want to keep the old "was_brand" and "old_name" for both objects, or am I wrong?
How would we go about merging properly?

I'd do it if someone answers the question

**Comment by Yelteen** [comment]
I'm not quite sure, because the rebranding is going on, and many people call the newly branded store by the old name. So possibly only a deprecation notice with a new brand OR keep both brands but update both properties. I think the last way would be more useful.
