### ISSUE TITLE
Add Club Alpino Italiano

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#6971]
Hi, 

I'm kindly requesting to add an operator.

The tagging would be:

office=association
name=Club Alpino Italiano
branch=* (usually "Sezione di [random city])
short_name=CAI
operator=Club Alpino Italiano
operator:wikidata=Q795273
operator:wikipedia=it:Club Alpino Italiano
this is the logo: https://it.wikipedia.org/wiki/File:Cai_Club_Alpino_Italiano_Stemma.png

also right now many clubs are named as "name=Club Alpino Italiano sezione di [random city]", could be possibile to suggest the change to the user with "name=Club Alpino Italiano+branch=Sezione di [random city]"?

**Comment by arch0345** [comment]
Thanks for bringing this to my attention. Moved it to office=association

**Comment by ivanbranco** [comment]
Hi, something is still wrong, NSI still suggest to add amenity=social_facility to CAI offices, see https://www.openstreetmap.org/changeset/133091146

The preset should be the following:

office=association
name=Club Alpino Italiano
short_name=CAI
operator=Club Alpino Italiano
operator:wikidata=Q795273
operator:wikipedia=it:Club Alpino Italiano

is it possible to fix it?

**Comment by UKChris-osm** [comment]
> operator:wikipedia=it:Club Alpino Italiano

Just as an FYI @ivanbranco, we no longer include any `wikipedia` tags in the NSI data, only `wikidata` tags.
