### ISSUE TITLE
Add Tuff Shed shops

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#6974]
https://www.tuffshed.com/

**Comment by yakhyaevs** [comment]
https://greenshops.netlify.app/

**Comment by Adamant36** [comment]
https://en.wikipedia.org/wiki/Tuff_Shed
Wikidata Q7851474

**Comment by nickmendezFlatiron** [comment]
@Adamant36 I would like to fulfill this request , please assign it to me at your earliest convenience. Thanks

**Comment by bhousel** [comment]
Welcome @nickmendezFlatiron  - we dont really do assignments here, just read the Project Wiki here to learn more about the index, and if you find stuff that is missing or wrong, send a PR with the fix 👍 
https://github.com/osmlab/name-suggestion-index/wiki

**Comment by nickmendezFlatiron** [comment]
I've updated brands/hardware to include Tuff shed in this pull request #7118 
@bhousel
