### ISSUE TITLE
Add operator:short=GTT

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#6976]
Hi,

I suggest adding operator:short=GTT with operator=Gruppo Torinese Trasporti to this suggestion: https://nsi.guide/index.html?t=transit&k=route&v=tram#formula-e9e131
as was done to Trenitalia with operator:short=TI (https://nsi.guide/index.html?t=transit&k=route&v=train&tt=trenit#trenitalia-66b763)

**Comment by arch0345** [comment]
Added in https://github.com/osmlab/name-suggestion-index/commit/825ec406a421863350d34a18abcff84e466ee21f
