### ISSUE TITLE
name= on amenity_parcel_locker

### ISSUE THREAD

**Issue by coolultra1** [osmlab/name-suggestion-index#6979]
Hi,

It seems to me, some templates for parcel lockers include a `name=` tag, some don't. The tag is generally unneccessary as the name that's rendered on Carto, for instance is the `brand=` tag. How about removing all `name=` from `amenity=parcel_locker`s, then?

**Comment by hanchao** [comment]
The labeling logic has not changed, it still use name.
https://github.com/gravitystorm/openstreetmap-carto/pull/4512#pullrequestreview-1052871137
https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/amenity-points.mss#L2970

**Comment by coolultra1** [comment]
Though, for some reason, brand is (also) rendered https://www.openstreetmap.org/node/9071299691

**Comment by hanchao** [comment]
> Though, for some reason, brand is (also??) rendered https://www.openstreetmap.org/node/9071299691

This is a good case. My mistake.
When importing data, use the brand first
https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L1490

**Comment by kjonosm** [comment]
We could also add `"preserveTags": ["^name"]` to the general properties in the file, see e.g. `bicycle_rental.json` for reference.

**Comment by hanchao** [comment]
I added "preserveTags": ["^name"] to the amenity/parcel_locker in https://github.com/osmlab/name-suggestion-index/commit/5876cc41ce479c4af9e6c56b5afa37d8f7e97592

This will allow the name tag as an initial value, but users are encouraged to change it, and NSI will not overwrite the custom names that people add.

See https://github.com/osmlab/name-suggestion-index/pull/4985
