### ISSUE TITLE
Some P.R.China brand wrong suggested in Poland because they musen't have branch, and need be excluded

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#6981]
"{"include":["001"],"exclude":["cn"]}" for "bank in the People's Republic of China"

https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Construct

Either https://www.wikidata.org/wiki/Q26299 or NSI is wrong.

I am pretty sure that it is not operating in Poland (I just have seen in iD matches there).

**Comment by bhousel** [comment]
I think the intent here is to tag it as:
"中国建设银行" in China, 
"中國建設銀行 China Construction Bank" in Hong Kong,  and 
"China Construction Bank" outside of China.

https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Q26299

It does seem to have a few branches around the world in financial centers, but we could definitely exclude Poland if you don't like seeing it in the list.

**Comment by matkoniecz** [comment]
So 

> bank from the People's Republic of China

or 

> bank centered in the People's Republic of China

or 

> bank primarily operating in the People's Republic of China

would be more accurate than what https://www.wikidata.org/wiki/Q26299 has right now, right? 

> but we could definitely exclude Poland if you don't like seeing it in the list.

+1 to that, unless I missed something and it has locations in Poland

**Comment by LaoshuBaby** [comment]
I've noticed a lot of brand in NSI have a `exclude pl` in locationset, (infact I also added some `exclude cn` because the government won't letthem in🤣 )
Those big international company usually have a 001 entry in English to match global branch company, like Marriott's hotel and Apple's electric store. (although CCB mainly operating in China. I think your second description is most exactly one.)
I think you can just exclude it if you think those brand won't have branch in your country.

**Comment by LaoshuBaby** [comment]
@matkoniecz 

I also thought that there would be no CCB branch in Poland. But before I edit `bank.json` I search for CCB's Europe website, and surprisedly found that it have a branch in Warsaw, here is official information and address.

http://eu.ccb.com/europe/cn/tszl/685457.html

> 华沙分行
> 
> 地址：Warsaw Financial Center, ul. Emilii Plater 53, 00-113 Warsaw, Poland
> 
> 电话：0048-22-1666666
> 
> 传真：0048-22-1666600
> 
> 邮箱:  marketing.pl@eu.ccb.com

On [WFC's website](https://wfc.pl/en) I found that this branch office located in 15 floor:

![图片](https://user-images.githubusercontent.com/42690037/187370564-93efc536-89c7-4e30-abb3-ecbaa29f9087.png)

Can you review this changeset ? https://www.openstreetmap.org/changeset/125553918
