### ISSUE TITLE
Phở Hòa signage is Phở Hòa + Jazen Tea

### ISSUE THREAD

**Issue by cliffordsnow** [osmlab/name-suggestion-index#6985]
A new Phở Hòa just opened near me. The signage has Phở Hòa + Jazen Tea same as their menu (below) Should the name be updated? Unfortunately it is the only one of the chain near me.

![phohoa](https://user-images.githubusercontent.com/3290977/187540244-2d599b04-d70b-4839-a958-1aa9f65e072d.jpg)

**Comment by 1ec5** [comment]
Jazen is a store-within-a-store concept. The overall store remains Phở Hòa, but a separate [`amenity=cafe` `cuisine=bubble_tea`](https://www.openstreetmap.org/node/8442146835) feature could be mapped right alongside it.

**Comment by cliffordsnow** [comment]
I didn't stop in but a friend showed me the menu. What interested me is the signage. Both Phở Hòa and Jazen Tea. The Jazen Tea website, jazentea.com, only shows 6 locations. Five near San Jose, CA and one near me in Washington State. There are another 12 locations outside of the US.

I agree that using two separate tags makes sense. Do you want a new issue or can you create one from here? There is no wikidata item.

**Comment by 1ec5** [comment]
Fixed in 23401b7d467b5a63f245a11cf2ac88272a1e9d58.
