### ISSUE TITLE
Remove "Dentista"

### ISSUE THREAD

**Issue by picsi** [osmlab/name-suggestion-index#70]
That's just a generic name meaning "dentist" in Portuguese.

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json). "Dentista" is also a generic name for "dentist" in [several other romance languages](https://en.wiktionary.org/wiki/dentista).
