### ISSUE TITLE
National Trust operator:type should be charitable

### ISSUE THREAD

**Issue by trigpoint** [osmlab/name-suggestion-index#7006]
The operator type for National Trust and National Trust for Scotland are incorrectly set to private, they are charities and the operator type should be charitable.

The error is in https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/leisure/park.json

      "displayName": "National Trust",
      "id": "nationaltrust-8367e0",
      "locationSet": {
        "include": ["gb-eng", "gb-nir", "gb-wls"]
      },
      "tags": {
        "leisure": "park",
        "operator": "National Trust",
        "operator:type": "private",
        "operator:wikidata": "Q333515"
      }
    },
    {
      "displayName": "National Trust for Scotland",
      "id": "nationaltrustforscotland-5433bf",
      "locationSet": {"include": ["gb-sct"]},
      "tags": {
        "leisure": "park",
        "operator": "National Trust for Scotland",
        "operator:type": "private",
        "operator:wikidata": "Q599997"
      }

to

      "displayName": "National Trust",
      "id": "nationaltrust-8367e0",
      "locationSet": {
        "include": ["gb-eng", "gb-nir", "gb-wls"]
      },
      "tags": {
        "leisure": "park",
        "operator": "National Trust",
        "operator:type": "charitable",
        "operator:wikidata": "Q333515"
      }
    },
    {
      "displayName": "National Trust for Scotland",
      "id": "nationaltrustforscotland-5433bf",
      "locationSet": {"include": ["gb-sct"]},
      "tags": {
        "leisure": "park",
        "operator": "National Trust for Scotland",
        "operator:type": "charitable",
        "operator:wikidata": "Q599997"
      }

**Comment by UKChris-osm** [comment]
Thanks @trigpoint  👍
