### ISSUE TITLE
Trying to update existing feature's wikidata

### ISSUE THREAD

**Issue by xmready** [osmlab/name-suggestion-index#7034]
A business group, Cotton On Group, has multiple retail chain brands under it. Currently two of these brands in the name index use the same `brand:wikidata` reference. I am creating new wikidata items to link the `parent organization` and `subsidiary` brands.

How can I update the `brand:wikidata` for one of the brands already in the name index with the new reference? Can I simply edit the .json, replace the old `brand:wikidata` with the new and submit a pull request? Does the `id` need to change also? Or do I need to create a new entry?

Thanks in advance and apologies for my ignorance.

**Comment by UKChris-osm** [comment]
> Can I simply edit the .json, replace the old `brand:wikidata` with the new and submit a pull request?

Yes, if the current brand entry is using a parent wikidata as the brand, and the actual brand has its own wikidata then you can simply update the brand:wikidata entry via a PR. The id element is an NSI only feature and doesn't end up in OSM, and it isn't affected by the brand:wikidata element.

**Comment by xmready** [comment]
> you can simply update the brand:wikidata entry via a PR.

What will happen to all the existing Points Of Interest using the suggested data once the change is merged? Will their `brand:wikidata` be updated automatically, or will they have to be changed manually?

**Comment by UKChris-osm** [comment]
As OSM data is separate from the NSI (this repository only acts as a dataset for suggesting edits) then nothing will happen to any existing POI's in OSM, except that when they are selected when editing in iD, the new brand:wikidata would be suggested as an edit. Current POI's would need to be manually changed, or an automatic edit setup elsewhere, but that automatic edit wouldn't be achieved via the NSI.

**Comment by xmready** [comment]
Last question, how long after a successful merge will OSM suggest the feature with the updated data?

**Comment by UKChris-osm** [comment]
We don’t have a set schedule, but there is roughly a fresh release every week or so, and once the latest update is released, the database is available instantly in iD (subject to cache issues).

**Comment by xmready** [comment]
Thanks for the info, all my questions have been answered.
