### ISSUE TITLE
"ASDA On The Move" issues

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#7038]
A couple of issues with the "Asda On The Move" (asdaonthemove-232829) preset:

1/ It currently uses the Q297410 Asda wikidata tag, but there's a more specific one defined for this brand: Q105221621

2/ It looks like its set up to prompt iD users to add this brand for any convenience stores named Asda. I don't think this will always be correct. Many larger Asda stores will have convenience stores at associated petrol stations. These shops may not be branded as "Asda On The Move". The preset is likely to lead unsuspecting users into adding incorrect data.

**Comment by UKChris-osm** [comment]
I added [ASDA on the Move](https://github.com/osmlab/name-suggestion-index/commit/fca3dc0b5472e428843381d4fc60b5cd338baa7f) a few weeks ago after learning of its existence, and used the ASDA wikidata as I didn’t realise you had crated a brand specific one already, and while the wikidata can be changed easily, the one you have created doesn’t reference any image / logo, or social media at the moment and so wouldn’t be included in the NSI. Are you able to add an “_on the move_” logo at all?

One of the downsides of brands like Asda, Tesco, etc who have multiple store types does mean that suggestions won’t always be 100%, but then my view is that they are only suggestions, and mappers still need to be aware of what they are mapping. If a building is named as simply Asda, then I think it’s reasonable for the suggestion list to be a supermarket, a petrol station or a convenience store, and for the mapper themselves to select the appropriate item.

I think the nature of OSM will always be open to the possibility of incorrect data entry.
