### ISSUE TITLE
The shop type of "Trial (Japanese store brand)" could be wrong

### ISSUE THREAD

**Issue by Revtro** [osmlab/name-suggestion-index#7040]
Hello.
I would like to report that I thought the type of shop in the Japanese store "Trial" seems wrong, as shown in the title.
Currently, it seems to be `shop=variety_store`, but I think the correct type is `shop=supermarket`.
[Search results for nsi.guide](https://nsi.guide/index.html?t=brands&k=shop&v=variety_store&tt=%E3%83%88%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%AB)

Trial stores mainly deal in daily necessities, food, clothing, and home appliances.
Aeon (or one of its brands, Aeon Supercenter), a well-known "supermarket" in Japan, also has stores that deal in these items as well.
Since Aeon is considered a supermarket, Trial should be considered a supermarket as well.

Also, the wiki on variety_store says "basically a retail store that sells all products at a single low price", but as mentioned above, I don't think Trial is the same.
I think the general perception is also that Trial is a supermarket (but it may depend on personal perception).

For example, Naming sample in Japan, etc. refer to the trial as a "supermarket".

[https://wiki.openstreetmap.org/wiki/JA:Naming_sample#shop=supermarket](https://wiki.openstreetmap.org/wiki/JA:Naming_sample#shop=supermarket)
[https://wiki.openstreetmap.org/wiki/JA:Naming_sample#shop=variety_store](https://wiki.openstreetmap.org/wiki/JA:Naming_sample#shop=variety_store)

If this is acceptable, I would appreciate it if you could fix the problem.

**Comment by UKChris-osm** [comment]
Thank you @Revtro - I have had a little look and I agree with you that Trial should be a supermarket!

**Comment by Revtro** [comment]
Thank you very much for your approval and correction as well.

**Comment by UKChris-osm** [comment]
Happy to help @Revtro - this should now be live in iD has @arch0345 has published our latest release!
