### ISSUE TITLE
Question about brand Hrvatska poštanska banka

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#7047]
Hi,

I have a question about the brand [Hrvatska poštanska banka](https://nsi.guide/index.html?t=brands&k=amenity&v=atm&tt=Hrvatska#hrvatskapostanskabanka-4d8c03). There are some ATMs in Croatia mapped as brand=HPB or operator=HPB that are not flagged with the NSI suggestion on iD editor, it's possibile to include these ([67 uses as far](https://overpass-turbo.eu/s/1lXX))?

Also would be possible to suggest brand:short=HPB and/or operator:short=HPB to existing ones?

**Comment by UKChris-osm** [comment]
Hi @ivanbranco - thanks for your question, I have added what we call a "_matchname_" to cater to the HPB abbreviation, and this should appear in the iD editor soon.
