### ISSUE TITLE
Add Reliance Digital

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#7049]
Indian consumer electronics retailer

[Wikidata link](https://www.wikidata.org/wiki/Q7311012)
[Wikipedia article](https://en.wikipedia.org/wiki/Reliance_Digital)

**Comment by UKChris-osm** [comment]
[Reliance Digital](https://nsi.guide/index.html?t=brands&k=shop&v=electronics&tt=reliance#reliancedigital-91ea11) is already in the index @Adamant36 :)

**Comment by Adamant36** [comment]
Oh good. Someone else had created an issue with multiple brands and I split it off from there in the hopes someone would fo it for Hacktober Fest. I guess they don't need to now though 😅
