### ISSUE TITLE
Add a new pharmacy brand April

### ISSUE THREAD

**Issue by JBJack** [osmlab/name-suggestion-index#7057]
Please add the brand (pharmacy chain) April. The link to wikidata is attached.
https://www.wikidata.org/wiki/Q114060847

**Comment by LaoshuBaby** [comment]
https://github.com/osmlab/name-suggestion-index/commit/7edee32fbdcc300eb3cc5c2541f804c692bdd668

Already merged.

**Comment by JBJack** [comment]
In the editor on Openstreetmap, the pharmacy did not appear. 
[https://imgur.com/a/ShBDHOp](url)
When you manually add a wikidata to a point, the name and brand are not pulled up.
[https://imgur.com/a/RmxZQAm](url)

**Comment by LaoshuBaby** [comment]
@JBJack this will need some days.

We will publish new version of package weekly or half month.(usually) And after it publish to npm, it may need several days let all CDN use latest json. This time can't be control by ourselves, you can try clean you cache in local browser and reload iD after a week.

This also been talked in #6958 and #6592

---
By the way, you can paste photo with Ctrl+V to github directly
