### ISSUE TITLE
Fixing an error on openstreetmap

### ISSUE THREAD

**Issue by JBJack** [osmlab/name-suggestion-index#7058]
Yesterday you added a pharmacy to the Name Suggestion list
https://nsi.guide/?t=brands&id=d13b83-571ebe
https://www.wikidata.org/wiki/Q114060847

The pharmacy did not appear in the editor on Openstreetmap.
https://imgur.com/a/ShBDHOp

When you manually add wikidata to a location, the name and brand are not pulled up.
https://imgur.com/a/RmxZQAm

**Comment by UKChris-osm** [comment]
Hi @JBJack 

Unfortunately this entry will not show up in iD until a logo is available to the Name Suggestion Index via the Wikidata article. We can grab a logo from a Facebook or Twitter account that is reference in the Wikidata article, or via an image included in the Wikidata article itself using the Logo Image item (P154).

[https://www.wikidata.org/wiki/Q106424150](https://www.wikidata.org/wiki/Q106424150) shows an image logo included in the Wikidata article that the NSI will use.

**Comment by arch0345** [comment]
As explained in https://github.com/osmlab/name-suggestion-index/issues/7057#issuecomment-1253919760, we only publish a new release every week or so. I usually create a new release every Monday.
