### ISSUE TITLE
Add Lounge restaurant chain (UK)

### ISSUE THREAD

**Issue by GeorgeHoneywood** [osmlab/name-suggestion-index#7069]
UK based restaurant chain with ~200 locations.

Names are unique to each restaurant, but they all follow the format of "[single spanish word ending with -o] Lounge".

[Brand website](https://thelounges.co.uk/)
[Parent company website](https://loungers.co.uk/about/)
[List of locations](https://thelounges.co.uk/lounges/)

[Wikipedia](https://en.wikipedia.org/wiki/Loungers) (these entries appear to be for the parent company, not specifically the Lounge brand)
[Wikidata](https://www.wikidata.org/wiki/Q111914262)

**Comment by UKChris-osm** [comment]
Thank you for the suggestion @GeorgeHoneywood 👍

**Comment by GeorgeHoneywood** [comment]
Thanks for adding this!
