### ISSUE TITLE
Delete transit operator

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7078]
Please delete SulFertagus (sulfertagus-d62b2b) because this dont have a wikidata number and no longer exists. 
Thank you

**Comment by bhousel** [comment]
It looks like the SulFertagus item will keep being collected into the index as long as the `network=SulFertagus` tag is being used in OSM:

https://nsi.guide/index.html?t=transit&k=route&v=bus#sulfertagus-d8d67b
[Overpass query](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22network%22%3D%22SulFertagus%22%5D%3B)%3B%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B%0A%0A%7B%7Bstyle%3A%0Anode%2C%0Away%2C%0Arelation%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Broute%3Dbus%5D%2C%0Away%5Broute%3Dbus%5D%2C%0Arelation%5Broute%3Dbus%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Broute%3Dbus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%2C%0Away%5Broute%3Dbus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%2C%0Arelation%5Broute%3Dbus%5D%5Bnetwork%3Awikidata%3Dundefined%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R)


So I think the first step is to remove the bus lines from OSM, if they really aren't existing anymore.

**Comment by DiogoBaptista98** [comment]
Delete this, theres no item associated.
