### ISSUE TITLE
`npm run wikidata` script is switching back and forth between two entries

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#7081]
[Q7237158](https://wikidata.org/wiki/Q7237158) is currently linked to both 365.bank and Poštová banka as a result of [this merge](https://www.wikidata.org/w/index.php?title=Q7237158&oldid=1685079480). Since then, `npm run wikidata` [has been switching between adding 365.bank and Poštová banka](https://www.wikidata.org/w/index.php?title=Q7237158&action=history) to the OSM Name Suggestion Index identifier property. It looks like this might be because we still have the old QID for 365.bank in `brand:wikidata`. Would it be better to update the QID on NSI or to revert the merge on Wikidata?

**Comment by LaoshuBaby** [comment]
For my opinion, if on wikidata this is correct, we should change NSI's value to new QID, wikidata is our "upstream"
