### ISSUE TITLE
Add Edmonton Catholic Schools

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#7088]
Please add school operator preset for Edmonton Catholic Schools (ECSD). Preset already exists for Edmonton Public Schools/EPSB, but not the separate Catholic school district.

website: https://www.ecsd.net
Wikipedia: en:Edmonton Catholic School District

-----
data/operators/amenity/school.json
```json
    {
      "displayName": "Edmonton Catholic School District",
      "locationSet": {
        "include": ["ca-ab.geojson"]
      },
      "tags": {
        "amenity": "school",
        "operator": "Edmonton Catholic School District",
        "operator:short": "ECSD",
        "operator:type": "public",
        "operator:wikidata": "Q5339019"
      }
    },
```

**Comment by TagaSanPedroAko** [comment]
@LaoshuBaby For the display name, let's use the shorter form Edmonton Catholic Schools, as found on the school district logo. Same can be done for Edmonton Public School Board (EPSB), which has the shorter common name "Edmonton Public Schools".

**Comment by SerpentBytes** [comment]
If no one is working on this issue, I would like to work on this one. Please assign it to me.

**Comment by arch0345** [comment]
It looks like we already have entries for ECSD and EPSB:
https://github.com/osmlab/name-suggestion-index/blob/94f799336fe00ee8124766e637882d15f1257e86/data/operators/amenity/school.json#L9062-L9087

I'll add `operator:short` for ECSD and fix `operator:short` for EPSB
