### ISSUE TITLE
Move Brazilian post office (Correios) to brands tree

### ISSUE THREAD

**Issue by matheusgomesms** [osmlab/name-suggestion-index#7100]
Hey guys!

I saw the discussions in this repository [here](https://github.com/osmlab/name-suggestion-index/issues/5561), [here](https://github.com/osmlab/name-suggestion-index/pull/5613) and [here](https://github.com/osmlab/name-suggestion-index/issues/5625).

However, as [we discussed in the Community Forum](https://community.openstreetmap.org/t/how-to-properly-tag-a-post-office-brand-operator/3056), we got to the conclusion that, at least in case of _[Correios](https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&tt=correio)_, we should use `brand` instead of `operator`.

The reason is that all _Correios_ (which is a public company, much like USPS) branches have this brand, but some of them are private operated. So it is not correct to tag all of them with `operator=Correios`.

Is it possible to move it back to the brands tree?

Also, I would like to ask to create another NSI suggestion: _Correios_ as a amenity=post_depot (not sure if I should open a new issue for that). So we would end with 3 _Correios_ suggestions: `post_office`, `post_depot` and `post_box`

Thanks a lot!

**Comment by UKChris-osm** [comment]
Hi @matheusgomesms 

I've added a post_depot for Correios.

I'll wait for others to add any opinions about moving the post office from operator to brand, but your reasoning does seem legitimate.

**Comment by vgeorge** [comment]
I agree with the reasoning behind using `brand` instead of `operator` for `post_office` described by @matheusgomesms and discussed elsewhere. 

I'm not so sure though about adding `post_depot` and `post_box`. 

As the wiki [states](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_depot), post depots are places not generally open to the public and I don't think the `brand` tag applies in that case. The `operator` tag is suggested in the wiki, but this is a very specific mapping that I don't think needs to be supported by NSI.

About post boxes, I don't remember seeing many in São Paulo, not sure about other parts of Brazil. I suggest holding the creation until there is a clearer demand to use it.

**Comment by matheusgomesms** [comment]
Hi @vgeorge 

Thanks for the support!

Regarding `post_depot`, I suggested because there are some _Correios_ distribution centers wrongly mapped. People are using `post_office` for those places (which is not the case, since you're right when mentioning that they are not open to public).

My idea is to avoid this wrong mapping, as you can see that [I've fixed here](https://www.openstreetmap.org/node/4464236696). I used `name=Centro de Distribuição dos Correios`, so I guess it is clear, besides the tag, that it is a distribution center and not a normal agency. Perhaps we could use this name for `post_depot`?

Regarding `post_box`, many companies have this NSI suggestion (and _Correios_ has it too already). Indeed, in Brazil they are not that common anymore, but on OSM [there are 500+ post boxed mapped](https://overpass-turbo.eu/s/1mk9), and it can be more, if it's easier to map them. If we remove it from NSI, then it is not possible anymore to map it (easily) on EveryDoor for instance (they use NSI).

**Comment by UKChris-osm** [comment]
> As the wiki [states](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_depot), post depots are places not generally open to the public and I don't think the `brand` tag applies in that case. The `operator` tag is suggested in the wiki, but this is a very specific mapping that I don't think needs to be supported by NSI.

I should have probably been clearer, but I have added the post_depot entry under the "_operator_" tree as opposed to the "_brand_" tree.

**Comment by vgeorge** [comment]
Thanks for the clarification @UKChris-osm and @matheusgomesms. I agree it makes sense to have both of them, and also use the extended names: "Agência dos Correios" for `brand:*` and "Centro de Distribuição dos Correios" for `operator:*`.
