### ISSUE TITLE
Adding Algérie Poste brand

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#7121]
Hi, I suggest to add a new brand for amenity=post_office in Algeria. The tagging would be (copied by [this clean-up](https://wiki.openstreetmap.org/wiki/Mechanical_edits/Friendly_Ghost#Algerian_Post)):

```
brand=بريد الجزائر
brand:en=Algérie Poste
brand:fr=Algérie Poste
brand:website=https://www.poste.dz/
brand:wikidata=Q2836029
brand:wikipedia=ar:بريد الجزائر
```

**Comment by kjonosm** [comment]
NSI lists entries in the `operator` branch, when `brand` information duplicates `operator` information. This is the case with Algérie Poste, see https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&cc=dz#algerieposte-e99ec0

Please also note that NSI doesn't store `website` oder `wikipedia` information.

**Comment by ivanbranco** [comment]
I thought I checked in the operators list also. Better than, thanks for the reply.
