### ISSUE TITLE
Cashzone ATM

### ISSUE THREAD

**Issue by Cj-Malone** [osmlab/name-suggestion-index#7143]
I was going to add [Cashzone](https://www.wikidata.org/wiki/Q110738461) ATM, but it's most often tagged as [operator](https://taginfo.openstreetmap.org.uk/search?q=Cashzone#values) and NSI seems to want ATMs to have brand tags not operator tags?

**Comment by LaoshuBaby** [comment]
Yes, most bank were seen as brand, so both of them in brand tree:

![图片](https://user-images.githubusercontent.com/42690037/194023894-5dc40b46-dbdb-482b-b4d4-5e27e680bfc5.png)

**Comment by Snowysauce** [comment]
Marking as completed - Cashzone was added as an ATM brand in February 2023.
