### ISSUE TITLE
Add Italian chain of supermarkets Pam Local

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7187]
Proposed tagging:

```
"brand": "Pam Local",
"brand:wikidata": "Q105614389",
"name": "Pam Local",
"shop": "supermarket"
```

It is another brand of the PAM group: https://www.gruppopam.it/en/pam-local

**Comment by kjonosm** [comment]
According to their website, Pam local is rather `shop=convenience` not `shop=supermarket`.
@DnaX Can you confirm?

**Comment by DnaX** [comment]
It's the small branch of the main supermarket chain, for example in the shop you have only the small hand chart so yes, better `shop=convenience`.
