### ISSUE TITLE
Duplicated item pharmacy Dona

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7194]
I think that the items dona-8861f5 and farmaciadona-8861f5 represent the same Romanian pharmacy chain.

**Comment by kjonosm** [comment]
@DnaX Which one of the two would be the preferred name?

**Comment by DnaX** [comment]
I think to good name it's "Farmacia DONA". See also the website (sorry, romanian): https://www.farmaciiledona.ro/
