### ISSUE TITLE
Remove "amenity/place_of_worship|Chapelle"

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#72]
"Chapelle" is just a generic name for "Chapel"
The source of so many "Chapelle" seems to be an import; for example, https://www.openstreetmap.org/way/68238798

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json).

**Comment by matthijsmelissen** [comment]
All good points! Would you be able to create pull requests?

**Comment by naoliv** [comment]
@matthijsmelissen by simply including the generic names at [filter.json](https://github.com/osmlab/name-suggestion-index/blob/master/filter.json) or something else is needed for this, please?

**Comment by naoliv** [comment]
Thanks for the merge!
