### ISSUE TITLE
Problem with transport entry

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#7201]
Hi,

there's a problem with this transport entry that operates only in the city of Catania: https://nsi.guide/index.html?t=transit&k=highway&v=bus_stop&tt=amt#amt-785058

apparently they changed name from AMT to AMTS, as a result none of the bus routes in Catania (which have network=AMTS and operator=AMTS) are flagged with this suggestion in iD editor: https://overpass-turbo.eu/s/1mMm

As a matter of fact not even one Catania route is update at the moment, in the database we have:
31 | not:network:wikidata | Q3601036
1 | network:wikidata | Q3601036 which is incorrect since is another city (that has an operator called in the same way of the old name aka ATM)

so 
1. the check should now look for AMTS instead of AMT
1b. Maybe it would be better to restrict the area for this check only to the area of Catania since there's a transport network with the same name in another city (Benevento city).

**Comment by UKChris-osm** [comment]
> 1b. Maybe it would be better to restrict the area for this check only to the area of Catania since there's a transport network with the same name in another city (Benevento city).

Would this be the [City area](https://www.openstreetmap.org/relation/39230) or the [County area](https://www.openstreetmap.org/relation/39181)?

**Comment by ivanbranco** [comment]
> > 1b. Maybe it would be better to restrict the area for this check only to the area of Catania since there's a transport network with the same name in another city (Benevento city).
> 
> Would this be the [City area](https://www.openstreetmap.org/relation/39230) or the [County area](https://www.openstreetmap.org/relation/39181)?

The city!

**Comment by UKChris-osm** [comment]
Thanks @ivanbranco 

Has AMTS in Benevento City also rebranded / been replaced?

**Comment by ivanbranco** [comment]
> Thanks @ivanbranco
> 
> Has AMTS in Benevento City also rebranded / been replaced?

Uhm, I don't know that company, but the Wikidata for "AMTS (Benevento)" says "**former** public transport service". The wikipedia page says: "è stata un'azienda pubblica italiana" (**was** an italian public company) and then "A partire dal 15 febbraio 2017 AMTS ha terminato la propria attività, passata alla società Trotta Bus Services" (As of 15 February 2017, AMTS ceased operations and passed to the company Trotta Bus Services).

So seems like AMTS Benevento has been replaced since 2017 by this company: https://www.wikidata.org/wiki/Q105086527

**Comment by UKChris-osm** [comment]
I've updated the AMTS Catania name and restricted the area using a [geo-circle](https://location-conflation.com/?locationSet=%7B%22include%22%3A%5B%5B15.1%2C37.5%5D%5D%7D&referrer=nsi), which should go live in the next update in a few days.
