### ISSUE TITLE
Add polish vegan burger franchise

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#7203]
Hi, 

I propose to add this polish restaurant chain:

amenity=restaurant
name=Krowarzywa
diet:vegan=only
diet:vegetarian=only
brand=Krowarzywa
brand:wikidata=Q107299031

EDIT: Wait, maybe should it be amenity=fast_food ? I'm gonna link this in the Polish telegram group.

**Comment by ivanbranco** [comment]
Ok maybe this is better:

amenity=fast_food
name=Krowarzywa
diet:vegan=only
diet:vegetarian=only
brand=Krowarzywa
brand:wikidata=Q107299031
cuisine=burger
takeaway=yes
delivery=yes (you can order from the website)

I changed with fast_food because is the preferred tag (10 uses vs 6) and because they advertise as such on the official website. I linked the discussion in the polish OSM group in case a local wants to edit it with something better.

**Comment by UKChris-osm** [comment]
They seem to refer to themselves as a restaurant on their website when I looked, but that was the English translation that they provided so perhaps it isn't accurate? Is their food pre-prepared on site or freshly prepared?

**Comment by ivanbranco** [comment]
Oh, I see.

"W naszych **restauracjach**" and "Jesteśmy wśród najlepszych **restauracji** w Polsce."

Then they also call it "street food": "Odwiedź nas i przekonaj się, że wegański **street food** jest smaczny i zdrowy!"

and at the bottom page they featured a review that calls them fast food: "najzdrowszy wegański **fast food** w mieście - KUKBUK"

I never been there, but when I wrote on Telegram that I would have changed it from restaurant to fast food I got a thumb up from a polish user who knows the franchise firsthand: https://t.me/OpenStreetMapPolska/9547
and again fast food is the most used value for the brand atm (10 vs 6). Maybe @matkoniecz can help us (I got the name from the "Local experts list")?

**Comment by bhousel** [comment]
Regardless of whether the establishment calls itself a "restaurant" in its name , the OpenStreetMap convention is to tag it as `amenity=restaurant` if there is table service (i.e. a waiter/waitress takes your order), and `amenity=fast_food` otherwise.

**Comment by ivanbranco** [comment]
> Regardless of whether the establishment calls itself a "restaurant" in its name , the OpenStreetMap convention is to tag it as `amenity=restaurant` if there is table service (i.e. a waiter/waitress takes your order), and `amenity=fast_food` otherwise.

I asked it to a local: "Hi! There's no table service at Krowarzywa"
