### ISSUE TITLE
Sklep Polski - Polish Store

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#7207]
Maybe @ivanrome can help here?

The planet run has added "_Sklep Polski_" to the index, but this seems to just translate to "Polish Store" - can anybody confirm if such a brand exists in Poland, or if it is indeed just a generic term?

**Comment by ivanrome** [comment]
Hello, 
I've jsut done a google search and I found a supermarket chain name like that.

https://www.skleppolski.pl/

It's quite extended in the west of Poland according to this information:
https://www.skleppolski.pl/sklepy

Don't hesitate to local checks if needed

Regards

**Comment by UKChris-osm** [comment]
Thanks @ivanrome 👍
