### ISSUE TITLE
Research needed for: amenity/pharmacy|Первая помощь

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#723]
#### :thinking: We need help deciding what to do with "amenity/pharmacy|Первая помощь"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/pharmacy|Первая помощь` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/pharmacy|Первая помощь`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/pharmacy|Первая помощь`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by ENT8R** [comment]
@Adamant36 I don't think that this is a generic one: https://translate.google.de/translate?sl=auto&tl=en&u=http%3A%2F%2Fwww.aptekapp.ru%2F

**Comment by Adamant36** [comment]
"First aid" sounds generic to me. The more I do this though, the more I learn there's some really generic name brands out there. Especially in Russia for some reason. I couldn't find the link you referenced when I did research myself either. 

Is the Tag usage in Moscow and St. Petersburg to go along with it? If so, feel free to remove the generic tag and add a needs wikidata one or whatever.
