### ISSUE TITLE
Add brand:BSB Fashion clothing retail chain store

### ISSUE THREAD

**Issue by sucrerouge123** [osmlab/name-suggestion-index#7240]
Hi!

I would like to request the addition of BSB Fashion Greek women's clothing retail chain store which operates in Greece (75 stores), Romania (28 stores), Cyprus (8 stores), Bulgaria (4 stores), Albania (1 store), Armenia (1 store), Egypt (1 store) and Kosovo (1 store).

shop:clothes
clothes:women
name:BSB Fashion
brand:BSB Fashion
brand:wikidata:Q12721399
website=https://www.bsbfashion.com/
country codes:gr, ro, cy, bg, sq, al, am, eg, xk

Thanks!

**Comment by sucrerouge123** [comment]
Please remove sq from the country codes (I expect that we use ISO 3166-1 alpha-2, so the country code for Albania is AL not SQ).

Thank you!

**Comment by LaoshuBaby** [comment]
> Please remove sq from the country codes (I expect that we use ISO 3166-1 alpha-2, so the country code for Albania is AL not SQ).

Infact I remove it in formatter run, you can see latest code.

By the way, you can find every supported country/region codes in https://ideditor.codes/ and here is a playground: https://location-conflation.com/

Many JavaScript based OSM project are all using those 2 infrastructure library

**Comment by sucrerouge123** [comment]
Please remove sq from the country codes (I expect that we use ISO 3166-1 alpha-2, so the country code for Albania is AL not SQ).

Thank you! Is there a reason that the website was excluded from the tags?

**Comment by LaoshuBaby** [comment]
> Is there a reason that the website was excluded from the tags?

Do you means why I don't collect website or other detailed contact tags like email or phone? Also we don't collect wikipedia tags.

You can see https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case, and those kind of information can be added to wikidata, we use wikidata as one of identifier。
