### ISSUE TITLE
Change name:en and brand:en and cuisine of gregorys-6b115c

### ISSUE THREAD

**Issue by sucrerouge123** [osmlab/name-suggestion-index#7255]
Both name:en and brand:en should be Gregory's and not Gregorys, according to their website, and cuisine should be changed to coffee shop, as Gregory's is mostly noted for it's coffee, and not like let's say Subway which specializes in sandwiches.

Thanks!

**Comment by LaoshuBaby** [comment]
> and cuisine should be changed to coffee shop, as Gregory's is mostly noted for it's coffee, and not like let's say Subway which specializes in sandwiches.

Do you need also change catagory to amenity=cafe and remove it from amenity=rerstaurant while change cuisine=coffee_shop? (Sorry we currently haven't judge case about which is cafe and which is restaurant) 
By the way I noticed both coffee and fast_food are its major food according to English wikipedia

**Comment by sucrerouge123** [comment]
As I understand cuisine=coffee_shop is mostly used in combination with amenity=cafe and not with amenity=fast_food. Gregory's is a chain of stores which some of them are in fuel stations and other small cafes. Most of them have sitting areas, but never a waiter, so they do qualify for fast_food. They do serve cold meals, such as cakes and sandwiches, but a person will most primarily enter a store to grab a cup of coffee, so the tag cuisine=coffee_shop is better. But I hesitate cause this is not a much used combination.

Their website mentions: Gregory’s has continued to grow ever since. Today, with more than 360 stores in Greece, Cyprus, Germany and Romania, it is the 9th biggest _coffee store_ chain in Europe.

**Comment by sucrerouge123** [comment]
So, it's better to leave it as it is. Just change the name:en and brand:en tags, and adding the "cy" country code.

Thanks!

**Comment by sucrerouge123** [comment]
Please add the tag:

drink:coffee=yes.

Sorry for not opening a new issue, but I don't want to spam. Tell me if this is a wrong practice.

Thanks!

**Comment by bhousel** [comment]
> Please add the tag:
> `drink:coffee=yes`
> Sorry for not opening a new issue, but I don't want to spam. Tell me if this is a wrong practice.

We don't really add tags here for the kinds of items that a restaurant serves.
