### ISSUE TITLE
Research needed for: amenity/pharmacy|Семейная

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#726]
#### :thinking: We need help deciding what to do with "amenity/pharmacy|Семейная"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/pharmacy|Семейная` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/pharmacy|Семейная`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/pharmacy|Семейная`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
@Adamant36 Why you think it is a generic name?

https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%D0%A1%D0%B5%D0%BC%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F gives translation "Family" what looks like a brand name.

**Comment by Adamant36** [comment]
I don't know. "Family Pharmacy" sounds generic to me. I'm pretty sure it is a generic name for local, "mom and pop" pharmacies in America. Like "family owned" or something. 

I couldn't find any common branding on Google/ Google image search when I looked it up either.
