### ISSUE TITLE
Add BEAT fast food chain in Greece

### ISSUE THREAD

**Issue by sucrerouge123** [osmlab/name-suggestion-index#7269]
amenity=fast_food
brand=ΒΕΑΤ
brand:wikidata=Q114830599
cuisine=sandwich
drink:coffee=yes
name=BEAT
alt_name=B-eat
opening_hours=24/7
takeaway=yes
delivery=yes

**Comment by LaoshuBaby** [comment]
> Furthermore, all Beat have diet:vegan=yes outdoor_seating=yes smoking=outside website=https://b-eat.gr/ wheelchair=yes WLAN=yes
> 
> And the cuisine is a bit more expanded Sandwich;crepe;hot_dog;coffee;burger;salad;juice

Sorry, you can have a look at https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case

If it isn't a only vegan/vegetarian restaurant, I don't think we need to emphasize this.

Also, we only need to collect the major kind of food, NSI isn't a menu.

---

And we don't collect those kind of tag need on ground survey such as ` outdoor_seating` or `smoking`, even those are advertised by this brand.
