### ISSUE TITLE
Add C Spire

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/name-suggestion-index#7278]
C Spire, formerly known as Cellular South, Inc., is an American telecommunications company operating in Mississippi, Tennessee, Alabama and Florida that sell mobile phones and service plans through its retail locations.

shop=telecommunication
name=C Spire
brand=C Spire
brand:wikidata=Q5015101

(This issue was first raised at a [discussion](https://osmus.slack.com/archives/C2VJAJCS0/p1666966647516329) on Slack)

**Comment by MoiraPrime** [comment]
I'd like to suggest this tag be restricted to just Tennessee, Alabama, and Misssissippi instead of just the generic United States. It is unlikely they're ever going to expand out of this region.
