### ISSUE TITLE
README.md in sub-folders

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#7292]
I tried adding a README.md file in the gb sub-folder of the features, as a reference to which areas were matched to the local [ISO 3166-2:GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB) for the UK, and it caused a build error, which I am going to assume is because the feature script is designed to grab everything in the folder to build the features file?

Is it possible to add an exception to the build script to ignore any README.md files during the build process?

**Comment by bhousel** [comment]
> Is it possible to add an exception to the build script to ignore any README.md files during the build process?

Good suggestion! I just made this change so the build script should ignore markdown files.
