### ISSUE TITLE
Escape quotation marks in Overpass Turbo queries

### ISSUE THREAD

**Issue by Dimitar5555** [osmlab/name-suggestion-index#7299]
Currently quotation marks are not escaped which breaks the query. See [0e50c9-143312](https://nsi.guide/index.html?t=operators&k=man_made&v=pipeline&tt="&cc=001#0e50c9-143312 ) for an example.

**Comment by LaoshuBaby** [comment]
Yes, it will raise a error like this:

![图片](https://user-images.githubusercontent.com/42690037/199113142-bc3b833d-9cf8-40a5-8d22-2ade5eb6d077.png)

because generated overpassql is:

```overpassql
[out:json][timeout:100];
(nwr["operator"="ОАО "Гомельтранснефть Дружба""];);
out center;
```

**Comment by Dimitar5555** [comment]
The problem seems to be in the listed below lines which need ``.replaceAll('\"', '\\"')``. I don't think that it's needed for the flags, but it can be added.
https://github.com/osmlab/name-suggestion-index/blob/0670add58d05e25719f83a6e3a52683e5d4c78a7/app/src/CategoryRow.jsx#L31
https://github.com/osmlab/name-suggestion-index/blob/0670add58d05e25719f83a6e3a52683e5d4c78a7/app/src/CategoryRow.jsx#L65
https://github.com/osmlab/name-suggestion-index/blob/0670add58d05e25719f83a6e3a52683e5d4c78a7/app/src/CategoryRow.jsx#L89
> https://github.com/osmlab/name-suggestion-index/pull/7290 also have edit in this file, if this is not so urgent, I suggest we don't do any change until that PR merged

I will wait until it's merged before creating a PR for this issue.

**Comment by UKChris-osm** [comment]
I've changed the double quotes " to a single quite ' when we call Overpass, so the double quotes within a name no longer clash.
