### ISSUE TITLE
Add "PicWicToys"

### ISSUE THREAD

**Issue by Manjiro5Fr** [osmlab/name-suggestion-index#7319]
Hello, i wish the french toy store PicWicToys (which took over a large majority of the Toys"R"Us in France) in sign proposed in iD. I'm also surprised that it's not up to date when it's been 4 years.
French Wikipédia link : https://fr.m.wikipedia.org/wiki/PicWicToys
Thank you a lot
Cordially
Manjiro5 (my OSM and Wikimedia account)

**Comment by UKChris-osm** [comment]
Hi @Manjiro5Fr 

It seems [PicWic](https://nsi.guide/index.html?t=brands&k=shop&v=toys#picwic-7999e4) is part of the index - but just needs a slight edit.

**Comment by Manjiro5Fr** [comment]
Thanks

Le jeu. 3 nov. 2022 à 23:06, UKChris-osm ***@***.***> a
écrit :
