### ISSUE TITLE
Please Add People's Gas

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#7336]
https://en.wikipedia.org/wiki/Peoples_Energy

**Comment by Snowysauce** [comment]
Queries on overpass-turbo return no results for People Energy/Peoples Energy, and no results for People Gas/Peoples Gas that are relevant to the linked company. Please add entities operated by the company to OSM and/or tag them with `operator=Peoples Gas` so we can determine if this company should be in the NSI.
