### ISSUE TITLE
Problems with Portuguese fuel brand Galp

### ISSUE THREAD

**Issue by siiky** [osmlab/name-suggestion-index#7359]
There are a few problems with the Portuguese brand Galp.

- [x] It's written "Galp" as per everywhere I've ever seen that matters, not "GALP" (including [their site](https://galp.com) but also [Wikidata](https://www.wikidata.org/wiki/Q1492739) and [Wikipedia](https://en.wikipedia.org/wiki/Galp_Energia)). I also asked the local community to be extra sure.

- [x] It doesn't currently show as a fuel brand for Portugal in https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&cc=pt (lol). I believe this problem is due to these lines:

https://github.com/osmlab/name-suggestion-index/blob/84aaad45602f3916b51351335566bd5d603faca4/data/brands/amenity/fuel.json#L1888-L1891

I have no idea what `001` is, but I'm guessing it should be `pt` instead. The `pl` looks out of place too, but I don't see it hurting.

- [ ] In Portugal, fuel stations with a name different from the brand are more common than would warrant keeping `name=brand` (on top of that,  yes, I'm on that side of https://github.com/osmlab/name-suggestion-index/issues/29, I think it doesn't make sense to include `name=brand`).

I can open a PR once the issues are confirmed.

**Comment by arch0345** [comment]
> It's written "Galp" as per everywhere I've ever seen that matters, not "GALP" (including [their site](https://galp.com/) but also [Wikidata](https://www.wikidata.org/wiki/Q1492739) and [Wikipedia](https://en.wikipedia.org/wiki/Galp_Energia)).

If the local community prefers this capitalization, feel free to open a PR to change it.

> I have no idea what `001` is

`001` is the [UN M49](https://en.wikipedia.org/wiki/UN_M49) code for the world. If Galp only has locations in Portugal, this should be changed to just `pt` (and `pl` should be removed).

**Comment by siiky** [comment]
> `001` is the [UN M49](https://en.wikipedia.org/wiki/UN_M49) code for the world. If Galp only has locations in Portugal, this should be changed to just `pt` (and `pl` should be removed).

I didn't know UN M49.

I found this [map](https://galp.com/pt/pt/particulares/estrada/mapa) of many Galp fuel stations. It seems they exist in Spain as well, I had no idea. For now I'll open a PR to fix the locations.

**Comment by siiky** [comment]
Opened #7402 to fix the casing problem.

Now only the `name=brand` issue remains. I was hoping to hear from your side what you think about this. In particular, is the "decision" in #29 final? Or do you open exceptions on request? Would you merge a PR that removes the `name=Galp`? Then I could go back to the local community and ask what is their opinion on this specific case -- if they'd rather have `name=Galp` or not.

**Comment by UKChris-osm** [comment]
If you feel the name tag will be unique in certain locations for this brand, you can now add `"preserveTags": ["^name"],` to the entry, and this will tell iD not to overwrite a name if it already exists, and only add a `name` tag as a default if one isn't present.

**Comment by siiky** [comment]
Thanks for the suggestion, but I think that goes besides the point.

For one, this isn't an issue with iD alone because NSI is used on other editors as well (e.g. JOSM and Every Door).

Let's say a fuel station that sells fuel of the Galp brand is called "My Super Fuel Station". Let's say I see such a fuel station only in passing. I may notice that it sells Galp fuel but not that it's called "My Super Fuel Station". I open Every Door and add a Galp fuel station. `name=Galp` will be added even though it's wrong. How does `perserveTags` help in this scenario?

**Comment by siiky** [comment]
Also, see the wiki page for `amenity=fuel`: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel#Names

> If the station has a [name](https://wiki.openstreetmap.org/wiki/Key:name) of its own, that can be tagged too using name=*.

**Comment by UKChris-osm** [comment]
> I open Every Door and add a Galp fuel station. `name=Galp` will be added even though it's wrong. How does `perserveTags` help in this scenario?

This would be available to EveryDoor to also support, but it's something they would have to implement if they chose to do so - but they may have already done so - @Zverik are you able to answer this?

The NSI was developed with iD in mind, and back then it was about the `name` tag. As things developed, the `brand` tag took over, and the `name` tag became secondary in certain circumstances (such as this) as it was a uniquely named item even when the brand was the same.

This is where `preserveTags` comes in, to try and cater to both scenarios, but it does require third party data users to make use of the tag, as the NSI is just a dataset.

**Comment by siiky** [comment]
That is still besides the point... If I'm adding a new feature to the map, it doesn't have a `name` tag, so I don't see how `preserveTags` could possibly help.

The point is that adding `name=Galp` to a `brand=Galp` fuel station is **likely** to be wrong (at least in Portugal). Therefore, the `name` tag should be inserted by the mapper instead, consciously, not by default! See the "My Super Fuel Station" example above.

**Comment by bhousel** [comment]
Ok I removed the name.  I think this is weird, but if it's what you want, whatever. 🤷
