### ISSUE TITLE
Restrict ATAP (Pordenone) area

### ISSUE THREAD

**Issue by ivanbranco** [osmlab/name-suggestion-index#7378]
Hi,

[ATAP (Pordenone) entry](https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=atap#atap-ba987e) is creating some false positives in the Piedmont region, where we have a transit bus company with the same name: https://www.atapspa.it/

Would it possible to restrict the ATAP (Pordenone) area to the Friuli-Venezia Giulia region ([OSM relation](https://www.openstreetmap.org/relation/179296))?

**Comment by UKChris-osm** [comment]
Thanks @ivanbranco - all done!
