### ISSUE TITLE
Can't we do a "npm run build" after each merge request

### ISSUE THREAD

**Issue by bmillemathias** [osmlab/name-suggestion-index#7383]
Hello,

just asking if something prevent to run a "npm run build" and commit the result in the repository ?
I don't know if it makes sense and how difficult is it.

**Comment by bhousel** [comment]
Sort of - there is a Github Action already that runs the npm build and test scripts on every commit, and you can see its results:
https://github.com/osmlab/name-suggestion-index/actions/workflows/test.yml

Also if the build does start failing, the badge on our main README will turn red:
<img width="400" alt="Screen Shot 2022-11-11 at 11 26 37 AM" src="https://user-images.githubusercontent.com/38784/201385659-fae35d7f-9967-41f4-92b6-1fd5d420ac68.png">

**Comment by Dimitar5555** [comment]
Would it be possible to autmatically run it daily or once every other day if the last commit passed all tests?

**Comment by UKChris-osm** [comment]
A GitHub action currently runs when a commit is made, and as @bhousel has mentioned `npm run build` is run as part of this commit.

I'm guessing, however, that you're both interested in the part that adds an `id` to each new entry if one isn't present?

**Comment by Dimitar5555** [comment]
> I'm guessing, however, that you're both interested in the part that adds an `id` to each new entry if one isn't present?

It certainly does something but the changes are not propagated to iD until someone runs `npm run build` as far as I have seen.

**Comment by UKChris-osm** [comment]
> It certainly does something but the changes are not propagated to iD until someone runs `npm run build` as far as I have seen.

`npm run build` only checks the data and does some tidying up, it doesn't make the data available in iD. This is only done when a new release is done, such as with [8c1cd17](https://github.com/osmlab/name-suggestion-index/commit/8c1cd176bae845774c8a393630c9efd1377d31bd).

**Comment by arch0345** [comment]
id-tagging-schema has a GitHub Action that does this, maybe this can also be added to NSI:
https://github.com/openstreetmap/id-tagging-schema/blob/main/.github/workflows/deploy.yml

**Comment by bmillemathias** [comment]
Hello,

Sorry, I was AFK after I created the question.
The reason I asked the question, is often I see MR where people did not run `npm run build` before submitting their patch, and after when someone does a `npm run build` he/she gets a lot of changes induced by the command, before it formats properly the json files (and incidentally change some ids.) 

Best

**Comment by bhousel** [comment]
> The reason I asked the question, is often I see MR where people did not run `npm run build` before submitting their patch, and after when someone does a `npm run build` he/she gets a lot of changes induced by the command, before it formats properly the json files (and incidentally change some ids.)

Isn't this ok?  I don't expect people to be running builds if they are just casual contributors, and sometimes I'll just change 5 things and then run the build later.  

I just don't see this as a problem that needs to be solved by introducing a new automation that we need to maintain.  All the other projects I've seen that have this kind of "run the build for me and commit the results" causes way more problems than it solves.
