### ISSUE TITLE
Three different タイムズ

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#7392]
https://github.com/osmlab/name-suggestion-index/blob/4ed6d3cfbb6476f1eede70e49905b83d70b22cfd/data/operators/amenity/car_sharing.json#L667-L676

https://github.com/osmlab/name-suggestion-index/blob/4ed6d3cfbb6476f1eede70e49905b83d70b22cfd/data/operators/amenity/car_sharing.json#L677-L686

https://github.com/osmlab/name-suggestion-index/blob/4ed6d3cfbb6476f1eede70e49905b83d70b22cfd/data/operators/amenity/car_sharing.json#L687-L698

Which one should be kept?

**Comment by blendy-map** [comment]
Wikidata is not included, so it is difficult to judge, but there is a brand whose name has been changed from "タイムズカーシェア(Times Car Share)" to "タイムズカー(Times Car)[[Q17987881](https://www.wikidata.org/wiki/Q17987881)]".

**Comment by Revtro** [comment]
The last one is the most similar, so I think it would be best to keep it and change the name to タイムズカー(Times Car).

In April 2021, the name was changed from タイムズカーシェア(Times Car Share) to タイムズカー(Times Car).

**Comment by Revtro** [comment]
Also, this is the brand name of the service, not the name of the operating company, so it might be better to move it to brand.
