### ISSUE TITLE
Shell Gas Station, Shell and SHELL are the same

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#74]
`"amenity/fuel|SHELL"` and `"amenity/fuel|Shell Gas Station"` should be only `"amenity/fuel|Shell"` (while I don't agree that it should suggest such names at all #29)

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json). Besides, [brand and name](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel#Names) are semantically [different things](https://github.com/gravitystorm/openstreetmap-carto/issues/698).

**Comment by naoliv** [comment]
Already at [canonical.json](https://github.com/osmlab/name-suggestion-index/blob/master/canonical.json)
Sorry that I didn't look at the proper file.
