### ISSUE TITLE
Conflicting tags

### ISSUE THREAD

**Issue by brawer** [osmlab/name-suggestion-index#7400]
Some brands have conflicting rules in NSI. For example, there’s currently *two* rules matching `k kiosk`: one rule is tagging the stores as `shop=newsagent`, another one as `shop=kiosk`. Are such conflicting rules a problem that should perhaps be caught be some unit test? Or should clients be advised to merge conflicting tags with semicolons?

**Comment by brawer** [comment]
Hm, in real life, for this particular brand the stores are always identical. Is there a way in NSI to state that a certain brand’s stores should be tagged as `shop=kiosk;newsagent`?  Another example would be `Press & Books` whose stores sell books and newspapers/magazines — again, their shops all look the same, so probably users shouldn’t be forced to make a tagging decision for each store. Can NSI state tagging rules for `shop=books;newsagent`?

**Comment by UKChris-osm** [comment]
The NSI works alongside the existing tagging structures of OSM, and as OSM uses a single primary tag (such as [shop=books](url)), then so does the NSI.

While I agree that it would be great if there was an ability to tag multiple places using a primary tag, it isn't something the NSI can override.

Some tags do have an ability to tag multiple types within a primary tag, such as `shop=clothes` has a sub-tag for `clothes=men;women;children`

**Comment by Cj-Malone** [comment]
I tried to push for multi value top level tags in OSM a few years ago and it went nowhere. I don't want to demotivate you, but I doubt it'll go anywhere now.

However I think it's fairly likely the k kiosk example is wrong in NSI, either `shop=kiosk` or `shop=newsagent`, but not both. I have no knowledge of k kiosk though, so just a guess.

**Comment by kjonosm** [comment]
There was a similar question a while ago about Yorma's in https://github.com/osmlab/name-suggestion-index/issues/4212#issuecomment-700834346 where we settled on keeping both options in the NSI to let the mappers decide on what tag to choose. I think this probably also makes sense here because depending on the layout and size of each store, mappers might tend to one option or the other...

**Comment by brawer** [comment]
Thanks for the kind feedback! I’ve asked on the Swiss OSM mailing list (where the local community hangs out) if there’s consensus how `k kiosk` and `Press & Books` should be tagged. Depending on the outcome of that discussion, I’ll either leave it as-is, or send a pull request for clean-up. In any case, it seems it’s actually not a bug in NSI when multiple rules match with conflicting tagging suggestions; thanks for having explained this to me!
