### ISSUE TITLE
O Boticário

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7434]
Please include more countries to this brand. 
In addition to Brazil, add Portugal, Venezuela, Paraguay, Colombia, Mozambique, Angola, Saudi Arabia, Japan and the United States

**Comment by LaoshuBaby** [comment]
Hello, @DiogoBaptista98 

You open this issue blank and only have a title "O Boticário", do you means this entry in NSI?

https://github.com/osmlab/name-suggestion-index/blob/790bffbf40635e23f808d8b21e201f7f1d0b881a/data/brands/shop/perfumery.json#L166-L176

Is there anything wrong or need to be changed? If nothing reply I'll close this issue after 1 week.
