### ISSUE TITLE
Rituals

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7435]
Please add this brand
https://www.wikidata.org/wiki/Q85308254

Rituals operates in more than 807 stores, 2700 shop-in-shops across 33 countries
Andorra, Austria, Bahrain, Belgium, Bulgaria, Croatia, Curaçao, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hong Kong, Hungary, Ireland, Italy, Kuwait, Latvia, Lithuania, Luxembourg, Netherlands, Norway, Oman, Poland, Portugal, Qatar, Romania, Saudi Arabia, Serbia, Slovakia, Spain, Sweden, Switzerland, United Arab Emirates, United Kingdom, United States of America

https://github.com/osmlab/name-suggestion-index/blob/0ec9f5b9da9fef1ea70a292748a448cf31eb7e1a/data/brands/shop/cosmetics.json#L435-L455

**Comment by DiogoBaptista98** [comment]
There are more countries that need to be added.

**Comment by DnaX** [comment]
Already present in NSI: [rituals-6bd843](https://nsi.guide/?id=rituals-6bd843)

Wikidata item: https://www.wikidata.org/wiki/Q62874140
