### ISSUE TITLE
Add Chicco

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7441]
Please add this brand as shop=baby_goods
Chicco is present in over 120 countries, with more than 150 shops in Italy and another 160 throughout the world. 
https://www.wikidata.org/wiki/Q27897515

**Comment by DnaX** [comment]
Suggested tagging:

```
shop=baby_goods
name=Chicco
brand=Chicco
brand:wikidata=Q27897515
```

**Comment by DiogoBaptista98** [comment]
> Suggested tagging:
> 
> ```
> shop=baby_goods
> name=Chicco
> brand=Chicco
> brand:wikidata=Q27897515
> ```

Agree
