### ISSUE TITLE
Add countries to Bimba y Lola

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7446]
Please add the following countries to the brand Bimba y Lola
Austria, Belgium, Bulgaria, Chile, Colombia, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Mexico, Monaco, Netherlands, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, Sweden, UK

**Comment by DnaX** [comment]
Some bits: https://nsi.guide/?id=bimbaylola-9e078d

@DiogoBaptista98 makes sense to add it worldwide `{"include":["001"]}`?
