### ISSUE TITLE
Add L'Occitane

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#7449]
Worldwide brand https://www.wikidata.org/wiki/Q1880676

**Comment by DnaX** [comment]
Already present: [loccitane-a08666](https://nsi.guide/?id=loccitane-a08666)

Please, check if the propery "OSM Name Suggestion Index identifier" [P8253](https://www.wikidata.org/wiki/Property:P8253) is present before fill new bug reports.

**Comment by DiogoBaptista98** [comment]
I couldn't find it in the initial search, sorry

> Already present: [loccitane-a08666](https://nsi.guide/?id=loccitane-a08666)
> 
> Please, check if the propery "OSM Name Suggestion Index identifier" [P8253](https://www.wikidata.org/wiki/Property:P8253) is present before fill new bug reports.

**Comment by DiogoBaptista98** [comment]
We can close this issue, thank you!
