### ISSUE TITLE
Add Romanian telecommunication operator Digi

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7454]
Digi (brand of RCS&RDS) is one of the main Romanian mobile, internet and cable TV provider. It has reveral point of sales alone and into malls.

In Spain and Italy seems doesn't have physical shops.

Even if it's selling some phones, I think it's better:

```
name=Digi
office=telecommunication
brand=Digi
brand:wikipedia=Q224710
```

than:

```
brand=Digi
brand:wikidata=Q224710
name=Digi
shop=mobile_phone
```

**Comment by Dimitar5555** [comment]
`office=telecommunication` is for the company's offices (where the general public is not allowed to enter). `shop=telecommunication` is the tag for the store fronts.

**Comment by DnaX** [comment]
Yes, ok for `shop=telecommunication`
