### ISSUE TITLE
Add Romanian operator of charging stations "Renovatio e-charge"

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7455]
Suggested tagging:

```
amenity=charging_station
brand=Renovatio e-charge
brand:wikidata=Q115409077
name=Renovatio e-charge
operator=Renovatio e-charge
operator:wikidata=Q115409077
```

**Comment by UKChris-osm** [comment]
Would this be more suitable as a `brand` or `operator` entry do you think @DnaX?

I don't see the need to include both if they both have the same data values!

**Comment by DnaX** [comment]
I followed the example of https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station&tt=enel%20x#enelx-bdf07e

Can be included only as operator for me.
