### ISSUE TITLE
Add Evie Charging networks

### ISSUE THREAD

**Issue by tastrax** [osmlab/name-suggestion-index#7487]
Hi Folks,

Any chance someone could add the Evie Charging network for Australia?
https://www.wikidata.org/wiki/Q105795220
https://goevie.com.au/

And

Electric Highway Tasmania (in Tasmania Only)
https://www.wikidata.org/wiki/Q105834331
https://electrichighwaytasmania.com.au/

**Comment by kjonosm** [comment]
@tastrax It's already in the index, see [here](https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station&tt=evie). Is there anything wrong or missing?

**Comment by tastrax** [comment]
Mmm - not sure why I missed that!
