### ISSUE TITLE
Improve Panda Express name matching

### ISSUE THREAD

**Issue by Adamant36** [osmlab/name-suggestion-index#7488]
There's a Chinese restaurant in my area called "Panda South Chinese Restaurant" that iD Editor is trying to upgrade to Panda Express just because it has the word panda in it since panda is currently a match name, which is clearly ridiculous. iD Editor shouldn't be trying to upgrade everything with the word "panda" to Panda Express restaurants. 

![Panda South](https://user-images.githubusercontent.com/30259065/205436197-b7a5432e-817f-4a39-891b-a0b0dbed93c4.jpg)

**Comment by kjonosm** [comment]
I agree, thanks @Adamant36
