### ISSUE TITLE
UDON restaurants

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#7498]
Whilst travelling in Spain I stumbled upon the Spanish brand UDON that has a lot of restaurants: https://www.udon.com/restaurantes/

It should be tagged as a Japanese restaurant ie

```
amenity=restaurant
name=UDON
cuisine=japanese
```

**Comment by codeinabox** [comment]
I've added the Wikidata for the brand https://www.wikidata.org/wiki/Q115679798

**Comment by paunofu** [comment]
Commit a pull request to include #7557
