### ISSUE TITLE
Remove "amenity/bar|Bar" and "amenity/pub|Bar"

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#75]
"Bar" is clearly a generic name for `amenity=bar` and `amenity=pub`, and shouldn't be suggested

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json).

**Comment by naoliv** [comment]
Seems to be already at [filter.json](https://github.com/osmlab/name-suggestion-index/blob/master/filter.json)
My bad that I look at the wrong file.
