### ISSUE TITLE
Bug: Incorrect tag suggestions for gas stations

### ISSUE THREAD

**Issue by k-yle** [osmlab/name-suggestion-index#7508]
These two gas station copmanies have the same `operator`  tags, but different `brand` tags.  iD is suggesting all [BP stations](https://github.com/osmlab/name-suggestion-index/blob/1640b2b/data/brands/amenity/fuel.json#L779-L790) should be upgraded to [RD Petroleum](https://github.com/osmlab/name-suggestion-index/blob/1640b2b/data/brands/amenity/fuel.json#L3906-L3919). This is definitely wrong.

[OSM Feature](https://osm.org/way/339070623).

![image](https://user-images.githubusercontent.com/16009897/206130345-6de492ce-241f-4b4f-8401-5b4c485e43c3.png)

**Comment by Dimitar5555** [comment]
I think that it should be resolved if we add a separate NZ entry for BP and add these tags to it:
```
operator=BP
operator:wikidata=Q152057
```
