### ISSUE TITLE
Please Add Home Run Inn Pizza

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#7534]
https://en.wikipedia.org/wiki/Home_Run_Inn

**Comment by DnaX** [comment]
Proposed tagging:

```
name=Home Run Inn
brand=Home Run Inn
brand:wikidata=Q16995746
amenity=restaurant
cuisine=pizza
```

**Comment by Zol87** [comment]
Looks good, How about

name=Home Run Inn Pizzeria
brand=Home Run Inn
brand:wikidata=Q16995746
amenity=restaurant
cuisine=pizza
