### ISSUE TITLE
EV Chargers - 'Named chargers'

### ISSUE THREAD

**Issue by tastrax** [osmlab/name-suggestion-index#7545]
Example - Adding a Tesla supercharger or destination charger and it gets 'named' (Tesla Supercharger or Tesla Destination Charger). This seems to be wrong according to both

https://wiki.openstreetmap.org/wiki/Key:name

and 

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station

in reality very few, if any, charging stations have 'names'. This seems to be tagging for the renderer. I suggest name be removed from all EV charging stations as its more likely the 'names' should either be brand, operator or network.

**Comment by bhousel** [comment]
Last time we considered this topic was #4985, and the research turned up that several brands (including Tesla Supercharger) do assign their charging stations unique names.

Where we left things was:  I added `"preserveTags": ["^name"]` to the charging station category.  This will allow the `name` tag as an initial value, but users are encouraged to change it, and NSI will not overwrite the custom names that people add.

**Comment by tastrax** [comment]
Trouble is that people seldom add anything to the default name so you end up with heaps of non unique records which just duplicates the Brand (and sometimes the network and operator as well)

**Comment by bhousel** [comment]
This does come up for discussion sometimes , like #5338 and #7236
On that #7236 one, the person even tried manipulating their screenshot, so I hope you understand that we like to move slowly on issues like this and do some research.

We have found on #4985 that some charging stations have unique names, so I still think that seeding the value with a name and letting users change it is the right thing to do.

> Trouble is that people seldom add anything to the default name so you end up with heaps of non unique records which just duplicates the Brand (and sometimes the network and operator as well)

Why does this matter though?

**Comment by tastrax** [comment]
For me its about the value of the name and the consistency of its application across all charge points. Its not applied to all charging_points and in many, maybe most cases, it adds little value over the brand. Its often just the brand and location  which is generally obvious. It just looks like tagging for the renderer to me so maybe that's also an issue that could be handled by carto in using the brand as label rather than name.

**Comment by Adamant36** [comment]
> Its not applied to all charging_points and in many, maybe most cases, it adds little value over the brand.

I've seen Tesla charging points in California that say "Tesla" in big letters on top of them. The cars are named Tesla, the company is named Tesla, the chargers say Tesla. Drawing an arbitrary line at the chargers just seems a little weird. Do you really think having that in the name field would have no value what-so-ever? Or for that matter that people even get the distinction between the name and the brand in case like this to begin with?

**Comment by tastrax** [comment]
Likewise other brands - what I am seeking is some consistency in application from NSI.

**Comment by Adamant36** [comment]
> what I am seeking is some consistency in application from NSI.

Doesn't it consistently seed the value with a name and then let users change it if they want to? Honestly I don't map many charging stations myself, but I assume it would be an across the board exception that would apply to all charging stations.

**Comment by tastrax** [comment]
No it doesn't and that's what I am trying to seek some clarity/consistency on because it seems few get edited beyond the default (which is often the same as brand or operator). It just seems to be tagging for the renderer.

https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/charging_station.json 
https://github.com/osmlab/name-suggestion-index/blob/main/data/operators/amenity/charging_station.json

**Comment by Adamant36** [comment]
> Few get edited beyond the default

But it still constantly has a default. That's the important thing 😉 No one is obligated to provide more details for something or change the defaults if they don't want to. So I don't really see what the issue here is. 

> It just seems to be tagging for the renderer.

You've said that several times now but how exactly is it tagging for the renderer when the charging stations, at least in Tesla's case, say Tesla on them? Like I asked you already and I don't see an answer to, do you really think people even get the distinction between the name and the brand in these cases? 

Like look at this way, say a Tesla charger says Tesla in big red letters on it. Either the preset will add "Tesla" in the name tag by default or I will add it myself when I see that the charger says "Tesla" on it. Why is one inherently tagging for the rendering and the other isn't? 

I don't know the exact numbers but there's like 2000 uses of name=Tesla. You can claim few get edited beyond the default and it's questionable that's the case, but assuming it is maybe that's the case because default is correct. Which is why no one changing it. Your approach to this seems to be "default bad and my evidence is that everyone goes with the default." Which just seems backwards.

**Comment by tastrax** [comment]
So why do only some charge stations get the 'default name' when most are 'branded' in some way? It seems to have only been applied to a few. I am just seeking clarity/consistency (and I am fan of Tesla so its not an issue against Tesla)

**Comment by Adamant36** [comment]
"I am just seeking clarity/consistency" 

I'm aware that'a what your doing. I think things have been clarified though. At least on a baaic enough level for to feel comftrable closing this as "Won't fix." At least for it's  going to be hard for this to be clarified beyond what it has if you even answer the can't basic clairifying questions that I've asked you. For instance how is it tagging for the rendering. I'm not the one claiming it is, you are. So it's not my thing to clarify. It's yours to if you think that's what is is. Anyway, there are specific presets that do or don't have a default where you think its wrong I'm sure they can dealt with by opening an issue about those specific chargers. No one here is for tagging for the rendering.

**Comment by kjonosm** [comment]
In context of a consistent approach to "unnamed" features, also see #7236
