### ISSUE TITLE
Blank screen when trying to view bus routes on nsi.guide

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#7552]
When I try to view train or bus routes on https://nsi.guide/index.html?t=transit I get a blank screen.
(Safari 16.6, macOS 12.5)

**Comment by UKChris-osm** [comment]
It seems the script is trying to run the `replaceAll();` function even after looping through all of the entries has been completed in this case, thus causing it to run on a variable with a value of `null`, but I'm not sure why.
