### ISSUE TITLE
Add Bank and ATM brands of Kazakhstan

### ISSUE THREAD

**Issue by contactobscurantist** [osmlab/name-suggestion-index#7571]
Please add the following brand entries for kz-region banks and atms:

Freedom Finance Bank
```
name=Freedom Bank
name:ru=Фридом Банк
official_name:ru=АО «Банк Фридом Финанс Казахстан»
official_name:kk=«Банк Фридом Финанс Қазақстан» АҚ
brand=Freedom Bank
brand:wikidata=Q21843099
```
---

Eurasian Bank
```
brand=Eurasian Bank
name=Eurasian Bank
name:ru=Евразийский банк
name:kk=Еуразиялық банк
official_name=Eurasian Bank JSC
official_name:ru=АО «Евразийский Банк»
official_name:kk=«Еуразиялық банк» АҚ
brand:wikidata=Q143852
```
---

Nurbank
```
brand=Nurbank
name=Nurbank
name:ru=Нурбанк
name:kk=Нұрбанк
official_name=Nurbank JSC
official_name:ru=АО «Нурбанк»
official_name:kk=«Нұрбанк» АҚ
brand:wikidata=Q1638772
```
---

CenterCredit
```
АО "Банк ЦентрКредит" 
brand=Bank CenterCredit
name=Bank CenterCredit
name:ru=Банк ЦентрКредит
name:kk=Банк ЦентрКредит
official_name=Bank CenterCredit JSC
official_name:ru=АО «Банк ЦентрКредит»
official_name:kk=«Банк ЦентрКредит» АҚ
```
(matchName:bcc,бцк,альфа,альфа-банк)

---

Bank RBK
```
brand=Bank RBK
name=Bank RBK
name:ru=Банк РБК
name:kk=РБК Банкі
official_name:ru=АО «Bank RBK»
official_name:kk=«Bank RBK» АҚ
```

---

Zaman Bank
```
name=Zaman-Bank
name:ru=Заман-Банк
name:kk=Заман-Банк
brand=Zaman-Bank
brand:wikidata=Q4185641
official_name=Islamic Bank “Zaman-Bank” JSC
official_name:ru=АО «Исламский банк «Заман-Банк»
official_name:kk=«Заман-Банк «Ислам банкі» АҚ
```

Thanks!

**Comment by Dimitar5555** [comment]
The Kazakh language seems to use Cyrillic as it's main alphabet. Are you sure that all of these banks' names are spelt in Latin on their signs and websites?

**Comment by contactobscurantist** [comment]
Absolutely - you can check the websites to see that main branding is done in latin, regardless of user's language preferences:
[Freedom Bank](https://bankffin.kz/); [Eurasian Bank](https://eubank.kz/); [Nurbank](https://nurbank.kz/); [BCC](https://www.bcc.kz/); [Bank RBK](https://bankrbk.kz); [Zaman](https://www.zamanbank.kz/).

I believe this is done both in commercial interests (brand recognition, stock listing, etc), and to prepare for country's planned switch to latin alphabet.

**Comment by Dimitar5555** [comment]
I was not aware that Kazakhstan is planning to switch to the Latin alphabet. Thanks for letting me know. I've added all banks that you've mentioned in https://github.com/osmlab/name-suggestion-index/commit/6caeaea6dbe152631ae079ff727d2ba85b8dbc5b.
