### ISSUE TITLE
Please Add Illinois Appellate Courts

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#7574]
https://en.wikipedia.org/wiki/Supreme_Court_of_Illinois#Districts
https://www.illinoiscourts.gov/courts/appellate-court/

**Comment by arch0345** [comment]
As mentioned in https://github.com/osmlab/name-suggestion-index/issues/7575#issuecomment-1446411096, adding these districts isn't feasible as each district only operates one courthouse.
