### ISSUE TITLE
Add banks in Georgia

### ISSUE THREAD

**Issue by Karthoo** [osmlab/name-suggestion-index#7602]
I noticed that banks and atms in the country of Georgia are still missing in the NSI. The four biggest banks are:

- [ ] [ლიბერთი ბანკი (Liberty Bank)](https://www.wikidata.org/wiki/Q6541585) 
- [ ] [თიბისი ბანკი (TBC Bank)](https://www.wikidata.org/wiki/Q2620975) 
- [ ] [საქართველოს ბანკი (Bank of Georgia)](https://www.wikidata.org/wiki/Q2469733)
- [ ] [ბაზისბანკი (Basisbank)](https://www.wikidata.org/wiki/Q16365625)

They should all be added with Georgian and English name.

**Comment by LaoshuBaby** [comment]
> They should all be added with Georgian and English name.

I haven't found Georgia in [Multilingual names](https://wiki.openstreetmap.org/wiki/Multilingual_names), but according to [WikiProject Georgia Abkhazia South-Ossetia](https://wiki.openstreetmap.org/wiki/WikiProject_Georgia_Abkhazia_South-Ossetia), name in Georgia should use Georgian only, not bilingual, and English name should only in `name:en`:

![图片](https://user-images.githubusercontent.com/42690037/210199092-5c4b606a-26a2-4d91-b7fc-24b4704f307d.png)

I'll add them in my spare time.

**Comment by Karthoo** [comment]
Thank you!

> English name should only in name:en

That is what I meant 👍 I just explicitly mentioned it, because usually the Georgian and the English name both are signposted outside the branches.
