### ISSUE TITLE
EG Australia

### ISSUE THREAD

**Issue by gyCfjSnO** [osmlab/name-suggestion-index#7611]
I am suggesting and requesting that `EG Australia` be added onto the index list.

EG Australia operates petrol stations in Australia and sell Ampol fuel (Like how 7-Eleven operates by selling Mobil fuel).

The receipts provided when purchasing fuel at EG branded outlets have the word `EG Fuelco (Australia) Limited` across the top.

The business number that is found on the receipt brings back the same name `EG FUELCO (AUSTRALIA) LIMITED` when searching online.

[Link to the receipt](https://i.imgur.com/mmV4NKV.jpg)
[Link to the business number search](https://abr.business.gov.au/ABN/View?abn=39627348645)

Prompt resolution of this matter would be muchly appreciated.

**Comment by UKChris-osm** [comment]
Did EG used to be branded as [Woolworths Petrol](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=ampol#woolworthspetrol-9ed9c0)?

**Comment by UKChris-osm** [comment]
#7636
