### ISSUE TITLE
Public transport network IJssel-Vecht points to an incorrect Wikidata page

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#7618]
The [ijsselvecht-2f3200](https://nsi.guide/?t=transit&k=route&v=bus#ijsselvecht-2f3200) and [ijsselvecht-0af83a](https://nsi.guide/?t=transit&k=highway&v=bus_stop#ijsselvecht-0af83a) point to [Q108721383](https://www.wikidata.org/wiki/Q108721383). This is the old network (2020-2022). The new network since 10 December 2022 is [Q115122853](https://www.wikidata.org/wiki/Q115122853) (2023-2025). 

This has resulted in iD-editors reverting the tag network:wikidata to the obsolete network.

Could this be corrected? Thanks in advance.

**Comment by A67-A67** [comment]
It seems to be corrected by https://github.com/osmlab/name-suggestion-index/pull/7626

**Comment by Cj-Malone** [comment]
I'm going to close the issue then. Let us know if there is still an issue after the next release on Sunday.
