### ISSUE TITLE
Add smart bus (Bangkok) Bus Network

### ISSUE THREAD

**Issue by OumKaZa** [osmlab/name-suggestion-index#7620]
network=smart bus
network:wikidata=Q116101493
route=bus

Wikidata Name/Description

smart bus
[Q116101493](https://www.wikidata.org/wiki/Q116101493)

Social Links - Facebook: https://www.facebook.com/smartbusthai

**Comment by UKChris-osm** [comment]
This seems to already exist via [smartbus-43cc75](https://nsi.guide/index.html?t=transit&k=route&v=bus&tt=smart#smartbus-43cc75)
