### ISSUE TITLE
Post Boxes suggesting brand as Post Office instead of Royal Mail

### ISSUE THREAD

**Issue by tyrasd** [osmlab/name-suggestion-index#7660]
1544697a292cbd0b6825b5f32c2e5d21c5359783 introduced the following regression: https://github.com/openstreetmap/id-tagging-schema/issues/738

> When editing a postbox with the brand "Royal Mail", eg https://www.openstreetmap.org/node/624633219
> It suggests the following edit, which I believe is entirely incorrect
> 
> Some features, for example retail chains or post offices, are expected to have certain tags in common.
> Suggested updates:
> ```
> - brand=Royal Mail
> + brand=Post Office
> - brand:wikidata=Q638098
> + brand:wikidata=Q1783168
> - operator=Royal Mail
> + operator=Post Office
> - operator:wikidata=Q638098
> + operator:wikidata=Q1783168
> ```
> 
> The Post Office operate shops where you can send letters and a lot more
> The postal network is operated by Royal Mail. Post boxes are operated by Royal Mail
> 
> They are two serate brands and have different ownership.
> 
> To Reproduce
> Edit any postbox in the UK with Royal Mail brand / operator tags set
> 
> Expected behavior
> Suggests Royal Mail brand tags if not completely set. Should not suggest Post Office

in short: Currently , all "Royal Mail" post boxes in the UK are falsely converted to ["Post Office" (Q1783168)](https://nsi.guide/index.html?t=operators&k=amenity&v=post_box&tt=post#postoffice-f65bfd) mail boxes. This is because the the nsi entry for "Post Office" post offices now includes "Royal Mail" in its `matchNames` and the fact the `post_box` template is cloning this over from the `post_office` entry into the `post_box` items. I think 1544697a292cbd0b6825b5f32c2e5d21c5359783 should have introduced a dedicated entry for UK "Royal Mail" post boxes after removing the entry for "Royal Mail" post offices.

**Comment by UKChris-osm** [comment]
Oh dear, I am sorry. I hadn't realised the template data for the operator section came from the brand section.

**Comment by UKChris-osm** [comment]
@arch0345 is there any chance of a fresh release to amend my error?

**Comment by arch0345** [comment]
Just released [`v6.0.20230117`](https://www.npmjs.com/package/name-suggestion-index?activeTab=versions)
