### ISSUE TITLE
Wikidata script adds irrelevant instance of statements

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#7661]
I noticed from the last run of `npm run wikidata` that the script added `instance of organization` to the [transgender Wikidata item](https://www.wikidata.org/w/index.php?title=Q189125&direction=prev&oldid=1813146349). We currently have this QID as the `subject:wikidata` for the transgender pride flag:

https://github.com/osmlab/name-suggestion-index/blob/0a3c9f74599f34bd60adc3e673d3eed3f967872e/data/flags/man_made/flagpole.json#L4359-L4378

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/212810361-4d0bdbef-7b22-48f4-a181-0ba9a9019964.png)

But there are only those 2 `Q43229` in script:

https://github.com/osmlab/name-suggestion-index/blob/4b263f86a23558c6b8699f426961bf5c36c1be24/scripts/build_wikidata.js#L180-L184

**Comment by bhousel** [comment]
Oh yeah that seems wrong.. Our script really shouldn't set an `instance of` claim here.. I'll take a look.
