### ISSUE TITLE
Correct tags and network tag for "臺鐵"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#7673]
Please correct the entry for Taiwan railway, which should should link to this Wikidata entry (Q697926) instead. English network value should also be changed to TRA (short for Taiwan Railways Administration) instead of the literal translation of the Chinese (臺鐵).

**Comment by UKChris-osm** [comment]
Hi @TagaSanPedroAko

[taiwanrailway-acc966](https://nsi.guide/index.html?t=transit&k=route&v=train&tt=Taiwan%20railway#taiwanrailway-acc966) seems to already include the Wikidata for [Q697926](https://www.wikidata.org/wiki/Q697926) as the `operator`, is this not correct?

**Comment by TagaSanPedroAko** [comment]
The operator is correct, but not the English value tag, and I'm seeing a different Wikidata for the network.

**Comment by bhousel** [comment]
I made the requested changes in fc8f58dac - hope it's correct now?
