### ISSUE TITLE
Remove "amenity/restaurant|Pizza"

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#77]
Most probably somebody is trying to say that the restaurant sells pizza, and not that the name is "Pizza"

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json).

**Comment by naoliv** [comment]
Seems to be already at [filter.json](https://github.com/osmlab/name-suggestion-index/blob/master/filter.json)
My bad that I look at the wrong file.
