### ISSUE TITLE
Duplicate Societé Génerale causing issues

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#7703]
Because of how Societé Génerale is set up, the Arabic tagged preset is being offered worldwide, and people are being prompted to "upgrade" the tags to include the Arabic ones.

<img width="200" alt="Screenshot 2023-01-25 at 2 39 17 PM" src="https://user-images.githubusercontent.com/38784/214671108-7e7fb18d-59a2-40d5-b282-cfa2328219af.png"><img width="240" alt="Screenshot 2023-01-25 at 2 40 27 PM" src="https://user-images.githubusercontent.com/38784/214671143-bb0e341c-0728-4b94-9b53-ed366bf7968f.png">

It looks like this commit introduced the duplicate: https://github.com/osmlab/name-suggestion-index/commit/ff50d966c5367c9bd7b2cae72d828b475796fcc5

Because it says `"locationSet": {"include": ["001"],"exclude": ["dz"]},` it will offer this preset everywhere in the world except for Algeria, which is probably not what we want - instead Arabic presets should just be scoped to a handful of countries where the Arabic tagging makes sense.

**Comment by kjonosm** [comment]
Is there a location set for countries using the Arabic alphabet?

**Comment by bhousel** [comment]
> Is there a "combined" location set for countries using the Arabic alphabet?

Nope, we'd just have to make it up.   
For McDonald's (the closest thing to a ubiquitous worldwide brand I can think of),
I see this, but there may be some missing.
https://github.com/osmlab/name-suggestion-index/blob/233690a6bd87c4d363af4fbfc65334bb5fa78984/data/brands/amenity/fast_food.json#L8634-L8652
