### ISSUE TITLE
Add City Electrical Factors - CEF

### ISSUE THREAD

**Issue by lukethemapper** [osmlab/name-suggestion-index#7710]
CEF (City Electrical Factors) - https://www.cef.co.uk/

**Comment by lukethemapper** [comment]
Trade shop I'd suppose as most customers are trade and account holders

**Comment by Cj-Malone** [comment]
@lukethemapper do you want to try and do it?

**Comment by lukethemapper** [comment]
How do you add them, and I'd have a go?

**Comment by Cj-Malone** [comment]
There is some details on the [wiki](https://github.com/osmlab/name-suggestion-index/wiki/Contributing), but basically you want to add an item to [this file](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/trade.json).

**Comment by peternewman** [comment]
Would it not be https://wiki.openstreetmap.org/wiki/Tag:shop%3Delectrical ? Which would match Rexel which appears to be in a similar vein:
https://github.com/osmlab/name-suggestion-index/blob/4d07c92457d0c7f2c1d1b6048228a8d6f37a90d8/data/brands/shop/electrical.json#L18-L54
