### ISSUE TITLE
[CH] Add 'Postomat'

### ISSUE THREAD

**Issue by habi** [osmlab/name-suggestion-index#7731]
A [Postomat](https://duckduckgo.com/?q=postomat+schweiz&t=ffab&iax=images&ia=images) is one of +800 `amenity=atm` in Switzerland, all (technically) with `operator:wikidata=Q449233`.

**Comment by UKChris-osm** [comment]
We don't currently have an operator tree for ATM's - would this fit in okay under the brand tree?

**Comment by habi** [comment]
After a very quick feedback loop in the Swiss OSM IRC I'd like to insist on `operator`, also because it's suggested on the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm).
