### ISSUE TITLE
Add VFS Global

### ISSUE THREAD

**Issue by arrival-spring** [osmlab/name-suggestion-index#7746]
VFS Global is a company that assists in getting visas. Some countries work exclusively with them (you can only get a visa through this company for that country).

I believe the correct tagging would be `office=visa` but this category does not exist. Can it be created?

On Wikidata at [Q7906873](https://www.wikidata.org/wiki/Q7906873)

**Comment by UKChris-osm** [comment]
This category can be created under the [/brands/office/](https://github.com/osmlab/name-suggestion-index/tree/main/data/brands/office) tree, all that it would need is its own JSON file, called visa.json

**Comment by UKChris-osm** [comment]
Another example of bad data - they have their London office mapped as being at a sewage treatment centre 👎

![vfs](https://user-images.githubusercontent.com/59393694/216761845-e800ed3a-c689-43cf-9537-6fecbe97fbc2.jpg)

**Comment by arrival-spring** [comment]
Thanks! I guess my question really was whether I could just create new files for categories (office/visa in this case) that didn't already exist, or whether there was any extra approval process.

**Comment by UKChris-osm** [comment]
> I guess my question really was whether I could just create new files for categories (office/visa in this case) that didn't already exist.

So long as the category exists within iD and OSM, then yes the only thing needed would be a new file. If a file was created that didn't match a category already in iD (such as nonexistentamenity.json) then this would be ignored, and possibly cause a build error.
