### ISSUE TITLE
Please add Babi (巴比馒头 in Chinese)

### ISSUE THREAD

**Issue by RicTimeMuseum** [osmlab/name-suggestion-index#7748]
Suggested OSM Tags includes: 

name=巴比馒头
name:zh=巴比馒头
name:en=Babi
shop=pastry
brand=巴比馒头
brand:zh=巴比馒头
brand:en=Babi
brand:wikidata=Q109413209
cuisine=chinese
diet:halal=no

Ref: 
https://zh.wikipedia.org/wiki/巴比饅頭
https://commons.wikimedia.org/wiki/Category:Babi_Mantou

**Comment by LaoshuBaby** [comment]
Thank you for letting us know, this is very valuable local knowledge, can't know by others unless they live near Shanghai.

Also, as a maintainer that have a Chinese background, I feel this is closer to the nature of "breakfast shop" and is not suitable for pastry

**Comment by RicTimeMuseum** [comment]
> Thank you for letting us know, this is very valuable local knowledge, can't know by others unless they live near Shanghai.
> 
> Also, as a maintainer that have a Chinese background, I feel this is closer to the nature of "breakfast shop" and is not suitable for pastry

Well, thanks a lot. 

However, I totally don't agree with "can't know by others unless they live near Shanghai" as you said. For example, there're at least 12 branches in urban Huizhou City (惠州市), where is quite far away from SH, and an example was shown in the Wikimedia Commons category. 

All in all, thanks for processing my request.

**Comment by LaoshuBaby** [comment]
> Well, thanks a lot.
> 
> However, I totally don't agree with "can't know by others unless they live near Shanghai" as you said. For example, there're at least 12 branches in urban Huizhou City (惠州市), where is quite far away from SH, and an example was shown in the Wikimedia Commons category.

Yes, but at least it only appears in some provinces, it's my words that are not precise enough

_(BTW, we are sorry for the geojson of the provinces in Mainland of China has not yet been provided, so even in Heilongjiang or Hainan, this preset will still take effect for a breakfast shop named "Babi Mantou")_

**Comment by RicTimeMuseum** [comment]
> Yes, but at least it only appears in some provinces, it's my words that are not precise enough
> 
> _(BTW, we are sorry for the geojson of the provinces in Mainland of China has not yet been provided, so even in Heilongjiang or Hainan, this preset will still take effect for a breakfast shop named "Babi Mantou")

OK, got it. 

And it seems that the value to the key "id" on line 10642 has not been changed yet, it still remains "mcdonalds".

**Comment by LaoshuBaby** [comment]
> And it seems that the value to the key "id" on line 10642 has not been changed yet, it still remains "mcdonalds".

https://github.com/osmlab/name-suggestion-index/commit/d87ece53c78bc462e4b63deec810d7b3810cb2eb

This can be re-generated by a build script run and I've done it because several PR was merged.

We have a [checklist](https://github.com/osmlab/name-suggestion-index/wiki/Release-Checklist) before publish a weekly(usually) new version. (And this can be done semi-automatically, so don't worry)

**Comment by RicTimeMuseum** [comment]
> This can be re-generated by a build script run and I've done it because several PR was merged.
> 
> We have a [checklist](https://github.com/osmlab/name-suggestion-index/wiki/Release-Checklist) before publish a weekly(usually) new version. (And this can be done semi-automatically, so don't worry)

OK, got it.
