### ISSUE TITLE
Consider remove Twitter API call in build script?

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#7750]
Twitter Dev announced that they will charge a large amount of money from developer since February 9, and in view of the series of reforms after Elon Musk took over Twitter, the Twitter API may become unstable, I recommend removing it from our build script:

https://github.com/osmlab/name-suggestion-index/blob/cc849d7d152e5f620fcc5410bbf9e82918fbfc1b/scripts/build_wikidata.js#L103-L129

Reference:
+ https://twitter.com/TwitterDev/status/1621026986784337922
+ https://twitter.com/elonmusk/status/1621259936524300289

(Hope 2.13 release won't be affected)

**Comment by arch0345** [comment]
I'll make a release today

We might be able to use [this scraper](https://apify.com/quacker/twitter-url-scraper) to fetch profile photos, but we should probably make sure using this doesn't violate the [automation rules](https://help.twitter.com/en/rules-and-policies/twitter-automation)

**Comment by bhousel** [comment]
Yeah I think I'm pretty ok with just dropping Twitter if their change introduce even the smallest amount of friction or cost.  
At this point most of the brand logos can be fetched from Facebook API or Wikimedia Commons.

**Comment by arch0345** [comment]
It looks like the date has been extended to February 13th so I'll wait until the 12th for the next release:
https://twitter.com/TwitterDev/status/1623467615539859456

**Comment by UKChris-osm** [comment]
https://twitter.com/TwitterDev/status/1623467618400374784 seems to imply a possible free tier that might still be usable?

> At this point most of the brand logos can be fetched from Facebook API or Wikimedia Commons.

Could Instagram profiles also be an option, even if via the Facebook API itself? I have seen a few brands that only have an Instagram account, or have an open Instagram account compared to their "log in" Facebook profile.

**Comment by bhousel** [comment]
I got the notices from Twitter last night that they are cutting back their API access.
According to the new terms it seems that we can use a single key on the "free" plan, or a few keys for "basic" plan which is $100/month.   So I'm just going to remove Twitter. 

<img width="1123" alt="Screenshot 2023-04-27 at 9 32 08 AM" src="https://user-images.githubusercontent.com/38784/234878238-2534c961-9ec1-4764-bffc-83cc21ed2bb9.png">
