### ISSUE TITLE
Add FastBreak

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#7759]
https://www.myfastbreak.com/locations

**Comment by Cj-Malone** [comment]
https://www.wikidata.org/wiki/Q116731804

**Comment by UKChris-osm** [comment]
I'm seeing a couple stores in California as well.

![fastbreak](https://user-images.githubusercontent.com/59393694/218308986-a52fef67-08c7-4aec-b608-9a9c6fcddac9.png)
