### ISSUE TITLE
New preset

### ISSUE THREAD

**Issue by Zavgor1990** [osmlab/name-suggestion-index#7762]
Hi.
Can you add new preset for POI: office=property_management, please?

**Comment by Dimitar5555** [comment]
There is a preset for it (see https://github.com/openstreetmap/id-tagging-schema/pull/622). I assume that you want to add brand/operator tagging for `office=property_management`. If so, feel free to provide the names and Wikidata items for them.

**Comment by UKChris-osm** [comment]
Hi @Zavgor1990

Each category needs at least one brand / operator in it before we can create a file for it, otherwise it may generate a build error.

Do you have any particular brands in mind?
