### ISSUE TITLE
Add italian shoes stores chain "Primadonna"

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7773]
"Primadonna" is an Italian chain of women's footwear stores with stores in France, Spain, Luxembourg and Switzerland.

See here: https://www.primadonnacollection.com/

Proposed tagging:

```
shop=shoes
name=Primadonna
brand=Primadonna
brand:wikidata=Q116774671
shoes=women
```

**Comment by DnaX** [comment]
@UKChris-osm  There is a mistake with the commit:

```
"shoes": "children",
"shop": "women"
```

Should be:

```
"shoes": "women",
"shop": "shoes"
```

**Comment by UKChris-osm** [comment]
`shop=shoes` seems to be correct already but I have corrected `shoes=women`
