### ISSUE TITLE
Add the Italian chain of sportswear stores "AW LAB"

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7774]
"AW LAB" is an Italian chain of sportswear stores in Italy and Spain

See here: https://en.aw-lab.com/awlab-franchising.html

Proposed tagging:

```
shop=clothes
name=AW LAB
brand=AW LAB
brand:wikidata=Q116774749
clothes=sports
shoes=sports
```

**Comment by Cj-Malone** [comment]
I'm not sure about the `shoes=sports`, otherwise looks good it me. Do you want to do a PR?

**Comment by Cj-Malone** [comment]
> Throughout Italy, AW LAB has a retail experience with 280 stores (200 Bata, 87 AW LAB/Athletes World) and in more than 30 years with franchising. 190 stores (105 Bata, 90 AW LAB/Athletes World). The year 2012 has witnessed the evolution of Athletes World into AW LAB, a true trend laboratory, which is presenting itself as Urban Style Refresher.

Maybe it should have a match name for "Athletes World" too

**Comment by DnaX** [comment]
Good point, thay renamed all the stores but maybe some of them are still with the old name.
