### ISSUE TITLE
Add Italian jewelry store chain "Stroili Oro"

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#7776]
"Stroili Oro" is an Italian chain of jewelry stores in Italy with more than 300 stores.

See here: https://www.stroilioro.com/it_IT/gioiellerie-stroili/ (italian)

Proposed tagging:

```
shop=jewelry
name=Stroili Oro
brand=Stroili Oro
brand:wikidata=Q106611306
```

**Comment by Cj-Malone** [comment]
"Stroili" or "Stroili Oro"?

**Comment by DnaX** [comment]
The shops are named "Stroili Oro". Look here: https://www.parcocommercialedora.it/negozi/stroili-oro/

**Comment by Cj-Malone** [comment]
Thank you
