### ISSUE TITLE
Add Two Hands fast food

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#7784]
name: Two Hands
full_name: Two Hands Fresh Corn Dogs
https://www.twohandsus.com/

**Comment by Cj-Malone** [comment]
https://www.wikidata.org/wiki/Q116817465

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this?

**Comment by UKChris-osm** [comment]
@Sheikh-JamirAlam you're certainly welcome to :)

**Comment by Sheikh-JamirAlam** [comment]
@UKChris-osm Can you just explain me where this [id](https://github.com/osmlab/name-suggestion-index/blob/f1dc6575d51f1d148712f645eec3bbd629454203/data/brands/amenity/fast_food.json#L47) is coming from?

**Comment by Cj-Malone** [comment]
You don't need to add an id when making a new entry.  One will get made automatically.

**Comment by UKChris-osm** [comment]
Would it be better to use the value "_corndog_", "_corn_dog_" or "_corn dog_" for the `cuisine` tag? OSM seems to use whole words or an underscore to represent a space.

**Comment by Sheikh-JamirAlam** [comment]
@UKChris-osm Changed it to _corn_dog_ , Does it work now?

**Comment by LaoshuBaby** [comment]
> Would it be better to use the value "_corndog_", "_corn_dog_" or "_corn dog_" for the `cuisine` tag? OSM seems to use whole words or an underscore to represent a space.

Similar situation of #5292, looks like space contained values were used more widely.

**Comment by UKChris-osm** [comment]
Thanks @Sheikh-JamirAlam - your edit should be live in a couple of days with the latest release 👍

**Comment by Sheikh-JamirAlam** [comment]
> Thanks @Sheikh-JamirAlam - your edit should be live in a couple of days with the latest release 👍 

Glad to know✨
