### ISSUE TITLE
Dialysis centers should use `healthcare:speciality=nephrology`

### ISSUE THREAD

**Issue by tyrasd** [osmlab/name-suggestion-index#7788]
… instead of `healthcare:speciality=dialysis` according to the OSM wiki: https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Ddialysis

See also https://github.com/openstreetmap/id-tagging-schema/pull/795#issuecomment-1435774412

**Comment by kjonosm** [comment]
NSI suggest `healthcare:speciality=dialysis` in some instances, see https://nsi.guide/index.html?t=operators&k=amenity&v=clinic&tt=dialysis

@tyrasd Should it be changed to `healthcare:speciality=nephrology`?

**Comment by tyrasd** [comment]
yes, that would be my proposal. It's only based on the wiki page above, which until [recently](https://wiki.openstreetmap.org/w/index.php?title=Tag:healthcare%3Ddialysis&diff=2258469&oldid=2137007) still suggested `healthcare:speciality=dialysis`.

**Comment by LaoshuBaby** [comment]
As my point of view, I think `specialty` should correspond to a series of disciplines (value can be `audiology`, `optometry` or others), and `dialysis` is a treatment method of `nephrology`, so later should be value.

Of course, this is limited to my understanding as an ordinary person. It would be better if a mapper with a medical education background can point out which value is more semantic

**Comment by 1ec5** [comment]
> As my point of view, I think `specialty` should correspond to a series of disciplines (value can be `audiology`, `optometry` or others), and `dialysis` is a treatment method of `nephrology`, so later should be value.

That’s true. What’s tricky, as I pointed out in https://github.com/openstreetmap/id-tagging-schema/pull/795#issuecomment-1435774412, is that these centers aren’t nephrology specialists per se. It would be better to avoid `healthcare:speciality` altogether in favor of `healthcare:service`, which is very popular in Norway for some reason, but that would require further discussion.
