### ISSUE TITLE
Need input for adding BYD Auto to car brands

### ISSUE THREAD

**Issue by mstsbe** [osmlab/name-suggestion-index#7804]
Dear all,

Normally I would just add a brand without discussion, but since this is a brand of global scale which has not been featured yet I thought it was first wise to consult the community.
In some markets Chinese auto-brands/automakers are already commonplace, but only since the whole electrification game they also start to appear in European or US/Canadian markets.

BYD (aka "Build Your Dreams") already was present in my country with their electric vans and buses, but now the first cars and own dealerships are appearing as well.
The question is: which Wikidata entry should we take ? BYD Auto ([Q27423](https://www.wikidata.org/wiki/Q27423)) seems the correct one, but some might argue it should be the parent company ([Q2608329](https://www.wikidata.org/wiki/Q2608329)).
Also for the locationset: can we just take 001 (the whole world) or should we still exclude several markets ?

We also might need help from a Chinese user for a seperate Chinese entry (with traditional or simplified Chinese spelling) I guess ? Someone did the same with NiO -> latin spelling version = https://nsi.guide/index.html?t=brands&k=shop&v=car#niohouse-465d1f
Chinese spelling/name -> https://nsi.guide/index.html?t=brands&k=shop&v=car#niohouse-115502

**Comment by UKChris-osm** [comment]
I would select BYD Auto rather than the parent company. Using 001 should be fine unless there are any specific clashes with other brands, or if you know that they trade only in a select few Countries.
