### ISSUE TITLE
Dutch chain cafe brand Bagels & Beans point to incorrect Wikidata page

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#7814]
The Dutch brand [Bagels & Beans](https://nsi.guide/?t=brands&k=amenity&v=cafe#bagelsandbeans-4a052f) points at [Q5140923](https://www.wikidata.org/wiki/Q5140923) (the British chain Coffee Republic) instead of the correct [Q13433690](https://www.wikidata.org/wiki/Q13433690).

**Comment by UKChris-osm** [comment]
That was strange, not sure why that was the case, but thank you for letting us know. 👍
