### ISSUE TITLE
"Wilco Farm Stores" preset in iD editor adds wrong tag

### ISSUE THREAD

**Issue by jmarchon1** [osmlab/name-suggestion-index#7816]
When selecting the "Wilco Farm Stores" preset in the iD editor, the tag shop=supermarket is added. [Wilco](https://en.wikipedia.org/wiki/Wilco_(farm_supply_cooperative)) is a brand of farm supply stores, which I would not say fits the definition of shop=supermarket. In my opinion, shop=agrarian would be more appropriate.

**Comment by arch0345** [comment]
Thanks for catching this @jmarchon1! The fix linked above should show up in iD/JOSM by next week
