### ISSUE TITLE
Add Capital Area Transit (Harrisburg, PA) 

### ISSUE THREAD

**Issue by biyak1** [osmlab/name-suggestion-index#7830]
Could the public transit network Capital Area Transit be added to the NSI? Thanks!

Wikidata=Q5035468
Wikipedia=Capital Area Transit (Harrisburg)

**Comment by UKChris-osm** [comment]
Hi @biyak1 

Is CAT now known as Rabbit Transit, or are both brands in use?

**Comment by biyak1** [comment]
CAT is a separate brand from Rabbit TransitOn Mar 4, 2023, at 6:48 AM, UKChris-osm ***@***.***> wrote:﻿
Hi @biyak1
Is CAT now known as Rabbit Transit, or are both brands in use?
