### ISSUE TITLE
Add Spain Autonomous Communities geoJSON to features

### ISSUE THREAD

**Issue by Robot8A** [osmlab/name-suggestion-index#7831]
Currently different brands with the same operator exist in Spain, leading to wrong suggestions in iD.

Examples of this are BiZi and bicing at amenity/bicycle_rental, and all the different Renfe services in transit.

Having different geoJSON files for the different regions would help aliviate some of the problems.

**Comment by Robot8A** [comment]
Fixed Trambahía popping up in other Renfe routes recommendation in: #7861

**Comment by bhousel** [comment]
closing, looks like this was done
