### ISSUE TITLE
Unrelated items being changed to pubs

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmlab/name-suggestion-index#7844]
(see related issues https://github.com/openstreetmap/iD/issues/9528 and https://github.com/openstreetmap/iD/issues/9529 elsewhere).

When I edit https://www.openstreetmap.org/node/3196433293/history (a cafe) iD suggests I change it to a pub.  I'm guessing that the culprit may be https://github.com/osmlab/name-suggestion-index/pull/7007 , but the data changes athttps://github.com/osmlab/name-suggestion-index/pull/7007/files don't actually look problematic (personally I'd have restricted the geographical area to where Robbie's operate, but that's not the issue here).

Is it really this NSI change that's causing the issue?  If not I'll happily raise this problem (guessing that cafes might actually be pubs) back over at iD if the problem is really at that end.

**Comment by bhousel** [comment]
> (personally I'd have restricted the geographical area to where Robbie's operate, but that's not the issue here).

It sounds like that is the issue here?
If you just restrict the Robbies brand to where it operates, iD will only make those suggestions within that geofence.

**Comment by SomeoneElseOSM** [comment]
> It sounds like that is the issue here? 

No, if someone called "Robinson" opened a cafe in Manchester then the incorrect suggestion would still be made.

**Comment by bhousel** [comment]
We could probably make this issue go away by making sure 'pub' and 'cafe' don't appear in the same matchgroup 🤔

There is a whole lot of overlap in what people consider a restaurant, but we could split the "food" group up into some smaller groups.

https://github.com/osmlab/name-suggestion-index/blob/53c3022257faa6bd62db22931e91cb555d70e068/config/matchGroups.json#L103-L108

**Comment by UKChris-osm** [comment]
I think that would be a good idea 👍

**Comment by SomeoneElseOSM** [comment]
> Would [gb-north-west.geojson](https://github.com/osmlab/name-suggestion-index/blob/main/features/gb/gb-north-west.geojson) and Wales be sufficient?

Robbie's territory extends a bit to the east of Buxton, so it'd need to extend a bit beyond "the northwest" in England, and I think Wales is just north Wales so that'd need similarly changing.  A fairly crude .poly or geojson would work for that though?

**Comment by UKChris-osm** [comment]
Yes the NSI supports custom geojson files for any area, so a basic inclusion zone would be fine, and the geojson file can be placed within the gb folder, under features.
