### ISSUE TITLE
A missing and an outdated Wikidata link for chain stores in the Netherlands

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#7849]
Hi,

The restaurant chain "De Beren" has an outdated Wikidata link after a merge on Wikidata: [NSI](https://nsi.guide/?t=brands&k=amenity&v=restaurant#deberen-2b67bf). Correct Wikidata: [Q57076079](https://www.wikidata.org/wiki/Q57076079)

The pet store chain "Pets Place" is missing its Wikidata link: [NSI](https://nsi.guide/?t=brands&k=shop&v=pet#petsplace-734485). Correct Wikidata: [Q116951772](https://www.wikidata.org/wiki/Q116951772)

Thanks in advance!

**Comment by Cj-Malone** [comment]
Do you want to try and fix these?
