### ISSUE TITLE
Sloppy copy-pasted brands in shop/clothing

### ISSUE THREAD

**Issue by mstsbe** [osmlab/name-suggestion-index#7885]
After submitting my own pull request to add a new clothing chain, I browsed the brand list for shop/clothing and noticed some sloppy copy-pasting of brands which have nothing to do with each other (except maybe if they share the same parent company, but it still remains a seperate **brand**)

Examples:
https://nsi.guide/index.html?t=brands&k=shop&v=clothes#hellyhansen-3937bd (uses the data from 7 for all Mankind, which was probably the top entry in the list back then).
The correct Wikidata entry is Q1603114.

https://nsi.guide/index.html?t=brands&k=shop&v=clothes#morgan-5bd015 (uses the data from Comptoir des Cotonniers).
Correct Wikidata entry: Q6911563

and sure there are many more.
Can we somehow automate/check this that the Wikidata entry roughly matches the brand ?

**Comment by bhousel** [comment]
closing, looks like this was fixed already
