### ISSUE TITLE
Australia Post post boxes

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#7891]
I've notice there is no `amenity=post_box` entry for Australia Post

**Comment by bhousel** [comment]
It looks like there should be one:
https://nsi.guide/index.html?t=operators&k=amenity&v=post_box#australiapost-7f3a8a

And I do see it suggested when editing in Australia:
<img width="387" alt="Screenshot 2023-03-20 at 11 26 18 AM" src="https://user-images.githubusercontent.com/38784/226388022-9413afe1-6131-4614-b6d3-ceefaacd3d59.png">

**Comment by codeinabox** [comment]
Ah you're right, I'll close this. I blame the jet lag
