### ISSUE TITLE
Remove "amenity/school|Escola Primária"

### ISSUE THREAD

**Issue by naoliv** [osmlab/name-suggestion-index#79]
"Escola Primária" is a descriptive name for "primary school", and not a proper name.

**Comment by ftrebien** [comment]
+1 Entering generic names in OSM is not [good practice](https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.json).

**Comment by naoliv** [comment]
Seems to be already at [filter.json](https://github.com/osmlab/name-suggestion-index/blob/master/filter.json)
My bad that I look at the wrong file.
