### ISSUE TITLE
Is English tagging required?

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#7921]
Do English tags need to exist in every POI added via the NSI?

I've noticed that with quite a lot of entries that aren't based in English speaking Countries, that tagging seems repetitive.

For example, the PR for [Caritas UA](https://github.com/osmlab/name-suggestion-index/pull/7908/commits/1ebfcfe1daad0f0e95e78d30e1027a44f67871a1) includes a basic `brand` tag for the Ukrainian name, but then this is repeated in `brand:uk` but also contains the English `brand:en`, with the same repetitiveness for the `name` tag.

Would it not be better for tagging to only focus on the local language where English isn't really used, with `matchNames` used for the English alternative if needed? Or is English so widespread in OSM that it's better to retain it?

**Comment by bhousel** [comment]
> Or is English so widespread in OSM that it's better to retain it?

This is kind of what I think, but in the past I've also been ok with removing the `name:en` if local communities are really bothered by it..  (#2992, #3967 come to mind)

It's useful for us as maintainers to see what the brands in NSI are, and it's also useful to have a `name:en` tag for matching purposes, if somebody does try to map it with the English name it can get a suggestion to upgrade the tagging to what the locals prefer.

**Comment by 1ec5** [comment]
In cases where the English name is being omitted, should there be a property outside the tags object that can indicate this name without affecting the applied tags? Or I guess that could be a `matchNames`…

**Comment by bhousel** [comment]
> In cases where the English name is being omitted, should there be a property outside the tags object that can indicate this name without affecting the applied tags? Or I guess that could be a `matchNames`…

Yes, `matchNames` would work for this 👍
