### ISSUE TITLE
Add DHL - Parcel Locker in Poland

### ISSUE THREAD

**Issue by CharlesMaZ** [osmlab/name-suggestion-index#7931]
amenity=parcel_locker
brand=DHL
brand:wikidata=Q115568785
operator=DHL
operator:wikidata=Q489815
parcel_mail_in=yes
parcel_pickup=yes

https://wiki.openstreetmap.org/wiki/Pl:Tag:amenity%3Dparcel_locker

**Comment by Vectari** [comment]
Hello! I looking for my first issue and find this topic. I looked on DHL page and checked their map. You can parcel mail in any POP BOX but you have to have label on it (probably when you return something to  shop like Zalando) or if you  don't have label you have to pay online.
Can I do something more to resolve this issue?

**Comment by mutipg** [comment]
I added PR #8613 for this issue. On page https://www.dhl.com/pl-pl/parcel/dla-ciebie/odbior/automaty-pop-box.html is written that you can send parcels in all DHL POP BOX.
