### ISSUE TITLE
Santander does not use "Banco Santander" in Poland

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#7944]
It seem to use "Santander"

See https://www.santander.pl/klient-indywidualny

See https://duckduckgo.com/?t=ffab&q=Santander%2C+Polska&iax=images&ia=images

https://www.google.com/maps/@50.0779824,19.9243998,3a,49.8y,9.9h,87.79t/data=!3m6!1e1!3m4!1sojfyk3u175CIMBbHg9HAQQ!2e0!7i16384!8i8192?hl=en

https://www.openstreetmap.org/node/1330778685

![screen](https://user-images.githubusercontent.com/899988/229374584-9749a58c-11e9-4ed9-86a7-6dbe6a313186.png)

Fortunately iD does not offer to "upgrade" `name=Santander` banks in Poland.

**Comment by matkoniecz** [comment]
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/bank.json#L1777

There is no `Banco Santander` brand operating in Poland, as far as I know.

**Comment by UKChris-osm** [comment]
There is a [Wikidata](https://www.wikidata.org/wiki/Q806653) for Sandander in Poland, but at the moment most of the POIs seem to use the US [Santander](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=Santander#santander-ea2e2d), so would it be better to target the one that's already widely used to also apply to Poland?

**Comment by Cj-Malone** [comment]
I've already documented my opinion https://github.com/osmlab/name-suggestion-index/pull/7638#issuecomment-1377736076 but basically: use the more specific one, using the US one is lying to data consumers, so they can't reliably use the Wikidata data.

**Comment by matkoniecz** [comment]
`brand:wikidata` is anyway being blindly changed to whatever NSI is suggesting, so there is little difference here.

**Comment by Cj-Malone** [comment]
It doesn't matter much to OSM people, (or maybe I'm projecting) but I only really use `brand:wikidata` as a unique brand key. Useful for writing overpass queries, but that's about it.

But for data consumers it has a very useful purpose: brand level attributes. Logos, social media, websites etc.

A POI with `brand:wikidata=Q5835668` can be expanded to:
```
brand:wikidata=Q5835668
brand:logo=https://commons.wikimedia.org/wiki/File:Banco_Santander_Logotipo.svg
brand:website=https://www.santanderbank.com/
brand:facebook=https://www.facebook.com/SantanderBankUS
brand:instagram= santanderbankus
brand:twitter= SantanderBankUS
```

VS a POI with `brand:wikidata=Q806653`
```
brand:wikidata=Q806653
brand:logo=https://commons.wikimedia.org/wiki/File:Santander_Bank_Polska_S.A.svg
brand:website=https://www.santander.pl/
brand:facebook=https://www.facebook.com/santanderbankpolska
brand:instagram=santanderbankpolska
brand:twitter= SantanderBankPL
brand:youtube=https://www.youtube.com/channel/UCbBDnfG5Ofxbw2om35P6YQw
```

**Comment by matkoniecz** [comment]
@Cj-Malone Thanks! Note that they also have some ATM: https://duckduckgo.com/?t=ffab&q=bankomant+santander&iax=images&ia=images

**Comment by matkoniecz** [comment]
> But for data consumers it has a very useful purpose: brand level attributes. Logos, social media, websites etc.

You could just match based on location + name data, OSM tags adds nothing as it is in nearly all cases blindly added based on location + name data.

**Comment by Cj-Malone** [comment]
> Note that they also have some ATM

I believe ATM entries are computed from bank entries automatically. If that doesn't happen on the next build, we can add it manually.

> You could just match based on location + name data

So OSM consumers would need another brand database?

> OSM tags adds nothing as it is in nearly all cases blindly added

That's why NSI is so important, get it right here then OSM will be right, eventually.
