### ISSUE TITLE
Exact country search

### ISSUE THREAD

**Issue by yotamN** [osmlab/name-suggestion-index#7995]
The country search in the website finds us-il (the state of Illinois in the United States) when I search for il (Israel). It would makes a lot more sense to have exact matches only, those are country codes, they are short and exact.

**Comment by peternewman** [comment]
Isn't this effectively a duplicate of #7603 or related to #4077 ?

**Comment by bhousel** [comment]
Yes looks like a duplicate, I'll close.

When I made the nsi.guide site, it was mostly just a quick throw-together so that people could look at the data without needing to check out the project from github.  Whatever searching it has is pretty basic.
