### ISSUE TITLE
Few Automotive brands like Fait, Ferrari,etc are not available

### ISSUE THREAD

**Issue by AshwaniBindroo-TomTom** [osmlab/name-suggestion-index#8014]
Automotive brands which I was not able to find in NSI:

1. Corvette
2. Ferrari
3. Fiat
There could be more :)
Would you be so kind to look into it.

Regards
AB

**Comment by UKChris-osm** [comment]
Hi @AshwaniBindroo-TomTom 

In what capacity are you refereeing to the above car brands?

From an NSI perspective, many car makers may use official dealerships to sell their models, rather than having their own show rooms, and it's these dealerships that are usually mapped.

Not being knowledgeable on cars myself, do Ferrari, for example, have their own showrooms that can be mapped as Ferrari branded showrooms, or are Ferrari's sold via dealerships approved by Ferrari?

**Comment by arch0345** [comment]
> Fait

Did you mean Fiat?

**Comment by AshwaniBindroo-TomTom** [comment]
Ah yes, apologies for the typo. 
Indeed "Fiat" and is present in NSI

**Comment by AshwaniBindroo-TomTom** [comment]
It could be both, Ferrari branded showrooms and/or Ferrari's sold via dealerships approved by Ferrari

**Comment by arch0345** [comment]
Can confirm that there are Ferrari dealerships. Corvette on the other hand is just a car model that's sold at Chevrolet dealerships, I couldn't find any standalone Corvette showrooms/dealerships.

**Comment by Cj-Malone** [comment]
> dealerships approved by Ferrari

I find dealerships a little weird in the OSM context. Take [this](https://www.openstreetmap.org/node/7141056553) as an example, it's got `brand=Toyota`, but it only sells Toyotas. It isn't owned or operated by Toyota. I'd probably argue that it should be brand=[Leslies](https://www.lesliesmotors.co.uk/our-locations/).

But I understand from a data consumers, and even a users perspective "Toyota" is the important bit. And any change here would rock the boat in OSM, so I'll put my head in the sand for now.

**Comment by 1ec5** [comment]
More charitably, it’s usually the name of the franchisee (but can sometimes be a unique name the franchisee chooses). The franchisee often has relationships with multiple automakers, each at a different location. It’s a brand, but not a `brand` in the sense of a broader chain. Or sometimes it is a small chain of a few locations around town, but the brand of that chain is still subordinate to the automaker’s brand. In any event, the dealership name usually appears in `branch` and `name` (alongside the automaker’s name), and this index respects that usage:

https://github.com/osmlab/name-suggestion-index/blob/519b224ff6c3c271a8ab9fc7ae7e4ac09f53e065/data/brands/shop/car.json#L4
