### ISSUE TITLE
matchIndex error for Unibail-Rodamco-Westfield

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#8023]
![image](https://user-images.githubusercontent.com/85302075/233917334-c5b06169-a7d4-441e-95b7-9d85c2da5e96.png)

Affected entries:

- [`westfield-24bee6`](https://nsi.guide/?id=westfield-24bee6)
- [`unibailrodamcowestfield-1448a2`](https://nsi.guide/?id=unibailrodamcowestfield-1448a2)

**Comment by AntiCompositeNumber** [comment]
Looks to have been fixed in 7cc43ec
