### ISSUE TITLE
Gong Cha reformulation

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#8028]
Theres 7 different Gong Cha brands on NSI, all them charing the same wikidata so please merge them all into one, worldwide.

**Comment by 1ec5** [comment]
There’s one for each country because the brand uses a different spelling of its name (in a different writing system) in several of the countries where it operates.

**Comment by LaoshuBaby** [comment]
This is expected, because we don't need to contain every languages' name for every Gong Cha shop around the world, and its current items are managed by regions. Here is a example: https://github.com/osmlab/name-suggestion-index/wiki/Contributing#category-file-contents
