### ISSUE TITLE
Change Mørenett to Linja Q25424841

### ISSUE THREAD

**Issue by Gazer75** [osmlab/name-suggestion-index#8038]
Power grid operator in Norway changed name due to a merger.

**Comment by 1ec5** [comment]
Yes, and also if you search for a preset called “Mørenett” in iD when adding a new feature, it’ll come up with Linja instead.

**Comment by Gazer75** [comment]
So something that has to be done for #8032 and #8033 I'm guessing?

**Comment by 1ec5** [comment]
Maybe. In cases where there are two possible replacements, iD won’t issue a warning encouraging you to replace anything, but it will turn up both presets if you search for the old name.
