### ISSUE TITLE
countries for Panda Express

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8047]
Please add Canada and the Philippines to the countries for Panda Express. Existing preset only applies this to the US; there are also Panda Express locations in Canada, and now a handful in the Philippines.

**Comment by UKChris-osm** [comment]
Thanks you @TagaSanPedroAko 👍

**Comment by TagaSanPedroAko** [comment]
Locations now added, but this should be restricted to the US, Canada and the Philippines for this time.

**Comment by UKChris-osm** [comment]
I don't think location restrictions are really necessary unless there is a clash with similar named entries, as sometimes a brand can be trading elsewhere without us realising it.

I also saw some other mapped locations when doing an Overpass Turbo search, and the [Panda Express Wikipedia](https://en.wikipedia.org/wiki/Panda_Express) implies they are available in other areas as well.

**Comment by TagaSanPedroAko** [comment]
Ah okay.
