### ISSUE TITLE
Nsi Brand in /data/brands/shop/mobile_phone.json but not in nsi-id-presets.min.json

### ISSUE THREAD

**Issue by laurent-chriqui** [osmlab/name-suggestion-index#8049]
Hello,

I have noticed that brand with nsi index free-f6fe9a is still in mobile_phone.json but not in the minified nsi-id-presets file.
https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=free#free-f6fe9a

Any ideas as to why?

**Comment by UKChris-osm** [comment]
Hi @laurent-chriqui 

I have had a look, and it does appear to be part of the minified preset file.

What makes you think it's missing? Do you many have an old copy?

Is it not showing up for you in iD when editing OpenStreetMap? I've just tried iD myself and it's appearing as expected within France.

**Comment by laurent-chriqui** [comment]
Hi,

Sorry you're right, I was looking at a file in a fork instead of the main repo.
