### ISSUE TITLE
Research needed for: amenity/restaurant|Casablanca

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#805]
#### :thinking: We need help deciding what to do with "amenity/restaurant|Casablanca"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/restaurant|Casablanca` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/restaurant|Casablanca`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/restaurant|Casablanca`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by lrm25** [comment]
There are no matches for any restaurants named "Casablanca" or "Casa Blanca" on Wikipedia.  A google search just shows a chain in the Massachusetts area and scattered independent restaurants.  They exist, but I'm not sure whether or not they're notable enough to be considered a "brand".  What are the notability requirements?

**Comment by bhousel** [comment]
> They exist, but I'm not sure whether or not they're notable enough to be considered a "brand". What are the notability requirements?

Thanks for the research!  It sounds like this is just a popular name for a restaurant.   If there aren't 50 locations all operating as the same brand, and no wikipedia or wikidata for it, then it's best to just discard it from the index.

**Comment by lrm25** [comment]
Thanks.  I actually just looked at #157.  I'll take this one.

**Comment by bhousel** [comment]
done in #1392
