### ISSUE TITLE
Add Visayan Electric

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8052]
Please add tag preset for Visayan Electric (full name: Visayan Electric Company, abbreviated name and former short name: VECO), a power distribution utility in the Philippines. Preset applicable for power lines, minor power lines, poles, towers and substations.

Wikidata: Q7935617

**Comment by anubhav1206** [comment]
Add where? Can you elaborate it?

**Comment by TagaSanPedroAko** [comment]
It's a utility serving Cebu City and the surrounding cities and towns of Mandaue, Talisay, Minglanilla, Naga, Consolacion, San Fernando and Liloan.

**Comment by anubhav1206** [comment]
I mean add where in the project?
