### ISSUE TITLE
Add Rapid KL and Rapid Penang

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8060]
Please add tag preset for Rapid KL, a public transport network in Kuala Lumpur and surroundings, and Rapid Penang, a bus operator in Penang. Preset for Rapid KL is applicable for bus routes and stops, light rail routes and subway routes, while preset for Rapid Penang is only for bus routes. Both should come with operator=Prasarana Malaysia (Wikidata: Q4209298)). Wikidata for Rapid KL is at Q3271384; Rapid Penang is at Q4259055.

**Comment by TagaSanPedroAko** [comment]
Actually, two network tags will be added under this ticket: Rapid KL and Rapid Penang. Rapid KL will apply to bus routes and stops, light rail routes and subway route, while Rapid Penang will only apply to bus routes and stops.

**Comment by yisengang** [comment]
This addition has not been discussed with the local communities. According to the information provided in the link https://wiki.openstreetmap.org/wiki/Bus_routes_in_Klang_Valley, the network should include services such as Rapid KL Bus (other examples include MRT Feeder Bus, LRT Feeder Bus, PJ City Bus, and Smart Selangor Bus), while the operator is Rapid KL (this also applies to MRT/LRT feeder bus, PJ City Bus, Nadi Putra, and Smart Selangor routes under Rapid KL), DBKL (GOKL City Bus), Selangor Omnibus, Smart Selangor, MARA Liner, Causeway Link, and Wawasan Sutera. Prasarana is not the operator but the asset owner of these services. Rapid KL and Rapid Penang are subsidiaries of Rapid Bus, while LRT/MRT is operated under another subsidiary known as Rapid Rail.

**Comment by MASangys** [comment]
This addition has not been discussed with the local communities. According to the information provided in the link https://wiki.openstreetmap.org/wiki/Bus_routes_in_Klang_Valley, the network should include services such as Rapid KL Bus (other examples include MRT Feeder Bus, LRT Feeder Bus, PJ City Bus, and Smart Selangor Bus), while the operator is Rapid KL (this also applies to MRT/LRT feeder bus, PJ City Bus, Nadi Putra, and Smart Selangor routes under Rapid KL), DBKL (GOKL City Bus), Selangor Omnibus, Smart Selangor, MARA Liner, Causeway Link, and Wawasan Sutera. Prasarana is not the operator but the asset owner of these services. Rapid KL and Rapid Penang are subsidiaries of Rapid Bus, while LRT/MRT is operated under another subsidiary known as Rapid Rail.

**Comment by bhousel** [comment]
oh this was #5092 a while ago - I forget all the details, sorry.

**Comment by MASangys** [comment]
@TagaSanPedroAko i see u ady update the tagging, but withou any update at here.I think for Rapid Kl situation quite special, it is ok to add operator for Rapid Bus. There are 3 type of Rapid Bus services, which is normal bus (that you already add), MRT Feeder Bus (using different livery, serving the MRT stations) and LRT Feeder Bus (also different livery). Therefore my suggestion is to not adding `network` tagging, leave it to the mapper to add since some bus stop maybe served by 2/3 livery. However for the Rapid Rail there is still need to be upgrade, again not Prasarana (asset owner).  Rapid Penang is fine.

**Comment by MASangys** [comment]
https://github.com/osmlab/name-suggestion-index/commit/b385404b6afc6774e0648bd943f540b88d0afe32

**Comment by MASangys** [comment]
> @TagaSanPedroAko i see u ady update the tagging, but withou any update at here.I think for Rapid Kl situation quite special, it is ok to add operator for Rapid Bus. There are 3 type of Rapid Bus services, which is normal bus (that you already add), MRT Feeder Bus (using different livery, serving the MRT stations) and LRT Feeder Bus (also different livery). Therefore my suggestion is to not adding `network` tagging, leave it to the mapper to add since some bus stop maybe served by 2/3 livery (can be using semicolon to add diff networks). However for the Rapid Rail there is still need to be upgrade, again not Prasarana (asset owner). Rapid Penang is fine.

I am still waiting reply from @TagaSanPedroAko

**Comment by MASangys** [comment]
Ok since no response, I will proceed with the community's original proposal. Thank you.
