### ISSUE TITLE
Should PhillyCarShare be in the index

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#8062]
Any Philly experts out there? This was acquired by Enterprise and rebranded in 2014. Seems like this should get removed.

https://en.wikipedia.org/wiki/PhillyCarShare

**Comment by UKChris-osm** [comment]
It seems like most of them were added as a bulk edit over 11 years ago [10394864](https://www.openstreetmap.org/changeset/10394864#map=12/39.9806/-75.1692) and haven't been touched since.
