### ISSUE TITLE
Improving icon selection for brands where wikidata contains multiple Facebook IDs

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8064]
It seems that icon is selected from last in the wikidata list Facebook ID, which means that icon may not be appropriate for different locations

**Affected brands:**
https://nsi.guide/?id=decathlon-330f9d
https://nsi.guide/?id=veantattoo-eea007

**Comment by bhousel** [comment]
It's generally assumed that all the values on Wikidata are "equally good".

But in situations like these where there are multiple values to choose from, you can adjust the priority on Wikidata if one is better , or more current, or more representative than the others.  

Our syncing script will take the "preferred" one over all the others. (and ignore anything marked "deprecated")

![wikidata priority](https://user-images.githubusercontent.com/38784/235355975-eb5bbe72-ecec-4bd3-b726-98ea481d16e1.gif)
