### ISSUE TITLE
Should the restaurant categories be restructured?

### ISSUE THREAD

**Issue by arnowrld** [osmlab/name-suggestion-index#8080]
An extension of dialogue from #8045 

What I'm specifically talking about in terms of restructuring is the possibility of creating a separate page for fast-casual restaurants in the nsi.

Example: 

- amenity/fast_casual
- amenity/fast_food
- amenity/restaurant

**Comment by bhousel** [comment]
Yes, the categories are still organized according to the OSM tag.
I remember you asked about this in #5579 and #5691 too - but for the forseeable future, the categorization of the project is really tied to OSM tags.
