### ISSUE TITLE
Add Wilcon Depot

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8091]
Please add Wilcon Depot, a chain of home improvement stores in the Philippines, with about 41 locations.

**Comment by TagaSanPedroAko** [comment]
@LaoshuBaby Wikidata for the chain has already been added by @ianlopez1115

**Comment by ianlopez1115** [comment]
The Wikidata entry in question can be found at https://www.wikidata.org/wiki/Q118189975
