### ISSUE TITLE
Metro (Philippines) brands

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8125]
Adds tag preset for Metro (also Metro Gaisano), a supermarket and department store chain in the Philippines. Request will add these store brands:

- [ ] Metro Department Store
- [x] Metro Supermarket (solved in #8149)
- [ ] Super Metro

This is in response to some locations that got tagged with the similarly-named but unrelated European chain METRO by a new editor. For the department store chain, there is also possible risk of mix-up with another similarly-named chain based in Singapore.

Wikidata for the three will be at Q23808789 (Metro Retail Stores Group)

    {
      "displayName": "Metro Department Store",
      "locationSet": {
        "include": ["ph"]
      },
      "tags": {
        "brand": "Metro Department Store",
        "brand:wikidata": "Q23808789"
        "shop": "department_store",
      }
    },
    {
      "displayName": "Metro Supermarket",
      "locationSet": {
        "include": ["ph"]
      },
      "tags": {
        "brand": "Metro Supermarket",
        "brand:wikidata": "Q23808789"
        "shop": "supermarket",
      }
    },
    {
      "displayName": "Super Metro",
      "locationSet": {
        "include": ["ph"]
      },
      "tags": {
        "brand": "Super Metro",
        "brand:wikidata": "Q23808789"
        "shop": "supermarket",
      }
    },

**Comment by TagaSanPedroAko** [comment]
@Cj-Malone Metro Department Store and Super Metro hasn't been added yet.

**Comment by Cj-Malone** [comment]
Sorry

**Comment by TagaSanPedroAko** [comment]
@Cj-Malone Thank you! Salamat!
