### ISSUE TITLE
Japanese railway networks missing Wikidata or needs to be renamed

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8132]
Looks like a lot of Japanese railway networks currently in NSI don't have any connected Wikidata but have links to Wikipedia. Here are the following networks that needs to be connected with their Wikidata. 

(_Japanese name (the one used for display and the main value) is provided first, then English translation_)

- [x] 京成電鉄 (Keisei). Wikidata: Q83538
- [x] 南海 (Nankai Electric Railway). Wikidata: Q1188230
- [x] 小田急電鉄 (Odakyu Electric Railway). Wikidata: Q83584
- [x] 東急電鉄 (Tokyu Railway). Wikidata: Q80229029
- [x] 阪急電車 (Hankyu). Wikidata: Q473058. Also rename to 阪急電鉄

Following entries should be renamed:
- [ ] - 池袋線系統 (Ikebukuro Line network). Should be renamed to 西武鉄道(Seibu). Wikidata: Q83543.
- [ ] 東武本線: rename to 東武鉄道 (Tobu Railway). Wikidata: Q1321914

**Comment by soprano1125** [comment]
> 池袋線系統 and 東武本線: merge to 東武鉄道 (Tobu Railway). Wikidata: Q1321914

Is the "池袋線系統" not 東武鉄道 (Tobu Railway) but [西武鉄道 (Seibu Railway)](https://en.wikipedia.org/wiki/Seibu_Ikebukuro_Line)?

**Comment by TagaSanPedroAko** [comment]
Yes, and just corrected it.

**Comment by bhousel** [comment]
closing, it looks like this was done..
