### ISSUE TITLE
Build script doesn't clean "shop/tobacco" from matchTags for "shop/tobacco" entry

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8137]
See T-ZONE entry in shop/tobacco
https://nsi.guide/?id=tzone-fbb387

**Comment by peternewman** [comment]
Seems sensible! Some stuff got done in https://github.com/osmlab/name-suggestion-index/commit/da4b7cf04a108c0dfa37170efc1c2aa5fa017e3c#diff-a998448731ea08351bf31b52ede0ac735c0950ea2cb376f651e4ba2a80d85cce but it doesn't seem to cover this specific case.
