### ISSUE TITLE
Social media links for Edo Japan

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8138]
Edo Japan is added in #8054, but it's missing social media links.

**Comment by LaoshuBaby** [comment]
Sorry, NSI don't designed to contain social media links, we get them from wikidata property. If you want to refine those data you can edit in https://www.wikidata.org/wiki/Q17492665, note that you need to abide by the editing rules of the wikidata community

https://github.com/osmlab/name-suggestion-index/wiki/Contributing#tags-required

**Comment by TagaSanPedroAko** [comment]
@LaoshuBaby Added Facebook ID to Wikidata already, but not yet Twitter, IG or YouTube IDs.

**Comment by Cj-Malone** [comment]
> Twitter, IG or YouTube IDs

Done.
