### ISSUE TITLE
Remove Winners from shop/clothes

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8140]
Winners (the Canadian retail chain) should be under shop/department_store instead of shop/clothes. While it mostly sells clothes, the also sells interior decor (unless store has a tied HomeSense), toys and some cheap electronics.

**Comment by TagaSanPedroAko** [comment]
Already in shop/department_store. To-do is to delete Winners from shop/clothes.

**Comment by tas50** [comment]
Fixed by 13901c02e
