### ISSUE TITLE
Add Romanian bookstores chain "Cărturești"

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#8153]
Cărturești is a Romanian bookstore chain with several shops: https://carturesti.ro/librarii

Suggested tagging:
```
name=Cărturești
brand=Cărturești
brand:wikidata=Q12726202
shop=books
```

Would be nice to keep the local name, because are named by the place, or because are historical bookstores.
Let's also put an matchName without diacritics "Carturesti".

**Comment by bhousel** [comment]
> Would be nice to keep the local name, because are named by the place, or because are historical bookstores.

We can do this - we support preserving the name tag for situations like this where each location is named differently.

> Let's also put an matchName without diacritics "Carturesti".

Good idea, though our matcher already ignores the diacritics (and spaces and punctuation), so we dont actually need a separate `matchName` property for it.
