### ISSUE TITLE
Add region restriction and localizations for METRO

### ISSUE THREAD

**Issue by TagaSanPedroAko** [osmlab/name-suggestion-index#8157]
METRO (the German warehouse club) needs some region restriction, in response to the brand getting added to unrelated chains in the Philippines (see #8125). Looks like it's available across the world in the present NSI.

**Comment by TagaSanPedroAko** [comment]
Location restriction to apply for Europe, India, Pakistan, Turkey. Some other examples elsewhere are the addition of the wrong brand (e.g. Indonesia, South Africa, Colombia).

**Comment by kjonosm** [comment]
@TagaSanPedroAko Can this issue be closed?
