### ISSUE TITLE
Please Add Pete's Market

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#8174]
Chicagoland Supermarket Chain
https://www.petesfresh.com/

**Comment by matkoniecz** [comment]
Is there a wikidata brand entry for it? If yes, can you link it? If no, could you create and link it? That would help with adding it.

(similarly, for other issues you opened)

**Comment by tommylung** [comment]
I have created the wikidata [Q118793358](https://www.wikidata.org/wiki/Q118793358).
