### ISSUE TITLE
Please add Cook County Health

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#8181]
https://cookcountyhealth.org/

**Comment by TagaSanPedroAko** [comment]
@Zol87 Looks like you're creating a lot of issue tickets (and you have done so before), many of them not yet having a Wikidata item (you can add them yourself) If possible, you are welcome to solve them yourself. It may take a while for maintainers to see your tickets.

**Comment by Zol87** [comment]
https://www.wikidata.org/wiki/Q30286975
