### ISSUE TITLE
A website search should ignore diacritics

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8188]
Currently, searching for "Geträ" and "Getra" provide different results. It would be helpful if the result was the same

**Comment by bhousel** [comment]
I added this in 44575df80
So the searching will now ignore diacritic marks.
Only drawback is - I don't know of a way to make the yellow highlighting the search result work if the match isn't exact.

![diacritic nsi](https://github.com/osmlab/name-suggestion-index/assets/38784/fd89aaa1-cb3a-4cb8-8cad-130ce68e598b)
