### ISSUE TITLE
Which variant of writing the operator in German-speaking countries is preferred: with "GmbH" or without?

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8202]
There are often duplicates in the repository
e.g. "TraveNetz GmbH" & "TraveNetz"

**Comment by kjonosm** [comment]
Since 2013 the German [wiki](https://wiki.openstreetmap.org/wiki/DE:Key:operator) states that legal entity types don't have to be used. As far as I see it, most mappers proceed this way and leave them out when tagging `operator=*`.
