### ISSUE TITLE
Caritas (Deutschland) brand vs operator

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8205]
There are 2 duplicate entries:
https://nsi.guide/index.html?t=brands&k=amenity&v=social_facility#caritas-da0ff2
https://nsi.guide/index.html?t=operators&k=amenity&v=social_facility#caritasverband-01cce6

How to resolve this duplication?

**Comment by kjonosm** [comment]
[Caritasverband](https://de.wikipedia.org/wiki/Deutscher_Caritasverband) is the umbrella organisation for over 900 local Caritas organisations in Germany. Hence, for the majority of Caritas features the correct choice should be [`brand=Caritas`](https://www.caritas.de) together with e.g. [`operator=Caritas Berlin`](https://www.caritas-berlin.de) for tagging the local entity. However, there might be occasions where the actual operator is indeed `operator=Caritasverband`.
