### ISSUE TITLE
Please remove name:*=* from ATM

### ISSUE THREAD

**Issue by Glebzilla** [osmlab/name-suggestion-index#8214]
Please remove name:*=* suggestion from some ATMs

amenity=atm
brand=Ак Барс Банк
brand:en=Ak Bars Bank
brand:ru=Ак Барс Банк
brand:wikidata=Q4059103
operator=Ак Барс Банк
operator:wikidata=Q4059103

amenity=atm
brand=Сбербанк
brand:en=Sberbank
brand:ru=Сбербанк
brand:wikidata=Q205012
operator=Сбербанк
operator:wikidata=Q205012

and others.
Thank you.

**Comment by bhousel** [comment]
oh yeah this is a dup of https://github.com/osmlab/name-suggestion-index/issues/7236#issuecomment-1356329538
