### ISSUE TITLE
Mer charging stations: brand vs operator

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8216]
Seems that these 2 entries correspond to the same charging stations network:

https://nsi.guide/?t=brands&k=amenity&v=charging_station#mer-b20835
https://nsi.guide/index.html?t=operators&k=amenity&v=charging_station#mergermanygmbh-c22d3a

**Comment by Cj-Malone** [comment]
The operator one isn't included in the output because it has no Wikidata associated with it. We can probably remove it, unless there is an argument that it should be the brand one that should be removed?
