### ISSUE TITLE
Please Add Chigo x Flip

### ISSUE THREAD

**Issue by Pizza2580** [osmlab/name-suggestion-index#8226]
name=Chigo x Flip
amenity=fast_food
cuisine=chicken
brand=Chigo x Flip
brand:wikidata=Q118515768
diet:halal=yes

**Comment by tommylung** [comment]
Thank you

**Comment by Pizza2580** [comment]
Also, please add "takeaway=yes"

**Comment by Pizza2580** [comment]
Sorry, I forgot to add "takeaway=yes" and "diet:halal=only"

**Comment by tommylung** [comment]
I added `"takeaway": "yes"` and `"diet:halal": "yes"` before.
I changed `diet:halal` as `"diet:halal": "only"` for this commit.
Could you please kindly have a check for it? And thanks for your contribution :)

**Comment by Pizza2580** [comment]
Yes, this is correct. They accept takeaway and they only sell halal foods.
