### ISSUE TITLE
shop=tool_hire vs shop=plant_hire

### ISSUE THREAD

**Issue by mstsbe** [osmlab/name-suggestion-index#8264]
I've encountered some examples of companies that are already in NSI under shop=tool_hire. But, some of the branches also rent out larger equipment (mobile gensets = mobile power generators, larger bulldozers, temporary toilets, temporary container units, aerial work platforms, etc..). This type of equipment rental is tagged with shop=plant_hire.

2 examples of such cases (at least in my region) are Boels Verhuur/Boels Rental and Loxam.
https://nsi.guide/index.html?t=brands&k=shop&v=tool_hire#boels-d0c09f
https://nsi.guide/index.html?t=brands&k=shop&v=tool_hire#loxam-33fef8
Both do individual tool rental, but also large to very large equipment rental.

Can we make a match group so these 2 companies are caught for shop=tool_hire as well as shop=plant_hire ?

**Comment by peternewman** [comment]
So https://github.com/osmlab/name-suggestion-index/blob/main/config/matchGroups.json would make them all equivalent/match either way IIRC, but are you saying they all do both, or there are two sub-brands, one of which does the big stuff.

You can also do it on individual shops if you don't think it should apply to the whole category with:
https://github.com/osmlab/name-suggestion-index/blob/ac47ca45d1343c6e9b2fb244fe19be1c3f4d6b55/data/brands/shop/doityourself.json#L393

**Comment by mstsbe** [comment]
Thanks for the insight. The second option is probably the better way to go, otherwise we may be making too disruptive changes in that category. I will make a PR so both brands are matched by both tags.
