### ISSUE TITLE
Fix Name for Angelo Caputo's Fresh Markets

### ISSUE THREAD

**Issue by Zol87** [osmlab/name-suggestion-index#8272]
Sorry It's "Angelo Caputo's Fresh Markets" not market

https://www.wikidata.org/wiki/Q118594294
https://www.shopcaputos.com/

**Comment by tommylung** [comment]
I just reopen the issue #8180.

**Comment by tommylung** [comment]
I updated the name to `Angelo Caputo's Fresh Markets`. You can double check on the commit. Cheers 🍻
