### ISSUE TITLE
Pédibus is a generic name?

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8293]
https://nsi.guide/index.html?t=transit&k=route&v=walking_bus#pedibus-dbaacb
https://www.wikidata.org/wiki/Q631012

If yes, how to process it correctly (single entry in file)?

**Comment by bhousel** [comment]
Looks like if there was a QID of [Q631012](https://www.wikidata.org/wiki/Q631012) it was removed a long time ago.
