### ISSUE TITLE
Can we add office=charity?

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8307]
Currently `office=association` file also contains charitable organizations (e.g. Red Cross, Malteser, Samaritan Foundation), although there is a more appropriate tag `office=charity` for them

https://nsi.guide/index.html?t=brands&k=office&v=association

https://wiki.openstreetmap.org/wiki/Tag:office%3Dcharity
https://wiki.openstreetmap.org/wiki/Tag%3Aoffice%3Dassociation

**Comment by codeinabox** [comment]
Are these offices or [social_facility=outreach](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Doutreach)?

**Comment by serhii-muchychka** [comment]
Not sure. Maybe from the customer's point of view, it's the same thing

**Comment by serhii-muchychka** [comment]
Closing because alternative solution has been proposed
