### ISSUE TITLE
Add Alpina 

### ISSUE THREAD

**Issue by jxckcooper** [osmlab/name-suggestion-index#8318]
Add Alpina internationally, the sub-brand and dealership network owned by BMW Group.
Wikipedia: https://en.wikipedia.org/wiki/Alpina
Wikidata: Q203550
Logo (via Wikipedia): ![image](https://github.com/osmlab/name-suggestion-index/assets/71857285/7f068df9-80d3-4b21-9151-9776c1d00cc7)

**Comment by AntiCompositeNumber** [comment]
I had a peruse around https://www.alpina-automobiles.com/en/contact/dealer-locator/ and couldn't find an Alpina dealer that wasn't part of a BMW dealer. I also only found [one existence](https://www.openstreetmap.org/node/11010418384) of a `brand=Alpina` with Overpass, which appears to be inside a BMW dealer as an uncommon form of micromapping. NSI doesn't really support multiple-brand car dealers, so I don't think this brand is a good candidate for inclusion.
