### ISSUE TITLE
Man Made Charge Points

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#8329]
When the NSI suggestion's pop up in iD for `man made / charge ports`, the sub-text reads "_Man-Made Feature_" rather than something more meaningful.

Is this because the generic preset for a `man made / charge ports` isn't available in iD yet?

![charging](https://github.com/osmlab/name-suggestion-index/assets/59393694/3611edd3-425a-436b-b92d-4681bf4c6fcf)
![charging-2](https://github.com/osmlab/name-suggestion-index/assets/59393694/91b94046-d0bb-4cd8-9cd7-7a521a363c50)

**Comment by arch0345** [comment]
I added a preset for `man_made=charging_point` around a month ago in https://github.com/openstreetmap/id-tagging-schema/pull/917, but that preset won't be available in iD until the next release of id-tagging-schema:
https://github.com/openstreetmap/id-tagging-schema/releases

@tyrasd What's the eta for the next id-tagging-schema release?

**Comment by arch0345** [comment]
As of [v6.0.20230816](https://github.com/osmlab/name-suggestion-index/releases/tag/v6.0.20230816) we're using the new version of id-tagging-schema which includes a preset for `man_made=charging_point`:
![image](https://github.com/osmlab/name-suggestion-index/assets/85302075/e1fe9382-9224-4812-b0fd-f1a95b4f90d1)
