### ISSUE TITLE
amenity=conference_centre - brand or operator?

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#8348]
I am looking to add an entry for [etc.venues](https://www.etcvenues.com/), however I am not sure to treat them as a brand or operator and no other `amenity=conference_centre` have been added. The sites are clearly branded, however I am not sure if they also operate them.

**Comment by bhousel** [comment]
oh yeah, this can be hard to decide.  [#5625 (comment)](https://github.com/osmlab/name-suggestion-index/issues/5625#issuecomment-958218478) lists the guidance:

### The rules:

IF an item is in the `brands` tree:
* the `brand` tag is required and `brand:wikidata` is used as main identifying tag for fetching the logo.  
* `operator*` tags are optional, as they are likely to be inconsistent / irrelevant across that brand.  (This includes things like privately operated post offices, like found in Norway, the United Kingdom, and stuff like the UPS Store and Mailboxes Etc..)

IF an item is in the `operators` tree: 
* the `operator` tag is required, and `operator:wikidata` is used as the main identifying tag for fetching the logo. 
* `brand*` tags are optional, as they are likely to be redundant / irrelevant / unusual in these situations (We wouldn't say that a public police force or school district is "branded").

IF you're going to create a category that exists in both `brands` and `operators` trees:
* one or both files should have `"skipCollection": true` property set (to avoid having both files filled up with the same collected names)

**Comment by bhousel** [comment]
I guess I didn't answer the question. It sounds like "etc.venues" is more of a brand, since we don't really know the operator situation and each location might have different operator.  These things seem similar to hotels.
