### ISSUE TITLE
A picture is not displayed on the website

### ISSUE THREAD

**Issue by dune0310421** [osmlab/name-suggestion-index#8358]
Hi, I just found that there is a picture (logo) not displayed on the website. 
https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone
![image](https://github.com/osmlab/name-suggestion-index/assets/94817721/0ee079d4-4b2c-4e3f-a30f-6f50b7435ea5)

**Comment by Cj-Malone** [comment]
It's an issue with Wikidata. The logo property either needs to be fixed, or removed. https://www.wikidata.org/wiki/Q19840921#P154

**Comment by dune0310421** [comment]
> 

Thanks for answering! I think someone will deal with it one day :)

**Comment by Cj-Malone** [comment]
I've just removed it from Wikidata. I don't know enough about commons to know if [it's](https://commons.wikimedia.org/wiki/File:Three_Ireland_logo.svg) coming back. But it seems to keep getting deleted.

NSI website will be fixed after the next release. Thank you.
