### ISSUE TITLE
Add Ward's

### ISSUE THREAD

**Issue by MoiraPrime** [osmlab/name-suggestion-index#8360]
Ward's is a chain restaurant local to Mississippi.

Wikidata: https://www.wikidata.org/wiki/Q119716752 (I've made a bit of an effort to try to add some info to it but I'm not too familiar with Wikidata)

recommended tags:

name=Ward's
amenity=fast_food
cuisine=burger;fries;hot_dog;catfish

Also a good idea to limit this to Mississippi. All of their locations are in Mississippi.

**Comment by Cj-Malone** [comment]
Thanks,

I added it as "Ward's Restaurant", OSM has 8 of them, 5 "Ward's", 3 "Wards" and 1 with no name. Feel free to correct me if you disagree.

I didn't add catfish as it has really low usage, but I added the other cuisines.

**Comment by MoiraPrime** [comment]
Catfish is a specific regional cuisine and I've used it on a few local places. Figured it might be worth adding since catfish filets is the most unique thing they serve.. but if you feel it's too underused of a tag I can understand that.
