### ISSUE TITLE
Text input field on nsi.guide broken

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#8396]
I can't type more than one key into each of the text input fields on nsi.guide without escaping.

<img width="498" alt="image" src="https://github.com/osmlab/name-suggestion-index/assets/51236777/40b16e0b-05bc-4145-9336-70431441220e">

I'm using latest Safari on macOS

**Comment by bhousel** [comment]
weird - yea I'm seeing this on Chrome too
