### ISSUE TITLE
Farmersville, California additions

### ISSUE THREAD

**Issue by happy5214** [osmlab/name-suggestion-index#8399]
I'd like to suggest the following operator additions to NSI in California:

- Farmersville Unified School District (FUSD) (https://www.wikidata.org/wiki/Q5435837)
  - `amenity=school`
- City of Farmersville (https://www.wikidata.org/wiki/Q986808)
  - `amenity=parking`
  - `emergency=fire_hydrant`
  - `leisure=park`
  - `man_made=manhole`
  - `man_made=pipeline`
  - `man_made=water_well`

Both operators should have `operator:type=public`.

**Comment by arrival-spring** [comment]
The website says there are only 7 schools in that district, so I think it is not notable enough for NSI

**Comment by happy5214** [comment]
> The website says there are only 7 schools in that district, so I think it is not notable enough for NSI

There are similar numbers of wells and parks (all of which are already mapped), so those tags can be taken off too. There are many more manholes, pipelines, and hydrants, many of which aren't yet mapped. Public parking comprises the street parking along the main street (which I've already micromapped) and parking lots at public areas like the parks and city hall (which are mostly, but not completely, mapped to at least a basic level).

**Comment by 1ec5** [comment]
This isn’t about whether things are mapped, only about whether an entry is added to NSI to standardize the `operator:wikidata` tagging. The tradeoff is that the memory and bandwidth cost of proliferating small operators can add up, hurting performance for everyone using iD or other NSI clients.
