### ISSUE TITLE
Disable tower:type=light

### ISSUE THREAD

**Issue by HubMiner** [osmlab/name-suggestion-index#84]
There are 
215: tower:type=light
and 7171: tower:type=lighting

The "light" likely refers to "lighting".  Please take out "light" as one of available values in ID, and apply global change to existing ones.

**Comment by HubMiner** [comment]
I checked that none of the files in this project contain "tower:type" or even "tower", so existing suggestion might be coming from somewhere else, please provide guidance.

**Comment by bhousel** [comment]
For many dropdown fields (including the `tower:type` one) iD pulls the list of available choices directly from taginfo.  The best way to avoid having iD suggest values here is to clean up the actual data in OSM, which taginfo ingests nightly.

**Comment by HubMiner** [comment]
It worked!
