### ISSUE TITLE
Incorrect name=ALDI Nord/ALDI Süd for shop=supermarket in Germany

### ISSUE THREAD

**Issue by fabi003** [osmlab/name-suggestion-index#8406]
NSI for Germany contains incorrect date for

https://nsi.guide/index.html?t=brands&k=shop&v=supermarket#aldinord-0a839e
and
https://nsi.guide/index.html?t=brands&k=shop&v=supermarket#aldisud-0a839e

Data at the moment:

brand=ALDI Nord
brand:wikidata=Q41171373
name=ALDI Nord
shop=supermarket

right data ("ALDI Nord" brand):

brand=ALDI Nord
brand:wikidata=Q41171373
name=ALDI (as written on the shop) or name=Aldi (as written as German word)
website=https://www.aldi-nord.de/
shop=supermarket

Sample picture of a ALDI Nord brand shop in Germany: https://www.lebensmittelzeitung.net/galerien/So-sieht-die-neue-Filiale-Nummer-1-aus-1545

right data ("ALDI Süd" brand):

brand=ALDI Süd
brand:wikidata=Q41171672
name=ALDI (as written on the shop) or name=Aldi (as written as German word)
website=https://www.aldi-sued.de/
shop=supermarket

Sample picture of a ALDI Süd brand shop in Germany: https://www.focus.de/finanzen/news/koelner-filiale-aldi-stampft-kassen-service-ein-doch-es-liegt-nicht-am-diebstahl_id_184975891.html

"ALDI" or "Aldi" is an abbreviation for "Albrecht Diskont" so it could also be "AlDi", which is not used is Germany. Most people use "Aldi" for e.g. "I go to Aldi."

**Comment by fabi003** [comment]
As additional background, why Aldi has two brands for the same shop name, as english Wikipedia don't has this:

In 1961, the discount chain was split into two, one operated by each Albrecht son, which divided Germany as food market into the north for "Aldi Nord" (Aldi North) and south "Aldi Süd" (Aldi South) before they expanded into the word. So the same shop name has two brands.

**Comment by kjonosm** [comment]
@fabi003 Current numbers queried by overpass:

882 x `name=Aldi`
68 x `name=ALDI`
410 x `name=Aldi Süd`
1410 x `name=ALDI Süd`
191 x `name=Aldi Nord`
1447 x `name=ALDI Nord`

950 x `name=ALDI` + `name=Aldi`
3358 x `name=Aldi Süd` + `name=ALDI Süd` + `name=Aldi Nord` + `name=ALDI Nord`

According to these numbers localised names - as suggested by NSI - are clearly preferred in Germany.

**Comment by fabi003** [comment]
I would also prefer name=Aldi over name=ALDI as it is also used by English Wikipedia too.
I wonder why no one reported this problem before, at it at least exist around a year now and, thanks to NSI garbage canonization, many shops in Germany also has name=ALDI Nord and name=ALDI Süd now.

**Comment by bhousel** [comment]
> I wonder why no one reported this problem before, at it at least exist around a year now and, thanks to NSI garbage canonization, many shops in Germany also has name=ALDI Nord and name=ALDI Süd now.

How seriously do you expect me to take your issue, if you call our project "garbage".

**Comment by fabi003** [comment]
@bhousel 

You should better explain, how this incorrect garbage data was added to the project in this kind, because I had not to complain about it now. Why no German mapper was asked about it?

**Comment by bhousel** [comment]
> You should better explain, how this incorrect garbage data was added to the project in this kind, because I had not to complain about it now. Why no German mapper was asked about it?

We've been collecting it from the OSM planet file this way since at least 2018.
https://github.com/osmlab/name-suggestion-index/pull/1907
The user who closed that issue is a German mapper. 😆

**Comment by fabi003** [comment]
OK, as in #1907, I did not know that the reporter give not enough information about the subject of tagging Aldi supermarket shops.

**Comment by bhousel** [comment]
If you are quite sure that the German community would prefer to just use `name=Aldi` for all of them, I can make this change.  

I can make geojsons for Aldi Nord and Aldi Süd so that users who type "Aldi" don't get the wrong preset.
I did a look on overpass and it does look like there is a clear line in the current data between the two brands where I could make the geofence.

[Aldi Nord](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket#aldinord-0a839e)|[Aldi Süd](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket#aldisud-0a839e)
---|---
<img width="300" alt="Screenshot 2023-07-20 at 9 13 17 AM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/9b695701-674f-4390-9039-30da0f766a4b">|<img width="300" alt="Screenshot 2023-07-20 at 9 14 02 AM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/2b3ff14a-99da-4797-a989-77edc1552795">


I found one that was one incorrectly tagged (it sticks out on the Süd map), so I just fixed it in https://www.openstreetmap.org/changeset/138764462
(I verified it to be an Aldi Nord from Mapillary imagery)

**Comment by fabi003** [comment]
I think your solution with the geojson, is much better for Germany the the situation now.

According to the [Geofabrik taginfo for Germany](https://taginfo.geofabrik.de/europe/germany/keys/name#values), there is a clear vote with 885 times for name=Aldi over 69 times for name=ALDI in Germany with the data from 2023-07-16.

![grafik](https://github.com/osmlab/name-suggestion-index/assets/110132764/b9b42326-907b-4837-b3e9-792117bffd46)

**Comment by kjonosm** [comment]
For ALDI vs. Aldi see also the example given on https://wiki.openstreetmap.org/wiki/DE:Abkürzungen

**Comment by fabi003** [comment]
Maybe we should tag therse shops as:
shop=supermarket
name=ALDI
old_name=Albrecht Diskont
short_name=AlDi
alt_name=Aldi
;-)

The is the OSM rule to write the name as on the sign.
The problem is, that the brand ALDI is written in all capital letters at least, if you look at https://aldi-nord.de, where they even write ALDI in the imprint of the page. Aldi Süd write it like "ALDI SÜD Dienstleistungs-SE & Co. oHG".
But no one use the word "ALDI" in natural German language, only "Aldi", so most of the OSM-community use "Aldi".

https://wiki.openstreetmap.org/wiki/Key:name writes:

> If an official name is more unwieldy or obscure than another name for the same feature and fewer people use it in practice, even if it is signposted, it is better to put the official name in [official_name](https://wiki.openstreetmap.org/wiki/Key:official_name)=* or [alt_name](https://wiki.openstreetmap.org/wiki/Key:alt_name)=* than to treat it as the primary name.

So we have:
name=Aldi
official_name=ALDI

The same brand vs. common language problem exists for e.g the brand ROSSMANN of the company "Dirk Rossmann GmbH":
https://www.fr.de/bilder/2023/06/09/92332243/31969857-rossmann-filiale-symbolfoto-drogerie-test-zdf-produkt-versprechen-preis-kunden-konkurrenz-preisdruck-2m8Oio0IM170.jpg
At the bottom of https://www.rossmann.de/ they write "ROSSMANN Copyright © 2023 - Dirk Rossmann GmbH" so the brand is also written "ROSSMANN" but we have 3757 uses of name="Rossmann" and 154 uses of "ROSSMANN" in the OSM database according to worldwide taginfo of today.

**Comment by fabi003** [comment]
https://de-m-wikipedia-org.translate.goog/wiki/Aldi?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp#Logos_(1945_bis_heute)

Brand and name for Aldi Süd is ALDI SÜD (at least now in Germany), the above article/photo is the international logo used until 2017, the new international logo of "Aldi Süd" has also name=ALDI (https://en.wikipedia.org/wiki/Aldi).

**Comment by Cj-Malone** [comment]
I don't want to get too involved with this, but it also seems like [Aldi CH](https://www.aldi-suisse.ch/de/homepage.html) use "ALDI SUISSE" over "ALDI". Maybe a CH mapper wants to comment, but I can envision that one getting separated out from the Aldi south entry.

**Comment by fabi003** [comment]
If you look at the above Google translate-link of the German Wikipedia, the ALDI  Nord brand is called "Aldi Marche" in France and "Aldi Marked" in Denmark and the "ALDI SÜD" brand is called "Hofer" in Austria. So the other counties/brands need extra handling, even as the international "ALDI SÜD" is named only "ALDI" but "ALDI SÜD" in Germany.

**Comment by bhousel** [comment]
> I now see, that the chemist Rossmann, is [in the NSI](https://nsi.guide/index.html?t=brands&k=shop&v=chemist&cc=de#rossmann-f4ddf3) with name=Rossmann and the incorrect written brand="Rossmann" instead of "ROSSMANN".

This was resolved most recently in #5510 / #5652
As you can see from those issues, we do have people show up on this GitHub regularly to tell us to uppercase or lowercase the names of things, and it can be kind of frustrating for us maintainers to flip the names back and forth.

Please don't jump to calling things "incorrect".  We try to research how the brand wants itself to be called, and pick values that are consistent with the community expectations and would look reasonable on a map.

> If you look at the above Google translate-link of the German Wikipedia, the ALDI Nord brand is called "Aldi Marche" in France and "Aldi Marked" in Denmark and the "ALDI SÜD" brand is called "Hofer" in Austria. So the other counties/brands need extra handling, even as the international "ALDI SÜD" is named only "ALDI" but "ALDI SÜD" in Germany. But the "ALDI Nord" brand is named only "ALDI", in Germany and international.

I think you might be overthinking things - They could all just be called "Aldi" and the world would keep spinning.

**Comment by fabi003** [comment]
> > I now see, that the chemist Rossmann, is [in the NSI](https://nsi.guide/index.html?t=brands&k=shop&v=chemist&cc=de#rossmann-f4ddf3) with name=Rossmann and the incorrect written brand="Rossmann" instead of "ROSSMANN".
> 
> This was resolved most recently in https://github.com/osmlab/name-suggestion-index/issues/5510

The reporter of #5510 from Poland don't have understood, that there is a difference between the brand which is, as written above, is "ROSSMANN", where the name of the shop is "Rossmann", if the native German writing of the OSM community majority should be used and not the brand-style writing, which is right, if the writing on the shop sign should be used. So the report for #5652 is right as name="ROSSMANN" it is not the preferred community writing. I don't know, which naming convention the reporter from Poland mean, as the is no one for this project or I only didn't found it. For the name=* I would suggest the writing which the community majority wants, as you get even more community reports otherwise, if the brand-style writing is used.

I found #5109 which seems to be reported by a German user, and seems to have introduced the shop name of "ALDI Nord", which is the brand, but the name=* is only "Aldi" (community writing, same as on the international logo, besides the known exceptions from the German Wikipedia, like in France) or "Aldi Süd" for the "ALDI SÜD" brand. And the operator=* which is in parts also written as the brand, is not in the NSI.

> I think you might be overthinking things - They could all just be called "Aldi" and the world would keep spinning.

Then you may get reports from France, at least parts of Belgium and Denmark, that name=* is not what is written on the shop sign, at least if the naming was not adjusted to the international brand in these countries. German Wikipedia is badly maintained, but on a Google search the naming for FR/BE of "Aldi Marche" seems to be still in use (aldi.be delivers me German content, if I don't switch my browser language (Don't want to try/change it for every country.)).

**Comment by mp747474** [comment]
Is it not possible to change the Northern flavor of Aldi to just "Aldi" and keep the Southern flavor of Aldi as "Aldi Süd" (which is what it has always said on their logo as well as on TV/radio commercials, even if it's colloquially known as just Aldi)?

This would change the names to what it says on their respective logos, while also keeping the ability to differentiate between the Northern and Southern flavor of Aldi. This is important because a handful of cities in Germany have both flavors of Aldi (e. g. Gummersbach, or Siegen) and losing the ability to differentiate between the two would be problematic from a usability standpoint.

**Comment by bhousel** [comment]
> Is it not possible to change the Northern flavor of Aldi to just "Aldi" and keep the Southern flavor of Aldi as "Aldi Süd" (which is what it has always said on their logo as well as on TV/radio commercials, even if it's colloquially known as just Aldi)?

Yes, but only after they are separated geographically, we can name them anything.

For now, they are both set to the same locationSet `{ 'include:' ['de'] }`, and this is why they need distinct names, and why when editing in Germany users are offered both presets.

<img width="500" alt="Screenshot 2023-08-14 at 5 23 14 PM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/3f48af71-e268-4d41-a10e-1a155690f6fb">

**Comment by fabi003** [comment]
> Is it not possible to change the Northern flavor of Aldi to just "Aldi" and keep the Southern flavor of Aldi as "Aldi Süd" (which is what it has always said on their logo as well as on TV/radio commercials, even if it's colloquially known as just Aldi)?

Yes, this is what should be done for Germany in the end. Other countries may be handled different.

For "ALDI Nord" brand in Germany:
name=Aldi
brand=ALDI Nord
brand:wikidata=Q41171373
website=https://www.aldi-nord.de

For "ALDI SÜD" brand in Germany (for the uncommon German writing of "Süd" look at the website or on the company name):
name=Aldi Süd
brand=ALDI SÜD
brand:wikidata=Q41171672
website=https://www.aldi-sued.de

**Comment by KAMI911** [comment]
Can you change the
name=ALDI
to 
name=Aldi
in Hungary?


Also are we sure that should be ALDI or Aldi, not that what they sell, like Milfina, Happy Harvest, Nature's Gold.

Thank you in advance!

**Comment by KasperFranz** [comment]
I can see someone is updating it in DE to be operator aldi nord and Aldi as brand

for example: https://www.openstreetmap.org/way/1013621557/history

**Comment by bhousel** [comment]
done in #9274
