### ISSUE TITLE
Brand of shop=shoes name=Leiser Comfort is "Leiser", not "Leiser Comfort" in Germany

### ISSUE THREAD

**Issue by fabi003** [osmlab/name-suggestion-index#8409]
Wrong brand of "Leiser Comfort" (which is only the shop name) for: 

https://nsi.guide/index.html?t=brands&k=shop&v=shoes&cc=DE#leisercomfort-0833e2

correct data (also see the logo image at Wikidata):

brand=Leiser
brand:wikidata=Q1815747
name=Leiser Comfort
website=https://www.leiser.de/
shop=shoes

**Comment by UKChris-osm** [comment]
Leiser seems to appear twice in the NSI, one as simply `Leiser` and the other `Leiser Comfort`, but the Wikidate for both reads `Leiser Handelsgesellschaft`.

As there only seems to be one entry in openstreetmap for `Leiser Comfort`, could you just confirm if that name is still used in Germany?

**Comment by fabi003** [comment]
I seared for some images and most shops of Leiser brand use only the brand Leiser on the shop, but a few have additional word added to the brand, such as "Leiser comfort" or "Leiser Vionic"

Search for Leiser shop image:
https://www.google.com/search?q=Leiser+Filiale&tbm=isch

Image "Leiser comfort":
https://www.golocal.de/media/1377839e5d3646d3dea1cd364a3b71dd/700/b67a6a6fce20e8ab.jpg?pid=e3dc7f9d18363ef13253a28e717ceee4&linkmode=true

Image "Leiser Vionic":
https://media.cylex.de/companies/6696/810/images/695339167-img3_651906_large.jpg

Image "Leiser Enjoy this time":
https://media.cylex.de/companies/6696/810/images/-198575611-img4_615868_large.jpg

So the NSI entry for "Leiser comfort" is an duplicate, as most of the shops use only "Leiser" and a few have additions to the brand such as "Enjoy this time". So the brand is only Leiser.
