### ISSUE TITLE
Brand=REWE City should be brand=REWE for shop=supermarket in Germay

### ISSUE THREAD

**Issue by fabi003** [osmlab/name-suggestion-index#8412]
https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=REWE&cc=DE#rewecity-0a839e

current data:

brand=REWE City
brand:wikidata=Q16968817
name=REWE City
shop=supermarket

new data:

brand=REWE
brand:wikidata=
name=REWE City
shop=supermarket

This issue is a bit harder, as the REWE Group (https://de.wikipedia.org/wiki/Rewe_Group) have several different kind of shops, so even the discounter Penny and toom doityourself-market. Even as "nahkauf" and "REWE to go" are only different in size compared to "REWE" named supermarkets, I would see "nahkauf" and "REWE to go", as a different brand, as the logo design is more different as the blue script written on yellow background of EDEKA shops.

But at least for for "REWE City" and "REWE" supermarkets and also "REWE Getränkemarkt", the brand REWE is the same.

https://nsi.guide/index.html?t=brands&k=shop&v=beverages&tt=REWE&cc=DE#rewegetrankemarkt-c4cb62

suggested new data:

brand=REWE
brand:wikidata=Q57519344
name=REWE Getränkemarkt
shop=beverages

Even as the Wikidata object is the facility and not the brand, but there exists no object for the brand alone as with the REWE supermarket chain.

**Comment by Cj-Malone** [comment]
The GB community decided Tesco Extra and Tesco Express are different brands, even though they are both owned by Tesco.

**Comment by fabi003** [comment]
If you want to see it strict, every new minimal changed logo design or different name on the shop, is a new brand. But is this useful for OSM?

**Comment by Cj-Malone** [comment]
I don't make decisions for OSM, or even GB, although I am a board member for OSMUK.

But, I think you've phrased that question in a weird way. It implies that more generic, less specific data is useful for OSM.

From an consumers point of view, the more specific values are easier to match against, and I'll always vote for the most specific Wikidata value so consumers can get extra data from there. In the Tesco example it would mean consumers can't get accurate logos, in other examples it would mean they get other wrong meta data, like social media accounts.

**Comment by fabi003** [comment]
I agree you, that in general, more detailed data are better, as you can always throw away, what is not needed.

But for e.g. [this](https://www.openstreetmap.org/node/3644478493) REWE City market near me, you can go to the Wikidata object to extract data about the whole REWE supermarket chain, so the more specific value for the brand don't help you to get any data for the "REWE City" branded market size. But you can at least all the affected markets with the more specific brand.

As another example the convenience store at a fuel station e.g. https://www.openstreetmap.org/way/305635147 which is named different then the the brand belonging to the fuel station, you can enrich your data from Wikidata about the shop with that about the fuel station chain. The data at Wikidata is again not so fine grained as that of the OSM brand, if it is useful in any kind for a full automatic, not human reviewed, processing. For humans, the non-matching Wikidata links may be useful, but I can also look at the data at Wikidata without the non-matching reference in the OSM data.

**Comment by Cj-Malone** [comment]
Yeah, OK, looking at the [website](https://www.rewe.de/marktseite/berlin-koepenick/4040488/rewe-markt-bahnhofstr-23-25/) I can't actually make an argument for `brand=REWE City`.

I should have probably checked that before commenting. If we compare this to [Tesco](https://www.tesco.com/store-locator/sheffield). The different formats (eg Tesco Express, Tesco Extra) are clearly branded. I assumed REWE would be the same.

**Comment by fabi003** [comment]
You can just go there as I (I added things, such as the operator and not only a deep link to the website, which may be outdated tomorrow) or read the [German Wikipedia article](https://de.wikipedia.org/wiki/Rewe).

REWE City markets, according tom German Wikipedia, have an unclear status, even if they are introduced 2009, the official status is unclear, but these that exist, are still branded as "REWE City" such as the above.

At least for now, for Germany, there exists only the "REWE supermarket chain" (even "REWE" is a supermarket sub brand, besides "REWE City") , "REWE to go", "nahkauf" and "REWE Getränkemarkt" as shops on Wikidata. 

It will not always help to make everything that looks different a new brand, as for German EDEKA shops, where a "nah und gut" brand (for smaller shops, that don't match with the new store guideline since 2018) are a new brand, as the natural person, who operate it, are a contractor of EDEKA, but you can't see it from the operator name.
