### ISSUE TITLE
iD doesn't know about "thrift" matchGroup

### ISSUE THREAD

**Issue by serhii-muchychka** [osmlab/name-suggestion-index#8454]
**Steps to reproduce:**
Create node with tags `shop=second_hand;name=Humana`
iD doesn't suggest to add **brand** tag

Maybe this question is not for NSI, I'm not sure

**Comment by bhousel** [comment]
Works for me?

![Humana upgrade](https://github.com/osmlab/name-suggestion-index/assets/38784/c94e7bc7-6be4-4723-9622-a7aafe4528b0)

**Comment by serhii-muchychka** [comment]
Checked in more detail
Rapid - **OK**
iD - **not suggest**

**Comment by UKChris-osm** [comment]
Just checked, I see it working fine in Rapid, but not iD.

**Comment by bhousel** [comment]
Closing here, it seems to be an iD issue..
