### ISSUE TITLE
Midcounties Coop

### ISSUE THREAD

**Issue by TheUKHighStreet** [osmlab/name-suggestion-index#8469]
Please could someone add Your Co-op Food as a brand. This is the convenience store brand for Midcounties Coop which uses different branding from The Coop. They have 224 stores. The wikidata page is Q121084548. Facebook logo: https://www.facebook.com/photo/?fbid=695869712540747&set=a.695869695874082
Thank you.

**Comment by UKChris-osm** [comment]
Thank you for the suggestion @TheUKHighStreet

**Comment by Cj-Malone** [comment]
We already have it :p

https://data.alltheplaces.xyz/runs/2023-07-29-13-32-45/output/midcounties_cooperative.geojson

But I'm not sure how it ties in with "Your Co-op", TBH coop confuses me sometimes.

**Comment by TheUKHighStreet** [comment]
The Midcounties Co-operative (Your Co-op) is the overall brand which has separate businesses such as Your Co-op Food, Your Co-op Mobile and Your Co-op Travel which all have separate branding.
