### ISSUE TITLE
steak input to return "steak house" as cuisine not as name

### ISSUE THREAD

**Issue by skorasaurus** [osmlab/name-suggestion-index#85]
Hello, 
While editing in iD, I searched for steak house and it returned a result with the tags amenity=restaurant and name="Steak House". 

I'm thinking this is an unintended error; I don't think there is any chain named "Steak House" and although there's very few users of this tag combination [(at most 75)](https://taginfo.openstreetmap.org/search?q=steak#values) I would caution that new iD users may want to add a steak house and just click on that top entry; and we want to prevent bad data from being created. 

Instead it would return should be "amenity=restaurant and cuisine=steak_house"

Sorry If I'm filing this in the wrong place, as I understand iD is still pulling tag suggestions from the name-suggestion-index.

**Comment by bhousel** [comment]
Thanks for reporting @skorasaurus  - I just added "Steak House" to the filter and rebuilt the index.  Next version of iD should not include it 👍
