### ISSUE TITLE
American Nails?

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#8504]
Can anyone verify that "American Nails" is a consistent brand? It [was added](https://github.com/osmlab/name-suggestion-index/blame/d4b463a93004eb88479f7679915ef80040511b1d/data/brands/shop/beauty.json#L33-L43) from a planet scan, but it doesn't look like a single entity to me, at least in the US. There are a lot outside the US though.

**Comment by UKChris-osm** [comment]
I think you're right, `American Nails` seems to be a generic name.
