### ISSUE TITLE
clothes: do not match Avenue in Germany

### ISSUE THREAD

**Issue by mp747474** [osmlab/name-suggestion-index#8522]
The clothes chain Avenue never existed outside the United States but it gets matched anyway. This has led to [at least one case](https://www.openstreetmap.org/node/2636824586) where an independent clothes store in Germany got matched to that chain by iD.

Also, the chain is defunct since 2019, so it arguably shouldn't be matched anyway.

**Comment by UKChris-osm** [comment]
Thank you @mp747474
