### ISSUE TITLE
Add Italian book shop Giunti al Punto

### ISSUE THREAD

**Issue by Domefemia** [osmlab/name-suggestion-index#8547]
name=Giunti al Punto
shop=books
brand=Giunti al Punto
brand:wikidata=Q76505309

**Comment by UKChris-osm** [comment]
Hi @Domefemia 

This brand is [already available](https://nsi.guide/index.html?t=brands&k=shop&v=books&tt=giunti) as part of the Name Suggestion Index, are you having issues when trying to add it when mapping?

**Comment by Domefemia** [comment]
Most of the poi I find on Nomination, as you can see [here](https://www.openstreetmap.org/search?query=giunti#map=19/46.06792/11.22399), call the place only Giunti (that was the case for me too), so maybe it's better to add another tag for a common shorter name "Giunti"

**Comment by UKChris-osm** [comment]
Thanks @Domefemia - I have added the short name as a match.
