### ISSUE TITLE
Add Techcombank

### ISSUE THREAD

**Issue by simonschaufi** [osmlab/name-suggestion-index#8550]
Techcombank is bank in Vietnam and here is the wikidata entry: https://www.wikidata.org/wiki/Q10541776

Please add it to the index! Thank you!

**Comment by Cj-Malone** [comment]
Thank you

**Comment by simonschaufi** [comment]
Thank you for this quick fix! When will this be aproximatly be available in the editor?

**Comment by Cj-Malone** [comment]
NSI is released about once a week. As far as I know, iD gets it straight away.

@arch0345 will know the specifics

**Comment by arch0345** [comment]
> NSI is released about once a week. As far as I know, iD gets it straight away.
> 
> @arch0345 will know the specifics

You might need to clear your cache to see the changes right away (see #6573). In my experience, it can take up to a week for iD to fetch the latest release without clearing cache.

**Comment by simonschaufi** [comment]
Nah, still not picking it up. See https://www.openstreetmap.org/edit?node=11118173605#map=21/16.05587/108.24458 even with clearing the browser cache

**Comment by arch0345** [comment]
Sorry, I meant seeing changes from the latest release, which in this case is from August 16th: https://github.com/osmlab/name-suggestion-index/tags

I'll publish a new one sometime today

**Comment by Cj-Malone** [comment]
Logos usually come from Facebook, please could you add the social media accounts to https://m.wikidata.org/wiki/Q10541776

**Comment by simonschaufi** [comment]
ok I've added a bunch of data https://www.wikidata.org/wiki/Q10541776 including a photo. I hope everything is correct.

**Comment by Cj-Malone** [comment]
That should do it, thank you.
