### ISSUE TITLE
X Icon to replace the Twitter icon on nsi.guide

### ISSUE THREAD

**Issue by UKChris-osm** [osmlab/name-suggestion-index#8555]
Font Awesome have added the [X icon](https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid) to their catalogue, and even though the NSI no longer includes Twitter icons, the [nsi.guide](https://nsi.guide/) web site still includes a link to an entries profile.

**Comment by tommylung** [comment]
Certainly. 
I added WeChat and Weibo icons previously. However, we don't have square icons available for them. We can opt to replace all the icons with non-square icon, such as the [X icon](https://fontawesome.com/icons/x-twitter?f=brands&s=solid), [Facebook icon](https://fontawesome.com/icons/facebook-f?f=brands&s=solid), [Instagram icon](https://fontawesome.com/icons/instagram?f=brands&s=solid), [YouTube icon](https://fontawesome.com/icons/youtube?f=brands&s=solid).

**Comment by UKChris-osm** [comment]
Thanks @arch0345 👍
