### ISSUE TITLE
Replace transit network Autobusy miejskie w Toruniu with WGK Urzędu Miasta Torunia

### ISSUE THREAD

**Issue by RCRalph** [osmlab/name-suggestion-index#8556]
Hello,

I recently made this issue https://github.com/osmlab/name-suggestion-index/issues/8536 where I made a request for adding "Autobusy miejskie w Toruniu" as a transit network. It was quickly approved and I really appreciate that. 

Unfortunately after consultation with other mappers I came into the conclusion that the transit network should be renamed to its organizer name instead of a what it is now, which translated means "City buses of Toruń". For that purpose I made a [Wikipedia article](https://pl.wikipedia.org/wiki/Komunikacja_miejska_w_Toruniu) and a [Wikidata entry](https://www.wikidata.org/wiki/Q121863259), which previously didn't exist.

Fortunately there weren't many changes made using that feature, as illustrated by [overpass turbo](https://overpass-turbo.eu/s/1zpx). All of them were made by me and I take full responsibility for updating them if this change comes into effect.

It would also be nice to add the tram transit network with the same name, as it is managed by the same organizer.

Excuse me for the trouble caused, I am still learning and trying new things. Thank you for understanding.

**Comment by UKChris-osm** [comment]
Thank you for interacting with your local mapping community and amending your original entry @RCRalph
