### ISSUE TITLE
Filters on nsi.guide are jumping around now

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#8576]
They move when you type in them 🤔 

![filters move](https://github.com/osmlab/name-suggestion-index/assets/38784/4a662db4-d771-408d-bbc0-818a40ca0769)

**Comment by UKChris-osm** [comment]
It looks like the class setting is switched when you type, before it's `class="filters"` but when you type it becomes `class="filtersactive"`

**Comment by vrun1208** [comment]
Hi @UKChris-osm, seems I figured it out, actually there is junk code in `docs/index.js` and I made a little change there and it is working. will soon open a PR
