### ISSUE TITLE
List of banks in India

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#8594]
- [x] Andhra Pradesh Grameena Vikas Bank (Q18109664)
- [ ] Bihar Gramin Bank (Q28170047)
- [x] Madhyanchal Gramin Bank (Q6727651) 
- [x] Maharashtra Gramin Bank (Q16915974)
- [x] Mizoram Rural Bank (Q60764014)
- [x] Odisha Gramya Bank (Q18356206)
- [x] Puduvai Bharathiar Grama Bank (Q17014664)
- [x] Tamil Nadu Grama Bank (Q108166718)
- [x] Tripura Gramin Bank (Q18354573)
- [ ] Aryavart Gramin Bank (Q4802664)
- [ ] DBS Bank (Q705417)
- [x] Jana Small Finance Bank (Q65122274)
- [x] Capital Small Finance Bank (Q106311248)

**Comment by serhii-muchychka** [comment]
@bponkishore please confirm names for "Bihar Gramin Bank" and "Aryavart **Gramin** Bank".  They are called "**Dakshin** Bihar Gramin Bank" and "Aryavart Bank" in their websites
