### ISSUE TITLE
Sanitization Italian fuel stations (Erg, TotalErg, IP, Api, Api-IP, Agip, Eni)

### ISSUE THREAD

**Issue by DnaX** [osmlab/name-suggestion-index#8597]
**Brands ceased to exists:**

* Erg: [erg-e8f712](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#apiip-e8f712)
* TotalErg: [totalerg-e8f712](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#totalerg-e8f712)
* Api: [api-e8f712](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#api-e8f712)
* Api-Ip: [apiip-e8f712](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#apiip-e8f712)
* Agip: [agip-b3d110](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#agip-b3d110)
* Agip Eni: [agipeni-e8f712](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#agipeni-e8f712)

**History of company selling/merging:**

* Erg -> TotalErg -> IP
* Api -> Api-Ip -> IP
* Agip > Agip Eni -> Eni

In 2007 Api bought IP and rebrand all API station with IP.
Erg ceased to exist since the 2010 after creating the joint-venture with Total, TotalErg. This last one ceased to exists in January 2018 and the all the network passed to IP.

Agip was the old brand of Eni used for their fuel station, at least in Italy now all the fuel stations are rebranded to Eni.

**Name matches proposed:**

* "Erg", "TotalErg", "Api", Api-Ip" should be matchName for IP
* "Agip" and "Agip Eni" should be matchName for Eni

**Then a doubt about Eni:**

Why we have both Eni [eni-4e932a](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#eni-4e932a) and Eni Station [enistation-4e932a](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#enistation-4e932a)? All the fuel stations are branded only with "Eni" even if the official website call them "Eni Station". See for reference: https://commons.wikimedia.org/wiki/File:Eni_(Lentiai).jpg

Is not better to keep visible brand name of the POI and not other nomenclature?

**Comment by kjonosm** [comment]
> Why we have both Eni [eni-4e932a](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#eni-4e932a) and Eni Station [enistation-4e932a](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#enistation-4e932a)? All the fuel stations are branded only with "Eni" even if the official website call them "Eni Station".

For a similar situation see #8412. There it was decided to preserve specific `name` variants but conflate all `brand` variants to one agreed upon value. I believe this approach could also work for your issue.
