### ISSUE TITLE
How to solve warning about missing English label in Wikidata?

### ISSUE THREAD

**Issue by kjonosm** [osmlab/name-suggestion-index#8622]
How to solve messages in [warnings.json](https://github.com/osmlab/name-suggestion-index/blob/67dbd4f889151f599ab525bab014a76330c9af19/dist/warnings.json#L965C15-L965C25) about missing English labels in Wikidata when a Latin version doesn't exist, e.g. for [this](https://www.wikidata.org/wiki/Q121464345) Ukrainian beverage retailer?

Should one add a transliterated English label to the Wikidata item, copy the Wikidata label from the original alphabet or just ignore the warning in NSI?

**Comment by bhousel** [comment]
> Should one add a transliterated English label to the Wikidata item, copy the Wikidata label from the original alphabet or just ignore the warning in NSI?

I'd add a transliterated name probably - but it's not really important.  It's probably safe to ignore if you aren't familiar with the brand.  I think it does help the Wikidata project to have the names of things filled in in different languages, but it's probably better for people with translation experience doing this.

If we have an English label, we display it on nsi.guide like this:
<img width="1158" alt="Screenshot 2023-09-10 at 12 12 27 AM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/23ac2d48-69ac-446b-81bd-81eab040fad4">
