### ISSUE TITLE
Can a preset be made for National Weather Service? 

### ISSUE THREAD

**Issue by RyanWatern** [osmlab/name-suggestion-index#8629]

**Comment by arch0345** [comment]
Thanks for opening this issue! I added it around a week ago (https://github.com/osmlab/name-suggestion-index/commit/0f02eee2c6903e23076e2f5d87a5c83fe4357e0e), however didn't get a change to publish a new release until today. It should now show up in the editor

**Comment by RyanWatern** [comment]
Thank you very much!
