### ISSUE TITLE
Is JustPark a brand and not an operator?

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#8716]
When passing a local car park that uses JustPark, I noticed that according to the sign another company UK Car Park Management (Q122889231) manages the car park. Would it be correct to say that JustPark is the brand and only handles bookings with its technology platform, whilst UK Car Park Management is the operator? I've attached a photo of the sign

![IMG_20230930_110529](https://github.com/osmlab/name-suggestion-index/assets/2069958/9b7c142e-6b24-496a-872e-847910919660)

**Comment by UKChris-osm** [comment]
Yes, JustPark are only a payment / booking brand, I don't think they operate any car parks, just offer the ability to pay for parking (I think they started out as just for private driveways to be rented out).
