### ISSUE TITLE
Include Orlen also in Slovakia (sk)

### ISSUE THREAD

**Issue by Filip10** [osmlab/name-suggestion-index#8814]
https://nsi.guide/index.html?t=brands&k=advertising&v=totem&tt=orlen
https://nsi.guide/index.html?t=brands&k=amenity&v=car_wash&tt=orlen
https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=orlen

They already have few tens of stations in Slovakia https://www.orlen.sk/stanice

**Comment by Cj-Malone** [comment]
Thank you
