### ISSUE TITLE
Rocket Stores

### ISSUE THREAD

**Issue by maxerickson** [osmlab/name-suggestion-index#8828]
Convenience brand: https://rocketstores.com/rocket-stations/

Q121513516

It's a rebrand of another hard to search for brand: https://www.retailwatchers.com/viewtopic.php?t=2790

**Comment by AntiCompositeNumber** [comment]
https://www.wikidata.org/wiki/Q121513516

Looks like there are no `brand=My Goods Market`, 22 `name=My Goods Market`, 1 `brand=Rocket`, 31 `name=Rocket`. All appear to be in the US, in Washington, Oregon, California, and Colorado. The https://rocketstores.com/rocket-stations/ station finder is not very good, so I can't really confirm that. Zooming in to the stations that appear to be in Mexico moves them to the other side of the border.

**Comment by Cj-Malone** [comment]
Their data says 453 locations, in CA, CO, OR, WA (no Mexico). You can get view the [data here](https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/6784949835/rocket_us/output.geojson) or download the [geojson here](https://data.alltheplaces.xyz/ci/6784949835/rocket_us/output.geojson).

I don't know the specifics of Rocket, but I think the system in general is that a company (Rocket) operates a site. That site will have fuel branded by one of the big ones (In this case 76, Chevron, Conoco, Phillips 66, Shell, United Oil), the shop may also be branded by one of the big convenience store chains (or in this case Rocket are self branding the stores), the site may also have other things that may or may not be "branded" like air pumps and car washes.

At this stage nobody in OSM really cares about the operator of the site (Rocket), but they do care about the brands of the shop (Rocket) and fuel station (76, Chevron, Conoco, Phillips 66, Shell, United Oil).

So yeah, at this stage I think NSI only needs Rocket as a convenience store.
