### ISSUE TITLE
Villo! rental bicycle should not have operator=Cyclocity

### ISSUE THREAD

**Issue by bxl-forever** [osmlab/name-suggestion-index#8872]
There is a rental bicycle scheme in Brussels, Belgium.  The brand name is Villo! and it is operated by French avertising company JCDecaux.

The index contains a reference to operator=Cyclocity.  This will consequently raise a suggestion in the iD editor to "upgrade the tags".
https://nsi.guide/index.html?t=brands&k=amenity&v=bicycle_rental&tt=villo

We believe this reference is incorrect.  Contrary to some cities in France, JCDecaux does not use the "Cyclocity" name at all in our country.  The service is branded as Villo! and the operator should be JCDecaux and not Cyclocity.

````
< operator=Cyclocity
< operator:wikidata=Q3008464
---
> operator=JCDecaux
> operator:wikidata=Q74877
````

**Comment by Cj-Malone** [comment]
Rel: #8682

Do you think this is just an issue for Villo?

**Comment by bxl-forever** [comment]
There was a bicycle rental schema operated as Cyclocity before 2009 but it had a very poor image because it didn’t meet users’ requirements.  As a consequence, when JCDecaux introduced the current Villo! scheme they carefully removed every reference to Cyclocity.  This is for Brussels.

They operate the same devices in other cities, e.g. [Dublin](https://www.dublinbikes.ie/en/legal-information/legal-notices) [Lyon](https://velov.grandlyon.com/fr/legal-information/legal-notices) and there is no single mention of Cyclocity on those websites either.  I understand the PR had a good intention to reflect the name of the (presumably internal) department in charge of the bicycle service, but from the customer’s point of view the "operator" is still JCDecaux.
