### ISSUE TITLE
Add other names to already existing NS (Despar)

### ISSUE THREAD

**Issue by DomHeadroom** [osmlab/name-suggestion-index#8924]
The [NS](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=despar) has not only the name Despar but it can be found with the 2 other names "Eurospar" and "Interspar", as even stated in their website [here](https://www.despar.it/it/punto-despar/) "Despar fa la sua comparsa in Italia nel 1960 e rappresenta l'insegna originaria da cui nasceranno nei decenni successivi Eurospar e Interspar" translated in eng "Despar made its appearance in Italy in 1960 and represents the original brand from which Eurospar and Interspar will be born in the following decades"

**Comment by bhousel** [comment]
Looks like we have all these names now..
