### ISSUE TITLE
Add Персона (Persona) 

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#8931]
It looks like [Персона (a378c7-0c474f)](https://nsi.guide/index.html?t=brands&k=shop&v=beauty&tt=%D0%9F%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0#a378c7-0c474f) corresponds to https://persona.ru based on https://overpass-turbo.eu/s/1Dgz. However, that website is broken and their social media (https://twitter.com/Persona_PR https://vk.com/lab_persona https://www.instagram.com/persona.original/ ) all haven't been updated recently. My ability to do research in Russian is limited, so can someone find out if this company is still a going concern and create a Wikidata item if so?

**Comment by bhousel** [comment]
I added the `beauty=cosmetics` tag , set the locationSet to `'ru'`, and added `name:en` and `brand:en` to as "Persona" so we can find it again later.

There still isn't a Wikidata or Wikipedia that I can find for this brand, so someone will have to add it.

**Comment by Cj-Malone** [comment]
@panasonic-mafia do you have any knowledge on this one?

**Comment by panasonic-mafia** [comment]
Thanks. I made a Wikidata item for it. Their instagram is the only social account I'm sure about, I was not able to find reliable vk.com or twitter pages.

**Comment by Cj-Malone** [comment]
And [here](https://www.openstreetmap.org/node/4722163889#map=19/55.74309/37.42875) is one that was edited a few hours ago. I think this is good to be closed, thank you everyone.
