### ISSUE TITLE
The full network brand exprés.cat is being recommended over the provincial exprés.cat (Barcelona)

### ISSUE THREAD

**Issue by AmyMagdalena** [osmlab/name-suggestion-index#8952]
It seems that when there is wikidata in the relation, that the network label of exprés.cat (Barcelona) is being ignored over exprés.cat.

I think this can be fixed by adding the wikidata tags to the provincial sub-networks.

Btw, it would also help if the other 2 provinces of Catalunya were added.

![imatge](https://github.com/osmlab/name-suggestion-index/assets/98350291/7df58a66-fc0d-46e4-b177-eb541b527e6a)

![imatge](https://github.com/osmlab/name-suggestion-index/assets/98350291/a7f9dcc6-167f-4652-acf2-221cef101c68)

```
colour=#009383
from=Barcelona
name=e9: Barcelona - Palau Solità i Plegamans - Caldes de Montbui
network=exprés.cat (Barcelona)
network:wikidata=Q8847125
network:wikipedia=ca:Exprés.cat
operator=Sagalés
public_transport:version=2
ref=e9
route=bus
to=Caldes de Montbui
type=route
via=Palau Solità i Plegamans
```

**Comment by UKChris-osm** [comment]
At the moment neither `exprés.cat (Barcelona)` or `exprés.cat (Tarragona)` will appear as a suggestion as neither have a `network:wikidata` assigned. Adding a `network:wikidata` will enable them to be suggested along with the current entry for `exprés.cat`.

Are all three of the above the same network / operator, or are they individual operators which share the name?

**Comment by AmyMagdalena** [comment]
They share the same operator but they share route numbers between provinces and thus are different networks, so I feel it should be 
```
operator=exprès.cat
network=exprès.cat (Barcelona)
```

**Comment by UKChris-osm** [comment]
If they are different Networks then it might be best to create a Wikidata for each one (Barcelona), so they can be differentiated. We can also use more precise geotagging to prevent them from overlapping.
