### ISSUE TITLE
N Family Club

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#8957]
I've created a [Wikidata entry for N Family Club](https://www.wikidata.org/wiki/Q123476376), though I am not sure if it should be treated as `amenity=kindergarten` or `amenity=childcare`, as there are existing examples using either tag.

**Comment by UKChris-osm** [comment]
Are they only UK based? If so, I'd probably go for `amenity=childcare`.

**Comment by codeinabox** [comment]
> Are they only UK based? If so, I'd probably go for `amenity=childcare`.

Yes just based in the UK, though according to their website they also offer a curriculum if that changes anything https://nfamilyclub.com/our-curriculum/
