### ISSUE TITLE
Wikidata item Q122839963 for "Crown Decorating Centre" has been deleted

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#8995]
Wikidata item Q122839963 which is referenced in the NSI entry for "Crown Decorating Centre" (crowndecoratingcentre-058646) https://github.com/osmlab/name-suggestion-index/blob/ef81ea1ddc5eb9d318136b8d00f8a70dfbba4dd7/data/brands/shop/paint.json#L111 has been deleted as "non-notable" https://www.wikidata.org/wiki/Q122839963 .

I'm afraid I don't know enough about Wikidata's rules to know whether the deletion was correct or not, or how to go about restoring it if not. But as far as NSI is concerned, we shouldn't be linking to a non-existent Wikidata item, as this will cause bad data to be added to OSM.

**Comment by Cj-Malone** [comment]
With 156 locations, it will probably get restored. https://www.crowndecoratingcentres.co.uk/stores

I can request it be restored tomorrow, unless you want to do it sooner. I've got some notes:

https://github.com/osmlab/name-suggestion-index/pull/8475#issuecomment-1665543134

**Comment by AntiCompositeNumber** [comment]
The wikidata item was quite sparse, consisting only of a link to their website, facebook, instance of business, and a link back to NSI. It's not surprising that a Wikidata admin saw it as spam.
The brand is owned by https://www.wikidata.org/wiki/Q5189421, (with two sitelinks), so there is a structural need argument for restoration as well. That would have been very useful if it had been linked.

We should improve https://github.com/osmlab/name-suggestion-index/wiki/Editing-Wikidata#creating-wikidata-pages with more advice to contributors on how to prevent items from being deleted and what to do when it happens.

**Comment by Cj-Malone** [comment]
Sorry it took so long, I've requested an [undeletion](https://www.wikidata.org/wiki/User_talk:Lymantria#Request_undeletion_of_Q122839963).

@AntiCompositeNumber, since you can see the page, does that mean you are a Wikidata admin? I don't really know the Wikidata details, compared to how much I know about OSM.

Admittedly, I rarely do described at URL or references, but if you could add more details to that page it would be helpful.

**Comment by AntiCompositeNumber** [comment]
I'm a [Steward](https://meta.wikimedia.org/wiki/Stewards), which means I have administrator access on all Wikimedia wikis. However, I can only use that access when there are no local administrators on a particular wiki. I can read deleted pages on Wikidata, but I can not restore them.

**Comment by Cj-Malone** [comment]
This item has been restored. Thanks everyone.

**Comment by 1ec5** [comment]
> We should improve https://github.com/osmlab/name-suggestion-index/wiki/Editing-Wikidata#creating-wikidata-pages with more advice to contributors on how to prevent items from being deleted and what to do when it happens.

[This wiki page](https://wiki.openstreetmap.org/wiki/Key:brand:wikidata#Establishing_notability) has some tips for establishing notability, which can be copied over to the NSI wiki page.
