### ISSUE TITLE
Add operator Infraestruturas de Portugal to power=substation

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#8998]
Add operator Infraestruturas de Portugal to power=substation in Portugal

https://nsi.guide/index.html?t=operators&k=route&v=railway&tt=infraestr

**Comment by DiogoBaptista98** [comment]
its not working

**Comment by AntiCompositeNumber** [comment]
NSI data is released periodically, usually once a week. This data was added after last week's release, and no release has been made since then yet. The new data will be available in editors after that happens.
