### ISSUE TITLE
Pizza Hut is listed as a restaurant instead of fast_food

### ISSUE THREAD

**Issue by mp747474** [osmlab/name-suggestion-index#9019]
The name suggestion index suggests that Pizza Hut is a restaurant (amenity=restaurant).

In Germany, and I'd say in most other countries too, Pizza Hut is not considered a fine dining restaurant but rather a fast food place. The wiki also suggests it should be fast_food and not restaurant: https://wiki.openstreetmap.org/wiki/List_of_brands

It also creates an inconsistency with Pizza Hut Delivery, which *is* listed as fast_food, with the fatal result that if one adds an amenity=fast_food with name "Pizza Hut", iD wants to match it with Pizza Hut Delivery instead, which is something completely different.

**Comment by UKChris-osm** [comment]
I'd disagree from a UK perspective, patrons enter a Pizza Hut and are seated, order at the table from a host, and dine at the table in the same way they would if they ordered a pizza from any other restaurant. Pizza Hut Delivery locations tend to have an over the counter order system for walk ins, which seems fitting for the fast food tagging.

If it's different in Germany, this can be localised if need be.

**Comment by mp747474** [comment]
I opened the bug because I noticed in Germany, KFC and Pizza Hut often share the same premises, and both patrons sit at the same table, and it is really confusing then that one should be a fast_food and the other a restaurant when they're literally the same thing, with the exception of the kind of food you get.

**Comment by trigpoint** [comment]
Certainly not the case in the UK. In Pizza Hut you are served by a waiter who brings your food to your table on a plate along with wine, beer or soft drinks in a glass.

Sounds like it need to be localised for Germany.

**Comment by 1ec5** [comment]
Yes, we should have a separate entry for Pizza Hut in Germany in that case. (There’s a similar distinction in the U.S., but the fast food format is called Pizza Hut Express, and the sit-down format is sometimes branded [Pizza Hut Classic](https://ronnysalerno.com/queencitydiscovery/pizza-hut-classic-wholesome-nostalgia-vs-newstalgia).)

**Comment by andrewpmk** [comment]
There's two types of Pizza Hut locations, some are take out/delivery only and some are sit down restaurants. How do we distinguish between them?

**Comment by 1ec5** [comment]
A takeout/delivery-only Pizza Hut would still be a `restaurant` because they only cook to order. An example of a takeout-only `fast_food` would be [Sbarro](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=sbarro#sbarro-658eea) – they have the pizzas already baked, sitting under a heatlamp for you to grab and go.

**Comment by LaoshuBaby** [comment]
~~From a Chinese perspective I'd like to decide whether a place should be restaurant or fast_food by cuisine~~ 
(Sounds rediculous)

For me I'll check the [Judge Case](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case) wiki page and a found an instructive comment

> For the restaurant/fast_food question, I believe the convention is that
> 
>     * `amenity=restaurant` for a place where a host seats you and a waiter takes your order (aka "table service"), and
> 
>     * `amenity=fast_food` for a place where you order food from a counter (includes ["fast casual"](https://en.wikipedia.org/wiki/Fast_casual_restaurant) style)
> 
> From https://github.com/osmlab/name-suggestion-index/pull/4987#issuecomment-803636623

So I'm not thinking about whether takeout is allowed (or only), but whether Pizza Hut in Germany has service staff and how you would order (I don't think whether food is pre-maked or not is a criterion for fast food, as in China a lot Complex snacks also require pre-made semi-finished products)

If Pizza Hut in Germany does look more like a fast food like KFC, I think we can split it as a localized entry

**Comment by andrewpmk** [comment]
I think there need to be 2 entries because there are Pizza Huts in Canada that are sit down restaurants and locations that are take out/delivery only. I believe the latter are more common. I'm sure it's like this in other countries as well.

**Comment by bhousel** [comment]
We already do have a multiple entries for Pizza Hut in NSI:
- Pizza Hut Express is `amenity=fast_food`
- Pizza Hut is `amenity=restaurant`

Both are set up as worldwide brands.  I think people can already just pick the one that applies?

I did some internet searching for Pizza Hut in Germany, and the situation there looks like everywhere else.. Some are sit down restaurants with table service, and some are cafeteria style fast food (usually branded as "express").
