### ISSUE TITLE
Target (USA) vs. Safeway US

### ISSUE THREAD

**Issue by TheAdventurer64** [osmlab/name-suggestion-index#9033]
I was looking at brand tags for Target and Safeway chains in the US, and I noticed that the way they distinguish their region is different from each other:

<img width="369" alt="Screenshot 2023-12-16 at 12 14 22 PM" src="https://github.com/osmlab/name-suggestion-index/assets/50059322/64e6199d-9a0f-4aeb-9160-76a87f090477">
<img width="373" alt="Screenshot 2023-12-16 at 12 15 17 PM" src="https://github.com/osmlab/name-suggestion-index/assets/50059322/6ae6e49d-40a1-4e2d-b899-c0f9859aef8f">

I think that the way Target does it should be preferred, as it is accustomed to how other brands are distinguished by their region, like with the different Foodland brands: 
<img width="480" alt="Screenshot 2023-12-16 at 1 54 51 PM" src="https://github.com/osmlab/name-suggestion-index/assets/50059322/bde9863a-656a-41e5-b8f5-d214a3652a92">

**Comment by AntiCompositeNumber** [comment]
Yes, the convention is to use parentheses for disambiguation per https://github.com/osmlab/name-suggestion-index/wiki/Contributing#displayname-required.
