### ISSUE TITLE
powerdot matchIndex errors

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#9069]
```
⚠️   Warning - matchIndex errors:
----------------------------------------------------------------------
  `key/value/name` occurs multiple times in the match index.
  To resolve these, make sure the key/value/name does not appear in multiple trees
    (e.g. `amenity/post_office/ups` should not be both a "brand" and an "operator"
----------------------------------------------------------------------
Duplicate cache key "man_made/charge_point/powerdot" in trees "operators" and "brands", check items: powerdot-009624
Duplicate cache key "amenity/charging_station/powerdot" in trees "operators" and "brands", check items: powerdot-f718d2,powerdot-a1285d
total 2
```
Looks to be caused by 7516420d1e (cc @andrewpmk )

**Comment by LaoshuBaby** [comment]
like #7712 we may need to pick one of two

**Comment by andrewpmk** [comment]
Oops that one was my fault
Since it's a warning it doesn't prevent merging

there's these duplicate entries:
In brands
{
      "displayName": "Powerdot",
      "id": "powerdot-f718d2",
      "locationSet": {
        "include": ["es", "fr", "pl"]
      },
      "tags": {
        "amenity": "charging_station",
        "brand": "Powerdot",
        "brand:wikidata": "Q123574541",
        "name": "Powerdot",
        "operator": "PowerDot",
        "operator:wikidata": "Q123574541"
      }
    }

In operators
{
      "displayName": "Power Dot France",
      "id": "powerdotfrance-c22d3a",
      "locationSet": {"include": ["001"]},
      "tags": {
        "amenity": "charging_station",
        "operator": "Power Dot France"
      }
    },

{
      "displayName": "Powerdot",
      "id": "powerdot-a1285d",
      "locationSet": {"include": ["pt"]},
      "tags": {
        "amenity": "charging_station",
        "operator": "Powerdot"
      }
    }

From what I can tell, this company operates in France, Spain, Portugal and Poland https://powerdot.eu/en

**Comment by andrewpmk** [comment]
Which entry do you want to remove? I think "Power Dot France" and "Powerdot" are the same
