### ISSUE TITLE
Change TD Canada Trust to TD

### ISSUE THREAD

**Issue by andrewpmk** [osmlab/name-suggestion-index#9086]
TD (Toronto-Dominion Bank) seems to be gradually retiring the brand name TD Canada Trust on their bank branches and simply using TD instead. Not sure if all their branches have changed I think only recently built/renovated branches have been updated. Should we update the "TD Canada Trust" preset to change it to "TD"?

Example: Yonge/Eglinton in Toronto https://mapilio.com/app?lat=43.706596899427666&lng=-79.39830601215363&zoom=17&pId=4689896 (newly built branch)
Kipling/Bloor in Toronto https://mapilio.com/app?lat=43.64099787626225&lng=-79.53942775726318&zoom=17&pId=5074037 (2019 Mapillary imagery shows TD Canada Trust on sign)

Example of non-updated branch: https://mapilio.com/app?lat=43.64822981243063&lng=-79.50874078936283&zoom=17.725630811599505&pId=5073828 (Royal York/Bloor, imagery taken December 2023)

**Comment by AntiCompositeNumber** [comment]
Hm. They've been doing something similar in the US, changing "TD Bank" to the same plain "TD" logo (compare https://www.mapillary.com/app/?pKey=3713575712295684 (new) to https://www.mapillary.com/app/?pKey=815571549387180 (old), for instance). https://www.td.com/ca/en/ leans into the plain TD brand slightly more than https://www.td.com/us/en/, which still uses TD Bank in the header.

At what point should we consider these two subsidiaries to be operating under the same brand?

**Comment by bhousel** [comment]
Looks like TD in Canada and TD Bank in USA are actually different banks, and they have different wikidata QIDs.

I set them up like this:
```js
    {
      "displayName": "TD Bank (USA)",
      "id": "tdbank-ea2e2d",
      "locationSet": {"include": ["us"]},
      "tags": {
        "amenity": "bank",
        "brand": "TD Bank",
        "brand:wikidata": "Q7669891",
        "name": "TD Bank",
        "short_name": "TD"
      }
    },
    {
      "displayName": "TD Bank (Canada)",
      "id": "tdcanadatrust-e1345b",
      "locationSet": {"include": ["ca"]},
      "matchNames": ["td bank"],
      "tags": {
        "alt_name": "TD Canada Trust",
        "amenity": "bank",
        "brand": "TD",
        "brand:wikidata": "Q1080670",
        "name": "TD"
      }
    },
```
