### ISSUE TITLE
Suspicious "Union School (historical)"

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#91]
from looking at https://github.com/osmlab/name-suggestion-index/blob/master/name-suggestions.presets.xml

**Comment by matkoniecz** [comment]
- Union School (historical)
- Walnut Grove School (historical)
- Antioch School (historical)
- Bethel School (historical)
- Cedar Grove School (historical)
- Central School (historical)

etc

**Comment by matkoniecz** [comment]
based on http://overpass-turbo.eu/s/yGT it looks like yet another import for cleanup...

Probably the preferable way of handling that is to delete these no longer existing schools and rerun update from data...

**Comment by bhousel** [comment]
I just fixed this - it turns out that we have a `buildJosm.js` script to rebuild the xml file, but it was never being run.  I added the necessary 'xmlbuilder' dependency to the project, and added some lines to the `Makefile` to make sure this file gets rebuilt just like the other files.
