### ISSUE TITLE
Is DTLR shop=shoes or shop=clothes?

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#9107]
It appears there are two entries for DTLR (https://www.dtlr.com/, https://www.wikidata.org/wiki/Q110706217), [one with `shop=shoes`](https://nsi.guide/?t=brands&k=shop&v=shoes&tt=dtlr#dtlr-c5ede1) and [one with `shop=clothes`](https://nsi.guide/index.html?t=brands&k=shop&v=clothes&tt=dtlr#dtlr-0a21d9). The `=shoes` entry has `brand:wikidata`, the `=clothes` entry does not.

I'm not familiar with the brand, but looking at their website it seems like they sell both clothes and shoes.

**Comment by bhousel** [comment]
Probably `shop=clothes`

Nike, Adidas, Puma, and Under Armour are all in `shop=clothes`.

Adidas is in `shop=sports`, not sure why - I could see them as more clothes too, but this probably doesn't matter much.

It looks like this was brought up in #3482 too, maybe in the last 4 years the tagging has shifted more towards `shop=clothes`.
