### ISSUE TITLE
Is Pro Nails actually a brand?

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#9128]
I was looking at a Pro Nails upgrade suggestion, then I noticed the logo on the sign didn't line up with the one on https://gopronails.com/. Then I noticed that https://gopronails.com/about-us/ says
>  *** [gopronails.com](http://gopronails.com/) is a fan page and does not represent the businesses listed on this website. For 100% accurate information, please contact the location near you. ***
Is this actually a brand? does anyone know anything about this? https://www.wikidata.org/wiki/Q113362663

See #6774

**Comment by matkoniecz** [comment]
https://www.wikidata.org/wiki/Wikidata:Requests_for_deletions#Q113362663

**Comment by AntiCompositeNumber** [comment]
The Wikidata item was deleted, and I have now removed it from the remaining POIs.
