### ISSUE TITLE
add "Regional Transit Coperation (RTC)" bus network on NSI Guide

### ISSUE THREAD

**Issue by OumKaZa** [osmlab/name-suggestion-index#9130]
{
      "displayName": "RTC (Thailand)",
      "id": "rtc-43cc75",
      "locationSet": {"include": ["th"]},
      "tags": {
        "network": "RTC (Thailand)",
        "network:wikidata": "Q124219694",
        "route": "bus"
      }
    },

**Comment by kjonosm** [comment]
superseded by #9302
