### ISSUE TITLE
dissolved, abolished or demolished date (P576) claims with qualifier excluding (P1011) = brand name (Q168678)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#9134]
Amoco is listed as dissolved brand at https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=Amoco&dis=true

Probably because its Wikidata entry has dissolved, abolished or demolished date (P576) property.

But it has qualifier excluding (P1011) = brand name (Q168678) - see https://www.wikidata.org/w/index.php?title=Q465952&diff=prev&oldid=2045503085

Maybe such cases should be excluded from being listed as dissolved? Or listed as candidates for creation separate wikidata entry for brand itself?

See https://www.wikidata.org/w/index.php?title=User:Mateusz_Konieczny/failing_testcases&oldid=2045586472#Existing_brands_with_dissolved,_abolished_or_demolished_date_(P576)_claims for some similar cases (I reported it to Wikidata community, someone decided to fix in this way, my https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/ QA tool is currently supporting this though maybe it is a bad way of modelling at Wikidata)

**Comment by bhousel** [comment]
Thanks for letting us know, this seems fine..

**Comment by bhousel** [comment]
Ok I just ran the wikidata sync script..  Now it looks like Agip, Amoco, and Radio Shack are not on the dissolved list anymore because of the 'excluding' = 'brand name' qualifier.
