### ISSUE TITLE
Is Wahlburgers fast_food or restaurant

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#9140]
Wahlburgers was added to `/data/brands/amenity/fast_food` by @peternewman in 8bd9b87. I did not notice this and later added it to `amenity/restaurant` in fada59d because the ones I had found already mapped were `amenity=restaurant`. I don't know a whole lot about the restaurant, but based on https://wahlburgers.com/careers and https://wahlburgers.com/faqs it sounds like they have table service. Can anyone confirm this?

**Comment by bhousel** [comment]
Looks like a restaurant from photos on their website 🤷
