### ISSUE TITLE
Add French universities

### ISSUE THREAD

**Issue by ErnestoLaPomme** [osmlab/name-suggestion-index#9181]
Hello,

Is it possible to add these French universities?

Thank you and good luck!

- [ ] université d'Aix-Marseille (Q2302586)
- [ ] Institut national polytechnique de Toulouse (Q3152453)
- [ ] Sorbonne-Université (Q41497113)
- [ ] université Bordeaux-Montaigne (Q13342)
- [ ] université Claude-Bernard-Lyon-I (Q4032)
- [ ] université Jean-Moulin-Lyon-III (Q4027)
- [ ] université Paul-Valéry-Montpellier-III (Q2912244)
- [ ] université Paris-Est-Créteil-Val-de-Marne (Q980688)
- [ ] université Paris-I-Panthéon-Sorbonne (Q999763)
- [ ] université Sorbonne-Nouvelle (Q571293)
- [ ] université Sorbonne-Paris-Nord (Q1780212)
- [ ] université Paris-VIII (Q1194988)
- [ ] université Rennes-II (Q459026)
- [ ] université Toulouse-Jean-Jaurès (Q1933558)
- [ ] université Toulouse-III-Paul-Sabatier‎ (Q1273188)
- [ ] université d'Angers (Q1538727)
- [ ] université d'Artois (Q475504)
- [ ] université d'Orléans (Q13334)
- [ ] université Paris-Saclay (Q1531014)
- [ ] université de Bordeaux (Q13344)
- [ ] université de Bourgogne (Q287072)
- [ ] université de Bretagne-Occidentale (Q1857334)
- [ ] université Caen-Normandie (Q568554)
- [ ] université de Corse-Pascal-Paoli (Q335841)
- [ ] université de Franche-Comté (Q829449)
- [ ] université de Haute-Alsace (Q280183)
- [ ] université de La Réunion (Q834819)
- [ ] université de Limoges (Q2661290)
- [ ] université de la Nouvelle-Calédonie (Q734332)
- [ ] université de Nîmes (Q2496121)
- [ ] université de Pau et des pays de l'Adour (Q572968)
- [ ] université de Perpignan - Via Domitia (Q304872)
- [ ] université de Picardie (Q947747)
- [ ] université de Poitiers (Q661056)
- [ ] université de Reims-Champagne-Ardenne (Q2496149)
- [ ] université de Rouen-Normandie (Q494247)
- [ ] université Jean-Monnet-Saint-Étienne (Q623154)
- [ ] université Savoie-Mont-Blanc (Q2496158)
- [ ] université de Strasbourg (Q157575)
- [ ] université de Toulon (Q1816857)
- [ ] université de Tours (Q494335)
- [ ] université de Versailles-Saint-Quentin-en-Yvelines (Q186638)
- [ ] université des Antilles (Q16682075)
- [ ] université du Havre (Q1784954)
- [ ] université du Littoral-Côte-d'Opale (Q3551755)
- [ ] université du Mans (Q834825)
- [ ] CY Cergy Paris Université (Q74452784)
- [ ] université de Nantes (Q259388)
- [ ] université Clermont-Auvergne (Q1319786)
- [ ] université Côte-d'Azur (Q19370961)
- [ ] université Grenoble-Alpes (Q945876)
- [ ] université Gustave-Eiffel (Q65153823)
- [ ] université Paris sciences et lettres (Q1163431)
- [ ] université Toulouse Capitole (Q590201)
- [ ] université Paris-Cité (Q55849612)
- [ ] université Paris-Panthéon-Assas (Q662976)
- [ ] université de Lille (Q3551621)
- [ ] université de Montpellier (Q776223)
- [ ] université de Rennes (Q1987282)
- [ ] université polytechnique Hauts-de-France (Q1548539)

**Comment by ErnestoLaPomme** [comment]
After checking, I have deleted all universities with fewer than 3 campuses and/or sites

**Comment by bhousel** [comment]
Oh this was #9402 which I closed yesterday.

We don't add individual colleges or universities to this index - we only add the kind of for-profit "universities” that operate like a branded business in multiple locations, such as DeVry or University of Phoenix. I know this is an unusual concept outside of the USA - the “universities” in the name-suggestion-index are really more like training centers than true universities.

The NSI project is for collecting common tags used by lots of stuff, not just single features.
You should probably go through your list and just update the items on OSM one by one.
