### ISSUE TITLE
Invalid crsf token when running Wikidata script

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#9182]
When running `npm run wikidata`, it keeps giving me this error about an invalid crsf token:
<img width="419" alt="image" src="https://github.com/osmlab/name-suggestion-index/assets/85302075/6e54d53f-fcf0-4ce2-ac32-927794f75074">
I haven't changed my Wikibase password and can still access/modify Wikidata through the web interface

**Comment by bhousel** [comment]
oh thats weird.. I will check if I get this too
`wikibase-edit` can be updated to v6, maybe I should do that.

**Comment by Cj-Malone** [comment]
wikibase-edit was updated to 7.0.3 in #9353. It hasn't fixed it, nor if we revert to 6.0.4 gives me "403 Forbidden".

[This](https://github.com/maxlath/wikibase-edit/issues/43#issuecomment-658118563) suggests we should be using OAuth, but NSI would have to apply for that.

**Comment by panasonic-mafia** [comment]
@arch0345 possible typo in `"token_Secret": "••••••••••"`? Template says it should be `"token_secret"`.
