### ISSUE TITLE
Use UK Specific brand:wikidata tag for Mail Boxes Etc.

### ISSUE THREAD

**Issue by rjw62** [osmlab/name-suggestion-index#9183]
https://nsi.guide/index.html?t=brands&k=amenity&v=post_office&tt=mail%20boxes

Currently in mailboxesetc-27cb18 NSI suggests the global Mail Boxes Etc wikidata item for all objects: https://www.wikidata.org/wiki/Q1139182 .

However, there is specific Wikidata item for the UK subsidiary: https://www.wikidata.org/wiki/Q92922921 .

Should NSI be using Q92922921 instead for UK and Ireland branches of Mail Boxes Etc?

**Comment by UKChris-osm** [comment]
If there's a UK Wikidata available, then yes I think it should be localised.

The only thing I'm unsure about with **Mail Boxes Etc**, is if it's correctly categorised as a _Post Office_?

**Comment by 1ec5** [comment]
OSM has tended to tag businesses of this sort as `amenity=post_office` for a while now. There was a rejected proposal to use [`office=courier`](https://wiki.openstreetmap.org/wiki/Tag:office%3Dcourier) instead. Some mappers have taken to this tag, but I’m concerned that it would easily get confused with a [courier dispatch office](https://wiki.openstreetmap.org/wiki/Talk:Tag:office%3Dcourier#Bicycle_couriers).

**Comment by Cj-Malone** [comment]
Rel: #8290

**Comment by bhousel** [comment]
this was done in [cd81a5b](https://github.com/osmlab/name-suggestion-index/commit/cd81a5b38b5501fc8c2cd9310a6b0d9146b2bd84)
