### ISSUE TITLE
Two errors in the Netherlands: fuel stations TinQ and public transport network Twente.

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#9195]
1) The fuel station brand TinQ in the Netherlands is written with an uppercase T and Q. See for example [their website](https://www.tinq.nl/). The NSI seems to be changing the capital Q to a lowercase q, due to the entries [tinq-56839d](https://nsi.guide/?id=tinq-56839d) and [tinq-dd31d7](https://nsi.guide/?id=tinq-dd31d7).

2) The entries about the public transport network Twente ([twente-948004](https://nsi.guide/?id=twente-948004), [twente-2f3200](https://nsi.guide/?id=twente-2f3200), [twente-0af83a](https://nsi.guide/?id=twente-0af83a) and [twente-c1189c](https://nsi.guide/?id=twente-c1189c)) still point to the wikidata tag of the old concession [Q108741255](https://www.wikidata.org/wiki/Q108741255), instead of the new concession [Q115122964](https://www.wikidata.org/wiki/Q115122964). The network:wikidata tag had been updated for all routes, but they are slowly being reverted to the outdated one due the this error.

Could these issues be solved? Thanks in advance!

**Comment by Dimitar5555** [comment]
Resolved by https://github.com/osmlab/name-suggestion-index/commit/10181d1dc7669cb13d09ac685cbde0cc5ce52488 and https://github.com/osmlab/name-suggestion-index/commit/fedde89043ee6ff21dcb6af4c6985fb2158e59a6.
