### ISSUE TITLE
Research needed for: amenity/restaurant|Тануки

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#921]
#### :thinking: We need help deciding what to do with "amenity/restaurant|Тануки"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/restaurant|Тануки` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/restaurant|Тануки`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/restaurant|Тануки`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
https://www.tanuki.ru/

**Comment by matkoniecz** [comment]
@DmitriiKh Can you check whatever this is actually restaurant chain and whatever tanuki.ru is a good match?

**Comment by DmitriiKh** [comment]
Yes, that's absolutely correct. It's a restaurant chain. I've created Q62758690.
cuisine | Japanese

Sorry, friends, can't make a PM today. A little bit busy this week.

**Comment by DmitriiKh** [comment]
Hi. 
I have a couple of questions before I make my first pull request.

First, after building the project VS Code sees changes in fast_food.json file but I don't. I think I should not submit a PR before I understand why. I think this invisible to me change was done by scripts. Was it? If so it should be safe to submit the file as well, I guess.

Second, should I make a PR just for change in Tanuki data or make more changes to fix more of open issues by one PR?

Sorry for newbie questions. This is gonna be my first contribution.

**Comment by bhousel** [comment]
> First, after building the project VS Code sees changes in fast_food.json file but I don't. I think I should not submit a PR before I understand why. I think this invisible to me change was done by scripts. Was it? If so it should be safe to submit the file as well, I guess.

What does `git diff` show?  If it's just whitespace changes or something in the file getting re-sorted, it's no big deal to include it.

> Second, should I make a PR just for change in Tanuki data or make more changes to fix more of open issues by one PR?

Probably best to just do one at a time until you get more familiar with the process..

Thanks!

**Comment by DmitriiKh** [comment]
It was just whitespaces reducing. Thanks :)

**Comment by matkoniecz** [comment]
> First, after building the project VS Code sees changes in fast_food.json file but I don't.

You may use `[git diff](https://stackoverflow.com/a/10039758/4130619)` or prepare PR and look in tab listing changes. It should display also whitespace changes.

It sometimes happens if other contributors forgot to run `npm run build`.

> Sorry for newbie questions.

Feel free to ask!
