### ISSUE TITLE
pickup-only "supermarkets" should use the "shop=outpost" tag

### ISSUE THREAD

**Issue by tyrasd** [osmlab/name-suggestion-index#9214]
Establishments like "E. Leclerc Drive" where customers can only pick up orders placed before arriving at the location (e.g. online or via telephone) should not use the `shop=supermarket` primary tag, as in a proper [supermarket](https://en.wikipedia.org/wiki/Supermarket) one would assume to be able to choose the to-be-purchased products at the location. Instead these locations should use the tag for "click and collect" pick-up locations, i.e. [`shop=outpost`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Doutpost).

Slightly related is also https://github.com/openstreetmap/id-tagging-schema/pull/1092

**Comment by matkoniecz** [comment]
See

https://github.com/osmlab/name-suggestion-index/blob/565575f7ad3c0e9941b6c2bb24ba1279282c4d05/data/brands/shop/supermarket.json#L2285

https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=leclerc

Seems to be still wrong for now.

**Comment by Cj-Malone** [comment]
If you know any other examples let us know.
