### ISSUE TITLE
Add kokoro

### ISSUE THREAD

**Issue by KasperFranz** [osmlab/name-suggestion-index#9220]
Fast food in UK: https://kokorouk.com/branches/ (72 locations)
wikidata: https://www.wikidata.org/wiki/Q117050264

**Comment by Cj-Malone** [comment]
Looks like 26 have amenity=restaurant, 14 have amenity=fast_food and 4 have amenity=cafe.

**Comment by kjonosm** [comment]
Checking their website and available photos of their branches I think its safe to categorise them as `fast_food`
