### ISSUE TITLE
add Beijer Byggmaterial (swedish hardware store chain) 

### ISSUE THREAD

**Issue by KasperFranz** [osmlab/name-suggestion-index#9230]
**name**: Beijer Byggmaterial 
**wikidata**: [Q10427772](https://www.wikidata.org/wiki/Q10427772)
**Website with branches**: https://www.beijerbygg.se/privat/byggvaruhus

**Comment by kjonosm** [comment]
Is it `Beijer Bygg` or `Beijer Byggmaterial`?

**Comment by KasperFranz** [comment]
Based on what I saw in OSM and their website I would say Beijer Byggmaterial
