### ISSUE TITLE
Add operator Technisches Hilfswerk / THW (German Federal Bureau of ```emergency=disaster_response```)

### ISSUE THREAD

**Issue by qugebert** [osmlab/name-suggestion-index#9231]
https://www.wikidata.org/wiki/Q697698

I would prefer adding only the operator-Tags, because the name-Tag is often used for the local organisation Name, e.g. "name=THW Ortsverband München Ost",  

* ```operator=Bundesanstalt Technisches Hilfswerk``` 
* ```operator:short_name=THW``` 
* ```operator:wikidata=Q697698``` 
* ```emergency=disaster_response```

**Comment by kjonosm** [comment]
@qugebert What do you think of using the `brand` key instead?
See e.g. NSI's [`emergency=ambulance`](https://nsi.guide/index.html?t=brands&k=emergency&v=ambulance_station) entries for reference.

**Comment by qugebert** [comment]
> @qugebert What do you think of using the `brand` key instead? See e.g. NSI's [`emergency=ambulance`](https://nsi.guide/index.html?t=brands&k=emergency&v=ambulance_station) entries for reference.

I guess brand is fine too, if that's common practice here.
Can we exclude name here too? Because most of the existing places already have a extended name (with local branch / "Ortsverband") in the name, i think it would be good to preserve this.

**Comment by kjonosm** [comment]
@qugebert Following https://community.openstreetmap.org/t/richtige-erfassung-von-liegenschaften-des-technischen-hilfswerks/108790/29 I think using `operator` is fine. Has there been an agreement on which exact value to use?

**Comment by qugebert** [comment]
Oops, i didn't recognize this thread
There is a poll for a unique operator value, I keep you updated after that poll is over.

**Comment by qugebert** [comment]
Ok, so we can take 
```
operator=Bundesanstalt Technisches Hilfswerk
operator:short=THW
operator:wikidata=Q697698
emergency=disaster_response
```

This template should only apply to the local branch (probably name "THW Ortsverband"), as THW operates other facilities too (regional bureaus,academies,logistic centres,etc.), where the tagging ``emergency=disaster_response`` would not fit. But these might become their own tagging schema in the future, see (https://wiki.openstreetmap.org/wiki/Proposal:Emergency%3Ddisaster_response#Future_plans)


![grafik](https://github.com/osmlab/name-suggestion-index/assets/44033795/b828d8d5-f67e-405c-aeff-fb94bcaf7ee0)
The ``operator:short_name`` in the [poll](https://community.openstreetmap.org/t/richtige-erfassung-von-liegenschaften-des-technischen-hilfswerks/108790/30) was a mistake, we should use ``operator:short`` as this is the common tag.
