### ISSUE TITLE
Add a Issue Template

### ISSUE THREAD

**Issue by qugebert** [osmlab/name-suggestion-index#9233]
This would make it much easier for people to provide all needed data.
For example, like the template of id-tagging-scheme https://github.com/openstreetmap/id-tagging-schema/blob/main/.github/ISSUE_TEMPLATE/0-enhancement.yaml

I can try to make one

**Comment by bhousel** [comment]
To be honest, I kind of don’t like issue templates.  

I don’t feel like they make it easier to report issues.
