### ISSUE TITLE
Tests should fail when deprecated/forbidden tags are included in a pull request

### ISSUE THREAD

**Issue by rskedgell** [osmlab/name-suggestion-index#9254]
As an occasional contributor, I hadn't noticed that website=* was no longer supported by NSI. That's fine, I understand the reasons for that. However, if it were possible to update the automated tests so that they fail when such a tag is present, that would avoid wasting the time of human reviewers and submitters.

**Comment by bhousel** [comment]
Our build script does already quietly remove these tags
https://github.com/osmlab/name-suggestion-index/blob/b05e4065dcbfc92a3c34ef377b68f38352613ae3/scripts/build_index.js#L531-L536

#5275 and #6481 have more on this..

**Comment by rskedgell** [comment]
Thanks. I hadn't realised that website went at the same time as brand:wikipedia (which I was aware of at the time).
