### ISSUE TITLE
Defunct Brand: Fry's Electronics (brands/shop/electronics)

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#9271]
https://www.wikidata.org/wiki/Q5506545

> On February 24, 2021, Fry's announced the immediate and permanent closure of all of its stores. A statement posted on its website cited "changes in the retail industry and the challenges posed by the [COVID-19 pandemic](https://en.wikipedia.org/wiki/COVID-19_pandemic)"

- [x] Add [dissolved, abolished or demolished date (P576)](https://www.wikidata.org/wiki/Property:P576) to Wikidata item
- [ ] Remove or re-tag existing POIs
- [ ] Remove from NSI

**Comment by AntiCompositeNumber** [comment]
Already marked as defunct in Wikidata and not being distributed in the Index. https://overpass-turbo.eu/s/1HMr shows 8 stores still mapped.

**Comment by CloCkWeRX** [comment]
Actually, I might be a bit confused - the reason I raised it was some tooling did pick it up and I can see 
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/electronics.json#L656 as in the NSI data.
