### ISSUE TITLE
Add Hey Tea

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#9283]
https://www.wikidata.org/wiki/Q60875376

**Comment by UKChris-osm** [comment]
I think it's already in the index: [heytea-4472b7](https://nsi.guide/?t=brands&k=amenity&v=cafe#heytea-4472b7)

**Comment by LaoshuBaby** [comment]
I checked this Entry and the associated Wikidata Item and found no problem. Have you found the brand claiming to be "HeyTea" outside of China (especially Mainland of China) and Singapore?
