### ISSUE TITLE
Add countries to Courir

### ISSUE THREAD

**Issue by DiogoBaptista98** [osmlab/name-suggestion-index#9292]
Add Luxembourg, Spain, Portugal, Morocco, Qatar and Cote d'Ivoire to Courir [courir-423d6f] [https://nsi.guide/index.html?t=brands&k=shop&v=shoes&tt=courir]

Source https://fr.wikipedia.org/wiki/Courir_(chaîne_de_magasins)#Magasins_dans_le_monde

**Comment by phd0** [comment]
{"include":["be","fx", "ci", "lu", "es", "qa", "ma",  "pt"]}

**Comment by bhousel** [comment]
done in #9424
