### ISSUE TITLE
Add Ben Gong's Tea

### ISSUE THREAD

**Issue by arch0345** [osmlab/name-suggestion-index#9297]
https://bengongstea.com.au/
https://bengongstea.ca/
https://bengongstea.id/
https://bengongstea.my/
https://www.bengongstea.us/

It looks like they also have locations in China and Japan

**Comment by LaoshuBaby** [comment]
本宫的茶

I've seen this brand sometimes. Wikidata item was created.

However, they do not have an official website in China (there used to be one, but the domain name expired and was not renewed), and the one in Japan was indeed not found.

**Comment by LaoshuBaby** [comment]
> 本宫的茶
> 
> I've seen this brand sometimes. Wikidata item was created.
> 
> However, they do not have an official website in China (there used to be one, but the domain name expired and was not renewed, It seems that the domestic business is about to close down, but still can search out many branch shop (thus I tend to not add it soon)), and the one in Japan was indeed not found.
