### ISSUE TITLE
Instituto Politécnico Nacional is a university not a school

### ISSUE THREAD

**Issue by heragnar** [osmlab/name-suggestion-index#9321]
Currently, [Instituto Politécnico Nacional](https://nsi.guide/index.html?t=operators&k=amenity&v=school#institutopolitecniconacional-422367) is listed as `amenity=school`, but it should be updated to `amenity=university`.
The official website also directs to a non-ssl option. It should be https://www.ipn.mx/ instead.

**Comment by LaoshuBaby** [comment]
Thank you for your feedback. We've recognized that IPN serves as both a secondary and higher education institution, and we are exploring options to accurately categorize it under both school and university classifications. Additionally, the HTTPS issue should indeed be addressed in the Wikidata entry, which we've corrected.
