### ISSUE TITLE
Please change some code "RTC Thailand"

### ISSUE THREAD

**Issue by OumKaZa** [osmlab/name-suggestion-index#9367]
},
    {
      "displayName": "RTC (Thailand)",
      "id": "rtc-43cc75",
      "locationSet": {"include": ["th"]},
      "tags": {
        "network": "RTC (Thailand)",
        "network:wikidata": "Q124219694",
        "operator": "Regional Transit Corporation",
        "route": "bus"
      }

**Comment by bhousel** [comment]
Oh I guess this is related to #9357  
(Please try to make sure if you open a Pull Request to mention the issue that it relates to). 

I closed it because it seems odd to change the `network` without pointing to a discussion somewhere.
Is there a good reason for this change?
