### ISSUE TITLE
EB Games is now GameStop in Canada

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9375]

**Comment by phd0** [comment]
* [NSI page](https://nsi.guide/index.html?t=brands&k=shop&v=video_games&tt=eb%20games#ebgames-3d1279)
* [overpass turbo page](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22name%22%3D%22EB%20Games%22%5D%3B)%3B%0Aout%20center%3B%0A%0A%7B%7Bstyle%3A%0Anode%2C%0Away%2C%0Arelation%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Bshop%3Dvideo_games%5D%2C%0Away%5Bshop%3Dvideo_games%5D%2C%0Arelation%5Bshop%3Dvideo_games%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Bshop%3Dvideo_games%5D%5Bbrand%3DEB%20Games%5D%5Bbrand%3Awikidata%3DQ4993686%5D%2C%0Away%5Bshop%3Dvideo_games%5D%5Bbrand%3DEB%20Games%5D%5Bbrand%3Awikidata%3DQ4993686%5D%2C%0Arelation%5Bshop%3Dvideo_games%5D%5Bbrand%3DEB%20Games%5D%5Bbrand%3Awikidata%3DQ4993686%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R)
