### ISSUE TITLE
Names of Ukrainian brands

### ISSUE THREAD

**Issue by MortalEngineXXII** [osmlab/name-suggestion-index#9386]
The names of some objects are incorrect — they are too long and somewhat advertising-like. Can you change them to the way they are written in Wikidata?

Brands list https://nsi.guide/index.html?t=brands&k=shop&v=frozen_food

Домашні напівфабрикати «Галя Балувана» > Галя Балувана (https://www.wikidata.org/wiki/Q117744813)
name=Домашні напівфабрикати > name=Галя Балувана
Елікатні радощі життя! > Елікатні продукти (https://www.wikidata.org/wiki/Q123848582)
name=Елікатні радощі життя! > name=Елікатні продукти

**Comment by Cj-Malone** [comment]
Thank you

**Comment by serhii-muchychka** [comment]
![IMG_20240422_223222_185](https://github.com/osmlab/name-suggestion-index/assets/17470298/4fe41367-1f7f-45ed-af1a-d2519662cafb)

**Comment by serhii-muchychka** [comment]
![Uploading 35823-42d38cf9_74c4_4636_81b5_035d79db88bc.jpeg…]()

**Comment by serhii-muchychka** [comment]
Previous names corresponded to the logos of branded stores

**Comment by MortalEngineXXII** [comment]
«Елікатні радощі життя!» — це гасло, очевидно ж. «Домашні напівфабрикати» — вказівка на асортимент товару. Вони так само могли б список товарів там написати. До бренду це ніякого відношення немає і не може мати

**Comment by serhii-muchychka** [comment]
@MortalEngineXXII 
That is why the brand should be "Галя Балувана"
If you look carefully at the OSM DB, the name "Домашні напівфабрикати" is not my invention, they were started to be labeled that way by another mapper, who added most of them

**Comment by MortalEngineXXII** [comment]
Another mapper may be affiliated with the company. That was my first thought when I saw "Домашні напівфабрикати" in the editor
