### ISSUE TITLE
Incorrectly copying the brand tag to name tag for some newly added Dutch brands.

### ISSUE THREAD

**Issue by A67-A67** [osmlab/name-suggestion-index#9387]
I noticed some Dutch brands were newly added. Thanks for that.

However, this has caused the brand name to be copied to the name tag, overwriting the correct name for the individual POI. Could the name overwriting be stopped for these brands?
- Service Apotheek: [serviceapotheek-7bb21a](https://nsi.guide/?id=serviceapotheek-7bb21a) 
- OK: [ok-6cdea6](https://nsi.guide/?id=ok-6cdea6)

**Comment by Cj-Malone** [comment]
I think you are right for Service Apotheek, but wrong on for OK. They are `branch` not `name`, eg [1](https://www.google.com/maps/@52.7496667,6.8737137,3a,40.8y,244.01h,92.69t/data=!3m7!1e1!3m5!1sIloUoMOFDWN26u2zbdzOFg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DIloUoMOFDWN26u2zbdzOFg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D110.07079%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192?entry=ttu) [2](https://www.google.com/maps/@51.956171,4.5493909,3a,75y,191.01h,88.13t/data=!3m6!1e1!3m4!1sBL7WLIxo_ULPSj6NYeSW3A!2e0!7i16384!8i8192?entry=ttu)

However it's not worth an argument. I've changed them.
