### ISSUE TITLE
Best Buy no longer exists in Mexico

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9407]

**Comment by phd0** [comment]
what do you mean ?
* [Best Buy Mobile](https://nsi.guide/index.html?t=brands&k=shop&v=mobile_phone&tt=best%20buy%20#bestbuymobile-947b24)
* [Best Buy Express](https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=best%20buy%20#bestbuyexpress-7e3927)
