### ISSUE TITLE
Add Best Brains

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9408]

**Comment by phd0** [comment]
https://www.wikidata.org/wiki/Q4896597

**Comment by grrla** [comment]
Wrong Wikidata. It's actually a tutoring center chain.

**Comment by bhousel** [comment]
> Wrong Wikidata. It's actually a tutoring center chain.

@grrla when you open these issues can you provide some links to get us started on the research?  
It's kinda time consuming to go through each thing and try to guess what you want.
