### ISSUE TITLE
Add City of London (Ontario) park

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9414]

**Comment by Snowysauce** [comment]
What should the name of the operator be? https://london.ca/living-london/parks-facilities/parks/parks-london refers to "Parks and Recreation", but https://london.ca/government/council-civic-administration/committees-task-forces/standing-committees lists the "Community and Protective Services Committee" as being in charge of "Parks, recreation and neighbourhood services".

**Comment by grrla** [comment]
Parks and Recreation seems more plausible
Sent from my iPhone

On Sep 28, 2024, at 13:19, Snowysauce ***@***.***> wrote:

﻿

What should the name of the operator be? https://london.ca/living-london/parks-facilities/parks/parks-london refers to "Parks and Recreation", but https://london.ca/government/council-civic-administration/committees-task-forces/standing-committees lists the "Community and Protective Services Committee" as being in charge of "Parks, recreation and neighbourhood services".

**Comment by Snowysauce** [comment]
I've given this a bit of thought, and I've added the operator to `operators/leisure/park` as simply "City of London". If the name of the actual city department in charge of parks isn't clear, I didn't feel comfortable using any other name for the NSI/OSM tags nor was I comfortable creating a Wikidata page for the department. The name and Wikidata ID can always be updated later if at some point the department's actual title becomes less ambiguous.
