### ISSUE TITLE
Add City of London (Ontario) community centre

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9415]

**Comment by Snowysauce** [comment]
What is the actual name of the relevant city department? The contact info on https://london.ca/living-london/parks-facilities/community-centres just refers to "Recreation".

**Comment by Snowysauce** [comment]
I've given this a bit of thought, and I've added the operator to `operators/amenity/community_centre` as simply "City of London". If the name of the actual city department in charge of the community centers isn't clear, I didn't feel comfortable using any other name for the NSI/OSM tags nor was I comfortable creating a Wikidata page for the department. The name and Wikidata ID can always be updated later if at some point the department's actual title becomes less ambiguous.
