### ISSUE TITLE
Add Town of Milton park

### ISSUE THREAD

**Issue by grrla** [osmlab/name-suggestion-index#9416]

**Comment by KarenDouglas** [comment]
The Town of Milton Park is considered a  business park, however I dont see it as a brand or amenity in the JSON Files. Where should I add the Town of Milton Park?
This is what I have so far: 
```
    {
      "displayName":"Milton Park",
      "locationSet": {"include": ["gb"]},
      "tags": {
        "operator": "MEPC Group",
        "operator:wikidata": "Q6861373"
      }
    },
```

**Comment by grrla** [comment]
It is a operator of municipal parks in Milton, Ontario, Canada. Not a business park.

https://facilities.milton.ca<https://facilities.milton.ca/>
[https://milton.ic12.esolg.ca/en/images/structure/news_avatar.jpg]<https://facilities.milton.ca/>
Town of Milton Listings<https://facilities.milton.ca/>
Town of Milton Facilities
facilities.milton.ca

________________________________

**Comment by Snowysauce** [comment]
It's not clear to me what the name of the operator should be. The bottom of https://www.milton.ca/en/arts-and-recreation/parks-and-facilities.aspx mentions "Community Services", while the [email link](https://forms.milton.ca/ContactUs/Recreation) for that name goes to a page calling the department "Recreation and Facilities".

**Comment by grrla** [comment]
The webpages are grouped by topic for ease of navigation, but they are not official dept names. I would say Recreation and Facilities.
Sent from my iPhone

On Sep 28, 2024, at 13:10, Snowysauce ***@***.***> wrote:

﻿

It's not clear to me what the name of the operator should be. The bottom of https://www.milton.ca/en/arts-and-recreation/parks-and-facilities.aspx mentions "Community Services", while the email link<https://forms.milton.ca/ContactUs/Recreation> for that name goes to a page calling the department "Recreation and Facilities".

**Comment by Snowysauce** [comment]
I've given this a bit of thought, and I've added the operator to `operators/leisure/park` as simply "Town of Milton". If the name of the actual town department in charge of parks isn't clear, I didn't feel comfortable using any other name for the NSI/OSM tags nor was I comfortable creating a Wikidata page for the department. The name and Wikidata ID can always be updated later if at some point the department's actual title becomes less ambiguous.
