### ISSUE TITLE
[Germany] Add Janny's Eis

### ISSUE THREAD

**Issue by Outlet2048** [osmlab/name-suggestion-index#9421]
https://jannys-eis.com/

Ice cream franchise with many stores in Germany

**Comment by phd0** [comment]
no [wikidata](https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&search=Janny%27s+Eis&fulltext=Rechercher) ID for this. It's better to make it before.

**Comment by riQQ** [comment]
Looks like the linked search on Wikimedia Commons doesn't surface wikidata ids, as the entrance for *Janny's Eis* exists since the end of 2012: https://www.wikidata.org/wiki/Q1229703.
