### ISSUE TITLE
Research needed for: amenity/social_facility|Safe Haven

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#945]
#### :thinking: We need help deciding what to do with "amenity/social_facility|Safe Haven"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/social_facility|Safe Haven` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/social_facility|Safe Haven`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/social_facility|Safe Haven`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
now filtered out

**Comment by 1ec5** [comment]
If Safe Haven is anything like [Safe Place](https://en.wikipedia.org/wiki/National_Safe_Place), then it should be tagged as [`retreat=yes`](https://wiki.openstreetmap.org/wiki/Key:retreat) `retreat:for=child` `retreat:operator=Safe Place` retreat:operator:wikidata=Q6978220` on some existing POI (which could be a fire station, school, etc.). Neither name-suggestion-index nor iD is set up for this kind of auxiliary tagging, but there does seem to be a demand for it. There are a bunch of `Safe Haven`s tagged `amenity=shelter`, which seems suspect.

**Comment by matkoniecz** [comment]
Safe Haven was discarded as a generic term for shelter rather than a specific organization/brand running shelters.
