### ISSUE TITLE
change name from Plug’n Roll to Plug'n Roll

### ISSUE THREAD

**Issue by RepowerCMC** [osmlab/name-suggestion-index#9479]
Hello

can you plaese change the name for 

amenity=charging_station 
operator=Plug’n Roll
operator:wikidata=Q115241443

to:

amenity=charging_station 
operator=Plug'n Roll
operator:wikidata=Q115241443

on OpenStreetMap Tags, NSI Hints, https://nsi.guide/?t=operators&k=amenity&v=charging_station#plugnroll-086737

there is a strange character  ’ for the simicolon and the search on openstreetmap.org is not working with this strange character for the simicolon.

Many thanks and best regards
RepowerCMC

**Comment by UKChris-osm** [comment]
Thanks for catching this @RepowerCMC - all fixed, and should appear in iD soon.
