### ISSUE TITLE
Research needed for: amenity/vending_machine|Dog-Station

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#950]
#### :thinking: We need help deciding what to do with "amenity/vending_machine|Dog-Station"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/vending_machine|Dog-Station` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/vending_machine|Dog-Station`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/vending_machine|Dog-Station`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by maxerickson** [comment]
Seems to be a brand, just not a big one.

http://www.dogstation.de/english.html

https://commons.wikimedia.org/wiki/File:Dog_station,_avenue_de_la_Libert%C3%A9,_D%C3%A9ifferdeng.jpg shows one with the text used as a brand/name.

**Comment by bhousel** [comment]
Nice 🐩 
I guess we can label this as "needs wikidata" for now
