### ISSUE TITLE
https://nsi.guide/?t=brands&k=shop&v=mobile_phone&tt=meO#meo-fcef49

### ISSUE THREAD

**Issue by Ribeiro2002Rafael** [osmlab/name-suggestion-index#9543]
Is Q1365938(https://www.wikidata.org/wiki/Q1365938) and not Q3306167(https://www.wikidata.org/wiki/Q3306167)

**Comment by matkoniecz** [comment]
https://nsi.guide/?t=brands&k=shop&v=mobile_phone&tt=meO#meo-fcef49
