### ISSUE TITLE
Add Thai Cafe

### ISSUE THREAD

**Issue by JoeyKentin** [osmlab/name-suggestion-index#9548]
{
      "displayName": "Thai Cafe",
      "id": "",
      "locationSet": {"include": ["be"]},
      "tags": {
        "amenity": "restaurant",
        "brand": "Thai Cafe",
        "brand:wikidata": "Q115865032",
        "cuisine": "thai",
        "name": "Thai Cafe"
      }
    },

**Comment by Cj-Malone** [comment]
Thanks
