### ISSUE TITLE
Revert e75e60a and only change the name to Aldi instead of ALDI as reported in #9388 / German shop name spelling

### ISSUE THREAD

**Issue by fabi003** [osmlab/name-suggestion-index#9596]
The commit https://github.com/osmlab/name-suggestion-index/commit/e75e60a90b381ed7858ac608ba98360bfec27d05 leads to 
![Bildschirmfoto_20240602_223311](https://github.com/osmlab/name-suggestion-index/assets/110132764/b5328ba9-14b5-42f1-b293-cab32a7d7195)
and should be reverted as it made the whole situation worse.

The brand of the shop in the picture is "ALDI Nord" (as you can see from the right brand of "ALDI Nord") and now should be changed to "Aldi". The shop name is "Aldi", but the brand is "ALDI Nord". To understand the background read #8406.

Before this commit everything was right, at least for Germany, but not the shop name, so  I reported issue #9388 to only change the shop name from "ALDI" to "Aldi". But instead the right brands (which are different from the shop name, which is right) were also changed, besides of some bad "simplifications".

**Comment by fabi003** [comment]
Additional general information for German shop names and brand writing, which should be apply to the most cases:

When the name of the shop is written only in capital letters as for ["NORMA"](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&cc=de#norma-c1eeeb) , then the shop name is in most cases written with only the first letter capitalized, so name=* of the shop is "Norma", but the brand=* should be written as on the shop sign or logo, brand=NORMA in this example. This is why it was reported in #6662.

This also applies to ["Penny"](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&cc=de#penny-55dfd6) (reported for the name in #9337) and ["Rossmann"](https://nsi.guide/index.html?t=brands&k=shop&v=chemist&cc=de#rossmann-06ae64) ([Background information for Rossmann](https://github.com/osmlab/name-suggestion-index/issues/8406#issuecomment-1654548630)). 

In the above cases the name or brand should be changed.

The background is, that over long time the shop name is used as a normal German word, even when it is an longer abbreviation as "EDEKA" (was "E. d. K." in history) or "ALDI" (is/was "**Al**brecht **Di**skont"). And is the name is a normal German name, then only the first letter is capitalized. There are only a few exceptions of very short abbreviations such as "NP", which can't be spoken (it should contain "A", "E", "I", "O" or "U" for this).

The brand style writing (spelling of the brand should be uniform, so the brand is easy recognized again by customers) is valid only, if the brand is written in publications or on the shop sign, but not as a normal German name, which name=* should be. So the brand should be written as on the shop (logo), website or other publications.

If the shop name is written only in lower lower case letters as ["dm"](https://nsi.guide/index.html?t=brands&k=shop&v=chemist&cc=de#dm-1281c9) or ["tegut"](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&cc=de#tegut-0a839e) then the shop name and brand is only written in lower case, as this spelling is allowed in German. So name=dm and brand=dm is right for example.

Also no action is required, if the name is already spelled right in German, with first letter capitalized, such as ["Müller"](https://nsi.guide/index.html?t=brands&k=shop&v=chemist&cc=de#muller-ca019f). Here name=Müller and brand=Müller is right.

I hope this helps you for the future with the spelling of German names.

**Comment by bhousel** [comment]
done in #9630 -  we can check it after the next release and see if it needs further adjustment 👍
