### ISSUE TITLE
Add brand for newspaper vending machines

### ISSUE THREAD

**Issue by PavLL** [osmlab/name-suggestion-index#9653]
```
{
  "displayName": "Punkt dystrybucji biuletynu wroclaw.pl",
  "tags": {
    "amenity": "vending_machine",
    "brand": "wroclaw.pl",
    "brand:website": "https://www.wroclaw.pl",
    "fee": "no",
    "operator": "Agencja Rozwoju Aglomeracji Wrocławskiej",
    "operator:short": "ARAW",
    "operator:wikidata": "Q126685212",
    "vending": "newspapers"
    "website": "https://www.wroclaw.pl/biuletyn"
  }
}
```
with geographic scope: Wrocław, Poland

**Comment by AntiCompositeNumber** [comment]
NSI does not distribute `brand:website` or `website` tags anymore. I created a [Wikidata item for the bulletin](https://www.wikidata.org/wiki/Q129464634), but I noticed that https://www.wikidata.org/wiki/Q126685212 got deleted. I've [asked](https://www.wikidata.org/wiki/Topic:Yauiu6qd25lnd6wf) for it to be undeleted but can't proceed until it is.
