### ISSUE TITLE
Please add Warrior ("回力" in Chinese)

### ISSUE THREAD

**Issue by RicTimeMuseum** [osmlab/name-suggestion-index#9665]
Suggested OSM Tags includes:

name=回力
name:zh=回力
name:en=Warrior
shop=shoes
brand=回力
brand:zh=回力
brand:en=Warrior
brand:wikidata=Q7970760
website=https://www.warriorshoes.com/

**Comment by LaoshuBaby** [comment]
谢谢你提醒我，这确实是一个比较大众化的品牌（我只是没想到它有实体店，大概只是我没见过）

Thank you for notice me about this! This is indeed a quite common brand (I just didn't realize it had physical stores, perhaps I just haven't seen them).

已经通过如下的commit添加

It has been added through the following commit.

https://github.com/osmlab/name-suggestion-index/commit/4179ba12246060151b2fb02f0fd7579215dedaf3

此外，应当指出，按照[Judge case](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case#can-we-add-website-or-phone)，品牌的网站应收录到Wikidata中，而不是OSM。OSM的website键应用于具体的这一元素的网站。

In addition, it should be noted that according to the [Judge case](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case#can-we-add-website-or-phone), the brand's website should be included in Wikidata, not in OSM. The website key in OSM should be used for the specific website of this element.
