### ISSUE TITLE
Add more Goodwill affiliates

### ISSUE THREAD

**Issue by reschultzed** [osmlab/name-suggestion-index#9675]
Following up on [#7323](https://github.com/osmlab/name-suggestion-index/issues/7323), I've created Wikidata items for over 100 Goodwill Industries affiliates that didn't previously have them. They are all listed below, along with three that were on Wikidata but not in the index already. In the absence of any official listing of all affiliates, I believe this covers them all, but there may be some that I missed. Also included are the states in which each affiliate operates, for ease of translation to {"include":["us-XX.geojson"]} format. Each Wikidata item has the headquarters of the affiliate tagged, which could be useful in determining which operator to suggest first in states that have a lot.

Affiliate | Wikidata | State(s)
-- | -- | --
Goodwill Central   Coast | Q114928499 | CA
Goodwill Industries of Houston | Q54624087 | TX
Goodwill Easterseals Miami Valley | Q5583652 | OH
Alabama Goodwill Industries | Q126843253 | AL
Easterseals Goodwill North Dakota | Q126843840 | ND
Evansville Goodwill Industries | Q126844052 | IL,IN,KY
Goodwill Columbus | Q126844141 | OH
Goodwill Easterseals of the Gulf Coast | Q126844308 | AL,FL
Goodwill Industries Big Bend | Q126844466 | FL,GA
Goodwill Industries of Acadiana | Q126844562 | LA
Goodwill Industries of Akron | Q126844650 | OH
Goodwill Industries of Alaska | Q126844970 | AK
Goodwill Industries of Arkansas | Q126845113 | AR
Goodwill Industries of Ashtabula | Q126845266 | OH,PA
Goodwill Industries of Central Alabama | Q126845404 | AL
Goodwill Industries of Central East Texas | Q126845494 | TX
Goodwill Industries of Central Florida | Q126845603 | FL
Goodwill Industries of Central Illinois | Q126845692 | IL
Goodwill Industries of Central Michigan's   Heartland | Q126845869 | MI
Goodwill Industries of Central North   Carolina | Q126846187 | NC
Goodwill Industries of Central Oklahoma | Q126846292 | OK
Goodwill Industries Central Texas | Q126846425 | TX
Goodwill Industries of Dallas | Q126846545 | TX
Goodwill Industries of Delaware and   Delaware County | Q126846718 | DE,PA
Goodwill Industries of East Texas | Q126846860 | TX
Goodwill Industries of Eastern North   Carolina | Q126846961 | NC
Goodwill Industries of El Paso | Q126847215 | NM,TX
Goodwill Industries of Erie, Huron,   Ottawa, and Sandusky Counties | Q126849319 | OH
Goodwill Industries of Greater Cleveland   & East Central Ohio | Q126849523 | OH,WV
Goodwill Industries of Greater Detroit | Q126849679 | MI
Goodwill Industries of Greater Grand   Rapids | Q126849908 | MI
Goodwill Industries of Greater Nebraska | Q126850099 | NE
Goodwill Industries of Kansas | Q126850348 | KS
Goodwill Industries of Kentucky | Q126850555 | KY
Goodwill Industries of KYOWVA Area | Q126850683 | KY,WV
Goodwill Serving Lorain, Erie and Huron   Counties | Q126851048 | OH
Goodwill Industries of Michiana | Q126851288 | IL,IN,MI
Goodwill Industries of Middle Georgia and   the Central Savannah River Area | Q126851815 | GA,SC
Goodwill Industries of Middle Tennessee | Q126897617 | TN
Goodwill Industries of Mid-Michigan | Q126897626 | MI
Goodwill Industries of Mississippi | Q126897629 | MS
Goodwill Industries of New Mexico | Q126897661 | NM
Goodwill Industries of North Central   Pennsylvania | Q126897686 | PA
Goodwill Industries of North Central   Wisconsin | Q126897690 | WI
Goodwill Industries of North Florida | Q126897703 | FL
Goodwill Industries of Northeast Indiana | Q126897712 | IN
Goodwill Industries of Northeast Iowa | Q126897713 | IA
Goodwill Industries of Northeast Texas | Q126897716 | OK,TX
Goodwill Industries of Northeastern   Pennsylvania | Q126897718 | PA
Goodwill Industries of Northern Michigan | Q126897721 | MI
Goodwill Industries of Northwest North   Carolina | Q126897725 | NC
Goodwill Industries of Northwest Ohio | Q126897729 | OH
Goodwill Industries of Northwest Texas | Q126897737 | TX
Goodwill Industries of San Antonio | Q126897776 | TX
Goodwill Industries of South Mississippi | Q126897777 | MS
Goodwill Industries of South Texas | Q126897785 | TX
Goodwill Industries of Southeast Texas   and Southwest Louisiana | Q126897791 | LA,TX
Goodwill Industries of Southeastern   Louisiana | Q126897798 | LA
Goodwill Industries of Southeastern   Michigan | Q126897803 | MI
Goodwill Industries of Southern Ohio | Q126897825 | KY,OH
Goodwill Industries of Southwest Florida | Q126897867 | FL
Goodwill Industries of Southwest Oklahoma   and North Texas | Q126897870 | OK,TX
Goodwill Industries of Southwestern   Michigan | Q126897875 | MI
Goodwill Industries of Tenneva | Q126897882 | TN,VA
Goodwill Industries of the Berkshires and   Southern Vermont | Q126897889 | MA,VT
Goodwill Industries of the Greater   Chattanooga Area | Q126897902 | GA,TN
Goodwill Industries of the Kanawha Valley | Q126897947 | WV
Goodwill Industries of the Southern   Piedmont | Q126898051 | NC,SC
Goodwill Industries of Tulsa | Q126898054 | MO,OK
Goodwill Industries of Upstate/Midlands   South Carolina | Q126898063 | SC
Goodwill Industries of Wayne and Holmes   Counties | Q126898070 | OH
Goodwill Industries of West Michigan | Q126898107 | MI
Goodwill Industries of Zanesville | Q126898111 | OH,WV
Goodwill Industries Serving Southeast   Nebraska | Q126898116 | NE
Goodwill Industries Suncoast | Q126898121 | FL
Goodwill Industries-Knoxville | Q126898185 | TN
Goodwill Keystone Area | Q126898297 | PA
Goodwill Manasota | Q126898303 | FL
Goodwill North Central Texas | Q126898309 | TX
Goodwill of Central and Coastal Virginia | Q126898315 | VA
Goodwill of Greater Washington | Q126898322 | DC,MD,VA
Goodwill of Northern Wisconsin and Upper   Michigan | Q126898359 | MI,WI
Goodwill of South Central Ohio | Q126898562 | OH
Goodwill of South Central Wisconsin | Q126898573 | WI
Goodwill Southeast Georgia | Q126898584 | GA
Goodwill of Southern New England | Q126898594 | CT,MA,RI
Goodwill of Southwestern Pennsylvania | Q126898625 | PA
Goodwill of North Central West Virginia | Q126898673 | WV
Goodwill of the Heartland | Q126898699 | IL,IA
Goodwill of the Southern Alleghenies | Q126898764 | PA
Goodwill of Western & Northern   Connecticut | Q126898773 | CT
Goodwill of Western Missouri and Eastern   Kansas | Q126898783 | KS,MO
Goodwill of Western New York | Q126898787 | NY
Goodwill Rappahannock | Q126898798 | VA
Goodwill Serving Eastern Nebraska and   Southwest Iowa | Q126898806 | IA,NE
Goodwill Southern Los Angeles County | Q126898814 | CA
Goodwill West Texas | Q126898819 | TX
Goodwill-Easter Seals Minnesota | Q126898825 | MN,WI
Gulfstream Goodwill Industries | Q126898837 | FL
Heart of Texas Goodwill Industries | Q126898851 | TX
Horizon Goodwill Industries | Q126898859 | MD,PA,VA,WV
Licking/Knox Goodwill Industries | Q126898865 | OH
Marion Goodwill Industries | Q126898874 | OH
Memphis Goodwill | Q126898879 | MS,TN
Palmetto Goodwill | Q126898891 | SC
True North Goodwill | Q126898900 | MN,WI
Wabash Valley Goodwill Industries | Q126898920 | IL,IN
Youngstown Area Goodwill Industries | Q126898924 | OH,PA

**Comment by Snowysauce** [comment]
Marking as resolved by #9691. Feel free to request for the issue to be reopened if any parts are still unresolved.
