### ISSUE TITLE
Scope of Delta gas station chain is too broad

### ISSUE THREAD

**Issue by Snowysauce** [osmlab/name-suggestion-index#9678]
Delta (https://www.wikidata.org/wiki/Q62274661) is a gas station chain limited to the New York City/Tri-State area, but [its geolocation scope in the NSI](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=delta#delta-c5cf43) covers the entire United States. This is causing incorrect suggestions in OSM's iD editor for other small gas station chains with "Delta" in the name, such as Delta Sonic in upstate New York. Please narrow Delta's scope to New Jersey and downstate New York (e.g., NYC, Long Island, and the Lower Hudson Valley).

**Comment by Cj-Malone** [comment]
It can be done in this case, but not in every case. Similar brands overlap. iD has "Tag as not the same" for this reason.

![image](https://github.com/osmlab/name-suggestion-index/assets/10121513/df73a2f0-370d-4e53-b1b1-9edfaffdaa5f)

**Comment by Cj-Malone** [comment]
I've fixed Delta Sonic in OSM. Do you know what the website is for [Delta](https://www.wikidata.org/wiki/Q62274661)? I wanna check its area.

**Comment by Snowysauce** [comment]
I tried searching multiple times for a website to add to its Wikidata, but came up empty no matter what I tried as a query. Based on what I saw in the various searches, "Delta" appears to be a generic brand used by independently owned gas stations across New Jersey, New York City, and New York State's Long Island and Westchester County. Other than sharing the brand, there doesn't seem to be any common ties from one gas station to the next.

**Comment by Cj-Malone** [comment]
Other than a couple mistakes in AL and surrounding states, all the OSM ones seem to be in NJ, so I've switched it to there for now. It can be expanded if needed.

**Comment by bhousel** [comment]
Yeah they are very common in New Jersey near me, but they don't have a website or anything you can do to learn about them.  Pretty mysterious! 

The overpass query on nsi.guide is useful for finding all the various Delta gas stations.
https://nsi.guide/index.html?t=brands&k=amenity&v=fuel#delta-c5cf43

<img width="891" alt="Screenshot 2024-06-26 at 8 46 08 AM" src="https://github.com/osmlab/name-suggestion-index/assets/38784/7c17e948-4f89-4c13-814f-2802a6aa1237">
