### ISSUE TITLE
Add Norwegian brands

### ISSUE THREAD

**Issue by hmlb-no** [osmlab/name-suggestion-index#9719]
Hey i need help to add Kid Interiør into NSI.

The brand has ca 150 stores in Norway and ca 130 stores in Sweden, Finland and Estonia. So it is a Norwegian brand but has stores in other countrys.

The brand is a "Textiles and interiors" Market

So what tag should be used maybe this "Tag:shop=interior_decoration" OR "Tag:shop=household_linen" i am not sure yet. Tho every kid store in Norway is usining household_linen so i gusse that is the right wonne?

website: https://kid.no

Wikidata: Q127385156

**Comment by kjonosm** [comment]
We already have [Kid interiør](https://nsi.guide/index.html?t=brands&k=shop&v=interior_decoration&tt=Kid%20interiør#kidinterior-d55252) listed in NSI that refers to [Q109628199](https://www.wikidata.org/wiki/Q109628199).

**Comment by hmlb-no** [comment]
This realy started ween i found out that this [node](https://www.openstreetmap.org/node/7707621558) did not have NSI , i guess i should have done my research before posting this post but soory.

Also i Kid dose is the owner of the brand Hemtex (Q10521868), i gusse they do not run there own kid store but rather they run Hemtex under the ownership of the Kid corporation.

I am going to add all the kid stores in Norway that is missing so that this never happens again.

### **OK but here are som other stores in norway that can be added into NSI**

[sport1](https://www.sport1.no) is a sports store and has ca 200 stores in norway [List of shops](https://www.sport1.no/butikker) 

[Kitch'n](https://www.kitchn.no) (Q11980795) is a store where you can find every ting to get in your kitchen(it is in the name) and has ca 142 stores in Norway.

[Sportoutlet](https://sportoutlet.no/butikker) is a sports store with ca 80 stores in norway. [List of shops](https://www.sport1.no/butikker) 

[elon](https://www.elon.no) is a electronics shop in Norway with 82 stores [List of shops in Norway)(https://www.elon.no/butikker/storelist)
[Extra Leker](https://www.extra-leker.no) is a toys store with ca 20 stores in Norway. [List of Shops](https://www.extra-leker.no/butikker)

### Other shops
[DNB ASA](https://www.dnb.no)(Q80788) Is a Norwegian bank that is also in other countrys like Luxembourg, Sverige and Danmark [List of shops in Norway](https://www.dnb.no/om-oss/kontorer/norge)
[specsavers](https://specsavers.no) is in Norway and has 106 stores in norway. There should maybe be created a new wikidata item called "Specsavers Norway" or somthinings like that becuse it is a under organazation.  [List of shops](https://www.specsavers.no/finn-din-butikk/komplett-butikkoversikt)

**Comment by hmlb-no** [comment]
[kremmerhuset](https://kremmerhuset.no) is a interior_decoration company my source is this [node](https://www.openstreetmap.org/node/5137372085). The company has around 80 stores in norway i gusse.[List of Shops](https://kremmerhuset.no/butikker)

**Comment by hmlb-no** [comment]
[Feel](https://feel.no) is a interior_decoration company and has 46 stores in Norway[List of Shops](https://feel.no/Kategori/421/Avdelinger)

**Comment by hmlb-no** [comment]
Here are some norwegian shoes company and it looks like all of this company is owned by the same person because they all is linking to each other.
[List of shoes company in NSI](https://nsi.guide/index.html?t=brands&k=shop&v=shoes&cc=no)
[DNA shoes](https://www.dna-shoes.com) is shoes company that has 65 stores in Norway [List of shops in norway](https://www.dna-shoes.com/no/butikker)
[Eurosko](https://www.eurosko.com) is a shoes company that has 170 stores in norway[List of shops in norway](https://www.eurosko.com/no/butikker). This is alerady in NSI.
[Shoeday](https://www.shoeday.no/no) is a shoes company and has 22 stores in norway [List of shops in Norway](https://www.shoeday.no/no/butikker)
# Other Shoes company that is most likaly not owend by the same person
[skomani](https://skomani.no) is a shoes company and has 19 physical stores in norway [List of shops](https://skomani.no/butikker)
[lillevinkelsko](https://lillevinkelsko.no) is a shoes company and has 6 physical stores in norway [List of shops](https://lillevinkelsko.no/butikker)
[skoringen](https://www.skoringen.no)is shoe company and has 68 stores in norway [List of shops in norway](https://www.skoringen.no/finn-butikk)

**Comment by kjonosm** [comment]
Please create a Wikidata page for each brand you want to have listed in nsi, see [here](https://github.com/osmlab/name-suggestion-index/wiki/Editing-Wikidata) for instructions.

**Comment by kjonosm** [comment]
I changed the title as the original issue has been resolved.

**Comment by kjonosm** [comment]
- [ ] [sport1](https://www.sport1.no)
- [ ] [Kitch'n](https://www.kitchn.no)
- [ ] [Sportoutlet](https://sportoutlet.no/butikker)
- [ ] [elon](https://www.elon.no)
- [ ] [Extra Leker](https://www.extra-leker.no)
- [ ] [DNB ASA](https://www.dnb.no)
- [ ] [Feel](https://feel.no)
- [ ] [Bilxtra](https://bilxtra.no)
- [ ] [Kremmerhuset](https://kremmerhuset.no)
- [ ] [DNA shoes](https://www.dna-shoes.com)
- [ ] [Shoeday](https://www.shoeday.no/no)
- [ ] [skomani](https://skomani.no)
- [ ] [lillevinkelsko](https://lillevinkelsko.no)
- [ ] [skoringen](https://www.skoringen.no)

@hmlb-no I left specsavers as is. Feel free to create a separate wikidata item.
