### ISSUE TITLE
Common Businesses in India

### ISSUE THREAD

**Issue by bponkishore** [osmlab/name-suggestion-index#9757]
1. Archies ([Q4786843](https://www.wikidata.org/wiki/Q4786843))
2. Kohler ([Q6426036](https://www.wikidata.org/wiki/Q6426036))
3. Lakmé ([Q6479731](https://www.wikidata.org/wiki/Q6479731))
4. Louis Philippe ([Q18350510](https://www.wikidata.org/wiki/Q18350510))
5. Fastrack ([Q28164179](https://www.wikidata.org/wiki/Q28164179))
6. DBS Bank ([Q705417](https://www.wikidata.org/wiki/Q705417))
7. Repco Bank ([Q18394050](https://www.wikidata.org/wiki/Q18394050))
8. Sri Krishna Sweets ([Q7585868](https://www.wikidata.org/wiki/Q7585868))

**Comment by kjonosm** [comment]
Hi @bponkishore! Could you add the corresponding [`shop=*`](https://wiki.openstreetmap.org/wiki/Key:shop) types to your list above?

**Comment by bponkishore** [comment]
- [ ] Archies ([Q4786843](https://www.wikidata.org/wiki/Q4786843)) - [shop=gift](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgift)
- [ ] Kohler ([Q6426036](https://www.wikidata.org/wiki/Q6426036)) - [shop=bathroom_furnishing](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbathroom_furnishing)
- [ ] Lakmé ([Q6479731](https://www.wikidata.org/wiki/Q6479731)) - [shop=beauty](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbeauty)
- [ ] Louis Philippe ([Q18350510](https://www.wikidata.org/wiki/Q18350510)) - [shop=clothes](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dclothes)
- [ ] Fastrack ([Q28164179](https://www.wikidata.org/wiki/Q28164179)) - [shop=fashion_accessories](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfashion_accessories)
- [ ] DBS Bank ([Q705417](https://www.wikidata.org/wiki/Q705417)) - [amenity=bank](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbank) & [amenity=atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm)
- [ ] Repco Bank ([Q18394050](https://www.wikidata.org/wiki/Q18394050)) - [amenity=bank](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbank) & [amenity=atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm)
- [ ] Sri Krishna Sweets ([Q7585868](https://www.wikidata.org/wiki/Q7585868)) - [shop=confectionery](https://wiki.openstreetmap.org/wiki/Tag:shop=confectionery?uselang=en)
