### ISSUE TITLE
Add Cardzone Group, and the Brands it operates

### ISSUE THREAD

**Issue by ClarSco** [osmlab/name-suggestion-index#9785]
According to their [website](https://cardzoneltd.com/our-brands/), Cardzone Ltd. owns/operates 141 stores across the UK under the following brands:

- [x] Cardzone (60 stores)
- [x] Mooch (18 stores)
- [x] Paper Kisses (17 stores)
- [x] Hallmark (20 stores)
- [x] Yankee Candle (12 stores)
- [x] Card Centre (14 stores)

Of these, only [Hallmark](https://nsi.guide/index.html?t=brands&k=shop&v=gift&tt=hallmark) and [Yankee Candles](https://nsi.guide/index.html?t=brands&k=shop&v=candles&tt=yankee) have entries in the NSI.

**Comment by ClarSco** [comment]
Relevant Wikidata Items:

* Cardzone - https://www.wikidata.org/wiki/Q123019897
* Mooch - X
* Paper Kisses - X
* Hallmark - https://www.wikidata.org/wiki/Q1521910
* Yankee Candles - https://www.wikidata.org/wiki/Q8048733
* Card Centre - X

Relevant Wikipedia articles:
* Cardzone - X
* Mooch - X
* Paper Kisses - X
* Hallmark - https://en.wikipedia.org/wiki/Hallmark_Cards
* Yankee Candle - https://en.wikipedia.org/wiki/Yankee_Candle
* Card Centre - X

**Comment by Snowysauce** [comment]
I've opened a pull request to add the Cardzone brand to NSI as it easily meets the [suggested inclusion criteria](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case). As you mentioned, Hallmark and Yankee Candle are already in the NSI, and both are also already available for tagging in the UK.

That leaves the Mooch, Paper Kisses, and Card Centre brands, which may not have enough locations to be included in the NSI. I'll defer to the opinions of the more established maintainers when it comes to that topic.

As for Cardzone Group (the operator), adding it to the NSI in such a way that would address this issue would require (to my knowledge) adding two new categories that don't currently exist in the code: `operators/shop/gift` and `operators/shop/candles`. Again, I'll defer to the opinions of the more established maintainers as to whether these should be added (and whether my understanding of the code is correct).

**Comment by bhousel** [comment]
This sounds like it would cause the same issues as #9716
If we already have these as brands we shouldn't also have an entry under the operators tree for "Cardzone Group" as the operator.

**Comment by Snowysauce** [comment]
If I'm interpreting the comments at #9716 correctly, the plugins/editors using the NSI prioritize matching for brands prior to matching for operators, and only attempt to match for operators if there were no matching brands? It makes sense and I agree that this is the correct prioritization, but I didn't know that. For the OP, I guess that leaves three options:

- having Mooch, Paper Kisses, and Card Centre added as brands, which depends on another maintainer deeming them individually notable
- leaving the three brands out, and creating a "Cardzone Group" operator entry that would only match said brands (collectively 49 stores per the OP)
- the status quo: Cardzone, Hallmark, Yankee Candle in the NSI; Mooch, Paper Kisses, and Card Centre not in; no operator entry for Cardzone Group

Notes for the OP on option 2: either the Cardzone brand or the Cardzone Group operator would need a separate Wikidata item from [Q123019897](https://www.wikidata.org/wiki/Q123019897) as the `npm` operations used to build the NSI will produce a warning if the same QID is used in both the brand and operator trees in the same category (e.g., `brands/shop/gift` and `operators/shop/gift`).

**Comment by UKChris-osm** [comment]
I don't think we need to worry about the `operator` in this case at all, and focus purely on the `brands` individually. I'd be happy for the remaining three brands to be added as they are, as while they may not have a large number of stores, I think they still have enough value in them to be added individually.
