### ISSUE TITLE
New category request: operators/amenity/veterinary

### ISSUE THREAD

**Issue by Snowysauce** [osmlab/name-suggestion-index#9786]
This idea came to me earlier tonight while taking care of my cat. The operator I have in mind when making this request is [Thrive Pet Healthcare](https://www.wikidata.org/wiki/Q121438667), which runs more than 50 clinics in various cities across the US. I can't think of any other items for this category, but I suspect that's partly due to Thrive having a mini-monopoly over the local vet clinics.

**Comment by Snowysauce** [comment]
If there is support for this idea, I've created a [preliminary file for the category](https://github.com/Snowysauce/name-suggestion-index/blob/vets/data/operators/amenity/veterinary.json).

**Comment by UKChris-osm** [comment]
Would **Thrive** not fit in with the current [amenity / veterinary](https://nsi.guide/index.html?t=brands&k=amenity&v=veterinary) category?

**Comment by Snowysauce** [comment]
I have no idea how Thrive operates their clinics elsewhere, but here in Rochester, the vet offices owned by them have unique names and looks. Thrive's physical corporate presence in and outside the offices is so subtle that one has to really look for signs that the clinic is owned by a national entity and isn't an independent office. To me, that falls more in line with Thrive being an "operator" (akin to a library network where each individual library is distinct) than a "brand" (which makes me think of chains with strong common ties, like identical names or looks).
