### ISSUE TITLE
Combination of "transit" and {t} in OverviewInstructions.jsx generates odd text

### ISSUE THREAD

**Issue by Snowysauce** [osmlab/name-suggestion-index#9793]
This is a purely cosmetic issue, but it is an issue nonetheless. In `OverviewInstructions.jsx`, `t` is assigned the title of each of the four category trees (`brands`, `transit`, etc.). While the overview text for [nsi.guide](https://nsi.guide/index.html) holds up for all values of `t` other than `transit`, it kind of falls apart when `t` is `transit`. Examples:

- `t` = `brands`: "You can help us by adding **brands** to the index, matching **brands** to Wikidata identifiers, or [improving](https://nsi.guide/wikidata-warnings.htm) the **brands'** Wikidata pages."
- `t` = `transit`: "You can help us by adding **transit** to the index, matching **transit** to Wikidata identifiers, or [improving](https://nsi.guide/wikidata-warnings.htm) the **transit'** Wikidata pages." (Note the unneeded apostrophe after the last instance of transit)

The issue would be rectified IMO if `OverviewInstructions.jsx` used "transit networks" instead for all instances of `t` when `t` = `transit`. As a programmer, I know it'd be possible to carve out an exception that does exactly that, but I guess I'm wondering if anyone else thinks that the effort required is worth it.

**Comment by UKChris-osm** [comment]
I've added a branch called [tempt edit](https://github.com/osmlab/name-suggestion-index/tree/tempt-edit) that could do this, but I currently don't have access to NPM or GitHub Desktop, so if someone else can run `npm run appbuild` on the branch it'll highlight any errors that need amending.

**Comment by UKChris-osm** [comment]
I've tried out the above edit and deployed it to nsi.guide, what do you think @Snowysauce?
