### ISSUE TITLE
Addition of car charing infrastructure  service provider:  'Believ'

### ISSUE THREAD

**Issue by osm-spiregrain** [osmlab/name-suggestion-index#9795]
Could the 'Believ' brand (operated by Liberty Charge Limited) be added as an NSI entry for the UK?

Something like:

- operator:wikidata = Q129085023
- operator=Liberty Charge Limited
- brand:wikidata = Q129085075
- brand=Believ
- amenity=amenity=charging_station
- man_made=charge_point

Master template:   /brands/man_made/charge_point.json
matchNames: Libery Charge,Believ,Believe

logo - https://www.believ.com/wp-content/themes/gravity-global-child/assets/images/favicon/favicon.png ?

**Comment by Cj-Malone** [comment]
Logo would need to be added to Wikidata/Wikimedia Commons.
