### ISSUE TITLE
Bpost is in the file but not on the list?

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/name-suggestion-index#9805]
Hi, (it's been a bit since i've done NSI stuff, so maybe i'm just missing something obvious)
but I see that bpost is listed in this file: https://github.com/osmlab/name-suggestion-index/blob/2becb7928d5271b35506ebf9992f700666e8b331/data/operators/amenity/post_office.json#L158

but when i look at the generated list, i don't see it: https://nsi.guide/index.html?t=brands&k=amenity&v=post_office&tt=bpost

**Comment by thibaultmol** [comment]
(also side issue: I don't see bpost in the parcel lockers list atm)

**Comment by thibaultmol** [comment]
aaaah right, that's where I was getting confused. Should Bpost be listed in both brands and operators maybe?

**Comment by Dimitar5555** [comment]
It is possible but it might create a separate preset which will confuse mappers. Personally I would avoid having two entries for the same object.

**Comment by AntiCompositeNumber** [comment]
A single entry can only be in the `brands/` tree or the `operators/` tree, not both (this is enforced by the build script). This separation is only really useful for the maintenance of the Index and is largely ignored by data consumers. Most `amenity=post_office` entries are using `operator=`, though there are 25 entries using both `brand=` and `operator=` tagging, split between both files. This is a bit of a mess, but I don't see any problems with the `bpost` entry compared to the other `post_office` entries. If there's a desire to change `post_office` brand/operator tagging more broadly, that would be better handled in a different issue.

I'll add bpost as a parcel locker brand.
