### ISSUE TITLE
Make fitness station features add only 'fitness_station=*' tag

### ISSUE THREAD

**Issue by somehundred** [osmlab/name-suggestion-index#9810]
Currently whenever user chooses something that would belong in fitness station, iD editor adds three tags:

- fitness_station=*
- leisure=fitness_station
- sport=fitness

Make this recommendation add only `fitness_station=*` tag as `leisure=fitness_station` may already be mapped as an area, resulting in double-mapped feature.

By '*' I mean any value applicable to 'fitness_station' tag.

I'm new here so if this is the wrong repository, tell me which is the right one and move this issue if needed.

**Comment by kjonosm** [comment]
Hi @andris86! I guess you should report your issue at https://github.com/openstreetmap/id-tagging-schema
