### ISSUE TITLE
Do not force name for vending_machine excrement_bags

### ISSUE THREAD

**Issue by ThomDietrich** [osmlab/name-suggestion-index#9817]
Please see https://github.com/openstreetmap/iD/issues/10422

Looking at https://nsi.guide/index.html?t=brands&k=amenity&v=vending_machine&tt=excrement_bags the following brands have a wrongful suggestion for `name={brand name}`. 

The entries "belloo" and "Bravo" should be corrected to not have the `name` tag. Thank you

**Comment by sfkeller** [comment]
I'd suggest to remove the name tag explicitly also in the "[Search Overpass Turbo](https://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A100%5D%3B%0A(nwr%5B%22name%22%3D%22belloo%22%5D%3B)%3B%0Aout%20center%3B%0A%0A%7B%7Bstyle%3A%0Anode%2C%0Away%2C%0Arelation%0A%7B%20color%3Ared%3B%20fill-color%3Ared%3B%20%7D%0Anode%5Bamenity%3Dvending_machine%5D%2C%0Away%5Bamenity%3Dvending_machine%5D%2C%0Arelation%5Bamenity%3Dvending_machine%5D%0A%7B%20color%3Ayellow%3B%20fill-color%3Ayellow%3B%20%7D%0Anode%5Bamenity%3Dvending_machine%5D%5Bbrand%3Dbelloo%5D%5Bbrand%3Awikidata%3DQ98526006%5D%2C%0Away%5Bamenity%3Dvending_machine%5D%5Bbrand%3Dbelloo%5D%5Bbrand%3Awikidata%3DQ98526006%5D%2C%0Arelation%5Bamenity%3Dvending_machine%5D%5Bbrand%3Dbelloo%5D%5Bbrand%3Awikidata%3DQ98526006%5D%0A%7B%20color%3Agreen%3B%20fill-color%3Agreen%3B%20%7D%0A%7D%7D&R) taken e.g. from Belloo.
