### ISSUE TITLE
Guardian Pharmacies (AU) is rebranded as Amcal (AU)

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#9821]
https://sigmahealthcare.com.au/first-guardian-pharmacy-makes-the-successful-switch-to-amcal/#:~:text=Sigma%20recently%20invited%20all%20Guardian,value%20proposition%20for%20its%20customers.

https://www.wikidata.org/wiki/Q63367814 - needs adjusting
https://www.wikidata.org/wiki/Q63367373

**Comment by UKChris-osm** [comment]
Thank you @CloCkWeRX 👍
