### ISSUE TITLE
Defunct brand: Sumo Salad (AU)

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#9822]
https://en.wikipedia.org/wiki/Sumo_Salad

> On 11 March 2022, the Sumo Group again put itself into administration. Sumo Salad's core business appears to have failed to find a buyer and been wound up.

**Comment by UKChris-osm** [comment]
This should hopefully be picked up the next time `npm run wikidata` is run.

**Comment by Snowysauce** [comment]
The [NSI guide entry for Sumo Salad](https://nsi.guide/index.html?t=brands&k=amenity&v=fast_food&tt=sumo%20s#sumosalad-474d0a) has been updated.
