### ISSUE TITLE
Hilti

### ISSUE THREAD

**Issue by Mahabarata** [osmlab/name-suggestion-index#9823]
Currently there is a name suggestion for this company :
name=Hilti 
shop=hardware
brand=Hilti
brand:wikidata=Q1361530

the main tag seems wrong, see https://www.hilti.fr/content/hilti/E2/FR/fr/company/corporate-information/company-profile.html.
Or see https://en.wikipedia.org/wiki/Hilti

They don't sell "screws and bolts, nails, hooks and other metal materials as well as metal tools" that we find in a hardware shop (see [Tag:shop%3Dhardware](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhardware)). They mainly sell electric supplies.

shop=power_tools seems better.

Best regards.

**Comment by UKChris-osm** [comment]
Seems like a good idea, but I'll wait for others to chip in first.

**Comment by Oivo35** [comment]
I agree, also with the change for Hilti, because Hilti stores specialize in power tools. Hardware stores offer fastening, electrical or plumbing supplies instead.

**Comment by DnaX** [comment]
I'm agree too. Hilti it's a brand who sells their own power tools.
