### ISSUE TITLE
Change brand Cemex

### ISSUE THREAD

**Issue by Oivo35** [osmlab/name-suggestion-index#9853]
Please change brand [Cemex](https://nsi.guide/index.html?t=brands&k=shop&v=trade&tt=cem#cemex-dabec2) from shop=trade to landuse=industrial and industrial=concrete_plant. Cemex doesn't operate shops with building materials, but concrete plants, cement plants and quarries. And it operates worldwide, not only in France.

For concrete plants I suggest:

    {
      "displayName": "Cemex",
      "id": "cemex-dabec2",
      "locationSet": {"include": ["001"]},
      "tags": {
        "industrial": "concrete_plant",
        "landuse": "industrial",
        "operator": "Cemex",
        "operator:wikidata": "Q1053348"
      }
    },

For quarries:

    {
      "displayName": "Cemex",
      "id": "cemex-dabec2",
      "locationSet": {"include": ["001"]},
      "tags": {
        "landuse": "quarry",
        "operator": "Cemex",
        "operator:wikidata": "Q1053348"
      }
    },

**Comment by Snowysauce** [comment]
Addressed (resolved?) by https://github.com/osmlab/name-suggestion-index/commit/504c4d340b9faf1994c7f8004f47908e79be20d8
