### ISSUE TITLE
Duplicate cache key "amenity/social_facility/q14751117" in trees "operators" and "brands", check items: johanniterunfallhilfeev-9a82eb

### ISSUE THREAD

**Issue by AntiCompositeNumber** [osmlab/name-suggestion-index#9861]
```
⚠️   Warning - matchIndex errors:
----------------------------------------------------------------------
  `key/value/name` occurs multiple times in the match index.
  To resolve these, make sure the key/value/name does not appear in multiple trees
    (e.g. `amenity/post_office/ups` should not be both a "brand" and an "operator"
----------------------------------------------------------------------
Duplicate cache key "amenity/social_facility/q14751117" in trees "operators" and "brands", check items: johanniterunfallhilfeev-9a82eb
total 1
```
https://github.com/osmlab/name-suggestion-index/blob/0b1f7a9f7b477cd6ef595e32be5efbe829c9cdf4/data/operators/amenity/social_facility.json#L850-L859

https://github.com/osmlab/name-suggestion-index/blob/0b1f7a9f7b477cd6ef595e32be5efbe829c9cdf4/data/brands/amenity/social_facility.json#L384-L394

**Comment by AntiCompositeNumber** [comment]
Looking at https://overpass-turbo.eu/s/1QuR and https://overpass-turbo.eu/s/1QuS this looks more like an operator than a brand, but input from folks more familiar with it would be useful.

**Comment by kjonosm** [comment]
I would keep it as a brand. Johanniter-Unfall-Hilfe is divided into nine regional associations, which comprise over 200 local, district and regional branches, see https://www.johanniter.de/johanniter-unfall-hilfe/johanniter-unfall-hilfe-vor-ort/
These branches usually act as operators.
