### ISSUE TITLE
Add GigaCharger charging network

### ISSUE THREAD

**Issue by neau** [osmlab/name-suggestion-index#9892]
Please add a new entry for a charging network

```json
    {
      "displayName": "GigaCharger",
      "id": "gigacharger-??????",
      "locationSet": {"include": ["bg"]},
      "tags": {
        "amenity": "charging_station",
        "name": "GigaCharger",
        "operator": "Гигачарджър ЕООД",
        "operator:wikidata": "Q130044770"
      }
    },
```
I am not familiar with how to generate an ID, so please help me out here.

Wikidata:
https://www.wikidata.org/wiki/Q130044770
Website:
https://gigacharger.net/

**Comment by Dimitar5555** [comment]
There is no need to generate the id manually. Once the item is added to `data/.../something.json` file and after the build script is ran, the id gets automatically generated.
