### ISSUE TITLE
"Warzywniak" is Polish for greengrocer, "piekarnia" for bakery, not a brand or a shop name

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/name-suggestion-index#99]
https://github.com/osmlab/name-suggestion-index/blob/d4c1b8437d47d63c6344e448c4c937b42f7b432d/config/canonical.json#L25999

I think that this name should not appear as possible shop name, but I am not 100% sure.

I am 100% sure that it is not a brand.

**Comment by matkoniecz** [comment]
The same for https://github.com/osmlab/name-suggestion-index/blob/d4c1b8437d47d63c6344e448c4c937b42f7b432d/config/canonical.json#L17074 - "piekarnia" is Polish for "bakery".

**Comment by matkoniecz** [comment]
Sorry, only now I spotted

> I'm not quite ready to have people help yet

in https://github.com/osmlab/name-suggestion-index/issues/38#issuecomment-421463860

Let me know once PRs and further review will be useful

**Comment by bhousel** [comment]
Yes, PRs to `config/filters.json` are welcome 👍   don't worry about building anything, those instructions are not updated yet.
