### ISSUE TITLE
Defunct brand: Basic AG

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#9903]
Q809994
https://de.wikipedia.org/wiki/Basic_AG
> Die Basic Aktiengesellschaft Lebensmittelhandel (kurz: Basic AG; Eigenschreibweise: basic) war eine deutsche Handelskette von [Bio-Supermärkten](https://de.wikipedia.org/wiki/Biosupermarkt) mit Sitz in [München](https://de.wikipedia.org/wiki/M%C3%BCnchen), die 1997 gegründet wurde.

> Die 19 deutschen Filialen wurden 2023 von [Tegut](https://de.wikipedia.org/wiki/Tegut) gekauft.[[3]](https://de.wikipedia.org/wiki/Basic_AG#cite_note-3)

(Bought by Tegut)

**Comment by kjonosm** [comment]
The Wikidata element has been updated accordingly, see https://www.wikidata.org/wiki/Q809994
