### ISSUE TITLE
Defunct brand: ekono

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/name-suggestion-index#9916]
https://es.m.wikipedia.org/wiki/Ekono
https://www.wikidata.org/wiki/Q2842729

**Comment by kjonosm** [comment]
Hey @CloCkWeRX, thank you for sharing. I have updated the wikidata element accordingly. 

You can do this also yourself by adding the [`dissolved`](https://www.wikidata.org/wiki/Property:P576) property to the wikidata element. That marks these items as dissolved in NSI and prevents NSI from suggesting updates.
