### ISSUE TITLE
Research needed for: shop/bakery|Bäckerei Schmidt

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#992]
#### :thinking: We need help deciding what to do with "shop/bakery|Bäckerei Schmidt"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/bakery|Bäckerei Schmidt` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/bakery|Bäckerei Schmidt`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/bakery|Bäckerei Schmidt`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
based on https://forum.openstreetmap.org/viewtopic.php?pid=747375#p747375 and searching it seems to be a popular nonbrand name that is not generic

**Comment by Adamant36** [comment]
Uuummm, no. I'm going with https://www.schmidtgenuss.de/ Seems the forum isn't that reliable of a source. 

![Schmidt](https://user-images.githubusercontent.com/30259065/57134224-4b572f80-6d5a-11e9-9ccf-c13f8b716988.jpg)
