### ISSUE TITLE
Research needed for: shop/bakery|Bäckerei Schneider (Germany)

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#993]
#### :thinking: We need help deciding what to do with "shop/bakery|Bäckerei Schneider"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/bakery|Bäckerei Schneider` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/bakery|Bäckerei Schneider`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/bakery|Bäckerei Schneider`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by matkoniecz** [comment]
This one may be more complicated. There seems to be a brand with multiple shops - see https://www.schneiders-baeckerei.de/unsere-baeckereien.html?adress=Siegen but it is not covering all shops and according to https://forum.openstreetmap.org/viewtopic.php?pid=747375#p747375 it is also used by independent bakeries 

Ping @ENT8R as a local expert

**Comment by ENT8R** [comment]
The bakery at https://www.schneiders-baeckerei.de/unsere-baeckereien.html is really a chain. It operates mainly in the western part of Germany near the city of Siegen. Though I'm not really sure whether it should be named "Bäckerei Schneider" or "Schneider's Bäckerei". Judging from the information on their website I would say the last one is the right name.
And I just found another bakery named "Bäckerei Schneider" which is also a chain (also in western Germany and also in the area where the other bakery ("Schneider's Bäckerei") operates): https://www.baecker-schneider.de/ This one seems to have about 110 stores, whereas the other one ("Schneider's Bäckerei") has about 45 stores...
All other bakeries just share the same name but they are independent from each other. "Schneider" is just a really common family name in Germany...
