### ISSUE TITLE
Research needed for: shop/bakery|Büsch

### ISSUE THREAD

**Issue by bhousel** [osmlab/name-suggestion-index#994]
#### :thinking: We need help deciding what to do with "shop/bakery|Büsch"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/bakery|Büsch` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/bakery|Büsch`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/bakery|Büsch`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

**Comment by Adamant36** [comment]
Owned by Edeka

**Comment by matkoniecz** [comment]
https://edeka-wegner.de/baeckerei-buesch/ (?)

**Comment by Adamant36** [comment]
I think that's them. They are mentioned here in the Fachhandel table https://de.wikipedia.org/wiki/Edeka

![download](https://user-images.githubusercontent.com/30259065/57134071-c53ae900-6d59-11e9-98b1-4053b4a292e5.jpg)
