### ISSUE TITLE
Marks & Spencer Food supermarkets

### ISSUE THREAD

**Issue by codeinabox** [osmlab/name-suggestion-index#9971]
Marks & Spencer also operates supermarkets, for example their stores at Hackney Central and Stratford. They are often branded as M&S Food

**Comment by Snowysauce** [comment]
Are these different stores than [M&S Foodhall](https://github.com/osmlab/name-suggestion-index/blob/f08cedea8805e15ac12a778f629588c6a8a13787/data/brands/shop/supermarket.json#L4711)?

**Comment by Snowysauce** [comment]
In addition to M&S Foodhall, the NSI has an entry for [M&S Food](https://github.com/osmlab/name-suggestion-index/blob/6f752c712d46ee0a230162ddf933f27627a1bbbe/data/brands/shop/convenience.json#L3079) under `brands/shop/convenience`. Since it appears that the NSI has this brand covered already, I'm closing this issue as resolved.

**Comment by codeinabox** [comment]
Sorry, I meant to reply to this. In answer to your earlier question, yes these are different to their food halls, and much larger than their convenience stores - both in terms of size and items for sale.

According to recent headlines, they are the UK's fastest growing supermarket: https://www.telegraph.co.uk/business/2024/10/08/marks-spencer-uk-fastest-growing-supermarket/

**Comment by Snowysauce** [comment]
> Sorry, I meant to reply to this. In answer to your earlier question, yes these are different to their food halls, and much larger than their convenience stores - both in terms of size and items for sale.

In that case, you'll probably need to submit a pull request with the exact changes to be made. Given what's already in the NSI, I don't anticipate anyone will take on this concern on their own.

**Comment by Cj-Malone** [comment]
There is also just `name=M&S` `shop=convenience`. https://www.openstreetmap.org/way/416601711#map=19/51.531278/-0.124504

To complicate the matter further, they don't have good data on the specific stores, eg they think [this](https://www.openstreetmap.org/way/42710135) is a Simply Food.

They have a lot of store formats, I imagine the easiest way to improve this is preserveTags.
