### ISSUE TITLE
Add fuel stations Orlen express

### ISSUE THREAD

**Issue by Oivo35** [osmlab/name-suggestion-index#9973]
Hi, please add fuel stations chain Orlen express in Czech Republic, Germany and Slovakia. This brand is different from [Orlen](https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=orlen#orlen-5730fb) fuel stations. because Orlen express is self-serviced and open 24/7.

amenity=fuel
brand=ORLEN express
brand:wikidata=Q971649
name=Orlen express
opening_hours=24/7
self_service=yes

[{"include":["cz","de","sk"]}]

**Comment by Snowysauce** [comment]
How many Orlen express locations are there? I tried using their [fuel station locator](https://www.orlen.pl/en/for-you/fuel-stations?kw=&from=&to=&s=1398&wp=&dst=0) and filtering for 24-hour facilities, but the site doesn't appear to distinguish between the full line (Orlen) and express brands.

**Comment by Oivo35** [comment]
I found these numbers:
Slovakia - 40 stations
https://www.orlen.sk/stanice
Czechia - 18
https://www.orlen.cz/stanice
Germany - 17
https://www.star.de/orlen-express

**Comment by Snowysauce** [comment]
Thanks for the information. I've added the brand to the index.
