### ISSUE TITLE
Duplicate cache key "amenity/post_office/q7233983" in trees "operators" and "brands", check items: postalcorporationofkenya-56917c

### ISSUE THREAD

**Issue by Snowysauce** [osmlab/name-suggestion-index#9993]
https://github.com/osmlab/name-suggestion-index/blob/d68d091637637527d3333eb969e8960793172f2e/data/brands/amenity/post_office.json#L274-L284

https://github.com/osmlab/name-suggestion-index/blob/d68d091637637527d3333eb969e8960793172f2e/data/operators/amenity/post_office.json#L1123-L1132

Posting for community feedback as to which entry should be retained.

**Comment by UKChris-osm** [comment]
The entry in the `brand` tree seems wrong, as it simply uses the `brand` _post office_ rather than _Posta Kenya_.

**Comment by Snowysauce** [comment]
I elected to merge the two entries into the brands tree using the "Posta Kenya" name. The value from the operator entry ("Postal Corporation of Kenya") is apparently the formal name of the entity, and it was added as a `matchName` both for the benefit of editors and to satisfy the build script, which readded the entry otherwise.
